### DISCUSSION TITLE
Infinispan DNS_PING without Kubernetes

### DISCUSSION THREAD

**Discussion by tanadeau** [keycloak/keycloak#10210] [Archive]
Per https://www.keycloak.org/server/caching, DNS_PING is available, but it's named `kubernetes`. I'm confused as normal DNS_PING can be used without kubernetes such as with AWS ECS and AWS service discovery. Is it possible to use DNS_PING in that situation with the Quarkus distribution?

**Comment by viyullas** [comment]
I would like to know this too.
We are currently using JDBC_PING wirh wildfly distribution but since we moved to ECS we are having some problems with it.

**Comment by nxadm** [comment]
This works for me  for DNS ping on Nomad (with Consul for container DNS):
```sh
KC_CACHE=ispn
KC_CACHE_STACK=kubernetes
JAVA_OPTS_APPEND="-Djgroups.dns.query=YOUR_CONTAINER_DNS_SERVICENAME"
```

Addition 1:
The DNS ping port changed on Keycloak 17: it's now 7800. Adapt your firewalls accordingly.

Addition 2:
When using running a Keycloak cluster on IPv6, Infinispan used the IPv6 HW address instead of the public one, breaking the cluster (some nodes joint, some not). This is the fix:
```
JAVA_OPTS_APPEND="-Djgroups.bind_addr=GLOBAL -Djgroups.dns.query=YOUR_CONTAINER_DNS_SERVICENAME"
```

**Reply by tanadeau** [reply]
Thanks! I'll give that a try.

**Reply by armujahid** [reply]
I am also using same approach with e.g. `JAVA_OPTS_APPEND=-Djgroups.dns.query=keycloak-headless.default.svc.cluster.local`
Note that service should be headless (with clusterIP: None). Otherwise it won't return POD IPs.

**Reply by nxadm** [reply]
> Addition 2: When using running a Keycloak cluster on IPv6, Infinispan used the IPv6 HW address instead of the public one, breaking the cluster (some nodes joint, some not). This is the fix:
> 
> ```
> JAVA_OPTS_APPEND="-Djgroups.bind_addr=GLOBAL -Djgroups.dns.query=YOUR_CONTAINER_DNS_SERVICENAME"
> ```

If someone from the Keycloak team is watching, should we convert this into a bug report? I think only ipv6 users are hit by this.

**Comment by epuronta** [comment]
Hijacking this thread to contribute my findings. We are running Keycloak 17 in Docker Swarm and have hit a number of hurdles getting Keycloak to cluster properly. Hopefully these can help someone else find their way. Generally, I feel these are things that I should not have to figure out or at least solve this way, but here we are.

**Pitfall 1: Multiple networks, choosing listening address**

If your containers are attached to multiple networks (say, one for cluster communication and one for ingress traffic) there's no telling which network Infinispan/JGroups chooses for clustering. Docker networks are not ordered deterministically (see https://github.com/moby/moby/issues/25181) so instructing JGroups to bind to `eth0` for example will not work. Using JGroups speciality `match-address` does the trick, however.

I resorted to the following solution:
- Export the subnet mask before deploying the stack
  - `export KC_CUSTOM_SUBNET=$(docker network inspect MY_CLUSTER_NETWORK --format "{{ (index .IPAM.Config 0).Subnet }}"`)
  - This returns subnet like `10.10.0.0/24`
- Have a custom `entrypoint.sh` in Keycloak image that reads the subnet mask and transforms it to a wildcard format expected by JGroups
  - Massage the CIDR mask (my rough script as an example below)
  - Pass it as Java option: `export JAVA_OPTS_APPEND="$JAVA_OPTS_APPEND -Djgroups.bind_addr=match-address:$NETWORK"`

```bash
 if [[ -z $KC_CUSTOM_SUBNET ]]; then 
        log "INFO" "KC_CUSTOM_SUBNET not set"
        return
    fi
    
    # Extract the CIDR block
    MASK=$(echo $KC_CUSTOM_SUBNET | cut -d/ -f 2)

    # We only deal in round blocks
    case "$MASK" in
        "8")
            CUT=1
            ;;
        "16")
            CUT=2
            ;;
        "24")
            CUT=3
            ;;
        *)
            echo "Invalid KC_CUSTOM_SUBNET. Expected /8, /16 or /24"
            exit 1
            ;;
    esac

    # Extract the appropriate number of ip segments
    NETWORK=$(echo $KC_CUSTOM_SUBNET | cut -d/ -f 1 | cut -d. -f "-$CUT")
    # Add the expected wildcard
    NETWORK="$NETWORK.*"

    JAVA_OPT="-Djgroups.bind_addr=match-address:$NETWORK"

    export JAVA_OPTS_APPEND="$JAVA_OPTS_APPEND $JAVA_OPT"
    
    log "INFO" "Added bind address to JAVA_OPTS_APPEND $JAVA_OPTS_APPEND"
```


**Pitfall 2: DNS resolution**

When using Docker Swarm DNS, there are a lot of options for resolving Keycloak peers via DNS. Suppose you're running service `keycloak` that is attached to networks `net-iam` and `net-ingress`. We're always passing the DNS query in via `jgroups.dns.query=$QUERY` as specified in Keycloak docs.

- Initially you'll just set `QUERY=keycloak`. If you're running `endpoint_mode: dnsrr` this may sort-of work, but in  default `endpoint_mode: vip` this only returns a single virtual IP for the service, not the actual nodes
- After further digging, you'll discover the `QUERY=tasks.keycloak` syntax, which actually returns the IPs of the individual workers. This works well, until you mix in multiple networks. In that case, your DNS results may reference any IP and network the container is attached to, not necessarily the one you're listening on (see Pitfall 1).
- Finally, using `QUERY=tasks.keycloak.net-iam` gets you the actual workers in the correct network.


To solve both of these challenges, I end up with several layers:
- Keycloak image with custom entrypoint handling the subnet
- Stack deploy script that exports the `SUBNET` before running `docker stack deploy`
- Compose file passed to deploy that
  - Passes the `SUBNET` to Keycloak
  - Hardcodes (well, there's another layer here really..) the DNS query to `tasks.MYSTACKNAME_keycloak.MYNETWORK`

**Reply by mspiess** [reply]
Thank you @epuronta very much for sharing this! `tasks.keycloak.NETWORK` did not work for me, so I went a different route: Specify an address for the network. That way I can avoid the additional layers you mentioned. See this compose file for an example:
```yml
version: "3.9"

networks:
  keycloak-net:
    external: false
    driver: overlay
    ipam:
      config:
        - subnet: "10.0.2.0/24"
        
services:
  keycloak:
    command: [ "start", "--optimized", "-Djgroups.dns.query=tasks.keycloak", "-Djgroups.bind_addr=match-address:10.0.2.*" ]
    networks:
      keycloak-net:
        ipv4_address: 10.0.2.12
    deploy:
      replicas: 3
      endpoint_mode: dnsrr
      # ... rest omitted
```

**Reply by epuronta** [reply]
Great input @mspiess. Your way definitely makes more sense if you manage the network in the same compose file.

**Reply by florian-forestier** [reply]
A bit late, but @epuronta, you dropped this: 👑

I was desperate because I thought my only option was to use JDBC_PING and all the backwards it has. Thanks a lot for the sharing!

**Reply by nicolabeghin** [reply]
thanks @mspiess your solution is the cleanest found on the whole internet! :D thanks a lot

**Comment by bdoublet91** [comment]
Hi,
Thanks a lot @epuronta and @mspiess.
Like @mspiess, tasks.keycloak.NETWORK doesn't work for me in swarm. I didn't find any documentation about this docker dns record ?

I use this configuration and it worked.
```
command: [ "start", "--optimized", "-Djgroups.dns.query=tasks.keycloak", "-Djgroups.bind_addr=match-address:10.0.2.*" ]
```

I had to remove my healthcheck container because the dns records of container are created when the container is healthy. However the distributed cache registration was made before the container get heallthy status so tasks.keycloak  resolve to the container Ips after the distributed cache registration and created each one a cluster....

To be clear with a healthcheck:
```
                  Healthcheck failed             (single cluster)               Healthcheck failed       Healthcheck success
Keycloak starting --------------------> keycloak distributed cache registration -----------------------> keycloak running
                  tasks.keycloak empty                                          tasks.keycloak empty     tasks.keycloak list containers IPs
```

Without a healthcheck
```
                  Healthcheck success                              (Same cluster)               
Keycloak starting ---------------------------------> keycloak distributed cache registration -----> keycloak running
                  tasks.keycloak list containers IPs                                          
```

I let you my full docker stack if it can help some people :)

I create the docker network outside of the docker stack
```
docker network create --driver overlay --subnet 10.0.12.0/24 --attachable keycloak-cluster
```

```
version: '3.8'

networks:
  keycloak-cluster:
    external: true
  traefik-public:
    external: true

services:
  keycloak-cluster:
    image: ${REGISTRY_DOMAIN}/keycloak:20.0.3
    command: start --http-enabled true --http-relative-path / --http-host 0.0.0.0 --http-port 8080 --hostname-strict false --log-level info --proxy edge --metrics-enabled true --health-enabled true --features scripts --db postgres --db-schema public --db-url-host **** --db-url-port **** --db-username **** --db-password **** --db-url-database keycloak --health-enabled=true --metrics-enabled=true --cache-stack=kubernetes --cache=ispn -Djgroups.dns.query=tasks.keycloak-cluster -Djgroups.bind_addr=match-address:10.0.12.*
    # healthcheck:
    #   test: ["CMD", "curl", "-fsq", "http://0.0.0.0:8080/realms/master"]
    #   start_period: 10s
    #   interval: 30s
    #   retries: 3
    #   timeout: 5s
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=changeme
    networks:
      - traefik-public
      - keycloak-cluster
    # ports:
    #   - 8080:8080
    deploy:
      update_config:
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr
      resources:
        limits:
          memory: 1024M
          cpus: '1.5'
        reservations:
          memory: 256M
          cpus: '0.5'
      # labels:
      #   - < your traefik conf >
```


```
2023-04-26 12:07:43,228 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [11c3d6d2de4d-40743|13] (4) [11c3d6d2de4d-40743, c61471572163-61224, c643916213ee-53912, 470d271fd582-44621]
2023-04-26 12:07:43,236 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `470d271fd582-44621`, physical addresses are `[10.0.12.41:7800]`
```

Do you have a clue to enable a healhtcheck and keep the distributed cache registration working ?

Thanks for your help
