### DISCUSSION TITLE
Creation of Admin User with environment variables

### DISCUSSION THREAD

**Discussion by Coding-Mike** [keycloak/keycloak#10317] [Archive]
Hi,

until version 16.1 I used the following Environment Variables in kubernetes for the docker image to create the admin user:

```
- name: KEYCLOAK_USER
          valueFrom:
            secretKeyRef:
              key: admin-user
              name: passwords
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              key: admin-pw
              name: passwords
```
How can this be achived with the new version.

Thanks in advance
Kind regards
Michael
