### DISCUSSION TITLE
docker-compose example and new quarkus distribution

### DISCUSSION THREAD

**Discussion by miguelcobain** [keycloak/keycloak#10366] [Archive]
All the examples in the repository seem to use the legacy distribution of keycloak. 
Can someone point me in the right direction?
I believe I need the auto-build option, but not sure how to do it from a docker-compose file.

Thank you.

**Comment by jsurkont** [comment]
I'm trying to run the new quarkus distribution in docker swarm. I'm not sure if that would work exactly the same in compose, but using the `["/opt/keycloak/bin/kc.sh", "start", "--auto-build"]` command works in swarm. Maybe you'll find it helpful.

**Comment by Nillth** [comment]
you may need to tweak them a little but they are working for me.
create two dir's data & postgres in the directory with your docker-compose and put the keystores in the data dir.
(instructions in the note)

[docker-compose.yml.txt](https://github.com/keycloak/keycloak/files/8116924/docker-compose.yml.txt)
[env.txt](https://github.com/keycloak/keycloak/files/8116927/env.txt)

**Comment by kresnasatya** [comment]
Hi @miguelcobain, here's docker-compose that I use for Keycloak Quarkus Distribution for development mode along with Postgres. This docker-compose also include openldap. If you don't need it then you can remove it.

https://raw.githubusercontent.com/satyakresna/sso-simulation/master/docker-compose.yml

**Reply by yougui68** [reply]
Hi Satyakresna, thank you for the post, but I was wondering how did you manage importing users, roles , realms... in docker-compose?
thank you in advance

**Reply by kresnasatya** [reply]
Hi @yougui68, I don't know about that. What I do just open Keycloak Admin Console and import from it.

**Reply by pehunka** [reply]
Hi @yougui68 I'm using following line in my docker compose. Env variable came from the official documentation for the Keycloak image on dockerhub.


```
volumes:
      - ./keycloak-assets:/opt/jboss/keycloak/imports
      
environment:
     - KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/my-realm.json
```

, where the path is a bind mount between an image and my host machine. I have created my-realm.json by using export feature in Keycloak and just save it

**Comment by armujahid** [comment]
This is the docker-compose file that I use for theme development with keycloak 17. You can change it as per your needs.

```
version: "3"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:17.0.0
    volumes: 
      - ./themes/sometheme/:/opt/keycloak/themes/sometheme/
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
    ports:
      - 8080:8080
      
```
