### DISCUSSION TITLE
specify image version for Keycloak with keycloak-operator

### DISCUSSION THREAD

**Discussion by xSuiteHaroonButt** [keycloak/keycloak#10622] [Archive]
Hello, we need a specific image for keycloak, but I don't understand how to specify it with the keycloak-operator. I deploy the 16.1.0 Operator, but need the `quay.io/keycloak/keycloak:16.1.1` Keycloak image. Can I somehow specify a image?

Thanks for any assistance

**Comment by xSuiteHaroonButt** [comment]
For the next one looking. You can specify the image with a variable in the `operator` not in the `keycloak` itself.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: keycloak-operator
  template:
    metadata:
      labels:
        name: keycloak-operator
    spec:
      serviceAccountName: keycloak-operator
      containers:
        - name: keycloak-operator
          image: quay.io/keycloak/keycloak-operator:16.1.0
          command:
          - keycloak-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "keycloak-operator"
            - name: RELATED_IMAGE_KEYCLOAK_INIT_CONTAINER
              value: quay.io/keycloak/keycloak-init-container:16.1.1
            - name: RELATED_IMAGE_KEYCLOAK 
              value: quay.io/keycloak/keycloak:16.1.1
```
