### DISCUSSION TITLE
Differences between zip project and the container setting up the initial user

### DISCUSSION THREAD

**Discussion by glats** [keycloak/keycloak#11045] [Archive]
I see a difference in the initial configuration between the project I download from the official keycloak website and the image I download from quay.io
When I download the zip with the project and start it (./bin/kc.sh start-dev) I get a form to create my first user. 

![Captura de Pantalla 2022-03-31 a la(s) 19 02 54](https://user-images.githubusercontent.com/4707766/161171061-4635e299-5927-487f-903f-22e969a8d0d4.png)
![Captura de Pantalla 2022-03-31 a la(s) 19 03 00](https://user-images.githubusercontent.com/4707766/161171081-239e8437-863e-4d46-9626-b177338953e9.png)

On the other hand, when I launch a container based on the latest keycloak image, the form does not appear and sends you to a url (/auth) that no longer exists in the quarkus version.

```
version: "3.8"
services:
  keylcoak:
    image: 'quay.io/keycloak/keycloak:17.0.1'
    ports:
      - "8080:8080"
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
```

![2022-03-31_19-03](https://user-images.githubusercontent.com/4707766/161171092-a2ca3caa-65f8-4df2-8295-69e924dbb03c.png)
![Captura de Pantalla 2022-03-31 a la(s) 19 04 09](https://user-images.githubusercontent.com/4707766/161171102-c1b20af9-0606-4184-aead-744ef4ddf092.png)

Why this difference? is there any option to create the initial user through this form in the container?
