### DISCUSSION TITLE
Setup Keycloak X using Operator with Istio as reverse proxy

### DISCUSSION THREAD

**Discussion by svilenvul** [keycloak/keycloak#11324] [Archive]
Hi here, 

We are having a setup of Keycloak running in Kubernetes in the Istio Service mesh.
Istio Service mesh is terminating SSL and routing to the Keycloak pod.

Currently we cannot find the appropriate settings to configure Keycloak so that:
- Users can login with the public URL (https://example.com/auth)
- Administrators can make a port-forward and login with (http://localhost:8080)

I have tried the following settings for the Keycloak operator :
  ```
  serverConfiguration:
    - name: http-enabled
      value: 'true'
    - name: proxy
      value: 'passthrough'
  hostname: INSECURE-DISABLE
  tlsSecret: INSECURE-DISABLE
```

The result is that:
- Users can login with the public URL (https://example.com/auth)
- Administrators can not port forward and login with http://localhost:8080 as all the URLs are rewritten to https://localhost:8080

Can someone help us with the setup?

**Comment by jnodorp-jaconi** [comment]
Adding
```
  serverConfiguration:
    [...]
    - name: hostname-strict-https
      value: "false"
```
worked for me.
