### DISCUSSION TITLE
Setup for autonomous DB based cluster in operator

### DISCUSSION THREAD

**Discussion by stevefan1999-personal** [keycloak/keycloak#11821] [Feedback]
Oracle Autonomous DB is wallet based and hence needs TNS_ADMIN to be set to a certain path like `/etc/secrets/oracle/`. 

I've uploaded the entire wallet to K8S as secret (as it definitely is), but there is no way to extract the secret to `/etc/secrets/oracle/` without using `unsupported` 

Also, it doesn't seems to have a way to set environmental variables without using `unsupported` in the operator as well

**Comment by stevefan1999-personal** [comment]
Here's a sample configuration for anyone interested:
```yaml
---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  serverConfiguration:
    - name: db
      value: oracle
    - name: db-url
      value: jdbc:oracle:thin:@apps_medium?TNS_ADMIN=/etc/secrets/oracle/
    - name: db-username
      secret:
        key: DB_USER
        name: keycloak-db
    - name: db-password
      secret:
        key: DB_PASSWORD
        name: keycloak-db
  unsupported:
    podTemplate:
      spec:
        containers:
          - volumeMounts:
              - mountPath: /etc/secrets/oracle
                name: oracle
                readOnly: true
            env:
              - name: TNS_ADMIN
                value: /etc/secrets/oracle/
        volumes:
          - name: oracle
            secret:
              secretName: oracle-app
```
Under my test this configuration successfully seeded a Keycloak X setup in my Oracle Autonomous DB. I do have to say it is weird to see everything in...Capital letters.

This setting assumes `/etc/secrets/oracle`, and thus the `oracle` secret to contain the `tnsname.ora` and friends from Oracle Autonomous Database in the wallet you downloaded from. I just uploaded all of them in a single K8S secret. The reason to use `db-url` is that TNS names are not your typical connection string, as they are substitutable to subject to extra configurations. 


Unfortunately, it seems like https://github.com/keycloak/keycloak/blob/e3ece8244fff0206b029b9539257fdf2626b6c13/quarkus/config-api/src/main/java/org/keycloak/config/database/Database.java#L154 mandates traditional connection string format so we need to override it. Oddly enough it seems like `TNS_ADMIN` environmental variable alone doesn't have any effects, so I also have to add it as a query option. So `TNS_ADMIN` as an environmental variable seems redundant (since the JDBC URL already specified the location) but is kept for defense purposes.
