### DISCUSSION TITLE
Install custom themes with Quarkus on k8s

### DISCUSSION THREAD

**Discussion by hausanstreicha** [keycloak/keycloak#11846] [Archive]
Hi, I would like to switch from WildFly to Quarkus, but right now I don't know what's the best way to install custom themes, besides building your own docker image.

With WildFly you were able to set extensions in the custom resource (as shown [here](https://www.keycloak.org/docs/latest/server_installation/index.html#_operator-extensions)). I'm not able to find a similar solution for Quarkus. 

Is there some documentation I missed to install custom themes with Quarkus on k8s?

Thanks for your help in advance!

**Comment by andreaTP** [comment]
Hi @hausanstreicha ! Thanks for reaching out!

[Here](https://github.com/keycloak/keycloak/issues/10835) we actually removed the support for extensions because we consider that mechanism not well suited for production environments.

By contrast, we encourage building custom Docker images, and [here](https://github.com/keycloak/keycloak/pull/11025) we properly documented the process.

Do you have any compelling use case where building a custom docker image is not viable/convenient?

**Reply by michaelkuechler** [reply]
@andreaTP a compelling use case i found:

a new image is always treated like a major deployment by keycloak operator (i.e. drain cluster to 1 node, run migration, scale up again). if i wanted to make a minor/patch release - or even changing a pixel in the theme(!) - using that approach, it turns that into a major release operation, which is totally unnecessary IMO.

**Comment by hausanstreicha** [comment]
Hi @andreaTP, thank you for your quick response and help!

My main reason for using extensions was convenience and simplicity to be honest.

I have another question regarding the migration and setting a relative path. Right now, I don't know, if this is a bug or missconfiguration on my side. I opened an issue [here](https://github.com/keycloak/keycloak/issues/11812). Do you happen to have an idea?

Thanks again for your help in advance!

**Comment by andreaTP** [comment]
> My main reason for using extensions was convenience and simplicity to be honest.

I see, I hope that the benefits of using immutable images and improving dramatically startup time outweigh the convenience.

Regarding the issue, I answered there already 🙂  👍  thanks for filing it!

**Comment by fabland** [comment]
I just saw the comment on the https://www.keycloak.org/operator/customizing-keycloak: 

> Note:
> Using custom images, every build time configuration passed through the serverConfiguration key will be ignored.

So what is the recommended way to be able to use an extension like the metrics extension and a custom theme like in the example here https://www.keycloak.org/server/containers "Building your optimized Keycloak docker image", while still being able to use the server settings options from the new Kubernetes Keycloak CRD (spec.serverConfiguration)?

**Reply by andreaTP** [reply]
> build time configuration

the sentence refers to the fact that you won't be able to use ["build options"](https://www.keycloak.org/server/all-config?f=build) as they are going to be ignored but you can freely use [normal configurations](https://www.keycloak.org/server/all-config?f=config).

**Reply by fabland** [reply]
Thanks for clarifying that

**Comment by jaymberry** [comment]
Hi, If I build a custom image, how do I get OLM installed operator to use it?

**Reply by andreaTP** [reply]
You can specify it in the CR `.spec.image` field as mentioned here: https://www.keycloak.org/operator/customizing-keycloak

**Reply by jaymberry** [reply]
It does not seem to recognize this.

Here is my process:
1. $ kubectl create -f https://raw.githubusercontent.com/operator-framework/operator-lifecycle-manager/master/deploy/upstream/quickstart/crds.yaml 
2. $ kubectl create -f https://raw.githubusercontent.com/operator-framework/operator-lifecycle-manager/master/deploy/upstream/quickstart/olm.yaml 
3. $ kubectl apply -f operator-keycloak.yaml 
4. $ kubectl apply -f crd-keycloak.yaml

Error output:
```
error: error validating "crd-keycloak.yaml": error validating data: ValidationError(Keycloak.spec): unknown field "image" in org.keycloak.v1alpha1.Keycloak.spec; if you choose to ignore these errors, turn validation off with --validate=false
```

$ cat operator-keycloak.yaml 
```
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: operatorgroup
spec:
  targetNamespaces:
  - default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-keycloak-operator
spec:
  channel: alpha
  name: keycloak-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
  installPlanApproval: Automatic
```

$ cat crd-keycloak.yaml
```
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: mykeycloak
  labels:
    app: mykeycloak
spec:
  instances: 1
  image: quay.io/keycloak/keycloak:18.0.0
  externalAccess:
    enabled: True
```
