### DISCUSSION TITLE
How to configure a custom TCPPING stack?

### DISCUSSION THREAD

**Discussion by jean-christophe-manciot** [keycloak/keycloak#11981] [Q&A] [answered]
keycloak 18.0.0

With:
```
JGROUPS_DISCOVERY_EXTERNAL_IP=172.21.1.1
JGROUPS_DISCOVERY_PROTOCOL=TCPPING
JGROUPS_DISCOVERY_PROPERTIES=initial_hosts="172.21.1.1[7600],172.21.1.2[7600]"
```
the keycloak server constantly tries to send discovery requests to /228.6.7.8:46655.

Is there any way to prevent this behavior even when the other cluster member(s) is/are not accessible?

**Comment by DmitryZ-outten** [comment]
Hello! I have encountered the same issue. It looks like Keycloak version 18 does not support the old configuration with TCPPING and  JGROUPS. And by default is using multicast.

I have restored the TCPING configuration in the following way:
* Took the default Infinispan XML file: https://github.com/keycloak/keycloak/blob/bf0f3d605c9ad73f0c0a5efb0534164e0fde24de/quarkus/runtime/src/main/resources/cache-ispn.xml
* Adjusted it by adding the jgroups section with tcpping stack. And specify stack for the transport
```
    <jgroups>
        <stack name="tcpping" extends="tcp">
          <TCP external_addr="${env.KC_EXTERNAL_ADDR}" bind_addr="${env.KC_BIND_ADDR}" bind_port="${env.KC_BIND_PORT}" />
          <TCPPING initial_hosts="${env.KC_INITIAL_HOSTS}"
                   max_dynamic_hosts="0"
                   port_range="0"
                   stack.combine="REPLACE"
                   stack.position="MPING"/>
        </stack>
    </jgroups>

    <cache-container name="keycloak">
        <transport lock-timeout="60000" stack="tcpping" />
```
* Add the adjusted XML file to the following dir: /opt/keycloak/conf/my-cache-ispn.xml
* Set the environment variable: KC_CACHE_CONFIG_FILE=my-cache-ispn.xml 
* Build Keycloak with: `/opt/keycloak/bin/kc.sh build`
* Define your new environment variables: 
```
KC_EXTERNAL_ADDR=172.21.1.1
KC_BIND_ADDR=172.21.1.1
KC_BIND_PORT=7600
KC_INITIAL_HOSTS="172.21.1.1[7600],172.21.1.2[7600]"
```
* Start the Keycloak: `/opt/keycloak/bin/kc.sh start`
* In the Log you should see the following message, which indicate that you are using the correct configuration:
```
[org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN` with stack `tcpping`
```
* After that in the log you should see members of the cluster

Useful links:
https://www.keycloak.org/server/caching
https://keycloak.discourse.group/t/infinispan-tcpping-discovery-in-quarkus-distribution/15375

**Comment by jean-christophe-manciot** [comment]
@DmitryZ-outten 

I've tried your suggestion with the latest ```keycloak 21.1.1``` and by removing the cache-stack setting from the configuration file (as indicated by https://www.keycloak.org/server/caching). 
You must have omitted some configuration detail(s) because it fails with ```Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!```:

```
2023-05-12 16:15:24,046 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: kc.example.com, Strict HTTPS: true, Path: <request>, Strict BackChannel: true, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: true
2023-05-12 16:15:27,178 INFO  [org.infinispan.SERVER] (keycloak-cache-init) ISPN005054: Native IOUring transport not available, using NIO instead: io.netty.incubator.channel.uring.IOUring
2023-05-12 16:15:27,296 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
2023-05-12 16:15:27,355 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2023-05-12 16:15:27,390 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2023-05-12 16:15:27,953 WARN  [io.quarkus.vertx.http.runtime.VertxHttpRecorder] (main) The X-Forwarded-* and Forwarded headers will be considered when determining the proxy address. This configuration can cause a security issue as clients can forge requests and send a forwarded header that is not overwritten by the proxy. Please consider use one of these headers just to forward the proxy address in requests.
2023-05-12 16:15:27,968 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2023-05-12 16:15:27,993 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
2023-05-12 16:15:28,110 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
```

Have you actually tried your solution and can you share your log with 21.1.1?

**Comment by jean-christophe-manciot** [comment, marked as answer]
Solved by starting with the ```--optimized``` option as shown [here](https://github.com/keycloak/keycloak/issues/20397#issue-1712338511).

**Comment by igloo777** [comment]
The only config that enabled unicast for me between 2 datacenters:

```xml
    <jgroups>
        <stack name="tcpping" extends="tcp">
          <TCP external_addr="${env.KC_EXTERNAL_ADDR}" bind_port="${env.KC_BIND_PORT}" stack.combine="COMBINE" />
          <TCPPING initial_hosts="${env.KC_INITIAL_HOSTS}"
                   port_range="0"
                   stack.combine="REPLACE"
                   stack.position="MPING"/>
          <VERIFY_SUSPECT timeout="1500"  />
          <pbcast.NAKACK2 use_mcast_xmit="false"
                          discard_delivered_msgs="false"/>
          <UNICAST3/>
          <pbcast.STABLE stability_delay="1000" desired_avg_gossip="50000"
                         max_bytes="400000"/>
          <pbcast.GMS print_local_addr="true" join_timeout="2000"/>
        </stack>
    </jgroups>

    <cache-container name="keycloak">
        <transport lock-timeout="60000" stack="tcpping"/>
...
```

**Comment by jean-christophe-manciot** [comment]
@igloo777 
Thanks for sharing. I'll try it out in a near future.

**Comment by prettypot** [comment]
Hi, Did you get tcpping/jgroups working?  Did you find a way to ignore other keycloak servers that were running MPING on the same VLAN?

**Comment by jean-christophe-manciot** [comment]
@igloo777 
I've just tried your config with kc **24.0.1**, and starting it fails with the following error msg:
```
2024-03-12 17:58:29,729 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: JGRP000001: configuration error: the following properties in pbcast.STABLE are not recognized: {stability_delay=1000}
```

**Comment by prettypot** [comment]
Hi all,

I got this working with TCPPING. 


```
# cat cache-dev.xml
<?xml version="1.0" encoding="UTF-8"?>
<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:14.0 http://www.infinispan.org/schemas/infinispan-config-14.0.xsd"
        xmlns="urn:infinispan:config:14.0">

<jgroups>
    <stack name="tcpping" extends="tcp">
    <TCP external_addr="10.1.1.161" bind_addr="10.1.1.161" bind_port="7600" />
    <TCPPING initial_hosts="10.1.1.161[7600],10.1.1.162[7600],10.1.1.163[7600]"
    max_dynamic_hosts="0"
    port_range="0"
    stack.combine="REPLACE"
    stack.position="MPING"/>
    </stack>
</jgroups>

```

Build it with: 

   _kc.sh build --cache-config-file=cache-dev.xml_
 
Start with: 

   _kc.sh start --optimized_

**Reply by fabiot100** [reply]
Hi @prettypot !
Thank you for the answer. I tested and it worked!

**Comment by jean-christophe-manciot** [comment]
@igloo777 
If I remove ```stability_delay="1000" ``` from your config, kc 24.0.1 starts and both nodes join the cluster.
I also replaced ```external_addr``` with ```bind_addr```.

@prettypot 
Thanks for sharing.

**Comment by buman** [comment]
Hi, I have tried this setup on Keycloak 25.0.0, using the following config.
```xml
<?xml version="1.0" encoding="UTF-8"?>

<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:14.0 http://www.infinispan.org/schemas/infinispan-config-14.0.xsd"
        xmlns="urn:infinispan:config:14.0">


    <jgroups>
        <stack name="tcpping" extends="tcp">
            <TCP external_addr="${env.KC_EXTERNAL_ADDR}" bind_addr="${env.KC_BIND_ADDR}" bind_port="${env.KC_BIND_PORT}" />
            <TCPPING initial_hosts="${env.KC_INITIAL_HOSTS}"
                     max_dynamic_hosts="0"
                     port_range="0"
                     stack.combine="REPLACE"
                     stack.position="MPING"/>
        </stack>
    </jgroups>


    <cache-container name="keycloak">
        <transport lock-timeout="60000"/>
        <metrics names-as-tags="true" />
```
Dockerfile as follows
```dockerfile
FROM quay.io/keycloak/keycloak:25.0.0 as builder

# the following ENV must be set build time in order to run container in "optimized" mode
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_DB=mssql
ENV KC_TRANSACTION_XA_ENABLED=false

# Custom cache config file
COPY --chown=keycloak:root cache-tcpping.xml /opt/keycloak/conf/cache-tcpping.xml
# theme file
COPY --chown=keycloak:root nfr-theme-2.0.1-SNAPSHOT.jar /opt/keycloak/providers/nfr-theme-2.0.1-SNAPSHOT.jar
# Form actions SPI file
COPY --chown=keycloak:root form-actions-spi-2.0-TEST.jar /opt/keycloak/providers/form-actions-spi-2.0-TEST.jar

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:25.0.0
COPY --from=builder /opt/keycloak/ /opt/keycloak/
WORKDIR /opt/keycloak

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]

```

docker-compose.yml.
```yml
services:
  keycloak:
    image: nexus.something:5001/nfr-keycloak:2.0.44-SNAPSHOT
    command: start --optimized
    ports:
      - 8080:8080
      - 8443:8443
      - 7600:7600
    volumes:
      - ${LOG_DIR}:/opt/keycloak/data/log
      - ${LOCAL_KEYSTORE_LOCATION}:/opt/keycloak/conf/keystore.p12
    container_name: keycloak
    mem_limit: 4G
    environment:
      - TZ=Europe/Oslo
      - KC_DB_URL=${DB_ADDR}
      - KC_DB_USERNAME=${DB_USER}
      - KC_DB_PASSWORD=${DB_PASSWORD}
      - KC_HOSTNAME=${KC_HOSTNAME}
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=false
      - KC_HOSTNAME_DEBUG=true
      - JAVA_OPTS_APPEND=${JAVA_OPTS}
      - KC_LOG=console,file
      - KC_LOG_FILE=/opt/keycloak/data/log/server.json
      - KC_LOG_CONSOLE_COLOR=true
      - KC_LOG_LEVEL=INFO,org.infinispan:DEBUG,org.jgroups:DEBUG
      - KC_LOG_FILE_OUTPUT=json
      - KC_LOG_CONSOLE_OUTPUT=default
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - KC_CACHE=ispn
      - KC_CACHE_CONFIG_FILE=cache-tcpping.xml
      # procuction only
      - KC_PROXY_HEADERS=xforwarded
      - KC_HTTPS_KEY_STORE_TYPE=PKCS12
      - KC_HTTPS_KEY_STORE_FILE=/opt/keycloak/conf/keystore.p12
      - KC_HTTPS_KEY_STORE_PASSWORD=${HTTPS_KEY_STORE_PASSWORD}
      - KC_EXTERNAL_ADDR=192.xxx.xxx.19
      - KC_BIND_ADDR=192.xxx.xxx.19
      - KC_BIND_PORT=7600
      - KC_INITIAL_HOSTS=192.xxx.xxx.142[7600],192.xxx.xxx.19[7600]
    dns_search:
      - sub.something.no
      - something.no
    dns_opt:
      - ndots:1
```
**Note**: From version 25.0.0 you can enter cache-config at startup in optimized mode, ref https://www.keycloak.org/docs/25.0.0/release_notes/#all-cache-options-are-runtime


For some strange reason Infinispan cannot find my custom log-file
```
$ docker logs keycloak | grep cache-tcpping
2024-06-17 15:12:57,915 DEBUG [org.infinispan.commons.util.AbstractFileLookup] (main) Unable to find file /opt/keycloak/bin/../conf/cache-tcpping.xml in classpath; searching for this file on the filesystem instead.

```
The file is evidently there 
```
$ docker exec -it keycloak ls -la /opt/keycloak/bin/../conf/
total 40
drwxrwxr-x 1 keycloak root 4096 Jun 17 15:12 .
drwxr-xr-x 1 keycloak root 4096 Jun 17 14:43 ..
-rw-rw-r-- 1 keycloak root 3568 Jun 10 09:17 cache-ispn.xml
-rwxr-xr-x 1 keycloak root 3365 Jun 17 12:16 cache-tcpping.xml
-rw-rw-r-- 1 keycloak root 1149 Jun 10 09:12 keycloak.conf
-rw-r--r-- 1 root     root 5131 Jun  5 22:15 keystore.p12
-rw-rw-r-- 1 keycloak root  398 Jun 10 09:12 README.md
drwxrwxr-x 1 keycloak root 4096 Jun 10 09:12 truststores
```
I have also made sure that the file have the expected content after being copied into the container. Creating the file origininally from a Windows environment I also made sure that the file has the correct unix-style line endings. 

Can anyone tell me what else could be missing in this setup?
