### DISCUSSION TITLE
How to get the reverse proxy / production settings to work

### DISCUSSION THREAD

**Discussion by keithn** [keycloak/keycloak#12090] [Q&A]
So I started out using keycloak in start dev, and it was super trouble free... but now trying to work out how to configure it for a production environment, I get all kinds of problems and I'm really not sure how to solve them.    I'm using keycloak for a .net website, and I want to put it behind a reverse proxy on IIS where it has a certificate.  It has a sql database backend ( which seems to work ok so far).    Ultimately the keycloak server would live in a private network and not directly exposed to the internet and I could access the admin interface via the internal private network.    I'm just experimenting with this locally using docker, and a windows server 2019 virtual machine for web which has an address of "keyserver.local".   I made a certificate on the windows server for the website, and use a browser on that server to try out the reverse proxy to keycloak.

I have a docker compose :

version: "3.2"

services:
    keycloak:
        image: quay.io/keycloak/keycloak:latest 
        container_name: keycloak
        ports:
            - "8090:8080"
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
            - KC_DB=mssql
            - KC_DB_URL=jdbc:sqlserver://192.168.1.146;database=Keycloak
            - KC_DB_USERNAME=keycloak
            - KC_DB_PASSWORD=keycloak
            - KC_HOSTNAME=keyserver.local
            - KC_TRANSACTION_XA_ENABLED=false
        command: 
            - start --auto-build --proxy=edge 

so if I try to use the internal network

`http://192.168.1.146:8090/admin/master/console/`
or via the proxy  (which ideally won't proxy admin , but it is while I try and work this out)
`https://keyserver.local/admin/master/console/`

I get a login but, logging in I get....

invalid redirect_url

ie, when doing the following it gets a 400 - Bad Request doing a get on the following ....

`https://keyserver.local/realms/master/protocol/openid-connect/auth?client_id=security-admin-console&redirect_uri=https://keyserver.local/admin/master/console/&state=81abcd9c-6103-47b0-92e0-180dcf83454d&response_mode=fragment&response_type=code&scope=openid&nonce=04dbc003-15e5-46b0-9680-aaead7e4d008&code_challenge=amiL6XNwyDx5OLB9MMhziKoWkcEWypH_wgZZ3Wfx0wY&code_challenge_method=S256`

the redirect url for whatever reason always uses the hostname, rather than the direct address, hence why I still have it reverse proxied, but more importantly I don't understand why I'm getting the bad request. 

The keycloak DB is fresh, nothing in it and its just using the default admin login.

Not really sure how to get this working / how to work out what is going wrong

**Comment by Wolfsrudel** [comment]
First try
```
KC_HOSTNAME_STRICT_HTTPS=false
```
to disable forcing tls.
Try these, too:
```
KC_HOSTNAME_STRICT=false
KC_HOSTNAME_STRICT_BACKCHANNEL=true
```
The `KC_HOSTNAME` should be set to the address of the proxy. It's the `frontend_url` in former releases.

Hope that helps.

**Reply by keithn** [reply]
hi,  I tried the first one, that seemed to make it worse, it ended up in a weird redirect loop....  the other 2 didn't have a noticeable affect, still complaining about the redirect_uri    

the hostname is set to the    keyserver.local   which is the proxy server which has https...  it does serve up the login page over https, just the redirect seems to be having issues,  from what I can tell, keycloak is having issues and saying its a bad uri  (ie, 400 - bad request)

**Comment by keithn** [comment]
just a FYI for anyone who has the same problem, I couldn't work it out, I've had to back out of using keycloak as the documentation etc isn't quite good enough to actually do this.  The developer experience is great, install it, and go, and it's pretty easy to use.   But deploying to a production environment fails on its mission "Add authentication to applications and secure services with minimum effort."  as the errors keycloak produces don't help and often there is no documentation explaining what's wrong when you get particular errors, and documentation in general on how to do it seem fragmented / out of date / or lacking.   Hopefully this improves.   I might have a go at it again at a later date.

**Reply by MansurAliKoroglu** [reply]
Unfortunately I am having the same issues on the part "Add authentication to applications and secure services with minimum effort.". Keycloak is a great and promising tool but it seems the documentation is not quite good. This issue should be seriously discussed since a documentation is the definition of whole application. If documentation is good enough, people will use it more. It would be so nice to have more detailed docs and some "How to dockerize Keycloak for production" etc. guides. Especially for people like me, new to  self hosting and security.

**Comment by sbenhazez** [comment]
![Screenshot from 2022-06-08 00-52-54](https://user-images.githubusercontent.com/15202328/172496314-cbf06585-12d8-49d8-ad30-adf5f0e5051b.png)
I have the same problem with a configuration behind an nginx proxy: 
```
https://keycloak.local/realms/master/protocol/openid-connect/auth?client_id=security-admin-console&redirect_uri=https:/keycloak.local/admin/master/console/&state=383c0911-444e-4ff6-8791-94a7cf4eda4b&response_mode=fragment&response_type=code&scope=openid&nonce=afb526f0-978e-4ce8-8927-3101a56dfd1a&code_challenge=C6NfBUvd8ZEwWCJrcPUQYrdM9eGv6vBUbLxAVPI_SMM&code_challenge_method=S256
Status
400
Bad Request

Request Host : keycloak.local
```


Can the Keycloak team help us with an example of a production ready setup (behind a reverse proxy or ingress) ?  
The recommended Quarkus version does not provide precise documentation (configuration page) for using it in production
thanks for the help

**Reply by tlann** [reply]
I have been able to get KC 18 running behind a Spring Cloud Gateway.  

The environment variables I used were 
```
env = [ "JAVA_OPTS_APPEND=-Dcom.redhat.fips=false",
      "KC_DB=postgres",  "KC_DB_URL_HOST=keycloak-db",
      "KC_DB_USERNAME=keycloak", "KC_DB_PASSWORD=pass",
      "KC_HTTPS_KEY_STORE_FILE=${var.keystore_file}",
      "KC_HTTPS_KEY_STORE_PASSWORD=${var.keystore_password}",
      "KC_SPI_TRUSTSTORE_FILE_FILE=${var.truststore_file}",
      "KC_SPI_TRUSTSTORE_FILE_PASSWORD=${var.truststore_password}",
      "KC_PROXY=passthrough",
      "KC_HOSTNAME_STRICT_BACKCHANNEL=false", "KC_HOSTNAME_STRICT=false"  ]
```
For the gateway I had to add some headers and add an additional path because hte frontend doesn't correctly set the url path.  The frontend uses frames and gateway by default adds security headers.  So I had to set x-frame-options to the response.  

```
        - id: keycloak-assets
          uri: ${keycloak-hostname}
          predicates:
            - Path=/auth/**
          filters:
            - AddRequestHeader=X-Forwarded-For, X-Forwarded-Proto, X-Forwarded-Host
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
            - AddResponseHeader=X-FRAME-OPTIONS, SAMEORIGIN
        - id: keycloak
          uri: ${keycloak-hostname}
          predicates:
            - Path=/keycloak/**
          filters:
            - AddRequestHeader=X-Forwarded-For, X-Forwarded-Proto, X-Forwarded-Host
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
            - StripPrefix=1
            - AddResponseHeader=X-FRAME-OPTIONS, SAMEORIGIN

```
You may also need to setup a webFilterChain with a matecher.

```
 final ServerWebExchangeMatcher authenticationMatcher =
      ServerWebExchangeMatchers.pathMatchers(
          "/keycloak", "/keycloak/**",  "/auth/**");
```
          
 ```
 @Bean
  @Order(HIGHEST_PRECEDENCE)
  public SecurityWebFilterChain authenticationChain(ServerHttpSecurity http) {
    http.anonymous()
        .and()
        .headers()
        .frameOptions()
        .disable()
        .and()
        .securityMatcher(authenticationMatcher)
        .authorizeExchange()
        .matchers(authenticationMatcher)
        .permitAll();
    configureHttp(http);
    return http.build();
  }
```

**Comment by michaelpearce-gain** [comment]
Im having the same issue when using edge proxy, seems maybe the initial master realm isn't adding allowed redirects to cater for

**Comment by kwoot** [comment]
This below currently works for me, using 18.0.2 on Ubuntu 22.04:

Add --proxy=edge to startup of keycloak in systemd keycloak.service file

Below FULL nginx config, default site disabled.

```
server {
    listen 80;
    server_name myserver;

    return 301 https://$host$request_uri;
}


server {

    listen 443 ssl;
    ssl_certificate /etc/nginx/ssl/my_mkcert_cert.pem;
    ssl_certificate_key /etc/nginx/ssl/my_mkcert_key.pem ;
	
    server_name myserver;

    proxy_set_header X-Forwarded-For $proxy_protocol_addr; # To forward the original client's IP address 
    proxy_set_header X-Forwarded-Proto $scheme; # to forward the  original protocol (HTTP or HTTPS)
    proxy_set_header Host $host; # to forward the original host requested by the client
    
    location / {  
      proxy_pass http://myserver:8080;
    }
 
}
```

**Reply by myfirstnameispaul** [reply]
What do you have configured for keycloak?

I'm running JDK16 and basically same results as OP and the other poster with the redirect with effectively the same proxy configuration you have here.

Oddly, I was able to access the administration panel with no issues using `start-dev`, but had other problems I hoped would be resolved by just testing in production mode (couldn't get the create user link to show up).

**Reply by kwoot** [reply]
I do not understand your question. What do you mean "what have I configured for keycloak"? Is it the command line to start it? 
Also, lots of documents mention that the rest api starts with "/auth", which is only the case if you have a proxy that relocates /auth to the root of keycloak. So removing that part increased your chances of a working setup dramatically.
Try to see if  this line gives some result:
curl -k GET "https://myserver:8443/realms/master" | jq . | head -n 20
And start using the reverse proxy after that.

**Reply by jsplate** [reply]
@kwoot If you remove the server section in your nginx config that redirects http to https does it still run then?
What is your configuration for "Valid Redirect URIs" in the Clients setting? I assume http://xxx ?

**Reply by max0l0gy** [reply]
thank u man! You save my life!

**Comment by eggyknap** [comment]
Perhaps I'm misunderstanding the question, but in my case I've gotten Keycloak to listen on a custom URL behind an Apache reverse proxy, and it appears to work. We're still building the environment, so it's not in production, but it has supported my testing.

First, I use this option when building keycloak: `--http-relative-path=/kc`  (/kc is the custom URL I've chosen, so the administrative console is at https://server/kc/admin, for instance). 

I have these settings when I start Keycloak:
```
--hostname my.hostname.com
--proxy edge
--hostname-strict-backchannel=true
```

My apache proxy load balances between two Keycloak servers, but when I had only one server configured, it worked fine with this configuration, where my keycloak instance listens on port 8083:
```
ProxyPass /kc http://keycloak-server:8083/kc
ProxyPassReverse /kc http://keycloak-server:8083/kc
```

**Comment by marrale** [comment]
This thread is quire old, I'm wondering if someone figure out how to get work keycloak (HTTP) with IIS (HTTPS) as reverse proxy? As the original request from @keithn

**Reply by Landuu** [reply]
If you somehow got it to work, let me know please

**Reply by Michelmat359** [reply]
Hi, I'm also trying to get it to work through a proxy using docker and there's no way :(

**Comment by anup-khanal** [comment]
I am using portainer in my synology NAS and using reverse proxy to load apps. I was able to load homepage but not the admin page. I was able to resolve the issue with the following docker-compose script.

https://gist.github.com/anup-khanal/3c3d29978dfb5c3f88727b4f4adbba67

```
version: '3'
volumes:
  postgres_data:
    driver: local
services:
  postgres:
    image: postgres:16.0
    container_name: Keycloak-DB
    hostname: keycloak-db
    mem_limit: 1g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "keycloak", "-U", "keycloakuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /volume1/docker/keycloakdb:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloakuser
      POSTGRES_PASSWORD: keycloakpass
    restart: on-failure:5
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: Keycloak
    restart: on-failure:5
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloakuser
      DB_SCHEMA: public
      DB_PASSWORD: keycloakpass
      KEYCLOAK_ADMIN: <user>
      KEYCLOAK_ADMIN_PASSWORD: <password>
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_URL: '<your proxy url>'
      KC_HOSTNAME_ADMIN_URL: '<your proxy url>'
      KC_HOSTNAME_PATH: /
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME_STRICT: false
      KC_PROXY: edge
      KC_PROXY_ADDRESS_FORWARDING: true
    ports:
      - '8900:8080'
    command:
      - start-dev
    depends_on:
      - postgres
```

**Reply by zsnmwy** [reply]
Thanks for your code snippets.

I succeed in making the keycloak run behind the APISIX.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:23.0.7
          args:
            - start
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
          env:
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HOSTNAME_URL
              value: 'https://keycloak.xxxx.com'
            - name: KC_HOSTNAME_ADMIN_URL
              value: 'https://keycloak.xxxx.com'
            - name: KC_HOSTNAME_PATH
              value: '/'
            - name: KC_PROXY_ADDRESS_FORWARDING
              value: 'true'
            - name: KC_PROXY
              value: edge
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "false"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_BACKCHANNEL
              value: "true"
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: password
            - name: KC_HEALTH_ENABLED
              value: 'true'
            - name: KC_METRICS_ENABLED
              value: 'true'
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: >-
                jdbc:postgresql://xxxx:5432/keycloak
            - name: KC_DB_USERNAME
              value: postgres
            - name: KC_DB_PASSWORD
              value: password
            - name: jgroups.dns.query
              value: keycloak
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
```


```yaml
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
spec:
  http:
    - backends:
        - serviceName: keycloak
          servicePort: 8080
      match:
        hosts:
          - keycloak.xxx.com
        paths:
          - /*
      name: route-1
      plugins:
        - config:
            comp_level: 6
            min_length: 100
            types:
              - text/plain
              - text/css
              - text/html
              - text/xml
              - text/javascript
              - application/json
              - application/x-javascript
              - application/javascript
              - image/bmp
              - image/png
              - font/ttf
              - font/otf
              - font/eot
          enable: true
          name: gzip
        - enable: true
          name: cors
      timeout:
        connect: 5m
        read: 5m
        send: 5m
```

```yaml
apiVersion: v1
kind: Service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443
  selector:
    app: keycloak
  clusterIP: None
  clusterIPs:
    - None
  type: ClusterIP
  sessionAffinity: None
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  internalTrafficPolicy: Cluster
```
