### DISCUSSION TITLE
[keycloak quarkus 18.0.0] what does the "random ports" using for?

### DISCUSSION THREAD

**Discussion by ncistyang** [keycloak/keycloak#12354] [Q&A] [answered]
I found two random port on keycloak container，the ports usually greater than 30000. please see below screenshot

![image](https://user-images.githubusercontent.com/7554536/172145161-21c5d91b-5713-4794-bfef-6c1b1f13537f.png)

now there is security audit in progress in our company, so I need  to find out what does the two random ports using for ? can them  support tls protocol ? 

anyone can kindly help?

please see below keycloak StatefulSet config file in kubernetes 
```

apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/name: keycloak
  name: keycloak
  namespace: yg-cmp
spec:
  podManagementPolicy: Parallel
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: keycloak
      app.kubernetes.io/name: keycloak
  serviceName: keycloak-headless
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: keycloak
        app.kubernetes.io/name: keycloak
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/component
                  operator: NotIn
                  values:
                  - test
                matchLabels:
                  app.kubernetes.io/instance: keycloak
                  app.kubernetes.io/name: keycloak
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/component
                operator: NotIn
                values:
                - test
              matchLabels:
                app.kubernetes.io/instance: keycloak
                app.kubernetes.io/name: keycloak
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: KC_CACHE
          value: ispn
        - name: KC_CACHE_STACK
          value: kubernetes
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HTTPS_PORT
          value: "8443"
        - name: KC_HTTPS_PROTOCOLS
          value: TLSv1.3,TLSv1.2
        - name: KC_HTTPS_CLIENT_AUTH
          value: none
        - name: KC_LOG
          value: console,file
        - name: KC_PROXY
          value: edge
        - name: KC_LOG_LEVEL
          value: info
        - name: KC_DB_URL_PORT
          value: "3306"
        - name: KC_DB_USERNAME
          value: root
        - name: KC_DB_PASSWORD
          value: ****
        - name: KC_DB_URL_DATABASE
          value: keycloak
        - name: KC_DB_URL_HOST
          value: ****
        - name: KC_HTTPS_KEY_STORE_FILE
          value: /etc/keystore/server.jks
        - name: KC_HTTPS_KEY_STORE_PASSWORD
          value: ****
        image: quay.io/keycloak/keycloak:18.0.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /auth/health/live
            port: http
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: keycloak
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 7800
          name: jgroups
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /auth/health/ready
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
```
