### DISCUSSION TITLE
Keycloak in kubernetes cluster

### DISCUSSION THREAD

**Discussion by Parth6288** [keycloak/keycloak#12594] [Q&A]
HI Team, 

I am new to keycloak and deployed it on a kubernetes cluster with standalone ha cluster mode. I created a new realm and integrated it with AD. However when I redeployed with a new image, all my changes were gone. I had to re-create the realm and integrate it again with the AD.

Where are this config stored with in the pods? How do I ensure that this changes are persisted across my releases?

**Comment by kkcmadhu** [comment]
if you are using oob keycloak then it will be using h2 database, which will store stuff in local pod.
better use a proper db (recommended is postgres) and configure the same in standalone.xml


Also, keycloak is moving away from wildfly based depoloyment, i would recommend  using the quarkus distribution of keycloak (there too you will have to configure database)

**Comment by Parth6288** [comment]
Thanks @kkcmadhu. We are using the postgresSQL and have provided the details in our helm charts however we see the realms configs are being stored in the local h2 database. so when a pod, that has this DB, dies the config is gone. Looking the docs we need to update the standalone.xml file for this config however we don't see this file in our pods. What path can we find it?

**Comment by Parth6288** [comment]
We are already using the quarkus deployment(version 17.0)

**Comment by kkcmadhu** [comment]
the stadalone.xml , standalone-ha.xml kind of configurations are only for wildfy deployments, if i understand it right you are using quarks based distribution.

You can put the jdbc details in you config map 


I use the below yaml for bring up my keycloak on quarkus with mysql.. you can cange the db url to use postgres
Note :: if your keycloak is not behind reverse proxy with does ssl termination, you can remove the proxy env variable and add relavelt certificattes here.. the configuration details are availble in config guie https://www.keycloak.org/server/all-config

```
apiVersion: v1
kind: Service
metadata:
  name: keycloak18-headless
spec:
  clusterIP: None
  selector:
    app: keycloak18
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    - name: jgroups
      port: 7600
      protocol: TCP
      targetPort: jgroups
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak18
  labels:
    app: keycloak18
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak18
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak18
  labels:
    app: keycloak18
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak18
  template:
    metadata:
      labels:
        app: keycloak18
    spec:
      containers:
      - name: keycloak18
        image: quay.io/keycloak/keycloak:18.0.0
        args: ["start-dev"]
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        - name: KC_PROXY
          value: "edge"
        - name: KC_DB
          value: "mysql"
        - name: KC_DB_URL
          value: "jdbc:mysql://mysqlhost:3306/keycloakonquarkus"        
        - name: KC_DB_USERNAME
          value: "mysqluser"
        - name: KC_DB_PASSWORD
          value: "mysqlpassword"
        - name: KC_HEALTH_ENABLED
          value: "true"
        - name: KC_METRICS_ENABLED
          value: "true"
        - name: KC_FEATURES
          value: "token-exchange,preview,scripts"
        - name: KC_HTTP_RELATIVE_PATH
          value: "/auth"
        - name: KC_SPI_ADMIN_REALM
          value: "yourmasterrealmname"
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /auth/realms/yourmasterrealmname
            port: 8080

```
