### DISCUSSION TITLE
Failed to start in Production mode

### DISCUSSION THREAD

**Discussion by ghost** [keycloak/keycloak#12703] [Q&A] [answered]
I'm running Keycloak in a docker container.
Whenever I try to start it in production I get:
```
<timestamp> ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
<timestamp> ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: /etc/x509/https/<mycertfile>.pem
<timestamp> ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Key material not provided to setup HTTPS. Please configure your keys/certificates or start the server in development mode.
<timestamp> ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
```
These occur after the info message that it's initializing the master realm

I'm running the container with the following command
`start '--hostname=keycloak.mydomain.com --https-certificate-file=/etc/x509/https/<mycertfile>.pem --https-certificate-key-file=/etc/x509/https/<mykeyfile>.pem`

I'm using a docker compose that has the following environment and volume variables:
``` 
volumes:
      - "/path/to/certs/:/etc/x509/https"
environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: <pw>
      KEYCLOAK_HTTP_PORT: 8080
      KEYCLOAK_HTTPS_PORT: 8443
      KEYCLOAK_HOSTNAME: keycloak.mydomain.com
      DB_VENDOR: mariadb
      DB_USER: Keycloak
      DB_PASSWORD: <dbpw>
```

I've also tried declaring the certfile and keyfile as environment variables but I don't get anything different in the errors.
I'm using nginx proxy manager to generate my cert and key and I've double and triple checked that they're the same cert and key.
I'm literally copying the cert and key file from the nginx directory where they're stored over to the folder I'm using in my docker-compose file.

I can provide any additional info that may be needed. I have full admin access to the environment and I set everything up. Thanks!
