### DISCUSSION TITLE
Keycloak Quarkus Postgres Setup with docker-compose

### DISCUSSION THREAD

**Discussion by GeofoxCoding** [keycloak/keycloak#13516] [Q&A] [answered]
Hi,

I'm experimenting with Keycloak Quarkus 19.0.1 and Postgres in a simple docker-compose scenario. I'm new to docker-compose and it seems there a still some errors in my configuration.

Can someone please help me to get forward?

My startup error looks like this. Basically it seems like my keycloak container has no access to postgres port 5432?

`keycloak     | 2022-08-03 14:13:26,847 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': The connection attempt failed.
keycloak     | 2022-08-03 14:13:26,849 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: org.postgresql.util.PSQLException: The connection attempt failed.
keycloak     |  at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:331)
keycloak     |  at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
keycloak     |  at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
keycloak     |  at org.postgresql.Driver.makeConnection(Driver.java:400)
keycloak     |  at org.postgresql.Driver.connect(Driver.java:259)
keycloak     |  at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
keycloak     |  at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
keycloak     |  at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:103)
keycloak     |  at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:49)
keycloak     |  at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:35)
keycloak     |  at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:216)
keycloak     |  at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:513)
keycloak     |  at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:494)
keycloak     |  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
keycloak     |  at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
keycloak     |  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
keycloak     |  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
keycloak     |  at java.base/java.lang.Thread.run(Thread.java:829)
keycloak     | Caused by: java.net.UnknownHostException: postgres
keycloak     |  at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:229)
keycloak     |  at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
keycloak     |  at java.base/java.net.Socket.connect(Socket.java:609)
keycloak     |  at org.postgresql.core.PGStream.createSocket(PGStream.java:241)
keycloak     |  at org.postgresql.core.PGStream.<init>(PGStream.java:98)
keycloak     |  at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:109)
keycloak     |  at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)
keycloak     |  ... 17 more
keycloak     |
keycloak     | 2022-08-03 14:13:27,235 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': The connection attempt failed.`

This is my environment file.
[env.txt](https://github.com/keycloak/keycloak/files/9252996/env.txt)

My yaml looks like this:

```
version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: keycloak-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes: 
      - C:/.../docker-compose-keycloak/user_db:/var/lib/postgresql/data
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:19.0.1
    env_file:
      - ./env.txt
    environment:
      KC_FEATURES:
        authorization
        token-exchange
        docker
        impersonation
        scripts
        upload-scripts
        web-authn
        client-policies
        dynamic-scopes
    entrypoint: /opt/keycloak/bin/kc.sh start --auto-build
    volumes:
      - ./keycloak_data/keycloak.local+1.pem:/opt/keycloak/conf/server.crt.pem
      - ./keycloak_data/keycloak.local+1-key.pem:/opt/keycloak/conf/server.key.pem
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - postgres
```

Beside my yaml file I have a folder keycloak_data with cert and key *.pem files and an folder user_db with content pgdata initialized by keycloak.

**Comment by GeofoxCoding** [comment]
I'm a few steps further. At the moment I'm putting both containers into a docker bridged network. Also I named my postgres container keycloak-db and tried to reach it as hostname postgres from keycloak environment settings.

Now I'm facing another interresting behavior. With following keycloak env variables:
KC_DB_URL_DATABASE=keycloak
KC_DB_URL_HOST=keycloak-db
KC_DB_URL_PORT=5432
KC_DB_URL_PROPERTIES="verifyServerCertificate=false&ssl=allow"

I get the following startup error:
keycloak     | 2022-08-04 12:28:30,889 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: org.postgresql.util.PSQLException: FATAL: database "keycloakverifyServerCertificate=false&ssl=allow" does not exist

What is going on here oO? Why does it try to find a database, named like my env variable KC_DB_URL_PROPERTIES ???

**Comment by GeofoxCoding** [comment, marked as answer]
Okay my setup is running now.

I ended up with the following yaml.
```
version: '3.8'
services:
  db:
    image: postgres:latest
    env_file:
      - ./keycloak-postgres.env
    container_name: keycloak-db
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes: 
      - C:/Users/Richard/Code/docker-compose-keycloak/user_db:/var/lib/postgresql/data
    networks:
      - keycloak-network
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:19.0.1
    restart: unless-stopped
    env_file:
      - ./keycloak-postgres.env
    environment:
      KC_FEATURES:
        authorization
        token-exchange
        docker
        impersonation
        scripts
        upload-scripts
        web-authn
        client-policies
        dynamic-scopes
    entrypoint: /opt/keycloak/bin/kc.sh start --auto-build
    volumes:
      - ./keycloak_data/keycloak.local+1.pem:/opt/keycloak/conf/server.crt.pem
      - ./keycloak_data/keycloak.local+1-key.pem:/opt/keycloak/conf/server.key.pem
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      - keycloak-network
    depends_on:
      - postgres
networks:
  keycloak-network:
    driver: bridge
```
Not sure if the explicit network is necessary because most keycloak docker-compose examples don't have that.

My env file looks like that:
```
KC_DB=postgres
KC_DB_USERNAME=keycloak
KC_DB_PASSWORD=kcpasswd
KC_DB_SCHEMA=public
# KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak?ssl=allow
KC_DB_URL_DATABASE=keycloak
KC_DB_URL_HOST=keycloak-db
KC_DB_URL_PORT=5432
#KC_DB_URL_PROPERTIES="verifyServerCertificate=false&ssl=allow"
KC_HOSTNAME=keycloak.local:8443
KC_HOSTNAME_STRICT=false
KC_HTTPS_CLIENT_AUTH=request
KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/conf/server.crt.pem
KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/conf/server.key.pem
KC_HTTPS_PORT=8443
KC_HTTPS_PROTOCOLS=TLSv1.3,TLSv1.2
KC_HTTP_ENABLED="true"
KC_HTTP_PORT=8080
KC_METRICS_ENABLED=true
KC_PROXY=edge
KEYCLOAK_ADMIN=Admin
KEYCLOAK_ADMIN_PASSWORD=Admin
PROXY_ADDRESS_FORWARDING=true
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
PGDATA=/var/lib/postgresql/data/pgdata
```
The scope of my question is solved. It would be great if one of the more experienced Docker/Keycloak experts could make an official and  comprehensive tutorial of a docker-compose setup with database.
