### DISCUSSION TITLE
Keycloak start-dev --import-realm never imports my realm.json

### DISCUSSION THREAD

**Discussion by InfoSec812** [keycloak/keycloak#13532] [Q&A] [answered]
I have a pod container defined which we use for our integration/e2e testing. With Keycloak 14 we are starting the container with options to import the `realm.json` from a ConfigMap and using an in-memory DB. I have tried to migrate to Keycloak 18/19 containers and have used a config like:

```
  containers:
  - args:
    - start-dev
    - --import-realm
    env:
    - name: KEYCLOAK_LOGLEVEL
      value: DEBUG
    - name: KEYCLOAK_ADMIN
      value: admin 
    - name: KEYCLOAK_ADMIN_PASSWORD
      value: admin
    volumeMounts:
    - mountPath: /opt/keycloak/data/realm
      name: keycloak-config
    image: quay.io/keycloak/keycloak:19.0.1
    name: keycloak
```

The realm never gets imported and there are no error logs I can see which indicate a problem.

Any suggestions on how I should achieve parity for KC 18/19?
