### DISCUSSION TITLE
Realm Import - Potential id conflicts

### DISCUSSION THREAD

**Discussion by MarkCupitt** [keycloak/keycloak#13530] [Archive]
We are using the new Operator V19.0.1 with the `KeycloakRealmImport` yaml definition. We have exported one of our realms from an older version of Keycloak (v16), converted it to yaml and loaded it. It works. (As described here [here](https://www.keycloak.org/operator/realm-import))

This question is related to the ids, specifically potential conflicts with duplicate ids and the way the YAML is structured.

The realm has lots of ids for the exported data:

This is the realm itself, I assume we can leave the id field out and it will be automatically created, and unique
```
  realm:
    id: d3bf7e8b-2824-4e28-ab68-2b566ff04a66
    realm: $internal_tenant_realm_name
    displayName: $internal_tenant_realm_display_name
```
However, when we come to clients, and some other items, we see that the id is actually used as a `key`, for example

```
    clients:
      - id: 3ec6a80e-dde6-4361-9d92-bc935a1591c8
        clientId: account
        name: "\${client_account}"
```
We want to use this yaml as a template to import multiple realms

Can we assign our own unique ids and is there any impact on the use of the id elsewhere in the yaml?

If, not, how do we achieve this and what are the risks of duplicate id's being used in multiple realms?
