### DISCUSSION TITLE
Configuring Quarkus distribution using the Operator

### DISCUSSION THREAD

**Discussion by vmuzikar** [keycloak/keycloak#13682] [Archive]
The [new Operator](https://github.com/keycloak/keycloak/tree/main/operator) is designed to bring the already great container experience with the Quarkus distribution to a whole new cloud-native level. This includes deployment and the server/distribution configuration in a way that respects K8s best practices. For this, there's a Keycloak CR (Custom Resource) that currently (KC 19) looks something like this:
```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  instances: 1
  serverConfiguration:
    - name: db
      value: postgres
    - name: db-url-host
      value: postgres-db
    - name: db-username
      secret:
        name: keycloak-db-secret
        key: username
    - name: db-password
      secret:
        name: keycloak-db-secret
        key: password
  hostname: example.com
  tlsSecret: example-tls-secret
  disableDefaultIngress: true
  image: quay.io/myorg/my-custom-kc:latest
```

In that CR, we can see there are several configuration categories:
* Server configuration, like `hostname`, `tlsSecret` but also the whole free-form (key-value) field `serverConfiguration`. The last one can either take a value as a plain text, or a reference to a Key in a Secret.
* Deployment configuration often passed down to the underlying StatefulSet, like `instances` or `image`.
* Operator configuration, like `disableDefaultIngress`.

Deployment and Operator configurations are pretty clear, however the Server configuration  can be inconsistent. Some fields are top-level (`hostname`, `tlsSecret`), some are hidden under `serverConfiguration` key-value map. Reason for this is that currently, the top-level fields are taken as a first-class citizen by the Operator which adds additional logic to them. E.g. `hostname` is reflected by the Ingress that the Operator creates. `tlsSecret` mounts a Secret and actually translates into 2 config options under the hood ([`https-certificate-file`, `https-certificate-key-file`](https://www.keycloak.org/server/enabletls)). On the other hand, `serverConfiguration` is taken as is and transformed into configuration env vars without the Operator altering it in any way.

There are several options to resolve this inconsistency.

## Proposal 1: Use only `serverConfiguration`

We move every server related top-level field under `serverConfiguration`.

**Pros:**
* Identical experience to "bare" Quarkus distribution. Users don't need to research the CRD too much as they can directly use all config options as they're used to.
* Low maintenance costs. Any new option added to the dist is implicitly available through the Operator.

**Cons:**
* No native type checking. Everything is a key-string, or key-secretReference type. Even for fields where one or the other doesn't make sense, like e.g. `tlsSecret`. Additional logic in the Operator would be required to mitigate this and to honor the Secure by default principle, e.g. enforce some options are coming from a Secret.
* More verbose. Compare the following:
  ```yaml
  spec:
      serverConfiguration:
        - name: hostname
          value: example.com
  ```
  ```yaml
  spec:
      hostname: example.com
  ```
* Not all dist options make sense in K8s environment (basically anything files related as K8s doesn't know the concept of files per se). E.g. `https-certificate-file` and `https-certificate-key-file` for which K8s offers a [native Secret type](https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets).
* No native field descriptors. Users (and OLM UI form rendering) cannot discover the API just by looking at the CRD.

### Example
```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  instances: 1
  serverConfiguration:
    - name: db
      value: postgres
    - name: db-url-host
      value: postgres-db
    - name: db-username
      secret:
        name: keycloak-db-secret
        key: username
    - name: db-password
      secret:
        name: keycloak-db-secret
        key: password
    - name: hostname
      value: example.com
    - name: https-certificate-key-file
      secretMount: # mounted by the Operator and replaced by an actual file path on StatefulSet level
        name: example-tls-secret
        key: tls.key
    - name: https-certificate-file
      secretMount:
        name: example-tls-secret
        key: tls.crt
  disableDefaultIngress: true
  image: quay.io/myorg/my-custom-kc:latest
```

## Proposal 2: Add more top-level fields

We would add selected fields to the top level, tailoring the API (the CR) to cloud-native environment. Some fields would be directly mapped to the dist options (like `hostname`), some would be an aggregation or alternative the dist options (like `tlsSecret`). We would keep the free-form `serverConfiguration` field (possibly renaming to `startupOptions`) mainly to support easy SPIs configuration which is often added via extensions.

**Pros:**
* K8s native API honoring the best practices, leveraging type checks, field descriptors, etc.
* Nested and cleaner structure, see example below.

**Cons:**
* Higher maintenance costs. Fields need to be added manually (possibly generated from dist options, at least partially for the directly mapped fields).
* Different API compared to "bare" dist.

### Example
```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  instances: 1
  db:
    vendor: postgres
    usernameSecret: # plain text value not supported by the type
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
    host: postgres-db
  vaultSecret: secretName
  hostname: example.com
  tlsSecret: example-tls-secret
  disableDefaultIngress: true
  image: quay.io/myorg/my-custom-kc:latest
```

## Related:
* https://github.com/keycloak/keycloak/discussions/11848

**Comment by vmuzikar** [comment]
CC: @keycloak/storage-x @keycloak/cloud-native-team @keycloak/kc-maintainers

**Comment by jsorah** [comment]
I think having an opinionated CRD with guardrails as in `Proposal 2` would make the most sense as these options would be more visible from the CRD itself.  It seems like what also should qualify for these "top-level" or first-class properties are those things that would be common to the majority of Keycloak installations and things that have potential to be "cross-cutting" (i.e. needs support from other k8s objects).

As long as there is some mechanism (as stated in the proposal, keeping something similar to `serverConfiguration`) to set items not configured directly by the CRD, that seems like it should cover many use cases.  However, that could come with pitfalls if there is some kind of conflict between the free-form configuration and what is declared in the CRD - and maybe some consideration for how that reconciliation works (does freeform win? does CRD win?).

The higher maintenance cost of how to add these top-level objects to the CRD isn't necessarily a bad thing - it means it would have to involve some consideration in if it _should_ be a top-level object or not.  

Not to distract from the current discussion but the other considerations here are how the CRD changes would impact upgrades.  If things are kept fully backwards compatible for N-1 releases, then there should be no problem - but drastic changes in the CRD (meaning new required fields or behavior change in how a field works) could be problematic and require a different approach for someone upgrading an existing, live deployment.

**Reply by vmuzikar** [reply]
@jsorah I share exactly this opinion. Add top-level fields for the stuff that make sense in cloud env and that we expect would be used in majority of instances. For everything else there'd be the free-form field. This would IMHO provide a great balance between nice and native K8s experience and the freedom of free-form field.

With regards to conflicts between top-level fields and `serverConfiguration`. I think the free-form field should take precedence over (overwrite) top-level fields. We actually had a similar problem with the [`podTemplate`](https://www.keycloak.org/operator/advanced-configuration#_unsupported_features) field which also [takes precedence](https://github.com/keycloak/keycloak/blob/d55d110ff9ad2441b6a85c123b25911da381d924/operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java#L532) over top-level fields.

**Comment by pedroigor** [comment]
Looks like we have no other option but #2. Based on our previous discussions, the fact we can't get the same level of integration with OLM in #1 (e.g.: discovering fields) removes it from the game completely. I would love to see the same experience between different runtimes, but if that is against OLM/Operator best practices we can't do much about it.

Let's move forward with #2 (I think) for now and see if we can improve it later once we know all the requirements we need to consider to properly generate code.

W.r.t. the structure of the CRD, I'm not 100% sure if using our configuration namespaces (e.g.: `db`) at the top is a good thing. I understand it helps to not repeat the same prefix in every single option and potentially make the CRD more readable by grouping options. But I think we can still keep some "cross-runtime experience" by aligning the option name as much as possible and making it less verbose:

```
db: postgres
db-url-host: postgresdb
db-username-secret: my-secret
db-password-secret: my-secret
hostname: example.com
https-certificate-file-secret: example-tls-secret 
https-certificate-key-file-secret: example-tls-secret
```

For me, it looks a lot easier to map options to/from a CRD while still leveraging the documentation/tooling we have. Perhaps we can even generate operator-specific documentation (e.g.: all-config page) if we use a naming pattern that includes the `-secret` suffix to options whenever the option maps to a field that relies on a secret.

I agree we need the free-form `serverOptions` field. But I would rename it to just `options`.

I'm also not sure if we should mix operator-specific options with server options. So perhaps we could have all server options defined in `options` and only the operator-specific options (e.g.: instance, image, etc) at the root.

```
options:
    db: postgres
    db-url-host: postgresdb
    db-username-secret: my-secret
    db-password-secret: my-secret
    hostname: example.com
    https-certificate-file-secret: example-tls-secret 
    https-certificate-key-file-secret: example-tls-secret
instance: 3
image: my-image
```

**Reply by vmuzikar** [reply]
I agree with the point to keep the "cross-runtime experience" as same as possible. However, I think we need to find some balance as we want to provide a K8s native experience at the same time. And that means e.g. to have a single field for TLS cert/key, or to nest fields inside "namespaces" (like `db`).

I know I stated that we basically have 3 config categories (Server, Deployment, Operator). But on the other hand the whole CR represents a single KC instance and the line between the categories is really thin. E.g. `hostname` – it's a server config but at the same time operator config (for Ingress). Or what if the operator will set `tlsSecret` on Ingress instead of on KC if user set `proxy=edge`. Is `tlsSecret` in that case really a server config? Therefore I think it's perfectly fine to have the options as top-level.

**Reply by pedroigor** [reply]
I don't think nesting fields inside namespaces is improving the k8s experience. For me, it is more verbose and does not provide the cross-runtime experience.

> E.g. hostname – it's a server config but at the same time operator config (for Ingress)

I see it differently. It is a server config (from a user perspective) used by the operator to automatically configure an ingress. In fact, note that even if the hostname is not set, the Ingress must always be created, regardless.

> Or what if the operator will set tlsSecret on Ingress instead of on KC if user set proxy=edge. Is tlsSecret in that case really a server config? Therefore I think it's perfectly fine to have the options as top-level.

If the operator is using `tlsSecret` to configure the key material for both ingress and KC, I would say it is not correct? In case you are using reencrypt, you probably want different key materials on both Ingress and the server. If the `tlsSecret` as it is today serves to configure both depending on the `proxy` setting, that is a bit confusing to me. For me, it makes more sense to configure TLS using the corresponding server option with the support to fetch from a secret. Ingress is set using a completly different option.

**Comment by stianst** [comment]
I'd favour an approach that aligns the Operator config as much as possible with the container and distribution config, and allows direct mapping/translations between the two.

Proposal 1 is not that at all; Let's take the example

```
serverConfiguration:
    - name: db
      value: postgres
    - name: db-username
      secret:
        name: keycloak-db-secret
        key: username
```

The equivalent in the CLI format is "--db=postgres", which is not comparable to the above. If directly translated to YAML it would rather look something like:

```
config:
  db
    vendor: postgres
    username: db-username
    password: mypassword
```

That's obviously not quite there, as you'd want to inject the password from a secret. That is something we can and should solve at all levels.

**Reply by vmuzikar** [reply]
@stianst Thanks for your input! Can we delete this one? Seems partially like a duplicate of the next thread here.

**Comment by stianst** [comment]
I'd favour an approach that aligns the Operator config as much as possible with the container and distribution config, and allows direct mapping/translations between the two.

Proposal 1 is not that at all; Let's take the example

```
serverConfiguration:
    - name: db
      value: postgres
    - name: db-username
      secret:
        name: keycloak-db-secret
        key: username
```

The equivalent in the CLI format is "--db=postgres", which is not comparable to the above. If directly translated to YAML it would rather look something like:

```
config:
  db
    vendor: postgres
    username: db-username
    password: mypassword
```

That's obviously not quite there, as you'd want to inject the password from a secret. That is something we can and should solve at all levels. Reading the docs for the dist today I'm not quite sure how that is handled today, but it should be relatively easy to say "use K8s secrets, then shouldn't matter if you are using the cli, env variables, or the operator, to configure you should be able to set what secret name to use.

Same goes around certs and other (smart options) like that; it's not just the Operator that should be cloud/k8 friendly, the container and CLI should also be. That may mean that we need smarter config at all levels, not just in the Operator. With also smarter validation at all levels. Doing something completely different in the Operator adds overhead in maintenance, complexity, documentation, as well as UX. 

How do we achieve something like what I have in mind? There's two approaches we can take there. First just align with the CLI, and live with the Operator not being ideal, then gradually improve things; or alternatively come up with a config approach that is ideal for the Operator, then gradually unify the two over time.

**Reply by pedroigor** [reply]
As mentioned before, I also agree we should align the experience across runtimes as much as possible. Whatever we can improve the distribution itself we should do it to make things easier and try as much as possible to make the distribution a main source of truth for the configuration. As a side note, we should also make life easier and provide a decent integration with k8s even if the operator is not used.

I would start first aligning the operator with the distribution config:

```
options:
    db: postgres
    db-url-host: postgresdb
    db-username-secret: my-secret
    db-password-secret: my-secret
    hostname: example.com
    https-certificate-file-secret: example-tls-secret 
    https-certificate-key-file-secret: example-tls-secret
instance: 3
image: my-image
```
