### DISCUSSION TITLE
Unable to Load CSS for Keycloak [not a supported MIME type] in kubernetes

### DISCUSSION THREAD

**Discussion by MohammedAdain** [keycloak/keycloak#13851] [Q&A]
![image](https://user-images.githubusercontent.com/61708483/185325318-da0f725b-aef9-498a-8b65-5396cf477aa6.png)

I get the following error while hitting the keycloak server from my browser via http.
I am using the latest image which is 19.0.1.
A snap of my deployment manifest
```
spec:
      containers:
      - args:
        - start-dev
        env:
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: admin
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KEYCLOAK_FRONTEND_URL
          value: http://keycloak-dev.ia55.net
        - name: KC_PROXY
          value: edge
        - name: KC_HEALTH_ENABLED
          value: "true"
        - name: DB_ADDR
          value: dbpgsqlinfra_keycloak.shared-dev.i.ia55.net
        - name: DB_DATABASE
          value: postgres
        - name: DB_USER
          value: infra_keycloak_app
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: secret
              name: vault-secret-infra-keycloak-secret
        - name: DB_SCHEMA
          value: public
        - name: DB_VENDOR
          value: POSTGRES
        - name: JGROUPS_DISCOVERY_PROTOCOL
          value: dns.DNS_PING
        - name: JGROUPS_DISCOVERY_PROPERTIES
          value: dns_query=keycloak
        - name: CACHE_OWNERS_COUNT
          value: "2"
        - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
          value: "2"
```
Thanks,
Mohammed Adain
