### DISCUSSION TITLE
KC_* environment variables are not working out of the box in Keycloak official container

### DISCUSSION THREAD

**Discussion by zak905** [keycloak/keycloak#14214] [Q&A] [answered]
I am running the official Keycloak image (version 19.0.1) in a local environment using docker compose. It seems to me that Keycloak is not capturing the KC_* environment variables. Here is an example of the service description

```
  image: quay.io/keycloak/keycloak:19.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME: auth-server
      KC_HOSTNAME_PATH: /auth
    ports:
    - "8080:8080"
    entrypoint: ["start"]
```

Even if I am specifiying the hostname path as `/auth`, keycloak is still serving at `/`

As far as I know, keycloak will automatically build on every start unless the `--optimized` flag is specified. I believe this should work out of the box without any additional configuration steps

### Update

Also, trying `command: ["start", "--http-enabled=true", "--hostname=auth-server", "--hostname-path=/auth"]` seems to have no effect, so I am guessing this is more general and not related to env variables only
