### DISCUSSION TITLE
When is quarkus based keycloak k8s operator coming out?

### DISCUSSION THREAD

**Discussion by bjethwan** [keycloak/keycloak#14901] [Archive]
When is quarkus based keycloak k8s operator coming out?

**Comment by FlxPeters** [comment]
It's already available and should be stable soon. I think version 20 of Keycloak is the target version for a stable release.

**Reply by bjethwan** [reply]
Thanks @FlxPeters .
I see it now:
https://www.keycloak.org/2022/04/keycloak-1800-released
The [legacy Operator](https://github.com/keycloak/keycloak-operator) will receive updates until Keycloak 20 when the Keycloak WildFly distribution reaches EOL.

**Reply by bjethwan** [reply]
@FlxPeters 
Can you give me one prime reason for moving onto Keycloak Operator instead of CodeCentric/StatefulSet based deployment?
https://github.com/keycloak/keycloak/discussions/14921

The one which is worrying me is that Infinispan cache which I got limited to two pod.
```
extraEnv: |
  - name: JGROUPS_DISCOVERY_PROTOCOL
    value: kubernetes.KUBE_PING
  - name: KUBERNETES_NAMESPACE
    valueFrom:
      fieldRef:
        apiVersion: v1
        fieldPath: metadata.namespace
  - name: CACHE_OWNERS_COUNT
    value: "2"
  - name: CACHE_OWNERS_AUTH_SESSIONS_COUNT
    value: "2"
```
