### DISCUSSION TITLE
After update to 20.0.0: Fetching from User Info endpoint returns 403

### DISCUSSION THREAD

**Discussion by jonasschwab** [keycloak/keycloak#15331] [Q&A]
I'm using Keycloak to secure a JupyterHub set up accroding to the Zero to Jupyter tutorial [here](https://z2jh.jupyter.org/). The settings for authentication are specified [here](https://z2jh.jupyter.org/en/stable/administrator/authentication.html#keycloak): 

```yaml
hub:
  config:
    GenericOAuthenticator:
      client_id: your-client-id
      client_secret: your-client-secret
      oauth_callback_url: https://your-jupyterhub-domain/hub/oauth_callback
      authorize_url: https://${host}/auth/realms/${realm}/protocol/openid-connect/auth
      token_url: https://${host}/auth/realms/${realm}/protocol/openid-connect/token
      userdata_url: https://${host}/auth/realms/${realm}/protocol/openid-connect/userinfo
      login_service: keycloak
      username_key: preferred_username
      userdata_params:
        state: state
    JupyterHub:
      authenticator_class: generic-oauth
```

This worked like a charm with version 19.0.3 and earlier, but with version 20 the hub complains
```
Error fetching user data 403 GET https:/${host}/auth/realms/${realm}/protocol/openid-connect/userinfo
```

and KeyCloak logs
```
WARN  [org.keycloak.events] (executor-thread-12) type=USER_INFO_REQUEST_ERROR, realmId=<redacted>, clientId=null, userId=null, ipAddress=<redacted>, error=access_denied, auth_method=validate_access_token
```
I was wondering if there's an obvious reason why it doesn't work any more.
