### DISCUSSION TITLE
Performance issue with remote infinispan

### DISCUSSION THREAD

**Discussion by antonionappi88** [keycloak/keycloak#15673] [Archive]
Hello,
I'm deploying Keycloak 20 using the Keycloak Operator and trying to connect to a remote infinispan machine. It is a single machine that I started up with default configuration. 
When I start up everything works but when I try to perform stress tests, then the infinispan get crazy and use whatever CPUs has. It was able to use 16 full cores and still fail to handle requests... (i was performing 50users/sec for 10 minutes).

Any suggestion on how tune infinispan or if I'm doing something wrong ? 

This is my keycloak resource:

```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  instances: 1
  ingress:
    enabled: false
  hostname:
    hostname: my-keycloak.com
  http:
    httpEnabled: true
    httpPort: 8080
  transaction:
    xaEnabled: true
  db:
    passwordSecret:
      key: password
      name: keycloak-db-secret
    usernameSecret:
      key: username
      name:  keycloak-db-secret
    url: jdbc:postgresql://my-host:6000,my-host-2:6604/keycloak
    vendor: postgres
    schema: keycloak
    poolMaxSize: 900
  additionalOptions:
  #- name: cache-config-file
  #  value: "/opt/keycloak/conf/cache-ispn.xml"
  - name: log-level
    value: info
  - name: proxy
    value: edge
  - name: storage
    value: jpa
  - name: storage-hotrod-host
    value: "my-vm"
  - name: storage-hotrod-port
    value: "11222"
  - name: storage-hotrod-password
    value: password
  - name: storage-hotrod-username
    value: myuser
  - name: storage-area-action-token
    value: hotrod
  - name: storage-area-single-use-object
    value: hotrod
  - name: storage-area-auth-session
    value: hotrod
  - name: storage-area-user-session
    value: hotrod
```

Thank you,
Antonio
