### DISCUSSION TITLE
Adding extensions to container without building one

### DISCUSSION THREAD

**Discussion by sr258** [keycloak/keycloak#16203] [Q&A] [answered]
I'd like to add an extension (provider) to KeyCloak which I run in a container. It works if I build a new container like this (Dockerfile):

```
FROM quay.io/keycloak/keycloak:20.0.2
ADD ./event-listener-http-jar-with-dependencies.jar /opt/keycloak/providers/
```

I'd prefer not building my own image to keep things simple. Is it possible to add extensions in another way? I've already tried mapping a volume into the container like this:

```
    volumes:
      - ./keycloak-extensions:/opt/keycloak/providers/http
```

The extension isn't detected, however, probably because it's in a subfolder.

**Comment by sr258** [comment, marked as answer]
Figured this out myself: If you specify an absolute path, you can also add single files as volumes in docker. Example (docker compose):

```
    volumes:
      - ${PWD}/event-listener-http-jar-with-dependencies.jar:/opt/keycloak/providers/event-listener-http-jar-with-dependencies.jar
```

**Comment by TiloGit** [comment]
here for kubernetes  (with PVC)

```yaml
        ...
         ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
          volumeMounts:
            - name: kc-jars-volume
              mountPath: /opt/keycloak/providers/scim-for-keycloak-kc-23-2.0.0-free.jar 
              subPath: scim-for-keycloak-kc-23-2.0.0-free.jar 
      volumes:
        - name: kc-jars-volume
          persistentVolumeClaim:
           claimName: kc-jars-pvc            
```
