### DISCUSSION TITLE
RESTEASY003210 issue

### DISCUSSION THREAD

**Discussion by amace-lzo** [keycloak/keycloak#16390] [Q&A]
Hi, I'm new for keycloak. I met RESTEASY003210 issue.

### Environment
**Dockerfile:**
```
FROM quay.io/keycloak/keycloak:19.0.0

COPY keycloak.conf /opt/keycloak/conf/keycloak.conf

COPY quarkus.properties /opt/keycloak/conf/quarkus.properties

COPY themes /opt/keycloak/themes

EXPOSE 8080

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev"]
```

**keycloak.conf:**
```
log=console,file
log-format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n
log-level=info,org.keycloak.truststore:debug,org.keycloak.events:debug,org.infinispan:info
```

**quarkus.properties:**
```
quarkus.log.file.rotation.max-file-size=10M
quarkus.log.file.rotation.max-backup-index=30
quarkus.log.file.rotation.file-suffix=.yyyy-MM-dd
quarkus.log.file.rotation.rotate-on-boot=true
```

**Docker-compose:**
```
version: '3.7'

services:
  keycloak:
    image: keycloak:latest
    environment:
      KC_DB: mariadb
      KC_DB_URL: jdbc:mariadb://127.0.0.1:3306/keycloak?characterEncoding=UTF-8&useSSL=false&autoReconnect=true
      KC_DB_USERNAME: username
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_LOG_LEVEL: debug
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4096M
    restart: always
```

### Background
When I start the rest service, keycloak works fine. But after a few minutes, the request to keycloak is unresponsive. 

### Keycloak Log
Error response 404: javax.ws.rs.NotFoundException: RESTEASY003210: Could not find resource for full path: http://check.best-proxies.ruhttp://check.best-proxies.ru/ip.php?Z72350101880Q1
<img width="1887" alt="image" src="https://user-images.githubusercontent.com/29742283/211790002-a9056875-9c08-486c-9a4b-c28ca485677f.png">
Has anyone encountered the same problem?
