### DISCUSSION TITLE
Token issuer is not based on the incoming request

### DISCUSSION THREAD

**Discussion by bbednarek** [keycloak/keycloak#16482] [Archive]
## Setup

I migrated from `quay.io/keycloak/keycloak:18.0.2-legacy` to `quay.io/keycloak/keycloak:18.0.2`. 
I am running Keycloak in Kubernetes in HA mode. It's behind istio proxy. 

There are 3 different ways to access it:
1. public domain `https://auth.mycompany.com`
2. private network  `https://auth.mycompany.internal.io` 
3. Kubelet Pods' DNS in `auth` Kubernetes namespace `http://main-keycloak-http.auth.svc`

### Dockerfile

```
FROM quay.io/keycloak/keycloak/keycloak:18.0.2

ENTRYPOINT [ "/opt/keycloak/bin/kc.sh" \
             ,"--verbose" \
             ,"start" \
             ,"--proxy=edge" \
             ,"--auto-build" \
             ,"--http-relative-path=/auth" \
             ,"--hostname-strict=false" \
             ,"--health-enabled=true" \
             ,"--metrics-enabled=true" \
             ,"--features=token-exchange,admin-fine-grained-authz" \
]
```

### Env variables
```
KEYCLOAK_ADMIN=(loaded from secrets)
KEYCLOAK_ADMIN_PASSWORD=(loaded from secrets)
JAVA_OPTS_APPEND="-Djgroups.dns.query=keycloak-headless"
KC_CACHE=ispn
KC_CACHE_STACK=kubernetes
```

## Problem 
After migration to Quarkus version of keycloak I see the following error on the client side:
```
The Issuer "https://main-keycloak-http.auth.svc/auth/realms/sme" provided in the configuration metadata 
did not match the requested issuer "http://main-keycloak-http.auth.svc:8080/auth/realms/sme"
```
On the client side I am using spring security with the following configuration:
```
spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: ${keycloak.client-id}
            client-secret: ${keycloak.client-secret}
        provider:
          keycloak:
            issuer-uri: "http://main-keycloak-http.auth.svc:8080/auth/realms/sme"
```

I see that the following curl from inside k8s pod
```
curl --data "grant_type=client_credentials&client_id=<CLIENT_ID>&client_secret=<CLIENT_SECRET>" \ 
  http://main-keycloak-http.auth.svc:8080/auth/realms/sme/protocol/openid-connect/token
```
returns valid JWT token which has issuer claim 
```
"iss": "https://main-keycloak-http.auth.svc/auth/realms/sme",
```
instead of
```
"iss": "http://main-keycloak-http.auth.svc:8080/auth/realms/sme", 
```
I haven't change anything on the client side. Only server got upgraded to Keycloak Quarkus version. 

#### hostname-strict-https
I tried to add following property to the ENTRYPOINT
```
--hostname-strict-https=false
```
but then `iss` claim is missing port  `8080` and it looks like this 
```
"iss": "http://main-keycloak-http.auth.svc/auth/realms/sme",
```

#### Drop `issuer-uri` in favour of `authorization-uri` and `token-uri`
```
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: "http://main-keycloak-http.auth.svc:8080/auth/realms/sme/protocol/openid-connect/auth"
            token-uri: "http://main-keycloak-http.auth.svc:8080/auth/realms/sme/protocol/openid-connect/token"
```

It works, but it's not desired solution, because JWKS won't work out of the box.

## Question
Accordingly to [Keycloak documentation](https://www.keycloak.org/server/hostname#_backend) if `--hostname-strict-backchannel=false` (which is default value)
> By default, the URLs for backend endpoints are also based on the incoming request.

It works for 1. public domain and 2. private network, but it doesn't for 3. Kubelet Pods' DNS.

Defining `hostname-url` param is also not an option, because I am running Keycloak behind a proxy.

Could you tell me how can I fix it?
