### DISCUSSION TITLE
Operator - how to use file based vault in Kubernetes?

### DISCUSSION THREAD

**Discussion by RichardSufliarsky** [keycloak/keycloak#16615] [Q&A]
Hi, I am trying to use file based vault with keycloak-operator.v20.0.3 according to this: https://www.keycloak.org/server/vault

Please, can you help me to make it work?

Tried to enable it with `vault-dir` option (see Keycloak CR below) and getting error when I want to use it in LDAP Bind credentials in the `master` realm.
![image](https://user-images.githubusercontent.com/31887324/214572464-2cc709e8-9825-437e-8f1b-f0e941d954d5.png)
When I click on `Test authentication`, I see in the tcpdump's output that there is `${vault.freeipa-pass}` string sent as password.

I see secret mounted in the container:
```
bash-4.4$ ls /vault
master_freeipa-pass
```
Keycloak CR:
```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak-dev
  namespace: dev-keycloak
spec:
  additionalOptions:
  - name: vault-dir
    value: /vault
  unsupported:
    podTemplate:
      spec:
        containers:
        - name: keycloak        
          volumeMounts:
          - name: vault
            mountPath: "/vault"
            readOnly: true
        volumes:
        - name: vault
          secret:
            secretName: vault
```
Secret:
```
kind: Secret
apiVersion: v1
metadata:
  name: vault
  namespace: dev-keycloak
data:
  master_freeipa-pass: *****
type: Opaque
```
