### DISCUSSION TITLE
Node.js throw (wrong ISS) error when connecting to keycloak

### DISCUSSION THREAD

**Discussion by Med-El-Mobarik** [keycloak/keycloak#19159] [Q&A] [answered]
I'm building an application with nestjs and keycloak. I'm running the services (postgres, keycloak, nestjs) with a docker-compose file

this is my docker-compose file:

```
version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
  keycloak:
    image: jboss/keycloak
    environment:
      DB_USER: keycloak
      DB_PASSWORD: password
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8080:8080
    depends_on:
      - postgres
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: backend
    ports:
      - 3000:3000
    depends_on:
      - keycloak
```

The keycloak service seems to work properly. But when I try to validate a token with keycloak from nestjs I got an error: **`WARN [Keycloak] Cannot validate access token: Error: Grant validation failed. Reason: invalid token (wrong ISS)`**

this is the configuration I'm using in nestjs:

```
KC_URL=http://keycloak:8080/auth
KC_REALM=Phoenix
KC_CLIENT_ID=nest-app
KC_SECRET=w5kChVCDCXStX6GoSGZ6z89WMMVT4cB3
```

**The Phoenix realm and the nest-app client are created properly**

this is the image I'm using for nestjs:

```
FROM node:18.14.1-buster

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install 
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

#run the project
CMD [ "npm", "run", "start:dev" ]
```

**Additional informations:**

1. When the nestjs app is running on local (not on docker) it connects keycloak with no errors, but when I use docker to run the app it doesn't work
2. the services are in the same network
3. I'm using this package to connect to keycloak [nest-keycloak-connect](https://www.npmjs.com/package/nest-keycloak-connect)
4. I can ping keycloak from backend
