### DISCUSSION TITLE
Setting Oracle DB v$session properties for Keycloak Quarkus jdbc connection

### DISCUSSION THREAD

**Discussion by hill-daniel** [keycloak/keycloak#19277] [Q&A] [answered]
Hello, I am unable to configure additional properties for an Oracle Database connection.
I.e. in Java, you can configure V$SESSION properties upon connecting to a Oracle DB using the JDBC Thin driver the following way:
```JAVA
Properties p = new java.util.Properties();
p.put("v$session.osuser", "ca_user");         
p.put("v$session.machine", "deployment_dev123");         
p.put("v$session.program", "token_service");

// get connection with properties...
```
Or configure a DataSource with Spring | Boot (w/ Hikari):

```yaml
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.OracleDriver
    username: username
    password: password
    data-source-properties: |
      v$session.program: token_service
      v$session.osuser: ca_user
      v$session.machine: deployment_dev123 
```
This sets fields of the V$SESSION table.

I've been trying to achieve the same thing with Keycloak and Quarkus, but to no avail.
I tried: 
- adding quarkus.properties to /opt/keycloak/conf with content: quarkus.datasource.jdbc.additional-jdbc-properties.connectionProperties="v$session.OSUSER=MY_USER"
- using db-url-properties in keycloak config
- adapting the db-url to contain the clientId like so: _jdbc:oracle:thin:@localhostL1521:XE?clientId={OSUSER=myuser,PROGRAM=myprogram,MACHINE=mymachine}_ (results in keycloak not even starting)
- setting system property with -Doracle.jdbc.v\$session.osuser="ca_user" with JAVA_OPTS_APPEND env variable

Is this even possible? If so, how?
