### DISCUSSION TITLE
How to migrate data from old WildFly distribution to the new Quarkus one (master realm included)

### DISCUSSION THREAD

**Discussion by LucasVanHaaren** [keycloak/keycloak#19545] [Q&A] [answered]
Hello everyone :wave:,

I've been working for several days now on the migration of a keycloak instance based on the old WildFly distribution (`19.0.3-legacy`) to the new one based on Quarkus (`19.0.3`), but I'm stuck on the data migration (realms configuration, users).

I think that the problem comes from the import on the quarkus instance. 
I tried several import methods (at startup with `--import-realm`, manually with `kc.sh import`, with `kcadm.sh update realms/master -f ...`, with keycloak-config-cli) but I always get errors like 'Importing master realm, skipping it already exists' or '403 Forbidden' ...

I have the impression that it is impossible to import an existing master realm (even by merging it), yet it is necessary in my case to migrate from one distribution to another. I am pretty confused between the old and the new documentation and it is never mentioned how to import and override a realm.

FYI my environment is a Kubernetes cluster, the 2 instances are deployed in separate namespaces. The first instance is deployed by the codecentric helm chart (image `quay.io/keycloak/keycloak:19.0.3-legacy`), the second is deployed by the bitnami helm chart (image `
docker.io/bitnami/keycloak:19.0.3-debian-11-r15`).

If anyone has any suggestions on what I should try or if there is a know process to do this kind of migration I'd love to hear them. 
I'll post the logs/traces of the different attempts if needed.

Thanks in advance :heart:

**Comment by adamency** [comment]


**Reply by LucasVanHaaren** [reply, marked as answer]
Yep, I finally abandoned the idea of using an export/import method like keycloak-config-cli.

I simply achieved the migration by using the same instance version (and same database version too), then dumping and restoring the database from the Wildfly one to the Quarkus one !

**Reply by adamency** [reply]
Well I managed to get it to work in the end, had a different problem than you actually. But thanks in any case for answering.

**Comment by adamency** [comment]
FWIW I managed to perfectly import everything including the master realm with `--import-realm` at startup from a `17.0.1-legacy` to a `26.0.0`. Seems you had some wrong configuration or version `19.x` had some bugs.

As per [documentation](https://www.keycloak.org/server/importExport):

```
By default, the --override option is set to true so that realms are always overridden with the new configuration.
```

**Reply by LucasVanHaaren** [reply]
Okay thanks for the information !

**Reply by huntx** [reply]
@adamency Would you mind to share the brief steps you used to upgrade to 26.0.0 ?

**Reply by huntx** [reply]
Update, I managed to upgrade 1.16.1 to 26.0.5.
Btw, my existing setup only involve single realm - master. I not sure if this work for setup that involve multiple realms.

The most important is the variables translation of WildFly to Quarkus.

1.16.1
--------
```
  keycloak:
    image: jboss/keycloak:latest
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: <db-user>
      DB_PASSWORD: <db-password>
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: <admin-password>
      PROXY_ADDRESS_FORWARDING: "true"
      REDIRECT_SOCKET: "proxy-https"
      KEYCLOAK_FRONTEND_URL: https://keycloak.domain/kc
```
      
26.0.5
--------
```
 keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    command: start
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: <admin-password>
      KC_HEALTH_ENABLED: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME:  https://keycloak.domain/kc/
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: true
      KC_PROXY_HEADERS: forwarded
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_PROXY_ADDRESS_FORWARDING: true
      KC_HOSTNAME_STRICT_BACKCHANNEL: true
      KC_PROXY: edge
      KC_DB: mysql
      KC_DB_URL: 'jdbc:mysql://mysql:3306/keycloak'
      KC_DB_SCHEMA: keycloak
      KC_DB_USERNAME: <db-user>
      KC_DB_PASSWORD: <db-password>
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: <admin-password>  
```
