### DISCUSSION TITLE
How can i save keycloak configuration with postgres in a docker-compose?

### DISCUSSION THREAD

**Discussion by brayanjeshua** [keycloak/keycloak#19962] [Q&A] [answered]
Until now this is my compose i'm using keycloak in development but i want to use a new container as **keycloak-db** to store and persist the whole configuration of realms / users / groups ...

```
version: '3.3'

services:
  #   keycloak-db:
  #     image: postgres:13-alpine
  #     ports:
  #       - 5432
  #     logging:
  #       options:
  #         max-size: "10m"
  #         max-file: "3"
  #     volumes:
  #       - ./keycloak-db-data:/var/lib/postgresql/data
  #     environment:
  #       POSTGRES_USER: postgres
  #       POSTGRES_PASSWORD: postgres
  #       POSTGRES_DB: keycloak
  #     healthcheck:
  #       test: pg_isready || exit 1
  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    restart: always
    env_file:
      - .env
    ports:
      - "${KEYCLOAK_PORT}:8080"
    command: start-dev
# networks:
#   app-tier:
#     driver: bridge
# volumes:
#   keycloak-db-data:
```

**Comment by slominskir** [comment]
Here is an example docker compose project that configures Keycloak container to a database container:

https://github.com/slominskir/keycloak_oracle

The example uses Oracle database, but using Postgres will be very similar.

**Comment by souravs17031999** [comment]
@brayanjeshua , check this below.

Btw, any exact issue/error are you facing ?

```
iam:
      image: quay.io/keycloak/keycloak:21.1.1
      environment:
        - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak
        - KC_DB_USERNAME=postgres
        - KC_DB_PASSWORD=postgres
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
      depends_on:
        - postgres

```
