### DISCUSSION TITLE
Cross-site and Infinispan: errors configuring caches

### DISCUSSION THREAD

**Discussion by piettes** [keycloak/keycloak#19992] [Archive]
I am trying to have a cross site setup, dc1 & dc2, with dc2 as a backup.

For this I use the new storage to use a custom Infinispan for session data and a jpa database for the rest.

```yml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  instances: 1
  db:
    host: postgres-db
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
  http:
    tlsSecret: example-tls-secret
  hostname:
    hostname: kc.dc1.de
  transaction:
    xaEnabled: false
  additionalOptions:
    - name: storage
      value: jpa
    - name: storage-hotrod-host
      value: "infinispan"
    - name: storage-hotrod-port
      value: "11222"
    - name: storage-hotrod-password
      value: "joFpmYMtnxaqTZHl"
    - name: storage-hotrod-username
      value: "developer"
    - name: storage-area-action-token
      value: hotrod
    - name: storage-area-auth-session
      value: hotrod
    - name: storage-area-single-use-object
      value: hotrod
    - name: storage-area-user-session
      value: hotrod
```

This works fine, and after logging into Keycloak, I can see the Infinispan console that some caches are created, for example `auth-sessions`:
```yml
auth-sessions: 
  distributedCache: 
    mode: "SYNC"
    remoteTimeout: "17500"
    statistics: "true"
    encoding: 
      mediaType: "application/x-protostream"
    locking: 
      concurrencyLevel: "1000"
      isolation: "REPEATABLE_READ"
      acquireTimeout: "15000"
      striping: "false"
    transaction: 
      mode: "FULL_XA"
    indexing: 
      enabled: "true"
      storage: "local-heap"
      indexedEntities: 
        - "kc.HotRodRootAuthenticationSessionEntity"
    stateTransfer: 
      timeout: "60000"
```

Question 1:  to make those caches replicated on other data centers, I need to add

```yml
    backups: 
      infinispan-dc2: 
        backup: 
          strategy: "ASYNC"
```
Where I am supposed to change that ? 

Question 2:  I would like to create those caches objects on dc2, using the .yml.
But when I do so, I get an error:
> ... Caused by: org.infinispan.commons.CacheConfigurationException: ISPN028022: The declared indexed type 'kc.HotRodRootAuthenticationSessionEntity' is not known. Please register its proto schema file first
  The declared indexed type 'kc.HotRodRootAuthenticationSessionEntity' is not known. Please register its proto schema file first

Is there a way to define those caches manually ?
