### DISCUSSION TITLE
Certificate based authentication from Keycloak to Postgresql

### DISCUSSION THREAD

**Discussion by jameshcovington** [keycloak/keycloak#20760] [Archive]
I'm trying to launch the latest keycloak 21.1.1 as a docker container with postgresql 15 as the external database, also part of the same docker-compose project.
I think I've configured postgresql correctly, enabling client ssl authentication through pg_hba.conf and pg_ident.conf
pg_hba.conf:
```
local   all             all                                     trust
host    all             all             127.0.0.1/32            trust
hostssl all             all             all                     cert clientname=CN clientcert=verify-full map=certmap
```
and pg_ident.conf:
```
certmap     keycloak          application_user
```
In my database I have a role named application_user, and in my keycloak instance I have a certificate with "CN=keycloak"
However, in all my attempts to configure keycloak with the correct parameters for this connection, the keycloak instance never attempts to send its client certificate. I have gotten the postgresql host certificate validation to succeed, but that's as far as it goes.
Both the keycloak and postgresql certs are signed by the same local root CA.

Here's a snippet of my docker-compose.yml:
```
  keycloak:
      image: quay.io/keycloak/keycloak:21.1.1
      depends_on:
         - postgresql
      environment:
        - KC_DB=postgres
        - KC_TRANSACTION_XA_ENABLED=false
        - KC_HTTPS_KEY_STORE_FILE=/etc/pki/tls/certs/keycloak.jks
        - KC_HTTPS_KEY_STORE_PASSWORD=keypass
        - KC_HTTPS_KEY_STORE_TYPE=pkcs12
        - KC_HTTPS
        - KC_HOSTNAME=keycloak
        - KC_DB_URL_HOST=postgresql
        - KC_DB_URL_PORT=5432
        - KC_DB_URL_PROPERTIES=?ssl=true&sslrootcert=/etc/pki/tls/certs/keycloak-ca/ca-root.pem&sslmode=require&sslkey=/etc/pki/tls/certs/keycloak.p12&sslpassword=xxxx
        - JAVA_TOOL_OPTIONS=-Djavax.net.debug=ssl,handshake
      command: start
      ports:
        - "8443:8443"
        - "8080:8080"
        - "9990:9990"
      volumes:
        - keycloak_certs:/etc/pki/tls/certs
```

Has anyone succeeded with this? Inquiring minds want to know!
