### DISCUSSION TITLE
Deploying keycloak on an internal, closed network

### DISCUSSION THREAD

**Discussion by saevarb** [keycloak/keycloak#21096] [Q&A]
Hi.

We have built an application which uses keycloak as auth provider, and for one of our customers, we need to deploy our application on a closed, internal network.

I can get everything working just fine with keycloak running in development mode, but ideally, that should not be the end result. We are trying to deploy everything with https enabled, in part because as far as I've understood, this is required by keycloak but naturally also for security. We have certificates and related infrastructure to make that work, but I'm still running into problems.

The relevant parts of the system are a web application, which interacts with keycloak from its backend to create users and such, and also needs to redirect to it for authentication and back. Everything is run via docker-compose. 

I've been trying various things, such as putting everything behind a reverse proxy, but this ends up requiring extra configuration, possibly something with `hostname-path` or `http-relative-path` which I've not managed to get working -- I end up with some redirect errors, and I'm honestly not sure whether this is my proxy that is misconfigured or something to do with keycloak. I've also tried not using a reverse proxy for keycloak and instead handing it the certificate, and while this is close to working, I end up having issues when it comes to communication between the backend and keycloak. 

Does anyone have any recommendations/tips or possibly guides for this sort of setup? I'd really appreciate any and all pointers and of course, if you need any more info, don't hesitate to ask. 

Thanks for your time.

**Comment by Chri-s** [comment]
Hi,

we use a similar configuration (running keycloak on an internal network behind a reverse proxy). Keycloak and Postgresql run as docker containers via docker-compose, but the reverse proxy is apache running on the docker host (natively, not as a docker container).
The relevant keycloak configuration in our setup is:

```yaml
environment:
  - KC_DB=postgres
  - KC_DB_URL_HOST=postgres
  - KC_DB_URL_DATABASE=keycloak
  - KC_DB_USERNAME=keycloak
  - KC_DB_PASSWORD=dbpwd
  - KC_HOSTNAME=auth.xyz.local # this is the external url, on which the reverse proxy listens to
  - KC_PROXY=edge
  - KC_HTTP_ENABLED=true
ports:
  - 127.0.0.1:8081:8080 # Keycloak only listens on localhost:8081, which is the port the local reverse proxy uses to connect. That way keycloak is not reachable directly from other hosts
depends_on:
  - postgres
```

And this is our apache configuration for the reverse proxy:

```ApacheConf
<VirtualHost *:80>
  # Redirect HTTP to HTTPS
  ServerName auth.xyz.local
  ServerAlias auth

  RewriteEngine On
  RewriteRule ^/?(.*) https://auth.xyz.local/$1 [R,L]
</VirtualHost>

<VirtualHost *:443>
  ServerName auth.xyz.local

  SSLEngine On
  SSLProtocol All -SSLv2 -SSLv3
  SSLHonorCipherOrder On
# Change pathes to your certificates
  SSLCertificateFile      /etc/ssl/mycerts/auth.xyz.local.crt
  SSLCertificateKeyFile   /etc/ssl/private/auth.xyz.local.key
  SSLCACertificateFile    /etc/ssl/mycerts/xyz-ca.pem
  ServerSignature Off

# Don't allow clients to send reverse proxy headers
  RequestHeader unset X-Forwarded-For
  RequestHeader unset X-Forwarded-Host
  RequestHeader unset X-Forwarded-Proto
  RequestHeader unset X-Forwarded-Server
  RequestHeader unset X-Forwarded-SSL
  RequestHeader unset Forwarded

  ProxyRequests off
  ProxyPreserveHost On
  RequestHeader set "X-Forwarded-Proto" https
  RemoteIPHeader X-Forwarded-For

  ProxyPass / http://127.0.0.1:8081/ retry=0
</VirtualHost>
```

When you visit https://auth.xyz.local/ you connect to the reverse proxy which proxies the request to http://127.0.0.1:8081/ where keycloak listens.
Because we set the keycloak ENV KC_PROXY=edge and apache sets the header `X-Forwarded-Proto` to `https` and `X-Forwarded-For` to the client ip address, keycloak knows that the connection was made via https and the client's ip address occurres in all keycloak logs.

Does this help you?
