### DISCUSSION TITLE
Unsupported database file version Error after upgrading

### DISCUSSION THREAD

**Discussion by 0195b3a7cb6735967a8f** [keycloak/keycloak#21628] [Q&A]
Hello,

I use Keycloak in a Docker Container and after upgrading the image, my DB seems to be broken. When i start Keycloak, I get following Error:
```
The write format 2 is smaller than the supported format 3
```

Full Logs:
<section>
  <details>

  ```
  keycloak-keycloak-1  | 2023-07-12 10:02:34,452 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: <request>, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: -1, Proxied: true
  keycloak-keycloak-1  | 2023-07-12 10:02:36,828 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
  keycloak-keycloak-1  | 2023-07-12 10:02:37,302 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': Unsupported database file version or invalid file header in file "/opt/keycloak/data/h2/keycloakdb.mv.db" [90048-220]
  keycloak-keycloak-1  | 2023-07-12 10:02:37,303 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread) HHH000342: Could not obtain connection to query metadata: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Unsupported database file version or invalid file header in file "/opt/keycloak/data/h2/keycloakdb.mv.db" [90048-220]
  keycloak-keycloak-1  |  at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
  keycloak-keycloak-1  |  at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
  keycloak-keycloak-1  |  at org.h2.message.DbException.get(DbException.java:212)
  keycloak-keycloak-1  |  at org.h2.mvstore.db.Store.convertMVStoreException(Store.java:158)
  keycloak-keycloak-1  |  at org.h2.mvstore.db.Store.<init>(Store.java:142)
  keycloak-keycloak-1  |  at org.h2.engine.Database.<init>(Database.java:324)
  keycloak-keycloak-1  |  at org.h2.engine.Engine.openSession(Engine.java:92)
  keycloak-keycloak-1  |  at org.h2.engine.Engine.openSession(Engine.java:222)
  keycloak-keycloak-1  |  at org.h2.engine.Engine.createSession(Engine.java:201)
  keycloak-keycloak-1  |  at org.h2.engine.SessionRemote.connectEmbeddedOrServer(SessionRemote.java:338)
  keycloak-keycloak-1  |  at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:122)
  keycloak-keycloak-1  |  at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:322)
  keycloak-keycloak-1  |  at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:232)
  keycloak-keycloak-1  |  at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:536)
  keycloak-keycloak-1  |  at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:517)
  keycloak-keycloak-1  |  at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  keycloak-keycloak-1  |  at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
  keycloak-keycloak-1  |  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
  keycloak-keycloak-1  |  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  keycloak-keycloak-1  |  at java.base/java.lang.Thread.run(Thread.java:833)
  keycloak-keycloak-1  | Caused by: org.h2.mvstore.MVStoreException: The write format 2 is smaller than the supported format 3 [2.2.220/5]
  keycloak-keycloak-1  |  at org.h2.mvstore.DataUtils.newMVStoreException(DataUtils.java:996)
  keycloak-keycloak-1  |  at org.h2.mvstore.FileStore.getUnsupportedWriteFormatException(FileStore.java:944)
  keycloak-keycloak-1  |  at org.h2.mvstore.FileStore.processCommonHeaderAttributes(FileStore.java:547)
  keycloak-keycloak-1  |  at org.h2.mvstore.RandomAccessStore.readStoreHeader(RandomAccessStore.java:227)
  keycloak-keycloak-1  |  at org.h2.mvstore.FileStore.start(FileStore.java:917)
  keycloak-keycloak-1  |  at org.h2.mvstore.MVStore.<init>(MVStore.java:289)
  keycloak-keycloak-1  |  at org.h2.mvstore.MVStore$Builder.open(MVStore.java:2036)
  keycloak-keycloak-1  |  at org.h2.mvstore.db.Store.<init>(Store.java:133)
  keycloak-keycloak-1  |  ... 15 more
  keycloak-keycloak-1  |
  ```

  </details>
</section>

Command i used to upgrade:
```bash
docker compose pull && docker compose up -d
```

My `docker-compose.yml` looks like this:

<section>
  <details>

  ```yml
  version: "3"
  services:
    postgres:
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: <POSTGRES_PASSWORD>
      volumes:
        - POSTGRES-DATA:/var/lib/postgresql/data


    keycloak:
      image: quay.io/keycloak/keycloak:latest
      restart: always
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: <ADMIN_PASSWORD>
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_PORT: 5432
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: <POSTGRES_PASSWORD>
        PROXY_ADDRESS_FORWARDING: true
      volumes:
        - ./rootca.jks:/opt/keycloak/rootca.jks
        - KEYCLOAK-DATA:/opt/keycloak/data
      ports:
        - 8080:8080
        - 8443:8443
      depends_on:
        - postgres
      command:
        - start
        - --proxy=edge
        - --hostname-strict=false
        - --spi-truststore-file-file=/opt/keycloak/rootca.jks
        - --spi-truststore-file-password=<TRUSTSORE_PASSWORD>
        - --spi-truststore-file-hostname-verification-policy=STRICT


  volumes:
    POSTGRES-DATA:
    KEYCLOAK-DATA:
  ```
  
  </details>
</section>

It also looks like that Keycloak isnt using my Postgres DB. Im completly new to Docker and Keycloak so there might be an issue in my file.
