### DISCUSSION TITLE
Keyclaok 21.0.0 with external infinispan 14.0.7.final. Setup is working but unable to view cache entries in remote infinispan.

### DISCUSSION THREAD

**Discussion by prashankjauhari** [keycloak/keycloak#21890] [Archive]
Hi All,

We are trying to use a external infinispan cluster for remote storage for keycloak's distributed and replicated cache. We are able to setup 2 standalone nodes of keycloak connecting with external infinispan cluster of 2 nodes. We are able to login in keycloak admin console. Token are getting generated and validated across all the nodes. Sessions are also getting expired. But when i move to infinispan nodes and try to see the content of the cache. That window just keeps on loading and in infinispan server logs i get following exception. This seems to be some encoding issue and i tried multiple solution but nothing seems to work. Is it a bug?

at io.reactivex.rxjava3.internal.operators.flowable.FlowableDoOnLifecycle.subscribeActual(FlowableDoOnLifecycle.java:39)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15863)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableScalarXMap$ScalarXMapFlowable.subscribeActual(FlowableScalarXMap.java:160)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15863)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableDefer.subscribeActual(FlowableDefer.java:42)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15863)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableRepeatUntil$RepeatSubscriber.subscribeNext(FlowableRepeatUntil.java:109)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableRepeatUntil.subscribeActual(FlowableRepeatUntil.java:38)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:38)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableTake.subscribeActual(FlowableTake.java:35)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15863)
	at org.infinispan.rest.stream.CacheEntryStreamProcessor.subscribe(CacheEntryStreamProcessor.java:52)
	at org.infinispan.rest.ResponseWriter$4.writeResponse(ResponseWriter.java:88)
	at org.infinispan.rest.RestRequestHandler.lambda$sendResponse$0(RestRequestHandler.java:107)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:403)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:834)
**Caused by: java.lang.ClassNotFoundException: org.infinispan.commons.marshall.Externalizer**
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 73 more

![infinispan](https://github.com/keycloak/keycloak/assets/16600147/e1c0852a-3f88-443c-b078-dee20227e4ed)

This cache currently have 20K entries and it is visible in infinispan global statistics  also and same can be seen on keycloak nodes. But this infinispan admin console just keeps on loading.

This is the cache-ispn file for keycloak nodes

```
<?xml version="1.0" encoding="UTF-8"?>
<infinispan xmlns="urn:infinispan:config:13.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:infinispan:config:13.0 http://www.infinispan.org/schemas/infinispan-config-13.0.xsd">
   <jgroups>
      <stack name="fileping" extends="tcp">
         <FILE_PING location="./ping_dir" 
                stack.combine="REPLACE" 
                  stack.position="MPING"
         />
      </stack>
   </jgroups>
   <cache-container name="keycloak">
      <transport cluster="${infinispan.cluster.name:globalCluster}" lock-timeout="60000" stack="fileping" site="site1" />
      <local-cache name="realms">
         <encoding>
            <key media-type="application/x-java-object" />
            <value media-type="application/x-java-object" />
         </encoding>
         <memory max-count="10000" />
      </local-cache>
      <local-cache name="users">
         <encoding>
            <key media-type="application/x-java-object" />
            <value media-type="application/x-java-object" />
         </encoding>
         <memory max-count="10000" />
      </local-cache>
      <local-cache name="authorization">
         <encoding>
            <key media-type="application/x-java-object" />
            <value media-type="application/x-java-object" />
         </encoding>
         <memory max-count="10000" />
      </local-cache>
      <local-cache name="keys">
         <encoding>
            <key media-type="application/x-java-object" />
            <value media-type="application/x-java-object" />
         </encoding>
         <expiration max-idle="3600000" />
         <memory max-count="1000" />
      </local-cache>
      <distributed-cache name="sessions" owners="1">
         <remote-store xmlns="urn:infinispan:config:store:remote:13.0" cache="sessions" purge="false" preload="false" segmented="false" shared="true" raw-values="true" marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
            <remote-server host="infinispan.node.one" port="11333" />
            <security>
               <authentication server-name="infinispan">
                  <digest username="admin" password="password" realm="default" />
               </authentication>
            </security>
         </remote-store>
      </distributed-cache>
      <distributed-cache name="authenticationSessions" owners="1">
         <remote-store xmlns="urn:infinispan:config:store:remote:13.0" cache="authenticationSessions" purge="false" preload="false" segmented="false" shared="true" raw-values="true" marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
            <remote-server host="infinispan.node.one" port="11333" />
            <security>
               <authentication server-name="infinispan">
                  <digest username="admin" password="password" realm="default" />
               </authentication>
            </security>
         </remote-store>
      </distributed-cache>
      <distributed-cache name="offlineSessions" owners="1">
         <remote-store xmlns="urn:infinispan:config:store:remote:13.0" cache="offlineSessions" purge="false" preload="false" segmented="false" shared="true" raw-values="true" marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
            <remote-server host="infinispan.node.one" port="11333" />
            <security>
               <authentication server-name="infinispan">
                  <digest username="admin" password="password" realm="default" />
               </authentication>
            </security>
         </remote-store>
      </distributed-cache>
      <distributed-cache name="clientSessions" owners="1">
         <remote-store xmlns="urn:infinispan:config:store:remote:13.0" cache="clientSessions" purge="false" preload="false" segmented="false" shared="true" raw-values="true" marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
            <remote-server host="infinispan.node.one" port="11333" />
            <security>
               <authentication server-name="infinispan">
                  <digest username="admin" password="password" realm="default" />
               </authentication>
            </security>
         </remote-store>
      </distributed-cache>
      <distributed-cache name="offlineClientSessions" owners="1">
         <remote-store xmlns="urn:infinispan:config:store:remote:13.0" cache="offlineClientSessions" purge="false" preload="false" segmented="false" shared="true" raw-values="true" marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
            <remote-server host="infinispan.node.one" port="11333" />
            <security>
               <authentication server-name="infinispan">
                  <digest username="admin" password="password" realm="default" />
               </authentication>
            </security>
         </remote-store>
      </distributed-cache>
      <distributed-cache name="loginFailures" owners="1">
         <remote-store xmlns="urn:infinispan:config:store:remote:13.0" cache="loginFailures" purge="false" preload="false" segmented="false" shared="true" raw-values="true" marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
            <remote-server host="infinispan.node.one" port="11333" />
            <security>
               <authentication server-name="infinispan">
                  <digest username="admin" password="password" realm="default" />
               </authentication>
            </security>
         </remote-store>
      </distributed-cache>
      <distributed-cache name="actionTokens" owners="1">
         <expiration max-idle="-1" interval="300000" />
         <remote-store xmlns="urn:infinispan:config:store:remote:13.0" cache="actionTokens" purge="false" preload="false" segmented="false" shared="true" raw-values="true" marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
            <remote-server host="infinispan.node.one" port="11333" />
            <security>
               <authentication server-name="infinispan">
                  <digest username="admin" password="password" realm="default" />
               </authentication>
            </security>
         </remote-store>
      </distributed-cache>
      <replicated-cache name="work">
         <remote-store xmlns="urn:infinispan:config:store:remote:13.0" cache="work" purge="false" preload="false" segmented="false" shared="true" raw-values="true" marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
            <remote-server host="infinispan.node.one" port="11333" />
            <security>
               <authentication server-name="infinispan">
                  <digest username="admin" password="password" realm="default" />
               </authentication>
            </security>
         </remote-store>
      </replicated-cache>
   </cache-container>
</infinispan>

```

And this is infinispan.xml file for infinispan cluster.

```
<?xml version="1.0" encoding="UTF-8"?>
<infinispan xmlns="urn:infinispan:config:14.0" xmlns:server="urn:infinispan:server:14.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:infinispan:config:14.0 https://infinispan.org/schemas/infinispan-config-14.0.xsd                             urn:infinispan:server:14.0 https://infinispan.org/schemas/infinispan-server-14.0.xsd">
   <jgroups>
      <stack name="ping-tcp" extends "tcp">

         <TCPPING async_discovery="true" 
                  initial_hosts="${jgroups.tcpping.initial_hosts:infinispan.node.one[7800],infinispan.node.one[7800]}" 
                  return_entire_cache="${jgroups.tcpping.return_entire_cache:false}" 
                  port_range="${jgroups.tcp.port_range:0}" 
                  stack.combine="REPLACE" 
                  stack.position="MPING"
         />

      </stack>
   </jgroups>

   <cache-container name="remoteKeycloak" statistics="true">

      <transport cluster="${infinispan.cluster.name:globalCluster}" 
                 stack="ping-tcp" 
                 node-name="${infinispan.node.name:secondaryNode}" 
                 site="globalSite" />

      <!-- <global-state>
            <persistent-location path="/data/node1"/>
      </global-state> -->

      <serialization marshaller="org.infinispan.jboss.marshalling.commons.GenericJBossMarshaller">
         <allow-list>
            <class>org.keycloak.cluster.infinispan.WrapperClusterEvent</class>
            <regex>.*</regex>
         </allow-list>
      </serialization>
      <security>
         <authorization />
      </security>

 <distributed-cache-configuration name="distributed-cfg"mode="SYNC">
         <locking acquire-timeout="20000" concurrency-level="8192"  striping= "false" isolation="READ_COMMITTED"/>
         <state-transfer timeout="1200000"/>
      <encoding>
         <key media-type="application/x-jboss-marshalling"/>
         <value media-type="application/x-jboss-marshalling"/>
      </encoding>

    <!-- <persistence passivation="false">
      <file-store shared="false" preload="true" fetch-state="true"
      read-only="false">
      <write-behind modification-queue-size="2048" />
      </file-store>
    </persistence> -->

</distributed-cache-configuration>


<replicated-cache-configuration name="replicated-cfg" mode="SYNC">
      <locking acquire-timeout="20000" concurrency-level="8192"  striping= "false" isolation="READ_COMMITTED"/>
      <state-transfer timeout="1200000"/>
      <encoding>
                <key media-type="application/x-jboss-marshalling"/>
                <value media-type="application/x-jboss-marshalling"/>
      </encoding>
<!-- <persistence passivation="false">
             <file-store
                   shared="false" preload="true"
                   fetch-state="true"
                     read-only="false"
                     >
              <write-behind modification-queue-size="2048" />
           </file-store>
        </persistence> -->
</replicated-cache-configuration>

      <replicated-cache name="work" configuration="replicated-cfg"/>

      <distributed-cache name="sessions" configuration="distributed-cfg" owners="2" />

      <distributed-cache name="authenticationSessions" configuration="distributed-cfg" owners="2" />

      <distributed-cache name="clientSessions" configuration="distributed-cfg" owners="2" />

      <distributed-cache name="offlineSessions" configuration="distributed-cfg" owners="2" />

      <distributed-cache name="offlineClientSessions" configuration="distributed-cfg" owners="2" />
      
      <distributed-cache name="actionTokens" configuration="distributed-cfg" owners="2" />
      
      <distributed-cache name="loginFailures" configuration="distributed-cfg" owners="2" />

   </cache-container>
   <server xmlns="urn:infinispan:server:13.0">
      <interfaces>
         <interface name="public">
            <inet-address value="${infinispan.bind.address:127.0.0.1}" />
         </interface>
      </interfaces>
      <socket-bindings default-interface="public" port-offset="${infinispan.socket.binding.port-offset:111}">
         <socket-binding name="default" port="${infinispan.bind.port:11222}" />
         <socket-binding name="memcached" port="11221" />
      </socket-bindings>
      <security>
         <credential-stores>
            <credential-store name="credentials" path="credentials.pfx">
               <clear-text-credential clear-text="secret" />
            </credential-store>
         </credential-stores>
         <security-realms>
            <security-realm name="default">
               <!-- Uncomment to enable TLS on the realm -->
               <!-- server-identities>
                  <ssl>
                     <keystore path="application.keystore"
                               password="password" alias="server"
                               generate-self-signed-certificate-host="localhost"/>
                  </ssl>
               </server-identities-->
               <properties-realm groups-attribute="Roles">
                  <user-properties path="users.properties" />
                  <group-properties path="groups.properties" />
               </properties-realm>
            </security-realm>
         </security-realms>
      </security>
      <endpoints socket-binding="default" security-realm="default">
         <endpoint>
            <hotrod-connector name="hotrod">
               <authentication>
                  <sasl mechanisms="DIGEST-MD5" server-name="infinispan" />
               </authentication>
            </hotrod-connector>
            <rest-connector name="rest" />
         </endpoint>
      </endpoints>
   </server>
</infinispan>

```

**Comment by theadarshsaxena** [comment]
Not sure the admin console has bug because same thing I am facing but alternatively you can retrieve data by sending the REST requests to the infinispan server.

**Comment by ashktn** [comment]
I had a similar issue on Keycloak 22 with an external infinispan 14, and was able to solve this by adding the required Keycloak libs in the infinispan server image. Here's the infinispan dockerfile that i used (includes postgresql because we are persisting the cache entries to the db - you might not need that)

```
FROM quay.io/infinispan/server:14.0

ENV KEYCLOAK_VERSION=22.0.5
ENV POSTGRESQL_JDBC_DRIVER_VERSION=42.5.4

RUN cd /opt/infinispan/server/lib && \
	curl -O https://jdbc.postgresql.org/download/postgresql-${POSTGRESQL_JDBC_DRIVER_VERSION}.jar && \
	curl -O https://repo1.maven.org/maven2/org/keycloak/keycloak-model-infinispan/${KEYCLOAK_VERSION}/keycloak-model-infinispan-${KEYCLOAK_VERSION}.jar && \
	curl -O https://repo1.maven.org/maven2/org/keycloak/keycloak-server-spi/${KEYCLOAK_VERSION}/keycloak-server-spi-${KEYCLOAK_VERSION}.jar && \
	curl -O https://repo1.maven.org/maven2/org/keycloak/keycloak-server-spi-private/${KEYCLOAK_VERSION}/keycloak-server-spi-private-${KEYCLOAK_VERSION}.jar && \
	curl -O https://repo1.maven.org/maven2/org/keycloak/keycloak-core/${KEYCLOAK_VERSION}/keycloak-core-${KEYCLOAK_VERSION}.jar && \
	cd -
```

![image](https://github.com/keycloak/keycloak/assets/6723913/56213f3d-0cb2-40d5-905e-50b3c5d5d8db)

**Comment by derlin** [comment]
@ashktn Could you please share your cache-ispn and infinispan configurations? I have been trying for days, impossible to start keycloak with remote infinispan locally (using keycloak 23.0.*)

**Reply by darius-m** [reply]
If it helps, we use the following configurations [for Infinispan](https://github.com/UPB-Admin/ansible-keycloak/blob/master/roles/infinispan/templates/infinispan-config.xml#L106) and [for Keycloak](https://github.com/UPB-Admin/ansible-keycloak/blob/master/roles/keycloak/templates/cache-ispn.xml#L30) respectively. Admittedly, they are a bit harder to read, since the configurations are in Ansible / Jinja2 template format to reduce clutter. The list of caches is [here](https://github.com/UPB-Admin/ansible-keycloak/blob/master/roles/keycloak/templates/cache-ispn.xml#L30). You may not need all configurations, such as persistence (to database) and security in the Infinispan configurations.

**Reply by ashktn** [reply]
@derlin here's the infinispan config on the Keycloak side. This config is persisting cache keys to PostgreSQL, but that part isn't necessary if you don't need it
I'm still testing this configuration in our staging environments and haven't yet moved to prod (we are still using Keycloak 12 on prod). But so far it's been working fine

`cache-ispn.xml`

```xml
<?xml version="1.0" encoding="UTF-8"?>

<infinispan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:infinispan:config:14.0 http://www.infinispan.org/schemas/infinispan-config-14.0.xsd"
    xmlns="urn:infinispan:config:14.0">

    <cache-container name="keycloak">
        <transport lock-timeout="60000"
            site="${env.SITE}" />
        <local-cache name="realms">
            <encoding>
                <key media-type="application/x-java-object" />
                <value media-type="application/x-java-object" />
            </encoding>
            <memory max-count="100000" />
        </local-cache>
        <local-cache name="users">
            <encoding>
                <key media-type="application/x-java-object" />
                <value media-type="application/x-java-object" />
            </encoding>
            <memory max-count="100000" />
        </local-cache>
        <local-cache name="authorization">
            <encoding>
                <key media-type="application/x-java-object" />
                <value media-type="application/x-java-object" />
            </encoding>
            <memory max-count="100000" />
        </local-cache>
        <local-cache name="keys">
            <encoding>
                <key media-type="application/x-java-object" />
                <value media-type="application/x-java-object" />
            </encoding>
            <expiration max-idle="3600000" />
            <memory max-count="100000" />
        </local-cache>

        <distributed-cache name="sessions">
            <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                cache="sessions"
                purge="false"
                preload="false"
                segmented="false"
                shared="true"
                raw-values="true"
                marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="${env.KEYCLOAK_REMOTE_ISPN_HOST}"
                    port="${env.KEYCLOAK_REMOTE_ISPN_PORT}" />
                <connection-pool max-active="${env.KEYCLOAK_REMOTE_ISPN_POOL_SIZE:10}"
                    exhausted-action="CREATE_NEW" />
                <security>
                    <authentication server-name="infinispan">
                        <digest username="${env.KEYCLOAK_REMOTE_ISPN_USERNAME}"
                            password="${env.KEYCLOAK_REMOTE_ISPN_PASSWORD}"
                            realm="default" />
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>
        <distributed-cache name="authenticationSessions">
            <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                cache="authenticationSessions"
                purge="false"
                preload="false"
                segmented="false"
                shared="true"
                raw-values="true"
                marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="${env.KEYCLOAK_REMOTE_ISPN_HOST}"
                    port="${env.KEYCLOAK_REMOTE_ISPN_PORT}" />
                <connection-pool max-active="${env.KEYCLOAK_REMOTE_ISPN_POOL_SIZE:10}"
                    exhausted-action="CREATE_NEW" />
                <security>
                    <authentication server-name="infinispan">
                        <digest username="${env.KEYCLOAK_REMOTE_ISPN_USERNAME}"
                            password="${env.KEYCLOAK_REMOTE_ISPN_PASSWORD}"
                            realm="default" />
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>
        <distributed-cache name="offlineSessions">
            <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                cache="offlineSessions"
                purge="false"
                preload="false"
                segmented="false"
                shared="true"
                raw-values="true"
                marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="${env.KEYCLOAK_REMOTE_ISPN_HOST}"
                    port="${env.KEYCLOAK_REMOTE_ISPN_PORT}" />
                <connection-pool max-active="${env.KEYCLOAK_REMOTE_ISPN_POOL_SIZE:10}"
                    exhausted-action="CREATE_NEW" />
                <security>
                    <authentication server-name="infinispan">
                        <digest username="${env.KEYCLOAK_REMOTE_ISPN_USERNAME}"
                            password="${env.KEYCLOAK_REMOTE_ISPN_PASSWORD}"
                            realm="default" />
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>
        <distributed-cache name="clientSessions">
            <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                cache="clientSessions"
                purge="false"
                preload="false"
                segmented="false"
                shared="true"
                raw-values="true"
                marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="${env.KEYCLOAK_REMOTE_ISPN_HOST}"
                    port="${env.KEYCLOAK_REMOTE_ISPN_PORT}" />
                <connection-pool max-active="${env.KEYCLOAK_REMOTE_ISPN_POOL_SIZE:10}"
                    exhausted-action="CREATE_NEW" />
                <security>
                    <authentication server-name="infinispan">
                        <digest username="${env.KEYCLOAK_REMOTE_ISPN_USERNAME}"
                            password="${env.KEYCLOAK_REMOTE_ISPN_PASSWORD}"
                            realm="default" />
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>
        <distributed-cache name="offlineClientSessions">
            <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                cache="offlineClientSessions"
                purge="false"
                preload="false"
                segmented="false"
                shared="true"
                raw-values="true"
                marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="${env.KEYCLOAK_REMOTE_ISPN_HOST}"
                    port="${env.KEYCLOAK_REMOTE_ISPN_PORT}" />
                <connection-pool max-active="${env.KEYCLOAK_REMOTE_ISPN_POOL_SIZE:10}"
                    exhausted-action="CREATE_NEW" />
                <security>
                    <authentication server-name="infinispan">
                        <digest username="${env.KEYCLOAK_REMOTE_ISPN_USERNAME}"
                            password="${env.KEYCLOAK_REMOTE_ISPN_PASSWORD}"
                            realm="default" />
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>
        <distributed-cache name="loginFailures">
            <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                cache="loginFailures"
                purge="false"
                preload="false"
                segmented="false"
                shared="true"
                raw-values="true"
                marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="${env.KEYCLOAK_REMOTE_ISPN_HOST}"
                    port="${env.KEYCLOAK_REMOTE_ISPN_PORT}" />
                <connection-pool max-active="${env.KEYCLOAK_REMOTE_ISPN_POOL_SIZE:10}"
                    exhausted-action="CREATE_NEW" />
                <security>
                    <authentication server-name="infinispan">
                        <digest username="${env.KEYCLOAK_REMOTE_ISPN_USERNAME}"
                            password="${env.KEYCLOAK_REMOTE_ISPN_PASSWORD}"
                            realm="default" />
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>
        <distributed-cache name="actionTokens">
            <expiration max-idle="-1"
                interval="300000" />
            <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                cache="actionTokens"
                purge="false"
                preload="false"
                segmented="false"
                shared="true"
                raw-values="true"
                marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="${env.KEYCLOAK_REMOTE_ISPN_HOST}"
                    port="${env.KEYCLOAK_REMOTE_ISPN_PORT}" />
                <connection-pool max-active="${env.KEYCLOAK_REMOTE_ISPN_POOL_SIZE:10}"
                    exhausted-action="CREATE_NEW" />
                <security>
                    <authentication server-name="infinispan">
                        <digest username="${env.KEYCLOAK_REMOTE_ISPN_USERNAME}"
                            password="${env.KEYCLOAK_REMOTE_ISPN_PASSWORD}"
                            realm="default" />
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>

        <replicated-cache name="work">
            <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                cache="work"
                purge="false"
                preload="false"
                segmented="false"
                shared="true"
                raw-values="true"
                marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="${env.KEYCLOAK_REMOTE_ISPN_HOST}"
                    port="${env.KEYCLOAK_REMOTE_ISPN_PORT}" />
                <connection-pool max-active="${env.KEYCLOAK_REMOTE_ISPN_POOL_SIZE:10}"
                    exhausted-action="CREATE_NEW" />
                <security>
                    <authentication server-name="infinispan">
                        <digest username="${env.KEYCLOAK_REMOTE_ISPN_USERNAME}"
                            password="${env.KEYCLOAK_REMOTE_ISPN_PASSWORD}"
                            realm="default" />
                    </authentication>
                </security>
            </remote-store>
        </replicated-cache>
    </cache-container>
</infinispan>
```

and the `infinispan.yml` server config

```yaml
infinispan:
  cacheContainer:
    caches:
      actionTokens:
        distributedCache:
          configuration: keycloak-distributed-cache-template
      authenticationSessions:
        distributedCache:
          configuration: keycloak-distributed-cache-template
      clientSessions:
        distributedCache:
          configuration: keycloak-distributed-cache-template
      loginFailures:
        distributedCache:
          configuration: keycloak-distributed-cache-template
      offlineClientSessions:
        distributedCache:
          configuration: keycloak-distributed-cache-template
      offlineSessions:
        distributedCache:
          configuration: keycloak-distributed-cache-template
      sessions:
        distributedCache:
          configuration: keycloak-distributed-cache-template
      work:
        replicatedCache:
          configuration: keycloak-replicated-cache-template
    distributedCacheConfiguration:
      encoding:
        mediaType: application/x-jboss-marshalling
      memory:
        maxCount: "100000"
      mode: SYNC
      name: keycloak-distributed-cache-template
      owners: 2
      persistence:
        passivation: "false"
        stringKeyedJdbcStore:
          dataSource:
            jndi-url: jdbc/postgres
          preload: "true"
          purge: "false"
          shared: "true"
          stringKeyedTable:
            createOnStart: "true"
            dataColumn:
              name: DATA
              type: BYTEA
            dropOnExit: "false"
            idColumn:
              name: ID
              type: VARCHAR(255)
            prefix: KC_ISPN_
            segmentColumn:
              name: S
              type: INT
            timestampColumn:
              name: TS
              type: BIGINT
          writeBehind:
            failSilently: "false"
            modificationQueueSize: "2048"
      statistics: "true"
    name: default
    replicatedCacheConfiguration:
      encoding:
        mediaType: application/x-jboss-marshalling
      memory:
        maxCount: "100000"
      mode: SYNC
      name: keycloak-replicated-cache-template
      persistence:
        passivation: "false"
        stringKeyedJdbcStore:
          dataSource:
            jndi-url: jdbc/postgres
          preload: "true"
          purge: "false"
          shared: "true"
          stringKeyedTable:
            createOnStart: "true"
            dataColumn:
              name: DATA
              type: BYTEA
            dropOnExit: "false"
            idColumn:
              name: ID
              type: VARCHAR(255)
            prefix: KC_ISPN_
            segmentColumn:
              name: S
              type: INT
            timestampColumn:
              name: TS
              type: BIGINT
          writeBehind:
            failSilently: "false"
            modificationQueueSize: "2048"
      statistics: "true"
    security:
      authorization: {}
    serialization:
      allowList:
        class: org.keycloak.cluster.infinispan.WrapperClusterEvent
        regex: .*
      marshaller: org.infinispan.jboss.marshalling.commons.GenericJBossMarshaller
    statistics: "true"
    transport:
      cluster: ${infinispan.cluster.name:cluster}
      node-name: ${infinispan.node.name:}
      stack: kubernetes
  server:
    dataSources:
    - connectionFactory:
        connectionProperties:
          name: value
        driver: org.postgresql.Driver
        password: ${env.ISPN_POSTGRESQL_PASSWORD}
        url: jdbc:postgresql://${env.ISPN_POSTGRESQL_HOSTNAME}:${env.ISPN_POSTGRESQL_PORT:5432}/${env.ISPN_POSTGRESQL_DATABASE:keycloak}?currentSchema=${env.ISPN_POSTGRESQL_SCHEMA:infinispan}
        username: ${env.ISPN_POSTGRESQL_USERNAME}
      connectionPool:
        backgroundValidation: 1000
        blockingTimeout: 1000
        idleRemoval: 1
        initialSize: 1
        leakDetection: 10000
        maxSize: 10
        minSize: 3
      jndiName: jdbc/postgres
      name: ds
      statistics: true
    endpoints:
    - connectors:
        hotrod:
          hotrodConnector: null
        rest:
          restConnector: null
      securityRealm: default
      socketBinding: default
    - connectors:
        rest:
          restConnector:
            authentication:
              mechanisms: BASIC
      securityRealm: metrics
      socketBinding: metrics
    interfaces:
    - inetAddress:
        value: ${infinispan.bind.address:127.0.0.1}
      name: public
    security:
      credentialStores:
      - clearTextCredential:
          clearText: secret
        name: credentials
        path: credentials.pfx
      securityRealms:
      - name: default
        propertiesRealm:
          groupProperties:
            path: groups.properties
          groupsAttribute: Roles
          userProperties:
            path: users.properties
      - name: metrics
        propertiesRealm:
          groupProperties:
            path: metrics-groups.properties
            relativeTo: infinispan.server.config.path
          groupsAttribute: Roles
          userProperties:
            path: metrics-users.properties
            relativeTo: infinispan.server.config.path
    socketBindings:
      defaultInterface: public
      portOffset: ${infinispan.socket.binding.port-offset:0}
      socketBinding:
      - name: default
        port: 11222
      - name: metrics
        port: 11223
```
