### DISCUSSION TITLE
Help with persisting data

### DISCUSSION THREAD

**Discussion by MaoMaoCake** [keycloak/keycloak#21971] [Q&A] [answered]
```
version: "3"

services:
  postgres:
      image: postgres:13.2
      restart: unless-stopped
      environment:
        POSTGRES_DB: keycloak_db
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: "db_password"
      volumes:
        - postgres_data:/var/lib/postgresql/data
  keycloak:
    depends_on:
      - postgres
    image: quay.io/keycloak/keycloak:22.0.0
    ports: 
      - 8443:8443
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak_db
      KC_DB_PORT: 5434
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: "db_password"
      ENV KC_HOSTNAME: localhost
      
      #DB_VENDOR: postgres
      #DB_ADDR: postgres
      #DB_DATABASE: keycloak_db
      #DB_USER: keycloak
      #DB_PASSWORD: "db_password"


      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: "kc_password"
      KC_HTTPS_CERTIFICATE_FILE: "/opt/keycloak/conf/server.crt.pem"
      KC_HTTPS_CERTIFICATE_KEY_FILE: "/opt/keycloak/conf/server.key.pem"
      # PROXY_ADDRESS_FORWARDING: "true"
      # HTTPS_METHOD: redirect
    volumes:
      - /home/maomao/keycloak/server.crt.pem:/opt/keycloak/conf/server.crt.pem
      - /home/maomao/keycloak/server.key.pem:/opt/keycloak/conf/server.key.pem
    command: "start --optimized --hostname login.example.com --proxy edge"

volumes:
  postgres_data:
```
Hi, I need some help with persisting the data in my keycloak db.  I tried https://github.com/keycloak/keycloak/discussions/19962 but It doesn't work, the error is  ` URL format error; must be "jdbc:h2:{ {.|mem:}[name] | [file:]fileName | {tcp|ssl}:[//]server[:port][,server2[:port]]/name }[;key=value...]" but is "jdbc:postgresql://postgres/keycloak_db"`
