### DISCUSSION TITLE
ppc64le supported keycloak-operator

### DISCUSSION THREAD

**Discussion by Vaibhav-Nazare** [keycloak/keycloak#21976] [Q&A]
Hi Team,

We are creating a ppc64le supported keycloak-operator:21.0.0 image using following commands required for one of tests for strimzi-kafka-operator

```
git clone -b 21.0.0 https://github.com/keycloak/keycloak.git
cd operator/
../mvnw -f ../pom.xml clean install -DskipTestsuite -DskipExamples -DskipTests
../mvnw clean install -DskipTests
mvn quarkus:add-extension -Dextensions='container-image-docker'
mvn clean package -Doperator -Dquarkus.container-image.build=true -Dquarkus.jib.platforms=linux/ppc64le
```

and keycloak container using

```
cd quarkus/
../mvnw -f ../pom.xml clean install -DskipTestsuite -DskipExamples -DskipTests
../mvnw clean install -DskipTests
cp dist/target/keycloak-21.0.0.tar.gz container/
docker buildx build --platform=linux/ppc64le --build-arg KEYCLOAK_DIST=keycloak-21.0.0.tar.gz . -t quay.io/keycloak/keycloak:21.0.0

```
We are using https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/21.0.0/kubernetes/kubernetes.yml yaml to deploy the keycloak-operator and have change imagepullpolicy to `IfNotPresent` to use locally built images

We are running into issue where the keycloak-operator is up and runnning , but the keycloak instance created on top of it fails with ImagePullBackOff as it doesn't use the locally built image and pulls amd64 image even after we have modifed the pull policy.

```
Events:

  Type     Reason     Age                  From               Message

  ----     ------     ----                 ----               -------

  Normal   Scheduled  2m57s                default-scheduler  Successfully assigned infra-namespace/keycloak-0 to minikube

  Normal   Pulling    80s (x4 over 2m56s)  kubelet            Pulling image "quay.io/keycloak/keycloak:21.0.0"

  Warning  Failed     79s (x4 over 2m55s)  kubelet            Failed to pull image "quay.io/keycloak/keycloak:21.0.0": rpc error: code = Unknown desc = no matching manifest for linux/ppc64le in the manifest list entries

  Warning  Failed     79s (x4 over 2m55s)  kubelet            Error: ErrImagePull

  Warning  Failed     66s (x6 over 2m54s)  kubelet            Error: ImagePullBackOff

  Normal   BackOff    54s (x7 over 2m54s)  kubelet            Back-off pulling image "quay.io/keycloak/keycloak:21.0.0"

```

can someone help us out with this?

**Comment by vmuzikar** [comment]
The Operator seems to be pulling the default Keycloak image (`quay.io/keycloak/keycloak:21.0.0`) which is not ppc64le. You have to [configure](https://github.com/keycloak/keycloak-k8s-resources/blob/22.0.1/kubernetes/kubernetes.yml#L211-L212) the Operator to use your ppc64le build of Keycloak image.

**Comment by Vaibhav-Nazare** [comment]
@vmuzikar We are using the following yaml
```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-03-08 - 14:26:09 +0000
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/version: 21.0.0
  name: keycloak-operator
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-03-08 - 14:26:09 +0000
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/version: 21.0.0
  name: keycloak-operator
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/version: 21.0.0
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloak-operator-role
rules:
  - apiGroups:
      - apps
      - extensions
    resources:
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: keycloak-operator
  name: keycloak-operator-role-binding
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: keycloak-operator-role
subjects:
  - kind: ServiceAccount
    name: keycloak-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-operator-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: keycloak-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloakcontroller-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: keycloakcontroller-cluster-role
subjects:
  - kind: ServiceAccount
    name: keycloak-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloakrealmimportcontroller-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: keycloakrealmimportcontroller-cluster-role
subjects:
  - kind: ServiceAccount
    name: keycloak-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloakcontroller-cluster-role
rules:
  - apiGroups:
      - k8s.keycloak.org
    resources:
      - keycloaks
      - keycloaks/status
      - keycloaks/finalizers
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloakrealmimportcontroller-cluster-role
rules:
  - apiGroups:
      - k8s.keycloak.org
    resources:
      - keycloakrealmimports
      - keycloakrealmimports/status
      - keycloakrealmimports/finalizers
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-03-08 - 14:26:09 +0000
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/version: 21.0.0
  name: keycloak-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak-operator
      app.kubernetes.io/version: 21.0.0
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2023-03-08 - 14:26:09 +0000
      labels:
        app.kubernetes.io/name: keycloak-operator
        app.kubernetes.io/version: 21.0.0
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_KEYCLOAK_IMAGE
              value: quay.io/keycloak/keycloak:21.0.0
          image: vaibhavnazare2022/keycloak-operator:21.0.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: keycloak-operator
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
      serviceAccountName: keycloak-operator

```
