### DISCUSSION TITLE
How mount the plugin keycloak-restrict-client-auth.jar on my keycloak instance with k8s ?

### DISCUSSION THREAD

**Discussion by BsctZz** [keycloak/keycloak#22144] [Q&A]
Hello everyone, I want to create a Keycloak instance with a provider mounted on the pod container. I have my plugin downloaded and I'd like to mount it on the container but I don't know how to do it. This is the provider (https://github.com/sventorben/keycloak-restrict-client-auth)
Here is my working manifest:
```
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: keycloak
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:22.0.1
          args: ["start-dev", '--debug', '--import-realm', '--features=client-policies']
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY
              value: "edge"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
```
I've tried that but I always get an error when deploying:
```
#          volumeMounts:
#            - name: restrict-client-auth-jar
#              mountPath: /opt/keycloak/providers/keycloak-restrict-client-auth.jar
#              subPath: keycloak-restrict-client-auth.jar
#      volumes:
#        - name: restrict-client-auth-jar
#          hostPath:
#            path: /home/azzime/Documents/KC/keycloak-restrict-client-auth.jar
```
My plugin has been downloaded and is located in /home/azzime/Documents/KC
How can I mount this jar file via my k8s manifest? please (edited)
