### DISCUSSION TITLE
Operator - annotation for linkerd injection?

### DISCUSSION THREAD

**Discussion by tamis-laan** [keycloak/keycloak#22174] [Q&A]
I'm looking to use linkerd service mesh to implement cluster wide security, and I'm trying to combine it with the keycloak operator. Linkerd usses annotations. The advanced configuration guide (https://www.keycloak.org/operator/advanced-configuration) claims I can add annotations under 'unsupported:` but this doesn't work. 

Here is my configuration:

``` yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 2
  db:
    vendor: postgres
    host: pg-auth-rw
    database: keycloak
    usernameSecret:
      name: pg-auth-superuser
      key: username
    passwordSecret:
      name: pg-auth-superuser
      key: password
  http:
    httpEnabled: true
  hostname:
    hostname: auth.dev.local
    strict: false
    strictBackchannel: false
  ingress:
    enabled: false
  unsupported:
    podTemplate:
      metadata:
        annotations:
          config.linkerd.io/inject: enabled
        labels:
          my-label: "keycloak"
```

As you can see the label is added to the pod but the annotation is not.
