### DISCUSSION TITLE
type=USER_INFO_REQUEST_ERROR

### DISCUSSION THREAD

**Discussion by prabhu-08** [keycloak/keycloak#22274] [Q&A]
We have hit a wired problem post upgrade of Keycloak from 16.1.1 to 21. 
When the user enters credentials from login page, post getting token by using the code. We are hitting this issue while getting user info .
```type=USER_INFO_REQUEST_ERROR, realmId=38c7aae8-0af4-4fe4-abd4-7a7c6400c214, clientId=null, userId=null, ipAddress=10.233.89.146, error=invalid_token, auth_method=validate_access_token```

Keyclaok is deployed as a STS. 
 ```       
env:
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "false"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: admin
        - name: KC_HTTP_RELATIVE_PATH
          value: /auth
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL_HOST
          value: my-postgresql
        - name: KC_DB_URL_PORT
          value: "5432"
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: postgresql-username
              name: postgresql
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgresql-password
              name: postgresql
        - name: KC_PROXY
          value: edge
```

The UI is accessed via node ip and port. The UI pod has a nginx which routes /auth to Keycloak service

Nginx conf
   ```
upstream keycloak {
      server keycloak-http:80;
    }

 location /auth/ {
        proxy_pass http://keycloak;
        proxy_cache_bypass  $http_upgrade;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $proxy_protocol_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $myscheme;
        proxy_set_header X-Forwarded-Host  $http_host;
        proxy_set_header Port  $http_port;
        proxy_set_header X-Forwarded-Port  $http_port;
        proxy_buffer_size 8k;
      }
```

Keycloak svc
`keycloak-http                  ClusterIP      10.233.8.240    <none>        80/TCP,8443/TCP       33h`

Ui svc
` web-ui                             LoadBalancer   10.233.2.110    <pending>     80:31931/TCP          33h   
`
So if I access the UI via node ip and port 
http://10.13.155.96:32247  this will redirect to  http://10.13.155.96:32247/auth/ and keycloaks login page will open. After entering credentials the code is sent to backend to get the token, the backend get the token(the call directly calls to keyclaok svc in this case http://keycloak-http/auth)  using the token when we call userinfo api we are hitting  

`type=USER_INFO_REQUEST_ERROR, realmId=38c7aae8-0af4-4fe4-abd4-7a7c6400c214, clientId=null, userId=null, ipAddress=10.233.89.146, error=invalid_token, auth_method=validate_access_token`

We tried adding frontendurl but as many of discussion group and GitHub issue suggested. This solves the problem but with gives another issue in our code we have some backend operations that we call directly keyclaok svc to generate token, but when we use that token we get   
`Unable to communicate with OIDC provider http://keycloak-http/auth/realms/master: oidc: issuer did not match the issuer returned by provider, expected "http://keycloak-http/auth/realms/master" got "http://10.13.155.96:32247/auth/realms/master" `
