### DISCUSSION TITLE
oidc authentication from within my cluster

### DISCUSSION THREAD

**Discussion by tamis-laan** [keycloak/keycloak#22611] [Q&A]
Keycloak and my API are both running inside the same cluster and I'm trying to use open id connect to verify authentication on my secured api routes. Because my API is running in the same cluster I'm connecting to keycloak internally (keycloak-service:8080). When initializing my oidc client I get the following error message:

``` error
oidc: issuer did not match the issuer returned by provider, expected "http://keycloak-service:8080/realms/myrealm" got "https://keycloak-service:8080/realms/myrealm"
```

How do I properly configure keycloak to accept internal connections??

Keycloak is exposed on auth,mydomain.xyz, it is running in https mode but the public endpoint is secured using https. This is my keycloak operator configuration:

``` yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 2
  db:
    vendor: postgres
    host: pg-auth-rw
    database: keycloak
    usernameSecret:
      name: pg-auth-superuser
      key: username
    passwordSecret:
      name: pg-auth-superuser
      key: password
  http:
    httpEnabled: true
  hostname:
    strict: false
  ingress:
    enabled: false
  unsupported:
    podTemplate:
      metadata:
        annotations:
          linkerd.io/inject: enabled
        labels:
          my-label: "keycloak"
```
