### DISCUSSION TITLE
X509ClientCertificateLookup for Envoy X-Forwarded-Client-Cert

### DISCUSSION THREAD

**Discussion by ethanchowell** [keycloak/keycloak#22907] [Ideas]
For users that run Keycloak in Kubernetes where ingress traffic is controlled by Istio, PKI auth can be a challenge if your Istio Gateway is configured for mTLS. Take the following Gateway for example

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: mtls-ingress
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: MUTUAL
      credentialName: mtls-cert
```

This Gateway tells Istio that requests over HTTPS for any hostname need to be enforced by mTLS with the `cacert`, `cert` and `key` (PEM format) in the `mtls-cert` secret. Envoy proxies (Istio sidecars or gateway controllers) will terminate TLS and forward the request to Keycloak over HTTP. At this point, Keycloak isn't able to fetch the user certificate from the peer connection, so it can't perform X509 authentication. The only way I've found to get around it, is to configure another Gateway and let Keycloak terminate TLS, leaving you with the following configs

```yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: keycloak-ingress
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: tls
      protocol: TLS
    hosts:
    - keycloak.my-domain
    tls:
      mode: PASSTHROUGH
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: mtls-ingress
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - app.my-domain
    tls:
      mode: MUTUAL
      credentialName: mtls-cert
```

However, Envoy packages up the users certificate into a `X-Forwarded-Client-Cert` header following [this specification](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-forwarded-client-cert). Having an official `X509ClientCertificateLookup` provider for parsing user certs from that header would help simplify the networking configs with Istio, making it easier to run Keycloak in that setting.
