### DISCUSSION TITLE
x509 Authentication - Keycloak Login

### DISCUSSION THREAD

**Discussion by tomastn14** [keycloak/keycloak#23218] [Q&A]
Hello everyone,

In keycloak, i want to log in with users with a personal digital certificate (.p12) that i installed in my browser.

I had configured the bind flow "Browser flow" with x509 username form but when i try to log in the browser don't request the certificate.

Can anyone help me??
Thanks in advance

**Comment by justin-tay** [comment]
Did you perform all the necessary TLS configuration as described at https://www.keycloak.org/server/enabletls?

**Reply by tomastn14** [reply]
Hi! 
thanks or your reply!

yes, i have the ssl/tls configuration. I have keycloak deployed in docker and i can acces via https and port 8443.

i want to log in with a certificate that i has installed on my browser, is a personal certificate of my country.

But I think (I must confirm) that the server is behind a proxy, I think it can be a problem too

**Reply by justin-tay** [reply]
Did you enable MTLS with the `https-client-auth` option?

**Comment by tomastn14** [comment]
This is mi docker-compose.yml file.
```
`version: '3'
services:
  keycloak:
    image: 'quay.io/keycloak/keycloak:latest'
    container_name: keycloak
    ports:
      - '8080:8080'
      - '8443:8443'
    volumes:
      - './certs/fullchain.pem:/etc/x509/https/tls.crt'
      - './certs/privkey.pem:/etc/x509/https/tls.key'
      - './certs:/certs'

    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
      KC_HTTPS_CLIENT_AUTH: request
    command:
      - start-dev
`
```

**Reply by justin-tay** [reply]
If I change `https-client-auth` to `required` and attempt to connect I get the following which shows Keycloak is asking for a certificate

![mtls](https://github.com/keycloak/keycloak/assets/49700559/d41bcd65-5fa8-4cfc-80a8-02dd3caf2a06)

**Comment by tomastn14** [comment]
Thanks for your help. Its very important for me.

Correct, if I change` https-client-auth` to `required`, I get the same error (`ERR_BAD_SSL_CLIENT_AUTH_CERT
`), but I don't understand it.

I want it to be requested in another realm (not master) when logging in with a user.

In https certificate and https key, I provide keys generated with lets encrypt for my domain where I deploy keycloak. Then in my browser the .p12 certificate is different, it is personal and I want to make it possible to log in with it.

**Reply by justin-tay** [reply]
MTLS is happening at the transport layer so this is really happening before Keycloak can really process anything.

This may mean that your client certificate is being rejected. You may need to configure a truststore with the CA of your client certificate or your client certificate itself and configure as per https://www.keycloak.org/server/enabletls#_using_a_truststore.

You probably need to make sure your client certificate is accepted before switching `https-client-auth` back to `request`.

**Comment by tomastn14** [comment]
Ok I have proceeded with your indication.

I have created the truststore with password "root1234"
`keytool -genkey -alias mytruststore -keystore truststore.jks`

I add the .p12 certificate that I have installed in my browser.
`keytool -importkeystore -srckeystore certificate.p12 -srcstoretype PKCS12 -destkeystore truststore.jks -deststoretype JKS
`

I have modified the environment of my docker compose file

```
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
      KC_HTTPS_TRUST_STORE_FILE: /certs/truststore.jks
      KC_HTTPS_TRUST_STORE_PASSWORD: root1234
      KC_HTTPS_CLIENT_AUTH: request
```
But the issue continues
