### DISCUSSION TITLE
How to configure secured and unsecured hostnames in the Keycloak HA statefulset

### DISCUSSION THREAD

**Discussion by reddybhavaniprasad** [keycloak/keycloak#23380] [Q&A] [answered]
Hi,

I am using keycloak **v22.0.0** version with 3 replicas for HA, I am able to bring it up with either secured or unsecured hostname, but I want to configure both secured and unsecured hostnames for the keycloak-HA setup

I have found an env-variable ( KC_HOSTNAME ) for setting the hostname in the keycloak statefulset-manifest . I am able to add only one hostname to this mentioned env-variable.

```
     env:
        - name: KC_HOSTNAME
          value: keycloak.x.x.x.nip.io
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "false"
```
![MicrosoftTeams-image (23)](https://github.com/keycloak/keycloak/assets/31069365/0ef655ef-d18e-4b9b-bfdc-b690da030da2)

Please let me know how to add 2 hostnames to this variable or if there is any other way to achieve this.
