### DISCUSSION TITLE
Cannot associate Persistent Volume Claim for storing theme files

### DISCUSSION THREAD

**Discussion by edbergavera** [keycloak/keycloak#24304] [Archive]
I'm trying to attach a PVC to Keycloak deployment but have not had any success. The following error occurs when applying the manifest.

`error: error validating "keycloak-deployment-with-pv.yml": error validating data: [ValidationError(Keycloak.spec): unknown field "containers" in org.keycloak.k8s.v2alpha1.Keycloak.spec, ValidationError(Keycloak.spec): unknown field "volumes" in org.keycloak.k8s.v2alpha1.Keycloak.spec]; if you choose to ignore these errors, turn validation off with --validate=false`

Here is my manifest:

```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak-pvc-demo
  namespace: keycloak
spec:
  instances: 1
  db:
    vendor: mysql
    host: mysql.mysql.svc.cluster.local
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
  containers:
    - name: keycloak
      image: quay.io/keycloak/keycloak:22.0.1
      volumeMounts:
        - name: keycloak-data
          mountPath: /opt/bitnami/keycloak/themes
  volumes:
    - name: keycloak-data
      persistentVolumeClaim:
        claimName: keycloak-pvc
  http:
    tlsSecret: keycloak-tls-secret
  hostname:
    hostname: keycloak.example.com

```

Is there no support yet for attaching PVC?

Your advice would be greatly appreciated.
