### DISCUSSION TITLE
How enable sslmode for external PostgreSQL database

### DISCUSSION THREAD

**Discussion by chary1112004** [keycloak/keycloak#24339] [Q&A]
Hi,

We are trying to enable ssl mode for external PostgreSQL database.

Is there any guide to config enable ssl mode in keycloak instance that is created from keycloak operator same as config keycloak bitnami https://github.com/bitnami/charts/issues/6217?

Thanks!

**Comment by shawkins** [comment]
@chary1112004 I don't think there is an existing guide.  You essentially need to follow whatever guide is most appropriate for you postgresql installation type.  

You'll then need to make the server certificate available.  More than likely the approach would be to make it available via a ConfigMap or Secret that is mounted by your keycloak, and referenced in the JDBC spec database url sslrootcert connection property.  You can also optionally update the url to include ssl=true

For example:

```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  database:
    url: jdbc:postgresql://pg-service/keycloak?ssl=true&sslrootcert=/mnt/cert/server.crt
    ...
  unsupported:
    podTemplate:
      spec:
        containers:
          - volumeMounts:
              - name: cert-volume
                mountPath: /mnt/cert
        volumes:
          - name: cert-volume
            secret:
              secretName: cert-secret
```
Were server.crt is a PEM file that is in the cert-secret Secret.
