### DISCUSSION TITLE
How to integrate keycloak 21.0.0 with sql server

### DISCUSSION THREAD

**Discussion by abdulqadir-technoheaven** [keycloak/keycloak#24348] [Archive]
How to integrate keycloak 21.0.0 with sql server so that all keycloak tables will be created in sql server database
using normal
and using docker
both approach
please suggest asap. Thanks

**Comment by jorozcof** [comment]
Hello I share my docker-compose with you. Change <ip>, <password>, <port> for yours

```
version: "3.8"
services:
        keycloak:
                container_name: keycloak21.0.0
                image: quay.io/keycloak/keycloak:21.0.0
                environment:
                        - KC_DB=mssql
                        - KC_DB_URL=jdbc:sqlserver://<ip>:<port>;databaseName=keycloak21
                        - KC_DB_USERNAME=sa
                        - KC_DB_PASSWORD=<password>
                        - KC_TRANSACTION_XA_ENABLED=false
                        - KC_DB_URL_HOST=<ip>
                        - KC_DB_URL_DATABASE=keycloak21
                ports:
                        - 9091:8080
```
