### DISCUSSION TITLE
Cannot reach /auth behind Nginx Ingress Controller

### DISCUSSION THREAD

**Discussion by rk9qn3j** [keycloak/keycloak#24549] [Q&A]
Hi,

I'm trying to set up Keycloak within Kubernetes behind Nginx Ingress Controller, but apparently, this was harder than I thought..

Using the manifest below, I'm able to reach Keycloak in the browser, but when I'm trying to access e.g. https://\<keycloak url\>/auth/realms/master/.well-known/openid-configuration, I get this:

![image](https://github.com/keycloak/keycloak/assets/18282546/160ba592-9621-431d-a781-5c8c04b3c494)

A funny thing though is if I set `KC_HTTP_RELATIVE_PATH` to `/auth`, the auth page works, but breaks everything else (of course).

I suspect that I'm missing some configuration somewhere, but I cannot for the world figure it out. I would be grateful if someone could point me in the right direction.

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: keycloak-app
  name: keycloak-app
  namespace: keycloak
spec:
  replicas: 1
  serviceName: "keycloak-app-svc"
  selector:
    matchLabels:
      app: keycloak-app
  template:
    metadata:
      labels:
        app: keycloak-app
    spec:
      containers:
      - image: quay.io/keycloak/keycloak:22.0.5
        name: keycloak
        ports:
          - containerPort: 8080
        args: ["start"]
        env:
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              name: keycloak-app-scrt
              key: admin-user
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-app-scrt
              key: admin-password
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL
          value: jdbc:postgresql://keycloak-db-svc.keycloak.svc.cluster.local:5432/keycloak
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: keycloak-app-scrt
              key: db-user
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-app-scrt
              key: db-password
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_PROXY
          value: "edge"
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KC_HTTP_PORT
          value: "8080"
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "false"
```

```yaml
apiVersion: v1
kind: Service
metadata:
  namespace: keycloak
  name: keycloak-app-svc
spec:
  selector:
    app: keycloak-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
```

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-app-ing
  namespace: keycloak
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
  - hosts: 
    - <keycloak url>
    secretName: keycloak-app-crt
  rules:
  - host: <keycloak url>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak-app-svc
            port:
              number: 8080
```
