### DISCUSSION TITLE
Cannot start keycloak with mariadb connection

### DISCUSSION THREAD

**Discussion by afiqhamzah** [keycloak/keycloak#24759] [Q&A]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dependencies

### Describe the bug

I failed to start the keycloack in a docker container that links to a mariadb database

my docker-compose.yml : 

```
version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    ports:
      - 8990:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KC_DB=mariadb
      - KC_DB_PASSWORD=root
      - KC_DB_USERNAME=root
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_URL_PORT=3306
      - KC_DB_URL=jdbc:mariadb://mariadb:3306/keycloak?characterEncoding=UTF-8
    networks:
      - network_keycloak
    command: 'start-dev'
networks:
  network_keycloak:
    external: true

```

### Version

22.0.5

### Expected behavior

Keycloak will run normally

### Actual behavior

![image](https://github.com/keycloak/keycloak/assets/26989296/2d86d9ef-26c8-4d3d-b120-4d05c1e11430)

### How to Reproduce?

 - Create new docker network
    docker create network network_keycloak

- Run a mariadb container 
'''
docker run -d \
  --name mariadb-container \
  --network network_keycloak \
  -e MYSQL_ROOT_PASSWORD=root \
  -e MYSQL_DATABASE=keycloak \
  -e MYSQL_USER=keycloak \
  -e MYSQL_PASSWORD=keycloak \
  -p 3306:3306 \
  mariadb:10.11
'''

create docker compose file : 
```
version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    ports:
      - 8990:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - KC_DB=mariadb
      - KC_DB_PASSWORD=root
      - KC_DB_USERNAME=root
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_URL_PORT=3306
      - KC_DB_URL=jdbc:mariadb://mariadb:3306/keycloak?characterEncoding=UTF-8
    networks:
      - network_keycloak
    command: 'start-dev'
networks:
  network_keycloak:
    external: true

```

run docker compose up in the same directory as the docker-compose.yml file

**Comment by robson90** [comment]
Here you go with a working example:

```
version: '3'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.5
    command: ["start-dev"]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: "mariadb"
      KC_DB_USERNAME: "admin"
      KC_DB_PASSWORD: "admin"
      KC_DB_URL: jdbc:mariadb://mariadb:3306/keycloak?characterEncoding=UTF-8
      KC_HTTP_RELATIVE_PATH: /auth
    ports:
      - "8080:8080"
    depends_on:
      mariadb:
        condition: service_healthy


  mariadb:
    image: mariadb:11.1.2
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: admin
      MARIADB_PASSWORD: admin
      MARIADB_DATABASE: keycloak
      MARIADB_ROOT_PASSWORD: admin
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized"]
      interval: 3s
      timeout: 3s
      retries: 20
```

Have a look at the official docs: https://hub.docker.com/_/mariadb (ENV-Variables)

Tested on Mac OS 14.1 and M1 Max
