### DISCUSSION TITLE
Keycloak 22.0.4 with external infinispan (docker compose)

### DISCUSSION THREAD

**Discussion by madhuchamara383** [keycloak/keycloak#25035] [Q&A]
I'm using keycloak 22.0.4 with custom spi and infinispan 14.0.21.Final docker images.
Im getting  

**ISPN000474: Error processing request 15@infinispan-server01-57681: java.lang.ClassNotFoundException: org.infinispan.server.hotrod.HotRodServer$ToEmptyBytesKeyValueFilterConverter$ToEmptyBytesKeyValueFilterConverterExternalizer** 

error when i up the keycloak container.But it's working without any issues with **keycloak 20.0.5** with below same configurations.
im using docker 24.0.7 version and docker compose v2.21.0

**docker-compose yml**

```
version: '3.8'
services:  
  
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    command: ["start-dev"]
    restart: always
    container_name: keycloak
    environment:
      KC_DB: mysql
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD:  keycloak 
      KC_DB_URL: "jdbc:mysql://mysql:3306/keycloak"
      KC_METRICS_ENABLED: true
      KC_HOSTNAME_STRICT: "false"
      #KC_PROXY: edge
      KC_HTTP_ENABLED: true 
      KC_HOSTNAME_STRICT_HTTPS: true
      PROXY_ADDRESS_FORWARDING: true
#      KC_LOG_LEVEL: WARN 
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: keycloaknew
    volumes:
        - ./server_data/keycloak/cache-ispn.xml:/opt/keycloak/conf/cache-ispn.xml:ro
#        - ./server_data/keycloak/infinispan.xml:/opt/keycloak/conf/cache-ispn-jdbc-ping.xml:ro
        - ./server_data/keycloak/keycloak.conf:/opt/keycloak/conf/keycloak.conf:ro  
        
  mysql:
      image: mysql:8.0
      container_name: mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root_password
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak_user
        MYSQL_PASSWORD: keycloak 
      volumes:
        - ./server_data/mysql:/var/lib/mysql
      ports:
        - 3306:3306

  infinispan:
    image:  quay.io/infinispan/server:14.0.21.Final
    hostname: INFINISPAN-SERVER-01
    container_name: infinispan
    ports:
      - 11222:11222
    environment:
      - USER=admin
      - PASS=admin
    volumes:
     - ./server_data/infinispan/infinispan.xml:/opt/infinispan/server/conf/infinispan.xml
     - ./server_data/infinispan/org.keycloak.keycloak-model-infinispan-22.0.4.jar:/opt/infinispan/lib/org.keycloak.keycloak-model-infinispan-22.0.4.jar
     - ./server_data/infinispan/org.keycloak.keycloak-core-22.0.4.jar:/opt/infinispan/lib/org.keycloak.keycloak-core-22.0.4.jar
     - ./server_data/infinispan/org.keycloak.keycloak-server-spi-22.0.4.jar:/opt/infinispan/lib/org.keycloak.keycloak-server-spi-22.0.4.jar
     - ./server_data/infinispan/org.infinispan.infinispan-jboss-marshalling-14.0.17.Final.jar:/opt/infinispan/lib/org.infinispan.infinispan-jboss-marshalling-14.0.17.Final.jar
     - ./server_data/infinispan/org.jboss.marshalling.jboss-marshalling-2.0.11.Final.jar:/opt/infinispan/lib/org.jboss.marshalling.jboss-marshalling-2.0.11.Final.jar
     - ./server_data/infinispan/org.keycloak.keycloak-server-spi-private-22.0.4.jar:/opt/infinispan/lib/org.keycloak.keycloak-server-spi-private-22.0.4.jar
     - ./server_data/infinispan/org.infinispan.infinispan-client-hotrod-jakarta-14.0.17.Final.jar:/opt/infinispan/lib/org.infinispan.infinispan-client-hotrod-jakarta-14.0.17.Fi
```

**infinispan.xml**

```
<infinispan
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="urn:infinispan:config:14.0 https://infinispan.org/schemas/infinispan-config-14.0.xsd
                            urn:infinispan:server:14.0 https://infinispan.org/schemas/infinispan-server-14.0.xsd"
      xmlns="urn:infinispan:config:14.0"
      xmlns:server="urn:infinispan:server:14.0">

   <cache-container name="keycloak" statistics="true">
      <transport cluster="${infinispan.cluster.name:ISPN}" stack="${infinispan.cluster.stack:tcp}" node-name="${infinispan.node.name:}"/>
      <security>
         <authorization/>
      </security>

    <serialization marshaller="org.infinispan.jboss.marshalling.commons.GenericJBossMarshaller">
            <allow-list>
                <class>org.keycloak.cluster.infinispan.WrapperClusterEvent</class>
                <regex>.*</regex>
            </allow-list>
    </serialization> 

    <replicated-cache name="work">
        <encoding media-type="application/x-jboss-marshalling"/>
    </replicated-cache>
    
    <distributed-cache name="sessions">
        <encoding media-type="application/x-jboss-marshalling"/>
    </distributed-cache>
    
    <distributed-cache name="authenticationSessions">
        <encoding media-type="application/x-jboss-marshalling"/>
    </distributed-cache>
    
    <distributed-cache name="clientSessions">
        <encoding media-type="application/x-jboss-marshalling"/>
    </distributed-cache>
    
    <distributed-cache name="offlineSessions">
        <encoding media-type="application/x-jboss-marshalling"/>
    </distributed-cache>
    
    <distributed-cache name="offlineClientSessions">
        <encoding media-type="application/x-jboss-marshalling"/>
    </distributed-cache>
    
    <distributed-cache name="actionTokens">
        <encoding media-type="application/x-jboss-marshalling"/>
    </distributed-cache>
    
    <distributed-cache name="loginFailures">
        <encoding media-type="text/plain"/>
    </distributed-cache>-->       
          
   </cache-container>

   <server xmlns="urn:infinispan:server:14.0">
      <interfaces>
         <interface name="public">
            <inet-address value="${infinispan.bind.address:127.0.0.1}"/>
         </interface>
      </interfaces>

      <socket-bindings default-interface="public" port-offset="${infinispan.socket.binding.port-offset:0}">
         <socket-binding name="default" port="${infinispan.bind.port:11222}"/>
         <socket-binding name="memcached" port="11221"/>
      </socket-bindings>

      <security>
         <credential-stores>
            <credential-store name="credentials" path="credentials.pfx">
               <clear-text-credential clear-text="secret"/>
            </credential-store>
         </credential-stores>
         <security-realms>
            <security-realm name="default">
               <!-- Uncomment to enable TLS on the realm -->
               <!-- server-identities>
                  <ssl>
                     <keystore path="application.keystore"
                               password="password" alias="server"
                               generate-self-signed-certificate-host="localhost"/>
                  </ssl>
               </server-identities-->
               <properties-realm groups-attribute="Roles">
                  <user-properties path="users.properties"/>
                  <group-properties path="groups.properties"/>
               </properties-realm>
            </security-realm>
         </security-realms>
      </security>

      <endpoints socket-binding="default" security-realm="default" />
   </server>
</infinispan>
```

**cache-ispn.xml**

```
<?xml version="1.0" encoding="UTF-8"?>

<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:14.0 http://www.infinispan.org/schemas/infinispan-config-14.0.xsd"
        xmlns="urn:infinispan:config:14.0">

    <cache-container name="keycloak">
        <transport cluster="${infinispan.cluster.name:ISPN}"  stack="tcp" lock-timeout="60000" site="site1"/>
        <local-cache name="realms">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <local-cache name="users">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <local-cache name="authorization">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <local-cache name="keys">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="3600000"/>
            <memory max-count="1000"/>
        </local-cache>

        <distributed-cache name="sessions" owners="2">
            <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                          cache="sessions"
                          purge="false"
                          preload="false"
                          segmented="false"
                          shared="true"
                          raw-values="true"
                          marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="172.18.0.2" port="11222" />
                <security>
                    <authentication server-name="infinispan">
                        <digest username="admin" password="admin" realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>
        <distributed-cache name="authenticationSessions" owners="2">
            <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                          cache="authenticationSessions"
                          purge="false"
                          preload="false"
                          segmented="false"
                          shared="true"
                          raw-values="true"
                          marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="172.18.0.2" port="11222" />
                <security>
                    <authentication server-name="infinispan">
                        <digest username="admin" password="admin" realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>
        <distributed-cache name="offlineSessions" owners="2">
            <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                          cache="offlineSessions"
                          purge="false"
                          preload="false"
                          segmented="false"
                          shared="true"
                          raw-values="true"
                          marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="172.18.0.2" port="11222" />
                <security>
                    <authentication server-name="infinispan">
                        <digest username="admin" password="admin" realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache> 
        <distributed-cache name="clientSessions" owners="2">
            <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                          cache="clientSessions"
                          purge="false"
                          preload="false"
                          segmented="false"
                          shared="true"
                          raw-values="true"
                          marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="172.18.0.2" port="11222" />
                <security>
                    <authentication server-name="infinispan">
                        <digest username="admin" password="admin" realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>
        <distributed-cache name="offlineClientSessions" owners="2">
            <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                          cache="offlineClientSessions"
                          purge="false"
                          preload="false"
                          segmented="false"
                          shared="true"
                          raw-values="true"
                          marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="172.18.0.2" port="11222" />
                <security>
                    <authentication server-name="infinispan">
                        <digest username="admin" password="admin" realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache>
        <distributed-cache name="loginFailures" owners="2">
            <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                          cache="loginFailures"
                          purge="false"
                          preload="false"
                          segmented="false"
                          shared="true"
                          raw-values="false"
                          marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="172.18.0.2" port="11222" />
                <security>
                    <authentication server-name="infinispan">
                        <digest username="admin" password="admin" realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache> 
        <distributed-cache name="actionTokens" owners="2">
                <expiration max-idle="-1" interval="300000"/>
            <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                          cache="actionTokens"
                          purge="false"
                          preload="false"
                          segmented="false"
                          shared="true"
                          raw-values="true"
                          marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="172.18.0.2" port="11222" />
                <security>
                    <authentication server-name="infinispan">
                        <digest username="admin" password="admin" realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </distributed-cache> 
        <replicated-cache name="work">
            <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                          cache="work"
                          purge="false"
                          preload="false"
                          segmented="false"
                          shared="true"
                          raw-values="true"
                          marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory">
                <remote-server host="172.18.0.2" port="11222" />
                <security>
                    <authentication server-name="infinispan">
                        <digest username="admin" password="admin" realm="default"/>
                    </authentication>
                </security>
            </remote-store>
        </replicated-cache>
    </cache-container>
</infinispan>
```

**keycloak.conf file**

```
# Basic settings for running in production. Change accordingly before deploying the server.

# Database

# The database vendor.
#db=postgres

# The username of the database user.
#db-username=keycloak

# The password of the database user.
#db-password=password

# The full database JDBC URL. If not provided, a default URL is set based on the selected database vendor.
#db-url=jdbc:postgresql://localhost/keycloak

# Observability

# If the server should expose healthcheck endpoints.
#health-enabled=true

# If the server should expose metrics endpoints.
#metrics-enabled=true

# HTTP

# The file path to a server certificate or certificate chain in PEM format.
#https-certificate-file=${kc.home.dir}conf/server.crt.pem

# The file path to a private key in PEM format.
#https-certificate-key-file=${kc.home.dir}conf/server.key.pem

# The proxy address forwarding mode if the server is behind a reverse proxy.
#proxy=reencrypt

# Do not attach route to cookies and rely on the session affinity capabilities from reverse proxy
#spi-sticky-session-encoder-infinispan-should-attach-route=false

# Hostname for the Keycloak server.
#hostname=myhostname
cache-config-file=cache-ispn.xml
```
