### DISCUSSION TITLE
login admin console appears 'Invalid username or password' after deployed keycloak operator and used external galera mysql cluster

### DISCUSSION THREAD

**Discussion by ViokingTung** [keycloak/keycloak#25319] [Archive]
#### Manually initialize the database

```bash
bin/kc.sh start-dev --db mysql --db-schema keycloak --db-username keycloak --db-password keycloak@2022 --db-url jdbc:mysql://pxc-mysql-pxc-0.pxc-mysql-pxc.pxc-mysql.svc.cluster.local:3306 --spi-connections-jpa-legacy-migration-strategy manual --spi-connections-jpa-legacy-initialize-empty false --transaction-xa-enabled=false
```

#### add DATABASECHANGELOG primary key in  generated sql file because pxc cluster not allowed no primary key for a table

```sql
alter table keycloak.DATABASECHANGELOG add constraint DATABASECHANGELOG_pk primary key (FILENAME,DATEEXECUTED,MD5SUM);
```

#### create db schema and import keycloak`s table and data

```sql
mysql version	8.0.31-23.2

create schema keycloak character set utf8 collate utf8_unicode_ci;
grant all privileges on keycloak.* to 'keycloak'@'%';
FLUSH PRIVILEGES;

keycloak-database-update.sql
```

#### deploy Keycloak Operator

```bash
kubectl -version	v1.23.17

kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/23.0.1/kubernetes/keycloaks.k8s.keycloak.org-v1.yml
kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/23.0.1/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/23.0.1/kubernetes/kubernetes.yml
```

#### Deploy Keycloak

```shell
kubectl create namespace keycloak
openssl req -subj '/CN=demo.keycloak.org/O=demo Keycloak./C=US' -newkey rsa:2048 -nodes -keyout key.pem -x509 -days 365 -out certificate.pem
kubectl create secret tls demo-tls-secret --cert certificate.pem --key key.pem -n keycloak
kubectl create secret generic keycloak-db-secret \
  --from-literal=username=keycloak \
  --from-literal=password=keycloak@2022 -n keycloak
kubectl apply -f keycloak/demo-kc.yaml -n keycloak

kubectl get keycloaks/demo-kc -o go-template='{{range .status.conditions}}CONDITION: {{.type}}{{"\n"}}  STATUS: {{.status}}{{"\n"}}  MESSAGE: {{.message}}{{"\n"}}{{end}}' -n keycloak
MESSAGE:
CONDITION: Ready
  STATUS: True
  MESSAGE: 
CONDITION: HasErrors
  STATUS: False
  MESSAGE: 
CONDITION: RollingUpdate
  STATUS: False
  MESSAGE: 
kubectl get secret demo-kc-initial-admin -n keycloak -o jsonpath='{.data.username}' | base64 --decode 
admin
kubectl get secret demo-kc-initial-admin -n keycloak -o jsonpath='{.data.password}' | base64 --decode 
181043f8c2c4442384df068b431a7cbe
```

demo-kc.yaml

```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: demo-kc
spec:
  instances: 3
  db:
    vendor: mysql
    host: pxc-mysql-pxc-0.pxc-mysql-pxc.pxc-mysql.svc.cluster.local
    schema: keycloak
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
  http:
    httpEnabled: true
    httpPort: 8180
    # httpsPort: 8443
    # tlsSecret: demo-tls-secret
  hostname:
    # hostname: keycloak.k8s.demo.com
    # admin: keycloak.admin.k8s.demo.com
    strict: false
    strictBackchannel: false
  ingress:
    className: demo-kc
    enabled: false
  transaction:
    xaEnabled: false
  # additionalOptions:
  #   - name: hostname-strict-https
  #     value: "false"
  #   - name: hostname-port
  #     value: "8443"
```

#### login admin console

![image](https://github.com/keycloak/keycloak/assets/17701012/50ace82f-3dc3-4027-973b-fa2185b0c395)

is it some problem with db script or keycloak operator ? could anyone give me some advice? Thanks
