### DISCUSSION TITLE
Hide Idp buttons on login page based on client

### DISCUSSION THREAD

**Discussion by ctmay4** [keycloak/keycloak#25553] [Q&A]
For a single realm, I have many SSO providers defined. I have multiple sites using the that realm. Is there a way to hide some SSO buttons on the login page depending on the site doing the login?

Right now all the apps use the same client-id. If I created separate clients for each site, would it be possible to show different Idp's depending on the client-id?

Here is the configuration for Spring Boot.

```yaml
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: app-name
            client-authentication-method: none
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: https://domain.com/realms/app=-name
            user-name-attribute: preferred_username
```

Alternatively, I saw this setting in the definition of the Idp. 

![image](https://github.com/keycloak/keycloak/assets/444345/b07f52d9-8cf9-4f6e-ac12-a4d4f09e73c2)

However it looks like `kc_idp_hint` is for bypassing the login screen and going straight to the provider which is not quite what I want.

https://www.keycloak.org/docs/latest/server_admin/index.html#_client_suggested_idp
