### DISCUSSION TITLE
Unable to access admin console with Keycloak started in optimized/production mode

### DISCUSSION THREAD

**Discussion by tspearconquest** [keycloak/keycloak#25799] [Archive]
Hi,

I've downloaded Keycloak 20.0.5 and configured for production as per https://web.archive.org/web/20230216185538/https://www.keycloak.org/server/configuration-production and https://web.archive.org/web/20230216185538/https://www.keycloak.org/server/containers

When I start the image in development mode, I am having no issue accessing the admin console.

However, when I start the image in production mode, I am able to access the main page for Keycloak at http://127.0.0.1:8080/ but when I click to go to the admin console, the page never loads. If I remove the deployment, change the startup args to `["start-dev"]` then it works properly.

Any clues what I am doing wrong?

Originally, I tried with a custom dockerfile, however now I tried pulling the image from dockerhub: `docker pull keycloak/keycloak:20.0.5` and I retagged it so that I could manually push it into my local minikube: `docker tag keycloak/keycloak:20.0.5 kctest:1 && minikube image load kctest:1`

Then as a test I applied the below manifest to the minikube cluster on my mac:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  strategy:
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 0
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: "keycloak"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9990"
      labels:
        app: keycloak
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: "kubernetes.io/hostname"
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - keycloak
      automountServiceAccountToken: false
      containers:
      - args:
## Below lines with double hash are what we tried to use for production mode with our source built image which results in the admin console never loading
##        - "--verbose"
##        - "start"
##        - "--optimized"
# Below line works fine with both our source built image and the public keycloak/keycloak 20.0.5 image; admin console loads
#        - "start-dev"
# Below is a hack to try to build and then start optimized with the basic Keycloak 20.0.5 image, and it replicates the issue well (admin console doesn't load)
        - "/opt/keycloak/bin/kc.sh build && /opt/keycloak/bin/kc.sh --verbose start --optimized"
        command:
        - "/bin/sh"
        - "-c"
# End hack
        env:
        - name: HOST_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_PASSWORD
          value: "keycloak"
        - name: KC_DB_SCHEMA
          value: "keycloak"
        - name: KC_DB_URL_HOST
          value: "pg-minikube-postgresql.postgres.svc"
        - name: KC_DB_USERNAME
          value: "keycloak"
        - name: KC_HEALTH_ENABLED
          value: "true"
        - name: KC_HOSTNAME
          value: "localhost"
        - name: KC_LOG_LEVEL
          value: "debug"
        - name: KC_METRICS_ENABLED
          value: "true"
        - name: KC_PROXY
          value: "edge"
        - name: KEYCLOAK_ADMIN
          value: "keycloak"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "keycloak"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: ROOT_LOGLEVEL
          value: "INFO"
        name: keycloak
        image: kctest:1
        imagePullPolicy: Never
        terminationMessagePolicy: FallbackToLogsOnError
        ports:
        - name: http
          containerPort: 8080
        - name: metrics
          containerPort: 9990
          protocol: TCP
        resources:
          requests:
            memory: 875Mi
            cpu: 150m
          limits:
            memory: 2Gi
            cpu: 1
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          runAsNonRoot: true
          runAsUser: 18000
          runAsGroup: 0
          seccompProfile:
            type: RuntimeDefault
      restartPolicy: Always
      serviceAccountName: keycloak
      terminationGracePeriodSeconds: 30
```
