### DISCUSSION TITLE
Unable to get "user-storage-properties-example" to show up in the UI

### DISCUSSION THREAD

**Discussion by lsmith77** [keycloak/keycloak#26181] [Q&A] [answered]
I have compiled https://github.com/keycloak/keycloak-quickstarts/tree/latest/extension/user-storage-simple and placed it into the `providers` dir and reloaded keycloak.

Using `show-config` it seems to be seen:
kc.provider.file.user-storage-properties-example.jar.last-modified =  1705222003804 (PersistedConfigSource)

However under federation the SPI does not appear:
<img width="831" alt="image" src="https://github.com/keycloak/keycloak/assets/300279/10f63d0d-4557-47df-8d01-e88afb2990db">

Any advice what could cause this or how to debug this?

**Comment by danielFesenmeyer** [comment]
Have you checked whether the SPI has actually been loaded, on the master realm start page?
If yes, it might be an issue in the UI.

**Reply by lsmith77** [reply]
On the `Provider info` I cannot see it listed.

But it is listed (as well as another SPI I added) under `show-config`
```
	kc.provider.file.dasniko.keycloak-demo-user-spi.jar.last-modified =  1704552303119 (PersistedConfigSource)
	kc.provider.file.user-storage-properties-example.jar.last-modified =  1705222003804 (PersistedConfigSource)
```

What would be my next debuggign steps?

**Reply by dasniko** [reply]
Proper Java version used to compile?
Proper version of the Keycloak interfaces used to compile?
Are the /META-INF/services/.... file contained in the deployed JAR?

**Reply by lsmith77** [reply]
I did use Java 17 to compile the jar's.

I am using 22.0.5 and the `latest` branch on the quickstart, which seems to be targetting keycloak 23. That being said `dasniko.keycloak-demo-user-spi` was targetting keycloak 22 and is also not showing up.

Switching the quickstart to `release/22.0` is causing some build errors:
```
The following artifacts could not be resolved: org.keycloak.bom:keycloak-spi-bom:pom:999.0.0-SNAPSHOT (absent)
```

So do I have to upgrade to Keycloak 23?

**Reply by lsmith77** [reply]
OK .. upgraded to Keycloak 23.0.2, same result. 

~~Ah actually `kc.provider` no longer shows up when using `show-config`~~

**Reply by lsmith77** [reply]
I tried finding pre-compiled jar's I could try it to just see if those would load properly but so far have not found anything. Hoping to figure out if the issue is with how I compile or elsewhere.

**Reply by lsmith77** [reply]
ok I found https://github.com/keycloak-customization/mongodb-user-federation

downloading that jar and adding it to my docker setup results in:
```
	kc.provider.file.dasniko.keycloak-demo-user-spi.jar.last-modified =  1704552303119 (PersistedConfigSource)
	kc.provider.file.mongodb_user_storage_provider.jar.last-modified =  1705312617849 (PersistedConfigSource)
	kc.provider.file.user-storage-properties-example.jar.last-modified =  1705303792278 (PersistedConfigSource)
```

But still not showing up under `Provider info` or `Federation` tabs :-/

**Reply by dasniko** [reply]
Can you provide anything how you configure, build and deploy your environment?

**Reply by lsmith77** [reply]
Dockerfile:
```
## From: https://medium.com/@ozbillwang/run-keycloak-in-docker-with-extenal-db-1b504ad00eae

# Documentation:
#  https://www.keycloak.org/server/containers

ARG KEYCLOAK_VERSION

FROM quay.io/keycloak/keycloak:$KEYCLOAK_VERSION as builder

# Configure postgres database vendor
ENV KC_DB=postgres

ENV KC_FEATURES="token-exchange,scripts,preview"

WORKDIR /opt/keycloak

# If run the image in kubernetes, switch and active below line.
# RUN /opt/keycloak/bin/kc.sh build --cache=ispn --cache-stack=kubernetes --health-enabled=true --metrics-enabled=true
RUN /opt/keycloak/bin/kc.sh build --cache=ispn --health-enabled=true --metrics-enabled=true

FROM quay.io/keycloak/keycloak:$KEYCLOAK_VERSION

LABEL image.version=$KEYCLOAK_VERSION

COPY --from=builder /opt/keycloak/ /opt/keycloak/

COPY --chown=keycloak ./*.jar /opt/keycloak/providers/.

# If any themes
# COPY themes/<nice-themes> /opt/keycloak/themes/<nice-themes>

# https://github.com/keycloak/keycloak/issues/19185#issuecomment-1480763024
USER root
RUN sed -i '/disabledAlgorithms/ s/ SHA1,//' /etc/crypto-policies/back-ends/java.config
USER keycloak

RUN /opt/keycloak/bin/kc.sh show-config

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```

docker-compose.yml:
```
version: "3.9"
services:
  postgres:
    image: "postgres:14.4"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - ./data/pg-keycloak:/var/lib/postgresql/data
      #- ./sql:/docker-entrypoint-initdb.d/:ro # turn it on, if you need run init DB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"

  pgadmin:
    image: "dpage/pgadmin4:latest"
    depends_on:
      - "postgres"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@talkspirit.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5480:80"

  keycloak:
    build:
      context: ./env/keycloak
      args:
        KEYCLOAK_VERSION: 23.0.2
    command: [ 'start', '--optimized' ]
    depends_on:
      - "postgres"
      - "mailhog"
    environment:
      JAVA_OPTS_APPEND: -Dkeycloak.profile.feature.upload_scripts=enabled
      KC_DB_PASSWORD: postgres
      KC_DB_URL: jdbc:postgresql://postgres/keycloak
      KC_DB_USERNAME: postgres
      KC_HEALTH_ENABLED: 'true'
      KC_HTTP_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      # KC_HOSTNAME: keycloak.local
      # KC_HOSTNAME_PORT: 8180
      KC_HOSTNAME_URL: http://keycloak.local:8180
      KC_PROXY: reencrypt
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - "8180:8080"
      - "8787:8787" # debug port

  mailhog:
    image: "mailhog/mailhog"
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
  project1:
    build:
      context: ./env/php1
    depends_on:
      - "postgres"
    volumes:
      - ./project1:/app

  project1-cli:
    build:
      context: ./env/php1-cli
    command: "/bin/bash"
    depends_on:
      - "postgres"
    volumes:
      - ./project1:/app
    stdin_open: true
    tty: true

  nginx:
    depends_on:
      - "project1"
    image: nginx:1.25.3
    ports:
      - "80:80"
    volumes:
      - ./env/nginx/:/etc/nginx/conf.d/

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.25.0.0/27
```

Also it appears the jar files are added with the right permissions:
```
docker exec lab-keycloak-keycloak-1 ls -al /opt/keycloak/providers
total 64
drwxrwxr-x 1 keycloak root  4096 Jan 15 09:58 .
drwxr-xr-x 1 keycloak root  4096 Jan 15 12:26 ..
-rw-r--r-- 1 keycloak root 14039 Jan  6 14:45 dasniko.keycloak-demo-user-spi.jar
-rw-r--r-- 1 keycloak root 12322 Jan 15 09:56 mongodb_user_storage_provider.jar
-rw-rw-r-- 1 keycloak root   256 Dec 14 19:23 README.md
-rw-r--r-- 1 keycloak root 15905 Jan 15 07:29 user-storage-properties-example.jar
```
