### DISCUSSION TITLE
May i Set kubernetes secret  for clients for realm?

### DISCUSSION THREAD

**Discussion by patsevanton** [keycloak/keycloak#26233] [Q&A]
Hello! I set password for clients for realm ?
Thanks!

```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: apatsev
  namespace: keycloak
  labels:
    app: sso
spec:
  keycloakCRName: core-keycloak
  realm:
    id: apatsev # grafana-id
    realm: apatsev # grafana-realm
    displayName: apatsev
    enabled: true
    clients:
      - clientId: grafana
        enabled: true
        clientAuthenticatorType: client-secret
        secret: password  # here 
```
