### DISCUSSION TITLE
Connect to Azure PostgreSQL Flexible Database Server from a Keycloak Container App without secrets using a managed identity

### DISCUSSION THREAD

**Discussion by netdip** [keycloak/keycloak#26267] [Q&A]
I am in the process of setting up a keycloak instance in Azure platform

In the process, I want to leverage passwordless authentication with postgresql in our AKS cluster to avoid having to setup any db credentials in the app. This system uses the native k8s service accounts to authenticate against Azure Active Directory which then issues a token that most Azure services can use to authenticate.

I have found some guideline in Azure for quarkus.
https://learn.microsoft.com/en-us/azure/container-apps/tutorial-java-quarkus-connect-managed-identity-postgresql-database?tabs=flexible

I tried to build the keycloak following above link along with https://www.keycloak.org/keycloak-benchmark/kubernetes-guide/latest/util/custom-image-for-keycloak to build a custom image. But getting error when the pod starts and throwing below error.

`2024-01-17 10:59:39,572 INFO  [com.azure.identity.ManagedIdentityCredential] (ForkJoinPool.commonPool-worker-1) Azure Identity => Managed Identity environment: AZURE AKS TOKEN EXCHANGE
2024-01-17 10:59:39,572 INFO  [com.azure.identity.ManagedIdentityCredential] (ForkJoinPool.commonPool-worker-1) Azure Identity => getToken() result for scopes [https://ossrdbms-aad.database.windows.net/.default]: SUCCESS
2024-01-17 10:59:39,572 INFO  [com.azure.identity.ChainedTokenCredential] (ForkJoinPool.commonPool-worker-1) Azure Identity => Attempted credential ManagedIdentityCredential returns a token
2024-01-17 10:59:39,573 FINE  [org.postgresql.Driver] (agroal-11) Connection error: : org.postgresql.util.PSQLException: Unable to acquire access token`

**Comment by subhidh-agarwal** [comment]
Hey @netdip, did you achieve this?

**Comment by Daveography** [comment]
For those following, I managed to get this to work by loading the Azure Identity Providers JDBC PostgreSQL library into the Keycloak `providers` folder, running `ks.sh build`, and then adding the required parameters to the the JDBC URL in `KC_DB_URL`.

This example uses Workload Identity, which is much more secure than Managed Identity; if you still prefer MI, see the [README](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/identity/azure-identity-extensions/Azure-Database-for-PostgreSQL-README.md) for what additional configuration you might need.

Example Dockerfile:
```dockerfile
ARG KEYCLOAK_VERSION

#----

FROM maven:alpine AS maven

# Preload plugin and dependencies (for Docker cache)
RUN mvn dependency:get -Dartifact=org.apache.maven.plugins:maven-dependency-plugin:3.8.0

# Obtain the Azure Identity Providers JDBC PostgreSQL library
ARG AZURE_IDP_VERSION
RUN mvn dependency:get -Dartifact=com.azure:azure-identity-extensions:${AZURE_IDP_VERSION}

# Now also get the IDP's dependencies
WORKDIR /root/.m2/repository/com/azure/azure-identity-extensions/${AZURE_IDP_VERSION}
RUN cp azure-identity-extensions-${AZURE_IDP_VERSION}.pom pom.xml
RUN mvn dependency:copy -Dartifact=com.azure:azure-identity-extensions:${AZURE_IDP_VERSION} -DoutputDirectory=/jar
RUN mvn dependency:copy-dependencies -DincludeScope=runtime -DoutputDirectory=/jar

#----

FROM quay.io/keycloak/keycloak:${KEYCLOAK_VERSION} AS builder

# Configure for postgres
ENV KC_DB=postgres

WORKDIR /opt/keycloak

# Copy the Azure Identity Provider
COPY --from=maven --chown=keycloak:keycloak --chmod=644 /jar/*.jar providers/

# Build
RUN bin/kc.sh build

#----

FROM quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
COPY --from=builder /opt/keycloak/ /opt/keycloak/

EXPOSE 8080

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```

NOTE: Feel free to suggest an easier way to obtain the required `jar` files, I'm not that familiar with Maven.

Be sure to include the version arguments when building; e.g.:
```bash
docker build -t youracr.azurecr.io/keycloak-az-postgres:25.0.2 --build-arg KEYCLOAK_VERSION=25.0.2 --build-arg AZURE_IDP_VERSION=1.1.20 .
```

Use the [Azure AD Workload Identity Quick Start](https://azure.github.io/azure-workload-identity/docs/quick-start.html?highlight=AZURE_CLI) instructions as a guide for setting up the Workload Identity.

Example manifests:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: keycloak
  name: keycloak-service-account
  annotations:
    azure.workload.identity/client-id: ac2d7530-ccd1-476e-b152-38aaad4ae9d2
--
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: keycloak
  name: keycloak
spec:
  replicas: 1
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: keycloak-service-account
      containers:
        - name: keycloak
          image: youracr.azurecr.io/keycloak-az-postgres:25.0.2
          args: ["start", "--optimized"]
          env:
            - name: KC_DB_URL
              value: "jdbc:postgresql://yourpsqlflexserver.postgres.database.azure.com:5432/keycloak?sslmode=require&authenticationPluginClassName=com.azure.identity.extensions.jdbc.postgresql.AzurePostgresqlAuthenticationPlugin&user=YourWorkloadIdentityApplicationDisplayName"
          ports:
            - name: http
              containerPort: 8080
```

NOTE: The `user` parameter is unfortunately required; if your Entra ID Application's display name includes spaces, be sure to escape them as `%20`.
