### DISCUSSION TITLE
Database erases during keycloak upgrade

### DISCUSSION THREAD

**Discussion by justpalma** [keycloak/keycloak#26413] [Q&A] [answered]
Hi, i'm trying to update my keycloak installation.
I'm currently running keycloak 8.0.2 and my goal is to install the latests version. I'm running keycloak on kubernetes and i'm not using keycloak opeartor.
Since keycloak 19.0.3 switched from jboss to quarkus, i'm following these steps:

1. Upgrade from 8.0.2 to 19.0.3-legacy: this is the latest version with jboss
2. Upgrade from 19.0.3-legacy to 19.0.3: switch from jboss to quarkus
3. Upgrade from 19.0.3 to 23.0.4

The first upgrade(8.0.2 to 19.0.3-legacy) went fine: all my data and realms are still visible after upgrade.
The second one(19.0.3-legacy to 19.0.3) went fine: all my data and realms are still visible after upgrade.
The third one(19.0.3 to 23.0.4) delete the entire database -> it seems that the DB migration is not performed.

This is my configuration
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cis-ops-9240-keycloa
  namespace: ops-9240
  labels:
    app: keycloak
    app.kubernetes.io/managed-by: Helm
    chart: keycloak-8.0.2
    release: cis-ops-9240
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
      release: cis-ops-9240
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: keycloak
        release: cis-ops-9240
    spec:
      volumes:
        - name: scripts
          configMap:
            name: cis-ops-9240-keycloa
            defaultMode: 365
        - name: keycloak-nfs-share
          persistentVolumeClaim:
            claimName: cis-ops-9240-keycloa-nfs-claim
      containers:
        - name: keycloak
          image: ...../keycloak:23.0.4
          command:
            - ./opt/keycloak/bin/kc.sh
            - start
            - '--spi-connections-jpa-default-migration-strategy=update'
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: jgroups
              containerPort: 7600
              protocol: TCP
          env:
            - name: JGROUPS_DISCOVERY_PROTOCOL
              value: dns.DNS_PING
            - name: JGROUPS_DISCOVERY_PROPERTIES
              value: >-
                dns_query=cis-ops-9240-keycloa-headless.ops-9240.svc.cluster.local
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL_HOST
              value: >-
                ops-9240-keycloak-upgrade.ciopjbsbqulr.eu-west-1.rds.amazonaws.com
            - name: KC_DB_URL_PORT
              value: '5432'
            - name: KC_DB_URL_DATABASE
              value: postgres
            - name: KC_DB_USERNAME
              value: keycloak
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cis-ops-9240-keycloa-db
                  key: password
            - name: KC_PROXY
              value: edge
            - name: KC_HOSTNAME
              value: '.....'
            - name: KC_HOSTNAME_ADMIN
              value: '.....'
            - name: KC_HOSTNAME_STRICT
              value: 'true'
            - name: KC_HTTP_RELATIVE_PATH
              value: /auth
            - name: KC_HTTP_ENABLED
              value: 'true'
          volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: keycloak-nfs-share
              mountPath: /opt/jboss/keycloak/themes/....
              subPath: themes/....-theme
            - name: keycloak-nfs-share
              mountPath: /opt/jboss/keycloak/standalone/deployments
              subPath: deployments
          livenessProbe:
            httpGet:
              path: /auth/
              port: http
              scheme: HTTP
            initialDelaySeconds: 120
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: http
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirst
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        fsGroup: 1000
      imagePullSecrets:
        - name: aws-ecr-credentials
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: keycloak
                  release: cis-ops-9240
                matchExpressions:
                  - key: role
                    operator: NotIn
                    values:
                      - test
              topologyKey: kubernetes.io/hostname
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: keycloak
                    release: cis-ops-9240
                  matchExpressions:
                    - key: role
                      operator: NotIn
                      values:
                        - test
                topologyKey: failure-domain.beta.kubernetes.io/zone
      schedulerName: default-scheduler
  serviceName: cis-ops-9240-keycloa-headless
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  revisionHistoryLimit: 10

```
I'm using postgres 14.7

any suggestion?

EDIT: during upgrade, the pod does not log any error
