### DISCUSSION TITLE
Unable to log into Admin portal using admin credentials on brand new installation

### DISCUSSION THREAD

**Discussion by maccamb** [keycloak/keycloak#29163] [Q&A] [answered]
Hello,

I am new to Keycloak and am not yet fully familiar with its details.

I have been able to successfully install, start and log into the Admin console using a Ubuntu VM and containers for keycloak and mariadb.

However I am unable to log in to the Admin console using the provisioned admin credentials if I repeat the setup on my Synology NAS that runs its own nginx web server.  (And I have been unsuccessful in locating any leads to debug this issue, so I am humbly seeking help here.)

My experience is as follows:

- I have installed Keycloak in a container and it successfully connects to a mariadb server in another container.
- Keycloak is started in development mode.
- I can successfully load the Admin console login page.
- However when I enter the admin credentials I receive an error message: We are sorry... Cookie not found.  Please make sure cookies are enabled in your browser.
- The URL for this page is: `http://mymachine.local:8082/realms/master/login-actions/authenticate?session_code=HaanjqIjp09Pc5uEtJzjaOMkch3toZDpnkIslV7cutM&execution=6ef32364-3ee2-4ecd-b9ce-7b5993df89b7&client_id=security-admin-console&tab_id=3UxWLRvp8Yw`
- (8082 is the exposed port)
- Keycloak logs reveal: `WARN  [org.keycloak.events] (executor-thread-11) type="LOGIN_ERROR", realmId="f0ca17aa-b545-427c-af1a-c8ba1d544863", clientId="null", userId="null", ipAddress="172.19.0.1", error="cookie_not_found"` 
- (172.19.0.1 is the container's IP address.)

Since (1) the error does not occur on my VM and I am able to successfully login using admin credentials, and (2) the only difference between the two setups that I can think of is the nginx web server, I suspect that my keycloak setup on the NAS may deficient, specifically wrt reverse-proxy.

I would greatly appreciate any guidance on this matter.

Many thanks!

**Comment by codespearhead** [comment]
If you're running Keycloak behind a reverse proxy, you have to [configure it accordingly](https://github.com/keycloak/keycloak/discussions/28279#discussioncomment-9001818).

**Reply by maccamb** [reply]
Many thanks for your response!  I applied `KC_PROXY_HEADERS: forwarded` to the compose file but no luck.

I am also curious to understand if `realmId="f0ca17aa-b545-427c-af1a-c8ba1d544863"` is a hint?

Should the master realm be seen as `realmId=master` or a key for the realm?  If the former is true then what could be the reason I am getting an incorrect realm?

**Reply by codespearhead** [reply]
No, realms have [a name and an id](https://github.com/vbhayden/keycloak-federation-examples/blob/e0b697642915c66747e73492a4154e5e1ff6d180/keycloak/keycloak-config/realms/example-realm.json#L3).

**Comment by darius-m** [comment]
Make sure Keycloak has the hostname, port and path configured correctly. Check for errors in the network tab and the stored cookies in the browser's developer tools. There should be no errors in the network tab, and cookies set for the `mymachine.local:8082` domain, with the `/realms/master` path.

**Reply by darius-m** [reply]
Considering you are exposing the service on port 8082 (which differs from the default 8080 / 8443), you probably need to set the `hostname-url` parameter - https://www.keycloak.org/server/reverseproxy#_relevant_options

**Comment by maccamb** [comment]
Thanks so much for your help!

So...
- I am using HTTP as I am still in the development and testing phase.
- I run keycloak in a container and remap the default port: so the compose file has: 8081:8080 i.e. default in the container maps to 8081 outside.
- My NAS's web setup (Synology Web Station) then requires me to setup the access portal and since I dont have a domain yet I am simply mapping the port.
- So in the end the ports go: clients accesses 8030; web server translates that to 8081 which is mapped to the default port in the keycloak container.
- I know that the port mapping works as I can access the Admin Console.

So my guess is that the issue may be related to `hostname-` parameters.

I continued exploring and found the following page: https://www.keycloak.org/server/hostname

It has 2 sections that I think may be relevant - see attached screenshot below - and am considering the following:
`--hostname=mymachine.local --hostname-strict-backchannel=true --hostname-url=https://mymachine.local:8030`

I am going to try this and will report results.  But I would also appreciate any guidance based on the above.

Many thanks!

<img width="1128" alt="Screenshot 2024-04-30 at 11 21 53 AM" src="https://github.com/keycloak/keycloak/assets/291388/6076ff42-d8fd-4839-b30f-fbdbc4551dbb">

**Reply by codespearhead** [reply]
You're passing `--hostname-url=https://mymachine.local:8030`, but shouldn't it be `--hostname-url=http://mymachine.local:8030`? Because you don't seem to be using HTTPS.

**Reply by maccamb** [reply]
I mis-typed in my post - I had set it up correctly with http.
(Nice catch though!)

**Reply by codespearhead** [reply]
Are you able to create a minimal reproducible example with Docker compose?

From what you've shown `--hostname-url` should have worked.

**Reply by maccamb** [reply]
Yes in fact the containers are created from a compose file included below.  Very straight-forward.
The Synology NAS handles nginx itself (via a package called Web Station) - I can try to unearth the web configuration if there could be nginx config issues.

```
version: '3.1'

name: mymachine-basic-services

services:

  mymachine_db:
    image: mariadb
    container_name: mymachine-mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 
    ports: 
      - 8040:3306

  mymachine_access:
    image: keycloak/keycloak
    container_name: mymachine-keycloak
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: 
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_DB: mariadb
      KC_DB_URL: jdbc:mariadb://mymachine_db:3306/mymachine_keycloak
      KC_DB_USERNAME: mymachine_keycloak_user
      KC_DB_PASSWORD: 
      KC_DB_SCHEMA: mymachine_keycloak
      KC_PROXY_HEADERS: forwarded
      KC_HOSTNAME_URL: http://mymachineds723.local:8030
    ports: 
      - 8080:8080
      - 8443:8443
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
```
