### DISCUSSION TITLE
[operator] keyclaok container does not start if initContainers is used

### DISCUSSION THREAD

**Discussion by mike-pt** [keycloak/keycloak#30251] [Archive]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

I need to add cloud-sql-proxy as a sidecar so I did:

```
  unsupported:
    podTemplate:
      spec:
        initContainers:
          - name: cloud-sql-proxy
            image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11-alpine
            args:
              - "--structured-logs"
              - "--private-ip"
              - "project:us-central1:instance-postgres-main"
 ```
 
 And cloud-sql-proxy actually starts fine, hower keycloak is stuck at:
 
 ```
   Normal  Pulled                   4m26s                  kubelet                  Container image "gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11-alpine" already present on machine
  Normal  Created                  4m26s                  kubelet                  Created container cloud-sql-proxy
  Normal  Started                  4m26s                  kubelet                  Started container cloud-sql-proxy
 ~/ k logs alpha-keycloak-0 -n keycloak
Defaulted container "keycloak" out of: keycloak, cloud-sql-proxy (init)
Error from server (BadRequest): container "keycloak" in pod "alpha-keycloak-0" is waiting to start: PodInitializing
```

I was using my own custom image but I unset it and just using the default but can't seem to get past this.

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak contianer should start 

### Actual behavior

keycloak container does not start

### How to Reproduce?

```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: keycloak
  name: alpha-keycloak
  namespace: keycloak
spec:
  hostname:
    strict: false
  resources:
    requests:
      cpu: "2"
      memory: "1250M"
    limits:
      cpu: "6"
      memory: "2250M"
  db:
    vendor: postgres
    url: jdbc:postgresql://localhost:5432/keycloak
    usernameSecret:
      name: alpha-keycloak-db-secret
      key: username
    passwordSecret:
      name: alpha-keycloak-db-secret
      key: password
  startOptimized: true 
  features:
    enabled:
      - scripts
      - token-exchange
      - admin-fine-grained-authz
  transaction:
    xaEnabled: false 
  http:
    httpEnabled: true
  instances: 3
  ingress:
    enabled: true
  unsupported:
    podTemplate:
      spec:
        initContainers:
          - name: cloud-sql-proxy
            image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11-alpine
            args:
              - "--structured-logs"
              - "--private-ip"
              - "project:us-central1:alpha-postgres-main"
```
apply this, notice that the keycloak container does not start
