### DISCUSSION TITLE
Unable to add a custom eventsListener provider to Keycloak running on Quarkus, even if it worked on Wildfly

### DISCUSSION THREAD

**Discussion by iuliu** [keycloak/keycloak#31677] [Archive]
Hello,
I'm trying to import a custom **eventsListener** provider to Keycloak **25.0.1** but it does not appear in the UI.
It puzzles me how it used to work on an older Keycloak version, which used Wildfly instead of Quarkus....

#### What I tried
I placed the jar file into the **providers** directory, then started Keycloak without the **--optimized** option, so that it would perform a rebuild.
After Keycloak finished starting up, i can see my custom provider mentioned in its configuration:

> **./kc.sh show-config**
> Current Mode: production
> Current Configuration:
>         kc.config.built =  true (SysPropConfigSource)
>         kc.db =  postgres (Persisted)
>         kc.http-relative-path =  /auth (Persisted)
>         kc.log-console-output =  default (classpath keycloak.conf)
>         **kc.provider.file.custom-logging.jar.last-modified =  1722003015470 (Persisted)**
>         kc.version =  25.0.1 (SysPropConfigSource)
> 

Note the  **kc.provider.file.custom-logging.jar.last-modified** line above.

However, when I log in to the GUI, I do not see this provider mentioned on the default page for the Keycloak realm:

![image](https://github.com/user-attachments/assets/11ededd5-0bb2-46a0-96a9-1407c161d5ce)

And it is not available in the **Realm Setting -> Events** section.

#### Another thing that I tried
was to add the following options when starting Keycloak in the un-optimized mode, so that it would rebuild:

```
--spi-events-listener-custom-logging-enabled=true 
--spi-events-listener-provider=custom-logging
```

But this generates the following exception:

```
ERROR: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#configureKeycloakSessionFactory threw an exception: 
        java.lang.RuntimeException: Failed to find provider custom-logging for eventsListener
        at org.keycloak.quarkus.deployment.KeycloakProcessor.checkProviders(KeycloakProcessor.java:896)
...
```

I'd be grateful if someone would let me know if I'm missing something.

The sample provider code is available in this public repository:
```
https://github.com/iuliu/playground/tree/master/Keyclock/SPI/CustomEventListener
```

Thank you!

**Comment by pr0PM** [comment]
Hi I tested your build using 25.0.2 and it seems to be working fine.
I'm working on something similar but with OTEL and logging events and have attached my setup below.

During startup I get Keycloak logs about loading the plugin.
```
keycloak-1  | 2024-07-29 07:15:10,752 WARN  [org.key.services] (build-32) KC-SERVICES0047: custom-logging (personal.iuliu.CustomEventListenerProviderFactory) is implementing the internal SPI eventsListener. This SPI is internal and may change without notice
```

and it even logs the events post startup
```
keycloak-1  | 2024-07-29 07:15:51,515 WARN  [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="27d11330-90ef-4b30-a6cd-21845a513d09", realmName="master", clientId="security-admin-console", userId="null", ipAddress="172.21.0.1", error="user_not_found", auth_method="openid-connect", auth_type="code", redirect_uri="http://0.0.0.0:8080/admin/master/console/", code_id="66db61b3-7e5a-4f20-b61b-86ffd414854c", username="admin"
keycloak-1  | 2024-07-29 07:15:55,681 WARN  [org.keycloak.events] (executor-thread-3) type="LOGIN_ERROR", realmId="27d11330-90ef-4b30-a6cd-21845a513d09", realmName="master", clientId="security-admin-console", userId="null", ipAddress="172.21.0.1", error="user_not_found", auth_method="openid-connect", auth_type="code", redirect_uri="http://0.0.0.0:8080/admin/master/console/", code_id="66db61b3-7e5a-4f20-b61b-86ffd414854c", username="admin"
```

Also shows up here
![image](https://github.com/user-attachments/assets/c62b6423-bb7b-40f1-a545-db1aebb7a5c6)


Dockerfile
```
FROM quay.io/keycloak/keycloak:25.0.2
COPY ./target/custom-logging.jar /opt/keycloak/providers/
```

Used this to build the custom-logging.jar
Also added a `<packaging>jar</packaging>` in pom.xml 
```
 mvn clean; mvn compile; mvn package -f "pom.xml"
```

docker-compose.yml
```
version: "3"

volumes:
  postgres_database:
    driver: local

services:

  postgres:
    image: postgres
    volumes:
      - postgres_database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    ports:
      - 5432:5432

  keycloak:
    image: keycloak:custom-logging
    volumes:
      - ./conf:/opt/keycloak/conf
    env_file:
      - .env

    ports:
      - 8080:8080
    depends_on:
      - postgres
    command:
      - --verbose
      - start
      - --http-enabled=true
      - --http-port=8080
      - --hostname-strict=false
      - --cache-config-file=cache-ispn.xml
      - --cache-stack=kubernetes
```
.env
```
KC_CACHE=ispn
KC_CACHE_STACK=kubernetes
URI_METRICS_ENABLED=true
KEYCLOAK_ADMIN=batman
KEYCLOAK_ADMIN_PASSWORD=batman
JAVA_OPTS_APPEND="-Djgroups.dns.query=keycloak-headless  --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.util.concurrent=ALL-UNNAMED"
KC_PROXY=edge
KC_DB=postgres
KC_DB_URL_HOST=postgres.keycloak.orb.local
KC_DB_URL_PORT=5432
KC_DB_URL_DATABASE=keycloak
KC_DB_USERNAME=user
KC_DB_PASSWORD=user
KC_METRICS_ENABLED=true
KC_HEALTH_ENABLED=true
```

So it doesn't seem to be problem with Quarkus, I hope it might help.
