### DISCUSSION TITLE
Unable to patch realm config updates using import-realm option at startup

### DISCUSSION THREAD

**Discussion by rahul-roy1-maersk** [keycloak/keycloak#32509] [Archive]
I am trying to import realms into multiple environments via keycloak operator through start import-realm   option using realm config json.
now first time, it works fine and the realm gets created. but then if I have to add a new client/change description of a client, i edit the realm config json, update the changes and redeploy. 
I have reloader auto configured - so any change in configmap, the statefulset restarts but then i see this in the log:

```
2024-08-29 15:48:11,974 INFO  [org.keycloak.exportimport.dir.DirImportProvider] (main) Importing from directory /opt/keycloak/bin/../data/import
2024-08-29 15:48:11,974 INFO  [org.keycloak.services] (main) KC-SERVICES0030: Full model import requested. Strategy: IGNORE_EXISTING
2024-08-29 15:48:12,256 INFO  [org.keycloak.exportimport.util.ImportUtils] (main) Realm 'realm-a' already exists. Import skipped
2024-08-29 15:48:12,407 INFO  [org.keycloak.exportimport.util.ImportUtils] (main) Realm 'realm-b' already exists. Import skipped
2024-08-29 15:48:12,412 INFO  [org.keycloak.services] (main) KC-SERVICES0032: Import finished successfully
```

Now, from keycloak guide [Importing and Exporting Realms - Keycloak](https://www.keycloak.org/server/importExport) I can see this:
```
If a realm already exists in the server, the import operation is skipped. The main reason behind this behavior is to avoid re-creating realms and potentially loose state between server restarts.

To re-create realms you should explicitly run the import command prior to starting the server.
```

Kindly please advise how this can be achieved using keycloak operator.

I have the following manifest right now:

```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-keycloak
spec:
  ingress:
    enabled: false
  unsupported:
    podTemplate:
      metadata:
        annotations:
          prometheus.io/path: /keycloak/metrics
          prometheus.io/port: "8080"
          prometheus.io/scrape: "true"
          reloader.stakater.com/auto: "true"
      spec:
        containers:
        - env:
          - name: PROXY_ADDRESS_FORWARDING
            value: "true"
          - name: KC_HTTP_RELATIVE_PATH
            value: /keycloak
          - name: KC_METRICS_ENABLED
            value: "true"
          - name: KEYCLOAK_IMPORT
            value: "/opt/keycloak/data/import/realm-a-realm.json,/opt/keycloak/data/import/realm-b-realm.json" # Import all JSON files from this directory
          envFrom:
          - secretRef:
              name:keycloak-client-secret
          volumeMounts:
          - name: realm-config-volume
            mountPath: /opt/keycloak/data/import/realm-a-realm.json
            subPath: realm-a-realm.json
            readOnly: true
          - name: realm-config-volume
            mountPath: /opt/keycloak/data/import/realm-b-realm.json
            subPath: realm-b-realm.json
            readOnly: true
          args: ["start", "--import-realm"]
          imagePullPolicy: "IfNotPresent"
        volumes:
        - name: realm-config-volume
          configMap:
            name: keycloak-realms-configmap
```
