### DISCUSSION TITLE
K8s: 404 Error & Latest Documentation?

### DISCUSSION THREAD

**Discussion by peter1357908** [keycloak/keycloak#32910] [Q&A] [answered]
(cross-posted from [the Discourse forum](https://keycloak.discourse.group/t/k8s-404-error-latest-documentation/27778) since it didn't gain any traction there)

Hello Keycloak community,

I’m trying to deploy Keycloak on a k8s cluster and ran into a strange issue of “404 Page Not Found” when I try to access the admin console at `https://some.hostname/keycloak/` (see screenshot).
![image](https://github.com/user-attachments/assets/7c5edb81-3735-4451-af9e-eaae8a96d4a6)

Some context, for what it’s worth: the cluster has an Nginx ingress controller and MetalLB, both of which work fine (tested with a JupyterHub deployment running on the same cluster). We want to deploy Keycloak as an authentication service for JupyterHub.

I deployed Keycloak using a modified version of the .yaml files in this guide: https://www.keycloak.org/getting-started/getting-started-kube. (e.g., the service type is “ClusterIP” instead of “LoadBalancer”, so it works with MetalLB). You can find their content at the end of this post.

On a related note, is there a place for the latest documentation for k8s configuration? The example config file linked in the aforementioned guide has deprecated values like “KC_PROXY”, where as [this other guide](https://www.keycloak.org/operator/basic-deployment) seems to use a newer API.

=================

keycloak.yaml

```
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: jhub
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 443
      targetPort: 8080
  selector:
    app: keycloak
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: jhub
  labels:
    app: keycloak
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:25.0.4
          volumeMounts: 
          - name: tls
            mountPath: '/etc/ssl'
            readOnly: true
          args: ["start"]
          env:
            - name: KEYCLOAK_ADMIN
              value: 'admin'
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: 'admin'
            - name: KC_PROXY
              value: 'edge'
            - name: KC_HOSTNAME
              value: 'some.hostname'
            - name: KC_HOSTNAME_STRCT_HTTPS
              value: 'true'
            - name: KC_LOG_LEVEL
              value: 'INFO'
            - name: KC_DB
              value: 'postgres'
            - name: KC_DB_URL
              value: 'jdbc:postgresql://some.db'
            - name: KC_DB_USERNAME
              value: 'kc-user'
            - name: KC_DB_PASSWORD
              value: 'kc-password'
            - name: KC_TRANSACTION_XA_ENABLE
              value: 'true'
            - name: KC_HEALTH_ENABLED
              value: 'true'
            - name: KC_METRICS_ENABLED
              value: 'true'
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /realms/master
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 1
      volumes:
        - name: tls
          secret:
            secretName: secret-name
            optional: false
```
    
=================

keycloak-ingress.yaml

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: jhub
spec:
  tls:
    - hosts:
        - some.hostname
      secretName: secret-name
  ingressClassName: nginx
  rules:
    - host: some.hostname
      http:
        paths:
          - path: /keycloak
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 443
```

**Comment by peter1357908** [comment, marked as answer]
Turns out this is due to a combination of **multiple** errors in the config files. The most critical error stems from having multiple replicas of keycloak pods, but not making the Service headless (`clusterIP: None`) nor setting `KC_CACHE_STACK` to be `kubernetes` (along with the `JAVA_OPTS`).

The following config now works (I included some of my findings in comments):

===
keycloak.yaml
```yaml
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: jhub
  labels:
    app: keycloak
spec:
  ports:
    - name: https
      port: 443
      targetPort: https
  selector:
    app: keycloak
  type: ClusterIP
  # the Service MUST BE headless for a multi-instance setup for Keycloak
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: jhub
  labels:
    app: keycloak
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.0.5
          args: ["start"]
          volumeMounts: 
          - name: tls
            mountPath: '/etc/ssl'
            readOnly: true
          env:
            # the first 2 env vars, `KC_CACHE_STACK` and `JAVA_OPTS` are REQUIRED
            # for the multi-instance Kubernetes cluster environment:
            # https://www.keycloak.org/server/caching#_configuring_caches_for_availability
            - name: KC_CACHE_STACK
              value: 'kubernetes'
            - name: JAVA_OPTS
              value: '-Djgroups.dns.query=keycloak.jhub.svc.cluster.local'
            - name: KC_BOOTSTRAP_ADMIN
              value: 'admin'
            - name: KC_BOOTSTRAP_ADMIN_PASSWORD
              value: 'admin'
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: '/etc/ssl/tls.crt'
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: '/etc/ssl/tls.key'
            # setting `KC_HOSTNAME` is recommended AND needed: https://www.keycloak.org/server/hostname
            # This MUST match the externally exposed URL, regardless of Ingress rewrites or KC_HTTP_RELATIVE_PATH settings.
            - name: KC_HOSTNAME
              value: 'some.hostname/keycloak/'
            # this is needed because keycloak normally exposes itself on the root path.
            # this must match wherever the reverse proxy is forwarding to.
            - name: KC_HTTP_RELATIVE_PATH
              value: '/keycloak/'
            - name: KC_LOG_LEVEL
              value: 'INFO'
            - name: KC_DB
              value: 'postgres'
            - name: KC_DB_URL
              value: 'jdbc:postgresql://some.database'
            - name: KC_DB_USERNAME
              value: 'db_username'
            - name: KC_DB_PASSWORD
              value: 'db_password'
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: 'true'
          ports:
            - name: https
              containerPort: 8443
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /keycloak/health/ready
              port: 9000
            initialDelaySeconds: 15
            periodSeconds: 1
      volumes:
        - name: tls
          secret:
            secretName: secret-name
            optional: false
```
===
keycloak-ingress.yaml
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: jhub
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  tls:
    - hosts:
        - some.hostname
      secretName: secret-name
  ingressClassName: nginx
  rules:
    - host: some.hostname
      http:
        paths:
          - path: /keycloak/
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  name: https
```
