### DISCUSSION TITLE
Declarative configuration API

### DISCUSSION THREAD

**Discussion by vmuzikar** [keycloak/keycloak#33049] [API guidelines]
The Keycloak team is working on a new REST API to support declarative configuration. The current Admin REST API is confusing, inconsistent and overall not really ready for a declarative style of communication. The main thoughts for the new API are:
* Well designed endpoints allowing to make a single request to create or update (PUT verb for both) a single logical entity. E.g. a Client incl. its Roles which currently requires making 2 requests to 2 different endpoints.
* Well designed DTOs/representations to be user friendly.
* Client agnostic. While one of the primary motivations for this is the Operator's Client CR, the API should be generic enough and cover use cases for 3rd party tools.
* The client should be only a thin layer around the API, all the logic for how to apply the configuration should be on the Keycloak side.
* The API will be a baseline for a new Admin REST API v2 and will be iteratively enhanced and developed.

This discussion is to continuously gather feedback as the design and a PoC evolves.

**Comment by hochbit** [comment]
I created some Python application for keycloak configuration called **rdynacloak** https://gitlab.com/C-X1/rdynacloak/.
At work we are currently using that in our Kubernetes cluster for an **automated setup of Keycloak - without persistence**.

In the Keycloak pod we have two additional containers the **rdynacloak and a k8s-sidecar** (https://github.com/kiwigrid/k8s-sidecar)

The k8s-sidecar picks up any **Secret or ConfigMap** inside the current namespace **with label and value “keycloak: keycloak_release-namespace”** and puts the files from each of those inside a directory shared with rdynacloak. rdynacloak watches this directory and on a update uses the existing Keycloak modules from Ansible  (in https://docs.ansible.com/ansible/latest/collections/community/general by using the **Python Ansible runner**) to apply the as settings given in the files to a realm called like the current namespace. 

**Additional settings are just applied**, but for **deletions or changes the realm is deleted and recreated** - so no need to undo the changes also in some cases undoing changes like deleting roles would break things.

**When a client helm chart is installed** (e.g. Grafana, Jenkins, etc), it creates a **secret** containing the **openid-client and the roles and role-bindings and its client secret.**

Here is an explanation of such config file:
```yaml
service_id: grafana  # an id for it to be able to be checked for readiness on the rest api of rdynacloak (not used by use atm)

# Each other entry in the yaml file is an array
# The key name of that array matches the name of the ansible 
# module - without the "keycloak_" prefix plus a "s" in the end.
# 
# Example: clients is for keylcoak_client
# https://docs.ansible.com/ansible/latest/collections/community/general/keycloak_client_module.html
#

# The keycloak modules I am using are applied in a specific order
# (groups -> roles -> users -> clients -> client_rolemappings)
# assuring that everything is already in place and it does not produce
# errors like if a client is not there for the client_rolemappings
# Each array entry is consistent with the values for the ansible module.
# auth_token, auth_user, auth_url, realm etc is set by rdynacloak

client_rolemappings:  
 -  ...
clients:
 -  ...
roles:
 - ...
 - ...
```


## Bigger setup and Issues

Each tenant (internal customer project) has its own namespace and Keycloak. We by default have LDAP and Microsoft Azure AD.
The access to each project depends on the groups of the LDAP. Most projects have multiple LDAP groups. 

Mostly they are called like

PROJECTNAME_admin  (Admins)
PROJECTNAME_dev (Developer)

That and the to work around the **Azure redirect URL security (needs to be added by our IT department – that can take days … mostly one or two)** led to the following setup:

Azure AD -> Main Cluster Keycloak -> Tenant Keycloak

The LDAP groups are synced to the main Keycloak and the Azure AD is used as OpenID Identity Provider, login is automatically forwarded from Tenant to Main Keycloak to Azure AD.

**Open Problems:**
- If the main **Keycloak is “reset”** – **the users of the tenant Keycloak are not able to login anymore** (maybe I can fix this with some authorization rules? Probably some UUID exchanged by the provider for the link - **_Hints on that are welcome_** )
 and I have to **reset the Tenant Keycloak** (deleting the pods Keycloak and Postgresql)
(Currently we have three projects using the cluster)
- **On an update of the main Keycloak which does not delete the realm,** It always runs into **timeout of the Ansible modules** – recent change of the timeout to 2 minutes, did not do the trick
Probably the vast number of LDAP groups make the Keycloak struggle when Ansible modules check for existing entries

**Solved Problems:**
- The LDAP groups exceeded the token size for users being at the company for a long time as none are deleted
   Assignment to namespace roles (administrator / developer) is done with group role mapping on main Keycloak, so for a default setup there is a maximum of 3 roles (administrator, developer, observer)
