### DISCUSSION TITLE
Cannot setup keycloak with traefik forward auth

### DISCUSSION THREAD

**Discussion by qiangxinglin** [keycloak/keycloak#33138] [Q&A]
Traefik manage the ACME certificates.

compose.yaml
```yaml
networks:
  traefik:
    name: traefik
    driver: bridge

include:
  - ./traefik/compose.yaml
  - ./keycloak/compose.yaml
```

.env
```
DOMAINNAME=ABC.XYZ
```

traefik/compose.yaml
```yaml
name: traefik

services:
  traefik:
    image: traefik:3.1
    container_name: traefik
    restart: unless-stopped
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./:/etc/traefik
    labels:
      - traefik.enable=true
      ## HTTP Routers
      - traefik.http.routers.api.rule=Host(`traefik.${DOMAINNAME}`)
      - traefik.http.routers.api.entrypoints=websecure
      ## Services - API
      - traefik.http.routers.api.service=api@internal
```

traefik/trafik.yaml
```yaml
global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https

  websecure:
    address: :443
    http:
      tls:
        certResolver: le
        domains:
          - main: "ABC.XYZ"
            sans:
              - "*.ABC.XYZ"

api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false
    network: traefik  # network to use for connections to all containers

certificatesResolvers:
  le:
    acme:
      email: 'EMAIL_ADDR'
      storage: /etc/traefik/acme.json
      dnsChallenge:
        provider: alidns
```

traefik/.env
```
ALICLOUD_ACCESS_KEY=AAA
ALICLOUD_SECRET_KEY=BBB
```

keycloak/compose.yaml
```yaml
name: keycloak

networks:
  keycloak-backend:
    name: keycloak-backend

services:
  keycloak_postgres:
    image: postgres:16.3-alpine
    container_name: keycloak_postgres
    shm_size: 128mb
    restart: unless-stopped
    networks:
      - keycloak-backend
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DB}

  keycloak:
    image: keycloak/keycloak:25.0
    container_name: keycloak
    restart: unless-stopped
    command: start
    depends_on:
      - keycloak_postgres
    networks:
      - keycloak-backend
      - traefik
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.keycloak.rule=Host(`${KEYCLOAK_SUBDOMAIN}.${DOMAINNAME}`)

  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:2
    environment:
      - SECRET=${PROVIDERS_OIDC_CLIENT_SECRET}
      - DEFAULT_PROVIDER=oidc
    networks:
      - keycloak-backend
      - traefik
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.forward-auth.forwardauth.address=http://traefik-forward-auth:4181
      - traefik.http.middlewares.forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User
      - traefik.http.services.forward-auth.loadbalancer.server.port=4181
```

keycloak/.env
```
PG_DB=keycloak_db
PG_USER=postgres
PG_PASS=postgres

KEYCLOAK_SUBDOMAIN=kc
KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=admin

KC_DB=postgres
KC_DB_URL=jdbc:postgresql://keycloak_postgres/${PG_DB}
KC_DB_USERNAME=${PG_USER}
KC_DB_PASSWORD=${PG_PASS}
KC_HTTP_ENABLED=true
KC_HOSTNAME_STRICT=false
KC_PROXY_HEADERS=xforwarded

PROVIDERS_OIDC_CLIENT_ID=traefik
PROVIDERS_OIDC_CLIENT_SECRET=SOME_SECRET
PROVIDERS_OIDC_ISSUER_URL=https://${KEYCLOAK_SUBDOMAIN}.${DOMAINNAME}/realms/MY_REALM
```

When I start the stack, the `traefik-forward-auth` container failed to startup:
```log
traefik-forward-auth  | time="2024-09-20T09:27:14Z" level=fatal msg="Get https://kc.ABC.XYZ/realms/MY_REALM/.well-known/openid-configuration: x509: certificate is valid for LOCAL-20190801, not kc.ABC.XYZ"
traefik-forward-auth exited with code 1
```

I'm not sure whether the problem is introduced by traefik reverse proxy, or keycloak oidc configuration, or the forward-auth part. Any idea?
