### DISCUSSION TITLE
Keycloak on Azure Web Service Help

### DISCUSSION THREAD

**Discussion by Reyzerbit** [keycloak/keycloak#33597] [Q&A]
I have spent almost all of yesterday trying to get a Keycloak 25.0.6 Docker image to run in an Azure Web Service, with no luck.
My current process is as follows:
1. I build my Keycloak customizations against the quay.io docker image using GitHub actions. Here's my Dockerfile:
```
FROM quay.io/keycloak/keycloak:25.0.6

COPY /keycloak/conf/ /opt/keycloak/conf/
COPY /keycloak/themes/ /opt/keycloak/themes/
RUN /opt/keycloak/bin/kc.sh build

EXPOSE 8443
EXPOSE 8080
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```
And here's my GitHub actions script:
```
name: Build and deploy container app to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: [REDACTED]
        username: [REDACTED]
        password: [REDACTED]

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: [REDACTED]
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: [REDACTED]

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: [REDACTED]
        slot-name: 'production'
        publish-profile: [REDACTED]
        images: [REDACTED]
```
The Keycloak instance has a `keycloak.conf` file in it with the following configurations:
```
# Features
features=hostname:v2

# Database
db=mssql
db-username=[REDACTED]
db-password=[REDACTED]
db-url=[REDACTED]

# Keystore
https-key-store-file=${kc.home.dir}/conf/truststores/[REDACTED].pfx
https-key-store-password=[REDACTED]

# HTTPS
hostname=[REDACTED]
# For Testing
# hostname=https://localhost:8443
hostname-backchannel-dynamic=true
hostname-strict=false
http-enabled=true
proxy-headers=forwarded
```
As you can see, I have a hostname set to a custom domain, and have the pfx files necessary for that domain's certs.
Additionally, I have the following environment variables set in my Azure Web Service, as recommended by a few other help guides I've read:
```
WEBSITES_PORT = 8443
SERVER_PORT = 8443
APPSETTINGS_PROXY_ADDRESS_FORWARDING = true
PROXY_ADDRESS_FORWARDING = true
```
2. Once the image is uploaded to the Azure Container Registry, my Web Service will restart and pull the new image. Once that is done, I wait for the container warmup. **This is where I experience issues.** No matter what configuration I try, the warmup never succeeds because the container doesn't respond to HTTP pings. Pretty much every other help guide I've read has told me to use some combination of the following Keycloak configurations:
```
hostname-backchannel-dynamic=true
hostname-strict=false
http-enabled=true
proxy-headers=forwarded
```
None of those combinations I've tried so far has worked. When I run Keycloak locally, I don't have issues. It connects to my MsSql database fine, I can get in and manage realms etc., and API requests all respond fine.

I'm kind of desperate at this point, and just need some help getting it past the HTTP pings warmup. Thanks in advance!
