### DISCUSSION TITLE
Docker - Failed to initialize truststore permission denied

### DISCUSSION THREAD

**Discussion by Tockra** [keycloak/keycloak#33882] [Q&A]
Hello,

I've been running a Keycloak setup in a Docker container behind an Nginx reverse proxy, which handles the HTTPS certificates. This setup has been operational for several months without issues. However, after a recent restart of the Docker container, Keycloak fails to start, and I receive the following error message:

**Error Message**:

<details>
  <summary>Click to expand the full error log</summary>

```bash
2024-10-14 09:10:36,996 INFO  [org.key.com.Profile] (main) Preview features enabled: token-exchange:v1
...
keycloak-1  | 2024-10-14 09:10:36,996 INFO  [org.key.com.Profile] (main) Preview features enabled: token-exchange:v1
keycloak-1  | 2024-10-14 09:10:37,012 WARN  [org.key.qua.run.cli.Picocli] (main) The following used options or option values are DEPRECATED and will be removed or their behaviour changed in a future release:
keycloak-1  | 	- proxy: Use proxy-headers.
keycloak-1  | Consult the Release Notes for details.
keycloak-1  | 2024-10-14 09:10:37,651 INFO  [org.key.com.Profile] (main) Preview features enabled: token-exchange:v1
keycloak-1  | 2024-10-14 09:10:42,721 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 5247ms
keycloak-1  | Server configuration updated and persisted. Run the following command to review the configuration:
keycloak-1  |
keycloak-1  | 	kc.sh show-config
keycloak-1  |
keycloak-1  | Next time you run the server, just run:
keycloak-1  |
keycloak-1  | 	kc.sh start --verbose --proxy=edge --hostname=login.mydomain.de --optimized
keycloak-1  |
keycloak-1  | ERROR: Unexpected error when starting the server in (production) mode
keycloak-1  | Error details:
keycloak-1  | java.lang.RuntimeException: Failed to start quarkus
keycloak-1  | 	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
keycloak-1  | 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
keycloak-1  | 	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
keycloak-1  | 	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
keycloak-1  | 	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
keycloak-1  | 	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
keycloak-1  | 	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
keycloak-1  | 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
keycloak-1  | 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
keycloak-1  | 	at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
keycloak-1  | 	at org.keycloak.quarkus.runtime.KeycloakMain.start(KeycloakMain.java:139)
keycloak-1  | 	at org.keycloak.quarkus.runtime.cli.command.AbstractStartCommand.run(AbstractStartCommand.java:35)
keycloak-1  | 	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
keycloak-1  | 	at picocli.CommandLine.access$1500(CommandLine.java:148)
keycloak-1  | 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
keycloak-1  | 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
keycloak-1  | 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
keycloak-1  | 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
keycloak-1  | 	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
keycloak-1  | 	at picocli.CommandLine.execute(CommandLine.java:2170)
keycloak-1  | 	at org.keycloak.quarkus.runtime.cli.Picocli.parseAndRun(Picocli.java:119)
keycloak-1  | 	at org.keycloak.quarkus.runtime.KeycloakMain.main(KeycloakMain.java:99)
keycloak-1  | 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
keycloak-1  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
keycloak-1  | 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:62)
keycloak-1  | 	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:33)
keycloak-1  | Caused by: java.lang.RuntimeException: Failed to initialize truststore, could not merge: /opt/keycloak/bin/../conf/truststores/reg.mydomain.de.key
keycloak-1  | 	at org.keycloak.truststore.TruststoreBuilder.mergePemFile(TruststoreBuilder.java:226)
keycloak-1  | 	at org.keycloak.truststore.TruststoreBuilder.mergeFiles(TruststoreBuilder.java:110)
keycloak-1  | 	at org.keycloak.truststore.TruststoreBuilder.mergeFiles(TruststoreBuilder.java:102)
keycloak-1  | 	at org.keycloak.truststore.TruststoreBuilder.createMergedTruststore(TruststoreBuilder.java:90)
keycloak-1  | 	at org.keycloak.truststore.TruststoreBuilder.setSystemTruststore(TruststoreBuilder.java:52)
keycloak-1  | 	at org.keycloak.quarkus.runtime.KeycloakRecorder.configureTruststore(KeycloakRecorder.java:102)
keycloak-1  | 	at io.quarkus.deployment.steps.KeycloakProcessor$configureTruststore2112467525.deploy_0(Unknown Source)
keycloak-1  | 	at io.quarkus.deployment.steps.KeycloakProcessor$configureTruststore2112467525.deploy(Unknown Source)
keycloak-1  | 	... 26 more
keycloak-1  | Caused by: java.io.FileNotFoundException: /opt/keycloak/bin/../conf/truststores/reg.mydomain.de.key (Permission denied)
keycloak-1  | 	at java.base/java.io.FileInputStream.open0(Native Method)
keycloak-1  | 	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
keycloak-1  | 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
keycloak-1  | 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:106)
keycloak-1  | 	at org.keycloak.truststore.TruststoreBuilder.mergePemFile(TruststoreBuilder.java:196)
keycloak-1  | 	... 33 more
keycloak-1 exited with code 0
...
```
</details>

The key part of the error seems to be:

```
Caused by: java.io.FileNotFoundException: /opt/keycloak/bin/../conf/truststores/reg.mydomain.de.key (Permission denied)
```

**Docker Compose Configuration**:

<details>
  <summary>docker-compose.yml</summary>

```yaml
version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    depends_on:
      - postgres
    restart: unless-stopped
    command:
      - start
      - --verbose
      - --proxy=edge
      - --hostname
      - ${KEYCLOAK_URL}
    volumes:
      - /home/titan/proxy/data/certs/:/opt/keycloak/conf/truststores:ro
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HEALTH_ENABLED: ${KC_HEALTH_ENABLED}
      KC_METRICS_ENABLED: ${KC_METRICS_ENABLED}
      KC_HOSTNAME_STRICT: ${KC_HOSTNAME_STRICT}
      KC_HTTP_ENABLED: ${KC_HTTP_ENABLED}
      KC_FEATURES: ${KC_FEATURES}
      PROXY_ADDRESS_FORWARDING: ${PROXY_ADDRESS_FORWARDING}
      KC_DB: ${KC_DB}
      KC_DB_URL_HOST: ${KC_DB_URL_HOST}
      KC_DB_URL_DATABASE: ${POSTGRESQL_DB}
      KC_DB_USERNAME: ${POSTGRESQL_USER}
      KC_DB_PASSWORD: ${POSTGRESQL_PASS}
      VIRTUAL_HOST: login.mydomain.de
      LETSENCRYPT_HOST: login.mydomain.de
      LETSENCRYPT_EMAIL: dev@mydomain.de
      VIRTUAL_PORT: 8080
    networks:
      - default
      - proxy-tier

  postgres:
    image: postgres:13.2
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
    networks:
      - default
      - proxy-tier

networks:
  proxy-tier:
    name: proxy-tier
    external: true
```
</details>

**Certificate Directory and Permissions**:

The Nginx reverse proxy stores the certificates under `/home/titan/proxy/data/certs/`, which is mounted into the Keycloak container at `/opt/keycloak/conf/truststores` with read-only permissions.

Here is the output of `ls -l /home/titan/proxy/data/certs/`:

<details>
  <summary>Directory Listing with Permissions</summary>

```bash
drwxrwxrwx 9 titan titan 4.0K Oct 14 11:08 .
drwxr-xr-x 5 titan titan 4.0K Feb  7  2024 ..
drwxrwxrwx 2 titan titan 4.0K Sep  1 17:39 be.mydomain.de
drwxrwxrwx 2 titan titan 4.0K Jul  8 10:41 bin.mydomain.de
drwxrwxrwx 2 titan titan 4.0K Aug  9 16:15 mydomain.de
lrwxrwxrwx 1 titan titan   24 Oct 11 11:35 mydomain.de.chain.pem -> ./mydomain.de/chain.pem
lrwxrwxrwx 1 titan titan   13 Oct 11 11:35 mydomain.de.dhparam.pem -> ./dhparam.pem
lrwxrwxrwx 1 titan titan   22 Oct 11 11:35 mydomain.de.key -> ./mydomain.de/key.pem
-rwxrwxrwx 1 titan titan 1.9K Feb  7  2024 default.crt
-rwxrwxrwx 1 titan titan 3.2K Feb  7  2024 default.key
-rw-r--r-- 1 titan titan  769 Feb  7  2024 dhparam.pem
drwxr-xr-x 2 root  root  4.0K Feb  7  2024 git.mydomain.de
lrwxrwxrwx 1 root  root    28 Oct 11 12:23 git.mydomain.de.chain.pem -> ./git.mydomain.de/chain.pem
lrwxrwxrwx 1 root  root    32 Oct 11 12:23 git.mydomain.de.crt -> ./git.mydomain.de/fullchain.pem
lrwxrwxrwx 1 root  root    13 Oct 11 12:23 git.mydomain.de.dhparam.pem -> ./dhparam.pem
lrwxrwxrwx 1 root  root    26 Oct 11 12:23 git.mydomain.de.key -> ./git.mydomain.de/key.pem
drwxr-xr-x 2 root  root  4.0K Sep  1 14:28 login.mydomain.de
lrwxrwxrwx 1 root  root    30 Oct 14 11:08 login.mydomain.de.chain.pem -> ./login.mydomain.de/chain.pem
lrwxrwxrwx 1 root  root    34 Oct 14 11:08 login.mydomain.de.crt -> ./login.mydomain.de/fullchain.pem
lrwxrwxrwx 1 root  root    13 Oct 14 11:08 login.mydomain.de.dhparam.pem -> ./dhparam.pem
lrwxrwxrwx 1 root  root    28 Oct 14 11:08 login.mydomain.de.key -> ./login.mydomain.de/key.pem
drwxr-xr-x 2 root  root  4.0K Jul  9 12:20 reg.mydomain.de
lrwxrwxrwx 1 root  root    28 Oct 11 12:24 reg.mydomain.de.chain.pem -> ./reg.mydomain.de/chain.pem
lrwxrwxrwx 1 root  root    32 Oct 11 12:24 reg.mydomain.de.crt -> ./reg.mydomain.de/fullchain.pem
lrwxrwxrwx 1 root  root    13 Oct 11 12:24 reg.mydomain.de.dhparam.pem -> ./dhparam.pem
lrwxrwxrwx 1 root  root    26 Oct 11 12:24 reg.mydomain.de.key -> ./reg.mydomain.de/key.pem
drwxrwxrwx 2 titan titan 4.0K Sep 24 17:11 vault.mydomain.de
```
</details>

Despite setting the `certs` folder and its contents to have `777` permissions (read, write, and execute for all users), Keycloak still encounters a permission denied error when accessing `/opt/keycloak/conf/truststores/reg.mydomain.de.key`.

**Steps to Reproduce**:

1. Use the provided `docker-compose.yml` to start the Keycloak and PostgreSQL containers.
2. Observe the Keycloak container logs upon startup.
3. Note that Keycloak fails to start due to a permission denied error on the truststore files.

**Expected Behavior**:

Keycloak should start successfully, accessing the truststore files without any permission issues.

**Actual Behavior**:

Keycloak fails to start with a permission denied error on the truststore file `/opt/keycloak/conf/truststores/reg.mydomain.de.key`.

**Troubleshooting Attempts**:

- Verified that the `certs` directory and its contents have `777` permissions.
- Confirmed that the files in question are indeed present and accessible on the host system.
- Restarted the Docker containers multiple times.
- Checked for any changes in the host system's permissions or ownership of the files.

**Additional Information**:

- **Keycloak Version**: 25.0
- **Docker Version**: (please insert your Docker version here)
- **Host OS**: (please insert your host OS details here)
- **Keycloak Container User**: Noticed that Keycloak may run as a non-root user inside the container.

**Questions and Assistance Needed**:

- Is there a known issue with Keycloak running in Docker where it cannot access mounted volumes with certain permissions?
- Could this be related to the user ID under which the Keycloak container is running versus the ownership of the mounted files?
- Are there recommended practices for mounting certificate directories into the Keycloak Docker container to avoid such permission issues?

Any guidance or assistance in resolving this issue would be greatly appreciated.

Thank you,

T
