### DISCUSSION TITLE
How can I upgrade this docker-compose from 24 to 26?

### DISCUSSION THREAD

**Discussion by Nefcanto** [keycloak/keycloak#33983] [Q&A] [answered]
Hi guys. My Keycloak version is 24.0.2. Now I want to upgrade it to 26.0.0.

This is part of my `docker-compose.yml` file:

```
        working_dir: /opt/keycloak
        environment:
            - KEYCLOAK_FRONTEND_URL=https://accounts.example.com/
            - PROXY_ADDRESS_FORWARDING=true
            - KC_HOSTNAME=accounts.example.com
            - KEYCLOAK_ADMIN=some_admin_user
            - KEYCLOAK_ADMIN_PASSWORD=some_admin_password
            - KC_DB_URL_HOST=database
            - KC_DB_URL_DATABASE=accounts
            - KC_DB_USERNAME=some_db_user
            - KC_DB_PASSWORD=some_db_password
            - KC_PROXY=edge
            - KC_HTTP_ENABLED=true
            - KC_HOSTNAME_STRICT=false
            - KEYCLOAK_IMPORT=/opt/keycloak/data/import
        command: start --optimized --proxy edge --hostname-strict=false
        depends_on:
            - database
        volumes:
            - /Infra/Accounts/Development.json:/opt/keycloak/data/import/development.json
            - /Infra/Accounts/Themes:/opt/keycloak/themes
```

This causes this error:

> Unknown option: '--proxy'
> Possible solutions: --proxy-headers, --proxy-protocol-enabled, --proxy-trusted-addresses

Also, it seems that the `KEYCLOAK_ADMIN` environment variable is not there anymore.

Could you please help on what should I change to upgrade this compose content to 26.0.0?
