### DISCUSSION TITLE
Installing keycloak X with traefik ingress

### DISCUSSION THREAD

**Discussion by prasadkris** [keycloak/keycloak#35751] [Q&A] [answered]
Greetings,

I am currently using the legacy keycloak hosted in our self-hosted kubernetes cluster. We are using Traefik v3 as our ingress controller, and the legacy keycloak setup works fine without any issues.

I am trying to test the latest **Keycloak.X** helm chart but couldn't get the ingress to work. 🙁  I believe this might require Traefik middlewares. However, despite trying various middlewares, I have been unable to resolve these errors. 

Setup:

    Self-hosted Kubernetes cluster (v1.28.3)
    Traefik ingress controller
    Keycloak  chart: keycloakx-2.6.0

```
cat custom-values.yaml

command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"
  - "--http-port=8080"
  - "--hostname-strict=false"
extraEnv: |
  - name: KEYCLOAK_ADMIN
    value: admin
  - name: KEYCLOAK_ADMIN_PASSWORD
    value: admin
  - name: JAVA_OPTS_APPEND
    value: >-
      -Djgroups.dns.query={{ include "keycloak.fullname" . }}-headless
  - name: JAVA_OPTS
    value: >-
      -XX:MaxRAMPercentage=50.0
  - name: KEYCLOAK_ADMIN
    value: admin
  - name: KEYCLOAK_ADMIN_PASSWORD
    value: xxxxxxxxxx
  - name: KC_PROXY
    value: "passthrough"

replicas: 3

dbchecker:
  enabled: true

http:
  relativePath: '/'

database:
  vendor: postgres
  hostname: keycloak
  port: 5432
  database: keycloak
  username: appuser
  password: xxxxxxxxxxxxxxxxxxxxx 

ingress:
  enabled: true
  servicePort: http
  rules:
    - host: 'keycloak.dus5.jaumo.dev'
      paths:
        - path: '{{ tpl .Values.http.relativePath $ | trimSuffix "/" }}/'
          pathType: Prefix
  tls: []

```

```
helm install keycloak codecentric/keycloakx --values ./custom-values.yaml
```

This will result in the following error when accessing the UI:

<img width="1642" alt="4" src="https://github.com/user-attachments/assets/25b2fe5f-ebea-43fe-81a4-dd18db7cdfd0">

I would appreciate it if someone could share insights or suggestions, on fixing this. Thanks

**Comment by codespearhead** [comment]
You should ensure this issue is reproducible using the latest stable release of the official Keycloak OCI image [1][2][3][4]. If not, you should close this discussion [5] and reach out to that third-party OCI image's vendor for support, because whatever it does on top of the official one is out of the official project's control.

A similar error came up recently [6][7], so you might want to reference it when talking to that vendor.

***

[1] https://github.com/keycloak/keycloak/discussions/29126
[2] https://github.com/keycloak/keycloak/discussions/29126#discussioncomment-9257666
[3] https://github.com/keycloak/keycloak/discussions/33407
[4] https://github.com/keycloak/keycloak/discussions/33407#discussioncomment-10820449
[5] https://docs.github.com/en/discussions/managing-discussions-for-your-community/managing-discussions#closing-a-discussion
[6] https://github.com/keycloak/keycloak/issues/33847
[7] https://github.com/keycloak/keycloak/issues/33847#issuecomment-2408642712

**Comment by prasadkris** [comment, marked as answer]
Thanks! I dug into this further and was finally able to resolve the issue. 😌 We need to include the `--proxy-headers=forwarded` option in the `command:` section and create a Traefik middleware to set the `Forwarded` header as shown below:

```
command:
  - "/opt/keycloak/bin/kc.sh"
  - "start"
  - "--http-port=8080"
  - "--hostname-strict=false"
  - "--proxy-headers=forwarded"
```

```
apiVersion: traefik.io/v1alpha1 
kind: Middleware
metadata:
  name: keycloak-forward-headers
  namespace: keycloak
spec:
  headers:
    customRequestHeaders:
      Forwarded: "proto=https;host=xxxxxxxxxx"
```
