### DISCUSSION TITLE
how to set `imagePullPolicy` for container image `keycloak:26.0.5`

### DISCUSSION THREAD

**Discussion by playgroundctl** [keycloak/keycloak#36987] [Archive]
Hey, could you advise on how to set the `imagePullPolicy` for `keycloak:26.0.5`, similar to how it's already configured for `keycloak-operator:26.0.5`?  

Currently, the relevant configuration looks like this:  
```yaml
spec:
  containers:
    - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RELATED_IMAGE_KEYCLOAK
          value: keycloak:26.0.5
      image: keycloak-operator:26.0.5 
      imagePullPolicy: Never
```  
I attempted the following but was unsuccessful:  
```yaml
unsupported:
  podTemplate:
    spec:
      containers:
        - imagePullPolicy: Never
```  
Would appreciate any insights on the correct approach.
