### DISCUSSION TITLE
Troubleshooting Horizontal Pod AutoScaling (HPA) Issues in Keycloak Deployment

### DISCUSSION THREAD

**Discussion by OS-emanuelbrici** [keycloak/keycloak#37223] [Q&A] [answered]
Hi all,

I’m facing an issue with Horizontal Pod Autoscaling (HPA) in my Keycloak v26 setup and would appreciate some insight.

I’m using Keycloak v26 with `persistent-user-sessions` enabled, deployed via the Keycloak Operator. The documentation suggests that the [built-in autoscaler](https://www.keycloak.org/getting-started/getting-started-scaling-and-tuning#_horizontal_scaling) should be functional in this version, so I’ve created an HPA resource targeting my Keycloak StatefulSet.

```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: keycloak-hpa
  namespace: keycloak-cluster
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: keycloak
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 60
```

However, I’m encountering an issue where the instance value in the Keycloak Custom Resource (CR) is preventing the autoscaler from scaling the pods. A Keycloak pod is created, and then immediately terminated - [similar to what is described in this SO question](https://stackoverflow.com/questions/72840685/horizontalpodautoscaler-scales-up-pods-but-then-terminates-them-instantly). It seems that the instant count in the Keycloak CR is conflicting with HPA functionality, blocking the scaling operation.

I came across a related issue with the legacy operator where a property was introduced to disable replica synchronization between the Keycloak CR and the StatefulSet (see: https://github.com/keycloak/keycloak-operator/issues/549).

Is this issue still relevant to the current version of the Keycloak Operator? I wasn’t able to find any similar properties (or alternative solutions) in the latest documentation, specifically for Keycloak Operator v26.0.6, or in the YAML schema for the [Keycloak CR](https://github.com/keycloak/keycloak-k8s-resources/blob/26.1.1/kubernetes/keycloaks.k8s.keycloak.org-v1.yml).

Here are my versions:
```
Keycloak v26.0.6
Keycloak Operator v26.0.6
```

Any guidance or suggestions on how to resolve this issue would be greatly appreciated!

**Comment by shawkins** [comment]
Don't target the statefulset. The Keycloak resource is scalable.

**Reply by OS-emanuelbrici** [reply]
Hi @shawkins,

When you mention that the Keycloak resource is scalable, are you referring to scaling it with the HPA resource? I’m a bit unclear on how that would work.

Do you have any examples of this configuration in action?

Thanks!

**Reply by shawkins** [reply, marked as answer]
> When you mention that the Keycloak resource is scalable, are you referring to scaling it with the HPA resource?

```
scaleTargetRef:
    apiVersion: k8s.keycloak.org/v2alpha1
    kind: Keycloak
    name: keycloak
```

It should be able to use the built in metrics as the pods will be found via the label selector.

> Do you have any examples of this configuration in action?

I don't believe one was ever added to the documentation.
