### DISCUSSION TITLE
To be or not to be. Question about valid kc+nginx proxy design.

### DISCUSSION THREAD

**Discussion by simonzsay** [keycloak/keycloak#37303] [Archive]
Hello! Quite long time trying to make all things correctly, but don`t have an option to ask smbd for advise and review regarding how properly i should config everything related to hostnames vars and proxy vars in KC 26.05. There are many tutorials for older versions, but for new ver not so many. Will appreciate if someone can tell me what i have to change (if needed).

I have docker compose with keycloak container
```
keycloak:
    container_name: keycloak
    image: "quay.io/keycloak/keycloak:{{ keycloak_version }}"
    volumes:
      - ./100k_passwords.txt:/opt/keycloak/data/password-blacklists/100k_passwords.txt
      - ./keycloak-theme.jar:/opt/keycloak/providers/keycloak-theme.jar
    command:
      - start
    environment:
      #KC_HOSTNAME: i dont use it as you can see
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "false"
      KC_PROXY_HEADERS: "xforwarded"
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://postgres:5432/{{ lookup('env', 'POSTGRES_DB') }}"
      KC_DB_USERNAME: {{ lookup('env', 'POSTGRES_USER') }}
      KC_DB_PASSWORD: {{ lookup('env', 'POSTGRES_PASSWORD') }}
      KC_BOOTSTRAP_ADMIN_USERNAME: {{ lookup('env', 'KEYCLOAK_ADMIN') }}
      KC_BOOTSTRAP_ADMIN_PASSWORD: {{ lookup('env', 'KEYCLOAK_ADMIN_PASSWORD') }}
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KC_LOG_LEVEL: "INFO"
      KC_FEATURES: "token-exchange"
    expose:
      - "8080"
      - "9000"
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - internal
 ```

Also i have nginx proxy config
```
worker_processes auto;
events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;

    upstream keycloak {
        server keycloak:8080;
    }

    upstream keycloak_health {
        server keycloak:9000;
    }

    server {
        listen 80;
        server_name eun.sso.abc.com eun.sso.int.abc.com dev.sso.abc.com dev.sso.int.abc.com;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name eun.sso.abc.com dev.sso.abc.com;

        ssl_certificate /etc/nginx/certs/dev-sso.crt;
        ssl_certificate_key /etc/nginx/certs/dev-sso.key;
    
    # Protects Keycloak from forged Host headers.
    if ($host !~* ^(eun.sso.abc.com|dev.sso.abc.com)$) {
        return 444;
    }

    # Block access from public net to abc-realm to avoid situation when user change his username/email/name and etc.
    location /realms/abc-realm/account/ {
        deny all;
    }
    # Block access from public net to master realm to avoid situation when user change his username/email/name and etc.
    location /realms/master/account/ {
        deny all;
       }

    location /realms/ {
        proxy_pass http://keycloak;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
    }

    location /resources/ {
        proxy_pass http://keycloak;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port $server_port;
    }

    location / {
        deny all;
    }

    location /admin/ {
        deny all;
    }

    location /metrics {
        deny all;
    }

    location /health {
        deny all;
    }

    }

    server {
        listen 443 ssl;
        server_name eun.sso.int.abc.com dev.sso.int.abc.com;

        ssl_certificate /etc/nginx/certs/dev-sso.crt;
        ssl_certificate_key /etc/nginx/certs/dev-sso.key;

        # Protects Keycloak from forged Host headers.
        if ($host !~* ^(eun.sso.int.abc.com|dev.sso.int.abc.com)$) {
        return 444;
        }

        # Block access from local net to abc-realm to avoid situation when user change his username/email/name and etc.
        location /realms/abc-realm/account/ {
        deny all;
       }
        # Block access from local net to master realm to avoid situation when user change his username/email/name and etc.
        location /realms/master/account/ {
         deny all;
       }

        location / {
            proxy_pass http://keycloak;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port $server_port;
            #proxy_cookie_flags ~.* secure samesite=None;
        }

        location /health {
            proxy_pass http://keycloak_health;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port $server_port;
    }
    }
}
```

So, seems i partly ignored advises from https://www.keycloak.org/server/reverseproxy and from https://www.keycloak.org/server/hostname but config above is the only one that works in scenario when i have for example two clients (one available only via public IP and second client only via private IP). Before with different configs private client always was redirected to public url. As i understand somehow this value should helps KC_HOSTNAME_BACKCHANNEL_DYNAMIC, but i don`t understand how to "cook" it. Regarding KC_HOSTNAME_STRICT: "false" in documentation i see that i can check it at proxy level. 

Again, will be glad to read any comments, not only about questions above =)

**Comment by shawkins** [comment]
See another discussion of hostname-backchannel-dynamic=true vs hostname-strict=false here #37219 - if you are trying to access non-backchannel endpoints from two different hostnames, then you will have to use hostname-strict=false - but you'll need to ensure that you trust how requests reach your keycloak instance.

**Reply by simonzsay** [reply]
Dear @shawkins, thank you for the link and comment. Sorry, probably I didn't use the topic search carefully enough. I read [topic](https://github.com/keycloak/keycloak/discussions/37219) and apparently @davysteegen encountered a similar problem and, as I see, he didn’t come up with anything other than not to use the new version until better times.

Regarding my questions. So, as i understand i have to be 100% sure that i thought over the scenario you described here [here](https://github.com/keycloak/keycloak/discussions/37219#discussioncomment-12127222)

Am i right that (taking into account the rest things) that i am correct way and i don`t have potential security issues?

**Reply by shawkins** [reply]
> Am i right that (taking into account the rest things) that i am correct way and i don`t have potential security issues?

If your only access to the keycloak instance is via the proxy and it has apppropriately restricted what hosts can be used (it does look like your configuration has taken this into account), then you should be good. 

You can further secure things on the keycloak side with the proxy-trusted-addresses option - proxy headers will then be ignored if they are not coming from your proxy.

**Reply by davysteegen** [reply]
So if I understand it correctly, this is the advised setup to use when multiple hosts are involved:

- Set KC_HOSTNAME_STRICT to false whenever more than 1 host should be allowed to access Keycloak (e.g. when certain admin API’s are accessed via another container running internally in a k8s cluster)
- Configure a host check on the reverse proxy to match only those for which Keycloak should be accessible from the outside world
- Set KC_PROXY_TRUSTED_ADDRESSES to the same hostnames as configured on the reverse proxy to have an additional layer of security.

**Reply by shawkins** [reply]
Yes to the first two.

> Set KC_PROXY_TRUSTED_ADDRESSES to the same hostnames as configured on the reverse proxy to have an additional layer of security.

It needs to be the address(es) of the proxy server.

**Reply by davysteegen** [reply]
Thank you for the clarification! That will definitely help us out when me migrate to Keycloak 26 and the v2 implementation of the hostname settings 👌

**Reply by simonzsay** [reply]
Dear @shawkins and @davysteegen many thnx for you advises. Today i predicted some things regarding trusted proxies a little and added necessary changes to docker compose. Seems, this setup works in general. However, just wanted to add one thing (even it is not valuable info for this topic). I have to check how clients goes to kc, because currently kc registers two different sessions for public and private IPs (for a public and private client) for a single user. So, philosophy of SSO doesn`t work here, compare with my provisos attempts where kc shows both clients (both private) under one session.

But.. i will  try to figure out. Again, thank you.

upd. On the other hand, what i expect from sessions if user came to kc via either public or private net. This is normal that user will have two sessions from different IPs.

**Comment by davysteegen** [comment]
I've been experimenting with a local Kubernetes cluster and this is the setup that is currently working fine (with `KC_HOSTNAME_STRICT` being set to `false`)

Keycloak statefulset:

```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  serviceName: keycloak
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      serviceAccountName: keycloak-kubeping-service-account
      volumes:
        - name: tls-cert
          secret:
            secretName: keycloak-tls
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.1.2
          env:
            - name: KC_HTTP_RELATIVE_PATH
              value: /auth
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL_HOST
              value: postgres
            - name: KC_DB_URL_DATABASE
              value: keycloak
            - name: KC_DB_USERNAME
              value: keycloak_owner
            - name: KC_DB_PASSWORD
              value: keycloak_owner
            - name: KC_DB_URL_PORT
              value: "5432"
            - name: KC_LOG_LEVEL
              value: "INFO"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HTTPS_CERTIFICATE_FILE
              value: /etc/x509/https/tls.crt
            - name: KC_HTTPS_CERTIFICATE_KEY_FILE
              value: /etc/x509/https/tls.key
            - name: KUBERNETES_LABELS
              value: app=keycloak
            - name: KUBERNETES_NAMESPACE
              value: default
            - name: KC_PROXY_HEADERS
              value: xforwarded
            - name: JGROUPS_DISCOVERY_PROTOCOL
              value: kubernetes.KUBE_PING
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          volumeMounts:
            - name: tls-cert
              mountPath: "/etc/x509/https"
              readOnly: true
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8080
```

Keycloak ingress:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "INGRESSCOOKIE"
    nginx.ingress.kubernetes.io/session-cookie-hash: "md5"
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "https"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
    nginx.ingress.kubernetes.io/server-alias: "keycloak.local"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # Protects Keycloak from forged Host headers.
      if ($http_host != keycloak.local) {
       return 444;
      }
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - keycloak.local
  rules:
    - host: keycloak.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  name: https
```

Note that the hostname check in the nginx configuration snippet is normally not required since the ingress is already configured to match a very specific hostname (`keycloak.local` in this case).
The hostname in the Keycloak ingress is also the only one that is being exposed to the public. Only if one has access the k8s cluster, then he can call Keycloak via the internal network.

@shawkins 
Do you still see any security concerns with the above setup? If not, then I think we can proceed with this configuration.
