### DISCUSSION TITLE
I'm getting cannot connect to port 8080 for following docker file even after using it in host network mode

### DISCUSSION THREAD

**Discussion by smeet10xdev** [keycloak/keycloak#37375] [Q&A]
I'm getting cannot connect to port 8080 for following docker file even after using it in host network mode

docker-compose.yml
```
version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8443:8443"
      - "8080:8080"
      - "9001:9000"
    environment:
      KC_DB: ${KC_DB}
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_HOSTNAME: ${KC_HOSTNAME}
    volumes:
      - ./conf:/opt/keycloak/conf
    user: root # solve this for production
    entrypoint: /bin/sh -c
    command: |
      "/opt/keycloak/bin/kc.sh start-dev \
      # solve this for production
      --https-certificate-file=conf/server.cert.pem \
      --https-certificate-key-file=conf/server.key.pem \
      -Dkeycloak.profile.feature.declarative_user_profile=enabled \
      -Dkeycloak.profile.feature.declarative_identity_provider=enabled
      "
    network_mode: host
```

logs:
```
[keycloak] | 2025-02-15 12:50:38,796 INFO  [io.quarkus] (main) Keycloak 26.1.2 on JVM (powered by Quarkus 3.15.3) started in 7.520s. Listening on: http://0.0.0.0:8080
[keycloak] | 2025-02-15 12:50:38,796 INFO  [io.quarkus] (main) Profile dev activated. 
```
Ref: https://github.com/smeet10xdev/auth_service_keycloak
