### DISCUSSION TITLE
Web Crypto API is not available (HTTP & initialize keycloak-js React App.tsx)

### DISCUSSION THREAD

**Discussion by BorisZo** [keycloak/keycloak#37399] [Q&A]
For the frontend React.tsx application, I use the KeycloakProvider wrapper (around App.tsx React), where I initialize **keycloak-js (26.1.2)** as follows: **keycloak.init({onLoad: 'login-required', checkLoginIframe: false, pkceMethod: false}).**
I need to run this application for the URL: http://our-local-network.internal/.

In the admin panel, in the Realm settings, I configure it like this: **Require SSL of Realm: None**, and in the public client settings for the frontend like this: **Proof Key for Code Exchange Code Challenge Method: plain**.

But! When navigating to the URL: http://our-local-network.internal/, there is an error in initializing keycloak.init, and I see the message: "Initialization error inside KeycloakProvider: **Web Crypto API is not available**".

In the development environment on localhost, everything works fine, but it doesn't work on HTTP.
This is my first time using a product like this, so please don't be too harsh.
Is there a guaranteed approach to fix this without using HTTPS?

Thanks in advance for your help!

**Comment by kwinczewski** [comment]
Hi, I run in to similar issue. Did you managed to resolve it or find a walkaround?

**Reply by BorisZo** [reply]
Hi!
No clear solution was found.

Alternative options:
1) Install webcrypto-shim in the frontend (questionable option)
2) Install nginx which will proxy requests from https to real http;

Or move to https.

**Reply by jonkoops** [reply]
Using HTTPS in production is the only way to solve this, this is a limitation of user-agents we do not control.

**Reply by joerno** [reply]
I have the same problem with our development enviroment using http and keycloak-angular like here: https://github.com/mauriciovigolo/keycloak-angular/issues/626

#37355
#36804

**Comment by kantorv** [comment]
found a workaround here (works on my ubuntu): https://stackoverflow.com/a/78397011/592737
tl;dr  - add your insecure domain here: `chrome://flags/#unsafely-treat-insecure-origin-as-secure`

**Reply by jonkoops** [reply]
Yeah, I don't know why they decided to do this. It feels like a stick to get people to move to HTTPS, which arguably isn't a problem anymore these days. Perhaps there is a good reason as to why, but I don't see it.

**Reply by kantorv** [reply]
I care less about production (where all the PKI stuff is set up, and it's good to be forced to use HTTPS) than about my local dev environment. Now I need to  figure out how to issue certificates for all the `.nip.io` subdomains )

**Reply by jonkoops** [reply]
Can't you use a [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts#potentially_trustworthy_origins) like `.localhost`?

**Reply by kantorv** [reply]
Guess I may, just need to migrate multiple stacks which look similar to this one.  I adopted `.nip.io` few years ago, and now it's everywhere  :) 
Anyway after discovering seems like https on local is not an issue, and could be implemented in reasonable time (mkcert + nginx-reverse-proxy), so I'll give it a try. 
 

```yml
# docker-compose.app.yml

name: kc-light
services:
  keycloak:
    networks:
      kc-net-v1:
        ipv4_address: 172.100.10.10
    image: quay.io/keycloak/keycloak:26.4
    environment:
      HOSTNAME: auth.172.100.10.10.nip.io

  static:
    networks:
      kc-net-v1:
        ipv4_address: 172.100.10.20
    environment:
      HOSTNAME: static.172.100.10.20.nip.io
    image: nginx:latest
    
  api:
    networks:
      kc-net-v1:
        ipv4_address: 172.100.10.30
    environment:
      HOSTNAME: api.172.100.10.30.nip.io

 
  reactapp:
    networks:
      kc-net-v1:
        ipv4_address: 172.100.10.50
    environment:
      HOSTNAME: app.172.100.10.50.nip.io

  # more services / databases here
networks:
  kc-net-v1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.100.10.0/24
  ```
