### DISCUSSION TITLE
How to use the SSSD user provider in a container?

### DISCUSSION THREAD

**Discussion by volkerCodeschoepfer** [keycloak/keycloak#37790] [Q&A]
Hi,

I need some advice, how can I use the User federation SSSD provider in a keycloak container. I did find several information which seems to be incorrect.

I am using Keycloak 26.1.

```
  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    command: start
    volumes:
      - /opt/containers/certs/ipa_ca.crt:/opt/keycloak/conf/truststores/ipa_ca.crt:ro
    environment:
      - VIRTUAL_HOST=${KEYCLOAK_HOSTNAME}
      - VIRTUAL_PORT=8080
      - KC_HOSTNAME=https://${KEYCLOAK_HOSTNAME}
      - KC_HTTP_ENABLED=true
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres/${POSTGRES_DB}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
```

Worth do note I am using the production mode Keycloak.

Does somebody have experience in this field. Any feedback is appreciated.

Thank you!
