### DISCUSSION TITLE
Unable to use reencrypt to route trafikk to keycloak in OKD

### DISCUSSION THREAD

**Discussion by oyviaase** [keycloak/keycloak#39356] [Q&A] [answered]
I've created a reencrypt using the following configuration
```yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: keycloak-route-route
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
    haproxy.router.openshift.io/disable_cookies: "true"
spec:
  host: keycloak.apps.okd-test.com
  to:
    kind: Service
    name: keycloak-service
  port:
    targetPort: https
  tls:
    termination: reencrypt
    certificate: configured-certificate
    key: certificate-key
    caCertificate: ca-certificate
    destinationCACertificate: ca-certificate
```

Which should result in the same as following the instructions added in the following PR https://github.com/keycloak/keycloak/pull/36809 

All that I'm presented with when I try to access keycloak is the standard openshift/okd error page that the service isn't running. 

![image](https://github.com/user-attachments/assets/78c26a7c-e82f-4b0d-9843-d9d4e9efa63b)

I've double checked that the route and service is to my knowledge configured correctly, and checked that the router in OKD say's if the route is available. Is there any sugestion on what I might have missconfigured here or is this a bug in either keycloak or OKD that needs to be reported?

**Comment by shawkins** [comment]
Can you provide what is shown in the Route and Keycloak status fields?

**Reply by oyviaase** [reply]
The status field from the route
```yaml
status:
  ingress:
  - conditions:
    - lastTransitionTime: "2025-04-28T13:54:04Z"
      status: "True"
      type: Admitted
    host: keycloak.apps.okd-test.com
    routerCanonicalHostname: router-default.apps.okd-test.com
    routerName: default
    wildcardPolicy: None
 ```
 The keycloak operator status field
 ```yaml
   status:
    conditions:
    - lastTransitionTime: "2025-04-29T12:36:55.954806549Z"
      message: ""
      observedGeneration: 96
      status: "True"
      type: Ready
    - lastTransitionTime: "2025-04-20T05:58:57.895881750Z"
      message: ""
      observedGeneration: 96
      status: "False"
      type: HasErrors
    - lastTransitionTime: "2025-04-29T12:36:55.954806549Z"
      message: ""
      observedGeneration: 96
      status: "False"
      type: RollingUpdate
    instances: 1
    observedGeneration: 96
    selector: app=keycloak,app.kubernetes.io/managed-by=keycloak-operator,app.kubernetes.io/instance=keycloak-dev
 ```
 Keycloak pod status field
 ```yaml
 status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-04-29T12:36:35Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-04-29T12:36:55Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-04-29T12:36:55Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-04-29T12:36:35Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://cd52eba20ab28240274cc2644a37679cdbd599cf1d73600180933c5b36aab57e
    image: local-registry/keycloak/keycloak-dev:26.1.3
    imageID: local-registry/keycloak/keycloak-dev@sha256:f3e66339311a82af3d53649995e5c44939c9e242874b1105efa52211378e54b7
    lastState: {}
    name: keycloak
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-04-29T12:36:36Z"
  hostIP: *****
  phase: Running
  podIP: 10.131.4.17
  podIPs:
  - ip: 10.131.4.17
  qosClass: Burstable
  startTime: "2025-04-29T12:36:35Z"
  ```

**Reply by shawkins** [reply]
I mean the status field from the Keycloak CR.

**Reply by oyviaase** [reply]
The graphic representation of the status field is shown in the image below
![image](https://github.com/user-attachments/assets/9015f598-dd97-4501-bfb6-500a835d281e)

**Reply by shawkins** [reply]
Sorry, I had quickly read the previous response and saw "keycloak operator status" and thought you had included the status from the operator pod.

What you are showing here has a Keycloak named keycloak-dev, so there should be a keycloak-dev-service, but the route references keycloak-service.

**Reply by oyviaase** [reply]
The name discrepancy from the post and the image was just me deciding to just use keycloak instead of keycloak-dev. The route routes to the `keycloak-dev-service`. I've been able to get things to work with edge termination, however that's not something that I'd like to use. The passthrough option from the ingress created by the operator is also an option, however I'd like to be able to limit access to certain paths per the recomendations listed here https://www.keycloak.org/server/reverseproxy#_exposed_path_recommendations and that's not something that's possible using a passthrough route.

**Reply by shawkins** [reply]
Ok, so the keycloak instance is up. The service exists. Access works via the default Ingress either as passthrough or edge.

As long as you have tls configured on your keycloak instance, I would expect the reencrypt route to work given all that.

Can you provide the yaml for the Service your route is targetting?

**Reply by oyviaase** [reply]
I've disabled http again after testing that edge worked. TLS is to my knowledge configured I've at least specified the following in the Keycloak resource
```yaml
spec:
  http:
    tlsSecret: keycloak-dev-tls-secret
```
The yaml configuration of the service is:
```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    javaoperatorsdk.io/previous: 1621a99a-38fb-4163-8e1c-382a54f7f06a,226260309
  creationTimestamp: "2024-08-28T12:28:33Z"
  labels:
    app: keycloak
    app.kubernetes.io/instance: keycloak-dev
    app.kubernetes.io/managed-by: keycloak-operator
  name: keycloak-dev-service
  namespace: keycloak-dev
  ownerReferences:
  - apiVersion: k8s.keycloak.org/v2alpha1
    kind: Keycloak
    name: keycloak-dev
    uid: bdd2e92e-9335-406d-985d-eddbd12d7c97
  resourceVersion: "228289672"
  uid: f71f0429-30ea-4ab4-a8c7-9a43e0d07bd2
spec:
  clusterIP: 172.30.92.204
  clusterIPs:
  - 172.30.92.204
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: management
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: keycloak
    app.kubernetes.io/instance: keycloak-dev
    app.kubernetes.io/managed-by: keycloak-operator
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
