### DISCUSSION TITLE
The official Keycloak Docker image should have `curl` installed

### DISCUSSION THREAD

**Discussion by TheKnarf** [keycloak/keycloak#39376] [Ideas]
### Description

Some platform needs `curl` to do healthchecks. They'll use the Docker image itself and run the healthcheck inside the image.

A simple example might be Docker Compose where you want the following to work:

```
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    ports:
      - "8081:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
    command: start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 20
```

There is a [discussion over here](https://gist.github.com/sarath-soman/5d9aec06953bbd0990c648605d4dba07) looking at other ways of doing it, but all of those seem wildly impractical, and it seems like it would make more sense for this to just ship with the image.

### Motivation

It should be easy to setup health checks, some platforms require `curl` (or a similar command) to exist in the Docker image to perform health checks (Docker Compose, Docker Swarm, etc).

### Details

Add `curl` as an package to the official Docker image.
