### DISCUSSION TITLE
Redirected to /admin endpoint

### DISCUSSION THREAD

**Discussion by rpartapsing** [keycloak/keycloak#39490] [Q&A]
I have installed keycloak helm chart [24.6.3](https://hub.docker.com/layers/bitnamicharts/keycloak/24.6.3/images/sha256-2079cfe0107eef4c1e07e5dd866c7ce4cf343dee242556c41c538c36754e7892)
using keycloak v26.2.2 after an upgrade from keycloak 24.0.5

with helm values
```
replicaCount: 3
resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 1Gi
postgresql:
  enabled: false
externalDatabase:
  existingSecret: {{ .Values.keycloakName }}-postgres-app
  existingSecretHostKey: host
  existingSecretPortKey: port
  existingSecretUserKey: username
  existingSecretDatabaseKey: dbname
  existingSecretPasswordKey: password
proxyHeaders: xforwarded
httpRelativePath: "/auth/"
auth:
  adminUser: <USER>
  existingSecret: {{ .Values.keycloakName }}
production: true
ingress:
  tls: true
  enabled: true
  ingressClassName: traefik
  pathType: Prefix
  hostname: "{{ .Values.subdomain }}.{{ .Values.platform.dnsDomain }}"
  path: "/"
  servicePort: http
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-https-redirect-permanent@kubernetescrd
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    endpoints:
      - path: '/auth/metrics'
    labels:
      prometheus-selector-target: system-prometheus
extraEnvVars:
  - name: KC_FEATURES
    value: "scripts"
```

My keycloak.conf inside the container shows:
```
# Hostname for the Keycloak server.
hostname = https://<MY_HOSTNAME>/
http-enabled = true
http-relative-path = /auth/
http-port = 8080
https-port = 8443
hostname-strict = false
cache-stack = kubernetes
cache = ispn
log-level = INFO
log-console-output = json
proxy-headers = forwarded
```

So even with
proxyHeaders: xforwarded
httpRelativePath: "/auth/"

I keep getting redirected to the /admin endpoint which shows: "Resource not found". I tried entering
<MYHOSTNAME>
<MYHOSTNAME>/
<MYHOSTNAME>/auth
<MYHOSTNAME>/auth/

With my keycloak v24.0.5 all works fine. However there I have
```
proxy: edge
```

I also tried with
```
proxyHeaders: forwarded
```

Anyone have an idea?
