### DISCUSSION TITLE
Admin console not loading

### DISCUSSION THREAD

**Discussion by cmonty14** [keycloak/keycloak#39711] [Q&A]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Describe the bug

I configured K8s with Istio Gateway ingress controller.
For deployment of keycloak I'm using bitnami helm chart.

Istio gateway is configured with SSL Termination.
And here's the virtual service manifest:
```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: keycloak
  namespace: keycloak
spec:
  hosts:
    - "keycloak.sle-stage.devsys.net"  # Match the host in your Gateway
  gateways:
    - istio-system/sle-stage-gateway  # Reference your Gateway
  http:
    - match:
        - uri:
            prefix: "/"  # For keycloak.sle-stage.devsys.net, match all paths and port 80
      route:
        - destination:
            host: keycloak
            port:
              number: 80
```

If I create port-forward to localhost with `kubectl port-forward svc/keycloak -n keycloak 8080:80` admin console UI loads w/o any problem.

### Version

26.2.4

### Regression

- [ ] The issue is a regression

### Expected behavior

Admin console with login

### Actual behavior

![Image](https://github.com/user-attachments/assets/048c9cdd-587a-4c3e-8774-d58d47065989)

### How to Reproduce?

Enter (pretty) URL in any browser.

**Comment by shawkins** [comment]
More than likely you have not configured proxy-headers on the keycloak server, so you are failing CORS checks and / or requests are being seen as from an insecure context.

**Reply by cmonty14** [reply]
This is probably true.
Could you please advise how to verify if and what proxy headers are configured in the relevant pod _keycloak-0_?

I'm using helm chart with these values.yaml:
```
global:
  defaultStorageClass: "default"

# PostgreSQL Configuration
postgresql:
  enabled: true
  auth:
    username: "keycloak"
    password: ""
    database: "keycloakdb"

# Keycloak Configuration
keycloak:
  auth:
    adminUser: ""
    adminPassword: ""
  production: false
  proxy: "edge"
  proxyHeaders: "xforwarded"

ingress:
  enabled: false

logging:
  level: INFO
```

**Reply by shawkins** [reply]
The helm chart is not supported by the Keycloak community. Presumably proxyHeaders maps to the proxy-headers Keycloak option. You'll need to verify that istio is setting the appropriate X-Forwarded-* headers. hostname debug can be helpful in these situations: https://www.keycloak.org/server/hostname#_troubleshooting

**Reply by cmonty14** [reply]
> The helm chart is not supported by the Keycloak community.

Can you please advise which helm chart is supported by Keycloak community?

**Reply by shawkins** [reply]
> > The helm chart is not supported by the Keycloak community.
> 
> Can you please advise which helm chart is supported by Keycloak community?

No helm chart is currently supported by the Keycloak community. If you think there is a problem in how the chart is configuring Keycloak, you'll need to raise an issue with that community instead. As long as you can confirm here what the underlying settings are for Keycloak, we can help point you in the right direction for changes to the configuration.

**Comment by cmonty14** [comment]
Issue solved.

For reference here's my working values.yaml (for helm chart bitnami/keycloak):
```
global:
  defaultStorageClass: "default"

# PostgreSQL Configuration
postgresql:
  enabled: true
  auth:
    username: "keycloak"
    password: ""
    database: "keycloakdb"

# Keycloak Configuration
auth:
  adminUser: ""
  adminPassword: ""
production: false
proxyHeaders: "xforwarded"
proxy: "edge"

ingress:
  enabled: false

adminIngress:
  enabled: false

logging:
  output: default
  level: DEBUG
```
