### DISCUSSION TITLE
Add the ability to create a group and subgroups in a single call

### DISCUSSION THREAD

**Discussion by j-n-white** [keycloak/keycloak#9395] [Ideas]
Currently if you wish to create a group with a subgroup this has to be done in two separate calls:
1. POST auth/admin/realms/{realm}/groups
2. POST auth/admin/realms/{realm}/groups/{parent group id}/children

If you provide subgroups to the first call they get ignored and only the top level group is created. It would be nice if endpoint could be used to create nested groups in a single call by providing json similar to this:
```json
{
    "name": "parent",
    "subGroups": [
        {
            "name": "child"
        }
    ]
}
```

**Comment by bs-matil** [comment]
IMHO this would be very artificial feature to have it only here. If I would rather like to have something like a bulk API which supports any kind of generic dependencies between objects which can than be used to flatten the calls in the internal API or something like that. 

e.g. 

```
kind: v1/Group
spec:
 name: "parent"

---

kind: v1/Group
dependency:   
  requirement: exists
  kind : v1/Group
  selector: 
     name: "parent"
spec:
  name": "child"

---
kind: v1/User
dependency: 
  requirement: exists
  kind : v1/Group
  selector: 
     name: "child"
spec:
  name: "user"
  groups: [ { name: "child"  } ]
        
```        


May I miss the point but actually the capabilities to import complex trees as a one off operations is sometimes a problem with keycloak for all domain objects not only for groups.
