### DISCUSSION TITLE
Connect to SqlServer named istance with dynamic port on docker container

### DISCUSSION THREAD

**Discussion by fabiorich-ico** [keycloak/keycloak#9582] [Q&A]
Hi,
I'm trying to pull up keycloak via docker by connecting to a SqlServer db.
If I try to connect to a normal db everything works normally, if I try to connect to the same server but to named instance with dynamic port the connection fails.

The question is:
is it possible to connect to a named instance named istance with dynamic port? Do you need to specify any special parameters?

Here are some examples:
```yml
services:
  auth:
    image: jboss/keycloak
    environment:
      DB_VENDOR: mssql
      DB_ADDR: {server_name}
      DB_DATABASE: {db_name}
      DB_USER: {db_user}
      DB_PASSWORD: {db_password}
      ...
```
IT WORKS!

```yml
services:
  auth:
    image: jboss/keycloak
    environment:
      DB_VENDOR: mssql
      DB_ADDR: {server_name}\{istance_name}
      DB_DATABASE: {db_name}
      DB_USER: {db_user}
      DB_PASSWORD: {db_password}
      ...
```
IT NOT WORKS!

Thanks
