### DISCUSSION TITLE
TLS host ingress Keycloak Operator

### DISCUSSION THREAD

**Discussion by Eddie4Frost** [keycloak/keycloak#9621] [Q&A]
Hi everyone, I hope you are doing great and safe, could you please help me with the question, if there's a way to define a https termination using the keycloak operator spec:
```yaml
 externalAccess:
    enabled: True
    host: keycloak.domain.com
```
Same as we set in Ingress using the array:
```yaml
tls:
  - hosts:
    - keycloak.domain.com
   secretName: my-tls
```

Thank you in advance, cya
