### DISCUSSION TITLE
Configure volume and configure https keycloak

### DISCUSSION THREAD

**Discussion by evandroteixeira1710** [keycloak/keycloak#9630] [Q&A]
Good afternoon,
I'm trying to configure the keyclock to use it in a demand of our project, I'm using the postgres compose model.
```
version: '3'
volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres
      volumes:
        - ./postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:latest
       - ./keycloak_data:/opt/jboss/keycloak/providers
       - ./keycloak_data:/opt/jboss/keycloak/standalone/configuration
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        
      ports:
        - 8080:8080
      depends_on:
        - postgres
 volumes:
    keycloack_data:
    postgres_data:
```
However, it is not mounting the keycloak volume, it returns an error:
opt/jboss/keycloak/bin/add-user.sh (permission denied).
And the container does not go up.
I'm trying to use this process, in order to configure the standealone.xml for https, I already have the certificates.
