### ISSUE TITLE
keycloak-operator uses wrong version & readiness and liveness probes issue

### ISSUE THREAD

**Issue by ThatDeveloper** [keycloak/keycloak#10310]
### Describe the bug

I just deployed the new operator when I saw that 17.0 was deployed.
When starting it I saw a lot of WildFly in the console and that confused me. While inspecting the deployment I saw that the legacy image is used (quay.io/keycloak/keycloak:17.0.0-legacy). Why is this the case?

It also looks like there is  an issue with the readiness and liveness probes as with the following configuration the instance stays on 1 instance and it does not accept incoming connections.

I assume the probes fail because it is not using the faster quarkus image?

```
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  instances: 3

  multiAvailablityZones:
    enabled: true

  podDisruptionBudget:
    enabled: true
  
  # IPv6
  keycloakDeploymentSpec:
    experimental:
      env:
      - name: "JAVA_OPTS"
        value: "-Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true -Djboss.bind.address.private=::1 -Djboss.bind.address=::1"

  # https://www.keycloak.org/docs/latest/server_installation/#_operator-upgrade-strategy
  migration:
    strategy: rolling
    backups:
      enabled: true

  externalDatabase:
    enabled: true
```

### Version

17.0

### Expected behavior

The operator starts, using the new quarkus powerd distro and successfully gets through the liveness and readiness probes.

### How to Reproduce?

EKS cluster on AWS
1.21 - IPv6 cluster

5 nodes running within 3 availbility zones and enough cpu / ram.
