### ISSUE TITLE
Keycloak 17 (Quarkus) slow when node dies in distributed caching setup with cache_stack=kubernetes

### ISSUE THREAD

**Issue by vdahlberg** [keycloak/keycloak#10359]
### Describe the bug

While running keycloak 17(quarkus) in clustered mode with `KC_CACHE_STACK=kubernetes`, on kubernetes, it get's extremely slow when a pod dies/restarts and is very slow for 4-5 minutes. After that everything is fine.

I think this has something to do with the distributed cache, since there is no issue when the infinispan "nodes"(?) can't discover each other (misconfigured discovery for example, and every new pod believe it's the 'master').

It is not an issue with 17.0-legacy (wildfly), only the quarkus variant.

I'm not sure if I'm missing any configuration or if this is a bug.

This is the Dockerfile I'm using:
```
FROM quay.io/keycloak/keycloak:17.0.0 as builder

ENV KC_METRICS_ENABLED=true \
    KC_DB=mysql \
    KC_CACHE_STACK=kubernetes \
    KC_STACK=ispn

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:17.0.0
COPY --from=builder /opt/keycloak/lib/quarkus/ /opt/keycloak/lib/quarkus/


ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```

And this is the statefulset + service:
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  serviceName: keycloak-headless
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: "" # Image built by dockerfile
        args: ["-Djgroups.dns.query=keycloak-headless", "start", "--spi-sticky-session-encoder-infinispan-should-attach-route=false"]
        env:
        - name: KEYCLOAK_ADMIN
          value: "" # admin user
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kcsecret
              key: adminpassword
        - name: KC_HOSTNAME
          value: "" # HOST
        - name: KC_HOSTNAME_STRICT_BACKCHANNEL
          value: "true"
        - name: KC_PROXY
          value: "edge"
        - name: KC_DB_USERNAME
          value: "keycloak"
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kcsecret
              key: dbpassword
        - name: KC_DB_URL_HOST
          value: "" # DB HOST
        - name: KC_DB_URL_PROPERTIES
          value: "?characterEncoding=UTF-8"
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: keycloak-headless
  labels:
    app: keycloak
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
```

### Version

17 (quarkus)

### Expected behavior

Should not be slow (almost unresponsive) for ~5 minutes when a node dies, and a new one starts to join.

### How to Reproduce?

Build the dockerfile in and run it in kubernetes with the statefulset and service.
