### ISSUE TITLE
production mode: ERROR: Cannot set quarkus.http.redirect-insecure-requests without enabling SSL

### ISSUE THREAD

**Issue by ruckc** [keycloak/keycloak#10902]
### Describe the bug

I'm trying to start a production mode quarkus 17.0.1 keycloak, and it stops with this error

>  ERROR: Cannot set quarkus.http.redirect-insecure-requests without enabling SSL

My environment variables are below, and i've validated the certificate/key are accurate and readable.

```yaml
        - name: KC_PROXY
          value: reencrypt
        - name: KC_DB
          value: postgres
        - name: KC_HOSTNAME
          value: keycloak
        - name: KC_HOSTNAME_STRICT_BACKCHANNEL
          value: "true"
        - name: KC_HOSTNAME_STRICT
          value: "true"
        - name: KC_HTTPS_CERTIFICATE_FILE
          value: /certs/tls.crt
        - name: KC_HTTPS_CERTIFICATE_FILE_KEY
          value: /certs/tls.key
        - name: JDBC_PARAMS
          value: sslmode=require
        - name: KC_DB_URL_DATABASE
          value: keycloak
        - name: KC_DB_URL_HOST
          value: keycloak-database-postgres
        - name: KC_METRICS_ENABLED
          value: "true"
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: database-credentials
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: database-credentials
```

### Version

17.0.1

### Expected behavior

Running keycloak

### Actual behavior

It fails to start

### How to Reproduce?

Using the above environment  variables

### Anything else?

I really can't stand this `start` and `start-dev` when the difference isn't documented.  Seems like this magic mojo maybe breaking somewhere.
