### ISSUE TITLE
Keycloak 17 Quarkus: PostgreSQL SCRAM-SHA-256 authentication not working

### ISSUE THREAD

**Issue by AGrzella** [keycloak/keycloak#10944]
### Describe the bug

Hi, I've configured the PostgreSQL DB Instance with SCRAM-SHA-256 authentication.
Keycloak 17 Quarkus is not able to authenticate at PostgreSQL.
The PostgreSQL error is:
`User "keycloak" does not have a valid SCRAM verifier.`

### Version

17 Quarkus

### Expected behavior

Authentication with SCRAM-SHA-256 protected pw should work out of the box.

### Actual behavior

Authentication with SCRAM-SHA-256 not working.

### How to Reproduce?

configure PostgreSQL with support for SCRAM and reset the pw

### Anything else?

https://stackoverflow.com/questions/64316324/i-tried-to-change-postgresql-md5-to-scram-sha-256-and-i-get-fatal-password-authe

**Comment by DGuhr** [comment]
Hi @AGrzella 

could you give a bit more information on e.g. which version of keycloak is used, or e.g. a reproducer in terms of a docker-compose file or similar? 

For me it seems there must be a specific problem in your postgres setup. I just spun up the following `compose.yml` file, using latest keycloak on quarkus (17.0.1):
```
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    command: ["start-dev"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak-secret
    ports:
      - 8080:8080
    depends_on:
      - postgres_scram
  postgres_scram:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak-secret
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    ports:
      - 5432:5432
    volumes:
      - pgtest-volume:/var/lib/postgresql/data
volumes:
  pgtest-volume:
    driver: local
```

and it worked as expected. Database gets initialized using `scram-sha-256` (see screenshot below)
<img width="1101" alt="Screenshot 2022-03-29 at 13 29 16" src="https://user-images.githubusercontent.com/89905860/160601670-b1dd7a6c-a002-43c7-94e5-4f9da80f5976.png">


and keycloak creates the database scheme,  admin user is created and i can login and create e.g. clients using localhost:8080. 

So, at the moment it seems for me your database setup might need some tweaks, but in general keycloak works with SCRAM-sha-256 :) 

Will close here for now. Feel free to re-open when you think there is still a problem on the keycloak side of the db connection.
