### ISSUE TITLE
MySQL database empty when using start-dev with the docker container

### ISSUE THREAD

**Issue by bogdanr** [keycloak/keycloak#10959]
### Describe the bug

Hello,

My keycloak instance didn't write anything in the database when I used the start-dev parameter.
I am using this because I wanted to avoid having SSL in keycloack as I have an ELB with SSL in front of it.

I know for sure that the instance tried to connect to the DB as it didn't want to start when I had some incorrect credentials for MySQL. But I was very disappointed when I wanted to restore some data from the database because there was nothing written there.

When I finally configured SSL also and started with the start parameter it also started to write to the database.

### Version

16.1.1

### Expected behavior

Write all the configuration to the MySQL database

### Actual behavior

Nothing was written in the database

### How to Reproduce?

start the server with mysql and start-dev

**Comment by DGuhr** [comment]
Hey @bogdanr it would really help if you could give us more info on "how to reproduce", describing the environment and the exact commands you used (for sure without credentials or sth). Also an exception, if any, would be good to see.

For now I can confirm that this is no general error. I just started kc 16.1.1 and a mysql docker environment using this docker compose:

```
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak-x:16.1.1
    command: ["start-dev"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL_HOST=mysql
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak-secret
    ports:
      - 8080:8080
      - 8443:8443
      - 9990:9990
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=keycloak-secret
      - MYSQL_ROOT_PASSWORD=supersecret
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
    driver: local
```

The result you can see in the screenshot. KC is running and the mysql database got inited correctly and is used. Also a client I created earlier survives docker compose down / up (expected, as the volume is there).
 
![Screenshot 2022-03-29 at 10 21 31](https://user-images.githubusercontent.com/89905860/160567393-3e8330a2-ff40-403f-b891-b393d86d39ef.png) 

So at the moment this is not reproducible without further information.
