### ISSUE TITLE
"Could not find resource for full path.." from any endpoint

### ISSUE THREAD

**Issue by hookenful** [keycloak/keycloak#11078]
### Describe the bug

Hello!

I am hosting keycloak 17.0.1 in docker on M1 with built 17.0.1 image on my own. It starts in development mode, UI is shown and configurable, but when I try to get for any API endpoint I am having error:

`{
    "error": "RESTEASY003210: Could not find resource for full path: http://localhost:8081/auth/master/user"
}`

![image](https://user-images.githubusercontent.com/31849464/161351917-9ae804ef-4acd-4b1c-a5e4-0347062d1f2d.png)

My docker-compose keycloak service:

```
  keycloak:
    image: quarkus-keycloak:17.0.1
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloakdb
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    networks:
      - coffeeface
    ports:
      - 8081:8080
    depends_on:
      - keycloakdb
    command:
      - "start-dev"
```

Haven't anyone faced that issue? Thanks in advance.

### Version

17.0.1
