### ISSUE TITLE
Keycloak 17.0.1 behind NginX reverse proxy

### ISSUE THREAD

**Issue by hookenful** [keycloak/keycloak#11372]
### Describe the bug

Hello there!

I am configuring keycloak in compose like that:

```
  keycloak:
    image: quay.io/keycloak/keycloak:17.0.1
    depends_on:
      - keycloakdb
    networks:
      - net
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: sS3459ol
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_METRICS_ENABLED: 'true'
      KC_FEATURES: token-exchange
      KC_HTTP_ENABLED: 'true'
    command:
      - "start"
      - "--auto-build"
      - "--hostname=localhost"
      - "--hostname-port=3000"
      - "--hostname-path=/keycloak"
      - "--proxy"
      - "edge"
    container_name: keycloak
```

I have nginx proxy with such config:

```
  nginx:
    build: src/nginx
    environment:
      ENVIRONMENT_NAME: Development
    ports:
      - "3000:80"
```
```
server {

  listen 80;

  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";

   proxy_http_version 1.1;
   proxy_set_header X-Forwarded-Host $host;
   proxy_set_header X-Forwarded-Server $host;
   proxy_set_header X-Real-IP $remote_addr;
   proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
   proxy_set_header X-Forwarded-Proto $scheme;
   proxy_set_header Host $http_host;
   proxy_set_header Upgrade $http_upgrade;
   proxy_set_header Connection "Upgrade";
   proxy_pass_request_headers on;

  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    try_files $uri $uri/ /index.html;
  }

  location /keycloak/ {

    proxy_pass  http://keycloak/;
  }
}
```

When navigating to `http://localhost:3000/keycloak` I am redirecting to 80 port.. What did I miss?
![image](https://user-images.githubusercontent.com/31849464/163847412-953740cd-8779-4baf-ae43-db426d660ea6.png)

Thanks in advance!

### Version

17.0.1

### Expected behavior

Navigating on admin console through nginx proxy localhost:3000/keycloak
