### ISSUE TITLE
SSL_ERROR_RX_RECORD_TOO_LONG

### ISSUE THREAD

**Issue by alirizaaribas-ibg** [keycloak/keycloak#11485]
### Describe the bug

I got this error:
On Firefox 99.0.1 `SSL_ERROR_RX_RECORD_TOO_LONG`
On Chrome 100.0.4896.88 `ERR_SSL_PROTOCOL_ERROR`

### Version

16.1.1

### How to Reproduce?

I use docker to run keycloak: `docker-compose -f pori.yml up -d`

YML file:
```
version: '3'
services:
  keycloak:
    build:
      context: .
      dockerfile: ./demo/Dockerfile.auth
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true"
      JAVA_OPTS_APPEND: "-Djboss.socket.binding.port-offset=808"
    ports:
      - 8888:8888
    networks:
      - app-network
    healthcheck:
      # test fetching public key from PORI realm
      test: ["CMD", "bash", "/scripts/kc_setup_keyfile.sh", "http://10.100.120.219:8888/auth", "admin", "admin", "PORI", "/keys/keycloak.key"]
      interval: 45s
      timeout: 10s
      retries: 5
    volumes:
      - source: ./keys
        target: /keys
        type: bind
```

ENV KEYCLOAK_VERSION 16.1.1
4 | 0 B | ENV JDBC_POSTGRES_VERSION 42.2.5
5 | 0 B | ENV JDBC_MYSQL_VERSION 8.0.22
6 | 0 B | ENV JDBC_MARIADB_VERSION 2.5.4
7 | 0 B | ENV JDBC_MSSQL_VERSION 8.2.2.jre11
