### ISSUE TITLE
Starting with Dockek on Mac M1 Chip

### ISSUE THREAD

**Issue by fstaine** [keycloak/keycloak#11543]
### Describe the bug

I tried to rebuild keycloak in order to add a custom theme.

Prior doing this, I tried to create a container with the features I use with the following Dockerfile:
```Dockerfile
FROM quay.io/keycloak/keycloak:17.0.1 as builder

ENV KC_FEATURES=token-exchange,admin_fine_grained_authz
ENV KC_DB=postgres
ENV KC_CACHE=local
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:17.0.1
COPY --from=builder /opt/keycloak/lib/quarkus/ /opt/keycloak/lib/quarkus/
WORKDIR /opt/keycloak

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]

CMD ["start"]
```

Here is the `docker-compose.yml` I use:
```yml
services:
    iam:
        container_name: cyg-iam
        image: cyg-identity
        depends_on: [rdbms]
        environment:
            KEYCLOAK_ADMIN: cyg-admin
            KEYCLOAK_ADMIN_PASSWORD: cyg-admin
            KC_DB_PASSWORD: admin
            KC_DB_URL_DATABASE: cyg_identity
            KC_DB_URL_HOST: rdbms:5432
            KC_DB_USERNAME: cyg_identity_admin
            KC_HOSTNAME: localhost
            KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/conf/server.crt.pem
            KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/conf/server.key.pem
        volumes:
            - ./keycloak/server.crt.pem:/opt/keycloak/conf/server.crt.pem
            - ./keycloak/server.key.pem:/opt/keycloak/conf/server.key.pem
        command:
          [
              '--verbose',
              'start-dev',
          ]
```

The postgres server is up and running correctly from another container. 

After starting the service, I have the following logs then nothing, even after waiting 30 minutes, the service seems blocked, without any other output:

```
cyg-rdbms is up-to-date
Recreating cyg-iam... done
Attaching to cyg-iam
cyg-iam   | Updating the configuration and installing your custom providers, if any. Please wait.
cyg-iam   | 2022-04-20 14:15:54,636 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 32329ms
cyg-iam   | 2022-04-20 14:16:08,912 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: localhost, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: -1, Proxied: false
cyg-iam   | 2022-04-20 14:16:12,605 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
cyg-iam   | 2022-04-20 14:16:12,652 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
cyg-iam   | 2022-04-20 14:16:12,748 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
cyg-iam   | 2022-04-20 14:16:13,614 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.6.Final
cyg-iam   | 2022-04-20 14:16:15,226 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: node_201656, Site name: null
cyg-iam   | 2022-04-20 14:16:22,451 INFO  [org.keycloak.quarkus.runtime.storage.database.liquibase.QuarkusJpaUpdaterProvider] (main) Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml
```

### Version

17.0.1

### Expected behavior

The server should start correctly

### Actual behavior

The server isn't starting and is not accessible

### How to Reproduce?

I had issues with the version previously used (`16.0.1`) and I had to build the Docker image myself to make it work with my Mac M1. 
I don't know if this issue could be related to the ARM architecture.
