### ISSUE TITLE
Keycloak 18.0.0 not connecting to postgress

### ISSUE THREAD

**Issue by SebastianThorn** [keycloak/keycloak#11566]
### Describe the bug

I just tried the new version 18.0.0 with same settings as i had with 17.0.1,
but 18 wont connect to my database.

Downgraded to 17 and it works again.

tcpdump on my database server can't see any traffic from Keycloak.

Was there some changes to 18 that would affect this?
All I could see was the driver upgrade: https://www.keycloak.org/2022/04/keycloak-1800-released

### Version

18.0.0

### Expected behavior

Database to connect

### Actual behavior

Database wont connect

### How to Reproduce?

**docker-compose.yaml**
```yaml
---

version: "3.7"

services:

  keycloak:
    container_name: keycloak
    image: "harbor.container.zp.mega-corp.org:8443/it-mega/mega_keycloak-zp:18.0.0"
    ports:
      - "8443:8443"
    environment:
      KC_HOSTNAME: idp-zp.zp.mega-corp.org:443
      KC_DB: postgres
      KC_DB_USERNAME: pqgs_username
      KC_DB_PASSWORD: sdfgsdfgsdfgsdf
      KC_DB_URL_HOST: 10.70.81.70:5432
      KC_DB_URL_DATABASE: keycloak
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/cert.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/cert.key
      KEYCLOAK_ADMIN: HRuR2rPBG3HzLz2sWjAy3sJNkC5yLfb5
      KEYCLOAK_ADMIN_PASSWORD: qVCgjTjvDJ68ktWSHnqsjpPQSnQkHLS4
      KC_PROXY: reencrypt
      PROXY_ADDRESS_FORWARDING: "true"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HOSTNAME_STRICT: "false"
      # KC_LOG_LEVEL: "DEBUG"
    volumes:
      - ./cert.crt:/etc/x509/https/cert.crt
      - ./cert.key:/etc/x509/https/cert.key
    restart: "no"
```

### Anything else?

ansible@keycloak-001:/opt/docker_conf/itp_keycloak_prd$ docker-compose up
Starting keycloak ... done
Attaching to keycloak
keycloak    | 2022-04-21 08:59:38,154 INFO  [org.keycloak.common.Profile] (main) Preview feature enabled: token_exchange
keycloak    | 2022-04-21 08:59:38,181 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: idp-zp.zp.mega-corp.org:443, Strict HTTPS: false, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: -1, Proxied: true
keycloak    | 2022-04-21 08:59:38,416 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': The connection attempt failed.
keycloak    | 2022-04-21 08:59:38,418 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: org.postgresql.util.PSQLException: The connection attempt failed.
keycloak    |   at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:331)
keycloak    |   at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
keycloak    |   at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
keycloak    |   at org.postgresql.Driver.makeConnection(Driver.java:400)
keycloak    |   at org.postgresql.Driver.connect(Driver.java:259)
keycloak    |   at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
keycloak    |   at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
keycloak    |   at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:103)
keycloak    |   at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:49)
keycloak    |   at org.postgresql.xa.PGXADataSource.getXAConnection(PGXADataSource.java:35)
keycloak    |   at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:216)
keycloak    |   at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:513)
keycloak    |   at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:494)
keycloak    |   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
keycloak    |   at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
keycloak    |   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
keycloak    |   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
keycloak    |   at java.base/java.lang.Thread.run(Thread.java:829)
keycloak    | Caused by: java.net.UnknownHostException: 10.70.81.70:5432
keycloak    |   at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:229)
keycloak    |   at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
keycloak    |   at java.base/java.net.Socket.connect(Socket.java:609)
keycloak    |   at org.postgresql.core.PGStream.createSocket(PGStream.java:241)
keycloak    |   at org.postgresql.core.PGStream.<init>(PGStream.java:98)
keycloak    |   at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:109)
keycloak    |   at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)
keycloak    |   ... 17 more
keycloak    |
keycloak    | 2022-04-21 08:59:39,127 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': The connection attempt failed.
keycloak    | 2022-04-21 08:59:39,191 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
keycloak    | 2022-04-21 08:59:39,226 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
keycloak    | 2022-04-21 08:59:39,239 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
keycloak    | 2022-04-21 08:59:39,398 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.8.Final
keycloak    | 2022-04-21 08:59:39,498 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
keycloak    | 2022-04-21 08:59:39,498 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
keycloak    | 2022-04-21 08:59:39,582 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
keycloak    | 2022-04-21 08:59:39,583 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20.00MB, but the OS only allocated 212.99KB
keycloak    | 2022-04-21 08:59:39,585 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
keycloak    | 2022-04-21 08:59:39,587 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25.00MB, but the OS only allocated 212.99KB
keycloak    | 2022-04-21 08:59:41,601 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) 3e99c87e3eef-28283: no members discovered after 2005 ms: creating cluster as coordinator
keycloak    | 2022-04-21 08:59:41,610 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [3e99c87e3eef-28283|0] (1) [3e99c87e3eef-28283]
keycloak    | 2022-04-21 08:59:41,618 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `3e99c87e3eef-28283`, physical addresses are `[172.27.0.2:55047]`
keycloak    | 2022-04-21 08:59:42,090 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
keycloak    | 2022-04-21 08:59:42,252 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
keycloak    | 2022-04-21 08:59:42,252 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
keycloak    | 2022-04-21 08:59:42,253 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: The connection attempt failed.
keycloak    | 2022-04-21 08:59:42,254 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: 10.70.81.70:5432
keycloak    | 2022-04-21 08:59:42,254 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
keycloak exited with code 1
