### ISSUE TITLE
Enable Horizontal Pod Autoscaling for Keycloak deployed with the new Operator

### ISSUE THREAD

**Issue by svilenvul** [keycloak/keycloak#11632]
### Description

My current research showed that Horizontal Pod Autoscaling for Keycloak deployed with the new Operator is not implemented yet.

While we are trying to migrate to the new operator based deployment we executed load tests.
We saw that referencing our Keycloak CRD in the Horizontal pod autoscaling resource did not have any effect. Example:

```
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: example-hpa
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 2
    type: Resource
  scaleTargetRef:
    apiVersion: keycloak.org/v2alpha1
    kind: Keycloak
    name: example-keycloak
```

Scaling the deployment of Keycloak with an HPA is also not possible as the operator is terminating the pods.

### Motivation

This is an important feature for the new operator so that it can be used in production deployments IMHO.

### Details

As far as I understood Keycloak CRD has to implement the scale subresource: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#scale-subresource.

After that changes in the operator are needed to handle the automatic scaling based on this subresouce.
