### ISSUE TITLE
mismatching property name for Keycloak CRD

### ISSUE THREAD

**Issue by WestFarmer** [keycloak/keycloak#11685]
### Describe the bug

Operator version: quay.io/keycloak/keycloak-operator:18.0.0

manifest:
```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: centauri-kc
  namespace : devops
spec:
  disableDefaultIngress: true
  instances: 1
  image: centauri/centauri-keycloak:18.0.0-1.0
  serverConfiguration:
    - name: db
      value: postgres
    - name: db-url
      value: jdbc:postgresql://pg-svc/keycloak
    - name: db-username
      value: keycloak
    - name: db-password
      value: keycloak
  hostname: keycloak.bgzchina.com
  tlsSecret: bgzchina-le
```

log:
`Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "disableDefaultIngress" (class org.keycloak.operator.v2alpha1.crds.KeycloakSpec), not marked as ignorable (7 known properties: "defaultIngressDisabled", "serverConfiguration", "unsupported", "image", "instances", "hostname", "tlsSecret"])`

seems operator expect "defaultIngressDisabled", while CRD defined "disableDefaultIngress"

### Version

18.0.0

### Expected behavior

CRD Keycloak instance created.

### Actual behavior

operator throws exception.
