### ISSUE TITLE
Can't login with generated user/password

### ISSUE THREAD

**Issue by WestFarmer** [keycloak/keycloak#11722]
### Describe the bug

using new operator to deploy keycloak on vanilla kubernetes.

please note I have modified CRD keycloak due to another issue #11685 

custom image:
```dockfile
FROM keycloak/keycloak:18.0.0 as builder

ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_FEATURES=token-exchange
ENV KC_DB=postgres
# Install custom providers
RUN curl -sL https://github.com/aerogear/keycloak-metrics-spi/releases/download/2.5.3/keycloak-metrics-spi-2.5.3.jar -o /opt/keycloak/providers/keycloak-metrics-spi-2.5.3.jar
RUN /opt/keycloak/bin/kc.sh build

FROM keycloak/keycloak:18.0.0
COPY --from=builder /opt/keycloak/ /opt/keycloak/
WORKDIR /opt/keycloak
# change these values to point to a running postgres instance
ENV KC_DB_URL=jdbc:postgresql://pg-svc/keycloak
ENV KC_DB_USERNAME=keycloak
ENV KC_DB_PASSWORD=keycloak
ENV KC_HOSTNAME=keycloak.bgzchina.com
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```
manifest:
```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: centauri-kc
  namespace : devops
spec:
  defaultIngressDisabled: true
  instances: 1
  image: centauri/centauri-keycloak:18.0.0-1.0
  serverConfiguration:
    - name: db
      value: postgres
    - name: db-url
      value: jdbc:postgresql://pg-svc/keycloak
    - name: db-username
      value: keycloak
    - name: db-password
      value: keycloak
    - name: proxy
      value: passthrough
  hostname: keycloak.bgzchina.com
  tlsSecret: bgzchina-le
```
following the docs, get username/password:

```bash
kubectl get -n devops secret centauri-kc-initial-admin  -o jsonpath='{.data.username}' | base64 --decode
admin (there is no newline actually, added for formating)
kubectl get -n devops secret centauri-kc-initial-admin  -o jsonpath='{.data.password}' | base64 --decode
f9d65cf676454ec4bf339318c029ba3a (there is no newline actually, added for formating)
```

however, with these username/password, I can't loing into the admin console.
![image](https://user-images.githubusercontent.com/14016562/165663656-a443953f-2672-4e27-b1c1-71eb745d0c49.png)

### Version

18.0.0

### Expected behavior

can login with generated username/password

### Actual behavior

login failed.
