### ISSUE TITLE
Deploying keycloak with http (not https!) only

### ISSUE THREAD

**Issue by ctron** [keycloak/keycloak#11926]
### Describe the bug

It is possible to deploy keycloak, using the operator, in http (not https!) mode. Which makes sense for development setups, using e.g. Minikube or Kind.

However, in that case, e.g. the admin console doesn't work, as it always redirects to `https://`, even if the port is 80:

![image](https://user-images.githubusercontent.com/202474/167646821-0bfea06c-4dec-4c6b-9632-d43068a89aab.png)

This did work in 17 (legacy).

### Version

18.0.0

### Expected behavior

Allows to use plain HTTP.

### Actual behavior

Wrongly redirects from http to https when opening the admin console.

### How to Reproduce?

Use the following CR:

```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: sso
spec:
  hostname: sso.192.168.39.167.nip.io
  instances: 1
  serverConfiguration:
  - name: db
    value: postgres
  - name: db-url-database
    secret:
      key: database
      name: keycloak-db-secret
  - name: db-url-host
    secret:
      key: host
      name: keycloak-db-secret
  - name: db-url-port
    secret:
      key: port
      name: keycloak-db-secret
  - name: db-username
    secret:
      key: username
      name: keycloak-db-secret
  - name: db-password
    secret:
      key: password
      name: keycloak-db-secret
  - name: hostname-strict
    value: "false"
  - name: hostname
    value: sso.192.168.39.167.nip.io
  - name: hostname-port
    value: "80"
  - name: proxy
    value: passthrough
  tlsSecret: INSECURE-DISABLE
```

**Comment by ctron** [comment]
It looks like keycloak returns some config, which includes `https` by default, ignoring the actual settings and requests:

```json
{"realm":"master","auth-server-url":"https://sso.192.168.39.167.nip.io:80/","ssl-required":"external","resource":"security-admin-console","public-client":true,"confidential-port":0}
```

**Comment by Wolfsrudel** [comment]
You'll need to set the hidden parameter `hostname-strict-https` to `false`.

**Comment by Wolfsrudel** [comment]
I'm stuck there too. I assume you have a proxy in front of it? I think it has something to do with the headers, but I haven't been able to find a suitable combination of possible solutions that works. 😅

**Comment by andreaTP** [comment]
Thanks a lot for opening this issue!

Just tested that everything works "as expected" using local port-forward( `kubectl port-forward service/sso-service 8080:8080` ) and those settings:

```yaml
    - name: hostname-strict-https
      value: "false"
    - name: proxy
      value: edge # tested also with "passthrough"
  hostname: INSECURE-DISABLE
  tlsSecret: INSECURE-DISABLE
 ```
 
Going to test with `hostname` and will get back to you.

**Comment by andreaTP** [comment]
Tested with the above configuration on `minikube` with the Docker driver (host is Mac):
 - add `127.0.0.1 example.org` to `/etc/hosts`
 - deploy Keycloak
 - start ina terminal `sudo minikube tunnel`
 - browse `http://example.org/`
 
 
![Screenshot 2022-05-10 at 17 44 19](https://user-images.githubusercontent.com/5792097/167680745-24968c69-93c2-4f9a-8630-76e8a79d8cc9.png)

**Comment by andreaTP** [comment]
Sorry for the multiple messages but tested with `nip.io` i.e. `hostname: 127-0-0-1.nip.io` (on top of `minikube tunnel`) as well:
![Screenshot 2022-05-10 at 17 50 11](https://user-images.githubusercontent.com/5792097/167681662-b10a3f25-9e5c-4070-a5a8-c93d6f276094.png)

**Comment by ctron** [comment]
Ok, just a quick update (some more might follow) as I was able to reproduce the issue with the settings you gave. However, those settings leave the `Ingress` object with no hostname. With makes it difficult to work with, as that rule now triggers for all requests on the cluster. Preventing other ingresses. I will do another round of tests and see if that `.spec.hostname` is the problem. As to my understanding that is what changes the value in the `Ingress` resource.

**Comment by ctron** [comment]
So I did to another test, just adding the `.spec.hostname` field. And this works too. The full configuration is this:

```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: sso
spec:
  hostname: sso.192.168.39.85.nip.io
  instances: 1
  serverConfiguration:
  - name: db
    value: postgres
  - name: db-url-database
    secret:
      key: database
      name: keycloak-db-secret
  - name: db-url-host
    secret:
      key: host
      name: keycloak-db-secret
  - name: db-url-port
    secret:
      key: port
      name: keycloak-db-secret
  - name: db-username
    secret:
      key: username
      name: keycloak-db-secret
  - name: db-password
    secret:
      key: password
      name: keycloak-db-secret
  - name: hostname-strict-https
    value: "false"
  - name: proxy
    value: edge
  tlsSecret: INSECURE-DISABLE
```

I am not sure which of the other parameters caused the problem. And I also don't know if this might have been caused by some stale configuration. But with this configuration I can reproducibly set up a working instance with "HTTP" only.

I would be great if this could make it into the documentation as: If you want HTTP only, use this configuration.
