### ISSUE TITLE
Keycloak Operator multiple namespaces / cluster wide

### ISSUE THREAD

**Issue by j0nm1** [keycloak/keycloak#11938]
### Description

Currently, the new operator can only manage keycloak instances within the namespace. This is a major problem for our projects as we would like to use different keycloak instances in different namespaces. 

Without this feature, I can't really see any advantage in using the operator as I would need to deploy an operator for each namespace.

### Motivation

All other operators that I know allow a configuration to manage instances in different namespaces or even cluster-wide. This allows us to separate teams and their environments.

Currently, when a team wants to deploy keycloak (with a new config or a new version) they would need to do this in a shared namespace (which leads to problems with the permissions) or create a new operator in their own namespace. Both solutions are pretty bad in my opinion and should not be the way to go.

**Comment by andreaTP** [comment]
Hi @j0nm1 and thanks for your interest in the new operator preview!!! 🙂 

I took a little time to answer because I wanted to find a viable workaround as I think your request is more than legit.

So, long story short, the new operator does already support watching multiple namespaces already but we haven't dedicated time/effort enough to make this a first-class supported feature.

The current workaround is:
 - add an environment variable to the [operator `Deployment`](https://github.com/keycloak/keycloak-k8s-resources/blob/153d9308503380fa076780a01669e4c9751a0c69/kubernetes/kubernetes.yml#L201)
```yaml
            - name: QUARKUS_OPERATOR_SDK_NAMESPACES
              value: test1,test2 # comma separated list of the namespaces to watch
```
 - create appropriate [RBAC resources](https://github.com/keycloak/keycloak-k8s-resources/blob/153d9308503380fa076780a01669e4c9751a0c69/kubernetes/kubernetes.yml#L30-L176) to let the operator perform its tasks in the defined namespaces. For example, assuming you have installed the operator in the `default` namespace, you should create those resources in namespace `test1` and `test2`:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloak-operator-role
rules:
  - apiGroups:
      - apps
      - extensions
    resources:
      - deployments
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keycloakcontroller-cluster-role
rules:
  - apiGroups:
      - k8s.keycloak.org
    resources:
      - keycloaks
      - keycloaks/status
      - keycloaks/finalizers
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: keycloak-operator
  name: keycloak-operator-role-binding
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: keycloak-operator-role
subjects:
  - kind: ServiceAccount
    name: keycloak-operator
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-operator-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: keycloak-operator
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloakcontroller-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: keycloakcontroller-cluster-role
subjects:
  - kind: ServiceAccount
    name: keycloak-operator
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloakrealmimportcontroller-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: keycloakrealmimportcontroller-cluster-role
subjects:
  - kind: ServiceAccount
    name: keycloak-operator
    namespace: default
```

Please note that being this a workaround on top of a "Preview" component, we cannot guarantee that the functionality will continue to work in this way in future releases.
On the good news, this functionality is, eventually, going to be implemented \in future releases of the operator.

cc. @vmuzikar
