### ISSUE TITLE
SQL Server DB connects ok start-dev, but fails when using start

### ISSUE THREAD

**Issue by keithn** [keycloak/keycloak#12061]
### Describe the bug

I'm just mucking around locally on some virtual machines trying to work out how I'd configure keycloak for production.... if I start it in dev, it connects to the DB, but if I use start, it doesn't.   I get "Could not obtain connection to query metadata: java.sql.SQLException: No suitable driver found for jdbc:sqlserver://192.168.1.146:1433;databaseName=Keycloak"

For reference this is my docker compose file
```
version: "3.2"

services:
    keycloak:
        image: quay.io/keycloak/keycloak:latest 
        container_name: keycloak
        ports:
            - "8090:8080"
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
            - KC_DB=mssql
            - KC_DB_USERNAME=keycloak
            - KC_DB_PASSWORD=keycloak
            - KC_DB_URL_HOST=192.168.1.146
            - KC_DB_URL_DATABASE=Keycloak
            - KC_HOSTNAME=localhost
            - KC_TRANSACTION_XA_ENABLED=false
        command: 
            - start
```

if I change that "start" to "start-dev" is when it fails with the above error, I know next to nothing about configuring keycloak, so I'm not sure whether I need to configure something else? or whether that is a problem.

### Version

18.0.0
