### ISSUE TITLE
UI Incorrect handling in 18.0.0 with multiple replicas

### ISSUE THREAD

**Issue by jasonmcintosh** [keycloak/keycloak#12060]
### Describe the bug

When deploying an Keycloak using::
```
      containers:
        image: quay.io/keycloak/keycloak:17.0.0
      - args:
        - start
        - --auto-build
        - --db=mysql
        - --http-relative-path=/auth
        - --http-enabled=true
        - --db-url=jdbc:mysql://mysql:3306/keycloak
        - --cache-stack=kubernetes
        - --proxy=edge
        - --hostname-strict=false
        - --hostname-strict-https=false
        env:
        - name: JAVA_OPTS_APPEND
          value: -Djgroups.dns.query=keycloak-cluster.NAMESPACE.svc.cluster.local
            -Dkeycloak.profile.feature.upload_scripts=enabled
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: replaceMe
        - name: KC_DB_USERNAME
          value: root
        - name: KC_DB_PASSWORD
          value: replaceMe
        - name: KC_PROXY
          value: edge
```
Making sure there's a service available for cluster discovery in that namespace, keycloak 17 works fine even with multiple replicas.  IN keycloak 18 of the distribution, it seems that something is broken where the UI server occasionally returns and occasionally doesn't.  

### Version

18

### Expected behavior

The UI should work on 18.  
An example URL failing:

curl -v http://console/auth/resources/18.0.0/common/keycloak/node_modules/autofill-event/autofill-event.js

returns only correctly half of the time - clustering on logs shows both pods in the cluster.

### Actual behavior

One of the replicas works, the other does not seem to return UI files.

### How to Reproduce?

```apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keycloak
  name: keycloak
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: keycloak
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - args:
        - start
        - --auto-build
        - --db=mysql
        - --http-relative-path=/auth
        - --http-enabled=true
        - --db-url=jdbc:mysql://mysql:3306/keycloak
        - --cache-stack=kubernetes
        - --proxy=edge
        - --hostname-strict=false
        - --hostname-strict-https=false
        env:
        - name: JAVA_OPTS_APPEND
          value: -Djgroups.dns.query=keycloak-cluster.REPLACEME.svc.cluster.local
            -Dkeycloak.profile.feature.upload_scripts=enabled
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: REPLACEME
        - name: KC_DB_USERNAME
          value: root
        - name: KC_DB_PASSWORD
          value: REPLACEME
        - name: KC_PROXY
          value: edge
        image: quay.io/keycloak/keycloak:18.0.0
        imagePullPolicy: IfNotPresent
        name: keycloak
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /auth/realms/master
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-cluster
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: keycloak
  clusterIP: None
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: console
spec:
  rules:
    - host: console
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080

### Anything else?

Wiping the database, going back to version 17, this works without issue.
