### ISSUE TITLE
Keycloak 18: Failed to obtain JDBC connection

### ISSUE THREAD

**Issue by MikeK184** [keycloak/keycloak#12213]
### Describe the bug

After successfully running keycloak in a Docker container with HTTPS certs I've decided add a volume to it to make data persistent. I've found the following (official) repo: https://github.com/keycloak/keycloak-containers/tree/main/docker-compose-examples that i used as a template for running `quay.io/keycloak/keycloak:18.0.0`. Eventually I ended up with the following **_docker-compose.yaml_**

```yaml
version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres:14
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:18.0.0
      environment:
        KC_DB: postgres
        KC_DB_URL: postgres
        KC_DB_URL_HOST: postgres
        KC_DB_URL_DATABASE: keycloak
        KC_DB_SCHEMA: public
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: password
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: password
        KC_HOSTNAME: keycloak.XXX.com
        KC_HTTPS_PORT: 443
        KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.cert
        KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
      volumes:
      - ./tls.cert:/etc/x509/https/tls.cert
      - ./tls.key:/etc/x509/https/tls.key
      ports:
        - 443:443
      command: start
      depends_on:
        - postgres   
```

### Version

18.0.0

### Expected behavior

That the keycloak container successfully connects to the postgres container in order to save persistent data.

### Actual behavior

Running the **_docker-compose.yaml_** however fails with the following output:
```bash
sudo docker-compose -f mariadb-compose.yaml up
Creating network "keycloak_default" with the default driver
Creating keycloak_postgres_1 ... done
Creating keycloak_keycloak_1 ... done
Attaching to keycloak_postgres_1, keycloak_keycloak_1
postgres_1  | 
postgres_1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres_1  | 
postgres_1  | 2022-05-26 18:59:56.664 UTC [1] LOG:  starting PostgreSQL 14.3 (Debian 14.3-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
postgres_1  | 2022-05-26 18:59:56.664 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1  | 2022-05-26 18:59:56.664 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1  | 2022-05-26 18:59:56.667 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres_1  | 2022-05-26 18:59:56.679 UTC [26] LOG:  database system was shut down at 2022-05-26 18:59:53 UTC
postgres_1  | 2022-05-26 18:59:56.686 UTC [1] LOG:  database system is ready to accept connections
keycloak_1  | 2022-05-26 18:59:59,501 WARN  [io.quarkus.runtime.configuration.ConfigRecorder] (main) Build time property cannot be changed at runtime:
keycloak_1  |  - quarkus.datasource.jdbc.driver is set to 'org.h2.jdbcx.JdbcDataSource' but it is build time fixed to 'org.postgresql.xa.PGXADataSource'. Did you change the property quarkus.datasource.jdbc.driver after building the application?
keycloak_1  | 2022-05-26 18:59:59,801 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: keycloak.XXX.com, Strict HTTPS: true, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: -1, Proxied: false
keycloak_1  | 2022-05-26 18:59:59,886 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': No suitable driver found for jdbc:postgresql://postgres:5432/keycloak
keycloak_1  | 2022-05-26 18:59:59,890 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: java.sql.SQLException: No suitable driver found for jdbc:postgresql://postgres:5432/keycloak
keycloak_1  |   at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:191)
keycloak_1  |   at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:352)
keycloak_1  |   at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:216)
keycloak_1  |   at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:513)
keycloak_1  |   at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:494)
keycloak_1  |   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
keycloak_1  |   at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
keycloak_1  |   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
keycloak_1  |   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
keycloak_1  |   at java.base/java.lang.Thread.run(Thread.java:829)
keycloak_1  | 
keycloak_1  | 2022-05-26 19:00:00,681 INFO  [org.infinispan.server.core.transport.EPollAvailable] (keycloak-cache-init) ISPN005028: Native Epoll transport not available, using NIO instead: java.lang.UnsatisfiedLinkError: could not load a native library: netty_transport_native_epoll_aarch_64
keycloak_1  | 2022-05-26 19:00:00,808 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
keycloak_1  | 2022-05-26 19:00:00,813 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
keycloak_1  | 2022-05-26 19:00:00,824 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
keycloak_1  | 2022-05-26 19:00:00,979 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.8.Final
keycloak_1  | 2022-05-26 19:00:01,091 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
keycloak_1  | 2022-05-26 19:00:01,091 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
keycloak_1  | 2022-05-26 19:00:01,183 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
keycloak_1  | 2022-05-26 19:00:01,184 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20.00MB, but the OS only allocated 212.99KB
keycloak_1  | 2022-05-26 19:00:01,186 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
keycloak_1  | 2022-05-26 19:00:01,187 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25.00MB, but the OS only allocated 212.99KB
keycloak_1  | 2022-05-26 19:00:03,203 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) a8efca73b940-46960: no members discovered after 2005 ms: creating cluster as coordinator
keycloak_1  | 2022-05-26 19:00:03,212 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [a8efca73b940-46960|0] (1) [a8efca73b940-46960]
keycloak_1  | 2022-05-26 19:00:03,219 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `a8efca73b940-46960`, physical addresses are `[172.24.0.3:42723]`
keycloak_1  | 2022-05-26 19:00:03,710 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: a8efca73b940-46960, Site name: null
keycloak_1  | 2022-05-26 19:00:03,716 WARN  [io.agroal.pool] (agroal-11) Datasource '<default>': No suitable driver found for jdbc:postgresql://postgres:5432/keycloak
keycloak_1  | 2022-05-26 19:00:03,747 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
keycloak_1  | 2022-05-26 19:00:03,805 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
keycloak_1  | 2022-05-26 19:00:03,805 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
keycloak_1  | 2022-05-26 19:00:03,805 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: No suitable driver found for jdbc:postgresql://postgres:5432/keycloak
keycloak_1  | 2022-05-26 19:00:03,806 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
keycloak_keycloak_1 exited with code 1
```

### How to Reproduce?

I've removed the certs and added the `KC_HTTP_ENABLED: "true"` parameter for everyone to try and get the same result:

```yaml
version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres:14
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:18.0.0
      environment:
        KC_DB: postgres
        KC_DB_URL: postgres
        KC_DB_URL_HOST: postgres
        KC_DB_URL_DATABASE: keycloak
        KC_DB_SCHEMA: public
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: password
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: password
        KC_HOSTNAME: keycloak.XXX.com
        KC_HTTPS_PORT: 443
        KC_HTTP_ENABLED: "true"
      #   KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.cert
      #   KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
      # volumes:
      # - ./tls.cert:/etc/x509/https/tls.cert
      # - ./tls.key:/etc/x509/https/tls.key
      ports:
        - 443:443
      command: start
      depends_on:
        - postgres   
```
