### ISSUE TITLE
Keycloak deployed by Operator does not appear to mount the truststore correctly

### ISSUE THREAD

**Issue by mjschmidt** [keycloak/keycloak#12231]
### Describe the bug

I have tried several ways to mount the truststore into a keycloak 18 deployment and it doesn't appear to take it.
I apologize in advance as I had to manually write out my yaml

When I try to pass the truststore via a secret:
```
kubectl create secret generic truststore.p12 --fromfile=truststore.p12
```

and then kc yaml:
```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  serverConfiguration:
    - name: db
      value: postgres # plain text value
    - name: db-url-host
      value: postgres-db # plain text value
    - name: db-username
      secret: # Secret reference
        name: keycloak-db-secret # name of the Secret
        key: username # name of the Key in the Secret
    - name: db-password
      secret: # secret reference
        name: keycloak-db-secret # name of the Secret
        key: password # name of the Key in the Secret
    - name: https-trust-store-file
      secret:
        name: truststore.p12
        key: truststore.p12
    - name: https-trust-store-password
      value: password
```

### Version

18.0.0

### Expected behavior

I expect keycloak and the container to pickup the truststore and use that, but it is not. Instead it is give the following error:
```
Error: failed to start container "keycloak": Error response from daemon: OCI runtime create failed: container_linux.go: 380: starting container process cuased: process_linux.go:545: container init caused: environment variable container contain null(\x00): ... etc.
```

I am not certain but it looks like it is trying to set the file I pass in as a variable?

I have also tried to use the kc api unsupported podTemplate features to pass the file into the container via volume mount and then tried to then set the  https-trust-store-file using a value rather than a secret pointing to a file. This seemed to at least not cause an error at runtime, but the keystore still did not load in even though I was able to exec into the container and validate that the file was in fact there.
```
name: https-trust-store-file
value: "/etc/pki/tls/certs/truststore.p12"
```

### Actual behavior

The truststore does not work, when I exec into the container and try to run a curl command out of the container i get ssl errors. When I try to add my ldap as a provider I get a test connection working and green but a connect to the ldap as a failure. When I check my ldap logs, I am able to see it is due to an ssl error.

### How to Reproduce?

deploy a test keycloak with a truststore and then validate that it works with an ldap that is using a cert verified by a non standard entity (therefore requiring keycloak make use of an associated truststore).

### Anything else?

I can see in my logs (it is set to debug)
```
DEBUG [org.keycloak.truststore.SSLSocketFactory] (executor-thread-3) No truststore provider found - using default SSLSocketFactory
```

**Comment by pedroigor** [comment]
@andreaTP I don't think it is a duplicate because https://github.com/keycloak/keycloak/issues/9784 seems to be about setting the truststore for TLS and not for Keycloak itself as a client to downstream services (e.g: LDAP) using TLS.

Do we have another one that could potentially improve the experience when configuring the TrustStore SPI ? That is the SPI that should be configured to properly communicate with downstream services through TLS.

**Comment by mjschmidt** [comment]
I was able to resolve this by using the spi-truststore-file-file parameter and an unsupported volume mount.

```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  serverConfiguration:
    - name: db
      value: postgres # plain text value
    - name: db-url-host
      value: postgres-db # plain text value
    - name: db-username
      secret: # Secret reference
        name: keycloak-db-secret # name of the Secret
        key: username # name of the Key in the Secret
    - name: db-password
      secret: # secret reference
        name: keycloak-db-secret # name of the Secret
        key: password # name of the Key in the Secret
    - name: spi-truststore-file-file #yes, the variable is file-file...
      value: "path/to/file.jks"
    - name: spi-truststore-file-password
      value: password
  unsupported:
    podTemplate:
      metadata:
        labels:
           name: example-kc
        spec:
          containers:
            volumeMounts:
              - name: jks-secret
                mountPath: path/to/file.jks
            volumes:
              - name: jks-secret
                secret:
                  secretName: jks-k8s-secret
                  items:
                  - key: jksTrustStore
                    path: file.jks
```
