### ISSUE TITLE
Support Kerberos in the operator

### ISSUE THREAD

**Issue by alexpdp7** [keycloak/keycloak#12577]
### Description

Add a mechanism to configure a keytab and any other requirement to configure Keycloak to integrate with FreeIPA

### Motivation

From https://www.keycloak.org/operator/advanced-configuration#_pod_template :+1: 

> This field is intended to be used as a temporary workaround if there is no officially supported field at the top level of the CR to cover your use-case. Please consider opening an issue on GitHub to help us make the experience better.

I'm using the operator to install Keycloak on a plain Kubernetes cluster. I wish to connect Keycloak to my FreeIPA instance and allow authentication using Kerberos. Reading the documentation I see that I need to include (at least) a relevant keytab in the Keycloak pod for this to work.

I assume I can do this with `podTemplate`, so I suppose I should ask for some "supported" configuration option to do this? I could build my own image and do everything with supported configuration, but it seems overkill.

### Details

If I can dream, you could have parameters for an IPA domain, allowed user and some way to get a password and the Keycloak operator would install Keycloak with FreeIPA integrated to the default realm. That would be truly awesome!

(And this is the experience that Ipsilon had- setting it up with FreeIPA was really smooth.)

**Comment by alexpdp7** [comment]
BTW, if someone comes across this question, the `podTemplate` recipe to inject a keytab is:

```
      apiVersion: k8s.keycloak.org/v2alpha1
      kind: Keycloak
      metadata:
        name: keycloak
        namespace: keycloak
      spec:
        instances: 1
        serverConfiguration:
          - name: db
            value: postgres
          - name: db-url
            value: "{{ keycloak_database_url }}"
        hostname: "{{ keycloak_domain }}"
        tlsSecret: tls
        disableDefaultIngress: true
        unsupported:
          podTemplate:
            spec:
              containers:
                - volumeMounts:
                    - name: keytab-volume
                      mountPath: /keytab
              volumes:
                - name: keytab-volume
                  secret:
                    secretName: keycloak-keytab
```

, with  a secret created by:

```
$ kubectl create secret generic -n keycloak keycloak-keytab --from-file=keytab=<<keytab file>>
```
