### ISSUE TITLE
Add a name to the keycloak port in the service

### ISSUE THREAD

**Issue by ctron** [keycloak/keycloak#12593]
### Description

Currently the keycloak service doesn't have a name for the port. I would expect the port to be named.

### Motivation

When referencing the keycloak port, (e.g. using ingress) it might not be important what service the port runs on. So not having a name, which is stable over different deployment variants (like HTTP and HTTPS), make this much more difficult, as it always need to be aligned with what the keycloak operator generates.

Having a stable name would make this much easier.

Additionally, it might also make sense to use a named port on the container itself.

### Details

Like so:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: MyApp
  ports:
    - name: http # <1>
      protocol: TCP
      port: 80
      targetPort: 9376
```
<1> Name
