### ISSUE TITLE
Refused to display 'https://keycloak.public.url/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

### ISSUE THREAD

**Issue by mazenaissa** [keycloak/keycloak#12695]
### Describe the bug

I've got a blank page after accessing the admin console, because the request to https://keycloak.public.url/keycloak/realms/master/protocol/openid-connect/3p-cookies/step1.html?version=ogvyw was blocked due to X-FRAME-OPTIONS set to SAMEORIGIN, you'll find below my configuration
Dockerfile:
```
FROM quay.io/keycloak/keycloak:18.0.1 as builder

RUN /opt/keycloak/bin/kc.sh build --http-relative-path=/keycloak  --db=postgres --cache-stack=kubernetes --health-enabled=true --metrics-enabled=true

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]
```
Kubernetes Configuration:
```
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: keycloak-upgrade
  name: keycloak-upgrade-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: keycloak-upgrade

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: keycloak-upgrade
  name: keycloak-upgrade 
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: keycloak-upgrade  
  template:
    metadata:
      annotations:
        prometheus.io/path: /keycloak/metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      labels:
        app: keycloak-upgrade
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - keycloak-upgrade
            topologyKey: "kubernetes.io/hostname"
          - labelSelector:
              matchLabels:
                app.kubernetes.io/instance: ingress-nginx
            topologyKey: kubernetes.io/hostname
            namespaces:
            - ingress-nginx
      containers:
        - name: keycloak-upgrade
          image: xxxxxxxxxxxxxxxxxxxxxx
          ports:
            - name: http
              containerPort: 8080
          env:
          - name: KEYCLOAK_ADMIN
            value: 'xxxxx'
          - name: KEYCLOAK_ADMIN_PASSWORD
            value: 'xxxx'
          - name: KC_PROXY
            value: 'edge'
          - name: KC_HOSTNAME_STRICT_HTTPS
            value: 'false'
          - name: KC_HOSTNAME
            value: "keycloak.public.url"
          - name: KC_HOSTNAME_ADMIN
            value: "console.keycloak.internal"
          - name: KEYCLOAK_LOG_LEVEL
            value: 'ALL'
          - name: KC_DB_URL_HOST
            value: 'xxxxx'
          - name: KC_DB_URL_PORT
            value: 'xxxxx'
          - name: KC_DB_URL_DATABASE
            value: 'xxxxx'
          - name: KC_DB_USERNAME
            value: 'xxxxx'
          - name: KC_DB_SCHEMA
            value: 'xxxxx'
          - name: KC_DB_PASSWORD
            value: 'xxxxx'
          - name: JGROUPS_DISCOVERY_PROTOCOL
            value: 'dns.DNS_PING'
          - name: JAVA_OPTS
            value: -Djgroups.dns.query=keycloak-upgrade.keycloak-upgrade.svc.cluster.local
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
            httpGet:
                path: /keycloak/health/ready
                port: 8080
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 1
              memory: 1Gi

      priorityClassName: critical-pods  
---

apiVersion: v1
kind: Service
metadata:
  namespace: keycloak-upgrade
  name: keycloak-upgrade
  labels:
    app: keycloak-upgrade
spec:
  clusterIP: None
  selector:
    app: keycloak-upgrade
  ports:
    - name: http
      port: 8080
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: 16k
    nginx.ingress.kubernetes.io/proxy-buffers-number: '4'
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: 32k
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.org/server-snippets: |
      location /keycloak {
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-Port $mapped_server_port;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
  labels:
    app: keycloak-upgrade-ingress
    argocd.argoproj.io/instance: nginx-ingress-resources
    ingressClass: nginx-tools
  name: keycloak-upgrade-tools-ingress
  namespace: keycloak-upgrade
spec:
  ingressClassName: nginx-tools
  rules:
    - http:
        paths:
          - backend:
              service:
                name: keycloak-upgrade
                port:
                  number: 8080
            path: /keycloak
            pathType: ImplementationSpecific
```

### Version

18.0.1

**Comment by pedroigor** [comment]
Thanks for the details, I'll try to check what might be happening.

**Comment by mazenaissa** [comment]
Another thing, with the that configuration the endpoint .well-known/openid-configuration/ is returning some values with keycloak.public.url and others with console.keycloak.internal.

**Comment by mazenaissa** [comment]
FYI, the ingress configured above is the one that will expose keycloak on the admin host : console.keycloak.internal

**Comment by pedroigor** [comment]
@mazenaissa I did some tests here and I could not reproduce the problem.

I've created two ingress as follows:

```
kind: Ingress
metadata:
  name: keycloak
  labels:
    service: keycloak
    layer: security
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "KC_SC"
    nginx.ingress.kubernetes.io/session-cookie-secure: "true"
    nginx.ingress.kubernetes.io/session-cookie-change-on-failure: "false"
    nginx.ingress.kubernetes.io/affinity-mode: "balanced"
spec:
  rules:
    - host: keycloak.apps.munerasoft.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: keycloak
                port: 
                  number: 8080
---
kind: Ingress
metadata:
  name: keycloak-admin
  labels:
    service: keycloak
    layer: security
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "KC_SC"
    nginx.ingress.kubernetes.io/session-cookie-secure: "true"
    nginx.ingress.kubernetes.io/session-cookie-change-on-failure: "false"
    nginx.ingress.kubernetes.io/affinity-mode: "balanced"
spec:
  rules:
    - host: keycloak-admin.apps.munerasoft.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: keycloak
                port: 
                  number: 8080
```

The only way I can get a blank page is if I'm using self-signed certs and the certs are not yet "trusted" by the browser.
