### ISSUE TITLE
Can't see the admin console

### ISSUE THREAD

**Issue by kambei** [keycloak/keycloak#12733]
### Describe the bug

I'm using a Dockerfile for create a custom image of Keycloak as follows:
```
FROM quay.io/keycloak/keycloak:18.0.2 as builder

ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_DB=postgres
# Install custom providers
RUN curl -sL https://github.com/aerogear/keycloak-metrics-spi/releases/download/2.5.3/keycloak-metrics-spi-2.5.3.jar -o /opt/keycloak/providers/keycloak-metrics-spi-2.5.3.jar
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:18.0.2
COPY --from=builder /opt/keycloak/ /opt/keycloak/
WORKDIR /opt/keycloak
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]
```

and whit this docker-compose I am able to run Keycloak:
```
version: "3.9"
services:

  keycloak_db:
    image: postgres
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=$DB_NAME
      - IGNORE_INIT_HOOK_LOCKFILE=true
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - ${DB_EXTERNAL_PORT:-15432}:5432

  keycloak:
    container_name: keycloak
    # image: quay.io/keycloak/keycloak:18.0.1
    image: keycloak
    ports:
      - "${KEYCLOAK_EXTERNAL_PORT:-18180}:8080"
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL_HOST=$DB_HOST
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=$DB_NAME
      - KC_DB_SCHEMA=$KEYCLOAK_SCHEMA
      - KC_DB_USERNAME=$DB_USER
      - KC_DB_PASSWORD=$DB_PASS
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME=localhost
      - KC_HOSTNAME_ADMIN=localhost
      - KC_HOSTNAME_PORT=80
      - KC_HOSTNAME_STRICT_BACKCHANNEL=true
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_PROXY=edge
      - KC_PROXY_ADDRESS_FORWARDING=true
      - KC_KEYCLOAK_FRONTEND_URL=http://localhost:18180/
      - KC_KEYCLOAK_URL=http://localhost:18180/
      # - KC_LOG_LEVEL=debug
    depends_on:
      - keycloak_db
```

I can see the Keycloak homepage:
[![enter image description here][1]][1]

But when I try to go to the admnistration console I see a blank page:
[![enter image description here][2]][2]

And if I use KC_FEATURES=admin2 as further environment variable I can see something, but still not the admin console:

[![enter image description here][3]][3]

  [1]: https://i.stack.imgur.com/ruwBq.png
  [2]: https://i.stack.imgur.com/eIiG4.png
  [3]: https://i.stack.imgur.com/KHp85.png

### Version

18.0.2

### Expected behavior

See the admin console

### Actual behavior

Can't see the admin console

**Comment by kambei** [comment]
If I use `ENV KC_FEATURES=token-exchange` in Dockerfile for the builder
I can see the login page:
![Screenshot from 2022-06-25 19-17-33](https://user-images.githubusercontent.com/10435317/175784217-dc9d5e63-661b-4ca0-a99a-e4a865b958c1.png)

But, after the login, always a blank page:
![Screenshot from 2022-06-25 19-18-17](https://user-images.githubusercontent.com/10435317/175784227-90b1f315-f0c9-496b-82e6-f683225703fb.png)

**Comment by kambei** [comment]
With version 18.0.1-legacy everything works fine and I don't have this issue.

**Comment by Edelbitter** [comment]
I have pretty much the same issue with a "bare metal" installation on a windows server. 
I'm not using TLS at all for now and keycloak can only be reached locally. 
So my admin console should be under 
http://localhost:8080/admin/master/console/
but the request to "step1.html?version=zzct6" which always fails tries to use https with port 8443 anyway, which I find curious

![grafik](https://user-images.githubusercontent.com/17107746/175989161-71f58dff-06ff-4068-84f8-6aa90b53fe96.png)

**Comment by kambei** [comment]
@abstractj I even tried
```

**Comment by approached** [comment]
You are using parameter that no longer exists:
```
      - KC_PROXY_ADDRESS_FORWARDING=true
      - KC_KEYCLOAK_FRONTEND_URL=http://localhost:18180/
      - KC_KEYCLOAK_URL=http://localhost:18180/
  ```

In development mode you can use keycloak with start-dev.
DEV Example: https://github.com/approached/docker-services/blob/master/keycloak/docker-compose.yml#L12

For production you need SSL certs or a reverse proxy that makes this job.
It's important to set correct hostname.

Example (with reverse proxy traefik): 
PROD Example: https://github.com/approached/docker-services/blob/master/keycloak/docker-compose-advanced.yml

**Comment by abstractj** [comment]
@kambei could you please check the comments from @approached ?

**Comment by kambei** [comment]
@abstractj @approached in prod environment I have Nginx as reverse proxy:
```
server {
        listen 443 ssl;
	listen [::]:443 ssl;
        server_name mydomain.com;
        ssl_certificate /etc/nginx/ssl/cert.pem;
        ssl_certificate_key /etc/nginx/ssl/privkey.pem;

        location / {
	    proxy_http_version 1.1;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	    proxy_pass http://keycloak:8080/;
        }
}
```
but still a blank page...

**Comment by lucasscheepers** [comment]
I also have the same issue as @kambei is experiencing. We're using [this helm chart](https://artifacthub.io/packages/helm/bitnami/keycloak) to deploy Keycloak on a Kubernetes platform (on-premise). The helm chart we're using is version 9.3.6.

When I inspect the blank page and refresh the page I see it does an `http` call instead of `https` we're using.

**Comment by approached** [comment]
@kambei 
You forget one header **X-Forwarded-Proto**:
```

    proxy_set_header X-Forwarded-For $proxy_protocol_addr; # To forward the original client's IP address 
    proxy_set_header X-Forwarded-Proto $scheme; # to forward the  original protocol (HTTP or HTTPS)
    proxy_set_header Host $host; # to forward the original host requested by the client
```

**Comment by kambei** [comment]
@approached in dev environment
with Nginx config:
```
events {
}
http {
  server {
    listen 80;  
    
    proxy_set_header X-Forwarded-For $proxy_protocol_addr; # To forward the original client's IP address 
    proxy_set_header X-Forwarded-Proto $scheme; # to forward the  original protocol (HTTP or HTTPS)
    proxy_set_header Host $host; # to forward the original host requested by the client
    
    # location / {  
    #   root   /data/www; 
    #   try_files $uri $uri/ /index.html;      #to support in app routing in SPA
    # } 
    location / {
      proxy_pass http://keycloak:8080;
    }
  }
}
```

and the docker-compose:
```
version: "3.9"
services:

  keycloak_db:
    image: postgres
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=$DB_NAME
      - IGNORE_INIT_HOOK_LOCKFILE=true
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - ${DB_EXTERNAL_PORT:-15432}:5432

  keycloak:
    container_name: keycloak
    # image: quay.io/keycloak/keycloak:18.0.2
    image: keycloak
    ports:
      - "${KEYCLOAK_EXTERNAL_PORT:-18080}:8080"
    # volumes:
    #   - ./keycloak-provider:/opt/jboss/keycloak/standalone/deployments/:rw
    #   - ./fwc_theme:/opt/jboss/keycloak/themes/fwc_theme/:rw
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL_HOST=$DB_HOST
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=$DB_NAME
      - KC_DB_SCHEMA=$KEYCLOAK_SCHEMA
      - KC_DB_USERNAME=$DB_USER
      - KC_DB_PASSWORD=$DB_PASS
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME=localhost
      # - KC_HOSTNAME_ADMIN=localhost
      # - KC_HOSTNAME_PORT=80
      # - KC_HOSTNAME_STRICT_BACKCHANNEL=true
      # - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_PROXY=edge
      - KC_PROXY_ADDRESS_FORWARDING=true
      # - KC_KEYCLOAK_FRONTEND_URL=http://localhost/
      # - KC_KEYCLOAK_URL=http://localhost/
      - KC_FEATURES=admin2
      # - KC_LOG_LEVEL=debug
    depends_on:
      - keycloak_db

  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
```
now I have a 500 Server Error response:
![Istantanea_2022-07-07_13-54-10](https://user-images.githubusercontent.com/10435317/177767297-88ec3205-8915-4864-b337-0367b2250e59.png)

**Comment by approached** [comment]
You trying to communicate via http. In the screenshot i am seeing request url is http://localhost/.... .
You mixing http and https to keycloak.

Maybe you can manual emulate via nginx config https:
```
proxy_set_header X-Forwarded-Proto https;
```

**Comment by kambei** [comment]
@approached for my testing purpouse I communicating only via http,
As I wrote for the Nginx config in the last comment.

Perhaps I have created confusion:
In prod environment I using only https via Nginx
In dev environment, for testing, I using only http for Nginx.

**Comment by kambei** [comment]
@approached @abstractj 
with these docker-compose:
```
version: "3.9"
services:

  keycloak_db:
    image: postgres
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=$DB_NAME
      - IGNORE_INIT_HOOK_LOCKFILE=true
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - ${DB_EXTERNAL_PORT:-15432}:5432

  keycloak:
    container_name: keycloak
    # image: quay.io/keycloak/keycloak:18.0.2
    image: keycloak
    ports:
      - "${KEYCLOAK_EXTERNAL_PORT:-18080}:8080"
    # volumes:
    #   - ./keycloak-provider:/opt/jboss/keycloak/standalone/deployments/:rw
    #   - ./fwc_theme:/opt/jboss/keycloak/themes/fwc_theme/:rw
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL_HOST=$DB_HOST
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=$DB_NAME
      - KC_DB_SCHEMA=$KEYCLOAK_SCHEMA
      - KC_DB_USERNAME=$DB_USER
      - KC_DB_PASSWORD=$DB_PASS
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME=keycloak.test
      # - KC_HOSTNAME_ADMIN=localhost
      # - KC_HOSTNAME_PORT=80
      # - KC_HOSTNAME_STRICT_BACKCHANNEL=true
      # - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_PROXY=edge
      # - KC_PROXY_ADDRESS_FORWARDING=true
      # - KC_KEYCLOAK_FRONTEND_URL=http://localhost/
      # - KC_KEYCLOAK_URL=http://localhost/
      - KC_FEATURES=admin2
      # - KC_LOG_LEVEL=debug
    depends_on:
      - keycloak_db

  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs/:/etc/nginx/certs/:ro
    ports:
      - 80:80
      - 443:443
```

and this Nginx conf:
```
events {
}
http {
  server {

    server_name keycloak.test;
    listen 443 ssl;
    ssl_certificate /etc/nginx/certs/local.crt;
    ssl_certificate_key /etc/nginx/certs/local.key;
    
    proxy_http_version 1.1;

    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Server $host;
    proxy_set_header X-Forwarded-For $proxy_protocol_addr; # To forward the original client's IP address 
    proxy_set_header X-Forwarded-Proto $scheme; # to forward the  original protocol (HTTP or HTTPS)
    proxy_set_header Host $host; # to forward the original host requested by the client
    
    # location / {  
    #   root   /data/www; 
    #   try_files $uri $uri/ /index.html;      #to support in app routing in SPA
    # } 
    location / {
      proxy_pass http://keycloak:8080;
    }
  }
}
```

everything works fine and I am able to see the admin console.

I assume that the administration console no longer works under http. Correct?
