### ISSUE TITLE
Admin console infinite redirect loop before password prompt

### ISSUE THREAD

**Issue by marekful** [keycloak/keycloak#12979]
### Describe the bug

Keycloak is repeatedly getting into above dead-end from a perfectly working state of configuration in a peculiar way.

I acknowledge that, strictly speaking, the issue may or may not be related to Keycloak, e.g. source code.

### Version

18.0.2, nightly

### Expected behavior

I'm buying 🍻 🍻 🍻 when you tell me how to fix this?

### Actual behavior

I've had a working configuration based on 18.0.2 quay.io image and docker-compose with three clients and three different kinds of client configurations (openid-connect public, openid-connect confidential, saml), running Keycloak behind Nginx. This is all wonderful, thanks a bunch!

The first time I encountered the issue was seemingly out of the blue. Not much before though I performed a forced reboot on the micro instance it was being ran on. This may or may not be related to the persistence of the issue.

**There is no apparent or intended change to Keycloak or Nginx configuration, nor to the OS** when the erroneous behaviour begins. Once in this state, I found no way to get out trying the following
- remove contents of all data mounts specified in the compose file 
- remove and  purge container and image
- move the configuration within the file system (e.g. somewhere else from /opt/keycloak) 
- change exposed port
- change to nightly image
- access the console in different browsers (e.g. an isolated chrome instance running with initially empty `--user-data-dir`)
- any combination of the above

**I did, however, eventually get out of the dead-end when I ran Keycloak on another host** (and updated Nginx proxy_pass accordingly)

I forgot to change back from nightly to 18.0.2 when copied over the config to the new host. I imported the realm export and all seemed fine again. **Until I changed back `nightly` to `18.0.2` in the compose file.** At that point, just with this change in itself, nothing else whatsoever, the issue began again right after pulling and running the image the first time. I find no way out of it again. I'm running out of hosts :| 

At this point I refuse to believe Keycloak or Nginx configuration (e.g. how cookies are forwarded or not) has anything to do with this since the setup did work the expected way with the configuration.

## Error info

**Steps to reproduce:** Unknown

**Request sequence** in Chrome dev tools

```html
Request URL: https://auth.example.com/admin/
Status Code: 302 Found
Location: https://auth.example.com/admin/master/console/

----

[js css assets load]

----

Request URL: https://auth.example.com/admin/master/console/config
Status Code: 200 OK

----

Request URL: https://auth.example.com/realms/master/protocol/openid-connect/3p-cookies/step1.html?version=4kwkt
Status Code: 200 OK
Response: <!DOCTYPE html>
<html>
<body>
<script>
    document.cookie = "KEYCLOAK_3P_COOKIE_SAMESITE=supported; max-age=60; samesite=none; secure"
    document.cookie = "KEYCLOAK_3P_COOKIE=supported; max-age=60"
    window.location = "step2.html"
</script>
</body>
</html>

----

Request URL: https://auth.example.com/realms/master/protocol/openid-connect/3p-cookies/step2.html
Cookie: KEYCLOAK_3P_COOKIE_SAMESITE=supported; KEYCLOAK_3P_COOKIE=supported
Status Code: 200 OK
<!DOCTYPE html>
<html>
<body>
<script>
    if (document.cookie.indexOf("KEYCLOAK_3P_COOKIE") !== -1) {
        document.cookie = "KEYCLOAK_3P_COOKIE_SAMESITE=; expires=Thu, 01 Jan 1970 00:00:00 GMT; secure"
        document.cookie = "KEYCLOAK_3P_COOKIE=; expires=Thu, 01 Jan 1970 00:00:00 GMT"
        window.parent.postMessage("supported", "*")
    }
    else {
        window.parent.postMessage("unsupported", "*")
    }
</script>
</body>
</html>

----

Request URL: https://auth.example.com/realms/master/protocol/openid-connect/auth?client_id=security-admin-console&redirect_uri=https%3A%2F%2Fauth.example.com%2Fadmin%2Fmaster%2Fconsole%2F&state=4c61ed25-af09-4dee-8a9c-2cc1490187d3&response_mode=fragment&response_type=code&scope=openid&nonce=9ca9330b-519a-433e-9355-63009d780760
Status Code: 302 Found
Location: https://auth.example.com/admin/master/console/#error=invalid_request&error_description=Missing+parameter%3A+code_challenge_method&state=4c61ed25-af09-4dee-8a9c-2cc1490187d3

```

and back to the beginning, however, during the next sequence, after step2.html, there is

```html
Request URL: https://auth.example.com/realms/master/protocol/openid-connect/login-status-iframe.html?version=4kwkt
Status Code: 200 OK
```

instead of the `/realms/master/protocol/openid-connect/auth?client_id=...` request. **Then these two sequences keep repeating one after the other**.

* Where I wrote no `Cookie: ...` there were none.

**Docker log**
```
keycloak_1  | 2022-07-09 10:35:06,573 INFO  [org.keycloak.protocol.oidc.endpoints.AuthorizationEndpointChecker] (executor-thread-4) PKCE enforced Client without code challenge method.
keycloak_1  | 2022-07-09 10:35:06,578 WARN  [org.keycloak.events] (executor-thread-4) type=LOGIN_ERROR, realmId=06c60a9f-1317-46dd-a584-bc5193a4e114, clientId=security-admin-console, userId=null, ipAddress=86.171.178.140, error=invalid_request, response_type=code, redirect_uri=https://auth.example.com/admin/master/console/, response_mode=fragment
```

## Config

**Keycloak**

`docker-compose.yml`

```yaml
version: "3.8"

networks:
    keycloak:
        ipam:
            config:
            - subnet: 10.0.1.0/24

services:

    mariadb:
        image: mariadb:latest
        cpuset: ${DB_CPUSET:-1}
        mem_limit: ${DB_MEMLIMIT:-500m}
        networks:
            - keycloak
        volumes:
            - /opt/keycloak/db/mariadb:/var/lib/mysql
            - /opt/keycloak/db/data:/opt/keycloak/data
        environment:
            MYSQL_ROOT_PASSWORD: <password>
            MYSQL_DATABASE: keycloak
            MYSQL_USER: keycloak
            MYSQL_PASSWORD: keycloak
            MYSQL_INITDB_SKIP_TZINFO: 1
        ports:
            - "3306:3306"

    keycloak:
        image: quay.io/keycloak/keycloak:18.0.2
        depends_on:
            - mariadb
        cpuset: ${KEYCLOAK_CPUSET:-1-1}
        mem_limit: ${KEYCLOAK_MEMLIMIT:-1g}
        networks:
            - keycloak
        volumes:
            - /opt/keycloak/keycloak.conf:/conf/keycloak.conf
            - /opt/keycloak/themes:/opt/keycloak/themes
        environment:
            MARIADB_HOSTS: mariadb:3306
            MARIADB_DATABASE: keycloak
            MARIADB_USER: keycloak
            MARIADB_PASSWORD: keycloak
            KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER:-admin}
            KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-<password>}
            # docker-compose syntax note: ${ENV_VAR:-<DEFAULT_VALUE>}
            JAVA_OPTS: ${KEYCLOAK_JVM_MEMORY:--Xms64m -Xmx1g -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m} -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true
            HTTP_MAX_CONNECTIONS: ${KEYCLOAK_HTTP_MAX_CONNECTIONS:-500}
            WORKER_IO_THREADS: ${KEYCLOAK_WORKER_IO_THREADS:-2}
            WORKER_TASK_MAX_THREADS: ${KEYCLOAK_WORKER_TASK_MAX_THREADS:-16}
            DS_MIN_POOL_SIZE: ${KEYCLOAK_DS_MIN_POOL_SIZE:-5}
            DS_MAX_POOL_SIZE: ${KEYCLOAK_DS_MAX_POOL_SIZE:-50}
            DS_POOL_PREFILL: "${KEYCLOAK_DS_POOL_PREFILL:-true}"
            DS_PS_CACHE_SIZE: ${KEYCLOAK_DS_PS_CACHE_SIZE:-50}
            JSTAT: "${KEYCLOAK_JSTAT:-false}"
        command: [ "--verbose", "-cf", "/conf/keycloak.conf", "start", "--proxy", "edge" ]
        ports:
            - "8085:8080"
            - "9991:9990"
```

`keycloak.conf`

```
hostname=auth.example.com
hostname-strict-https=false
```

**Nginx**

`default`

*main server section omitted*

```
server {
	listen 443;
	listen [::]:443;

	server_name auth.example.com;

	root /var/www/html;
	index index.html;

	location / {
                # proxy_pass http://127.0.0.1:8080;
                proxy_pass http://10.0.0.212:8085;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $http_host;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_redirect off;
	}
}
```

**Host 1**

```bash
$ uname -a
Linux ory 5.15.0-1011-oracle #15-Ubuntu SMP Fri Jun 10 12:18:08 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
$
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy
$
$ docker --version
Docker version 20.10.12, build 20.10.12-0ubuntu4
$
$ docker-compose --version
docker-compose version 1.29.2, build unknown
```

**Host 2**

```shell
$ uname -a
Linux instance-20211225-1924 5.13.0-1036-oracle #43~20.04.1-Ubuntu SMP Tue Jun 14 01:06:54 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
$
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
$
$ docker --version
Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1
$
$ docker-compose --version
docker-compose version 1.25.0, build unknown
```

### How to Reproduce?

Unknown as of yet

### Anything else?

I don't necessarily expect this to be accepted as a bug, merely seeking some guidance on how one might be able to fix or avoid this behaviour. 

Most importantly, it would be brilliant to understand exactly how this is happening.
