### ISSUE TITLE
Admin page redirect is with wrong port when using docker

### ISSUE THREAD

**Issue by mspark** [keycloak/keycloak#12974]
### Describe the bug

Admin panel is not accessable behind reverse proxy. The application points to the wrong admin URL.

The docker container is configured to forward 8090:8080. This is behind areverse proxy which terminates SSL. It redirects from https://example.com/auth -> http://localhost:8090

Now, even with KC_HOSTNAME_ADMIN=example.com, KC_HOSTNAME_PORT=443 and KC_HOSTNAME=example.com configured, the admin page redirects to https://example.com:8090/admin instead of the wished https://example.com/admin

### Version

18.0.2

### Expected behavior

The admin path /admin/ should be available via configured KC_HOSTNAME_ADMIN. 
Like example.com/admin 

### Actual behavior

The configured port is added to the admin path. Like example.com:8090/admin

### How to Reproduce?

1. Run docker container with port binding 8090:8080
2. Setup reverse proxy: example.com/auth -> localhost:8090/
3. Setup KC_HOSTNAME=example.com and KC_HOSTNAME_PATH=auth
4. Setup KC_HOSTNAME=example.com 
5. Go to example.com/auth - try to access the admin panel. It will point to example.com:8080/admin

Alternative:
1. run docker compose (see below)
2. setup apache2 with 
```
        ProxyPass /auth http://localhost:8090
        ProxyPassReverse /auth http://localhost:8090/
```

**Docker compose file:**
```
version: '3'

volumes:
  postgres_data:
      driver: local

services:
  keycloak:
      image: quay.io/keycloak/keycloak:18.0.2
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
        KC_PROXY: edge
        KC_HOSTNAME: example.com
        KC_HOSTNAME_PATH: auth
        KC_HOSTNAME_ADMIN: example.com
        KC_HOSTNAME_PORT: 443
      ports:
        - 8090:8080
     command: ["start"]
```

### Anything else?

Possible related Issue: https://github.com/keycloak/keycloak/issues/10626
