### ISSUE TITLE
Operator CRD status incompatible with kstatus

### ISSUE THREAD

**Issue by tim-jagenberg-piscada** [keycloak/keycloak#13074]
### Describe the bug

When using the new operator with Flux, the create Keycloak CRD instance never reaches ready status because the reported status deviates from the convention otherwise used: It uses yaml booleans instead of yaml strings.

(also see [kstatus](https://github.com/kubernetes-sigs/cli-utils/tree/master/pkg/kstatus)).

The conventions seems to be yaml strings:

Certificate from cert-manager:
```yaml
status:
  conditions:
    - lastTransitionTime: '2022-07-13T06:51:51Z'
      message: Certificate is up to date and has not expired
      observedGeneration: 1
      reason: Ready
      status: 'True'
      type: Ready
  notAfter: '2022-10-11T06:51:51Z'
  notBefore: '2022-07-13T06:51:51Z'
  renewalTime: '2022-09-11T06:51:51Z'
  revision: 1
```

SealedSecret from bitnami:
```
status:
  conditions:
    - lastTransitionTime: '2022-07-13T06:51:20Z'
      lastUpdateTime: '2022-07-13T06:51:20Z'
      status: 'True'
      type: Synced
```

### Version

18.0.2

### Expected behavior

The Keycloak CRD should report its status using yaml strings:

```yaml
status:
  conditions:
    - message: ''
      status: 'True'
      type: Ready
    - message: ''
      status: 'False'
      type: HasErrors
    - message: ''
      status: 'False'
      type: RollingUpdate
```

### Actual behavior

The Keycloak CRD reports its status using yaml booleans:

```yaml
status:
  conditions:
    - message: ''
      status: true
      type: Ready
    - message: ''
      status: false
      type: HasErrors
    - message: ''
      status: false
      type: RollingUpdate
```

### How to Reproduce?

Deploy Keycloak to kubernetes using the new operator and the Keycloak CRD.

**Comment by tim-jagenberg-piscada** [comment]
@andreaTP I suppose changing the status type from Boolean to String in the KeycloakStatusCondition would resolve this.

**Comment by andreaTP** [comment]
Hi @tim-jagenberg-piscada , this is actually a great suggestion, thanks a lot for filing this issue!
It should be an easy fix cc. @vmuzikar

**Comment by JWood48** [comment]
I'm stuck with this issue a the moment - since is is never considered ready dependent flux kustomizations never run - is there a workaround?

**Comment by thezanke** [comment]
Bump. I too am running into this issue when trying to use fluxcd with keycloak-operator. I'm guessing this is low priority because it works in openshift and this would only help people not using openshift?

**Comment by nick4fake** [comment]
Wow, just noticed this bug. This CRD is the only resource across our whole ecosystem (15+ operators, hundreds of services) which simply doesn't work with GitOps due to this issue. Is there any chance for this to be fixed? Chaning bools to strings doesn't sound like a difficult change.

@JWood48 So far we haven't found workaround, but this helps to at least save it in suspended mode:
1. Scale down keycloak operator to zero
2. Delete keycloak resource
3. Sync flux (initial sync is successful)
4. Suspend resource in flux, keep it suspended
5. Scale up keycloak operator

**Comment by andreaTP** [comment]
Cc. @shawkins

**Comment by shawkins** [comment]
Opened https://github.com/keycloak/keycloak/pull/21056 for this.

**Comment by lion7** [comment]
Just ran into this as well and found this issue. Great to see that it's being fixed soon 😄 
FWIW: these are the 'valid' values for conditions:
https://github.com/kubernetes/kubernetes/blob/master/pkg/apis/core/types.go#L2396-L2398

**Comment by twobiers** [comment]
I'm on 22.0.0 and getting the following error when flux is reconciling the kustomization. 
```
Keycloak/keycloak/keycloak dry-run failed: failed to create manager for existing fields: failed to convert new object (keycloak/keycloak; k8s.keycloak.org/v2alpha1, Kind=Keycloak) to smd typed: errors:	
           	             	                 	        	    	 .status.conditions[0].status: expected map, got &{True}                                                                                                                                                	
           	             	                 	        	    	 .status.conditions[1].status: expected map, got &{False}                                                                                                                                               	
           	             	                 	        	    	 .status.conditions[2].status: expected map, got &{False}   
```
I suggest from the `&{True}` that somehow a boolean literal is being read, however my current keycloak manifest returns strings as status:
```yaml
status:
  conditions:
  - message: ""
    observedGeneration: 28
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-07-11T17:39:03.279266537Z"
    message: ""
    observedGeneration: 28
    status: "False"
    type: HasErrors
  - message: ""
    observedGeneration: 28
    status: "False"
    type: RollingUpdate
  instances: 1
  observedGeneration: 28
  selector: app=keycloak,app.kubernetes.io/managed-by=keycloak-operator,app.kubernetes.io/instance=keycloak
  ```
  
  Any idea if my problem is related to this issue?
