### ISSUE TITLE
Reencrypt proxy ignored with new operator

### ISSUE THREAD

**Issue by tim-hutchinson** [keycloak/keycloak#13114]
### Describe the bug

We're deploying Keycloak 18.0.2 into Kubernetes with the new Quarkus operator, also version 18.0.2. Our deployment is in EKS, with an ALB as the ingress solution, with the ALB terminating TLS and re-encrypting traffic back to the keycloak pods. Per the [reverse proxy documentation](https://www.keycloak.org/server/reverseproxy) we aim to have `--proxy reencypt` used on our deployment, which we do by setting the value in the `serverConfiguration` block of the Keycloak CRD.

**Our Keycloak CRD**
```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  annotations:
  # ... removed
  labels:
  # ...removed
  name: keycloak
  namespace: keycloak
spec:
  disableDefaultIngress: true 
  hostname: keycloak.ourcompany.com
  instances: 1
  serverConfiguration:
  - name: log-console-output
    value: json
  - name: log-level
    value: INFO
  - name: proxy
    value: reencrypt
  - name: db
    value: postgres
  - name: db-url-host
    value: keycloakdb.ourcompany.com
  - name: db-url-database
    value: keycloak
  - name: db-username
    secret:
      key: username
      name: keycloak-database-secret
  - name: db-password
    secret:
      key: password
      name: keycloak-database-secret
  - name: hostname-admin
    value: keycloak-admin.ourcompany.com
  tlsSecret: keycloak-tls-secret
```

**Resulting Keycloak Deployment Env vars**
```yaml
spec:
  template:
    spec:
      containers:
      - args:
        - start
        env:
        - name: KC_HEALTH_ENABLED
          value: "true"
        - name: KC_CACHE
          value: ispn
        - name: KC_CACHE_STACK
          value: kubernetes
        - name: KC_LOG_CONSOLE_OUTPUT
          value: json
        - name: KC_LOG_LEVEL
          value: INFO
        - name: KC_PROXY
          value: reencrypt
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL_HOST
          value: keycloakdb.ourcompany.com
        - name: KC_DB_URL_DATABASE
          value: keycloak
        - name: KC_DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: keycloak-database-secret
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: keycloak-database-secret
        - name: KC_HOSTNAME_ADMIN
          value: keycloak-admin.ourcompany.com
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              key: username
              name: keycloak-initial-admin
              optional: false
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: keycloak-initial-admin
              optional: false
        - name: jgroups.dns.query
          value: keycloak-discovery.keycloak
        - name: KC_HOSTNAME
          value: keycloak.ourcompany.com
        - name: KC_HTTPS_CERTIFICATE_FILE
          value: /mnt/certificates/tls.crt
        - name: KC_HTTPS_CERTIFICATE_KEY_FILE
          value: /mnt/certificates/tls.key
        - name: KC_PROXY
          value: passthrough
```

As you can see, the `KC_PROXY` setting is set twice, and the one at the bottom is what takes priority in the pod. 

Digging through the history, it looks to me like https://github.com/keycloak/keycloak/pull/12021/files imposed logic that automatically sets up KC_PROXY, but that logic is faulty in not handling cases such as `reencrypt`, but also does not defer to the user-specified value in `serverConfiguration`, which I would expect.
 

### Version

18.0.2

### Expected behavior

Keycloak should be deployed with the specified `proxy` configuration, in this case `reencrypt`.

### Actual behavior

Keycloak is deployed with `KC_PROXY=passthrough`

### How to Reproduce?

Create an operator-backed deployment with
```yaml
serverConfiguration:
  - name: proxy
    value: reencrypt
```

### Anything else?

https://github.com/keycloak/keycloak/issues/11581 was the original issue that led to the PR creating the automated `KC_PROXY` behavior
