### ISSUE TITLE
Keycloak 18.0.2 - new Quarkus Operator - MySQL migration fails

### ISSUE THREAD

**Issue by ppaulis** [keycloak/keycloak#13269]
### Describe the bug

Hi,

I'm trying to install Keycloak 18.0.2 on my AKS Kubernetes Cluster using a MySQL database (using the new quarkus operator, vanilla installation, no OLM).

Connection to the database works fine and the migration of the DB starts. However, after more or less 90 tables, errors start appearing in the pod's log :

Reason: liquibase.exception.DatabaseException: Table 'keycloak.client_template_attributes' doesn't exist [Failed SQL: (1146) ALTER TABLE keycloak.CLIENT_TEMPLATE_ATTRIBUTES DROP FOREIGN KEY FK_CL_TEMPL_ATTR_TEMPL]

And I've seen other errors related to Foreign Keys etc.
I dialed it down to 1 instance to make sure, that it's not about multiple instances stepping on each other toes. But the result is the same.

### Version

18.0.2

### Expected behavior

When installing Keycloak with an external MySQL 8.0 database, the migrations should run without errors.

### Actual behavior

The migration fails with errors like:

Reason: liquibase.exception.DatabaseException: Table 'keycloak.client_template_attributes' doesn't exist [Failed SQL: (1146) ALTER TABLE keycloak.CLIENT_TEMPLATE_ATTRIBUTES DROP FOREIGN KEY FK_CL_TEMPL_ATTR_TEMPL]

### How to Reproduce?

1. kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/18.0.2/kubernetes/keycloaks.k8s.keycloak.org-v1.yml
2. kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/18.0.2/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
3. kubectl apply -n keycloak -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/18.0.2/kubernetes/kubernetes.yml
4. Create a certificate
5. Install Keycloak:
```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  instances: 1
  disableDefaultIngress: true
  serverConfiguration:
    - name: health-enabled
      value: "true"
    - name: db
      value: "mysql"
    - name: db-url-host
      value: "<DB host>"
    - name: db-username
      secret:
        name: keycloak-db-secret
        key: username
    - name: db-password
      secret:
        name: keycloak-db-secret
        key: password
  hostname: <hostname>
  tlsSecret: keycloak-cert
```
