### ISSUE TITLE
Installation error - You have an error in your SQL syntax

### ISSUE THREAD

**Issue by approached** [keycloak/keycloak#13389]
### Describe the bug

Cannot install current verison 19.0.0.

### Version

19.0.0

### Actual behavior

mls2_keycloak  | Changes detected in configuration. Updating the server image.
mls2_keycloak  | Updating the configuration and installing your custom providers, if any. Please wait.
mls2_keycloak  | 2022-07-28 09:36:50,564 INFO  [io.quarkus.deployment.QuarkusAugmentor] (main) Quarkus augmentation completed in 4199ms
mls2_keycloak  | Server configuration updated and persisted. Run the following command to review the configuration:
mls2_keycloak  |
mls2_keycloak  | 	kc.sh show-config
mls2_keycloak  |
mls2_keycloak  | Next time you run the server, just run:
mls2_keycloak  |
mls2_keycloak  | 	kc.sh start --optimized
mls2_keycloak  |
mls2_keycloak  | 2022-07-28 09:36:51,287 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: FrontEnd: login.mls2.test, Strict HTTPS: true, Path: <request>, Strict BackChannel: false, Admin: <request>, Port: -1, Proxied: true
mls2_keycloak  | 2022-07-28 09:36:51,857 INFO  [org.keycloak.common.crypto.CryptoIntegration] (main) Detected crypto provider: org.keycloak.crypto.def.DefaultCryptoProvider
mls2_keycloak  | 2022-07-28 09:36:52,823 INFO  [org.infinispan.server.core.transport.EPollAvailable] (keycloak-cache-init) ISPN005028: Native Epoll transport not available, using NIO instead: java.lang.UnsatisfiedLinkError: could not load a native library: netty_transport_native_epoll_aarch_64
mls2_keycloak  | 2022-07-28 09:36:52,872 WARN  [org.infinispan.PERSISTENCE] (keycloak-cache-init) ISPN000554: jboss-marshalling is deprecated and planned for removal
mls2_keycloak  | 2022-07-28 09:36:52,933 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
mls2_keycloak  | 2022-07-28 09:36:52,942 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
mls2_keycloak  | 2022-07-28 09:36:53,107 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.9.Final
mls2_keycloak  | 2022-07-28 09:36:53,146 WARN  [liquibase.database.DatabaseFactory] (main) Unknown database: MySQL
mls2_keycloak  | 2022-07-28 09:36:53,198 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
mls2_keycloak  | 2022-07-28 09:36:53,198 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
mls2_keycloak  | 2022-07-28 09:36:53,250 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
mls2_keycloak  | 2022-07-28 09:36:53,250 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20.00MB, but the OS only allocated 212.99KB
mls2_keycloak  | 2022-07-28 09:36:53,250 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
mls2_keycloak  | 2022-07-28 09:36:53,250 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25.00MB, but the OS only allocated 212.99KB
mls2_keycloak  | 2022-07-28 09:36:53,736 WARN  [liquibase.database.DatabaseFactory] (main) Unknown database: MySQL
mls2_keycloak  | 2022-07-28 09:36:53,853 WARN  [liquibase.database.DatabaseFactory] (main) Unknown database: MySQL
mls2_keycloak  | 2022-07-28 09:36:53,878 INFO  [org.keycloak.quarkus.runtime.storage.legacy.liquibase.QuarkusJpaUpdaterProvider] (main) Initializing database schema. Using changelog META-INF/jpa-changelog-master.xml
mls2_keycloak  | 2022-07-28 09:36:55,267 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) 8190c2b58c72-28538: no members discovered after 2004 ms: creating cluster as coordinator
mls2_keycloak  | 2022-07-28 09:36:55,273 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [8190c2b58c72-28538|0] (1) [8190c2b58c72-28538]
mls2_keycloak  | 2022-07-28 09:36:55,277 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `8190c2b58c72-28538`, physical addresses are `[172.22.0.6:51334]`
mls2_keycloak  | 2022-07-28 09:36:56,549 INFO  [org.infinispan.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
mls2_keycloak  | 2022-07-28 09:36:56,584 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
mls2_keycloak  | 2022-07-28 09:36:56,584 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to update database
mls2_keycloak  | 2022-07-28 09:36:56,584 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: liquibase.exception.MigrationFailedException: Migration failed for change set META-INF/jpa-changelog-1.2.0.Beta1.xml::1.2.0.Beta1::psilva@redhat.com:
mls2_keycloak  |      Reason: liquibase.exception.DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CLOB, NAME VARCHAR(255) NOT NULL)' at line 1 [Failed SQL: (1064) CREATE TABLE PROTOCOL_MAPPER_CONFIG (PROTOCOL_MAPPER_ID VARCHAR(36) NOT NULL, VALUE CLOB, NAME VARCHAR(255) NOT NULL)]
mls2_keycloak  | 2022-07-28 09:36:56,584 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Migration failed for change set META-INF/jpa-changelog-1.2.0.Beta1.xml::1.2.0.Beta1::psilva@redhat.com:
mls2_keycloak  |      Reason: liquibase.exception.DatabaseException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CLOB, NAME VARCHAR(255) NOT NULL)' at line 1 [Failed SQL: (1064) CREATE TABLE PROTOCOL_MAPPER_CONFIG (PROTOCOL_MAPPER_ID VARCHAR(36) NOT NULL, VALUE CLOB, NAME VARCHAR(255) NOT NULL)]
mls2_keycloak  | 2022-07-28 09:36:56,584 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CLOB, NAME VARCHAR(255) NOT NULL)' at line 1 [Failed SQL: (1064) CREATE TABLE PROTOCOL_MAPPER_CONFIG (PROTOCOL_MAPPER_ID VARCHAR(36) NOT NULL, VALUE CLOB, NAME VARCHAR(255) NOT NULL)]
mls2_keycloak  | 2022-07-28 09:36:56,584 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CLOB, NAME VARCHAR(255) NOT NULL)' at line 1
mls2_keycloak  | 2022-07-28 09:36:56,584 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.

### How to Reproduce?

```yml
# https://www.keycloak.org/getting-started/getting-started-docker
# https://www.keycloak.org/server/all-config

---
version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0.0
    container_name: mls2_keycloak
    # command: start --import-realm
    command: start
    volumes:
      - ./.docker-v2/keyloak/import:/opt/keycloak/data/import
      - ./.docker-v2/keyloak/themes:/opt/keycloak/themes
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_DB: mysql
      KC_DB_URL_HOST: mls2_mysql
      KC_DB_PORT: 3306
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: root
      KC_DB_PASSWORD:

      KC_HOSTNAME: login.mls2.test
      KC_HOSTNAME_STRICT: false
      KC_PROXY: edge
    labels:
      traefik.enable: true
      traefik.http.routers.keycloak.entrypoints: https
      traefik.http.routers.keycloak.rule: Host(`login.mls2.test`)
      traefik.http.routers.keycloak.tls: true
    networks:
      - traefik_proxy
      - backend

networks:
  traefik_proxy:
    name: traefik_proxy
  backend:
    name: backend
```

### Anything else?
In version 18.0.2 it work fine .

_No response_

**Comment by DGuhr** [comment]
Just confirmed with the following compose file: 
```
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:19.0.0
    command: ["start-dev"]
    environment:
      - KC_DB=mysql
      - KC_DB_URL_HOST=mysql
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak-secret
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=keycloak-secret
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume:
    driver: local
```

same error happens. will investigate more. cc @pedroigor @hmlnarik @stianst any hints are appreciated.
