### ISSUE TITLE
Upgrading from 18.0.2 to 19.0.0 postgres will not authenticate

### ISSUE THREAD

**Issue by ssill2** [keycloak/keycloak#13398]
### Describe the bug

This morning, in my local minikube environment, I tested upgrading from 18.0.2 to 19.0.0.   No matter what I try keycloak will not authenticate to postgresql using the same credentials that 18.0.2 was using.

I get the following.  reverting back to 18.0.2 works fine.  Postgres is latest 14.x.
```
2022-07-28 15:03:26,350 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "keycloak_admin"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:646)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:180)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
	at org.postgresql.Driver.makeConnection(Driver.java:400)
	at org.postgresql.Driver.connect(Driver.java:259)
	at java.sql/java.sql.DriverManager.
```

### Version

19.0.0

### Expected behavior

I didn't see anything in the migration guide regarding postgresql so I used the same settings and would expect it to authenticate just as 18.0.2 did/does

### Actual behavior

I get failed password authentication. 
My pg_hba.conf has had the same entry in there for months:

`host    keycloak             keycloak_admin             192.168.57.0/24            scram-sha-256`

I don't recall seeing anything in the migration guide regarding this, but I'll check again.

### How to Reproduce?

Take a working 18.0.2 keycloak deployment and upgrade to 19.0.0 by pointing at the 19.0.0 image but leaving everything else the same.

**Comment by ssill2** [comment]
I also tried changing the `scram-sha-256` to `md5` and `password` with no change in behavior.

**Comment by DGuhr** [comment]
that's weird, I get a postgres based keycloak 19 up and running with e.g. 

```
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:19.0.0
    command: ["start-dev"]
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak-secret
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak-secret
    ports:
      - 5432:5432
    volumes:
      - pg-volume:/var/lib/postgresql/data
volumes:
  pg-volume:
    driver: local
```

can you show more of your keycloak config, especially on how you set the db-url etc? the error message is pretty clear, but when you haven't changed a thing, tbh I have no clue what could cause this for now.

**Comment by ssill2** [comment]
yeah, give me a few minutes to put something together.   Since we use kubernetes I use a helm chart and deploy on minikube for testing before deploying the same helm chart and image on GKE for staging and prod.   So my values.yaml defines all the vars and the helm chart creates the configmap, secrets and deployment from that.  The process of stepping through this to post here might helm me uncover some stupid error lol

**Comment by ssill2** [comment]
So for my environment we use kubernetes.   So deployment involves a docker image, a helm chart and a values.yaml file.  So we add a few login screen themes in our deployed version so we build our own docker image from the base keycloak image and lay in the templates.

Our docker image Dockerfile looks like
```
FROM quay.io/keycloak/keycloak:19.0.0

ENV KC_METRICS_ENABLED=false
ENV KC_DB=postgres

COPY launcher.sh /opt/keycloak/bin
COPY --chown=keycloak keycloak_themes/ /opt/keycloak/themes/
RUN /opt/keycloak/bin/kc.sh build --db=postgres

# change these values to point to a running postgres instance
#ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]
ENTRYPOINT ["/opt/keycloak/bin/launcher.sh"]
```

The launcher.sh looks like
```
#!/bin/bash

KC_HOME=/opt/keycloak
KC=${KC_HOME}/bin/kc.sh
KC_CONFIG_FILE=${KC_HOME}/conf/keycloak.conf                                                                                                    

# base64 decode secret values
DBUSER=$(echo "${KC_DB_USER}" | base64 -d)
DBPASS=$(echo "${KC_DB_PASSWORD}" | base64 -d)
KEYCLOAK_ADMIN=$(echo "${KEYCLOAK_ADMIN}" | base64 -d)
KEYCLOAK_ADMIN_PASSWORD=$(echo "${KEYCLOAK_ADMIN_PASSWORD}" | base64 -d)

# write some lines to keycloak.conf
echo "db-url-host=${KC_DB_URL_HOST}" >> ${KC_CONFIG_FILE}
echo "db-url-port=${KC_DB_URL_PORT}" >> ${KC_CONFIG_FILE}
echo "db-url-database=${KC_DB_URL_DATABASE}" >> ${KC_CONFIG_FILE}
echo "db-username=${DBUSER}" >> ${KC_CONFIG_FILE}
echo "db-password=${DBPASS}" >> ${KC_CONFIG_FILE}
cat  ${KC_CONFIG_FILE}
# the rest of the settings are inherited using KC_* environment variables

# this must be set so that original requests to https:// urls will be properly redirected to https:// and not http://
export PROXY_ADDRESS_FORWARDING=true

if [ "${KC_DEV_MODE}" == "true" ] ; then
  ${KC} start-dev
else
  ${KC} start --optimized
fi
```

Vars referenced are provided by the kubernetes Deployment object.   I put that cat in there to verify that the credentials were indeed being supplied.
These are the lines being appended

```
db-url-host=192.168.57.35
db-url-port=5432
db-url-database=keycloak
db-username=keycloak_admin
db-password=Str0ngP@sswordH3r3
```
This same methodology works perfectly for my 18.0.2 based image

**Comment by ssill2** [comment]
it has worked for me since 17.0.0 when I first started using keycloak

**Comment by ssill2** [comment]
here's the deployment template for helm
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "keycloak-node"
  namespace: {{ .Values.namespace }}
  labels:
    name: keycloak
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: keycloak
  template:
    metadata:
      labels:
        name: keycloak
    spec:
      serviceAccountName: {{ include "keycloak.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: keycloak-cluster-node
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.keyCloakImage }}"
          imagePullPolicy: "{{ .Values.keyCloakImagePullPolicy }}"
          resources:
            requests:
              memory: "{{ .Values.requestMem }}"
              cpu: "{{ .Values.requestCpu }}"
          command: ["/opt/keycloak/bin/launcher.sh"]
          env:
            # define environment variables to expose variables from configmap
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: java.opts
            - name: K8S_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: k8s.namespace
            - name: KC_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: kc.hostname
            - name: KC_DB_URL_HOST
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: kc.db.host
            - name: KC_DB_URL_PORT
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: kc.db.port
            - name: KC_DB_URL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: kc.db.name
            - name: KC_CACHE_STACK
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: kc.cache.stack
            - name: KC_HOSTNAME_STRICT
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: kc.hostname.strict
            - name: KC_HTTP_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: kc.http.enabled
            - name: KC_PROXY
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: kc.proxy
            - name: KC_DEV_MODE
              valueFrom:
                configMapKeyRef:
                  name: keycloak-config
                  key: kc.dev.mode
            - name: KC_DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials-secret
                  key: username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials-secret
                  key: password
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-credentials-secret
                  key: username
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-credentials-secret
                  key: password
          ports:
            - name: jgroups
              containerPort: 7800
              protocol: TCP
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            - name: pingport
              containerPort: 8888
              protocol: TCP
            - name: jgroups2
              containerPort: 57600
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    name: keycloak
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    name: keycloak
```
