### ISSUE TITLE
Add more config options from Quarkus dist to Keycloak CR

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#13456]
The aim of this epic is to enhance the UX around configuring Quarkus distribution through the Operator. This will be achieved by adding more first-class citizen fields to the Keycloak CR.

This is an umbrella for the initial iteration covering only selected fields. For details, see the individual tasks.

Tasks included in this epic.
- [x] #14374
- [x] #14375
- [x] #14376
- [x] #14395
- [x] #14396
- [ ] #9784
- [ ] #14400
- [x] #14407
- [x] #14410
- [x] #14924

Example CR:
```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  db:
    vendor: postgres
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password 

  features:
    enabled:
      - docker
    disabled:
      - admin

  hostname:
    server: some-server-hostname
    admin: admin.some-serverhostname

  http:
    httpsPort: 443
    tlsSecret: my-super-secret
    truststoreFileSecret:
      name: my-secret-with-trustore
      key: my-key
    truststorePasswordSecret:
      name: my-secret-with-trustore
      key: my-key

  proxy:
    mode: edge

  ingress:
    enabled: false

  additionalOptions:
    - name: https-protocols
      value: TLSv1.2
```

The following configuration areas are out of scope:
* #14403
* #14402
* #14401

Supersedes: #12088
Related discussion: https://github.com/keycloak/keycloak/discussions/13682
