### ISSUE TITLE
⚠️ Basic keycloak deployment failing when using operator (vanilla k8s)

### ISSUE THREAD

**Issue by rustygreen** [keycloak/keycloak#13515]
### Describe the bug

When following the [Keycloak Operator Installation](https://www.keycloak.org/operator/installation) guide (using vanilla Kubernetes) and then the [Basic Keycloak Deployment](https://www.keycloak.org/operator/basic-deployment) guide, I get an error when the keycloak pod starts:

```txt
2022-08-03 15:12:07,527 DEBUG [io.quarkus.deployment.QuarkusAugmentor] (main) Beginning Quarkus augmentation

2022-08-03 15:12:07,863 TRACE [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Class quarkus.properties not found in parent first load from java.net.URLClassLoader@3406472c

2022-08-03 15:12:07,863 TRACE [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Class quarkus.properties not found in parent first load from java.net.URLClassLoader@3406472c

ERROR: Failed to run 'build' command.
ERROR: java.util.NoSuchElementException: No value present
ERROR: No value present
```

### Version

19.0.1

### Expected behavior

The Keycloak deployment/pod starts correctly

### Actual behavior

The pod fails on load:
![image](https://user-images.githubusercontent.com/1774477/182644501-bb95dd20-4052-47b9-818f-7501194d29a8.png)

### How to Reproduce?

Using a fresh cluster (k3s in my case):

From [Keycloak Operator Installation guide](https://www.keycloak.org/operator/installation):
```yaml
kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/19.0.1/kubernetes/keycloaks.k8s.keycloak.org-v1.yml
kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/19.0.1/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/19.0.1/kubernetes/kubernetes.yml
```

Create Postgres DB
```yaml
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-data
  labels:
    app: postgres
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: "YOUR_PASSWORD"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.4-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /mnt/postgresql/data # /var/lib/postgresql/data/db
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: postgres
```

Create secret for keycloak DB credentials:

```bash
kubectl create secret generic keycloak-db-secret --from-literal=username=admin --from-literal=password='YOUR_PASSWORD'
```

Apply keycloak manifest file based on [Keycloak Operator Installation guide](https://www.keycloak.org/operator/installation):
`kubectl apply -f ./cluster/keycloak/database.yaml`

```yaml
# keycloak.yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 1
  serverConfiguration:
    - name: db
      value: postgresdb
    - name: db-url-host
      value: postgres
    - name: db-username
      secret:
        name: keycloak-db-secret
        key: username
    - name: db-password
      secret:
        name: keycloak-db-secret
        key: password
  hostname: identity1.keycloak.org
  tlsSecret: YOUR_TLS_SECRET

```

The result will be a pod start failure of:

```txt
2022-08-03 15:12:07,527 DEBUG [io.quarkus.deployment.QuarkusAugmentor] (main) Beginning Quarkus augmentation

2022-08-03 15:12:07,863 TRACE [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Class quarkus.properties not found in parent first load from java.net.URLClassLoader@3406472c

2022-08-03 15:12:07,863 TRACE [io.quarkus.bootstrap.classloading.QuarkusClassLoader] (main) Class quarkus.properties not found in parent first load from java.net.URLClassLoader@3406472c

ERROR: Failed to run 'build' command.
ERROR: java.util.NoSuchElementException: No value present
ERROR: No value present
```

### Anything else?

I was able to get the deployment to work (using same configurations) using helm deployment.

**Comment by vmuzikar** [comment]
@rustygreen Thanks for reporting this, however it's not a bug. There's a typo in the db vendor, should be `postgres` not `postgresdb`:
```yaml
  serverConfiguration:
    - name: db
      value: postgres
```
Please see also the docs.

@pedroigor I see this as a candidate for enhancement. We should provide more meaningful error message in this case. WDYT? But perhaps it's something that's already on our radar? :)
