### ISSUE TITLE
Admin console with `--hostname-port 80` not reachable under port 80

### ISSUE THREAD

**Issue by BonaBeavis** [keycloak/keycloak#13519]
### Describe the bug

It took me some days to figure this out. I have Traefik as a reverse proxy and with port 80 as the outward facing port it is not possible to reach the admin console, with any other port (81) with an otherwise identical config it is possible to reach the admin console.

### Version

19.0.1

### Expected behavior

Navigating to `http://keycloak.localhost/admin/master/console/` open admin console.

### Actual behavior

Only a a spinner is shown.

### How to Reproduce?

Traefik static conf:
```bash
TRAEFIK_ENTRYPOINTS_WEB_ADDRESS=:80
TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS=:443
```
Traefik dynamic conf:
```yaml
http:
  routers:
    to_keycloak:
      rule: "HostRegexp(`keycloak.{host:.+}`)"
      service: keycloak

  services:
    keycloak:
      loadBalancer:
        servers:
          - url: "http://pod_keycloak:8080"
```

Keycloak conf:
```
start --hostname keycloak.localhost --proxy edge --hostname-port 80 --hostname-strict-https false --hostname-strict false
```

### Anything else?

I would guess the bug comes from the special handling of port 80, because it can be implicitly assumed, while when setting another port, the port is always explicitly part of the hostname.
