### ISSUE TITLE
Admin console "supported locales" dropdown doesn't show custom added language.

### ISSUE THREAD

**Issue by drsmile1001** [keycloak/keycloak#13876]
### Describe the bug

By following [Server Developer Guid](https://www.keycloak.org/docs/latest/server_development/#adding-a-language-to-a-realm), I added "zh-TW" (Traditional Chinese or 正體中文) to my custom theme.

The new language doesn't show up in dropdown menu.
![圖片](https://user-images.githubusercontent.com/11384864/185559264-f841832b-8cf9-49e9-848b-95115d29676b.png)

I add "zh-TW" by directly access `realm_supported_locales` table in database.
![圖片](https://user-images.githubusercontent.com/11384864/185558343-5c474f22-643a-423b-a8f8-19eb39783d1e.png)
 
And it come up in language selector.
![圖片](https://user-images.githubusercontent.com/11384864/185558628-40f4f277-ae0d-4a8f-b2f6-12784567b0e3.png)
![圖片](https://user-images.githubusercontent.com/11384864/185557752-58fa5629-f9fb-494e-a45e-4ec743dc9772.png)

### Version

19.0.1

### Expected behavior

Supported locales should show up custom add language.

### How to Reproduce?

I use docker to run keycloak.

```
keycloak                                  
├─ themes                                 
│  └─ mytheme                             
│     ├─ account                          
│     │  ├─ messages                      
│     │  │  ├─ messages_en.properties     
│     │  │  └─ messages_zh_TW.properties  
│     │  └─ theme.properties              
│     ├─ email                            
│     │  ├─ messages                      
│     │  │  └─ messages_zh_TW.properties  
│     │  └─ theme.properties              
│     └─ login                            
│        ├─ messages                      
│        │  ├─ messages_en.properties     
│        │  └─ messages_zh_TW.properties  
│        └─ theme.properties              
├─ docker-compose.yml                     
└─ dockerfile                             
```
* docker-compose.yml
binding `themes` to `/opt/keycloak/themes`
```yml
version: "3.2"

services:
  keycloak:
    container_name: keycloak
    image: keycloak:my
    build: .
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./themes
        target: /opt/keycloak/themes
    entrypoint:
      [
        "/opt/keycloak/bin/kc.sh",
        "start",
        "--spi-theme-static-max-age=-1",
        "--spi-theme-cache-themes=false",
        "--spi-theme-cache-templates=false",
      ]
```

* themes/mytheme/account/messages/messages_en.properties
* themes/mytheme/login/messages/messages_en.properties
```properties
# encoding: utf-8
locale_zh-TW=正體中文
```

### Anything else?

I also notice the "zh-CN" (Simplified Chinese or 简体中文) on "supported locales" dropdown shows "中文". Dose't match "中文简体" in origin resources properties.

https://github.com/keycloak/keycloak/blob/main/themes/src/main/resources/theme/base/account/messages/messages_en.properties

\u4e2d\u6587\u7b80\u4f53 is "中文简体"
```properties
locale_ca=Catal\u00e0
locale_cs=\u010Ce\u0161tina
locale_de=Deutsch
locale_en=English
locale_es=Espa\u00f1ol
locale_fr=Fran\u00e7ais
locale_hu=Magyar
locale_it=Italiano
locale_ja=\u65e5\u672c\u8a9e
locale_lt=Lietuvi\u0173
locale_nl=Nederlands
locale_no=Norsk
locale_pl=Polski
locale_pt-BR=Portugu\u00eas (Brasil)
locale_ru=\u0420\u0443\u0441\u0441\u043a\u0438\u0439
locale_sk=Sloven\u010dina
locale_sv=Svenska
locale_tr=T\u00FCrk\u00E7e
locale_zh-CN=\u4e2d\u6587\u7b80\u4f53
locale_fi=Suomi
```
