### ISSUE TITLE
ERROR: No suitable driver found for jdbc:postgresql://db:5432/keycloak?ssl=allow

### ISSUE THREAD

**Issue by mathias4github** [keycloak/keycloak#13965]
### Describe the bug

Hi Team,
we are struggling with starting version 19.

We always get:

```
ERROR: Failed to start server in (production) mode
identity_production_keycloak      | 2022-08-24 13:47:11,508 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
identity_production_keycloak      | 2022-08-24 13:47:11,508 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: No suitable driver found for jdbc:postgresql://db:5432/keycloak?ssl=allow
identity_production_keycloak      | 2022-08-24 13:47:11,509 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use 
```

any ideas?

### Version

19.0.1

### How to Reproduce?

```
cat build/keycloak/production/Dockerfile 
FROM quay.io/keycloak/keycloak:latest as builder

#ENV KC_HEALTH_ENABLED=true
#ENV KC_METRICS_ENABLED=true
#ENV KC_FEATURES=token-exchange
ENV KC_DB=postgres
# Install custom providers
#RUN curl -sL https://github.com/aerogear/keycloak-metrics-spi/releases/download/2.5.3/keycloak-metrics-spi-2.5.3.jar -o /opt/keycloak/providers/keycloak-metrics-spi-2.5.3.jar
RUN /opt/keycloak/bin/kc.sh build 

FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/ /opt/keycloak/
WORKDIR /opt/keycloak
# for demonstration purposes only, please make sure to use proper certificates in production instead
# RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
# change these values to point to a running postgres instance
# ENV KC_DB_URL=<DBURL>
# ENV KC_DB_USERNAME=<DBUSERNAME>
# ENV KC_DB_PASSWORD=<DBPASSWORD>
# ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]
```

Docker Compose file:
```
keycloak:
    container_name: identity_production_keycloak
    restart: unless-stopped
    build:
      context: ./build/keycloak/production/
      dockerfile: ./Dockerfile
    image: keycloak
    environment:
    - KEYCLOAK_ADMIN=${KC_USER}
    - KEYCLOAK_ADMIN_PASSWORD=${KC_PASSWORD}
    command:
    - --proxy=edge
    - --hostname-strict=false
    - --hostname=${DOMAIN}
    - --hostname-admin=${ADMIN_DOMAIN}
    - --db-url=jdbc:postgresql://db:5432/keycloak?ssl=allow
    - --db-username=${DB_USER}
    - --db-password=${DB_PASSWORD}
    - --http-enabled=true
    networks:
      - app
      - db
      - ldap


```
### Anything else?

an 18.0.2 the same file was still working
