### ISSUE TITLE
⚠️ Kubernetes Operator - Too big request header

### ISSUE THREAD

**Issue by rustygreen** [keycloak/keycloak#14047]
### Describe the bug

When deploying Keycloak using the [Keycloak Operator](https://www.keycloak.org/operator/installation#_vanilla_kubernetes_installation), adding a realm (with SSO identity provider) and basic client results in a `Too big request header` error message being returned from Keycloak.

![image](https://user-images.githubusercontent.com/1774477/186946401-93228b0a-3205-4db5-b472-ebf223ce684b.png)

![image](https://user-images.githubusercontent.com/1774477/186949237-b6f13e56-11c8-4d97-9d5c-b5673abc585d.png)

### Version

19.0.1

### Expected behavior

By default the "production" Keycloak instance created by the operator should support creating clients using standard Identity Providers (such as Azure/Office 365 for SSO).

If this is not the desired "default" behavior, then a configuration should be available to change the max header size. There is no documentation describing that this can be done using the operator/CRD.

### Actual behavior

Out-of-the-box production Keycloak cluster (using operator) is unusable with connected Identity Providers (such as MS Azure/Office 365).

### How to Reproduce?

1. Install the Kubenetes Operator following the [Keycloak Operator Installation guide](https://www.keycloak.org/operator/installation#_vanilla_kubernetes_installation) (using valnilla Kubernetes)
2. Create a Keycloak cluster using CRD, following the [Keycloak Operator Installation guide](https://www.keycloak.org/operator/installation#_vanilla_kubernetes_installation).
3. Create a new realm (ex: test)
4. Add an OIDC Identity Provider (in my case pointed at single tenant Office 365 for SSO)
5. Create a new client, for basic OIDC application authentication with standard flow (ex: dev-app)
![image](https://user-images.githubusercontent.com/1774477/186943706-80770618-d40e-48e1-bc5f-3c19e3f886a7.png)
6. Try to use the realm/client in an application (using the added OIDC Identity Provider for SSO)
7. Will result in `Too big request header` error
![image](https://user-images.githubusercontent.com/1774477/186946401-93228b0a-3205-4db5-b472-ebf223ce684b.png)

#### Pods
![image](https://user-images.githubusercontent.com/1774477/186946547-d835da3c-70ac-4dbb-b9e1-3dfb489b3e00.png)

### Services
![image](https://user-images.githubusercontent.com/1774477/186946619-ed23d098-9505-4992-904d-a4b79bc667b9.png)

### Ingress
Ingress Class: [ingress-nginx[(https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/)
![image](https://user-images.githubusercontent.com/1774477/186946700-b2791cc0-d8bd-4a35-897a-1ec034c93907.png)

Ingress Annotations:
```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: security
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-buffering: "off" # THIS IS OFF BY DEFAULT, BUT JUST MAKING SURE
```
