### ISSUE TITLE
Add transaction options to Keycloak CR

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#14375]
Mapped options:
* transaction-xa-enabled

Example CR:
```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  transaction:
    xa-enabled: false # boolean
...
```
