### ISSUE TITLE
Add features options to Keycloak CR

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#14376]
Mapped options:
* features
* features-disabled

Example CR:
```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  features:
    enabled: # list of strings
      - docker
    disabled:
      - admin
...
```
