### ISSUE TITLE
Add DB options to Keycloak CR

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#14374]
Mapped options:
* db
* db-password (as a Secret)
* db-username (as a Secret)
* db-pool-initial-size
* db-pool-max-size
* db-pool-min-size
* db-url
* db-url-database
* db-url-host
* db-url-port
* db-url-properties

CR structure:
```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  db:
    vendor: postgres
    usernameSecret: # plain text value not supported by the type
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
    url: jdbc:postgresql://db-postgres-service/keycloak
    urlDatabase: keycloak
    urlHost: db-postgres-service
    urlPort: 5432
    urlProperties: extrarg
    schema: some-schema
    poolInitialSize: 1 # integer
    poolMinSize: 1 # integer
    poolMaxSize: 3 # integer
```
