### ISSUE TITLE
Add HTTP options to Keycloak CR

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#14396]
Mapped options:
* http-port
* https-port
* http-enabled
* https-certificate-file
* https-certificate-key-file
* https-trust-store-file (separate issue: https://github.com/keycloak/keycloak/issues/9784)
* https-trust-store-password (separate issue: https://github.com/keycloak/keycloak/issues/9784)
* https-trust-store-type (separate issue: https://github.com/keycloak/keycloak/issues/9784)

Omitting for now for simplicity:
* http-host (probably doesn't make too much sense in K8s)
* http-relative-path
* https-cipher-suites
* https-protocols
* https-client-auth
* https-key-store-file
* https-key-store-password
* https-key-store-type

Removed/moved existing properties in the CR:
* tlsSecret (moved to http/tlsSecret)
* Remove the [`INSECURE-DISABLE` functionality](https://www.keycloak.org/operator/advanced-configuration#_disabling_required_cr_fields) to align with the distribution

CR structure:
```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  http:
    httpPort: 80 # integer; reflected by Ingress and Service
    httpsPort: 443 # integer; reflected by Ingress and Service
    tlsSecret: my-super-secret # mapped to https-certificate-file and https-certificate-key-file
...
```

**NOTE:** this is a breaking change and there will be no automated migration; make sure to mention it in release notes and migration guide.
