### ISSUE TITLE
Add hostname options to Keycloak CR

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#14395]
Mapped options:
* hostname
* hostname-admin
* hostname-port
* hostname-strict
* hostname-strict-backchannel
* hostname-url
* hostname-admin-url

Omitting for now for simplicity:
* hostname-path (superseded by hostname-url)

Removed/moved existing properties in the CR:
* hostname (moved under hostname/server)
* Remove the [`INSECURE-DISABLE` functionality](https://www.keycloak.org/operator/advanced-configuration#_disabling_required_cr_fields) to align with the distribution

CR structure:
```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  hostname:
    hostname: some-server-hostname # moved from spec/hostname; now optional; if set it has to be reflected by Ingress
    hostnameUrl: url
    admin: admin.some-serverhostname # not reflected by Ingress for now
    adminUrl: url
    port: 80 # integer; reflected by Ingress
    strict: false # boolean
    strictBackchannel: false # boolean
...
```

**NOTE:** this is a breaking change and there will be no automated migration; make sure to mention it in release notes and migration guide.
