### ISSUE TITLE
Refine Ingress settings in Keycloak CR

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#14407]
Add a new section dedicated to Ingress to support future non-breaking extension of this area.

CR structure:
```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  ingress:
    enabled: false # moved from spec/disableDefaultIngress; defaults to true
...
```

**NOTE:** this is a breaking change and there will be no automated migration; make sure to mention it in release notes and migration guide.
