### ISSUE TITLE
Add proxy options to Keycloak CR

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#14400]
Mapped options:
* proxy

Additional logic:
* When the default Ingress is enabled, proxy will be automatically pre-set to `passthrough`.

CR structure:
```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  proxy:
    mode: edge # enum
...
```
