### ISSUE TITLE
Cannot list client roles specified in authorization policy (UI bug in 19.0.1 and 19.0.2)

### ISSUE THREAD

**Issue by Romain7495** [keycloak/keycloak#14517]
### Describe the bug

When we create Confidential client, with authorization enabled, we can specify role that can acess a specific policy. The issue is that after the role is assigned to this policy, you cannot list it in the policy description. cf screenshot above

![Screenshot from 2022-09-21 10-03-48](https://user-images.githubusercontent.com/15386726/191451387-716596c6-d614-45d2-9257-111bd78e70f1.png)

Workaround is to describe the policy by api or in the `Authorization/Export` tab in the client. cf screenshot above

![Screenshot from 2022-09-21 10-04-43](https://user-images.githubusercontent.com/15386726/191451699-a823d134-1f19-48cc-b49b-d4505bcb735f.png)

### Version

19.0.2

### Expected behavior

Being able to list role in policy. cf screenshot above

![Screenshot from 2022-09-21 10-19-28](https://user-images.githubusercontent.com/15386726/191453423-d5b96343-9a69-42cc-8b0a-3044edb111e5.png)

### Actual behavior

Role listing in policy is broken. cf screenshot above

![Screenshot from 2022-09-21 11-44-47](https://user-images.githubusercontent.com/15386726/191472658-fbc87a05-3761-4750-8ec8-51cce22fa598.png)

### How to Reproduce?

Deploy keycloak with version `19.0.2`. cf `docker-compose.yml` but same in kubernetes

```
version: '3'

services:
  keycloak-db:
    image: postgres:14-alpine
    restart: on-failure
    volumes: 
      - db-data-keycloak-datastore:/var/lib/postgresql/data
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB:       keycloak
      POSTGRES_USER:     keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: "quay.io/keycloak/keycloak:19.0.2"
    container_name: keycloak
    restart: on-failure
    depends_on:
      - keycloak-db
    command: start-dev
    ports:
      - "8180:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      PROXY_ADRESS_FORWARDING: "true"
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: "sso.local.domain.com"
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge

volumes:
  db-data-keycloak-datastore:

networks:
  default:
    external: true
    name: local-net
```
