### ISSUE TITLE
Issue: Stuck on 'Loading the admin console'

### ISSUE THREAD

**Issue by ZinkNotTheMetal** [keycloak/keycloak#14586]
### Describe the bug

I am in the process of standing up a local instance of KeyCloak with docker and docker-compose.

Previously I have setup Keycloak with the [jboss image (jboss/keycloak:latest)](https://hub.docker.com/r/jboss/keycloak). But I am now trying to stand up with the quay image and the new runtime (quay.io/keycloak/keycloak:19.0.2)

Linked below is my docker-compose.yml and .env file as an example.

I have tried to search for similar issues and found the following:
* [Stack Overflow - 59361923](https://stackoverflow.com/questions/59361923/keycloak-admin-console-not-accessible)
* [Stack Overflow - 73259860](https://stackoverflow.com/questions/73259860/i-do-not-get-keycloak-working-in-docker-behind-traefik)
* [Keycloak GitHub Issue](https://github.com/keycloak/keycloak/issues/11083)

But none of these solutions are what I am trying to achieve. I am looking just to setup a non-proxied environment similar to the response [here](https://github.com/keycloak/keycloak/issues/11083#issuecomment-1088704957) in that same issue linked above.

### Version

19.0.2

### Expected behavior

Login screen renders so I am able to login with proper credentials

### Actual behavior

Stuck on the loading screen

![image](https://user-images.githubusercontent.com/6002111/192337082-7ea680a6-32fb-4df5-8cf2-1199334bd843.png)

### How to Reproduce?

Run
`docker-compose up -d`
Navigate to the port specified
`https://localhost:8080/admin`

Notice the failure to bring up the login screen

docker-compose.yml
```yml
version: "3.9"

services:
  postgres:
    image: postgres:14.5
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    networks:
      - local-keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    restart: unless-stopped
    command: start
    environment:
      PROXY_ADDRESS_FORWARDING: true
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      #KC_HOSTNAME: localhost
      KC_PROXY: none
      KC_METRICS_ENABLED: true
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: ${POSTGRESQL_USER}
      KC_DB_PASSWORD: ${POSTGRESQL_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - keycloak-postgres:/var/lib/postgresql/data
    networks:
      - local-keycloak
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  keycloak-postgres:

networks:
  local-keycloak:

```

.env (example)
```
POSTGRESQL_DB=keycloak
POSTGRESQL_USER=keycloak
POSTGRESQL_PASSWORD=k3ycl0ak!!
KEYCLOAK_ADMIN_USERNAME=admin
KEYCLOAK_ADMIN_PASSWORD=k3ycl0ak
```

**Comment by matumot** [comment]
I also experienced same problem (In my case,  I used keycloak with mysql DB).   It was OK for 19.0.1.  So I think some bugs were introcued between 19.0.1 and 19.0.2.

**Comment by ArminRadmueller** [comment]
Hi @ZinkNotTheMetal 
I had the same problem and was able to solve it with this entry in docker-compose.yml:
`entrypoint: /opt/keycloak/bin/kc.sh start --proxy edge --hostname-strict false`
It is not the smartest solution, but I have not found any other solution... :-)

**Comment by ZinkNotTheMetal** [comment]
Ammended docker-compose.yml
```yaml
version: "3.9"

services:
  postgres:
    image: postgres:14.5
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    networks:
      - local-keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    restart: unless-stopped
    entrypoint: /opt/keycloak/bin/kc.sh start --proxy edge --hostname-strict false
    environment:
      PROXY_ADDRESS_FORWARDING: true
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_PROXY: none
      KC_METRICS_ENABLED: true
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: ${POSTGRESQL_USER}
      KC_DB_PASSWORD: ${POSTGRESQL_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - keycloak-postgres:/var/lib/postgresql/data
    networks:
      - local-keycloak
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  keycloak-postgres:

networks:
  local-keycloak:
```

I'm still getting the spinning admin console issue

**Comment by Hollerweger** [comment]
you forgot the equals, should be --hostname-strict-https=false

**Comment by ZinkNotTheMetal** [comment]
@Hollerweger I have updated the command line like you specified and still stuck on the loading screen

new docker-compose.yml
```yml
version: "3.9"

services:
  postgres:
    image: postgres:14.5
    container_name: keycloak_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    networks:
      - local-keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.2
    container_name: keycloak
    restart: unless-stopped
    entrypoint: /opt/keycloak/bin/kc.sh start --proxy edge --hostname-strict=false
    environment:
      PROXY_ADDRESS_FORWARDING: true
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_PROXY: edge
      KC_METRICS_ENABLED: true
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: ${POSTGRESQL_USER}
      KC_DB_PASSWORD: ${POSTGRESQL_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - keycloak-postgres:/var/lib/postgresql/data
    networks:
      - local-keycloak
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  keycloak-postgres:

networks:
  local-keycloak:
```
