### ISSUE TITLE
HTTP Redirect 303 to wrong URL (in case port is not 80) when trailing slash is not added

### ISSUE THREAD

**Issue by ummarbhutta** [keycloak/keycloak#14581]
### Describe the bug

I have configured Keycloak behind reverse proxy (Nginx) at subpath `/auth`. If I run my following setup on port 80 (Nginx) everything works fine, but using a different port cause an invalid `303 redirect` if trailing slash is not used and always redirect to URL with port 80. If I add a trailing slash it works fine.

### Version

19.0.2

### Expected behavior

When I access admin console with `http://localhost:8080/auth` It should open admin console. 

### Actual behavior

If I access `http://localhost:8080/auth`, It is redirecting to `http://localhost/auth/` with `303 See Other` header, if I access the URL `http://localhost:8080/auth/` it doesn't redirects and works fine.

#### Nginx reverse proxy configuration and `Dockerfile`

- Create a directory and create two files in it
**default.conf**
```
server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    absolute_redirect off;
    access_log  /var/log/nginx/host.access.log  main;
    error_log  /var/log/nginx/host.error.log  debug;

    
    location /auth {
      proxy_pass http://my-keycloak:8080;
      proxy_set_header X-Forwarded-For $proxy_protocol_addr; # To forward the original client's IP address 
      proxy_set_header X-Forwarded-Proto $scheme; # to forward the  original protocol (HTTP or HTTPS)
      proxy_set_header Host $host; # to forward the original host requested by the client
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    #location ~ \.php$ {
    #    root           html;
    #    fastcgi_pass   127.0.0.1:9000;
    #    fastcgi_index  index.php;
    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    #    include        fastcgi_params;
    #}

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}
```

**Dockerfile**
```
# Use official nginx image as the base image
FROM nginx:1.23.1

COPY default.conf /etc/nginx/conf.d/

# Expose port 80
EXPOSE 80
```

Both of above files should be in same directory and then run
```sh
sudo docker build -t my-nginx:1.23.1 .
```

**docker-compose.yml**

```yml
version: '3.9'
services:
    my-postgresql:
        image: "postgres:14.5"
        volumes:
        - /kcdata/postgresql:/var/lib/postgresql/data
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=keycloak
        - PGDATA=/var/lib/postgresql/data/pgdata
        restart: unless-stopped
    my-keycloak:
        image: "quay.io/keycloak/keycloak:19.0.2"
        environment:
        - KC_DB=postgres
        - KC_DB_URL=jdbc:postgresql://my-postgresql:5432/
        - KC_DB_USERNAME=testuser
        - KC_DB_PASSWORD=testpw
        - KC_HOSTNAME=localhost
        - KC_HOSTNAME_PORT=8080
        - KC_HOSTNAME_ADMIN_URL=http://localhost:8080/auth
        - KEYCLOAK_ADMIN=admin
        - KEYCLOAK_ADMIN_PASSWORD=admin
        - KC_HTTP_RELATIVE_PATH=/auth
        command: ["start-dev", "--proxy", "edge"]
        depends_on:
        - my-postgresql
        restart: unless-stopped
    my-nginx:
        image: "my-nginx:1.23.1"
        ports:
        - "8080:80"
        depends_on:
        - my-keycloak
```

then from same directory run

```sh
sudo docker compose up
```

### Anything else?

> Keyclock is build for PostgreSQL (not part of above yml)
> Nginx is configured with [absolute redirect off;](http://nginx.org/en/docs/http/ngx_http_core_module.html#absolute_redirect)
> No issues with default port 80
