### ISSUE TITLE
Possibility to configure metadata for the service created by the operator

### ISSUE THREAD

**Issue by sebidude** [keycloak/keycloak#14669]
### Description

When using the operator, one cannot add labels or annotations to the service which gets created by the operator.

### Motivation

It would be nice to have the possibility to configure/adjust the metadata of the service created by the operator to be able to trigger external controllers or things like that. For example LB controllers.

### Details

My suggestion is to add a `serviceConfiguration` map to the CRD similar to `serverConfiguration` which could look like this:

```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  serviceConfiguration:
    metadata:
      labels:
        my-label-key: my-label-value
      annotations:
        my-annotation-key: my-annotation-value 
```
