### ISSUE TITLE
Keycloak:15.1.1  is deployed in k8s with nginx ingress but https://hostname/auth is not displaying and page is keep refreshing.

### ISSUE THREAD

**Issue by narasimhamurthi** [keycloak/keycloak#14909]
### Describe the bug

Keycloak:15.1.1  is deployed in k8s with nginx ingress but https://hostname/auth is not displaying and page is keep refreshing.

### Version

15.1.1

### Expected behavior

Keycloak:15.1.1  is deployed in k8s with nginx ingress but https://hostname/auth is not displaying and page is keep refreshing.

please suggest if any

deployment file
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: realoq-identity-keycloak
  namespace: realoq-services
  labels:
    app: realoq-identity-keycloak
spec:
  replicas: 1
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: realoq-identity-keycloak
  template:
    metadata:
      labels:
        app: realoq-identity-keycloak
    spec:
      containers:
      - name: realoq-identity-keycloak
        image: quay.io/keycloak/keycloak:15.1.1
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: "/auth/realms/master"
            port: 8080
        ports:
          - name: http
            containerPort: 8080
          - name: https
            containerPort: 8443
        env:
          - name: PROXY_ADDRESS_FORWARDING
            value: "true"
          - name: KEYCLOAK_FRONTEND_URL
            value: "https://XXxXxx/auth/"
```

ingress file

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: realoq-services-ingress
  namespace: realoq-services
  labels:
    app: realoq-listings-frontend
  annotations:
    cert-manager.io/issuer: letsencrypt-nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  tls:
  - hosts:
    - dev.XXXXXXXX.com
    secretName: letsencrypt-nginx
  rules:
  - host: "dev.XXXXX.com"
    http:
      paths:
      - path: /auth(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: realoq-identity-keycloak
            port:
              number: 80
  ingressClassName: nginx

```
