### ISSUE TITLE
Forbidden 403 on Admin UI with HTTPS

### ISSUE THREAD

**Issue by filipetavares** [keycloak/keycloak#15107]
### Area

admin/ui

### Describe the bug

Running keycloak in production mode on AWS, with the following configurations:

KC_HOSTNAME: sitename.com
KC_HOSTNAME_STRICT: "true"
KC_HTTP_PORT: "8080"
KC_HTTPS_PORT: "8443"
KC_LOG_LEVEL: INFO
KC_PROXY: edge
KC_SERVICE_FQDN: keycloak
PROXY_ADDRESS_FORWARDING: "true"

And I'm getting a 403 forbidden just like in https://github.com/keycloak/keycloak/issues/14812, but I'm accessing though **https://sitename.com/auth** (I've added the **relative path** as well in config file).

The only way I have to make it work is by setting KC_HOSTNAME_ADMIN_URL env var:
KC_HOSTNAME_ADMIN_URL: https://sitename.com/auth/

Shouldn't this work by default since I'm doing everything with https or does it not count for the relative path?

### Version

19.0.3

### Expected behavior

Shouldn't need to set the KC_HOSTNAME_ADMIN_URL  var to be able to access the ADMIN CONSOLE without a 403 forbbiden.

### Actual behavior

Get the Forbidden 403 when getting to ADMIN CONSOLE.

### How to Reproduce?

Launch a keycloak in AWS with an nginx ingress in front of it, and don't set the KC_HOSTNAME_ADMIN_URL var. When going to the admin console it should keep loading indefinitely and you should get a 403 forbidden in the requests performed to the server.

**Comment by filipetavares** [comment]
I'm guessing you mean this documentation https://www.keycloak.org/server/hostname, which has this single line about `hostname-path` and there is no example:
> This should be set if proxy uses a different context-path for Keycloak.

Do you mind explaining what should be set here?

**Comment by ykun91** [comment]
I have meet the same issue. 

In my environment, the requests go `GCP HTTPS Load balancer ---(HTTPS)---> traefik ---(HTTP)---> keycloak`
with `KC_PROXY=edge` set.  Then I go to the Admin console and got a 403 error, and the page is keep loading forever.

I dig into this issue, and finally found out it was caused by the lack of `forwardedHeaders.trustedIPs` [settings](https://doc.traefik.io/traefik/routing/entrypoints/#forwarded-headers) in traefik.

Without this setting, traefik will not forward the `X-Forwarded-*` headers from the HTTPS load balancer to Keycloak,
due to the lack of `X-Forwarded-Proto` header, Keycloak can't recognize itself is running behand a HTTPS proxy, then cause this issue.

After I add that `forwardedHeaders` settings, every things go works well, without the `KC_HOSTNAME_ADMIN_URL`.

So, maybe same as the nginx, you may need to set the nginx to send `X-Forwarded-Proto: https` header to backend.

JFYI

**Comment by nschipperbrainsmith** [comment]
This problem still happens in the latest version. The only way I managed to fix this was by not using the `KC_HOSTNAME` and `KC_HOSTNAME_ADMIN` but instead using the `KC_HOSTNAME_URL` and `KC_HOSTNAME_ADMIN_URL`

docker-compose.yml
```
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      KC_PROXY: "edge"
      KC_HTTP_ENABLED: "false"
      KC_HOSTNAME_STRICT: "true"
      KC_HOSTNAME_STRICT_HTTPS: "true"
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_DB_URL: "jdbc:postgresql://somehost:5432/keycloak"
#      KC_HOSTNAME: ${KEYCLOAK_HOST}
#      KC_HOSTNAME_ADMIN: ${KEYCLOAK_HOST}
      KC_HOSTNAME_URL: "https://authorisation.somehost.local/"
      KC_HOSTNAME_ADMIN_URL: "https://authorisation.somehost.local/"
      KC_LOG_LEVEL: debug
```

**Comment by bader-tayeb** [comment]
> I go to the Admin console and got a 403 error, and the page is keep loading forever.

For anyone facing this in the future, I had the same issue with it loading forever. For me, it turns out it was a database dumping issue. I am using MySQL and the binary data got loaded incorrectly (they all loaded with 0). So everything was "disabled" in the database columns.

**Comment by lanmarti** [comment]
I encountered the same issue while upgrading from v20 to v22, without any configuration changes on my side.
I deploy keycloak through the keycloak operator. The `hostname` field was already set before upgrading. The operator seems to have `hostname` (`KC_HOSTNAME`), `admin` (`KC_HOSTNAME_ADMIN`) and `adminUrl` (`KC_HOSTNAME_ADMIN_URL`), but no `KC_HOSTNAME_URL` equivalent. Luckily, setting `adminUrl` seems to suffice.

```
  hostname:
    adminUrl: 'https://your.domain.org/'
    hostname: your.domain.org
    strict: true
 ```
