### ISSUE TITLE
Admin console Invalid parameter: redirect_uri

### ISSUE THREAD

**Issue by tomhuang12** [keycloak/keycloak#15123]
### Area

operator

### Describe the bug

I am trying out the new operator deployed using vanilla kubernetes manifests from https://github.com/keycloak/keycloak-k8s-resources. 

I deployed the following Keycloak CR and a custom ingress resource but unable to get to the admin console login page with error `Invalid parameter: redirect_uri`. I am using nginx ingress controller for ingress traffic. Please advise on how to identify and fix the root cause. 
Note that the URL is redacted to `auth.mycompany.com` but hope it gets the idea across.

Keycloak CR:
```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 3
  serverConfiguration:
    - name: db
      value: postgres
    - name: db-url-host
      secret:
        name: keycloak-db-secret
        key: POSTGRES_EXTERNAL_ADDRESS
    - name: db-url-database
      secret:
        name: keycloak-db-secret
        key: POSTGRES_DATABASE
    - name: db-url-port
      secret:
        name: keycloak-db-secret
        key: POSTGRES_EXTERNAL_PORT
    - name: db-username
      secret:
        name: keycloak-db-secret
        key: POSTGRES_USERNAME
    - name: db-password
      secret:
        name: keycloak-db-secret
        key: POSTGRES_PASSWORD
  hostname: auth.mycompany.com
  tlsSecret: tls-secret
  disableDefaultIngress: true
```

Ingress:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress-public
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  labels:
    app: keycloak
spec:
  ingressClassName: nginx
  rules:
  - host: auth.mycompany.com
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /
        backend:
          service:
            name: keycloak-service
            port: 
              number: 8443
```

Error log from keycloak pod:
```
2022-10-24 17:56:43,075 WARN  [org.keycloak.events] (executor-thread-7) type=LOGIN_ERROR, realmId=ecb20500-7e2f-4a4c-8028-6ed5d318d01b, clientId=security-admin-console, userId=null, ipAddress=10.15.0.94, error=invalid_redirect_uri, redirect_uri=https://auth.mycompany.com/admin/master/console/
```

### Version

18.0.2

### Expected behavior

I should be able to get to the login screen and successfully sign in with the admin credentials. 

### Actual behavior

Unable to get to the login console with error `Invalid parameter: redirect_uri`

### How to Reproduce?

1. Deploy the Kubernetes operator manifests from https://github.com/keycloak/keycloak-k8s-resources. 
2. Deploy an nginx ingress controller
3. Deploy Keycloak CR described above
4. Deploy ingress resource described above
5. Try to get to admin console from the URL

### Anything else?

The pod env's `KC_HOSTNAME` is set to auth.mycompany.com which I think is what `$(authAdminUrl)` picks up the url from for the `security-admin-console` client root url.
