### ISSUE TITLE
[bug] stable version 18.0 doesn't connect to postgres in production mode

### ISSUE THREAD

**Issue by yalattas** [keycloak/keycloak#15228]
### Area

core

### Describe the bug

keyCloak version `18.0` doesn't work with postgres in `production mode`. only `dev mode`

### Version

18

### Expected behavior

For the app to bootstrap in production mode with ability to connect to postgres db

### Actual behavior

running the app in production failed due to ` java.sql.SQLException: No suitable driver found for jdbc:postgresql://iam-db/keyclock`

In case of changing the base image to the latest instead of 18.0, it does work. But there is another bug in user role mapping as an admin to a realm.

error trace
```
iam-backend    | 2022-10-31 13:59:20,125 WARN  [org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator] (JPA Startup Thread: keycloak-default) HHH000342: Could not obtain connection to query metadata: java.sql.SQLException: No suitable driver found for jdbc:postgresql://iam-db/keyclock
iam-backend    |        at org.h2.jdbcx.JdbcDataSource.getJdbcConnection(JdbcDataSource.java:191)
iam-backend    |        at org.h2.jdbcx.JdbcDataSource.getXAConnection(JdbcDataSource.java:352)
iam-backend    |        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:216)
iam-backend    |        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:513)
iam-backend    |        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:494)
iam-backend    |        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
iam-backend    |        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
iam-backend    |        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
iam-backend    |        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
iam-backend    |        at java.base/java.lang.Thread.run(Thread.java:829)
```

Dockerfile
```
FROM quay.io/keycloak/keycloak:18.0 as builder
ARG KEYCLOAK_HOME="/opt/keycloak"
# Install custom providers
RUN curl -sL https://github.com/aerogear/keycloak-metrics-spi/releases/download/2.5.3/keycloak-metrics-spi-2.5.3.jar -o ${KEYCLOAK_HOME}/providers/keycloak-metrics-spi-2.5.3.jar
RUN ${KEYCLOAK_HOME}/bin/kc.sh build

FROM quay.io/keycloak/keycloak:latest
ARG KEYCLOAK_HOME="/opt/keycloak"
COPY --from=builder ${KEYCLOAK_HOME}/ ${KEYCLOAK_HOME}/
WORKDIR ${KEYCLOAK_HOME}
# for demonstration purposes only, please make sure to use proper certificates in production instead
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
RUN export PATH=$PATH:${KEYCLOAK_HOME}/bin
# change these values to point to a running postgres instance
ENV KC_DB_URL=db_url
ENV KC_DB_USERNAME=db_username
ENV KC_DB_PASSWORD=db_password
ENV KC_HOSTNAME=localhost
EXPOSE 8443
ENTRYPOINT ["bin/kc.sh"]
CMD ["start"]
```

the option `start --optimized` exist only in the latest image but not `18.0`

In case I started the app in `dev` mode [`CMD ["start-dev"]`] it also is working with postgres just fine

Here is my environment variable file

```
KC_HOSTNAME="localhost"
KC_DB=postgres
KC_DB_URL="jdbc:postgresql://iam-db/keyclock"
KC_DB_SCHEMA="public"
KC_DB_USERNAME=postgres
KC_DB_PASSWORD=123123
KC_DB_POOL_MIN_SIZE=1
KC_DB_POOL_MAX_SIZE=5
KC_FEATURES="account-api,account2,admin2,authorization,ciba,client-policies,impersonation,par,step-up-authentication,web-authn,docker"
KC_HTTP_ENABLED=true
KC_HTTP_HOST="0.0.0.0"
KC_HTTP_PORT="8081"
KC_HTTPS_PORT="8443"
KC_HEALTH_ENABLED=true
KC_METRICS_ENABLED=true
KC_LOG="console"
KC_LOG_CONSOLE_COLOR=true
KC_LOG_CONSOLE_FORMAT="%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n"
KC_LOG_LEVEL="info"
KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=admin
```

my docker-compose file

```
version: '3.3'
services:
  iam-backend:
    container_name: iam-backend
    build: devops/keyclock
    restart: always
    env_file:
      - ./devops/keyclock/iam.env
    ports:
      - '8443:8443'
      - '8081:8081'
    depends_on:
      - iam-db

  iam-db:
    container_name: iam-db
    image: postgres:13-alpine
    volumes:
      - iam_db:/var/lib/postgresql/data/
    env_file:
      - devops/iam-db.env
    ports:
      - "5432:5432"

networks:
  default:
    name: survey_default_network

volumes:
  app_db:
  iam_db:
```

### How to Reproduce?

run base image 18.0 and connect to postgres and run the app in production mode
