### ISSUE TITLE
KC_HTTP_RELATIVE_PATH --http-relative-path ingress or nginx not work

### ISSUE THREAD

**Issue by yaoguoh** [keycloak/keycloak#15324]
### Area

admin/ui

#### Ingress or nginx proxy not work
- KC_HTTP_RELATIVE_PATH: auth 
- --http-relative-path /auth

### Version

20.0.0

### Expected behavior

![image](https://user-images.githubusercontent.com/18107429/199870759-5f777f71-ad90-4cec-8a7c-418555e40201.png)

### Actual behavior

Normal use

### How to Reproduce?

- KC_HTTP_RELATIVE_PATH: auth 
- kc.sh --http-relative-path /auth

https://example.com/auth

**Comment by yaoguoh** [comment]
## This can work

```yaml
apiVersion: apps/v1
kind: Deployment
spec:
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-keycloak-keycloak
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-keycloak-keycloak
    spec:
      containers:
        - args:
            - start
            - '--hostname-strict=false'
            - '--proxy=edge'
            - '--http-relative-path=auth'
          env:
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: 2DUEd7MxZ1OW
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: TZ
              value: Asia/Shanghai
            - name: KC_DB
              value: mysql
            - name: KC_DB_URL
              value: >-
                jdbc:mysql://mysql.mysql.svc.cluster.local:3306/keycloak
            - name: KC_DB_USERNAME
              value: keycloak
            - name: KC_DB_PASSWORD
              value: keycloak
            - name: KC_HEALTH_ENABLED
              value: 'true'
            - name: KC_METRICS_ENABLED
              value: 'true'
          image: quay.io/keycloak/keycloak:20.0.0
          imagePullPolicy: Always
          name: container-0
          ports:
            - containerPort: 8080
              name: 8080tcp
              protocol: TCP
              _serviceType: ClusterIP
              _name: 8080tcp


apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |-
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Host $http_host;
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          service:
            name: keycloak
            port:
              number: 8080
        path: /auth
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - example.com
    secretName: pharmbrain

```
