### ISSUE TITLE
Keycloak admin console redirecting to port 443 instead of 8088

### ISSUE THREAD

**Issue by raz08** [keycloak/keycloak#15375]
### Area

admin/ui

### Describe the bug

we are using keycloak:19.0.3. We have reverse proxy to serve HTTPS i.e. we set proxy to edge. 

```
        - start
        - --hostname-strict-https=false
        - --hostname-strict=false
        - --hostname-strict-backchannel=true
        - -Djboss.bind.address.private=127.0.0.1
        - -Djboss.bind.address=0.0.0.0
        - --log-level=debug

        env:
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KC_PROXY
          value: edge

```

Tried
        - name: KC_HOSTNAME_ADMIN_URL
          value: https://{publicip}:8088

working with this, but we don't want to hardcode public IP(because it is dynamic) neither we don not have dns. Is there a way we can just mention to use the request port as it is?

With private or public IP we are accessing the admin UI. When we click on "Administration console" it is redirecting to https://{publicip}/admin instead of https://{publicip}:8088/admin. 

### Version

Tried in both 19.0 and 20.0

### Expected behavior

Should use same port as request port i.e. 8088.

### Actual behavior

redirecting to default 443 port 

### How to Reproduce?

with 19.0

**Comment by ssilvert** [comment]
@raz08 Can we close this issue?

**Comment by ssilvert** [comment]
@raz08 I'm going to close this issue now.  If you continue to have problems we can reopen.

**Comment by Alpenbelieve** [comment]
@ssilvert Why close this issue?  I met the same problem in Keycloak 18.0.2 Quarkus. The official document about configure cluster, hostname and reverseproxy is so confusing... I spend several days on making keycloak cluster works fine in K8s, and then I encountered this issue... I've tried many config in many posts but still have this issue.
I also don't want to hardcode public IP(because it is dynamic).

When I visit  https://myipaddress:30383/auth/ , the welcome page appears, and when I click admin console, URL becomes https://myipaddress/auth/admin/.

My Keycloak Stateful config:
```yaml
      containers:
      - args:
        - start-dev
        env:
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL_HOST
          value: postgresql
        - name: KC_DB_URL_DATABASE
          value: keycloak
        - name: JGROUPS_DISCOVERY_EXTERNAL_IP
          value: keycloak-discovery.iam.svc.cluster.local
        - name: KC_LOG_LEVEL
          value: INFO,org.infinispan:DEBUG,org.jgroups:DEBUG
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: admin
        - name: JAVA_OPTS_APPEND
          value: -Djava.net.preferIPv6Stack=true
        - name: KC_HTTP_RELATIVE_PATH
          value: /auth/
        - name: KC_PROXY
          value: edge
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "false"
        - name: KC_HOSTNAME_URL
          value: https://myipaddress:30383/auth/
        - name: KC_HOSTNAME_ADMIN_URL
          value: https://myipaddress:30383/auth/
```

**Comment by ssilvert** [comment]
@Alpenbelieve I closed it because there was no response.  

Also see https://github.com/keycloak/keycloak/issues/14666

Can you verify if the issue still exists in the latest version of Keycloak?  If so, we will reopen.

**Comment by Alpenbelieve** [comment]
The above issue still exists in the latest version of Keycloak.
After more experiments, when I use 18.0.2 and yaml is
```
      containers:
      - args:
        - start-dev
        env:
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL_HOST
          value: postgresql
        - name: KC_DB_URL_DATABASE
          value: keycloak
        - name: KC_LOG_LEVEL
          value: INFO,org.infinispan:DEBUG,org.jgroups:DEBUG
        - name: JGROUPS_DISCOVERY_EXTERNAL_IP
          value: keycloak-discovery.iam.svc.cluster.local
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: aliyun_cos
        - name: KC_HTTP_RELATIVE_PATH
          value: /auth/
        - name: KC_HOSTNAME_ADMIN_URL
          value: https://myipaddress:30383/auth/
        - name: KC_HOSTNAME_URL
          value: https://myipaddress:30383/auth/
```
The admin console's url is correct (https://myipaddress:30383/auth/admin/), but the page is empty white and console log is:
```
Refused to frame 'http://myipaddress:30383/' because it violates the following Content Security Policy directive: "frame-src 'self'".
```
(Some other issues also mentioned this)

When  I use 20.0.3 and above yaml, everything is fine.

Well, maybe I have to migrate to the latest version. Will there be version 2.0 in the near future? Thanks.
