### ISSUE TITLE
No email send on TOTP/Authenticator app removal

### ISSUE THREAD

**Issue by sventorben** [keycloak/keycloak#15403]
### Area

account/ui

### Describe the bug

When a TOTP device/authenticator app is removed via account console, no email is send via the email event listener.
This worked with the old account console, but does not with the new account console.

### Version

20.0.1

### Expected behavior

An email should be send to the user that notifies the user about the removal of TOTP device/Authenticator app.

### Actual behavior

No email is send when the new account console is used.
With the old account console the email is send.

### How to Reproduce?

Create a file named `docker-compose.yml` with this content:
```yaml
version: '3'
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:20.0.1
    environment:
      KC_SPI_EVENTS_LISTENER_EMAIL_ENABLED: "true"
      KC_SPI_EVENTS_LISTENER_EMAIL_INCLUDE_EVENTS: UPDATE_TOTP,REMOVE_TOTP
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DEBUG_PORT: '*:8787'
      DEBUG: 'true'
    command: ['start-dev', '--debug']
    ports:
      - 8080:8080
      - 8787:8787
  mail:
    container_name: mail
    image: maildev/maildev
    ports:
      - 1080:1080

```

- Start the docker containers via `docker-compose up`.
- Navigate to http://localhost:8080/admin/master/console/#/
- Login with user `admin` and password `admin`
- Navigate to `Users -> admin`
  - Add `admin@local.local` as email address
  - Mark email as verified
  - Save the changes
- Navigate to `Realm settings -> Email`
  - Add `keycloak@local.local` as from address
  - Add `mail` as SMTP host
  - Add `1025` as SMTP port
  - Save the changes
  - Test connection (should succeed)
- Navigate to `Realm settings -> Events -> Event Listeners`
  - Add `email` to the list of event listeners
  - Save changes
- Navigate to http://localhost:8080/realms/master/account/#/security/signingin
  - Click `Setup authenticator application`
  - Register authenticator app via barcode
- Navigate to http://localhost:1080/#/
  - You should see an email with subject `Update OTP`
- Navigate http://localhost:8080/realms/master/account/#/security/signingin
  - Remove the authenticator application
- Navigate to http://localhost:1080/#/
  - refresh the page
  - ⚠️ No email with subject `Remove OTP` is shown
- In the admin console navigate to `Realm settings -> themes` (http://localhost:8080/admin/master/console/#/master/realm-settings/themes)
  - Change the `Account theme` to `keycloak` (old account management console)
  - Save changes
- Navigate to http://localhost:8080/realms/master/account/totp
  - Register authenticator app via barcode
 - Navigate to http://localhost:1080/#/
  - refresh the page
  - An additional email with subject `Update OTP` is shown
- Navigate to http://localhost:8080/realms/master/account/totp
  - Delete the configured authenticator
- Navigate to http://localhost:1080/#/
  - refresh the page
  - ✔️ Email with subject `Remove OTP` is shown

### Anything else?

The old account console uses this endpoint to delte the authenticator app: `http://localhost:8080/realms/master/account/totp`
The new account console uses this endpoint instead: `http://localhost:8080/realms/master/account/credentials/<credential_id>`

It looks like the credential endpoint does not fire the `REMOVE_TOTP` event.
