### ISSUE TITLE
Ability to modify command and args section of pod generated by KeyCloakRealmImport

### ISSUE THREAD

**Issue by eversardoth** [keycloak/keycloak#15458]
### Description

Add 'command' and 'args' field in KeycloakRealmImport CRD to manage command and args section in keycloak container in the pod generated by KeycloakRealmImport object.

### Motivation

Being able to shutdown database authorization side-car (cloud-sql-proxy) after import is generated.

This is the configuration of my side-car container (cloud-sql-proxy) added in the Keycloak object.

![image](https://user-images.githubusercontent.com/68908705/201235899-44cca810-39ac-4b62-b38c-d7074ee63dd1.png)

The pod generated by the KeycloakRealmImport object inherits this sidecar container, but after the import is completed the side car container keeps running. As you can see, the pod is configured to kill the connection process after the file /tmp/pod/terminated is created, this file would be created in the keycloak container by adding the file in a emptyDir shared volume between the sidecar and the keycloak container.

Right now, this cannot be done since the command and args section of the keycloak contaniner in the pod generated by the KeycloakRealmImport object always defaults to this:

![image](https://user-images.githubusercontent.com/68908705/201237247-af52f903-532f-4c8b-aab3-55c192d8ed60.png)

**Comment by abelmatos** [comment]
Same issue here.

I'm running cloud-sql-proxy with --quitquitquit. 
And I need to call something like this `curl -X POST localhost:9091/quitquitquit"`



proxy config
```
          - name: cloud-sql-proxy
            image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
            imagePullPolicy: Always
            env:
              - name: INSTANCES
                valueFrom:
                  secretKeyRef:
                    name: keycloak-gcp
                    key: CLOUD_SQL_INSTANCE_NAME
            args:
              - "--structured-logs"
              - "--quitquitquit"
              - "$(INSTANCES)"
```

related to:
https://github.com/GoogleCloudPlatform/cloud-sql-proxy/issues/828

**Comment by shawkins** [comment]
@eversardoth I don't see a good way around. The only current workaroud I can think of would be to create a custom image with a modified kc.sh that produces the termination file you want.

~priority-normal

**Comment by abelmatos** [comment]
https://kubernetes.io/docs/concepts/workloads/pods/sidecar-containers/
> Jobs with sidecar containers 
If you define a Job that uses sidecar using Kubernetes-style init containers, the sidecar container in each Pod does not prevent the Job from completing after the main container has finished.

**Comment by shawkins** [comment]
@abelmatos can you clarify that the init container is working for you? The previous comment seemed to suggest you still needed something to call "And I need to call something like this curl -X POST localhost:9091/quitquitquit". 

@eversardoth did you define your sidecar as an init container? The link @abelmatos provided seems to suggest that if it were, then it should be terminated along with the Job when the main container completes.

**Comment by abelmatos** [comment]
@shawkins 
Get it working with 

```
  unsupported:
    podTemplate:
      spec:
        initContainers:
          - name: cloud-sql-proxy
            image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
            imagePullPolicy: Always
            restartPolicy: Always
            env:
              - name: INSTANCES
                valueFrom:
                  secretKeyRef:
                    name: keycloak-gcp
                    key: CLOUD_SQL_INSTANCE_NAME
            args:
              - "--structured-logs"
              - "$(INSTANCES)"
            securityContext:
              runAsNonRoot: true
```

The caveat is that it's only compatible with GKE ( Kubernetes >= v1.29 )

**Comment by shawkins** [comment]
> The caveat is that it's only compatible with GKE ( Kubernetes >= v1.29 )

So beta support would be coming in OpenShift 4.16 as well. 

This also relates to #29200 - if we commit to providing a version of import/export that act against a running server, this issue will be moot.

**Comment by Tomasz-Marciniak** [comment]
My workaround... do not add realm.yaml to kustomization.yaml

Mount it as config map and run apply from own job with own annotations:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-realm-import
  namespace: platform
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      serviceAccountName: keycloak-operator
      containers:
        - name: realm-import
          image: bitnami/kubectl:1.30
          command:
            - /bin/sh
            - -c
            - |
              set -e
              echo ">>> Applying KeycloakRealmImport CR..."
         
              kubectl apply -f /manifests/realm.yaml
              
              echo ">>> Waiting for Keycloak to import realm..."
              # simple wait; can be replaced with smarter check via Keycloak API
              sleep 60
              
              echo ">>> Deleting KeycloakRealmImport CR..."
              kubectl delete -f /manifests/realm.yaml
              
              echo ">>> Done!"
          volumeMounts:
            - name: realm-manifest
              mountPath: /manifests
      volumes:
        - name: realm-manifest
          configMap:
            name: keycloak-realm-cm
```
