### ISSUE TITLE
Keycloak is crashing on Debian systemd

### ISSUE THREAD

**Issue by SpiderD555** [keycloak/keycloak#15534]
### Area

core

### Describe the bug

When I use systemd service, then keycloak crashes after around 20 seconds.

### Version

20.0.1

### Expected behavior

Keycloak should start normally with systemd service and I should be able to access main page

### Actual behavior

Keycloak systemd service crashes after around 20 seconds with log:
2022-11-16 21:52:05,991 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) Key material not provided to setup HTTPS. Please configure your keys/certificates or start the server in development mode.

### How to Reproduce?

Install Debian VM and use this script to reproduce the setup (make sure to change default hostname, certbot server and email):
[script.txt](https://github.com/keycloak/keycloak/files/10026011/script.txt)

### Anything else?

I tried changing the certificate and key files path/ownership/privileges, also tried older java 8. Only when I change the systemd user from keycloak to root, run the keycloak once, then change user back to keycloak, then it works.

**Comment by SpiderD555** [comment]
After reading this thread https://github.com/keycloak/keycloak/discussions/10180 I came to a conclusion that this is an issue with file permissions.
What I did next is this:
1. create a folder /opt/letsencrypt/ with keycloak user/group permissions
2. Install authbind, so certbot can run as non-root user and bind to port 80 (this is achieved by creating empty /etc/authbind/byport/80 file with credentials that will allow keycloak to execute it
3. Run certbot as keycloak user and set work/config directories to /opt/letsencrypt

After that keycloak have no problems with loading the certificate, that certbot created.
Here is my Ansible playbook snippet that deals with above steps (if anyone needs it):
```
---
- name: Install certbot and authbind (so certbot can bind to low port number)
  become: true
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - certbot
    - authbind

- name: Create authbind file
  become: true
  ansible.builtin.file:
    path: "/etc/authbind/byport/80"
    state: touch
    owner: root
    group: "{{ keycloak.service_group }}"
    mode: 0454

- name: Get certificate
  shell: "sudo -u keycloak authbind certbot certonly -n --standalone -d {{ hostname }} --server {{ acme_directory }} --agree-tos --email {{ certbot_email }} --config-dir {{ keycloak_certbot_dir }} --work-dir {{ keycloak_certbot_dir }} --logs-dir {{ keycloak_log_file_folder }}"
```

Now the main question comes if this is a real bug or rather "works as designed"/"It is not a bug, it is a feature".
In ideal world I would expect that keycloak could fetch certificate files from /etc/letsencrypt/ folder, just like apache or nginx can, but since I have a working keycloak server now, then I will let @vmuzikar decide if this issue should be closed or not.
