### ISSUE TITLE
Descoped mode for the Operator

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#15888]
Operator should support cluster-wide mode, i.e. a single Operator for all namespaces.

**Comment by shawkins** [comment]
Is the desire here to support all modes, like as shown on #12545 via env overrides, or should the operator always be / default to cluster wide?

If the intention is be cluster-wide are there any immediate considerations for blast-radius that are needed?

**Comment by vmuzikar** [comment]
@shawkins IIRC, the mode is usually decided during the installation of the Operator via OLM. That implies some specific env vars. But this needs to be double checked.

**Comment by shawkins** [comment]
I see in the csv that we're declaring support for all installModes:

```
installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: false
      type: AllNamespaces
```

From the other issue https://github.com/keycloak/keycloak/issues/12545#issuecomment-1594335970 the user is then responsible for setting env variables:

QUARKUS_OPERATOR_SDK_CONTROLLERS_KEYCLOAKCONTROLLER_NAMESPACES
QUARKUS_OPERATOR_SDK_CONTROLLERS_KEYCLOAKREALMIMPORTCONTROLLER_NAMESPACES

I can confirm that when you use all namespaces. you do see the primary informers start watching everything:

```
Starting informer for namespace: JOSDK_ALL_NAMESPACES resource: Keycloak
```

However this setting does not influence the informers registered by prepareEventSources, the namespace it obtains from the client configuration is the current namespace, so we'll only watch dependent resources in the current namespace.

To confirm, the expectation here is to support all InstallModes (defaulting to current namespace) and let the user set env the controller env variables as necessary for anything else.
