### ISSUE TITLE
Can not set Context path on Keycloak 20

### ISSUE THREAD

**Issue by wavemoroc001** [keycloak/keycloak#15921]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

I deploy keycloak via docker-compose. I try to set context path to `\auth` via `KC_HTTP_RELATIVE_PATH` and try on cli `--http-relative-path` it doesn't work. following this [documents](https://www.keycloak.org/server/all-config)

**Docker-compose file**
```yaml
 keycloak:
      image: quay.io/keycloak/keycloak
      environment:
        TZ: Asia/Bangkok
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_SCHEMA: public
        DB_USER: psql
        DB_PASSWORD: secret
        KEYCLOAK_ADMIN: keycloak
        KEYCLOAK_ADMIN_PASSWORD: secret
        KC_HOSTNAME_URL: https://gateway-classroom.wavemoroc.app:8443
        KC_HTTP_RELATIVE_PATH: /auth
        KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/tls.key
        KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/tls.crt
      command : start --optimized
      ports:
        - 8080:8080
        - 8443:8443
        - 9990:9990
      volumes:
        - ./cert/classroom_cert.crt:/etc/x509/https/tls.crt
        - ./cert/classroom_key.key:/etc/x509/https/tls.key
      depends_on:
        - postgres
      networks:
        - apisix
```
In log, it look like not effect 
```log
keycloak_1  | 2022-12-09 10:44:51,929 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: https://gateway-classroom.wavemoroc.app:8443, Hostname: gateway-classroom.wavemoroc.app, Strict HTTPS: true, Path: /, Strict BackChannel: false, Admin URL: <unset>, Admin: <request>, Port: 8443, Proxied: false
keycloak_1  | 2022-12-09 10:44:53,882 WARN  [io.quarkus.agroal.runtime.DataSources] (main) Datasource <default> enables XA but transaction recovery is not enabled. Please enable transaction recovery by setting quarkus.transaction-manager.enable-recovery=true, otherwise data may be lost if the application is terminated abruptly
```

I have try `--http-relative-path` in cli. it throw back unknown this option.
```log
keycloak_1  | Unknown option: '--http-relative-path'
keycloak_1  | Possible solutions: --http-enabled, --http-host, --http-port, --https-port, --https-client-auth, --https-cipher-suites, --https-protocols, --https-certificate-file, --https-certificate-key-file, --https-key-store-file, --https-key-store-password, --https-key-store-type, --https-trust-store-file, --https-trust-store-password, --https-trust-store-type
keycloak_1  | Try 'kc.sh start --help' for more information on the available options.
``` 

### Version

keycloak 20.0

### Expected behavior

When set context path via `KC_HTTP_RELATIVE_PATH` or `--http-relative-path` should set

### Actual behavior

It have not effect. still set in default context `\`

### How to Reproduce?

Try to set context path via docker env `KC_HTTP_RELATIVE_PATH` or cli `--http-relative-path`
