### ISSUE TITLE
Changing locale on error page doesn't work

### ISSUE THREAD

**Issue by SamTV12345** [keycloak/keycloak#15972]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/ui

### Describe the bug

When changing the locale on an error page like "You are already logged in" the locale doesn't change.

### Version

20.0.1

### Expected behavior

The locale should change and I should see the message in different languages.

### Actual behavior

The page reloads but the language is still the same. The Query parameter does change but that doesn't seem to have an effect on the locale being displayed.

### How to Reproduce?

1. Start with this docker-compose

```yaml
version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.1
    ports:
      - "80:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
    volumes:
      - .local/keycloak/:/opt/jboss/keycloak/standalone/data/
 ```
 
 2. Open the account console in to different tabs without login. 
 3. Log into the Account console with one tab. 
 4. Do the same with the other tab. 
 5. You should see the message that you are already logged in.
 6. Change the locale via the dropdown. The page refreshes and changes the query parameter but doesn't change locale.current

### Anything else?

There is already a closed issue here: [Fixed locale switcher on error page](https://github.com/keycloak/keycloak/pull/14728) but that did not resolve the issue. I can see the changed line in 20.0.1 but the behaviour is still wrong.
