### ISSUE TITLE
403 login-status-iframe on Keycloak Docker Compose

### ISSUE THREAD

**Issue by tnsfk309** [keycloak/keycloak#16005]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

I just got Keycloak with compose and when I try to get into the admin panel, it gets stuck on loading loop and I checked console to see what the issue is and it throws 403 on the URL:
`https://auth.ryuluna.com/realms/master/protocol/openid-connect/login-status-iframe.html/init?client_id=security-admin-console&origin=https%3A%2F%2Fauth.ryuluna.com`
![image](https://user-images.githubusercontent.com/32681723/207747907-0c9fab85-a9cd-4853-9594-9f8b4028b38e.png)

I'm using the following compose yml
```
version: "3"

services:

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: always
    command: start
    environment:
      KC_PROXY_ADDRESS_FORWARDING: "true"
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME: auth.ryuluna.com
      KC_PROXY: edge
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/$POSTGRES_DB?ssl=allow
      KC_DB_USERNAME: $POSTGRES_USER
      KC_DB_PASSWORD: $POSTGRES_PASSWORD
      KEYCLOAK_LOGLEVEL: ERROR
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    labels:
      - traefik.enable=true
      - traefik.http.routers.keycloak-http.rule=Host(`auth.ryuluna.com`)
      - traefik.http.routers.keycloak-http.entrypoints=web
      - traefik.http.routers.keycloak-http.service=keycloak
      - traefik.http.services.keycloak.loadbalancer.server.port=8080
    env_file:
      - .env
    networks:
      - traefik-net

  postgres:
    image: docker.io/postgres:14
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    env_file:
      - .env
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true
```

### Version

Latest

### Expected behavior

.

### Actual behavior

.

### How to Reproduce?

.
