### ISSUE TITLE
service account get `userinfo` return `401 Unauthorized`

### ISSUE THREAD

**Issue by dungdm93** [keycloak/keycloak#16015]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

oidc

### Describe the bug

After service account authenticated via `client_credential` flow, I send a request with its `access_token` to `userinfo_endpoint`, but Keycloak server return `401 Unauthorized`

### Version

20.0

### Expected behavior

Keycloak should return `200 OK` with user information as the same as normal user

### Actual behavior

401 Unauthorized

### How to Reproduce?

1. `docker compose up -d`
    ```
    version: '3'
    
    services:
      keycloak:
        image: quay.io/keycloak/keycloak:20.0
        command: [start-dev]
        environment:
          KEYCLOAK_ADMIN:           admin
          KEYCLOAK_ADMIN_PASSWORD:  SuperSecr3t
        ports:
        - 8080:8080
        volumes:
        - keycloak_data:/opt/keycloak/data
    
    volumes:
      keycloak_data:
        driver: local
    ```
2. Create new realm
3. Create new OIDC client and enable `Service accounts roles`
![image](https://user-images.githubusercontent.com/6848311/207871965-3179bf12-cf90-4e58-bec9-466ad87dcdd9.png)
 4. Authenticate using service account
     ```bash
     curl --location --request POST 'http://localhost:8080/realms/<realm>/protocol/openid-connect/token' \
        --header 'Content-Type: application/x-www-form-urlencoded' \
        --data-urlencode 'grant_type=client_credentials' \
        --data-urlencode 'client_id=<client_id>' \
        --data-urlencode 'client_secret=<client_secret>'
     ```

 5.  Get userinfo:
    ```bash
     curl --location --request GET 'http://localhost:8080/realms/<realm>/protocol/openid-connect/userinfo' \
    --header 'Authorization: Bearer <access_token>'
    ```

### Anything else?

I try to enable `Use refresh tokens for client credentials grant` as [KEYCLOAK-16800](https://issues.redhat.com/browse/KEYCLOAK-16800), but it won't work
