### ISSUE TITLE
How to open high availability?

### ISSUE THREAD

**Issue by Xuezenghuigithub** [keycloak/keycloak#16031]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

infinispan

### Describe the bug

I read the [documentation](https://www.keycloak.org/server/caching) about HA, And think Keycloak natively supports it.

But when I set up multiple replicas in Kubernetes, I can't log in to Keycloak. When the other replica is hit, Keycloak tells me that the login timed out, please log in again.

I want to know how I should turn on HA correctly, please.

### Version

20.0.1

### Expected behavior

After setting multiple replicas, I can use the Keycloak normally.

### Actual behavior

Your login attempt timed out. Login will start from the beginning.

### How to Reproduce?

1. Set multiple replicas in Kubernetes
2. Login

**Comment by Xuezenghuigithub** [comment]
This is my yaml:

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    name: my-keycloak
  name: my-keycloak
  namespace: dm
spec:
  type: LoadBalancer
  ports:
    - port: 8940
      targetPort: 8080
      protocol: TCP
  selector:
    name: my-keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-keycloak
  namespace: dm
spec:
  selector:
    matchLabels:
      name: my-keycloak
  replicas: 2
  template:
    metadata:
      labels:
        name: my-keycloak
    spec:
      volumes:
        - name: log-volume
          persistentVolumeClaim:
            claimName: dm-pv-claim-logs
      containers:
        - name: my-keycloak
          image: my-keycloak:dev_lastest
          imagePullPolicy: Always
          ports:
            - containerPort: 8940
          volumeMounts:
            - name: log-volume
              mountPath: /data/log
          resources:
            requests:
              cpu: "1000m"
              memory: "1024Mi"
            limits:
              cpu: "2000m"
              memory: "2048Mi"
          args:
            - start
            - --log=console,file
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: dm-secret
                  key: keycloak_username
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dm-secret
                  key: keycloak_password
            - name: KC_PROXY
              value: edge
            - name: KC_HOSTNAME
              value: *****
            - name: KC_HOSTNAME_STRICT_BACKCHANNEL
              value: "true"
            - name: KC_HOSTNAME_ADMIN
              value: *****
            - name: KC_DB
              value: mysql
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db_password_i
                  name: dm-secret
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: db_username_i
                  name: dm-secret
                  optional: false
            - name: KC_DB_URL
              value: jdbc:mysql:*****
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /realms/master
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
```
