### ISSUE TITLE
Stuck at Loading the admin console

### ISSUE THREAD

**Issue by Nefcanto** [keycloak/keycloak#16069]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/cli

### Describe the bug

This is my custom `Dockerfile` to to create `holism/accounts` docker image:

```
FROM quay.io/keycloak/keycloak:latest as builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure a database vendor
ENV KC_DB=mariadb

WORKDIR /opt/keycloak
# for demonstration purposes only, please make sure to use proper certificates in production instead
RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```

It's copied from [Running Keycloak in a container](https://www.keycloak.org/server/containers) and I just changed the database to `mariadb` and removed environment to be passed using Docker Compose.

This is my `docker-compose.yml` file:

```
version: "3.9"
services: 
    accounts:
        image: holism/accounts
        container_name: Accounts
        ports: 
            - 52985:8080
        environment: 
            - KEYCLOAK_FRONTEND_URL=https://accounts.holism.local/
            - PROXY_ADDRESS_FORWARDING=true
            - KC_HOSTNAME=https://accounts.holism.local/
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=password
            - KC_DB_URL_HOST=database
            - KC_DB_URL_DATABASE=accounts
            - KC_DB_URL_PORT=3306
            - KC_DB_USERNAME=db-user
            - KC_DB_PASSWORD=db-password
            - KC_PROXY=none
            
        # logging:
        #     driver: none
        restart: always
        #command: start --optimized --proxy edge
        command: start-dev
    database:
        image: mariadb
        container_name: AccountsDatabase
        ports:
            - 3306:3306
        environment:
            - MARIADB_ROOT_PASSWORD=root-password
            - MYSQL_DATABASE=accounts
            - MYSQL_USER=db-user
            - MYSQL_PASSWORD=db-password
        volumes:
            - /Temp/Accounts/Databases:/var/lib/mysql 
        logging:
            driver: none
        restart: always
    admin:
        image: adminer
        container_name: AccountsAdminer
        restart: always
        logging:
            driver: none
        ports:
            - 8080:8080
        environment:
            - ADMINER_DEFAULT_SERVER=database      
```

And this instance is behind an NGINX reverse propsy, with this `accounts.holism.local.conf` config:

```
server {
    listen 80;
    server_name accounts.holism.local;
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 http2 ssl;
    server_name accounts.holism.local;

    ssl_certificate /Temp/HolismHolding/Accounts/Certificate.pem;
    ssl_certificate_key /Temp/HolismHolding/Accounts/Key.pem;

    error_page 502 /502.html;

    location /502 {
    	root /HolismHolding/Infra/Nginx;
    	internal;
    }

    location / {
        proxy_pass http://localhost:52985;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
}
```

I use `mkcert` for local valid certificates and I also added `127.0.0.1 accounts.holism.local` to `/etc/hosts`.

So, basically, when I go to `https://accounts.holism.local` I see the home page of the Keycloak. And the certificate is also valid. But when I click on the **Administration Console** link, it goes to `https://accounts.holism.local/admin/master/console/` and I see this page indefinitely:

![Screenshot from 2022-12-19 14-13-47](https://user-images.githubusercontent.com/12782347/208408247-08162220-57df-4dfd-b452-c67ad2e62401.png)

And these are the logs from the browser console:

```
The source list for the Content Security Policy directive 'frame-src' contains an invalid source: 'http://https:'. It will be ignored.
index.0cb2e516.js:90 The source list for the Content Security Policy directive 'frame-src' contains an invalid source: 'http://https:'. It will be ignored.
At @ index.0cb2e516.js:90
Promise.then (async)
(anonymous) @ index.0cb2e516.js:90
Promise.then (async)
Keycloak.o.init @ index.0cb2e516.js:90
initAdminClient @ index.0cb2e516.js:90
initialize @ index.0cb2e516.js:91
(anonymous) @ index.0cb2e516.js:91
index.0cb2e516.js:90 Refused to frame 'http://https/' because it violates the following Content Security Policy directive: "frame-src 'none'".

VM960:6748 crbug/1173575, non-JS module files deprecated.
(anonymous) @ VM960:6748
index.0cb2e516.js:91 Uncaught (in promise) {error: 'Timeout when waiting for 3rd party check iframe message.'}
```

### Version

20.0.2

### Expected behavior

When I have not specified the `KC_HOSTNAME_ADMIN` as per documentation Keycloak should use `KC_HOSTNAME`, or maybe I have misunderstood something.

Thus it should work on the `KC_HOSTNAME`.

### Actual behavior

It gets stuck on the **Loading the admin console** message.

### How to Reproduce?

- Use the above `Dockerfile` to build an image
- Use the above `docker-compose.yml` to configure services
- Use the above NGINX configuration
- Create an `mkcert` valid local certificate
- Set up local DNS
- Run `docker-compose up`
- Now go to `https://accounts.holism.local`

### Anything else?

I saw the https://github.com/keycloak/keycloak/issues/12612 issue, but I have not set or use `X-Frame-Options` anywhere. Neither have I used `KC_HOSTNAME_STRICT=false`.
