### ISSUE TITLE
20.0.2 keycloak (image docker server) doesnt use resources/partials extra-field-form templates from .jar file (custom 'social' provider in a /providers directory)

### ISSUE THREAD

**Issue by shamilsun** [keycloak/keycloak#16083]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

identity-brokering

### Describe the bug

My appologize, im not sure with the issue, 

I found similar issues but its not clear for the reason of issue and how to solve it.

**the case/issue**

**The envs:**

- docker
- image: quay.io/keycloak/keycloak:20.0.2 , its quarkus 
- identity provider jar file with packed theme resources (based on 'social identity provider behaviour')

**Reproduce steps:**

ill show issue by the favorite 'apple provider', https://github.com/klausbetz/apple-identity-provider-keycloak 

mine project is mostly then same.

So:

1. we need docker image image: quay.io/keycloak/keycloak:20.0.2 ,
2.  download https://github.com/klausbetz/apple-identity-provider-keycloak/releases/download/1.4.0/apple-identity-provider-1.4.0.jar
3.  place jar into /providers path under into docker container, im using docker-compose, so my content is

```
version: '3.3'
services:
  auth-server:
    image: quay.io/keycloak/keycloak:20.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME: auth-server
      #to keep compatible with other services that are expecting /auth
      KC_HTTP_RELATIVE_PATH: /auth
      KC_HOSTNAME_STRICT_HTTPS: "false"
      JAVA_OPTS_APPEND: "-Dkeycloak.migration.action=import -Dkeycloak.migration.provider=dir -Dkeycloak.migration.dir=/import -Dkeycloak.migration.strategy=IGNORE_EXISTING"
    volumes:
      - ./import:/import
      - ./providers/:/opt/keycloak/providers/
    command: ["start --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false"]
```

5. run keycloak server, im using docker compose
6. go into admin console /auth , then into 'providers' section 
7. add 'apple' provider to a realm
8. you will no see 'additional' extrra properties from social jar, its here , for example this control ` <input ng-model="identityProvider.config.teamId" id="teamId" class="form-control" required/>`  , the source:https://github.com/klausbetz/apple-identity-provider-keycloak/blob/main/src/main/resources/theme-resources/resources/partials/realm-identity-provider-apple.html

Whats wrong? .. i used kc.sh build, itsnt help me.

The same troubles with other images
    image: quay.io/keycloak/keycloak:19.0.1
    image: quay.io/keycloak/keycloak:17.0.1
    image: quay.io/keycloak/keycloak:19.0.2

Maybe its quarkus problem, 
please help ;)
