### ISSUE TITLE
SPI x509cert-lookup ignores certification validation against a truststore

### ISSUE THREAD

**Issue by mpromny** [keycloak/keycloak#16193]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

It seems that x509cert-lookup spi should check whether client certificate has been issued by CA, which  has been added to the truststore.

In case of a negative answer, such request should be rejected.
Currently, spi only generates a WARN message and performs further authentication.

 ```
 18:19:32,514 DEBUG [org.keycloak.services.x509.AbstractClientCertificateFromHttpHeadersLookup] (default task-18) Found a valid x.509 certificate in "ssl-client-cert" HTTP header
18:19:32,514 DEBUG [org.keycloak.services.x509.NginxProxySslClientCertificateLookup] (default task-18) End user certificate found : Subject DN=[CN=client.example.com]  SerialNumber=[2]
18:19:32,514 WARN  [org.keycloak.services.x509.NginxProxySslClientCertificateLookup] (default task-18) No issuer certificate for certificate in certification path found.
18:19:32,514 INFO  [org.keycloak.services.x509.NginxProxySslClientCertificateLookup] (default task-18) Impossible to rebuild end user cert chain : client certificate authentication will fail.
18:19:32,515 DEBUG [org.keycloak.services] (default task-18) [X509ClientCertificateAuthenticator:authenticate] Matched CN=client.example.com certificate.
18:19:32,515 DEBUG [org.keycloak.authentication.ClientAuthenticationFlow] (default task-18) client authenticator SUCCESS: client-x509
18:19:32,515 DEBUG [org.keycloak.authentication.ClientAuthenticationFlow] (default task-18) Client client authenticated by client-x509
```

Code:
https://github.com/keycloak/keycloak/blob/16.0.0/services/src/main/java/org/keycloak/services/x509/NginxProxySslClientCertificateLookup.java

### Version

16.0.0

### Expected behavior

in case of a negative check, the query should be rejected as in the case of missing truststore 

### Actual behavior

Currently, x509cert-lookup spi generates only a warning: 
```
WARN  [org.keycloak.services.x509.NginxProxySslClientCertificateLookup] (default task-18) No issuer certificate for certificate in certification path found.
INFO  [org.keycloak.services.x509.NginxProxySslClientCertificateLookup] (default task-18) Impossible to rebuild end user cert chain : client certificate authentication will fail.
```

### How to Reproduce?

Initial configuration (K8s + Istio):

1) Create `truststore.jks` and don't add `CA` cert used to sign `client cert` to the ``truststore.jks`:

- `keytool -genkey -alias test -keyalg RSA -keystore truststore.jks -validity 10950`

2) Add the below posted config to the `Keycloak`
```
#x509cert-lookup spi configuration
/subsystem=keycloak-server/spi=x509cert-lookup:write-attribute(name=default-provider, value=nginx)
/subsystem=keycloak-server/spi=x509cert-lookup/provider=nginx:add(enabled=true, properties={sslClientCert=ssl-client-cert, sslCertChainPrefix=cert-chain, certificateChainLength=3}

#truststore configuration
/subsystem=keycloak-server/spi=truststore/:add()
/subsystem=keycloak-server/spi=truststore/provider=file/:add(enabled=true,properties={ \
    file => "/opt/jboss/keycloak/standalone/configuration/keystores/truststore.jks", \
    password => "password", \
    hostname-verification-policy => "STRICT", \
disabled => "false"})
```
3) Add Istio Ingress Gateway
```
      -   enabled: true
          name: istio-ingressgateway-test
          label:
              app: istio-ingressgateway-test
          k8s:
              serviceAnnotations:
              service:
                  type: LoadBalancer
```
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
    name: gateway-test
    namespace: istio-system
spec:
    selector:
        app: istio-ingressgateway-test
    servers:
        - port:
              number: 443
              name: https
              protocol: HTTPS
          hosts:
              - '*'
          tls:
              mode: MUTUAL
              credentialName: mtls-test
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
    name: vs-test
    namespace: default
spec:
    hosts:
        - "*"
    gateways:
        - istio-system/gateway-test
    http:
        - route:
              - destination:
                    host: keycloak.default.svc.cluster.local
                    port:
                        number: 8080
                headers:
                    request:
                        set:
                            ssl-client-cert: "%DOWNSTREAM_PEER_CERT%"
    
```                            
4) Add client `client` to the KC
- Client Authenticator: X509 certificate
-- Direct Grant Flow: X509
---  Authentication: X509/Username

5) Send request to the KC via service that will add `ssl-client-cert` header with a client certificate
`curl -v -X POST https://test.example.com/auth/realms/master/protocol/openid-connect/token --data "client_id=client" --data "grant_type=client_credentials" --cacert ca.pem --cert ./client.crt --key ./client.key  `
