### ISSUE TITLE
Backchannel URL rewriting skips port if hostname matches KC_HOSTNAME

### ISSUE THREAD

**Issue by jblachly** [keycloak/keycloak#16301]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

Backchannel URLs are by default rewritten according to the incoming `Host` header. This can be optionally disabled with `--hostname-strict-backchannel=true`. By way of an example, retrieving the open-id configuration from `http://keycloak:8080/realms/vv-prod/.well-known/openid-configuration` with curl yields:

```
{"issuer":"https://auth/realms/vv-prod","authorization_endpoint":"https://auth/realms/vv-prod/protocol/openid-connect/auth","token_endpoint":"http://keycloak:8080/realms/vv-prod/protocol/openid-connect/token","introspection_endpoint":"http://keycloak:8080/realms/vv-prod/protocol/openid-connect/token/introspect","userinfo_endpoint":"http://keycloak:8080/realms/vv-prod/protocol/openid-connect/userinfo",...
```

when `KC_HOSTNAME=auth`. Note that some URLs are written as `https://auth/`, while backchannel-able URLs, like `token_endpoint`, are rewritten according to the `Host` header (`keycloak:8080`, in this case, since that is one of the hostname aliases on my docker network. **NOTE THE INCLUSION OF PORT NUMBER**).

The problem is that I had set my internal services to also use the `auth` name for backchannel, private-network requests, but when requesting URL `http://auth:8080/realms/vv-prod/.well-known/openid-configuration`, the port is stripped off (or more likely, backchannel-able URLs are just not rewritten at all):

```
{"issuer":"https://auth/realms/vv-prod","authorization_endpoint":"https://auth/realms/vv-prod/protocol/openid-connect/auth","token_endpoint":"https://auth/realms/vv-prod/protocol/openid-connect/token","introspection_endpoint":"https://auth/realms/vv-prod/protocol/openid-connect/token/introspect","userinfo_endpoint":"https://auth/realms/vv-prod/protocol/openid-connect/userinfo","end_session_endpoint":"https://auth/realms/vv-prod/protocol/openid-connect/logout","frontchannel_logout_session_supported":true,"frontchannel_logout_supported":true,"jwks_uri":...
```

This is problematic, because my internal services must access Keycloak through backchannel URLs, but keycloak is only listening on 8080/8443 on the internal network. In the meantime, I can set the internal network services to use a hostname alias.

(NOTE: for completeness, of course I am using proxy=edge mode)

### Version

20.0.0

### Expected behavior

I expect that when the `Host` header matches `<KC_HOSTNAME>:<port that's not 80 or 443>` for backchannel-able URLs to still be rewritten, just as they are when `Host` header matches `<anything other than KC_HOSTNAME>:<port>`

### Actual behavior

Backchannel URLs are not rewritten if the host-part, excluding port, of the `Host` header matches `KC_HOSTNAME`

### How to Reproduce?

Example docker-compose fragment included; the build `Dockerfile.example` is taken verbatim from the Keycloak documentation

```
    #image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    build:
      context: keycloak
      dockerfile: Dockerfile.example
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 2s
      retries: 15
    depends_on:
      - postgres
    environment:
      # Keycloak Docker-only options
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      # Keycloak Java options
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_PROXY=edge
      - KC_HOSTNAME=${KEYCLOAK_HOSTNAME}
      - KC_HOSTNAME_STRICT_BACKCHANNEL=false
    command: start
    networks:
      backend-net:
        aliases:
          - auth
      traefik:
        aliases:
          - auth
```
