### ISSUE TITLE
LDAP Federation -> User Sync does not work in combination with the new map-storage.

### ISSUE THREAD

**Issue by GerDner** [keycloak/keycloak#16366]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

ldap

### Describe the bug

Feature enabled: map-storage

DB: postgres/cockroachdb via jdbc url.

Version tested: 19.0.0-20.0.2 + nightly

LDAP Server used: OpenLdap.

The "Sync all Users" and the "Sync changed Users" method in the admin ui return a "Could not sync users: 'HTTP 404 Not Found'" Response. The admin api, the account api and other backend functionalities are working fine. So it's no hostname issue. 

The called url looks like this: `http://localhost:8080/admin/realms/master/user-storage/36b183b1-92ff-48cc-96af-f5e4382e3b14/sync?action=triggerFullSync`

The Exception is thrown here: https://github.com/keycloak/keycloak/blob/022d2864a6fa71bd97c6f4ac86de178f8bdcfbd6/services/src/main/java/org/keycloak/services/resources/admin/RealmAdminResource.java#L519

The Error suggests that something is not found. I'm not a java guy but from what i can see the functionality for ldap sync + map-storage is not implemented yet? Or am i missing something?
Then the Error-Message could be improved?

User Sync us working fine with legacy storage. But then cockroachdb is not supported.

Keycloak Debug Log
```
keycloak-keycloak-1  | 2023-01-10 13:55:31,140 DEBUG [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Error response 404: javax.ws.rs.NotFoundException: HTTP 404 Not Found
keycloak-keycloak-1  |  at org.keycloak.services.resources.admin.RealmAdminResource.extension(RealmAdminResource.java:519)
keycloak-keycloak-1  |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
keycloak-keycloak-1  |  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
keycloak-keycloak-1  |  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
keycloak-keycloak-1  |  at java.base/java.lang.reflect.Method.invoke(Method.java:568)
keycloak-keycloak-1  |  at org.jboss.resteasy.core.ResourceLocatorInvoker.constructLocator(ResourceLocatorInvoker.java:107)
keycloak-keycloak-1  |  at org.jboss.resteasy.core.ResourceLocatorInvoker.resolveTargetFromLocator(ResourceLocatorInvoker.java:87)
keycloak-keycloak-1  |  at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:148)
keycloak-keycloak-1  |  at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
keycloak-keycloak-1  |  at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:152)
keycloak-keycloak-1  |  at org.jboss.resteasy.core.ResourceLocatorInvoker.invokeOnTargetObject(ResourceLocatorInvoker.java:183)
keycloak-keycloak-1  |  at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:141)
keycloak-keycloak-1  |  at org.jboss.resteasy.core.ResourceLocatorInvoker.invoke(ResourceLocatorInvoker.java:32)
keycloak-keycloak-1  |  at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
keycloak-keycloak-1  |  at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
keycloak-keycloak-1  |  at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
keycloak-keycloak-1  |  at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
keycloak-keycloak-1  |  at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
keycloak-keycloak-1  |  at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
keycloak-keycloak-1  |  at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
keycloak-keycloak-1  |  at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
keycloak-keycloak-1  |  at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:82)
keycloak-keycloak-1  |  at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.handle(VertxRequestHandler.java:42)
keycloak-keycloak-1  |  at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
keycloak-keycloak-1  |  at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
keycloak-keycloak-1  |  at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
keycloak-keycloak-1  |  at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:84)
keycloak-keycloak-1  |  at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:71)
keycloak-keycloak-1  |  at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
keycloak-keycloak-1  |  at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
keycloak-keycloak-1  |  at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
keycloak-keycloak-1  |  at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:430)
keycloak-keycloak-1  |  at io.quarkus.vertx.http.runtime.VertxHttpRecorder$6.handle(VertxHttpRecorder.java:408)
keycloak-keycloak-1  |  at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1284)
keycloak-keycloak-1  |  at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:173)
keycloak-keycloak-1  |  at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:140)
keycloak-keycloak-1  |  at org.keycloak.quarkus.runtime.integration.web.QuarkusRequestFilter.lambda$createBlockingHandler$0(QuarkusRequestFilter.java:82)
keycloak-keycloak-1  |  at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
keycloak-keycloak-1  |  at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
keycloak-keycloak-1  |  at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
keycloak-keycloak-1  |  at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
keycloak-keycloak-1  |  at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
keycloak-keycloak-1  |  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
keycloak-keycloak-1  |  at java.base/java.lang.Thread.run(Thread.java:833)
```

### Version

20.0.2

### Expected behavior

The User are synced or an error message indicating that this not (yet) supported is thrown.

### Actual behavior

API returns an 404 not found error indicating that a resource was not found which is missleading in my opinion.

### How to Reproduce?

Spin up a testsetup in docker-compose like this and configure federation for ldap. Then try to sync users.

```yaml
version: '3.6'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    ports: 
      - "8080:8080"
    environment:
      KC_HOSTNAME_URL: "http://localhost:8080"
      KC_LOG_LEVEL: debug
      KC_DB: postgres
      KC_DB_URL:  "jdbc:postgresql://cockroach:26257/defaultdb"
      KC_DB_USERNAME: root
      KC_FEATURES: token-exchange,map-storage
      KC_STORAGE: jpa

  cockroach:
    container_name: cockroach
    image: cockroachdb/cockroach:latest
    volumes:
      - /tmp/data/node_1:/cockroach/cockroach-data
    command: start-single-node --insecure
    ports:
      - '26257:26257'
      - '9800:8080'

  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Example Inc."
      LDAP_DOMAIN: "example.org"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - /var/lib/ldap
      - /etc/ldap/slapd.d
      - /container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    # For replication to work correctly, domainname and hostname must be
    # set correctly so that "hostname"."domainname" equates to the
    # fully-qualified domain name for the host.
    domainname: "example.org"
    hostname: "ldap-server"
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "9000:80"
    depends_on:
      - openldap
```
