### ISSUE TITLE
http-relative-path is not working

### ISSUE THREAD

**Issue by nrobert13** [keycloak/keycloak#16605]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

I cannot get keycloak to work with `http-relative-path`. I have the following in the pod:

```
bash-4.4$ env | grep -Ei "health|relative"
KC_HEALTH_ENABLED=true
KC_HTTP_RELATIVE_PATH=/auth
bash-4.4$
```
The operator seem to add the correct health endpoints, but because keycloak is not serving there, had to overwrite.

### Version

20.0.3

### Expected behavior

```
bash-4.4$ /opt/keycloak/bin//kcadm.sh config credentials --server http://localhost:8080/auth --realm <realm> --user <user>
Logging into http://localhost:8080/auth as user <user> of realm <realm>
Enter password: ********************


bash-4.4$ curl -k https://127.0.0.1:8443/auth/health/live
{
    "status": "UP",
    "checks": [
    ]
}
bash-4.4$
```

### Actual behavior

```
bash-4.4$ /opt/keycloak/bin//kcadm.sh config credentials --server http://localhost:8080/auth --realm <realm> --user <user>
Logging into http://localhost:8080/auth as user <user> of realm <realm>
Enter password: ********************
null [RESTEASY003210: Could not find resource for full path: http://localhost:8080/auth/realms/<realm>/protocol/openid-connect/token]

bash-4.4$ /opt/keycloak/bin//kcadm.sh config credentials --server http://localhost:8080/ --realm <realm> --user <user>
Logging into http://localhost:8080/ as user <user> of realm <realm>
Enter password: ********************

bash-4.4$ curl -k https://127.0.0.1:8443/auth/health/live
{"error":"RESTEASY003210: Could not find resource for full path: https://127.0.0.1:8443/auth/health/live"}
bash-4.4$ curl -k https://127.0.0.1:8443/health/live
{
    "status": "UP",
    "checks": [
    ]
}
bash-4.4$
```

### How to Reproduce?

deploy keycloak with the operator using:
```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 2
  image: keycloak/keycloak:20.0.3
  db:
    vendor: postgres
    host: {{ $db_name }}
    usernameSecret:
      name: "<db_user>"
      key: username
    passwordSecret:
      name: "<db_pass>"
      key: password
  http:
    httpEnabled: true
    httpPort: 8080
    httpsPort: 8443
    tlsSecret: "keycloak-backend-tls"
  hostname:
    hostname: {{ .Values.keycloak.ingress.host }}
  ingress:
    enabled: false
  unsupported:
    podTemplate:
      spec:
        containers:
        - livenessProbe:
            exec:
              command:
              - curl
              - --head
              - --fail
              - --silent
              - --insecure
              - https://127.0.0.1:8443/health/live
            failureThreshold: 150
            initialDelaySeconds: 20
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            exec:
              command:
              - curl
              - --head
              - --fail
              - --silent
              - --insecure
              - https://127.0.0.1:8443/health/ready
            failureThreshold: 250
            initialDelaySeconds: 20
            periodSeconds: 2
            successThreshold: 1
            timeoutSeconds: 1
  additionalOptions:
  - name: spi-theme-default
    value: syseleven
  - name: spi-theme-welcome-theme
    value: syseleven
  - name: http-relative-path
    value: "/auth"
```

**Comment by nrobert13** [comment]
this seems to be a problem only in prod mode. I couldn't reproduce it in dev mode. here's a docker-compose to reproduce it:
```
version: "3.9"
services:
  database:
    image: postgres:13-alpine
    container_name: kc-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak
    networks:
      - keycloak
  keycloak:
    image: keycloak/keycloak:20.0.3
    container_name: keycloak
    ports:
      - 8080:8080
      - 8443:8443
    command:
      - start
      - --optimized
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_HTTP_RELATIVE_PATH: /auth
      KC_HTTP_ENABLED: true
      KC_HOSTNAME: <your_preferred_hostname>
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL_HOST: database
      KC_HTTPS_CERTIFICATE_FILE: /cert/tls.crt
      KC_HTTPS_CERTIFICATE_KEY_FILE: /cert/tls.key
    volumes:
      - ${PWD}/tls.crt:/cert/tls.crt
      - ${PWD}/tls.key:/cert/tls.key
    networks:
      - keycloak
networks:
  keycloak: {}
```

and the simply try with `/auth` and will fail.
```
# docker exec -i keycloak /opt/keycloak/bin/kcadm.sh config credentials --server http://localhost:8080/auth --realm master --user admin
Logging into http://localhost:8080/auth as user admin of realm master
Enter password: admin
*****
null [RESTEASY003210: Could not find resource for full path: http://localhost:8080/auth/realms/master/protocol/openid-connect/token]
```
and succeeds without `/auth`:
```
docker exec -i keycloak /opt/keycloak/bin/kcadm.sh config credentials --server http://localhost:8080 --realm master --user admin
Logging into http://localhost:8080 as user admin of realm master
Enter password: admin
*****
```
