### ISSUE TITLE
Cannot insert duplicate key in object

### ISSUE THREAD

**Issue by rezaokhravi** [keycloak/keycloak#16845]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

core

### Describe the bug

Hi
when run again docker-compose file , then occurred error duplicate key in object .
" Violation of UNIQUE KEY constraint 'UK_CLI_SCOPE'. Cannot insert duplicate key in object 'dbo.CLIENT_SCOPE' ".

```
version: '3.6'
services:
  mssqldb:
    container_name: mssqldb
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    ports:
      - 1430:1433
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Aa123456
      MSSQL_PID: Express
    volumes:
      - ./mssql_data:/var/opt/mssql/data
  mssqlscripts:
    container_name: mssqlscripts
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - mssqldb
    command: /bin/bash -c 'until /opt/mssql-tools/bin/sqlcmd -S mssqldb -U sa -P "Aa123456" -Q "if not exists (select database_id from sys.databases where name like "keyclock") create database keyclock"'
  keyclock:
    container_name: keyclock
    image: quay.io/keycloak/keycloak:20.0.3
    restart: unless-stopped
    depends_on:
      - mssqldb
      - mssqlscripts
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Aa123456
      KC_DB: mssql
      KC_DB_URL: jdbc:sqlserver://mssqldb:1433;databaseName=keyclock;integratedSecurity=false;encrypt=false;trustServerCertificate=true;
      KC_DB_USERNAME: sa
      KC_DB_PASSWORD: Aa123456
    entrypoint: [ "/opt/keycloak/bin/kc.sh", "start-dev" ]
```

### Version

20.0.3

### Expected behavior

run  without error

### Actual behavior

occurred error :
" Violation of UNIQUE KEY constraint 'UK_CLI_SCOPE'. Cannot insert duplicate key in object 'dbo.CLIENT_SCOPE' ".

### How to Reproduce?

check database exist
