### ISSUE TITLE
Standalone: reboot/restart of Keycloak leads to users having to log-in again

### ISSUE THREAD

**Issue by croneter** [keycloak/keycloak#16877]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

I've been trying for hours but can't get this to work. I have Keycloak running in a single containeron Kubernetes. It's a home set-up; there is only 1 node, only 1 Keycloak instance. Whatever I do, Keycloak forgets which users logged in if I reboot the container. 

I messed around with the Infinispan setting; unsuccessfully. 

https://www.keycloak.org/server/caching is not helping at all. Yes I did try `cache = local`. 

How do I manage to e.g. mount Keycloak's cache directory to my host in order for user sessions to survive a re-setup of the Keycloak containr?

Many thanks for any pointers!!

### Version

20.0.3

### Expected behavior

I expect the documentation of Keycloak to tell me how to persist user session on Keycloak reboot

### Actual behavior

Users need to log in again if I reboot the Keycloak container

### How to Reproduce?

E.g. when using flux, use this `release.yaml`
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: keycloak
  namespace: keycloak
spec:
  releaseName: keycloak
  chart:
    spec:
      chart: keycloak
      version: 13.0.x
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 15m
  timeout: 5m
  values:
    auth:
      adminUser: admin
      existingSecret: keycloak-secrets
      passwordSecretKey: keycloak-admin-password
    postgresql:
      auth:
        username: keycloak
        existingSecret: postgresql-secrets
    service:
      type: ClusterIP
      ports:
        http: 80
    production: true
    proxy: edge
    extraEnvVars:
      # https://www.keycloak.org/server/hostname
      - name: KC_HOSTNAME_URL
        value: https://keycloak.${hostname}
      - name: KC_HOSTNAME_ADMIN_URL
        value: https://keycloak.${hostname}
      - name: KC_CACHE
        value: local
    logging:
      level: DEBUG
    cache:
      enabled: false
    extraVolumes:
      - name: keycloak-tokens
        hostPath:
          path: ${hostPathConfig}/keycloak
          type: Directory
    extraVolumeMounts:
      - name: keycloak-tokens
        mountPath: /opt/bitnami/keycloak/cache
```
