### ISSUE TITLE
Cannot access admin ui 403 and perpetual loading spinner

### ISSUE THREAD

**Issue by nigel-f-wilson** [keycloak/keycloak#17137]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

This seems related to some of this issues under this [umbrella issue](https://github.com/keycloak/keycloak/issues/14666), but none of the advice here worked for us.

### Area

admin/ui

### Describe the bug

We cannot access the Admin UI. After a recent upgrade it fails to initialize and we are presented with a perpetual loading spinner.  Everything was working properly with version 17.0.0

We recently built new container images and upgraded to 18.0.2 and then 19.0.3 and then 20.0.3. Through that process we encountered  a few different errors. 

### Upon upgrading to 18.0.2

- Login to the application still worked as expected but the new confirm logout flow did not. Clicking logout in our application took me to the expected confirm logout screen, but then clicking “confirm logout” resulted in a 400 Bad Request error, and a message warning that `redirect_uri` was an invalid parameter.
- I was not able to access the admin panel due to a 400 Bad Request error, and go the same message warning that `redirect_uri` was an invalid parameter.

### Upon upgrading to 19.0.3 (including the JavaScript adapter)

- Login to our app still worked as expected
- Now the confirm logout flow also works
- Still no access to the Admin UI but we started getting a different error, a 403 Forbidden.  We have debug level logs enabled but nothing is being generated regarding these requests. 
Upon upgrading to 20.0.3 we saw the same results as with 19.0.3, which led me to suspect that the problem was somewhere in the migration changes from 17 to 18. That led me to try disabling step-up authentication but that did not make a difference.

### Version

18.0.2, 19.0.3, 20.0.3

### Expected behavior

Clicking the link to the Administration Console on the Keycloak welcome page should open the Admin UI.

### Actual behavior

Instead, we are presented with a loading spinner that never goes away. In the Network tab it can be seen that there is a 403 forbidden error.
<img width="505" alt="keycloak 403 error" src="https://user-images.githubusercontent.com/45880776/219206929-bf7374ae-8511-4274-9883-c84e9fd6209a.png">

### How to Reproduce?

We run Keycloak as a Nomad job behind a Traefik reverse proxy.  It is configured with Salt and there is one other change that could be affecting the v17 -> v18 upgrade, we transitioned from using exclusively Environment Variables to a mix on Environment Variables and Image Args

Configuration used with v17
```
      env:
        DB_TYPE: postgres
        DB_URL: XXXX
        DB_USERNAME: XXX
        PROXY_TYPE: edge
        HOSTNAME: {{ host.hostnames[0] }}
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: XXXX
        DB_PASSWORD: XXXX

```
Configuration used with v18 and up
```
      image_args:
        - "--db=postgres"
        - "--db-url=XXXX"
        - "--db-username=XXXX"
        - "--db-password=XXX"
        - "--proxy=edge"
        - "--hostname=auth.ourdomain.com"
        - "--log-level=debug"
        - "--spi-events-listener-jboss-logging-success-level=debug"
        - "--spi-events-listener-jboss-logging-error-level=debug"
        - "--spi-connections-jpa-default-migration-strategy=update"
      env:
        KEYCLOAK_ADMIN: XXXX
        KEYCLOAK_ADMIN_PASSWORD: XXXX
```

Other flags that we have experimented with that have not helped so far:
```
- "--hostname-strict-https=false"
- "--spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true"
- "--features-disabled=step-up-authentication"
```

### Anything else?

From what I've read it seems like this might have something to do with needing the X-Forwarded-* headers on Traefik but I don't know how I can be sure if that is the problem.
