### ISSUE TITLE
Kubernetes Deployment gets 401

### ISSUE THREAD

**Issue by ZinkNotTheMetal** [keycloak/keycloak#17222]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

infinispan

### Describe the bug

Getting the following error when scaling up to multiple instances.

![image](https://user-images.githubusercontent.com/6002111/220402126-357b864a-4646-45ad-ba70-898ba8c91f76.png)

Using a basic helm chart which I will post below

```yaml
#Deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/opt/keycloak/bin/kc.sh"]
          args: ["start","--optimized", "--hostname-strict-https=false"]
          env:
            {{- range $k, $v := .Values.env }}
              - name: {{ $k }}
                value: {{ $v | quote }}
            {{ end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.containerPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```

## Notice this
command: ["/opt/keycloak/bin/kc.sh"]
args: ["start","--optimized", "--hostname-strict-https=false"]

```yaml
# values.yaml
image:
  repository: <ourregistry>/keycloak
  pullPolicy: Always
  tag: "20.0.3"

imagePullSecrets: [{ name: "registry-auth" }]

# Liveness Probe informs Azure that the container is alive (but not necessarily ready for traffic to send yet)
# Readiness and Liveness values should not be the same
livenessProbe:
  httpGet:
    path: /health/live
    port: http
  initialDelaySeconds: 90
# Readiness Probe informs Azure that the container is ready for traffic
# Readiness and Liveness values should not be the same
# Application / API should implement an endpoint to return a JSON object to help identify why the application is not ready as this helps the
#  Azure team and development teams better debug what is going on
readinessProbe:
  httpGet:
    path: /health/ready
    port: http
  initialDelaySeconds: 90

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  servicePort: 8080
  containerPort: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-buffering: "On"
    nginx.ingress.kubernetes.io/proxy-buffers: "4"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"

nodeSelector: {}

tolerations: []

affinity: {}

```

```yaml
# values.pd.yaml
replicaCount: 3

# Helpers.tpl (line 76)
environment: Production

env:
  PROXY_ADDRESS_FORWARDING: true
  KC_PROXY: "edge"
  KC_HOSTNAME: <my domain>
  KC_HOSTNAME_STRICT_HTTPS: false
  KC_DB: postgres
  KC_DB_USERNAME: "" # Retrieve from Prod Keyvault
  KC_DB_PASSWORD: "" # Retrieve from Prod Keyvault
  KC_DB_URL_HOST: "" # Retrieve from Prod Terraform
  KC_DB_URL_PORT: 5432
  KC_DB_SCHEMA: "public"
  KC_DB_URL_DATABASE: keycloak
  KC_TRANSACTION_XA_ENABLED: true
  KEYCLOAK_ADMIN: "" # Retrieve from Prod Keyvault
  KEYCLOAK_ADMIN_PASSWORD: "" # Retrieve from Prod Keyvault
  WEBSITES_PORT: 8080

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: "500m"
    memory: "1024Mi"
  requests:
    cpu: "300m"
    memory: "1024Mi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-buffering: "On"
    nginx.ingress.kubernetes.io/proxy-buffers: "4"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"

```

### Version

20.0.3

### Expected behavior

Scaling to multiple instances works as expected with no errors

### Actual behavior

Screen shot

![image](https://user-images.githubusercontent.com/6002111/220402399-67d79e94-050c-415f-a520-c4019a62ce8d.png)

when trying to add clients

### How to Reproduce?

Use a basic helm chart to deploy a custom image of keycloak

```dockerfile
# Documentation:
#  https://www.keycloak.org/server/containers
ARG KEYCLOAK_VERSION

FROM quay.io/keycloak/keycloak:$KEYCLOAK_VERSION as builder

# Enable health and metrics support
#  https://www.keycloak.org/server/health
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

# Configure postgres database vendor
ENV KC_DB=postgres

ENV KC_FEATURES=token-exchange

WORKDIR /opt/keycloak

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:$KEYCLOAK_VERSION
COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```

### Anything else?

Additional issues trying to login:

![image](https://user-images.githubusercontent.com/6002111/220403730-3e9ce76b-1b3d-4c42-9c35-d8c363b4f9d7.png)
