### ISSUE TITLE
Keycloak 21 and Istio 1.17 return 401 Invalid Token - Jwt issuer is not configured

### ISSUE THREAD

**Issue by jonathanvila** [keycloak/keycloak#17299]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

authentication

### Describe the bug

I have installed istio and keycloak (ns keycloak) in a minikube.

Created a RequestAuthentication and a AuthorizationPolicy:
```yaml
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: requestauth
  namespace: default
spec:
  selector:
    matchLabels:
      app: quarkus
  jwtRules:
    - issuer: "http://keycloak.keycloak.svc.cluster.local:8080/realms/demo"
      jwksUri: "http://keycloak.keycloak.svc.cluster.local:8080/realms/demo/protocol/openid-connect/certs"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: authpolicy
  namespace: default
spec:
  selector:
    matchLabels:
      app: quarkus
  rules:
  - from:
    - source:
        requestPrincipals: ["*"]
```
And after getting the token :

```bash
  curl \
  -sk \
  --data "username=quarkus&password=quarkuspwd&grant_type=password&client_id=istio" \
  https://keycloak.192.168.49.2.nip.io/realms/demo/protocol/openid-connect/token \ 
  | jq ".access_token"
```

I do a call to my service :

```bash
curl -sv -H "Authorization: Bearer $token" "http://$GATEWAY_URL/echo/productpage"
```

it always return an error :
```bash
*   Trying 10.98.21.200:80...
* Connected to 10.98.21.200 (10.98.21.200) port 80 (#0)
> GET /echo/productpage HTTP/1.1
> Host: 10.98.21.200
> User-Agent: curl/7.87.0
> Accept: */*
> Authorization: Bearer eyJhbG........
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< www-authenticate: Bearer realm="http://10.98.21.200/echo/productpage", error="invalid_token"
< content-length: 28
< content-type: text/plain
< date: Fri, 24 Feb 2023 17:12:33 GMT
< server: istio-envoy
< 
* Connection #0 to host 10.98.21.200 left intact
Jwt issuer is not configured%         
```

If I send a wrong header in the call :

```bash
curl -sv -H "AuthorizationXX: Bearer $token" "http://$GATEWAY_URL/echo/productpage"
```

**I receive as expected** , an RBAC error:

```bash
* Mark bundle as not supporting multiuse
< HTTP/1.1 403 Forbidden
< content-length: 19
< content-type: text/plain
< date: Sun, 26 Feb 2023 11:39:30 GMT
< server: istio-envoy
< x-envoy-upstream-service-time: 14
< 
* Connection #0 to host 10.98.21.200 left intact
RBAC: access denied%                                                                                                                                         
```

### Version

21.0.0

### Expected behavior

Not give the error

### Actual behavior

Gives the error mentioned in the description

### How to Reproduce?

Install istio and keycloak in minikube, then install a simple REST app and create the RequestAuthentication mentioned above
