### ISSUE TITLE
Incorrect Url on Keycloak Health - Liveness and Readiness, no Startup Probes

### ISSUE THREAD

**Issue by MarkCupitt** [keycloak/keycloak#17388]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

operator

### Describe the bug

I have set the Crds for a deployment, and enabled Health using the Additional Options. 
```
    - name: health-enabled
      value: "true"
    - name: metrics-enabled
      value: "true"
```

The pod starts ok, but ends up in a continuous restart loop as the readiness probe is never satisfied

Looking at the deployed probes, I see an error in the url `http://:8080//health/live` mnnote the `//` before health path

![image](https://user-images.githubusercontent.com/5503184/222336776-84b71431-6192-4c72-90c1-501cadb5de8d.png)

### Version

21.0.0

### Expected behavior

Health Probes should work, we should see a startup probe

### Actual behavior

Health Probes sdo not work, we do not see a startup probe

### How to Reproduce?

As described above in the CRD

**Comment by MarkCupitt** [comment]
I have been able to apply a workaround using the `unsupported` -> `podTemplate` (Pretty cool to help sort out issues temporarily :) ) as follows (I added a `startupProbe` as well just for grins)

```
  unsupported:
    podTemplate:
      spec:
        containers:
          - 
            livenessProbe:
              httpGet:
                path: /health/live
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 20
              periodSeconds: 2
              successThreshold: 1
              timeoutSeconds: 1
              failureThreshold: 150

            readinessProbe:
              httpGet:
                path: /health/ready
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 20
              periodSeconds: 2
              successThreshold: 1
              timeoutSeconds: 1
              failureThreshold: 250

            startupProbe:
              httpGet:
                path: /health/ready
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 60
              periodSeconds: 2
              successThreshold: 1
              timeoutSeconds: 1
              failureThreshold: 250
```
