### ISSUE TITLE
Permissions tab in Client settings disappeared in 21.0 update

### ISSUE THREAD

**Issue by PlutoHDDev** [keycloak/keycloak#17446]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

Since the update from Keycloak version 20 to 21, the Permissions tab under Clients > Client details > Permissions has disappeared which is required to set up token exchange. We have enabled this preview feature as you can see in the `docker-compose.yml` below. When downgrading to 20.0, the tab appears again.

```
keycloak:
      container_name: keycloak
      image: quay.io/keycloak/keycloak:latest
      volumes:
        - /docker/keycloak/providers:/opt/keycloak/providers
      environment:
        JAVA_OPTS_APPEND: "-Dkeycloak.profile=preview -Dkeycloak.profile.feature.scripts=enabled -Dkeycloak.profile.feature.token_exchange=enabled -Dkeycloak.profile.feature.admin_fine_grained_authz=enabled -Dkeycloak.profile.feature.impersonation=enabled"
        KC_FEATURE: account-api,account2,admin-api,admin2,authorization,ciba,client-policies,impersonation,js-adapter,par,step-up-authentication,web-authn,token_exchange,admin_fine_grained_authz
        KC_PROXY: passthrough
        KC_HOSTNAME: *...*
        KC_HTTP_ENABLED: true
        KC_HTTP_PORT: 8010
        KC_DB: postgres
        KC_DB_URL_HOST: postgres
        KC_DB_USERNAME: keycloak
        KC_DB_SCHEMA: public
        KC_DB_PASSWORD:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD:
      ports:
        - 8010:8010
      depends_on:
        - postgres
      command:
        - start-dev
      restart: unless-stopped
```

### Version

21.0

### Expected behavior

As in version 20.0, there should be a tab Clients > Client details > Permissions with a toggle `Permissions enabled` and a `Permission list`.

### Actual behavior

In version 21.0, there is no Permissions tab in the Client settings.

### How to Reproduce?

Enable the preview features, create a Client and compare the admin interfaces of version 20.0 and 21.0.
