### ISSUE TITLE
Mixed content when wrapped in traefik

### ISSUE THREAD

**Issue by finwo** [keycloak/keycloak#18712]
When running keycloak on docker-swarm and using traefik to provide the SSL reverse proxy, the following problem occurs:

When loading `/auth/admin/master/console/`, `/auth/js/keycloak.js` is loaded using http instead of https (`http://<hostname>/auth/js/keycloak.js`), making the browser refuse it based on mixed content.

Is there a known work-around to make keycloak play nice with an ssl-handling reverse-proxy in front of it?

---

keycloak stack:
```yml
version: '3.8'
services:

  database:
    image: postgres:13
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_USER: keycloak
    volumes:
     - keycloak-postgres:/var/lib/postgresql/data
    networks:
     - default
    logging:
      driver: json-file

  keycloak:
    image: jboss/keycloak:15.0.0
    command:
      - -Djboss.as.management.blocking.timeout=3600
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: **REDACTED**
      KEYCLOAK_HTTP_PORT: 8080
      KEYCLOAK_HTTPS_PORT: 8443
      KEYCLOAK_LOGLEVEL: INFO
      DB_VENDOR: postgres
      DB_ADDR: database
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    logging:
      driver: json-file
    links:
      - database
    networks:
      - default
      - traefik
    restart: unless-stopped
    deploy:
      labels:
        traefik.enable: 'true'
        traefik.http.routers.**REDACTED**.entrypoints: websecure
        traefik.http.routers.**REDACTED**.rule: Host(`**REDACTED**`)
        traefik.http.routers.**REDACTED**.tls.certresolver: letsencryptresolver
        traefik.http.services.**REDACTED**.loadbalancer.server.port: '8080'
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
      resources:
        limits:
          cpus: '1.50'
          memory: 2048M
        reservations:
          cpus: '0.05'
          memory: 128M

networks:
  default:
    driver: overlay
  traefik:
    external: true

volumes:
  keycloak-postgres:
    driver: local
    driver_opts:
      device: **REDACTED**
      o: bind
      type: none
```

Traefik stack:
```yml
version: '3.3'
services:
  reverse-proxy:
    image: traefik:v2.5
    command:
     - --providers.docker.endpoint=unix:///var/run/docker.sock
     - --providers.docker.swarmMode=true
     - --providers.docker.exposedbydefault=false
     - --providers.docker.network=traefik
     - --entrypoints.web.address=:80
     - --entrypoints.websecure.address=:443
     - --certificatesresolvers.letsencryptresolver.acme.httpchallenge=true
     - --certificatesresolvers.letsencryptresolver.acme.httpchallenge.entrypoint=web
     - --certificatesresolvers.letsencryptresolver.acme.email=**REDACTED**
     - --certificatesresolvers.letsencryptresolver.acme.storage=/letsencrypt/acme.json
    ports:
     - 80:80
     - 443:443
    volumes:
     - traefik-certificates:/letsencrypt
     - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
     - traefik
    logging:
      driver: json-file
    deploy:
      labels:
        traefik.enable: 'true'
        traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
        traefik.http.routers.http-catchall.entrypoints: web
        traefik.http.routers.http-catchall.middlewares: redirect-to-https@docker
        traefik.http.routers.http-catchall.rule: hostregexp(`{host:.+}`)
        traefik.http.services.http-catchall.loadbalancer.server.port: '80'
      placement:
        constraints:
         - node.role == manager
networks:
  traefik:
    external: true
volumes:
  traefik-certificates:
```
