### ISSUE TITLE
[JGroups/Infinispan] Sometimes failed to form jdbc_ping based Keycloak cluster mode in dual stack (IPv6 preferred)

### ISSUE THREAD

**Issue by Alpenbelieve** [keycloak/keycloak#19610]
### Before reporting an issue

- [X] I have searched existing issues
- [ ] I have reproduced the issue with the latest release

### Area

dist/quarkus

### Describe the bug

Hi, I've encountered a problem about cluster mode when I used Keycloak 20.0.3 in K8s.

I have several K8s clusters that have different architectures (arm or amd) and networks (dual stack, IPv4 preferred or IPv6 preferred). I found that in the dual stack (IPv6 preferred) clusters (regardless of architecture arm or amd), sometimes keycloak can't form a cluster. Most of the time I can get a Keycloak cluster, but when I redeploy my application multiple times, once every 5 to 6 times I encounter a situation where Keycloak fails to form a cluster. And this problem doesn't happen in a dual-stack IPv4-first cluster.

When this problem happens, I tried to delete keycloak-1 pod to let it restart and connect to keycloak-0, but it doesn't work. However if I delete keycloak-0 pod, let it restart and connect to keycloak-1 pod, then Keycloak cluster is formed. Why is this happening? Is it because there is something wrong with the discovery mechanism of jgroups on dual stack (IPv6 preferred) ?

Then I search the logs of these 2 pods, and it shows that keycloak-1 pod is sending JOIN to keycloak-0 pod, but it gets a java.net.ConnectException: Connection refused. Meanwhile keycloak-0 has no logs about error reporting.

keycloak-1 pod's log:
![image](https://user-images.githubusercontent.com/18638035/230865499-1f74c67d-0834-432e-9bee-b9ed38b99f37.png)

meanwhile keycloak-0 pod's log (between seconds 19-24 there's no log):
![image](https://user-images.githubusercontent.com/18638035/230865989-b81f582a-f72d-4347-a41f-a4282ee2e17c.png)

This is my configuration (most of the time it configure a Keycloak cluster successfully):

Keycloak statefulset
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: myapp
spec:
  replicas: 2
  serviceName: keycloak
  template:
    spec:
      containers:
      - args:
        - start
        env:
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL_HOST
          value: postgresql
        - name: KC_DB_URL_DATABASE
          value: keycloak
        - name: KC_CACHE_CONFIG_FILE
          value: cache-ispn-jdbc-ping.xml
        - name: JAVA_OPTS_APPEND
          value: -Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true
        - name: KC_HTTP_RELATIVE_PATH
          value: /auth/
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: JGROUPS_DISCOVERY_EXTERNAL_IP
          value: keycloak-discovery.myapp.svc.cluster.local
        - name: KC_HTTP_ENABLED
          value: "true"
        image: quay.io/keycloak/keycloak:20.0.3
        imagePullPolicy: IfNotPresent
        name: keycloak
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        ...
```

keycloak-discovery headless service
```yaml
apiVersion: v1
kind: Service
metadata:
  name: keycloak-discovery
  namespace: myapp
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  publishNotReadyAddresses: true
```

cache-ispn-jdbc-ping.xml (I place this file in /opt/keycloak/conf/)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:11.0 http://www.infinispan.org/schemas/infinispan-config-11.0.xsd"
        xmlns="urn:infinispan:config:11.0">
    <jgroups>
        <stack name="postgres-jdbc-ping-tcp" extends="tcp">
            <TCP external_addr="${env.JGROUPS_DISCOVERY_EXTERNAL_IP:127.0.0.1}" />
            <JDBC_PING connection_driver="org.postgresql.Driver"
                       connection_username="${env.KC_DB_USERNAME}" connection_password="${env.KC_DB_PASSWORD}"
                       connection_url="jdbc:postgresql://${env.KC_DB_URL_HOST}/${env.KC_DB_URL_DATABASE}"
                       initialize_sql="CREATE SCHEMA IF NOT EXISTS ${env.KC_DB_SCHEMA:public}; CREATE TABLE IF NOT EXISTS ${env.KC_DB_SCHEMA:public}.JGROUPSPING (own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, bind_addr varchar(200) NOT NULL, updated timestamp default current_timestamp, ping_data BYTEA, constraint PK_JGROUPSPING PRIMARY KEY (own_addr, cluster_name));"
                       insert_single_sql="INSERT INTO ${env.KC_DB_SCHEMA:public}.JGROUPSPING (own_addr, cluster_name, bind_addr, updated, ping_data) values (?, ?, '${env.JGROUPS_DISCOVERY_EXTERNAL_IP:127.0.0.1}', NOW(), ?);"
                       delete_single_sql="DELETE FROM ${env.KC_DB_SCHEMA:public}.JGROUPSPING WHERE own_addr=? AND cluster_name=?;"
                       select_all_pingdata_sql="SELECT ping_data, own_addr, cluster_name FROM ${env.KC_DB_SCHEMA:public}.JGROUPSPING WHERE cluster_name=?"
                       info_writer_sleep_time="500"
                       remove_all_data_on_view_change="true"
                       stack.combine="REPLACE"
                       stack.position="MPING" />
        </stack>
    </jgroups>

    <cache-container name="keycloak">
        <transport lock-timeout="60000" stack="${env.KC_DB}-jdbc-ping-tcp"/>
        <local-cache name="realms">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <local-cache name="users">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <distributed-cache name="sessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="authenticationSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="offlineSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="clientSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="offlineClientSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="loginFailures" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <local-cache name="authorization">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <replicated-cache name="work">
            <expiration lifespan="-1"/>
        </replicated-cache>
        <local-cache name="keys">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="3600000"/>
            <memory max-count="1000"/>
        </local-cache>
        <distributed-cache name="actionTokens" owners="2">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="-1" lifespan="-1" interval="300000"/>
            <memory max-count="-1"/>
        </distributed-cache>
    </cache-container>
</infinispan>
```

### Version

Keycloak 20.0.3 Quarkus

### Expected behavior

Keycloak cluster should be formed in the dual stack (IPv6 preferred) K8s clusters.

### Actual behavior

Most of the time I can get a Keycloak cluster, but when I redeploy my application multiple times, once every 5 to 6 times I encounter a situation where Keycloak fails to form a cluster. 

### How to Reproduce?

Get a dual stack (IPv6 preferred) K8s cluster, and use the configuration file above, and redeploy (helm uninstall and helm install) Keycloak several times. Every 5 to 6 times, there will be a situation where the 2 Keycloak pod can't form a cluster.
