### ISSUE TITLE
Health Check is not disabled even when you set --heath-enabled as false

### ISSUE THREAD

**Issue by mpaulgreen** [keycloak/keycloak#19654]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

The health check is not disabled even when you disable it. The result is POD never reaches the ready state. Two configuration tested are
```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: sso
  name: example-keycloak
  namespace: keycloak
spec:
  additionalOptions:
    - name: health-enabled
      value: 'false'
  features:
    enabled:
      - fips
  hostname:
    hostname: fipskeycloak.apps.asaro.az-env1.appeng.rhecoeng.com
  http:
    tlsSecret: cluster-cert
  image: 'quay.io/keycloak/keycloak:21.0.2'
  instances: 1
```

and 
```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: sso
  name: example-keycloak
  namespace: keycloak
spec:
  additionalOptions:
    - name: health-enabled
      value: 'false'
  features:
    enabled:
      - fips
  hostname:
    hostname: fipskeycloak.apps.asaro.az-env1.appeng.rhecoeng.com
  http:
    tlsSecret: cluster-cert
  image: 'quay.io/mpaulgreen/keycloak-fips-pod:21.0.2'
  instances: 1
```

### Version

keycloak operator 21.0.2

### Expected behavior

The health check should not be performed as described below

https://www.keycloak.org/server/health

### Actual behavior

The POD is never is ready state

### How to Reproduce?

Deploy the operator 21.0.2 and then execute the spec provided above.
