### ISSUE TITLE
Operator restarts occasionally result in recreation of managed keycloak Statefulset Pods

### ISSUE THREAD

**Issue by raphaelzoellner** [keycloak/keycloak#19725]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

operator

### Describe the bug

When the operator container is restarted occasionally the pod template of the keycloak statefulsets managed by the operator changes which leads to a recreation of the keycloak containers managed by the operator.

I noticed the order of environment variables in the pod template changed, which I think is the reason for the recreation.

Pre operator container restart keycloak statefulset spec:
```yaml
spec:
  ...
  template:
    ...
    spec:
      containers:
      - args:
        - start
        env:
        - name: KC_CACHE_STACK
          value: kubernetes
        - name: KC_CACHE
          value: ispn
        - name: KC_HEALTH_ENABLED
          value: "true"
        - name: KC_PROXY
          value: edge
      ...
```

Post operator container restart keycloak statefulset spec:
```yaml
spec:
  ...
  template:
    ...
    spec:
      containers:
      - args:
        - start
        env:
        - name: KC_CACHE_STACK
          value: kubernetes
        - name: KC_HEALTH_ENABLED
          value: "true"
        - name: KC_CACHE
          value: ispn
        - name: KC_PROXY
          value: edge
      ...
```

### Version

20.0.5

### Expected behavior

Even though the keycloak operator container was restarted, reconciliation should not result in a recreation of the managed keycloak statefulset pods if no configuration was changed.

### Actual behavior

Keycloak Pods are recreated by the operator when it restarts.

### How to Reproduce?

1. Install the keycloak operator in a kubernetes cluster
2. Create a valid Keycloak Resource without specifying the [default configurations](https://github.com/keycloak/keycloak/blob/20.0.5/operator/src/main/java/org/keycloak/operator/Constants.java#L42-L47)
5. Wait until the keycloak StatefulSet is ready and reconciliation of the Keycloak Resource has successfully finished
6. Redeploy the keycloak operator multiple times and notice the order of the environment variables in the Keycloak Statefulset's pod template to change and that keycloak pods are being recreated

### Anything else?

I think the reason for the behavior is that a Map is used for the 
[default configurations](https://github.com/keycloak/keycloak/blob/20.0.5/operator/src/main/java/org/keycloak/operator/Constants.java#L42-L47) 
which does not guarantee order when converted later to a list.
https://github.com/keycloak/keycloak/blob/20.0.5/operator/src/main/java/org/keycloak/operator/controllers/KeycloakDeployment.java#L434-L436
