### ISSUE TITLE
Some environment variables of Dockerfile are been ignored by Statefulset

### ISSUE THREAD

**Issue by mpaulgreen** [keycloak/keycloak#19766]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

In my Dockerfile I have following env vaiables
```
ENV KC_HEALTH_ENABLED=true
ENV KC_DB=postgres
ENV KC_HTTPS_KEY_STORE_FILE=/opt/keycloak/bin/server.keystore
ENV KC_HTTPS_KEY_STORE_PASSWORD=password
ENV KC_HTTPS_TRUST_STORE_FILE=/opt/keycloak/bin/server.truststore
ENV KC_HTTPS_TRUST_STORE_PASSWORD=password
```
The first two are being displayed as part of stateful set, but the last ones are being ignored by stateful set.

### Version

quay.io/keycloak/keycloak:21.0.2

### Expected behavior

All env of Dockerfile needs to be captured by Statefulset

### Actual behavior

The following env variables are being ignored by StatefulSet
```
ENV KC_HTTPS_KEY_STORE_FILE=/opt/keycloak/bin/server.keystore
ENV KC_HTTPS_KEY_STORE_PASSWORD=password
ENV KC_HTTPS_TRUST_STORE_FILE=/opt/keycloak/bin/server.truststore
ENV KC_HTTPS_TRUST_STORE_PASSWORD=password
```

### How to Reproduce?

Use the following to create a custom images of keycloak

```
FROM quay.io/keycloak/keycloak:21.0.2 as builder

ADD files /tmp/files/

ENV KC_HEALTH_ENABLED=true
ENV KC_DB=postgres
ENV KC_HTTPS_KEY_STORE_FILE=/opt/keycloak/bin/server.keystore
ENV KC_HTTPS_KEY_STORE_PASSWORD=password
ENV KC_HTTPS_TRUST_STORE_FILE=/opt/keycloak/bin/server.truststore
ENV KC_HTTPS_TRUST_STORE_PASSWORD=password

WORKDIR /opt/keycloak
RUN cp /tmp/files/*.jar /opt/keycloak/providers/
RUN cp /tmp/files/keycloak-fips.keystore.* /opt/keycloak/bin/
RUN cp /tmp/files/server.* /opt/keycloak/bin/
# RUN cp /tmp/files/keycloak.conf /opt/keycloak/conf/



RUN /opt/keycloak/bin/kc.sh show-config

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:21.0.2
COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```

### Anything else?

https://www.keycloak.org/server/all-config

**Comment by sschu** [comment]
My assumption is the ENV variables are not taken over to the second stage because that stage uses a different base image not containing the ENV variables. Can you try setting the ENV variables in the second stage too to see if that works?

**Comment by andre-nascimento-rh** [comment]
@mpaulgreen ,


I believe @sschu is right. Have you tried what he suggested?

The `Build options` (See again https://www.keycloak.org/server/all-config) take place when happen the Quarkus Re augmentation procedure (which is done when you issue `kc.sh build`). In your case, only on the second stage Keycloak is ready to start, and from then it will consider the `Configuration` options as settings for runtime. HTTP/TLS certificates configuration are `Configuration` options. Therefore, they must be passed by the ENV Variables in the second stage. This is not a bug.

In order to try to help you, I have these assets here in my side. Even showing a `docker-compose` structure, maybe somehow you could adapt to your case there. 

- Dockerfile-v21:

```
FROM quay.io/keycloak/keycloak:21.1.1 as builder

ARG ARG_KC_DB
ARG ARG_KC_METRICS_ENABLED
ARG ARG_KC_HEALTH_ENABLED
ARG ARG_KC_CACHE
ARG ARG_KC_CACHE_STACK
ARG ARG_KC_HTTP_RELATIVE_PATH
ARG ARG_KC_FEATURES
ARG ARG_KC_FEATURES_DISABLED

ENV KC_METRICS_ENABLED=${ARG_KC_METRICS_ENABLED}
ENV KC_DB=${ARG_KC_DB}
ENV KC_FEATURES=${ARG_KC_FEATURES}
ENV KC_FEATURES_DISABLED=${ARG_KC_FEATURES_DISABLED}

RUN /opt/keycloak/bin/kc.sh build


# ==== Second Stage ===================================
FROM registry.access.redhat.com/ubi9-minimal

ARG ARG_JAVA_JDK_TO_INSTALL
ARG ARG_JDK_CACERTS_KEYSTORE_PASSWORD
ARG ARG_TLS_CERTIFICATE_PEM_FILEPATH_WITHIN_KC
ARG ARG_TLS_CERTIFICATE_PEM_FILENAME_FOR_BUILD
ARG ARG_KC_HTTPS_KEY_STORE_FILE
ARG ARG_KC_HTTPS_KEY_STORE_PASSWORD
ARG ARG_KC_HTTPS_TRUST_STORE_FILE
ARG ARG_KC_HTTPS_TRUST_STORE_PASSWORD

ENV ENV_TLS_CERTIFICATE_PEM_FILEPATH_FOR_BUILD=${ARG_TLS_CERTIFICATE_PEM_FILENAME_FOR_BUILD}
ENV ENV_JAVA_JDK_TO_INSTALL=${ARG_JAVA_JDK_TO_INSTALL}
ENV ENV_JDK_CACERTS_KEYSTORE_PASSWORD=${ARG_JDK_CACERTS_KEYSTORE_PASSWORD}
ENV KC_HTTPS_KEY_STORE_FILE=${ARG_KC_HTTPS_KEY_STORE_FILE}
ENV KC_HTTPS_KEY_STORE_PASSWORD=${ARG_KC_HTTPS_KEY_STORE_PASSWORD}
ENV KC_HTTPS_TRUST_STORE_FILE=${ARG_KC_HTTPS_TRUST_STORE_FILE}
ENV KC_HTTPS_TRUST_STORE_PASSWORD=${ARG_KC_HTTPS_TRUST_STORE_PASSWORD}
ENV LANG en_US.UTF-8

COPY --from=builder /opt/keycloak/ /opt/keycloak/

USER root

RUN microdnf upgrade -y \
  && microdnf install -y gettext \
  && microdnf install -y ${ENV_JAVA_JDK_TO_INSTALL} \
  && microdnf clean all \
  && rm -rf /var/lib/dnf

# Container will run with an arbitrary user, the following uid is a random default to prevent executing as root
USER 10001

WORKDIR /opt/keycloak


ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]

```

- Snippet of `docker-compose.yaml`:

```
  projectxpto-dev1-infra-keycloak-v21:
    build:
      context: "./06-keycloak"
      dockerfile: "./Dockerfile-v21"
      args:
        ARG_KC_DB: ${ENV_KC_V21_DB}
        ARG_KC_METRICS_ENABLED: ${ENV_KC_V21_METRICS_ENABLED}
        ARG_KC_HEALTH_ENABLED: ${ENV_KC_V21_HEALTH_ENABLED}        
        ARG_KC_CACHE: ${ENV_KC_V21_CACHE}
      	ARG_KC_CACHE_STACK: ${ENV_KC_V21_CACHE_STACK}
        ARG_KC_FEATURES: ${ENV_KC_V21_FEATURES}
        ARG_KC_FEATURES_DISABLED: ${ENV_KC_V21_FEATURES_DISABLED}
	ARG_KC_HTTP_RELATIVE_PATH: ${ENV_KC_HTTP_RELATIVE_PATH}
	ARG_KC_HTTPS_KEY_STORE_FILE
	ARG_KC_HTTPS_KEY_STORE_PASSWORD
	ARG_KC_HTTPS_TRUST_STORE_FILE
	ARG_KC_HTTPS_TRUST_STORE_PASSWORD
        ARG_JAVA_JDK_TO_INSTALL: ${ENV_KC_V21_JAVA_JDK_TO_INSTALL}
      network: host
      cache_from:
        - quay.io/keycloak/keycloak:21.1.1
    hostname: projectxpto-dev1-infra-keycloak-v21
    container_name: projectxpto-dev1-infra-keycloak-v21
    user: "root:root"
    environment:
      ENVIRONMENT_TYPE: ${ENV_TYPE}
      KC_DB: ${ENV_KC_V21_DB}
      KC_DB_URL_HOST: ${ENV_KC_V21_DB_URL_HOST}
      KC_DB_URL_PORT: ${ENV_KC_V21_DB_URL_PORT}
      KC_DB_URL_DATABASE: ${ENV_KC_V21_DB_URL_DATABASE}
      KC_DB_USERNAME: ${ENV_KC_V21_DB_USERNAME}
      KC_DB_PASSWORD: ${ENV_KC_V21_DB_PASSWORD}
      KC_DB_SCHEMA: ${ENV_KC_V21_DB_SCHEMA}
      KC_DB_URL_PROPERTIES: ${ENV_KC_V21_DB_URL_PROPERTIES}
      KEYCLOAK_ADMIN: ${ENV_KC_V21_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${ENV_KC_V21_ADMIN_PASSWORD}

      [HTTP-AND-PROXY-SETTINGS-AS_ENV-VARS...]
      
      [HOSTNAME-SETTINGS-AS_ENV-VARS...]

      KC_HTTPS_CERTIFICATE_FILE: ${ENV_KC_HTTPS_CERTIFICATE_FILE}
      KC_HTTPS_CERTIFICATE_KEY_FILE: ${ENV_KC_HTTPS_CERTIFICATE_KEY_FILE}
      KC_HTTPS_KEY_STORE_FILE: ${ENV_KC_HTTPS_KEY_STORE_FILE}
      KC_HTTPS_KEY_STORE_PASSWORD: ${ENV_KC_HTTPS_KEY_STORE_PASSWORD}
      KC_HTTPS_TRUST_STORE_FILE: ${ENV_KC_HTTPS_TRUST_STORE_FILE}
      KC_HTTPS_TRUST_STORE_PASSWORD: ${ENV_KC_HTTPS_TRUST_STORE_PASSWORD}

      [OTHER-SETTINGS-AS_ENV-VARS...]
    mem_limit: 1024m
    mem_reservation: 1024m
    cpus: 2
    deploy:
      replicas: 1
    healthcheck:
      test: ["CMD", "curl", "--head", "--fail", "--silent", "--insecure", "http://127.0.0.1:${ENV_KC_V21_HTTP_PORT}${ENV_KC_V21_HTTP_RELATIVE_PATH}/health/ready"]
      interval: 5s
      timeout: 3s
      retries: 5
    entrypoint: ["/opt/keycloak/bin/kc.sh",
                 "--verbose",
                 "start",
                 "--spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true"]
    ports:
      - "${ENV_KC_V21_HTTP_PORT}:${ENV_KC_V21_HTTP_PORT}"
      - "${ENV_KC_V21_HTTPS_PORT}:${ENV_KC_V21_HTTPS_PORT}"
    expose:
      - "${ENV_KC_V21_HTTP_PORT}"
      - "${ENV_KC_V21_HTTPS_PORT}"
    depends_on:
      - projectxpto-dev1-infra-postgresql-01
    links:
      - projectxpto-dev1-infra-postgresql-01
    volumes:
      - ${ENV_DEFAULT_CERTS_PATH}/_wildcard.projectxpto-devlocal.com.crt.pem:/etc/x509/ca/tls.crt:z
      - ${ENV_DEFAULT_CERTS_PATH}/_wildcard.projectxpto-devlocal.com.crt.pem:/etc/x509/https/tls.crt:z
      - ${ENV_DEFAULT_CERTS_PATH}/_wildcard.projectxpto-devlocal.com.key.pem:/etc/x509/https/tls.key:z
      - ${ENV_DEFAULT_CERTS_PATH}/projectxpto-devlocal.com-pkcs.p12:${ENV_KC_HTTPS_TRUST_STORE_FILE}:z
      - ${ENV_DEFAULT_CERTS_PATH}/devlocal-projectxpto-keystore.jks:${ENV_KC_HTTPS_KEY_STORE_FILE}:z
      - ./06-keycloak/scripts:/tmp/keycloak/scripts:z
      # Add Custom Keycloak extensions
      # Add Custom Themes
    networks:
      - projectxpto-dev01-network


```


- Snippet of `.env` file:

```
ENV_KC_V21_DB=postgres
ENV_KC_V21_METRICS_ENABLED=true
ENV_KC_V21_HEALTH_ENABLED=true
ENV_KC_V21_CACHE=local
ENV_KC_V21_CACHE_STACK=tcp
ENV_KC_V21_FEATURES=authorization,account-api,admin-fine-grained-authz,scripts,token-exchange,web-authn,client-policies,ciba,par,declarative-user-profile,dynamic-scopes,preview,step_up_authentication,account2,account_api,client_secret_rotation,recovery_codes,account3
ENV_KC_V21_FEATURES_DISABLED=impersonation
ENV_KC_V21_HTTP_RELATIVE_PATH=/auth

ENV_KC_HTTPS_CERTIFICATE_FILE=/etc/x509/https/tls.crt
ENV_KC_HTTPS_CERTIFICATE_KEY_FILE=/etc/x509/https/tls.key
ENV_KC_HTTPS_TRUST_STORE_FILE=/etc/x509/https/projectxpto-devlocal.com-pkcs.p12
ENV_KC_HTTPS_TRUST_STORE_PASSWORD=password
ENV_KC_HTTPS_KEY_STORE_FILE=/etc/x509/https/devlocal-projectxpto-keystore.jks
ENV_KC_HTTPS_KEY_STORE_PASSWORD=password

ENV_KC_V21_JAVA_JDK_TO_INSTALL=java-17-openjdk-headless

ENV_KC_V21_DB_URL_HOST=<postgresql-host>
ENV_KC_V21_DB_URL_PORT=<postgresql-port>
ENV_KC_V21_DB_URL_DATABASE=<database-name>
ENV_KC_V21_DB_USERNAME=<db-username>
ENV_KC_V21_DB_PASSWORD=<db-password>
ENV_KC_V21_DB_SCHEMA=public
ENV_KC_V21_DB_URL_PROPERTIES=?ApplicationName=projectxpto-infra-keycloak-v21&ssl=false
ENV_KC_V21_ADMIN_USERNAME=ciam-admin
ENV_KC_V21_ADMIN_PASSWORD=<kc-admin-password>
ENV_KC_V21_HTTP_PORT=9021
ENV_KC_V21_HTTPS_PORT=8421

```

I hope it helps somehow.

Thanks.
