### ISSUE TITLE
How to add keycloak theme

### ISSUE THREAD

**Issue by rakeshreddyrg09** [keycloak/keycloak#19772]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

Hi Team,
I am using [keycloak-operator](https://www.keycloak.org/operator/installation)  21.0.2 and deployed keycloak from [here](https://www.keycloak.org/operator/basic-deployment) and here I can't find an option to provide the **keycloak theme** as an extension as earlier.

old-code
```yaml
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
spec:
  extensions:
    - keycloak-custom-theme.jar
    - keycloak-custom-metrics.jar
    - etc..
```

[New code base](https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/21.0.2/kubernetes/keycloaks.k8s.keycloak.org-v1.yml)  I am not able to find the option.

Is there any other way of providing this option.

Can you kindly look into it.

Thank you.

### Version

21.0.2

### Expected behavior

NA

### Actual behavior

Should have an option to provide the extensions for theme, metric etc,.

### How to Reproduce?

NA
