### ISSUE TITLE
Add support for `reencrypt` OpenShift Routes to the Operator

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#20128]
The Operator currently creates `passthrough` Routes by default (if TLS is not configured, unlike Nginx Ingress that uses uses a reencrypt strategy. Passthrough has (among others) performance implications on Keycloak.

We should either make `reencrypt` the default strategy, or make it configurable (affecting both Routes and Nginx Ingress).

**Considerations**
* This is potentially a breaking change.
* `reencrypt` requires configuring the Route to trust the Keycloak's certificate. This might be a bit tricky doing manually and not something we want to force the users to do. Keycloak should be automatically configured to use TLS key/cert that is generated by OpenShift CA (and therefore implicitly trusted by the Routes).

**Workaround**
Disable the default Ingress and create a custom Route.

**Comment by vmuzikar** [comment]
The routing strategy should probably honor our `proxy` settings, see https://github.com/keycloak/keycloak/issues/14400

**Comment by ckupe** [comment]
This currently breaks deployments of Keycloak on Openshift, in the use case where we are trying to use the cluster-deployed instance of keycloak as an OIDC IdP for the Openshift cluster Oauth client.

Redirection in the middle of auth chain with the default `passthrough` encryption results in "Page not Found" sending the user back to the keycloak pod.

With wildcard certs and openshift-ingress, this is a poor UX. Hard refreshing the browser session has varying success depending on the browser.

**Comment by gilvansfilho** [comment]
@shawkins as we talked about...

To provide first class support to Openshift reencrypt routes I think we need below scenarios.

| Scenario | http.tlsSecret | ingress.tlsSecret | ingress.mode | service annotation                                                        | pod certificate      | route certificate             |
|----------|----------------|-------------------|--------------|---------------------------------------------------------------------------|----------------------|-------------------------------|
| 1        | (not defined)  | (not defined)     | reencrypt    | service.alpha.openshift.io/serving-cert-secret-name: generated-tls-secret | generated-tls-secret | (cluster default certificate) |
| 2        | pod-tls-secret | (not defined)     | reencrypt    |                                                                           | pod-tls-secret       | (cluster default certificate) |
| 3        | (not defined)  | custom-route-tls  | reencrypt    | service.alpha.openshift.io/serving-cert-secret-name: generated-tls-secret | generated-tls-secret | custom-route-tls              |
| 4        | pod-tls-secret | custom-route-tls  | reencrypt    |                                                                           | pod-tls-secret       | custom-route-tls              |


# Scenario 1: Reencrypt with cluster domain and serving certificate for pod

```
spec:
  http:
    ...
  ingress:
    mode: reencrypt
```

Operator will have to:
- Create a `reencrypt` route with no cert (so Openshift will use cluster default certificate)
- Create a service adding the annotation `service.alpha.openshift.io/serving-cert-secret-name: generated-tls-secret`
- Under the hoods `spec.http.tlsSecret` must be set to `generated-tls-secret`

With that we have:
- A `reencrypt` openshift route using cluster default certificate (keycloak exposed using default openshift cluster domain). 
- Pod using certificate generated by Openshift (serving certificate)

# Scenario 2: Reencrypt with cluster domain and custom certificate for pod

```
spec:
  http:    
    tlsSecret: pod-tls-secret
  ingress:
    mode: reencrypt
```

User must provide: 
- `pod-tls-secret` to be used by keycloak pods

Operator will have to:
- Create a `reencrypt` route with no cert (so Openshift will use cluster default certificate)
- Create a service in same way is created today

With that we have:
- A `reencrypt` openshift route using cluster default certificate (keycloak exposed using default openshift cluster domain). 
- Pod using certificate provided through `spec.http.tlsSecret`

# Scenario 3: Reencrypt with custom domain certificate and serving certificate for service

```
spec:
  http:
    ...
  ingress:
    mode: reencrypt
    tlsSecret: custom-route-tls
```

User must provide: 
- `custom-route-tls` to be used by router

Operator will have to:
- Create a `reencrypt` route with the custom certificate 
- Create a service adding the annotation `service.alpha.openshift.io/serving-cert-secret-name: generated-tls-secret`
- Under the hoods `spec.http.tlsSecret` must be set to `generated-tls-secret`

With that we have:
- A `reencrypt` openshift route using custom certificate (keycloak exposed using domain of the certificate provided through `spec.ingress.tlsSecret` )
- Pod using certificate generated by Openshift (serving certificate)

# Scenario 4: Reencrypt with custom domain certificate and custom certificate for pod

```
spec:
  http:
    tlsSecret: pod-tls-secret
  ingress:
    mode: reencrypt
    tlsSecret: custom-route-tls
```

User must provide: 
- `pod-tls-secret` to be used by keycloak pods
- `custom-route-tls` to be used by router

Operator will have to:
- Create a `reencrypt` route with the custom certificate 
- Create a service in same way is created today

User must provide `pod-tls-secret` to be used by keycloak pods

With that we have:
- A `reencrypt` openshift route using custom certificate (keycloak exposed using domain of the certificate provided through `spec.ingress.tlsSecret` )
- Pod using certificate provided through `spec.http.tlsSecret`

In this scenario `mode: reencrypt` could be omitted and implied because two certs was provided

**Comment by vmuzikar** [comment]
As discussed in #39925, we will address reencrypt by adding TLS secret to the ingress spec and documenting various use cases how to make it work incl. generating the Service cert (that was enabled by #39925).

**Comment by gilvansfilho** [comment]
Just for the matter to who is interested in `reencrypt` support today it is possible to be achieved by using a combination of `spec.http.annotations` and `spec.ingress.annotations` like below:

```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  http:
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: tls-secret <1>
    tlsSecret: tls-secret <2>
  ingress:
    annotations:
      route.openshift.io/termination: reencrypt <3>
    enabled: true
```

<1> This annotation instruct openshift to generate a tls secret with the service certificate with `tls-secret` name
<2> We should use same name as above
<3> With this annotation in ingress openshift will generate a reencrypt route

**Comment by gilvansfilho** [comment]
@vmuzikar I think would be great to have this in our operator guide. WDYT?
I could open a issue and also a PR to that.

**Comment by vmuzikar** [comment]
@gilvansfilho Thank you for offering the contribution. Instead of just a docs change, I'd rather have a dedicated support in the Operator for this as captured in this issue.

CC @shawkins

**Comment by shawkins** [comment]
> @vmuzikar I think would be great to have this in our operator guide. WDYT? I could open a issue and also a PR to that.

Thank you for the follow up @gilvansfilho - to confirm this matches scenario 1 in https://github.com/keycloak/keycloak/issues/20128#issuecomment-2940103485 correct? By extrapolation is it fair to say that the other scenarios are working as expected? For example scenario 3 is:

````
  http:
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: tls-secret
    tlsSecret: tls-secret
  ingress:
    annotations:
      route.openshift.io/termination: reencrypt <1>
    enabled: true
    tlsSecret: custom-route-tls
````
 
<1> Still required because the operator only has built-in openshift logic for passthrough and edge.

I'm fine if we just go the documentation route and forgo adding new CR fields - a PR would be good.

The only additional complication I can imagine here is mtls between the keycloak instance and the proxy. I believe that is addressed with the `route.openshift.io/destination-ca-certificate-secret` annotation.

**Comment by gilvansfilho** [comment]
@shawkins today with the options that we have at `spec.http` and `spec.ingress` we are able to achieve all scenarios. I have tested all of them in my Openshift local (CRC) and all have been worked.

Would be great a double check from someone from keycloak team.

# Scenario 1

In this scenario both certificate (service and ingress/route) are provided by the cluster, so when have:
- cluster provided service certificate
- cluster provided ingress certificate

```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  http:
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: svc-tls-secret <1>
    tlsSecret: svc-tls-secret <2>
  ingress:
    annotations:
      route.openshift.io/termination: reencrypt <3>
    enabled: true
```

<1> this will add the annotation to the service generated by the operator, so cluster will create a tls secret named `svc-tls-secret`
<2> name of the tls secret created by the cluster, as defined in <1>
<3> adds the annotation to the ingress, so openshift will generate a reencrypt route. Since no certificate was provided the cluster certificate will be used. 

# Scenario 2

In this scenario service certificate is provided by the user and ingress/route certificate is provided by the cluster, so when have:
- user provided service certificate
- cluster provided ingress certificate

```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  http:
    tlsSecret: svc-tls-secret <1>
  ingress:
    annotations:
      route.openshift.io/termination: reencrypt <2>
      route.openshift.io/destination-ca-certificate-secret: dest-ca-svc-secret <3>
    enabled: true
```

<1> user needs to provide a service certificate through tls secret
<2> adds the annotation to the ingress, so openshift will generate a reencrypt route. Since no certificate was provided the cluster certificate will be used. 
<3> user needs to provide de ca certificate through a generic secret so openshift router will trust in service certificate

# Scenario 3

In this scenario service certificate is provided by the cluster and ingress/route certificate is provided by the user, so we have:
- cluster provided service certificate
- user provided ingress certificate

```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  http:
      service.alpha.openshift.io/serving-cert-secret-name: svc-tls-secret <1>
    tlsSecret: svc-tls-secret <2>
  ingress:
    annotations:
      route.openshift.io/termination: reencrypt <3>
    tlsSecret: ingress-tls-secret <4>
    enabled: true
```

<1> this will add the annotation to the service generated by the operator, so cluster will create a tls secret named `svc-tls-secret`
<2> name of the tls secret created by the cluster, as defined in <1>
<3> required because the operator only has built-in openshift logic for passthrough and edge.
<4> certificate to be used at the ingress/route

# Scenario 4

In this scenario both certificate (service and ingress/route) are provided by the user, so we have:
- user provided service certificate
- user provided ingress certificate

```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  http:
    tlsSecret: svc-tls-secret <1>
  ingress:
    annotations:
      route.openshift.io/termination: reencrypt <2>
      route.openshift.io/destination-ca-certificate-secret: dest-ca-svc-secret <3>    
    tlsSecret: ingress-tls-secret <4>
    enabled: true
```

<1> user needs to provide a service certificate through tls secret
<2> required because the operator only has built-in openshift logic for passthrough and edge.
<3> user needs to provide de ca certificate through a generic secret so openshift router will trust in service certificate
<4> certificate to be used at the ingress/route

**Comment by gilvansfilho** [comment]
Thinking about all scenarios and openshift users I really believe just scenarios 1 and 3 makes sense.

I mean, Why a openshift user would bother with certificates for service layer when He have a  openshift feature which manages this for him? Just put a annotation at a service and is it. It works.

But, again, all of them works in case someone wants to manage his own certificates for service layer.

**Comment by shawkins** [comment]
> Thinking about all scenarios and openshift users I really believe just scenarios 1 and 3 makes sense.

Let's just document it all together:

```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak
spec:
  http:
    tlsSecret: svc-tls-secret <1>
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: svc-tls-secret <2>
  ingress:
    annotations:
      route.openshift.io/termination: reencrypt <3>
      route.openshift.io/destination-ca-certificate-secret: dest-ca-svc-secret <4>
    tlsSecret: ingress-tls-secret <5>
    enabled: true
```
<1> _Required_: tls secret the server will use
<2> _Optional_: add this annotation to have OpenShift create a tls Secret with the given name - must match <1>. If this annotation is not used, the Secret must be created by some other means.
<3> _Required_: the operator only has built-in OpenShift logic for passthrough and edge, so it must be explicitly told we're in a reencrypt scenario
<4> _Optional_: if mtls is used and you are providing a server tls Secret by a mechanism other than <2>, the proxy needs to trust the server via this tls Secret.
<5> _Optional_: tls Secret to be used at the Ingress/Route. If not specified, IngressController defaults will be used.

> I'd rather have a dedicated support in the Operator for this as captured in this issue.

@vmuzikar see the above. There are three potential customizations for openshift <2>, <3>, and <4>. Unless we assume a name for the svc-tls-secret, we really aren't saving the user much effort. That is instead of:

```
  ingress:
    annotations:
      route.openshift.io/termination: reencrypt
```

We'd reintroduce something like our old proxy setting:

```
  ingress:
    type: reencrypt
```

And while we'd handle that for openshift, it wouldn't work for any other platform.
