### ISSUE TITLE
403 forbidden while accessing the admin console

### ISSUE THREAD

**Issue by rakeshreddyrg09** [keycloak/keycloak#20145]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

account/api

### Describe the bug

I am using keycloak 21.1.1 and deploying in EKS.
accessing through kong gateway.

Not able to access the keycloak admin console. getting 403 forbidden.

![235846794-492a6797-81ea-49b8-aa53-a44c69d5e719](https://user-images.githubusercontent.com/48629246/236138902-59edc0f8-5f92-412e-b9a5-5b6768bbaaaa.png)
![235846896-4aa8adf7-a987-4298-82a8-d7a284b8a7bc](https://user-images.githubusercontent.com/48629246/236138961-577a9686-9917-471f-8c8b-db2cc335a2ae.png)
![235846991-19e81950-b253-47cb-81a5-24088874c8f6](https://user-images.githubusercontent.com/48629246/236138986-6e6e0ec9-6ee3-4e8e-8dcb-2b86b05227b9.png)
![235847092-6434cfec-422f-46e1-9032-ff1070eb039a](https://user-images.githubusercontent.com/48629246/236139016-5d39b4df-cbe9-4748-9adb-1a36c7596bbe.png)
![235847172-bdf88009-249c-446f-9890-8a2e115d7464](https://user-images.githubusercontent.com/48629246/236139038-45f90300-4fa1-48a7-b564-f92caab4c308.png)
![235847216-fa198fc2-af8e-4745-a29d-6ce4a3a39e67](https://user-images.githubusercontent.com/48629246/236139129-1eb1a725-2004-4e35-91ad-102ed1c2dd6d.png)
![235846675-1f6e3bb4-fd1b-46a5-96f4-72831aa8f9e7](https://user-images.githubusercontent.com/48629246/236139158-f694e9a7-ea05-43f3-b8ac-31f03fd4f620.png)
here is my kc.yaml
```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  instances: 1
  db:
    vendor: postgres
    host: keycloak-ha-primary.default.svc
    usernameSecret:
      name: keycloak-ha-kcdb
      key: user
    passwordSecret:
      name: keycloak-ha-kcdb
      key: password
    database: keycloak-kcdb0
    port: 5432
  hostname:
    hostname: keycloak.<my-url>.cloud
    admin: keycloak.<my-url>.cloud
    strictBackchannel: true
    strict: true
  additionalOptions:
    - name: proxy
      value: "edge"
    - name: override
      value: "true"
    - name: hostname-strict-https
      value: "true"
  ingress:
      enabled: false
  http:
    httpEnabled: true
    httpPort: 8080
```
here is my ingress.yaml
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: keycloak
    app.kubernetes.io/managed-by: keycloak-operator
  name: example-kc-ingress
spec:
  ingressClassName: kong
  rules:
  - host: keycloak.<my-url>.cloud
    http:
      paths:
      - path: /
        backend:
          service:
            name: example-kc-service
            port:
              number: 8080
        pathType: Prefix
```

can any one help me here.

### Version

21.1.1

### Expected behavior

Should be able to access the admin console.

### Actual behavior

NA

### How to Reproduce?

Create a EKS cluster, add kong with helm version -- 2.17.0
Get keycloak operator from [here](https://www.keycloak.org/operator/installation)
Fallow [this](https://www.keycloak.org/operator/basic-deployment) to install keycloak 21.1.1

try to access the keycloak admin console.

**Comment by mposolda** [comment]
Looks like a setup issue rather than Keycloak bug (Setup of the complex environment including kong proxy). You can check the Keycloak docs sections like for example https://www.keycloak.org/server/reverseproxy and https://www.keycloak.org/server/hostname. Maybe it helps.

Temporarily adding to Backlog for now. We can possibly triage later.

**Comment by dsaju** [comment]
@rakeshreddyrg09 , Did you manage to resolve this issue ?

**Comment by dsaju** [comment]
Addition of KC_HOSTNAME_ADMIN_URL fixed the issue for me

**Comment by rakeshreddyrg09** [comment]
got fixed by adding adminUrl: https://keycloak.<my-url>.cloud under host.
```yaml
 hostname:
    hostname: keycloak.<my-url>.cloud
    adminUrl: https://keycloak.<my-url>.cloud
    strictBackchannel: true
    strict: true
```
