### ISSUE TITLE
Keycloak Operator - Keycloak pod exposes incorrect startup readiness probe end points

### ISSUE THREAD

**Issue by MarkCupitt** [keycloak/keycloak#20173]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

operator

### Describe the bug

When teh operator deploys a keycloak pod, it does not set teh end points correctly, the look like this `http://health` thus causing the pod to not start. We set the Additional Options Var as follows, can not see any other way to enable health on docs we have searched for

```
    - name: health-enabled
      value: "$true"
```
The pod is running, but gets restarted by Kubernetes

as a workaround, we were able ot get a running pod with this in the keycloak definition yaml

```
  unsupported:
    podTemplate:
      metadata:
        labels:
          bounty: "keycloak"
      spec:
        containers:
          - 
            livenessProbe:
              httpGet:
                path: /health/live
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 20
              periodSeconds: 2
              successThreshold: 1
              timeoutSeconds: 1
              failureThreshold: 150

            readinessProbe:
              httpGet:
                path: /health/ready
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 20
              periodSeconds: 2
              successThreshold: 1
              timeoutSeconds: 1
              failureThreshold: 250

            startupProbe:
              httpGet:
                path: /health/ready
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 60
              periodSeconds: 2
              successThreshold: 1
              timeoutSeconds: 1
              failureThreshold: 250
```

Everything is running fine now

### Version

21.1.1

### Expected behavior

Probes should be correctly exposed by the pod, when operator deployed it

### Actual behavior

See above

### How to Reproduce?

See above

### Anything else?

Nope
