### ISSUE TITLE
Operator: Improve Service

### ISSUE THREAD

**Issue by phmcder** [keycloak/keycloak#20500]
### Description

I tried to deploy Keycloak into AWS EKS by using the Kubernetes operator. I am using the AWS Application Load Balancer to handle forward external traffic to the Keycloack service. However, the ALB only supports a service type of NodePort, not ClusterIP.

Also to configure the ALB you should add annotations to the Keycloack service definition

Can we add more customisation to the definition of the Keycloak deployed service to cover this?

### Motivation

Currently, you cannot create an ingress for keycloak deployed in AWS EKS that uses ALB. There should be enough configuration options to support this

### Details

See here for details of what configurations are supported by ALB https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html

**Comment by ahus1** [comment]
@phmcder - while this has not been implemented yet, I suggest you add your own service in addition to Keycloak's standard service to make the bits work that you need. Would that work in your scenario?

**Comment by ahus1** [comment]
@vmuzikar - I might be needing something like this in the work stream I'm currently working on, and I wonder a CR would look like. 

```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
spec:
  service:
    annotations:
      key: value
    spec:
      type: ClusterIP
      ports:
      - port: 8443
        nodePort: 30001
```       

While the part about the annotations looks quite similar what we're planning for the Ingress, I'm not so sure about the `spec` part ... would we allow all parts of the Ingress to be overwritten? 

Or would we wrap it into `unsupported`: 

```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
spec:
  service:
    annotations:
      key: value
  unsupported: 
    serviceSpec:
      type: ClusterIP
      ports:
      - port: 8443
        nodePort: 30001
```       

Best,
Alexander
