### ISSUE TITLE
Allow operator to create kubernetes secrets with information from client descriptions

### ISSUE THREAD

**Issue by dpalmmna** [keycloak/keycloak#20838]
### Description

Require the ability to create kubernetes secrets with different elements for keycloak clients.

Allows the injection of kubernetes secrets into pods containing client secrets. Allows maintaining up to date client secrets synchronized with the keycloak server.

Secret Creation Example:
```
kind: KeycloakSecretCreation
apiVersion: v1
metadata:
  name: my-client-security-resource-server-secret-creation
spec:
  realm: test
  clientId: my-client
  secretName: my-client-security-resource-server
  secretTemplate:
    stringData:
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUETOKEN_INTROSPECTION-URI: ${AUTH_SERVER_URL}/realms/%{realm}/protocol/openid-connect/token/introspect
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUETOKEN_CLIENT-ID: my-client
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUETOKEN_CLIENT-SECRET: %{client.secret}
```

would generate secret
```
kind: Secret
apiVersion: v1
metadata:
  name: my-client-security-resource-server
type: Opaque
stringData:
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUETOKEN_INTROSPECTION-URI: ${AUTH_SERVER_URL}/realms/test/protocol/openid-connect/token/introspect
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUETOKEN_CLIENT-ID: my-client
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUETOKEN_CLIENT-SECRET: bgiuzefzbufibqogngbuigngzzfnfoinfnfieonfzf
```
