### ISSUE TITLE
Operator Only Allows you to Create One Keycloak Instance

### ISSUE THREAD

**Issue by silverbp** [keycloak/keycloak#21015]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

operator

### Describe the bug

When you create more than one instance after installing the operator..

example..

```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak-01
  namespace: keycloak
```

```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak-02
  namespace: keycloak
```

I've left the rest of the configuration out of the example as it's not necessarily relevant, it is configured in such a way where they both function and come up, however.. what the operator creates for services won't work because the selector labels will hit ALL instances..

both keycloak-01-service and keycloak-02-service that were created by the operator have the following selector labels.

``` 
 selector:
    app: keycloak
    app.kubernetes.io/managed-by: keycloak-operator
```

### Version

nightly

### Expected behavior

the keycloak service and keycloak discovery service would both have selectors that would limit it to the instance name and pods running under the instance name.

### Actual behavior

The services created by the operator, both the keycloak-service and keycloak-discovery ones have selectors that will route traffic to ALL keycloak pods.

### How to Reproduce?

Create two different instances of keycloak in the same namespace and cluster.
