### ISSUE TITLE
Support YAML formatted Quarkus configuration

### ISSUE THREAD

**Issue by mruzicka** [keycloak/keycloak#21057]
### Description

Please include the `quarkus-config-yaml` Quarkus extension (https://quarkus.io/guides/config-yaml) in Keycloak.

### Motivation

The YAML format has many advantages over the Java properties format, to name a few:
* it is easier to work with - think tools like helm, which support it natively
* terser, more readable - cf.
  ```properties
  quarkus.datasource.extrads.jdbc.url=jdbc:oracle:thin:@//hostname:1521/DBNAME
  quarkus.datasource.extrads.jdbc.new-connection-sql=ALTER SESSION SET CURRENT_SCHEMA = "APP-SCHEMA"
  quarkus.datasource.extrads.jdbc.acquisition-timeout=PT30S
  quarkus.datasource.extrads.username=scott
  quarkus.datasource.extrads.password=tiger
  ```
  with:
  ```yaml
  quarkus:
    datasource:
      extrads:
        jdbc:
          url: jdbc:oracle:thin:@//hostname:1521/DBNAME
          new-connection-sql: |-
            ALTER SESSION SET CURRENT_SCHEMA = "APP-SCHEMA"
          acquisition-timeout: PT30S

        username: scott
        password: tiger
  ```
* less error prone

### Details

The extension can actually be added even to the current Keycloak releases just by putting the following two jar files (all other dependencies are already included):
- [quarkus-config-yaml-2.13.7.Final.jar](https://mvnrepository.com/artifact/io.quarkus/quarkus-config-yaml/2.13.7.Final)
- [smallrye-config-source-yaml-2.12.3.jar](https://mvnrepository.com/artifact/io.smallrye.config/smallrye-config-source-yaml/2.12.3)

to the `/opt/keycloak/providers` directory of the official docker image and running `/opt/keycloak/bin/kc.sh build`.
Together those two jar files are less than 20kB in size, which is IMO negligible.
