### ISSUE TITLE
Getting "Unexpected Application Error! Network response was not OK" before loading Administration Console

### ISSUE THREAD

**Issue by getsueineko** [keycloak/keycloak#21253]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the latest release

### Area

admin/ui

### Describe the bug

I have deployed keycloak version 21.1.1 in openshift as statefulset. Everthing is working fine from authentication and authorisation side. 
But when i am trying to access the Administration Console. It is throwing me the below error (the message appears for a second or less):

Unexpected Application Error!
Network response was not OK.
Error: Network response was not OK.
**at fetchWithError ([https://DUMMY-URL/auth/resources/abcma/admin/keycloak.v2/assets/index-d2c499e7.js:67:43710](https://dummy-url/auth/resources/abcma/admin/keycloak.v2/assets/index-d2c499e7.js:67:43710))**
**at async Agent.requestWithParams ([https://DUMMY-URL/auth/resources/abcma/admin/keycloak.v2/assets/index-d2c499e7.js:67:46301](https://dummy-url/auth/resources/abcma/admin/keycloak.v2/assets/index-d2c499e7.js:67:46301))**

and then successfully redirecting me to the Administration Console.

I'm not the only one with this behavior https://keycloak.discourse.group/t/getting-error-before-loading-keycloak-ui/22406

### Version

21.1.1

### Expected behavior

no weird messages

### Actual behavior

![image](https://github.com/keycloak/keycloak/assets/14312837/c852bc4e-e1d2-463e-b974-90c61912c691)

### How to Reproduce?

just click to Administration Console link

**Comment by jonkoops** [comment]
In order to reproduce this issue we'll need detailed steps on how this can be reproduced locally.

**Comment by getsueineko** [comment]
> In order to fix this issue we'll need detailed steps on how this can be reproduced locally.

kubectl apply -f ./k8s
no problem in process of installation
after a fresh installation, what happens is what is seen in the video 
https://github.com/keycloak/keycloak/assets/14312837/0dce8ac6-ed41-459f-ac5d-863ff0ad0cff

in attach my statefulset
[statefulset.zip](https://github.com/keycloak/keycloak/files/11887440/statefulset.zip)

**Comment by ssilvert** [comment]
@getsueineko Thanks for the video.  So are you able to successfully log in and run the admin console after getting the error?

**Comment by ssilvert** [comment]
@getsueineko ???

**Comment by djairhogeuens** [comment]
@ssilvert We're having the same problem so I can also help with the troubleshooting here. To answer your question: yes we're able to successfully log in and use the admin console after briefly seeing the error.

**Comment by getsueineko** [comment]
> @getsueineko ???

Yes, I'm not experiencing any problems in operation, except for questions from worried users about a slipping error

**Comment by ssilvert** [comment]
@djairhogeuens @getsueineko Can one of you try this with Keycloak 22 or the [nightly build](https://github.com/keycloak/keycloak/releases/tag/nightly)?

**Comment by getsueineko** [comment]
Not yet. Approved version 21.1.1 on production =(

**Comment by jon-nfc** [comment]
I too just had this error. However in my case it turned out to be a permissions error and one that had never caused me issues before. I initially got the same error screen, however refreshing the browser, brought up the realm console, with the error inside of keycloak itself.

![Screenshot from 2023-07-16 13-23-53](https://github.com/keycloak/keycloak/assets/8982109/ee46240d-9762-45bd-8311-69d391dcfbf2)


Turns out, that the admin console i was trying to log into, I didn't have the permissions set to access the realms console.. where they went i don't know as the same LDAP group has access to both realms as admin. it logged in but the realms dropdown wouldn't populate and "Network response was not OK" message would pop up. after some debugging i noticed (browser debug console) a HTTP/403 was being returned ("serverinfo" https://example.com/admin/serverinfo/). Clearing browser cache, restarting keycloak, reverse proxy and server did nothing to fix it. In the end, I logged into a different realm then used the realm dropdown to select the realm in question i wished to access. I do not know why now i couldn't accesss the realms console or why now, i'm getting soft access denied errors. I have been able to log into this realms admin console before. 

I can re-simulate the above, by removing said permission to access the console. and attempting to log into the realm where the permission is removed.

**Comment by djairhogeuens** [comment]
> @djairhogeuens @getsueineko Can one of you try this with Keycloak 22 or the [nightly build](https://github.com/keycloak/keycloak/releases/tag/nightly)?

I just managed to make some time to try and reproduce this on the latest Keycloak release (22.0.1).

After spinning up identical containers with Keycloak 21.1.2 and Keycloak 22.0.1 and switching between them I can confirm that I can still reproduce the issue on 21.1.2 but not anymore on 22.0.1. I did not try 22.0.0.

We will look into upgrading to Keycloak 22.0.1 to get this solved for us.

**Comment by ssilvert** [comment]
Glad to hear Keycloak 22.0.1 solves the problem.  Closing.

**Comment by Lexachoc** [comment]
> > @djairhogeuens @getsueineko Can one of you try this with Keycloak 22 or the [nightly build](https://github.com/keycloak/keycloak/releases/tag/nightly)?
> 
> I just managed to make some time to try and reproduce this on the latest Keycloak release (22.0.1).
> 
> After spinning up identical containers with Keycloak 21.1.2 and Keycloak 22.0.1 and switching between them I can confirm that I can still reproduce the issue on 21.1.2 but not anymore on 22.0.1. I did not try 22.0.0.
> 
> We will look into upgrading to Keycloak 22.0.1 to get this solved for us.

I have tried to upgrade from Keycloak 22.0.0 to 22.0.1 and even to 22.0.5, but the problem persists.
The problem occurs when **non-admin** user trying to access the admin console

> https://<domain>/admin/master/console/

It does not cause any problems if the access is done through an administrator account.

![image](https://github.com/keycloak/keycloak/assets/20377719/0db7a9e8-f826-49f9-bb74-bbf03f42fc41)

Below is my Keycloak setting:
Dockerfile:
```yml
FROM quay.io/keycloak/keycloak:22.0.5

ENV KC_DB=postgres
ENV KC_DB_URL_HOST=keycloak-db
ENV KC_DB_URL_DATABASE=keycloak
ENV KC_DB_USERNAME=keycloak
ENV KC_DB_PASSWORD=<password>
ENV KC_DB_SCHEMA=public
ENV KEYCLOAK_ADMIN=admin
ENV KEYCLOAK_ADMIN_PASSWORD=<password>


ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true

ENV KC_HTTP_ENABLED=false

ENV KC_HTTPS_CLIENT_AUTH=request
ENV KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/conf/cert.pem
ENV KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/conf/key.pem

ENV KC_HOSTNAME_DEBUG=true

ENV KC_HOSTNAME=sso.cms.uni-jena.de
ENV KC_HOSTNAME_ADMIN=<domain>
ENV KEYCLOAK_FRONTEND_URL=https://<domain>:443
ENV PROXY_ADDRESS_FORWARDING=true
ENV KC_PROXY=edge
```
docker-compose.yml:
```yml
version: '3.7'

services:
  keycloak-db:
      container_name: keycloak-db
      image: postgres:15
      volumes:
        - keycloak22_postgres15:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: <password>
      networks:
        - internal
      restart: always

  keycloak:
      build: .
      volumes:
        - ../nginx/cert_sso/cert_sso_combine.pem:/opt/keycloak/conf/cert.pem
        - ../nginx/cert_sso/key_sso.pem:/opt/keycloak/conf/key.pem
      depends_on:
        - keycloak-db
      networks:
        - internal
        - proxy-net
      command:
        - start
      restart: always

volumes:
  keycloak22_postgres15:
      driver: local

networks:
  internal:
    driver: bridge
  proxy-net:
    name: proxy-net
    driver: bridge
```
I use nginx as a reverse proxy


Any help would be appreciated! Thank you
