### ISSUE TITLE
Hostname admin url loading block

### ISSUE THREAD

**Issue by silex-fabrice** [keycloak/keycloak#21581]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

With a fresh install of keycloak 21.1 in docker, i was unable to connect to the admin master console with a different URI of the frontend URI.
ex:
account URI: auth-test.hostname.com
admin url: keycloak.private-hostname.com

When i come to the admin master console (keycloak.private-hostname.com/admin/master/console/) the page in blocking the loading screen and try to load this page: auth-test.hostname.com/realms/master/protocol/openid-connect/3p-cookies/step1.html

![uueMHgRCKx](https://github.com/keycloak/keycloak/assets/73938363/3cfa2821-8f34-4300-9426-e708d0366af5)

### Version

21.1

### Expected behavior

can login on master admin console

### Actual behavior

Can not login on master admin console

### How to Reproduce?

my docker-compose configuration:
```yaml
keycloakdev:
    depends_on:
      - traefik
      - keycloakdbdev
    image: quay.io/keycloak/keycloak:21.1.2
    command: start --optimized --hostname-strict-backchannel=false
    restart: always
    environment:
      - PROXY_ADDRESS_FORWARDING=true
      - KC_HOSTNAME_ADMIN_URL=https://keycloak.private-hostname.com
      - KC_HOSTNAME_URL=https://auth-test.hostname.com
      - KC_HTTP_ENABLED=true
      - KC_PROXY=edge
      - KC_DB_URL_HOST=keycloakdbdev
      - KC_DB_URL_DATABASE=keycloak_new
      - KC_DB_USERNAME=keycloak_new
      - KC_DB_URL_SCHEMA=keycloak_new
      - KC_DB_PASSWORD=xxxxxxxxxxxxxxxxxxxxxxx
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    container_name: keycloakdev
    labels:
      - traefik.enable=true
      - traefik.http.routers.keycloakdev-fe.entrypoints=websecure
      - traefik.http.routers.keycloakdev-fe.tls
      - traefik.http.routers.keycloakdev-fe.tls.certresolver=letsencrypt
      - traefik.http.routers.keycloakdev-fe.rule=Host(`auth-test.hostname.com`) && (PathPrefix(`/realms/customReal`) || PathPrefix(`/resources`) || PathPrefix(`/js`))
      - traefik.http.routers.keycloakdev-admin.entrypoints=websecure
      - traefik.http.routers.keycloakdev-admin.tls
      - traefik.http.routers.keycloakdev-admin.rule=Host(`keycloak.private-hostname.com`)
      - traefik.http.routers.keycloakdev-admin.middlewares=localiponly
      - com.centurylinklabs.watchtower.enable=true
``` 

Now go to the page https://keycloak.private-hostname.com, and click on the "Administration Console" link and i have an infinit login.
