### ISSUE TITLE
Ability to deploy Keycloak OpenShift running on restricted networks (airgap)

### ISSUE THREAD

**Issue by pgodowski** [keycloak/keycloak#21827]
### Description

We have customers who are using OpenShift on restricted network (aka airgapped aka offline) - meaning that the clusters are not internet connected.
In order to deploy the operators from the catalog, there is a published procedure https://docs.openshift.com/container-platform/4.12/operators/admin/olm-restricted-networks.html#olm-mirror-catalog_olm-restricted-networks which require execution of some commands to get the list of images (operator/operands) to mirror into the local container registry.

One of those commands is `oc adm catalog mirror` which at the high level is doing the 'discovery of the container images to mirror'. The way how it works is that it [expects](https://github.com/openshift/oc/blob/master/pkg/cli/admin/catalog/mirror.go#L505-L538) that `ClusterServiceVersion` for each operator to be deployed has `relatedImages` attributes specified, pointing to the image digests of both operator and operand.

### Motivation

Half of our customers are deploying on disconnected (offline) OpenShift clusters - they have to be provided a way to deploy the solution which uses Keycloak.

### Details

For example it would be expected in Keycloak operator's `ClusterServiceVersion`:

```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metatdata:
  name: keycloak-operator.v22.0.1
spec:
 relatedImages:
    - image: quay.io/keycloak/keycloak-operator@sha256:43d9d912f34309e9e286a123cb7d39182aa6f27512193a0d5297c3e25e2f4804
      // digest of quay.io/keycloak/keycloak-operator:22.0.1
      name: KEYCLOAK_OPERATOR_IMAGE

    - image: quay.io/keycloak/keycloak@sha256:5b872e841ea9e394d89bdf250146434532d9c2001404540d46621d60f87494e7
      // digest of quay.io/keycloak/keycloak:22.0.1
      name: KEYCLOAK_OPERAND_IMAGE
```
