### ISSUE TITLE
Keycloak Admin password sign in issue, while keycloak restore process

### ISSUE THREAD

**Issue by Naresh240** [keycloak/keycloak#21859]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

user-profile

### Describe the bug

Hi Team,

Please help us on issue

I have deployed Keycloak with version 22.0.1 and integrated with Postgres database, later I have deleted Keycloak and restored again.
But when I tried to access Admin console facing below issue

![image](https://github.com/keycloak/keycloak/assets/58024415/2332e5c8-b256-40e4-8097-ef7a46ab8d2d)

Is old password is storing anywhere in database?
Can we restore admin password? 

Please check below which yaml I am using... Please suggest did I missed any parameter in this keycloak yaml

```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
  namespace: vela-system
spec:
  instances: 1
  db:
    vendor: postgres
    url: jdbc:postgresql://rds-example-instance.cpiu6aou8xxl.ap-southeast-1.rds.amazonaws.com:5432/exampledb
    usernameSecret:
      name: rds-example-secret
      key: username
    passwordSecret:
      name: rds-example-secret
      key: attribute.password
    # database: exampledb
    # port: 5432
  hostname:
    hostname: keycloak.managedeks.infra.example.com
    adminUrl: https://keycloak.managedeks.infra.example.com/
    strictBackchannel: true
    strict: true
  additionalOptions:
    - name: proxy
      value: "edge"
  ingress:
    enabled: false
```

### Version

22.0.1

### Expected behavior

When I restore Keycloak admin password should use new password itself

### Actual behavior

When I restore Keycloak admin password should use new password itself

### How to Reproduce?

1. Install keycloak from https://www.keycloak.org/operator/installation
2. While installing add external database (Postgres)
3. Delete Keycloak without deleting database
4. Re-install keycloak with existing database (Postgres)
5. Check Admin console with new secret Produced by KC

### Anything else?

NA
