### ISSUE TITLE
Admin interfaces failed to load when using non default port (docker)

### ISSUE THREAD

**Issue by prettySongbird** [keycloak/keycloak#21882]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Running keycloak in docker with non default ports, the admin interface fails to load with the following message in the browser logs:

Browser: Firefox 115
```

Uncaught
Object { error: "Timeout when waiting for 3rd party check iframe message." }
```

To reproduce this, run keycloak with this docker-compose:

```
---
version: '3'
volumes:
  kc_data:

services:
  keycloak:
      image: hub.docker.com/sys/docker/keycloak:nightly
      container_name: keycloak
      command:
         - start --hostname=keycloak01-fra.myorg.net
      environment:
        KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/ssl/keycloak01.myorg.net.crt.pem
        KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/ssl/keycloak01.myorg.net.key.pem
      env_file:
        - .env
      volumes:
        - kc_data:/opt/keycloak
        - ./ssl:/opt/keycloak/ssl:ro
      ports:
        - 80:8080
        - 443:8443
```

This issue does not appear when using the default ports like this:

```
---
version: '3'
volumes:
  kc_data:

services:
  keycloak:
      image: hub.docker.com/sys/docker/keycloak:nightly
      container_name: keycloak
      command:
         - start --hostname=keycloak01-fra.myorg.net
      environment:
        KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/ssl/keycloak01.myorg.net.crt.pem
        KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/ssl/keycloak01.myorg.net.key.pem
      env_file:
        - .env
      volumes:
        - kc_data:/opt/keycloak
        - ./ssl:/opt/keycloak/ssl:ro
      ports:
        - 8080:8080
        - 8443:8443
```

Tested with version 22.0 and nightly

### Version

22.0

### Expected behavior

Keycloak should work with non default ports

### Actual behavior

Changing the exposed ports breakds the admin ui

### How to Reproduce?

Run keycloak with this docker compose configuration:

```
---
version: '3'
volumes:
  kc_data:

services:
  keycloak:
      image: hub.docker.com/sys/docker/keycloak:nightly
      container_name: keycloak
      command:
         - start --hostname=keycloak01-fra.myorg.net
      environment:
        KC_HTTPS_CERTIFICATE_FILE: /opt/keycloak/ssl/keycloak01.myorg.net.crt.pem
        KC_HTTPS_CERTIFICATE_KEY_FILE: /opt/keycloak/ssl/keycloak01.myorg.net.key.pem
      env_file:
        - .env
      volumes:
        - kc_data:/opt/keycloak
        - ./ssl:/opt/keycloak/ssl:ro
      ports:
        - 8080:8080
        - 8443:8443
```
