### ISSUE TITLE
keycloak realmimport update

### ISSUE THREAD

**Issue by rakeshreddyrg09** [keycloak/keycloak#21974]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

operator

### Describe the bug

Hi Team,
I have deployed keycloak operator form [here](https://www.keycloak.org/operator/installation) on EKS.
Then I have configured [realm-import](https://www.keycloak.org/operator/realm-import) and applied to my kc.
```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: my-realm-kc
spec:
  keycloakCRName: example-kc
  realm:
    id: example-realm
    realm: example-realm
    displayName: ExampleRealm
    enabled: true
```

Now I wanted to update my realm-import file by adding users, client and OIDC information and reapply the same.
```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: my-realm-kc
spec:
  keycloakCRName: example-kc
  realm:
    id: example-realm
    realm: example-realm
    displayName: ExampleRealm
    enabled: true
    adminTheme: NEW-KC
    clients:
    - clientId: test-client
      name: test-client
      description: test-client
      enabled: true
      clientAuthenticatorType: client-secret
      secret: secret
    identityProviders: 
    - alias: companyid
      displayName: Login with test ID(OIDC)
      providerId: oidc
      enabled: true
      trustEmail: false
      storeToken: false
      addReadTokenRoleOnCreate: false
      linkOnly: false
      firstBrokerLoginFlowAlias: first broker login
      config:
        validateSignature: "true"
        userInfoUrl: "https://test-a.auth0.com/userinfo"
        tokenUrl: "https://test-a.auth0.com/oauth/token"
        clientId: "2sAjWVH5jdi4cNptHIszdLEarexuNHOU"
        jwksUrl: "https://test-a.auth0.com/.well-known/jwks.json"
        issuer: "https://test-a.auth0.com/"
        pkceMethod: "S256"
        useJwksUrl: "true"
        pkceEnabled: "true"
        authorizationUrl: "https://test-a.auth0.com/authorize?connection=main-tenant-oidc"
        clientAuthMethod: "client_secret_post"
        syncMode: "FORCE"
        clientAssertionSigningAlg: "RS256"
        clientSecret: "abc"        
        defaultScope: "openid email profile"
    users:
    - username: "realm_user"
      firstName: "John"
      lastName: "Doe"
      email: "user@example.com"
      enabled: True
      emailVerified: False
      credentials:
        - type: "password"
          value: "12345"
      realmRoles:
        - "offline_access"
      clientRoles:
        account:
          - "manage-account"
        realm-management:
          - "manage-users"
```
When I reapplied the updated file, it shows applied but it is not reflecting in the keycloak UI, 
in this case I was deleting the keycloak and reapplying the keycloak and reapplying the realm-import.
Can you suggest be the best case for this.

### Version

22.0.1

### Expected behavior

I should able to apply the updated realm-import configuration and it should be reflecting in kc ui without any manual steps.

### Actual behavior

NA

### How to Reproduce?

Install keycloak  operator from [here](https://www.keycloak.org/operator/installation)
apply realm import from [here](https://www.keycloak.org/operator/realm-import)

Update the realm-import file and reapply it. See whether  the new changes are updated in KC ui.

### Anything else?

No
