### ISSUE TITLE
Operator - Enabling http does not include 8080 in service

### ISSUE THREAD

**Issue by tamis-laan** [keycloak/keycloak#22131]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

operator

### Describe the bug

When following the advanced configuration guide (https://www.keycloak.org/operator/advanced-configuration) the last section shows how to enable http:

``` yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  ...
  http:
    httpEnabled: true
  hostname:
    strict: false
    strictBackchannel: false
```
However the keycloak-service does not expose port 8080 for directing http traffic to the corresponding pods.
![screenshot](https://github.com/keycloak/keycloak/assets/3178666/deb9e050-727a-4953-b084-4e2aa6105d72)

### Version

keycloak-operator-0.0.4	20.0.2

### Expected behavior

An open port 8080 of the keycloak-service for routing traffic

### Actual behavior

Closed port 8080

### How to Reproduce?

1. Install operator
2. Follow advanced configuration guide
