### ISSUE TITLE
Operator - annotation not working

### ISSUE THREAD

**Issue by tamis-laan** [keycloak/keycloak#22227]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

operator

### Describe the bug

I'm looking to use linkerd service mesh to implement cluster wide security, and I'm trying to combine it with the keycloak operator. Linkerd usses annotations. The advanced configuration guide (https://www.keycloak.org/operator/advanced-configuration) claims I can add annotations under 'unsupported:` but this doesn't work.

Here is my configuration:

``` yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 2
  db:
    vendor: postgres
    host: pg-auth-rw
    database: keycloak
    usernameSecret:
      name: pg-auth-superuser
      key: username
    passwordSecret:
      name: pg-auth-superuser
      key: password
  http:
    httpEnabled: true
  hostname:
    hostname: auth.dev.local
    strict: false
    strictBackchannel: false
  ingress:
    enabled: false
  unsupported:
    podTemplate:
      metadata:
        annotations:
          config.linkerd.io/inject: enabled
        labels:
          my-label: "keycloak"
```

### Version

keycloak-operator-0.0.4	20.0.2

### Expected behavior

Annotations are added to keycloak pods

### Actual behavior

No annotations are added

### How to Reproduce?

Use yaml spec and operator for testing
