### ISSUE TITLE
Keycloak admin console in loading, problem in step1 (http is enabled, but still looking for https in step 1)

### ISSUE THREAD

**Issue by rakeshreddyrg09** [keycloak/keycloak#22294]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

admin/ui

### Describe the bug

Hi Team,
I am trying to install keycloak (operator) 22.0.1 in k3d cluster.
here is my configuration
operator installed from here: 
```yaml
kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/22.0.1/kubernetes/kubernetes.yml
````
keycloak:
```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  instances: 1
  db:
    vendor: postgres
    host: keycloak-ha-primary.ra.svc
    usernameSecret:
      name: keycloak-ha-pguser-keycloak-kcdb
      key: user
    passwordSecret:
      name: keycloak-ha-pguser-keycloak-kcdb
      key: password
    database: keycloak-kcdb0
    port: 5432
  hostname:
    hostname: keycloak.test-sample.com:8080
    admin: keycloak.test-sample.com:8080
    strictBackchannel: false
    strict: false
  additionalOptions:
    - name: proxy
      value: "edge"
  ingress:
    enabled: false
  http:
    httpEnabled: true
    httpPort: 8080

````

kong-ingress:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: keycloak
    app.kubernetes.io/managed-by: keycloak-operator
  name: example-kc-ingress
spec:
  ingressClassName: prod-kong-ingress
  rules:
    - host: keycloak.test-sample.com
      http:
        paths:
          - path: /
            backend:
              service:
                name: example-kc-service
                port:
                  number: 8080
            pathType: Prefix

```
When i tried to login to admin console facing infinite loading page

![image](https://github.com/keycloak/keycloak/assets/48629246/20aecd9f-b800-4588-b9b2-7733f6bc0900)

What I observe is, In the RequestURL in the above image:  <b>https://keycloak.test-sample.com:8080<b> even though I have enabled http 

can you please look into it.

### Version

22.0.1

### Expected behavior

NA

### Actual behavior

NA

### How to Reproduce?

Operator: kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/22.0.1/kubernetes/kubernetes.yml
keycloak: https://www.keycloak.org/operator/basic-deployment
using kong as load balancer: ingress is attached above.

### Anything else?

no

**Comment by vmuzikar** [comment]
@rakeshreddyrg09 Thanks for the report. Can you please report this under the umbrella issue #14666?

**Comment by rakeshreddyrg09** [comment]
I have resolved this issue by adding this parameter in additionalOptions field
```yaml
additionalOptions:

    - name: hostname_strict_https
      value: "false"
```
here is the updated file
```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  instances: 1
  db:
    vendor: postgres
    host: keycloak-ha-primary.test.svc
    usernameSecret:
      name: keycloak-ha-pguser-keycloak-kcdb
      key: user
    passwordSecret:
      name: keycloak-ha-pguser-keycloak-kcdb
      key: password
    database: keycloak-kcdb0
    port: 5432
  hostname:
    hostname: keycloak.test-sample.com:8080
    adminUrl: http://keycloak.test-sample.com:8080/
    strictBackchannel: true
    strict: true
  additionalOptions:
    - name: proxy
      value: "edge"
    - name: hostname_strict_https
      value: "false"
  ingress:
    enabled: false
  http:
    httpEnabled: true
    httpPort: 8080
    ```
