### ISSUE TITLE
Keycloak Operator generates wrong PrometheusRules

### ISSUE THREAD

**Issue by droslean** [keycloak/keycloak#22977]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

operator

### Describe the bug

```yaml
spec:
  groups:
  - name: general.rules
    rules:
    - alert: KeycloakJavaNonHeapThresholdExceeded
      annotations:
        message: '{{ printf "%0.0f" $value }}% nonheap usage of {{ $labels.area }}
          in pod {{ $labels.pod }}, namespace {{ $labels.namespace }}.'
      expr: 100 * jvm_memory_bytes_used{area="nonheap",namespace="my-keycloak-operator"}
        / jvm_memory_bytes_max{area="nonheap",namespace="my-keycloak-operator"} >
        90
      for: 1m
      labels:
        severity: warning
    - alert: KeycloakJavaGCTimePerMinuteScavenge
      annotations:
        message: Amount of time per minute spent on garbage collection of {{ $labels.area
          }} in pod {{ $labels.pod }}, namespace {{ $labels.namespace }} exceeds 90%.
          This could indicate that the available heap memory is insufficient.
      expr: increase(jvm_gc_collection_seconds_sum{gc="PS Scavenge",namespace="my-keycloak-operator"}[1m])
        > 1 * 60 * 0.9
      for: 1m
      labels:
        severity: warning
    - alert: KeycloakJavaGCTimePerMinuteMarkSweep
      annotations:
        message: Amount of time per minute spent on garbage collection of {{ $labels.area
          }} in pod {{ $labels.pod }}, namespace {{ $labels.namespace }} exceeds 90%.
          This could indicate that the available heap memory is insufficient.
      expr: increase(jvm_gc_collection_seconds_sum{gc="PS MarkSweep",namespace="my-keycloak-operator"}[1m])
        > 1 * 60 * 0.9
      for: 1m
      labels:
        severity: warning
    - alert: KeycloakJavaDeadlockedThreads
      annotations:
        message: Number of threads in deadlock state of {{ $labels.area }} in pod
          {{ $labels.pod }}, namespace {{ $labels.namespace }}
      expr: jvm_threads_deadlocked{namespace="my-keycloak-operator"} > 0
      for: 1m
      labels:
        severity: warning
    - alert: KeycloakLoginFailedThresholdExceeded
      annotations:
        message: More than 50 failed login attempts for realm {{ $labels.realm }},
          provider {{ $labels.provider }}, namespace {{ $labels.namespace }} over
          the last 5 minutes. (Rate of {{ printf "%0f" $value }})
      expr: rate(keycloak_failed_login_attempts{namespace="my-keycloak-operator"}[5m])
        * 300 > 50
      for: 5m
      labels:
        severity: warning
    - alert: KeycloakInstanceNotAvailable
      annotations:
        message: Keycloak instance in namespace {{ $labels.namespace }} has not been
          available for the last 5 minutes.
      expr: (1 - absent(kube_pod_status_ready{namespace="my-keycloak-operator", condition="true"}
        * on (pod) group_left (label_component) kube_pod_labels{label_component="keycloak",
        namespace="my-keycloak-operator"})) == 0
      for: 5m
      labels:
        severity: critical
    - alert: KeycloakAPIRequestDuration90PercThresholdExceeded
      annotations:
        message: More than 10% the RH SSO API endpoints in namespace {{ $labels.namespace
          }} are taking longer than 1s for the last 5 minutes.
      expr: (sum(rate(keycloak_request_duration_bucket{le="1000.0", namespace="my-keycloak-operator"}[5m]))
        by (job) / sum(rate(keycloak_request_duration_count{namespace="my-keycloak-operator"}[5m]))
        by (job)) < 0.90
      for: 5m
      labels:
        severity: warning
    - alert: KeycloakAPIRequestDuration99.5PercThresholdExceeded
      annotations:
        message: More than 0.5% of the RH SSO API endpoints in namespace {{ $labels.namespace
          }} are taking longer than 10s for the last 5 minutes.
      expr: (sum(rate(keycloak_request_duration_bucket{le="10000.0", namespace="my-keycloak-operator"}[5m]))
        by (job) / sum(rate(keycloak_request_duration_count{namespace="my-keycloak-operator"}[5m]))
        by (job)) < 0.995
      for: 5m
      labels:
        severity: warning
    - alert: KeycloakDatabaseNotAvailable
      annotations:
        message: RH SSO database in namespace {{ $labels.namespace }} is not available
          for the last 5 minutes.
      expr: '(1 - absent(kube_pod_status_ready{namespace="my-keycloak-operator", condition="true"}
        * on (pod) group_left (label_component) kube_pod_labels{label_component="database",
        namespace="my-keycloak-operator"})) == 0 '
      for: 5m
      labels:
        severity: critical
```

Those `PrometheusRules` are being created automatically by the operator. However, those rules are wrong.

How can I configure the operator NOT to generate them?

### Version

v19.0.3

### Expected behavior

I would expect the operator to generate the correct metrics

### Actual behavior

The `namespace` label in all of the rules is wrong since the `kube-state-metrics` uses the `exported_namespace` label instead. 

### How to Reproduce?

Just run the operator with a kube-state-metrics and Prometheus in the cluster
