### ISSUE TITLE
Expose container resources configuration on top level of the CR spec

### ISSUE THREAD

**Issue by Daniel-Fan** [keycloak/keycloak#23182]
### Description

Currently KeyCloak CR supports to configure
- the replicas of Statefulset by updating `.spec.instance`
- container resources via pod template
```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: cs-keycloak
  namespace: keycloak
spec:
  instances: 2
  unsupported:
    podTemplate:
      spec:
        containers:
          - resources:
              limits:
                cpu: 1000m
                memory: 1Gi
              requests:
                cpu: 1000m
                memory: 1Gi
```

Could we considering exposing resources configurations like CPU limits and requests at the top level of CR like `.spec.instance`?
```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: cs-keycloak
  namespace: keycloak
spec:
  instances: 2
  resources:
    limits:
      cpu: '1'
      ephemeral-storage: 512Mi
      memory: 1Gi
    requests:
      cpu: '1'
      ephemeral-storage: 128Mi
      memory: 1Gi
```

### Motivation

It could provide production-ready resource configuration to fine tune those values for performance evaluation.
