### ISSUE TITLE
Existing realm can not be exported

### ISSUE THREAD

**Issue by Nefcanto** [keycloak/keycloak#23493]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

import-export

### Describe the bug

Using your [docs](https://www.keycloak.org/server/importExport) I have crafted the following command to export my `Development` realm into a file:

```
bin/kc.sh export --dir ExportedData --realm Development --users realm_file
```

When I run it I see a long message, but from it the following lines seem to be relevant:

```
2023-09-23 14:08:03,885 INFO  [org.keycloak.services] (main) KC-SERVICES0034: Export of realm 'Development' requested.
2023-09-23 14:08:04,026 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (import_export) mode
2023-09-23 14:08:04,028 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Cannot invoke "org.keycloak.models.RealmModel.getId()" because "realm" is null
```

Though I have provided the `--realm` flag, it seems that it does not read it.

### Version

Keycloak - Version 22.0.3

### Expected behavior

The following command should export the realm `Development` into the `ExportedData` directory, alongside the users:

```
bin/kc.sh export --dir ExportedData --realm Development --users realm_file
```

### Actual behavior

The data is not exported.

### How to Reproduce?

I have no idea.

**Comment by Nefcanto** [comment]
@ahus1 I didn't understand what you mean by an external database. I have a `docker-compose.yml` file that sets environment variables:

```
        environment:
            - KEYCLOAK_FRONTEND_URL=https://accounts.example.com/
            - PROXY_ADDRESS_FORWARDING=true
            - KC_HOSTNAME=accounts.example.com
            - KEYCLOAK_ADMIN=some_admin_user
            - KEYCLOAK_ADMIN_PASSWORD=some_admin_password
            - KC_DB_URL_HOST=database
            - KC_DB_URL_DATABASE=accounts
            - KC_DB_USERNAME=some_db_user
            - KC_DB_PASSWORD=some_db_password
            - KC_PROXY=edge
            - KC_HTTP_ENABLED=true
            - KC_HOSTNAME_STRICT=false
            - KEYCLOAK_IMPORT=/opt/keycloak/data/import
```

The command to start Keycloak `start --optimized --proxy edge --hostname-strict=false` works just fine, which means that it can read the connection from the environment.

Also the error says `realm is null`. It does not say `DB connection error`.

**Comment by ahus1** [comment]
When reading the original bug description, it is unclear to me how you pass in the environment variables, and how you then run the export command. If some of the environment variables fail to be passed to Keycloak, you might end up with the default development database H2. Once it does that, it will create an empty database with an unkown realm `Development`.

I see you don't pass in the `KC_DB` parameter, which would mean you would use the `dev-file` setup as described in https://www.keycloak.org/server/db which is actually H2, and only supported for development, not for production.

Again, please add more context what parameters you pass to Keycloak either via the environment or via a configuration file.

**Comment by CaptainKrby** [comment]
Hello, I also encountered this error when exporting from a separate instance from my Keycloak cluster.

On a closer look I didn't set the KC_DB environment variables as @ahus1 suggested.

The error isn't explicit I confess, there's nothing to say that the connection was not made with postgres and nevertheless if you set these environment variables in addition, it should work (at least in my case):

KC_HOSTNAME_URL=https://my-keycloak/auth
KC_HOSTNAME_ADMIN_URL=https://mykeycloak/auth
KC_CACHE=local
KC_DB=postgres
KC_DB_URL=jdbc:postgresql://db_host/database
KC_DB_PASSWORD=itsasecret

**Comment by Nefcanto** [comment]
@ahus1 and @CaptainKrby , thank you for following up. I'll add more details.

We create a custom docker image, using this `Dockerfile`:

```
FROM quay.io/keycloak/keycloak:latest as builder

ENV KC_DB=mariadb

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```

Then we use this `docker-compose.yml` to run this image. We use different `docker-compose.yml` files for different projects that we have:

```
version: "3.9"
services: 
    accounts:
        image: holism/accounts
        container_name: SomeProjectAccounts
        working_dir: /opt/keycloak
        ports:
            - 4000:8080
        environment:
            - KEYCLOAK_FRONTEND_URL=https://accounts.example.com/
            - PROXY_ADDRESS_FORWARDING=true
            - KC_HOSTNAME=accounts.example.com
            - KEYCLOAK_ADMIN=something
            - KEYCLOAK_ADMIN_PASSWORD=something
            - KC_DB_URL_HOST=database
            - KC_DB_URL_DATABASE=accounts
            - KC_DB_USERNAME=something
            - KC_DB_PASSWORD=something
            - KC_PROXY=edge
            - KC_HTTP_ENABLED=true
            - KC_HOSTNAME_STRICT=false
            - KEYCLOAK_IMPORT=/opt/keycloak/data/import
        logging:
            driver: none
        restart: always
        command: start --optimized --proxy edge --hostname-strict=false
        depends_on:
            - database
        volumes:
            - /Infra/Accounts/Development.json:/opt/keycloak/data/import/development.json
            - /Infra/Accounts/Themes:/opt/keycloak/themes
    database:
        image: mariadb
        container_name: SomeProjectAccountsDatabase
        ports:
            - 4001:3306
        environment:
            - MARIADB_ROOT_PASSWORD=something
            - MYSQL_DATABASE=accounts
            - MYSQL_USER=something
            - MYSQL_PASSWORD=something
        volumes:
            - /SomeProject/Accounts/Databases:/var/lib/mysql 
        logging:
            driver: none
        restart: always
    admin:
        image: adminer
        container_name: SomeProjectAccountsAdminer
        restart: always
        logging:
            driver: none
        ports:
            - 4002:8080
        environment:
            - ADMINER_DEFAULT_SERVER=database
```

Then we create a container based on this `docker-compose.yml`. Once it's up and running, when we want to export a realm, we enter the container using `docker exec -it SomeProjectAccount bash` and from there we run the command that is at the beginning of this issue. As you can see, `KC_DB` is provided in the docker image. Other variables are provided in the compose file. It works just fine. Everything works. The only problem is this null realm when being exported.
