### ISSUE TITLE
Updating Keycloak 21 to 22 with rolling update

### ISSUE THREAD

**Issue by crashday** [keycloak/keycloak#23542]
### Description

I am getting the following errors when trying to perform a rolling update from Keycloak version 21 to version 22.

 2023-09-06 19:05:09,016 ERROR [org.infinispan.CLUSTER] (jgroups-6,keycloak-2-26221) ISPN000475: Error processing response for request 2 from keycloak-1-4495: java.io.EOFException
	at org.infinispan.marshall.core.AbstractBytesObjectInput.checkPosLength(AbstractBytesObjectInput.java:261)
	at org.infinispan.marshall.core.AbstractBytesObjectInput.readByte(AbstractBytesObjectInput.java:107)
	at org.infinispan.commons.marshall.MarshallUtil.unmarshallSize(MarshallUtil.java:426)
	at org.infinispan.commons.marshall.MarshallUtil.unmarshallCollection(MarshallUtil.java:271)
	at org.infinispan.commons.marshall.MarshallUtil.unmarshallCollection(MarshallUtil.java:295)
	at org.infinispan.topology.CacheStatusResponse$Externalizer.readObject(CacheStatusResponse.java:86)
	at org.infinispan.topology.CacheStatusResponse$Externalizer.readObject(CacheStatusResponse.java:70)
	at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
	at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
	at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
	at org.infinispan.marshall.core.BytesObjectInput.readObject(BytesObjectInput.java:32)
	at org.infinispan.remoting.responses.SuccessfulResponse$Externalizer.readObject(SuccessfulResponse.java:71)
	at org.infinispan.remoting.responses.SuccessfulResponse$Externalizer.readObject(SuccessfulResponse.java:63)
	at org.infinispan.marshall.core.GlobalMarshaller.readWithExternalizer(GlobalMarshaller.java:727)
	at org.infinispan.marshall.core.GlobalMarshaller.readNonNullableObject(GlobalMarshaller.java:708)
	at org.infinispan.marshall.core.GlobalMarshaller.readNullableObject(GlobalMarshaller.java:357)
	at org.infinispan.marshall.core.GlobalMarshaller.objectFromObjectInput(GlobalMarshaller.java:191)
	at org.infinispan.marshall.core.GlobalMarshaller.objectFromByteBuffer(GlobalMarshaller.java:220)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processResponse(JGroupsTransport.java:1570)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport.processMessage(JGroupsTransport.java:1480)
	at org.infinispan.remoting.transport.jgroups.JGroupsTransport$ChannelCallbacks.up(JGroupsTransport.java:1685)
	at org.jgroups.JChannel.up(JChannel.java:733)
	at org.jgroups.stack.ProtocolStack.up(ProtocolStack.java:921)
	at org.jgroups.protocols.FRAG2.up(FRAG2.java:138)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:245)
	at org.jgroups.protocols.FlowControl.up(FlowControl.java:245)
	at org.jgroups.protocols.pbcast.GMS.up(GMS.java:845)
	at org.jgroups.protocols.pbcast.STABLE.up(STABLE.java:226)
	at org.jgroups.protocols.UNICAST3.deliverMessage(UNICAST3.java:1052)
	at org.jgroups.protocols.UNICAST3.addMessage(UNICAST3.java:794)
	at org.jgroups.protocols.UNICAST3.handleDataReceived(UNICAST3.java:776)
	at org.jgroups.protocols.UNICAST3.up(UNICAST3.java:425)
	at org.jgroups.protocols.pbcast.NAKACK2.up(NAKACK2.java:658)
	at org.jgroups.protocols.VERIFY_SUSPECT2.up(VERIFY_SUSPECT2.java:105)
	at org.jgroups.protocols.FailureDetection.up(FailureDetection.java:180)
	at org.jgroups.protocols.FD_SOCK2.up(FD_SOCK2.java:188)
	at org.jgroups.protocols.MERGE3.up(MERGE3.java:274)
	at org.jgroups.protocols.Discovery.up(Discovery.java:294)
	at org.jgroups.stack.Protocol.up(Protocol.java:314)
	at org.jgroups.protocols.TP.passMessageUp(TP.java:1178)
	at org.jgroups.util.SubmitToThreadPool$SingleMessageHandler.run(SubmitToThreadPool.java:100)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-09-06 19:05:17,692 ERROR [org.jgroups.protocols.TCP] (Connection.Receiver [10.187.203.120:48425 - 10.187.94.69:7800]-8,keycloak-2-26221) JGRP000030: keycloak-2-26221: failed handling incoming message: java.lang.IllegalArgumentException: invalid magic number 256; needs to be in range [0..100]
	at org.jgroups.conf.ClassConfigurator.create(ClassConfigurator.java:136)
	at org.jgroups.util.Util.readSizeStreamable(Util.java:1874)
	at org.jgroups.ObjectMessage.readPayload(ObjectMessage.java:144)
	at org.jgroups.BaseMessage.readFrom(BaseMessage.java:314)
	at org.jgroups.util.Util.readMessageBatch(Util.java:1482)
	at org.jgroups.protocols.TP.handleMessageBatch(TP.java:1267)
	at org.jgroups.protocols.TP.receive(TP.java:1259)
	at org.jgroups.blocks.cs.BaseServer.receive(BaseServer.java:204)
	at org.jgroups.blocks.cs.TcpConnection$Receiver.run(TcpConnection.java:307)
	at java.base/java.lang.Thread.run(Thread.java:833)

2023-09-06 19:05:18,297 ERROR [org.jgroups.protocols.TCP] (Connection.Receiver [10.187.203.120:48425 - 10.187.94.69:7800]-8,keycloak-2-26221) JGRP000030: keycloak-2-26221: failed handling incoming message: java.lang.IllegalArgumentException: invalid magic number 256; needs to be in range [0..100]
	at org.jgroups.conf.ClassConfigurator.create(ClassConfigurator.java:136)
	at org.jgroups.util.Util.readSizeStreamable(Util.java:1874)
	at org.jgroups.ObjectMessage.readPayload(ObjectMessage.java:144)
	at org.jgroups.BaseMessage.readFrom(BaseMessage.java:314)
	at org.jgroups.util.Util.readMessageBatch(Util.java:1482)
	at org.jgroups.protocols.TP.handleMessageBatch(TP.java:1267)
	at org.jgroups.protocols.TP.receive(TP.java:1259)
	at org.jgroups.blocks.cs.BaseServer.receive(BaseServer.java:204)
	at org.jgroups.blocks.cs.TcpConnection$Receiver.run(TcpConnection.java:307)
	at java.base/java.lang.Thread.run(Thread.java:833)

i use this configuration:

- name: KC_CACHE
  value: "ispn"
- name: KC_CACHE_STACK
  value: "kubernetes"
- name: JAVA_OPTS_APPEND
  value: "-Djgroups.dns.query={{headless-service}}.{{namespace}}.svc.cluster.local"
  

i added new headless service and changed the jgroups.dns.query parameter value but still all pods can discover each other, after that i created these steps to update keycloak 21 to 22

1.  Create a new headless service and add a different pod selector for the new headless service
```
kind: Service
apiVersion: v1
metadata:
  name: keycloak-headless-v2
...
spec:
...
  selector:
    idp_pod_selector: idp-cluster-2
status:
  loadBalancer: {}
```

2.  Make sure the old headless service not discovered by new pods by keeping only the idp_pod_selector selector label
```
kind: Service
apiVersion: v1
metadata:
  name: keycloak-headless
...
spec:
...
  selector:
    idp_pod_selector: idp-cluster-1
status:
  loadBalancer: {}
```
3.  Specify the pod selector name for the headless service in the StatefulSet. Provide the new headless service name to -Djgroups.dns.query.
```
spec:
  replicas: 4
  selector:
    matchLabels:
      app.kubernetes.io/instance: keycloak
      app.kubernetes.io/name: keycloak
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: keycloak
        app.kubernetes.io/name: keycloak
        idp_pod_selector: idp-cluster-2
...
          env:
            - name: JAVA_OPTS #or JAVA_OPTS_APPEND depends on your configuration
              value: >-
                -Djgroups.dns.query=keycloak-headless-v2.{{namespace}}.svc.cluster.local
```

    These steps should help prevent the issue when upgrading to Keycloak 22 with JGroups discovery while sharing the cache with older versions. After completing these steps, i can successfully update keycloak 22.
    
    When the old version and the new version are connected to the same headless service, the old pods are also discovering the new pods. It might be more appropriate to configure this mechanism so that only the new pods can discover the old ones. Additionally, it would be beneficial to include a name or label in the JGroups configuration for the cluster
 

### Motivation

it could be easier to update between keycloak versions
