### ISSUE TITLE
Readiness Probe dont fail if KC pod is isolated

### ISSUE THREAD

**Issue by cjabrantes** [keycloak/keycloak#23798]
### Before reporting an issue

- [X] I have searched existing issues
- [X] I have reproduced the issue with the [latest nightly release](https://github.com/keycloak/keycloak/releases/tag/nightly)

### Area

core

### Describe the bug

Hi all,

I am deployed KC with the operator, 2 instances.

I m testing what happens if KC gets isolated, network partition, i m doing this with network policies.
This will cut the KC instance from reaching anything.

### Version

22.0.3

### Expected behavior

I expected that the probe would fail and the pod to get removed from available endpoints.

### Actual behavior

The endpoint remains available,the probe still succeeds and the endpoints is only removed when containers crashes.

### How to Reproduce?

Deploy KC via operator 
deploys 2 instances
drop ingress and egress traffic with network policies

**Comment by vmuzikar** [comment]
Seems more related to Quarkus dist, reassigning.

**Comment by cjabrantes** [comment]
To clarify, i expect that the pod readiness probe fails because he can't reach the DB and i would expect that the readiness probe would make this check.

**Comment by vmuzikar** [comment]
The Operator does not enable metrics hence the DB checks are not present in the probes. Hence this is an expected behaviour with current configuration.

We might want to consider enabling metrics by default in Operator deployments but we'd probably need to implement #19334 first.

CC @shawkins

**Comment by cjabrantes** [comment]
What is i enable metrics in the manifest, would that work?
  additionalOptions:
    - name: metrics-enabled
      value: "tru"

**Comment by vmuzikar** [comment]
Yeah, but bear in mind to prohibit access to them on your Ingress.

**Comment by cjabrantes** [comment]
Related ingress i m following "Exposed path recommendations" from https://www.keycloak.org/server/reverseproxy, meaning:
/realms/
/resources/
/robots.txt
/js/

all the rest is getting 404.

I will test and update you.

**Comment by cjabrantes** [comment]
Hi,

I tested with the same result, but i missed one very important detail that i believe is in the end "the problem".
Any reason why the readiness probe are being set with:
    readinessProbe:
      failureThreshold: 250

    livenessProbe:
      failureThreshold: 150

So only after 250 failures in a row the pod get into not ready state.

**Comment by cjabrantes** [comment]
@vmuzikar Any way of overwrite the probe or the failureThreshold parameter?  Thanks.

**Comment by vmuzikar** [comment]
You can overwrite the probes via podTemplate field in the CR.

**Comment by cjabrantes** [comment]
i m missing something, i added the following values to manifest:

```
  unsupported:
    podTemplate:
      spec:
        containers:
          readinessProbe:
            failureThreshold: 5
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                  - kc-test
              topologyKey: kubernetes.io/hostname
```

When i try to apply it, i get:
`strict decoding error: unknown field "spec.unsupported.podTemplate.spec.containers.readinessProbe"`

Before i just had the affinity rules and was working fine, I checked the CRD and containers.readinessProbe.failureThreshold.

Any lights on what i m missing?

Thanks

**Comment by cjabrantes** [comment]
It worked like a charm, adding just for the reference:

```
  unsupported:
    podTemplate:
      spec:
        containers:
          - readinessProbe:
              failureThreshold: 5
              httpGet:
                path: /health/live
                port: 8080
                scheme: "HTTP"
              initialDelaySeconds: 20
              periodSeconds: 2
              successThreshold: 1
              timeoutSeconds: 1
```

Thanks for all the help!
