### ISSUE TITLE
Keycloak 22 Admin Console Redirecting To Port 443 in 

### ISSUE THREAD

**Issue by xu001186** [keycloak/keycloak#24696]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

I am running the keycloack operator in the k8s 1.27.5 ,
This is the config I am using:
```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  instances: 2
  db:
    vendor: postgres
    host: acid-minimal-cluster
    usernameSecret:
      name: keycloak.acid-minimal-cluster.credentials.postgresql.acid.zalan.do
      key: username
    passwordSecret:
      name: keycloak.acid-minimal-cluster.credentials.postgresql.acid.zalan.do
      key: password
  http:
    tlsSecret: example-tls-secret
  hostname:
    hostname: test.keycloak.org
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
    app.kubernetes.io/instance: example-kc
  name: example-kc-port
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app: keycloak
    app.kubernetes.io/instance: example-kc
    app.kubernetes.io/managed-by: keycloak-operator
  sessionAffinity: None
  type: NodePort
```
After the keycloak is up running , I can access the https://test.keycloak.org:31151 , however , when I clicked on the "Administrator Console", it redirectes to https://test.keycloak.org/realms/master/protocol/openid-connect/3p-cookies/step1.html 

### Version

22.0.5

### Expected behavior

It redirects to the correct port https://test.keycloak.org:31151/realms/master/protocol/openid-connect/3p-cookies/step1.html

### Actual behavior

It redirects to the default port https://test.keycloak.org/realms/master/protocol/openid-connect/3p-cookies/step1.html

### How to Reproduce?

1. Install the keyclock operator by https://www.keycloak.org/operator/installation
2. Apply the config from bug description 
3. Add the node IP and hostname test.keycloak.org to the /etc/hosts file
4. Access https://test.keycloak.org:31151/, and click on "Administrator Console"
