### ISSUE TITLE
Add truststores to keycloak cr

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#24798]
### Description

For #23742 the Keycloak cr will be enhanced to support the truststore-paths option.  Based upon the server support, the cr change should be as simple as:

```
spec:
  ...
  trustStores:
    - name: my-truststore
      secret: my-secret 
    ...
 ```

We could also support configmaps in addition to secrets.

**Comment by ozbillwang** [comment]
So any reason this request is not planned?

in RHBK (redhat build of keycloak), it does support truststore (https://access.redhat.com/solutions/7051525) 

```
additionalOptions:
  - name: spi-truststore-file-file
    secret:
      name: truststore-example-secret
      key: path
  - name: spi-truststore-file-password
    secret:
      name: truststore-example-secret
      key: password
unsupported:
  podTemplate:
    spec:
      containers:
        - volumeMounts:
            - name: truststore
              mountPath: /opt/truststore                                                                                                                                                                         
      volumes:
        - name: truststore
          secret: 
            secretName: truststore-file-secret
```

the problem here is, RHBK , Redhat Build of Keycloak, (**apiVersion: k8s.keycloak.org/v2alpha1**) has limited CRD support: The current RHBK operator only ships **Keycloak** and **KeycloakRealmImport** CRDs under k8s.keycloak.org/v2alpha1. Crucial CRDs like **KeycloakRealm, KeycloakClient, and KeycloakUser are missing.** The setting , include ldap, clients, realm, etc, are not persistant, so keycloak CRD will reset the settings , these setting, done via keycloakrealmImport are gone. It is very annoying. 

<img width="807" height="404" alt="Image" src="https://github.com/user-attachments/assets/07348da7-ac2d-4fd4-a2e5-51b9a56cb5c8" />

So we have to back to RHSSO (**apiVersion: keycloak.org/v1alpha1**) , but unlucky, truststore doesn't suport yet
