### ISSUE TITLE
error=cookie_not_found Could not find cookie: KEYCLOAK_IDENTITY

### ISSUE THREAD

**Issue by david-curran-90** [keycloak/keycloak#24821]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

Out client is having an issue logging in with their AD IDP SSO when logging into our realm in the application

Logs output

```
2023-11-17 13:44:20,629 WARN  [org.keycloak.events] (executor-thread-1) type=IDENTITY_PROVIDER_LOGIN_ERROR, realmId=application, clientId=null, userId=null, ipAddress=x.x.x.x, error=cookie_not_found
2023-11-17 13:44:20,806 DEBUG [org.keycloak.services.util.CookieHelper] (executor-thread-1) Could not find cookie KEYCLOAK_IDENTITY, trying KEYCLOAK_IDENTITY_LEGACY
2023-11-17 13:44:20,807 DEBUG [org.keycloak.services.managers.AuthenticationManager] (executor-thread-1) Could not find cookie: KEYCLOAK_IDENTITY
```

The customer has third part cookies disabled and cannot enable them due to company policy. They have added the application and keycloak URLs to the allowed list for third party cookies but still no luck.

Is there a way to log in without this cookie or should this not be an issue? Some other cause for the login failure?

Thanks

### Version

22.0.0

### Expected behavior

User logs in via SSO 

### Actual behavior

User is blocked as cookie isn't created

### How to Reproduce?

Disable third party cookies
Log in with AD IDP

### Anything else?

This customer cannot have third part cookies enabled due to company policy

**Comment by sschu** [comment]
Did you check how the cookie is set by Keycloak and if it is returned by the browser. KEYCLOAK_IDENTITY is not a third-party cookie afaik but a normal session cookie and it is required to identify the user.

**Comment by david-curran-90** [comment]
>   if it is returned by the browser

No such cookie seems to be present in the browser when looking with developer tools.

The login flow is IDP

* Customer hits URL that directs to keycloak (kcl.us.com) with relay state set
* Customer clicks the SSO link (ADFS)
* Login happens
* Customer should be redirected to our app (app.us.com)

Is there maybe some missing configuration?

**Comment by sschu** [comment]
There is no special configuration necessary. Keycloak sets a cookie and the browser should send it back next time it visits Keycloak.

**Comment by david-curran-90** [comment]
The customer confirms that the cookie is not created at all. What could be the cause of this? Mis matched URLs?

**Comment by sschu** [comment]
The typical cause is that cookies are disabled (at least for the site in question). But that really is up to the browser...

**Comment by torquato76** [comment]
I am facing the same error. Got a solution.
In my case, I configured SAML SSO in OKTA, and when clicking on the application shortcut it calls keycloack and displays the message.

Cookies not found. Please make sure cookies are enabled in your browser.

I appreciate any help.

**Comment by frickman** [comment]
I faced the same error, but it turned out it wasn't related to cookies. Upon further investigation of the log files, there was an error in the redirect url coming back from the identity provider which keycloak was not able to handle properly.

> (my-appliction)+is+not+configured+as+a+multi-tenant+application.+Usage+of+the+%2fcommon+endpoint+is+not+supported+for+such+applications+created7.+Use+a+tenant-specific+endpoint+or+configure+the+application+to+be+multi-tenant.

So I had a typo in the tenant Id which led to keycloak having a "cookie error". Fixing it resolved the issue.

**Comment by jonkoops** [comment]
I am going to close this issue as there are no reliable steps to reproduce it. We're aware of issues around 3rd-party cookies and their phase-out, and are actively working on solutions and alternatives.

**Comment by jmkolbe** [comment]
I'm running into this issue using KeyCloak 24.0.3 in development mode on a network host, i.e. not on my development workstation. I'm running using this Dockerfile:

```
FROM quay.io/keycloak/keycloak:latest

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev"]
```

This docker-compose entry:
```
keycloak:
    image: keycloak
    build:
      context: ./keycloak
      dockerfile: Dockerfile-dev
    container_name: keycloak
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
```

Loading <hostname>:8080 loads the authentication prompt, entering admin/admin shows the "Cookie not found. Please make sure cookies are enabled in your browser." page and the logs say

```
keycloak         | 2024-05-03 11:36:12,064 WARN  [org.keycloak.events] (executor-thread-18) type="LOGIN_ERROR", realmId="3d8e1782-579b-4ab3-8783-cfc5da25634a", clientId="null", userId="null", ipAddress="10.23.1.202", error="cookie_not_found"
```

Maybe I'm missing something, but that's how this issue can be produced reliably on my side.

**Comment by nbiancolin** [comment]
I am experiencing the exact same issue as @jmkolbe, any help or assistance would be greatly appreciated!

**Comment by NiC0x36** [comment]
I also have the exact same issue trying to login on a dockerized keycloak (same error witth 24.0.1, 24.0.4) running on a debian server in our network, **BUT** apparently it works using Keycloak 23.0!

cc @jmkolbe, @nbiancolin

**Comment by NiC0x36** [comment]
I found the issue: 
I opened Keycloak on the server over the hostname (`http://myserver:8080`) instead of the IP (`http://192.168.0.123:8080`). It works for me using the IP. 

I suspect using Keycloak over the hostname only works with Keycloak 23, due to increased security since Keycloak 24. Keycloak 24 seems to demand configured HTTPS / SSL now, even when starting with `app-dev`, which I actually did not configure yet.

Maybe a clearer error message or warning at startup would be helpful?

**Comment by uniquejava** [comment]
Me too, I can use IP address (`192.168...`, but not hostname (`offline`) that I defined in `/etc/hosts`. I have been using 24.0.2 for some time.

<img width="817" alt="image" src="https://github.com/keycloak/keycloak/assets/1049271/021bc064-db45-464b-9128-bd3a176635c6">

**Comment by rsoika** [comment]
Yes, falling back to version `quay.io/keycloak/keycloak:23.0.5` works for me. 
And yes - the error message is maybe confusing?

**Comment by zhfkt** [comment]
The same issue. Revert to keycloak 23 works for me as well.

**Comment by jonkoops** [comment]
Likely your browser is blocking cookies because you are serving the application from an non-secure context. Try using a [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts#when_is_a_context_considered_secure), such as `localhost` or `whatever.localhost`.

**Comment by jonkoops** [comment]
Also please do not comment on closed issues if you are experiencing issues with a new release. Log a new issue with steps to reproduce, but make sure that your server is [properly configured](https://www.keycloak.org/server/configuration) first.

**Comment by jonkoops** [comment]
> It has something to do with required SSL/HTTPS connections now.

The connection to the Keycloak server must indeed be secure, but only in production environments. Do NOT disable TLS requirements in a production environment, this will lead to security issues.

Like I mentioned before in https://github.com/keycloak/keycloak/issues/24821#issuecomment-2173010754, you need to be on a secure context for Keycloak to work properly. On a local machine specific hostnames are whitelisted by the browser, which do not require TLS to be considered secure.

**Comment by rsoika** [comment]
Hi @jonkoops, but what than is the reason that verison >=24 does not work in a docker-compose environment. 
In my docker-compose file I start keycloak and my app that uses keycloak. I guess 'localhost' in such a szenario does not work as I have to define some static host name on my host to enable the communication between my app and keycloak? (I agree that on production all is much easier ;-)

This is the docker-compose file I use:

```yaml
version: "3"
services:

  ##################################
  # My app
  ##################################
  app:
    image: imixs/imixs-office-workflow
    # Mapping the host ip to the container 
    # This setting is used for local testing only
    # Wildfly can access the keycloak server via the external host address
    extra_hosts:
      - "keycloak.imixs.local:host-gateway"
    ports:
      - "8080:8080"
      - "8787:8787"

  ##################################
  # Keycloak Server
  ##################################
  dbkeycloak:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: adminadmin
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak
    volumes: 
      - dbkeycloak:/var/lib/postgresql/data
  keycloak:
    # latest 23.0.5
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
    command:
      - start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=adminadmin
    # DATABASE Config
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://dbkeycloak:5432/keycloak
      - KC_DB_USER=keycloak
      - KC_DB_PASSWORD=adminadmin
    ports:
      - "8084:8080"

volumes:
  dbkeycloak:
```
