### ISSUE TITLE
Operator is missing CRDs metadata in CSV

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#24984]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

Compare [22.0.5](https://github.com/k8s-operatorhub/community-operators/blob/main/operators/keycloak-operator/22.0.5/manifests/keycloak-operator.clusterserviceversion.yaml#L48-L59) and [23.0.0](https://github.com/k8s-operatorhub/community-operators/blob/main/operators/keycloak-operator/23.0.0/manifests/keycloak-operator.clusterserviceversion.yaml#L48-L55).
<img width="1121" alt="Screenshot 2023-11-23 at 18 25 38" src="https://github.com/keycloak/keycloak/assets/13906855/43d09fc1-df47-4502-8ff7-6e375cf1daf5">

### Version

23.0.0

### Expected behavior

Missing name and desc for CRDs.

### Actual behavior

Metadata present like:
```yaml
spec:
  customresourcedefinitions:
    owned:
      - kind: KeycloakRealmImport
        description: Represents a Keycloak Realm Import
        displayName: KeycloakRealmImport
        name: keycloakrealmimports.k8s.keycloak.org
        version: v2alpha1
      - kind: Keycloak
        description: Represents a Keycloak Instance
        displayName: Keycloak
        name: keycloaks.k8s.keycloak.org
        version: v2alpha1
```

### How to Reproduce?

https://operatorhub.io/operator/keycloak-operator
