### ISSUE TITLE
[keycloak-operator] sets --optimize when setting a custom image, breaking the normal startup workflow

### ISSUE THREAD

**Issue by stefanandres** [keycloak/keycloak#25000]
### Description

I've tried to use a custom image with the keycloak operator, but it looks like the operator adds `--optimize` to its startup-args when setting the spec.image key.

```
❯ cat keycloak.yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: test-keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgres-db
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
  image: quay.io/keycloak/keycloak:22.0.5
  ```
  
  This breaks the normal startup workflow as you *must* run some build command before.
  I'd expect the --optimize flag to be optional and that this must be set explicitly. 
  As far as I can see, there currently is not way to disable this behavior.
  
  Thanks!

### Details

Operator-Version: quay.io/keycloak/keycloak-operator:22.0.5
