### ISSUE TITLE
Unexpected Application Error when clicking "Cancel" on user creation page

### ISSUE THREAD

**Issue by RomanKosovnenko** [keycloak/keycloak#25051]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

There are two types of errors that occur in 2 similar scenarios.
Both described in `How to Reproduce?` part of the issue.
I think, they are similar.

Errors occur when I'm starting the process of creating a new user and then cancel it by click on `Cancel` button.

### Version

23

### Expected behavior

In both scenarios I expect to go back to list of users page of corresponding realm.

### Scenario 1: 
redirect to `http://localhost:9080/admin/master/console/#/1b052167-f4e4-41c9-bba1-79c5b547f598/users`
with next content:

> Unexpected Application Error!
> Network response was not OK.
> Error: Network response was not OK.
>     at cc (http://localhost:9080/resources/gzwwv/admin/keycloak.v2/assets/index-46ucf2q6.js:48:296627)
>     at async #i (http://localhost:9080/resources/gzwwv/admin/keycloak.v2/assets/index-46ucf2q6.js:48:298999)

### Scenario 2: 
redirect to `http://localhost:9080/admin/foo/console/#/undefined/users`
The page shows `undefined` realm in realm selector and error alert with:
> No users found due to Realm not found.

### How to Reproduce?

I started a Keycloak as a docker container. Here is an example of docker compose:

```
version: '3'

services:
  keycloak-database:
    image: postgres:16
    environment:
      TZ: Europe/Berlin
      POSTGRES_DB: keycloakdb
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: passw0rd!
    restart: unless-stopped

  keycloak-service:
    image: keycloak/keycloak:23.0
    ports:
      - "9080:8080"
    command: >
      start-dev --hostname-strict=false
    environment:
      TZ: Europe/Berlin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: passw0rd!
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-database/keycloakdb
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: passw0rd!
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    restart: unless-stopped
    depends_on:
      - keycloak-database
```

### Scenario 1:

1. Go to [http://localhost:9080/](http://localhost:9080/)
2. Click on `Administration Console`
3. Enter login `admin` and password `passw0rd!`
4. Click `Sign in`
5. Click on `Users` link on the left sidebar
6. Click `Add user` button
7. Click `Cancel`

### Scenario 2:

1. Login in admin console
2. Create a new realm `foo`
3. Create a group with name `admin` for realm `foo`
4. Open group details for `admin` group
5. Assign next roles: `manage-users`, `view-users`
6. Create user `bar` with some password
7. Add `bar` user to the `admin` group
8. Open [http://localhost:9080/admin/foo/console/](http://localhost:9080/admin/foo/console/) in incognito mode
9. Login with as `bar` user
10. Click on `Users` link on the left sidebar
11. Click `Add user` button
12. Click `Cancel`
