### ISSUE TITLE
Configuring Truststore doc is misleading

### ISSUE THREAD

**Issue by pgodowski** [keycloak/keycloak#25094]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

The doc https://www.keycloak.org/server/keycloak-truststore is not clear enough saying that as soon as the custom trust store is added, then Keycloak no longer falls back to the standard Java Truststore (`cacerts` file).

I would be expecting that the fallback is still there, but based on my experiments it's not the case.

Ideally I would like to:
- clarify how to have both custom trust store + java standard truststore fallback
- if it's currently not possible, update the docs.

There are some related discussions like https://github.com/keycloak/keycloak/issues/9784 and others linked, but none of them are clear on the Java truststore fallback.

### Version

22.0.5

### Expected behavior

Keycloak does fallback to the Java trust store.

### Actual behavior

Keycloak ignores the Java trust store as soon as the custom trust store is provided.

### How to Reproduce?

Follow https://www.keycloak.org/server/keycloak-truststore, specifying the custom trust store with empty trust store. From now on, Keycloak cannot be configured with any OIDC provider, even those who provide the well-known / trusted certificates.

**Comment by pgodowski** [comment]
@vmuzikar would appreciate your perspective on the custom truststores.
 fyi @Jamstah

**Comment by shawkins** [comment]
@pgodowski this will be addressed in 24 with #24148 and the corrsponding pr - the existing spi-truststore options will be deprecated in favor of a single / simpler mechanism for all truststores, and the appropriate fall back to the system truststore was added for the creation of the combined store and for the internal code paths that get a truststore from the spi.  

The question for this issue then is how much should the docs or even the code be updated for a 23 fix release to address these concerns prior to the 24 release.

**Comment by pgodowski** [comment]
BTW, this is how we're going to circumvent the limitation:

We will override the Keycloak operand Pod _entrypoint_ with a custom script (loaded thru the mounted `ConfigMap`), which will overlay the copy of Keycloak JVM `cacerts` file with the customer-provided CA certs (via optionally mounted `ConfigMap` with potentially several CA certificates) saved into a JKS keystore file, in the `emptyDir` volume mount.

Something like:

```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
...
 unsupported:
    podTemplate:
      spec:
        containers:
          - command: <-- HERE
              - /bin/sh
              - /mnt/startup/keycloak-entrypoint.sh
 ...
            volumeMounts: <-- HERE
              - mountPath: /mnt/truststore
                name: truststore-volume
              - mountPath: /mnt/startup
                name: startup-volume
              - mountPath: /mnt/trust-ca
                name: trust-ca-volume
        volumes: <-- HERE
          - emptyDir:
              sizeLimit: 2Mi
            name: truststore-volume
          - configMap:
              name: keycloak-entrypoint
            name: startup-volume
          - configMap:
              name: keycloak-ca-certs
              optional: true
            name: trust-ca-volume
```

and a startup script like:

```sh
#!/usr/bin/env bash

CA_DIR=/mnt/trust-ca
TRUSTSTORE_DIR=/mnt/truststore

echo "Building the truststore file..."

cp /etc/pki/java/cacerts ${TRUSTSTORE_DIR}/keycloak-truststore.jks
chmod +w ${TRUSTSTORE_DIR}/keycloak-truststore.jks

IFS='
'
for cert in `ls ${CA_DIR}`; do
    echo "Importing ${cert} into the truststore file..."
    keytool -importcert -file ${CA_DIR}/${cert} -keystore ${TRUSTSTORE_DIR}/keycloak-truststore.jks -storepass changeit -alias ${cert} -noprompt
done

echo "Truststore file built, starting Keycloak ..."
"/opt/keycloak/bin/kc.sh" "$@" --spi-truststore-file-file=${TRUSTSTORE_DIR}/keycloak-truststore.jks --spi-truststore-file-password=changeit --spi-truststore-file-hostname-verification-policy=WILDCARD
```
loaded into the `ConfigMap`:

```sh
kubectl create configmap keycloak-entrypoint --from-file=keycloak-entrypoint.sh=keycloak-entrypoint.sh
```

We want to ship our product with above. We are aware the it's prone to problems when the default entrypoint for Keycloak would change from what it is today, but we'll keep an eye on this. Any other considerations from the team here?


Also, considering publishing an medium.com article about this, yet if you're ok, I can publish it somewhere on the Keycloak-related forums, etc. If this is worth putting into Keycloak docs, happy to do the writeup for benefit of others.
