### ISSUE TITLE
KC ignoring port behind reverse proxy not running on port 80

### ISSUE THREAD

**Issue by JacopoSciampi** [keycloak/keycloak#25177]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

My nginx config: 

```
        location /auth {
            proxy_pass http://keycloak:8082/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
```

docker-compose: 

```
  keycloak:
    image: jboss/keycloak
    restart: always
    container_name: keycloak
    volumes:
      - keycloak-theme:/opt/jboss/keycloak/themes
    env_file:
      - .env
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
      KEYCLOAK_USER: ${IDP_MASTER_USER}
      KEYCLOAK_PASSWORD: ${IDP_MASTER_PASS}
      PROXY_ADDRESS_FORWARDING: 'true'
    ports:
      - 8082:8080
    depends_on:
      - postgres
    networks:
      - sp_int
```

I can succefully reach kc at mysite.com:88/auth but when I login to the admin area KC totally ignores the port, sending request to mysite.com/auth instead of mysite.com:88/auth/....
I've tried to set every possible flag that should tell KC that is running behind a proxy, but nothing changes. Instead, it just goes in a forever loop.

I know documentation is boring to do, but you guys didn't even try at all.

the only solution is to set nginx to the port 80, which is a BS thing to do in my case since I do not want keycloak to be available on that port.

### Version

JBOSS latest

### Expected behavior

As described above.

### Actual behavior

As described above.

### How to Reproduce?

As described above.

### Anything else?

Do a proper documentation.
