### ISSUE TITLE
Unable to start after updating Docker container

### ISSUE THREAD

**Issue by felixtech-msp** [keycloak/keycloak#25235]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

After updating the Docker container, Keycloak will no longer start only showing a completely useless message.

```
Changes detected in configuration. Updating the server image.

Invalid value for option 'kc.features': account-api, account2, account3, admin-api, admin-fine-grained-authz, admin2, authorization, ciba, client-policies, client-secret-rotation, declarative-user-profile, device-flow, docker, dpop, dynamic-scopes, fips, impersonation, js-adapter, kerberos, linkedin-oauth, map-storage, par, preview, recovery-codes, scripts, step-up-authentication, token-exchange, transient-users, update-email, web-authn. Expected values are: account-api, account2, account3, admin-api, admin-fine-grained-authz, admin2, authorization, ciba, client-policies, client-secret-rotation, declarative-user-profile, device-flow, docker, dpop, dynamic-scopes, fips, impersonation, js-adapter, kerberos, linkedin-oauth, map-storage, par, preview, recovery-codes, scripts, step-up-authentication, token-exchange, transient-users, update-email, web-authn. From ConfigSource KcEnvVarConfigSource
```

The list of features is exactly like documented in https://www.keycloak.org/server/containers
Also the "invalid value"exactly matches the "expected values".

Also nothing has changed in the configuration when updating.

### Version

quay.io/keycloak/keycloak@sha256:42c6c6cf9e7c4c06ff0fd5c0ad7293f0ca76cbb0a3439835b9f940cc1aa4e10f

### Expected behavior

Keycloak starts and is usable

### Actual behavior

Keycloak refuses to start with an error message that is neither true nor useful.

### How to Reproduce?

Run Keycloak as a Docker Stack:

```
version: "3"

volumes:
  database:
    driver: local

services:
  server:
    image: quay.io/keycloak/keycloak
    restart: always
    command: 'start --hostname-port=8070'
    ports:
      - 8070:8080
    environment:
      - TZ=Europe/Zurich
      - KC_HOSTNAME_ADMIN=sso.example.com
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=adminpw
      - KC_HEALTH_ENABLED=false
      - KC_METRICS_ENABLED=false
      - KC_DB=mariadb
      - KC_DB_URL=jdbc:mariadb://database:3306/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=secret
      - KC_PROXY=edge
      - KC_HOSTNAME_URL=https://sso.example.com/
      - KC_FIPS_MODE=disabled
      - KC_HTTP_ENABLED=true
      - KC_FEATURES=account-api, account2, account3, admin-api, admin-fine-grained-authz, admin2, authorization, ciba, client-policies, client-secret-rotation, declarative-user-profile, device-flow, docker, dpop, dynamic-scopes, fips, impersonation, js-adapter, kerberos, linkedin-oauth, map-storage, par, preview, recovery-codes, scripts, step-up-authentication, token-exchange, transient-users, update-email, web-authn

  database:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secretrootpw
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=keycloak
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-u", "keycloak", "--password=secret"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - database:/var/lib/mysql
```
