### ISSUE TITLE
Admin Console doesnt open {error: 'Timeout when waiting for 3rd party check iframe message.'}

### ISSUE THREAD

**Issue by oe3gwu** [keycloak/keycloak#25754]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

When deploying Keycloak.X to out Ezmeral Cluster (using an HAProxy for ingress), I can acces /auth. But I cant access the Admin UI

![image](https://github.com/keycloak/keycloak/assets/17622063/aa433010-ad97-482b-87f3-682805231daa)

Is there a setting somehwere (and a guide) to deactive this check as workaround?

### Version

22.0.4, 23.0.3

### Expected behavior

Open Access to the Admin UI

### Actual behavior

Getting the screenshot above

### How to Reproduce?

Just a plain installation with Edge Proxy Setting and Localhost as Hostname. Otherwise I get many more other errors. Out HA Proxy forwards the https port to the Keycloax.X http port.

**Comment by Paul6552** [comment]
I had the same problem. But on my side I had a wrong config. Can you post your configuration

**Comment by jonkoops** [comment]
Duplicate of #14666

**Comment by Atomique** [comment]
I was able to fix this issue and hope someone gets it also working: 
It was necessary to increase the `large_client_header_buffers` in my nginx configuration. 

Just add this line to your server block (!): `large_client_header_buffers 4 32k;` - seems like the default wasn't enough. 

If you want to fix it in the ingress-nginx configuration you need to set the following annotation in the ingress object configuration:

```
nginx.ingress.kubernetes.io/server-snippet: | 
        large_client_header_buffers 4 32k; 
```

If you have both (nginx redirecting to ingress-nginx port then going to keycloak into Kubernetes, you need to adjust both configurations!). 

If someone is interested in my kubernetes configuration, I will add it here. 

Note to my setup to understand this config: 

- I am using an nginx reverse proxy in front of my kubernetes cluster to terminate TLS 
- I am using an ingress-nginx controller with cert-manager to get traffic into my cluster. If I get some trouble I try working around with Service Type LoadBalancer - thats why I added this also. Its not necessary to have them both. If you use it, you need metallb (onpremise). 
- I have an external postgres database. Thats why I am using the ExternalName type of service. You could also host it in your cluster and point it to it. 
- If you want to use reencrypt proxy mode you need to disable all HTTP Settings and comment out every HTTPS setting. This is fully optional. 

```
# 01-namespace.yaml
kind: Namespace
apiVersion: v1
metadata:
  name: keycloak
  labels:
    name: keycloak
```

```
# 03-secret.yaml
# Secret: keycloak-credentials
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
  namespace: keycloak
  labels:
    app: app
    tier: keycloak
    customer: org
    environment: prod
type: Opaque
data:
  KEYCLOAK_ADMIN_PASSWORD: <BASE64 ENCODED ADMIN PASSWORD>
  KC_DB_PASSWORD: <BASE64 ENCODED DB PASSWORD>
```

```
# 04-configmap.yaml
# ConfigMap: keycloak-credentials
---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: keycloak-config
    namespace: keycloak
    labels:
      app: app
      tier: keycloak
      customer: org
      environment: prod
  data:
    KEYCLOAK_ADMIN: "admin"
    # If HTTPS Termination on Keycloak and Nginx is needed, see also KC_HTTPS_CERTIFICATE_FILE 
    # KC_HTTPS_CERTIFICATE_KEY_FILE and all other configs with HTTPS
    # KC_PROXY: "reencrypt"
    KC_PROXY: "edge"
    KC_HOSTNAME_URL: "https://keycloak.domain.tld"
    # It is not necessary to keep them the same, as everybody says
    # it was also possible to have a different ADMIN_URL set.
    KC_HOSTNAME_ADMIN_URL: "https://keycloak.domain.tld"
    KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
    KC_HTTP_ENABLED: "true"
    KC_HEALTH_ENABLED: "true"
    KC_METRICS_ENABLED: "true"
    KC_LOG: "console"
    KC_DB: "postgres"
    KC_DB_URL_HOST: "postgres"
    KC_DB_URL_DATABASE: "db_keycloak"
    KC_DB_USERNAME: "us_keycloak"
    # Needed for headless kubernetes Service
    jgroups.dns.query: "keycloak"
    # Increase to replicacount if increased. Enables cache per instance
    CACHE_OWNERS_COUNT: "1"
    CACHE_OWNERS_AUTH_SESSIONS_COUNT: "1"
    ## Used if proxy: reencrypt is enabled.
    #KC_HTTPS_CERTIFICATE_FILE: "/tls/tls.crt"
    #KC_HTTPS_CERTIFICATE_KEY_FILE: "/tls/tls.key"
```

```
# 05-service.externaldns.yaml
# Service: postgres
---
  apiVersion: v1
  kind: Service
  metadata:
    name: postgres
    namespace: keycloak
  spec:
    type: ExternalName
    # Set it to the domain/ip of the psql server
    externalName: psql.domain.tld
```

```
# 05-service.ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-web
  namespace: keycloak
  annotations:
    #nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    #cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 12k
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/server-snippet: | 
      large_client_header_buffers 4 32k;
  labels:
    app: app
    tier: keycloak
    customer: org
    environment: prod
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: keycloak
            port:
              name: http
              # name: https
    host: keycloak.domain.tld
```

```
# 05-service.loadbalancer
# Service: keycloak-lb
# MetalLB LoadBalancer Service
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-lb
  namespace: keycloak
  labels:
    app: app
    tier: keycloak
    customer: org
    environment: prod
  annotations:
    metallb.universe.tf/allow-shared-ip: "<metallbpassword>" # SharingKey - only needed if used
spec:
  type: LoadBalancer
  loadBalancerIP: <metallb IP>
  ports:
  - name: http
    port: <external port used to connect from nginx>
    protocol: TCP
    targetPort: 8080
  # - name: https
  #   port: <external port used to connect from nginx>
  #   protocol: TCP
  #   targetPort: 8443
  selector:
    app: app
    tier: keycloak
    customer: org
    environment: prod
```

```
# 05-service.yaml
# Service: keycloak 
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: app
    tier: keycloak
    customer: org
    environment: prod
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 8443
    targetPort: 8443
  selector:
    app: app
    tier: keycloak
    customer: org
    environment: prod
```

```
# 99-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      tier: keycloak
      customer: org
      environment: prod
  template:
    metadata:
      labels:
        app: app
        tier: keycloak
        customer: org
        environment: prod
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:23.0
        #args: ["start", "--cache-stack=kubernetes", "--hostname-debug=true"]
        args: ["start", "--cache-stack=kubernetes"]
        envFrom:
          - secretRef:
              name: keycloak-credentials
          - configMapRef:
              name: keycloak-config
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1024Mi"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        - name: jgroups
          containerPort: 7600
      ## Used if proxy: reencrypt is enabled. Needs also variables
      ## KC_HTTPS_CERTIFICATE_FILE and KC_HTTPS_CERTIFICATE_KEY_FILE 
      ## configured with a path to the cert files. 
      ## Generate Certs via: 
      ## openssl req -subj '/CN=keycloak.domain.tld/O=IT./C=DE' -newkey rsa:4096 -nodes -keyout key.pem -x509 -days 365 -out certificate.pem
      ## Create Secret from Cert: 
      ## kubectl -n keycloak create secret tls tls-secret --cert certificate.pem --key key.pem
        # volumeMounts:
        #   - mountPath: "/tls"
        #     name: vol-keycloak-ssl
        #     readOnly: true
      # volumes:
      #   - name: vol-keycloak-ssl
      #     secret:
      #       secretName: tls-secret
```

Additional Notes: 

## nginx config

```
server {
        listen 80;
        listen [::]:80;

        server_name  keycloak.domain.tld;

        location / {
                return 301 https://$host$request_uri;
        }

        # Logging
        error_log  /var/log/nginx/http_keycloak.domain.tld-error.log;
        access_log /var/log/nginx/http_keycloak.domain.tld-access.log;
}

# Upgrade WebSocket if requested, otherwise use keepalive
map $http_upgrade $connection_upgrade_keepalive {
    default upgrade;
    ''      '';
}

server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;

        server_name  keycloak.domain.tld;

        # Logging
        error_log  /var/log/nginx/https_keycloak.domain.tld-error.log;
        access_log /var/log/nginx/https_keycloak.domain.tld-access.log;

        # SSL - Include *.ggrnet.de LE
        include /etc/nginx/ssl-cert_wc.ggrnet.de.conf;

        # replace with the IP address of your resolver
        resolver 10.1.10.10;

        large_client_header_buffers 4 32k;

        location / {
                #proxy_buffer_size   12k;
                #proxy_buffers   4 256k;
                #proxy_busy_buffers_size   256k;

                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;

                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";

                proxy_set_header X-Forwarded-Host $http_host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

                # Can be switched to ingress with HTTPS!
                proxy_pass http://<ip of LoadBalancer>:<PortOfLoadBalancer>;

        }

}

```

## Keycloak Deployment

### PostgreSQL Database Preparation

```PSQL
CREATE ROLE us_keycloak LOGIN PASSWORD '<PASSWORD>' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE db_keycloak TEMPLATE template0 ENCODING 'UNICODE';
ALTER DATABASE db_keycloak OWNER TO us_keycloak;
GRANT ALL PRIVILEGES ON DATABASE db_keycloak TO us_keycloak;
``` 



I really hope this helps someone out - I had some bad hours with this one. It wasnt only the nginx parameter, also the mess of settings not working for the admin console loading cicle were very frustrating. 

With this, have a nice weekend 
regards atomique
