### ISSUE TITLE
Since 23, start-dev command line arguments parsing is buggy

### ISSUE THREAD

**Issue by turboMaCk** [keycloak/keycloak#25783]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

After update of (official docker container) from 22 to 23 my script for starting keycloak using `start-dev` with configuration flags no longer works.

I'm using following command:

```
      start-dev \
        --http-port=8180 \
        --db=postgres \
        --features=token-exchange \
        --db-url=jdbc:postgresql://postgres:5432/keycloak \
        --db-username=${DB_USER} \
        --db-password=${DB_PASSWORD} \
        --import-realm
```

I'm unable to find any information about this breaking change in [release notes](https://www.keycloak.org/docs/latest/release_notes/#keycloak-23-0-0) so I assume this is not intentional.

### Version

23.0.3

### Expected behavior

start-dev should start accepting the configuration flags.

### Actual behavior

Fails with:

```
keycloak-1  | Option '--http-port' expects a single value (port)
keycloak-1  | Try 'kc.sh start-dev --help' for more information on the available options.
keycloak-1 exited with code 2
```

### How to Reproduce?

```
docker run --rm -it quay.io/keycloak/keycloak:23.0.3 \
      start-dev \
        --http-port=8180 \
        --db=postgres \
        --features=token-exchange \
        --db-url=jdbc:postgresql://postgres:5432/keycloak \
        --db-username=${DB_USER} \
        --db-password=${DB_PASSWORD} \
        --import-realm
```

### Anything else?

My current workaround is simply to stay on on version 22.

**Comment by turboMaCk** [comment]
It seems to me that the problem is with argument parsing and new lines because

```
docker run --rm -it quay.io/keycloak/keycloak:23.0.3  start-dev --http-port 8180
```

works but 

```
docker run --rm -it quay.io/keycloak/keycloak:23.0.3 \
      start-dev \
      --http-port=8180 
```

fails.

**Comment by shawkins** [comment]
@turboMaCk both of those work for me on a bash shell. What shell are you using?

**Comment by turboMaCk** [comment]
I'm using ZSH but I use docker-compose to run the container (for local development) with docker-compose.yaml:

```
services:
  postgres:
    build: docker/postgres
    command: ["-c", "log_statement=all"]
    environment:
      POSTGRES_MULTIPLE_DATABASES: keycloak
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.3
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
    command: |
       start-dev --http-port 8180 --db postgres --features token-exchange --db-url jdbc:postgresql://postgres:5432/keycloak --db-username ${DB_USER} --db-password ${DB_PASSWORD} --import-realm
    volumes:
      - "./docker/keycloak/realm.json:/opt/keycloak/data/import/realm.json"
    ports:
      - "8180:8180"
```

With some additonal dependecies like realm.json. Here the multi-line variant failed during startup. Now I'm trying to make environment variables work is an unrealated problem. This did work with some previous version but compose file was using :latest tag so I don't know which version of docker image it was.
