### ISSUE TITLE
Introduce a new Authenticator to handle duplicate IdP broker links

### ISSUE THREAD

**Issue by lexcao** [keycloak/keycloak#26201]
### Description

Split from the PR of #20677 and the origin issue is #9209 

Need to introduce a new Authenticator to handle duplicate IdP broker links when first login flow, 
which will show some confirmation screen then overriding the broker link would be possible.

### Discussion

https://github.com/keycloak/keycloak/pull/20677

### Motivation

There are two cases when updating the broker link when duplicates exists.
case 1:
```
[before]
User A:
 - username: user_a
 - broker_user: 
     - username: user_a
     - user_id: id_1

when the new broker_link comes
(This happens when the broker_user create a new account but use the previous username)
broker_user:
    - username: user_a
    - user_id: id_2

[after]
User A:
 - username: user_a
 - broker_user: 
     - username: user_a
     - user_id: id_2
 ```

case 2:
```
[before]
User A:
 - username: user_a
 - broker_user: 
     - username: whatever
     - user_id: id_1

when the new broker_link comes
(This happens when the broker_user just changed its username)
broker_user:
    - username: user_b
    - user_id: id_1

[after]
User A
 - username: user_a
 - broker_user: 
     - username: user_b
     - user_id: id_1
 ```
The case 2 makes sure the ID not changed.

### Details

For the case 1 with security concern,

> we should introduce a step during the flow to say "Hey, looks like you have an existing account linked to Foo IdP but using a different than the account you are now authenticating. Do you confirm using the new account instead?"

And make sure the user confirm the override existing broker link.

Introduce a new Authenticator for the first login flow, the process might be:

1. try find the user by `identityProvider` and `brokerUsername`
2. display a confirm screen if exists
3. verify the email by code if user has email (by IdpEmailVerificationAuthenticator)
4. otherwise, we can verify by the credential (by IdpUsernamePasswordForm)
