### ISSUE TITLE
Incorrect example in the Keycloak operator configuration

### ISSUE THREAD

**Issue by BadgerOps** [keycloak/keycloak#26281]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

I was reading through the discourse forum today, and noticed this post https://keycloak.discourse.group/t/is-the-keycloak-operator-still-maintained/20350 which prompted me to look at https://operatorhub.io/operator/keycloak-operator and notice that the example had omitted the `http:` from the 
```
http:
  tlsSecret:
```
part of the config. I found where the update needs to be made and will be submitting a PR, but am also creating this issue as per the CONTRIBUTING.md.

### Version

22.x

### Expected behavior

ability to install and configure the operator given the examples provided

### Actual behavior

unable to install the operator due to invalid example

### How to Reproduce?

1. Use the given example structure:

```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-keycloak
  labels:
    app: sso
spec:
  instances: 1
  hostname: example.org
  tlsSecret: my-tls-secret
```
2. :( 

### Anything else?

https://keycloak.discourse.group/t/is-the-keycloak-operator-still-maintained/20350
