### ISSUE TITLE
Keycloak returns different lists of sessions every time

### ISSUE THREAD

**Issue by alexclear** [keycloak/keycloak#26846]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Keycloak returns inconsistent results on https://keycloak.company.com/admin/master/console/#/master/sessions, the session list is different from call to call

### Version

22.0.5

### Expected behavior

The session list should be the same

### Actual behavior

Keycloak returns inconsistent results on https://keycloak.company.com/admin/master/console/#/master/sessions, the session list is different from call to call

### How to Reproduce?

Install Keycloak using a K8s operator with PostgreSQL and external Infinispan:
```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: keycloak
  name: keycloak
  namespace: infra
spec:
  hostname:
    hostname: keycloak.company.com
  additionalOptions:
    - name: db
      value: postgres
    - name: db-url
      value: jdbc:postgresql://haproxy-patroni.postgres.svc.cluster.local:5432/keycloak3
    - name: remote-store-host
      value: infinispan-keycloak.infinispan.svc.cluster.local
    - name: cache-config-file
      value: kcb-infinispan-cache-remote-store-config.xml
    - name: remote-store-port
      value: '11222'
    - name: remote-store-username
      secret:
        name: remote-store-secret
        key: username
    - name: remote-store-password
      secret:
        name: remote-store-secret
        key: password
    - name: db-pool-min-size
      value: '5'
    - name: db-pool-max-size
      value: '10'
    - name: db-pool-initial-size
      value: '5'
    - name: storage
      value: jpa
    - name: storage-deployment-state-version-seed
      value: some-secret-seed
    - name: log-console-output
      value: default
    - name: metrics-enabled
      value: 'true'
    - name: health-enabled
      value: 'true'
    - name: db-username
      value: 'keycloak'
    - name: db-password
      value: 'XXXXXXXXXXXXXXXXXXX'
  http:
    tlsSecret: keycloak-tls-secret
  instances: 1
  image: keycloak/keycloak:22.0.5
  ingress:
    enabled: false
  unsupported:
    podTemplate:
      spec:
        containers:
          -
            #args:
            #  - start
            env:
              - name: PRINT_ENV
                value: "true"
              - name: JAVA_OPTS_APPEND
                # using non-blocking random, make DNS lookups expire after 10 seconds and not cache them forever
                value: >
                  -Xms64m -Xmx512m
                  -XX:MetaspaceSize=96m -XX:MaxMetaspaceSize=256m
                  -Djava.security.egd=file:/dev/urandom -Dnetworkaddress.cache.ttl=10 -XX:+ExitOnOutOfMemoryError
                  -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8787
                  -Dcom.sun.management.jmxremote.port=9091 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
                  -XX:FlightRecorderOptions=stackdepth=512 -Djgroups.thread_dumps_threshold=1 -Djboss.site.name=keycloak
              - name: PROMETHEUS_PUSHGATEWAY_ADDRESS
                value: "prometheus-pushgateway:9091"
            ports:
              - containerPort: 9091
                protocol: TCP
                name: jfr-jmx
              - containerPort: 8787
                protocol: TCP
                name: jvmdebug
            resources:
              requests:
                cpu: "0"
                memory: "1024M"
              limits:
                cpu: "4"
                memory: "1024M"
            startupProbe:
              httpGet:
                path: /health/ready
                port: 8443
                scheme: HTTPS
              failureThreshold: 600
              initialDelaySeconds: 10
              periodSeconds: 2
            readinessProbe:
              httpGet:
                path: /health/ready
                port: 8443
                scheme: HTTPS
              failureThreshold: 10
              periodSeconds: 10
            livenessProbe:
              httpGet:
                path: /health/live
                port: 8443
                scheme: HTTPS
              failureThreshold: 10
              periodSeconds: 10
```
Login to the admin console and get a list of sessions for the master realm. It will be different every time.
