### ISSUE TITLE
(operator): generate TLS-enabled Ingress resource for edge mode 

### ISSUE THREAD

**Issue by lukasmrtvy** [keycloak/keycloak#27045]
### Description

The common use case is to terminate TLS on Ingress, but that's impossible now ( without a custom Ingress resource ). The generated Ingress resource does not contain TLS spec for `proxy: edge` mode and is not possible to add it via operator.

### Discussion

https://cloud-native.slack.com/archives/C056HC17KK9/p1707944975041489

### Details

I would like to see an option to add TLS spec to generated Ingress resource either via `spec.ingress.spec` , or `spec.experimentalFeatures.ingress.spec`
```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgres-keycloak-rw
    usernameSecret:
      name: postgres-keycloak-app
      key: username
    passwordSecret:
      name: postgres-keycloak-app
      key: password
  hostname:
    hostname: https://keycloak.example.com
  additionalOptions:
    - name: proxy
      value: edge
  ingress:
    enabled: true
    spec:
      tls:
      - hosts:
          - https-keycloak.example.com
        secretName: keycloak.example.com-tls
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production
experimentalFeatures:
  ingress:
    spec:
      tls:
      - hosts:
          - keycloak.example.com
        secretName: keycloak.example.com-tls
```
