### ISSUE TITLE
User login successfuly, but got error CODE_TO_TOKEN_ERROR

### ISSUE THREAD

**Issue by ziyunxiao** [keycloak/keycloak#27397]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

I am using shinyproxy(3.0.1) and using keyclaok as the SSO IDP with OIDC client. 

It was working fine with Keycloak(20.0.2). After I upgrade Keycloak to 23.0.7. I got the error CODE_TO_TOKEN_ERROR. Please help to resolve this issue.

Here are the event log and client settings.
![image](https://github.com/keycloak/keycloak/assets/6117913/0de565c1-4aaf-48b2-acf5-020d171841f9)
![image](https://github.com/keycloak/keycloak/assets/6117913/ccca3f64-6234-496b-98cf-5f58be1503eb)

Error from logs:
```
2024-02-29 16:33:28,967 WARN  [org.keycloak.events] (executor-thread-7) type="CODE_TO_TOKEN_ERROR", realmId="Shiny Applications", clientId="shiny-proxy-p1", userId="adb6a6a0-386b-4c71-8a0d-a9c0193a2cfe", ipAddress="10.65.144.204", error="invalid_code", grant_type="authorization_code", code_id="0e34fb9b-0f37-471a-99c8-cedb71137109", client_auth_method="client-secret"
```

All other settings are default settings except redirect URLs.

Thanks
Robin

### Version

23.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

Be able to get proper token and client app can continue.the the 

### Actual behavior

Got error CODE_TO_TOKEN_ERROR

### How to Reproduce?

Create OIDC client in Keycloak and configure Shinyproxy to use Keycloak as SSO IDP.
Here are the settings for keycloak in shinyproxy application.xml
```
...
  authentication: keycloak
  keycloak:
    realm: shiny
    ssl-required: all
    verify-token-audience: true
    resource: shiny-proxy-p1
    credentials-secret: xxxxxxx
    auth-server-url: https://sso1-test.xxxx.ca/
    confidential-port: 443
    #proxy.keycloak.name-attribute: username
    name-attribute: email
.....
```
