### ISSUE TITLE
Ldap via ipv6 in a ipv6 only network fails with Protocol family unavailable

### ISSUE THREAD

**Issue by nanu-c** [keycloak/keycloak#27766]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Describe the bug

Our ldap server is only reachable via ipv6. Keycloak fails to connect to it. When i use the domain as url, it tries to use ipv4 and fails because server is not reachable, if i enter the ipv6 address directly it fails with `Root exception is java.net.SocketException: Protocol family unavailable`

### Version

24.0 docker

### Regression

- [ ] The issue is a regression

### Expected behavior

Connect to the ldap server via ipv6.
Connect to the ldap server via ipv6 when a domain is entered 

### Actual behavior

```
keycloak-keycloak-1  | 2024-03-11 11:21:47,558 ERROR [org.keycloak.services] (executor-thread-10) KC-SERVICES0055: Error when connecting to LDAP: 2001:<rest of ipv6>: javax.naming.CommunicationException: 2001:<rest of ipv6>[Root exception is java.net.SocketException: Protocol family unavailable]
keycloak-keycloak-1  |  at java.naming/com.sun.jndi.ldap.Connection.<init>(Connection.java:253)
keycloak-keycloak-1  |  at java.naming/com.sun.jndi.ldap.LdapClient.<init>(LdapClient.java:137)
keycloak-keycloak-1  |  at java.naming/com.sun.jndi.ldap.LdapClient.getInstance(LdapClient.java:1616)
keycloak-keycloak-1  |  at java.naming/com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2848)
keycloak-keycloak-1  |  at java.naming/com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:348)
keycloak-keycloak-1  |  at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxFromUrl(LdapCtxFactory.java:229)
keycloak-keycloak-1  |  at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:189)
keycloak-keycloak-1  |  at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:247)
keycloak-keycloak-1  |  at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:154)
keycloak-keycloak-1  |  at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:84)
keycloak-keycloak-1  |  at java.naming/javax.naming.spi.NamingManager.getInitialContext(NamingManager.java:732)
keycloak-keycloak-1  |  at java.naming/javax.naming.InitialContext.getDefaultInitCtx(InitialContext.java:305)
keycloak-keycloak-1  |  at java.naming/javax.naming.InitialContext.init(InitialContext.java:236)
keycloak-keycloak-1  |  at java.naming/javax.naming.ldap.InitialLdapContext.<init>(InitialLdapContext.java:154)
keycloak-keycloak-1  |  at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.createLdapContext(LDAPContextManager.java:80)
keycloak-keycloak-1  |  at org.keycloak.storage.ldap.idm.store.ldap.LDAPContextManager.getLdapContext(LDAPContextManager.java:100)
keycloak-keycloak-1  |  at org.keycloak.services.managers.LDAPServerCapabilitiesManager.testLDAP(LDAPServerCapabilitiesManager.java:160)
keycloak-keycloak-1  |  at org.keycloak.services.resources.admin.TestLdapConnectionResource.testLDAPConnection(TestLdapConnectionResource.java:93)
keycloak-keycloak-1  |  at org.keycloak.services.resources.admin.TestLdapConnectionResource$quarkusrestinvoker$testLDAPConnection_d65ae9343a71f2736595679e81594225f9de5d6f.invoke(Unknown Source)
keycloak-keycloak-1  |  at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
keycloak-keycloak-1  |  at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
keycloak-keycloak-1  |  at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
keycloak-keycloak-1  |  at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
keycloak-keycloak-1  |  at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
keycloak-keycloak-1  |  at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
keycloak-keycloak-1  |  at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
keycloak-keycloak-1  |  at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
keycloak-keycloak-1  |  at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
keycloak-keycloak-1  |  at java.base/java.lang.Thread.run(Thread.java:840)
keycloak-keycloak-1  | Caused by: java.net.SocketException: Protocol family unavailable
keycloak-keycloak-1  |  at java.base/sun.nio.ch.Net.connect0(Native Method)
keycloak-keycloak-1  |  at java.base/sun.nio.ch.Net.connect(Net.java:579)
keycloak-keycloak-1  |  at java.base/sun.nio.ch.Net.connect(Net.java:568)
keycloak-keycloak-1  |  at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:593)
keycloak-keycloak-1  |  at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
keycloak-keycloak-1  |  at java.base/java.net.Socket.connect(Socket.java:633)
keycloak-keycloak-1  |  at java.naming/com.sun.jndi.ldap.Connection.createConnectionSocket(Connection.java:333)
keycloak-keycloak-1  |  at java.naming/com.sun.jndi.ldap.Connection.createSocket(Connection.java:285)
keycloak-keycloak-1  |  at java.naming/com.sun.jndi.ldap.Connection.<init>(Connection.java:232)
keycloak-keycloak-1  |  ... 28 more
```

### How to Reproduce?

* Set up a ipv6 only network with the ldap server on a different machine. Ensure that the ldap server is reachable outside of docker.
* Ensure that the `ping` command resolves via ipv6.
* Enable ipv6 for docker -> https://docs.docker.com/config/daemon/ipv6/
* Ensure that docker can connect to ldap -> `docker run -it registry.access.redhat.com/ubi9@sha256:66233eebd72bb5baa25190d4f55e1dc3fff3a9b77186c1f91a0abdb274452072 /bin/bash`  then run `dnf install -y https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/Packages/telnet-0.17-85.el9.x86_64.rpm` and `telnet LDAP-URL 389` This should work.

Enter the ldap settings under user federation and click `Test connection`

### Anything else?

Appending  the following doesn't help either:
`Appending additional Java properties to JAVA_OPTS: -Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true`

**Comment by pedroigor** [comment]
@nanu-c It seems slightly related to this issue https://github.com/keycloak/keycloak/issues/23992#issuecomment-1879204394.

Do you see anything different that might be missing when we tried to reproduce ipv6 communication issues?

**Comment by nanu-c** [comment]
Actually i set the ipv6 in the docker and i can ping/login to ldap via the REDHAT ubi9 base image in a docker container but still i get this error. So maybe if you want to reproduce:
Set up a vm with ldap that is only reachable by ipv6
Set up a second vm with docker + Keycloak. -> enable docker ipv6 

Test it again.

**Comment by nanu-c** [comment]
Okey the problem is docker compose uses per default ipv4 and not ipv6.
Example for a working docker compose file

```
version: "3.8"

services:
  keycloak:
    build:
      context: ./src
      dockerfile: ./Dockerfile
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_FRONTEND_URL: ${KEYCLOAK_HOST}
      KC_DB_USERNAME: ${KEYCLOAK_DB_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_DB_SCHEMA: public
      KC_DB_URL_DATABASE: ${KEYCLOAK_DB_NAME}
      KC_DB_URL_HOST: ${KEYCLOAK_DB_HOST}
      KC_DB_URL_PORT: ${KEYCLOAK_DB_PORT}
      ROOT_LOGLEVEL: ALL
      KEYCLOAK_LOGLEVEL: ${KEYCLOAK_LOGLEVEL}
      KC_HOSTNAME_URL: ${KEYCLOAK_HOST}
      KC_HOSTNAME_ADMIN_URL: ${KEYCLOAK_HOST}
      KEYCLOAK_ENVIRONMENT: ${KEYCLOAK_ENVIRONMENT}
      JAVA_OPTS_APPEND: -Djava.net.preferIPv4Stack=false -Djava.net.preferIPv6Addresses=true
      KC_LOG_LEVEL: DEBUG
    depends_on:
      keycloak-db: 
        condition: service_healthy
    volumes:
      - ./import:/opt/keycloak/data/import
      - ./export:/tmp/export
      - ./src/themes/oeh:/opt/keycloak/themes/oeh # used for development
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080;echo -e \"GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n\" >&3;grep \"HTTP/1.1 200 OK\" <&3"]
      interval: 5s
      timeout: 2s
      retries: 15
    logging:
      driver: "json-file"
      options:
          max-size: "200m"
    ports:
      - "${KEYCLOAK_PORT}:8080"
    networks:
      dockerbridge:
        ipv6_address: 2001:3200:3200::21
  keycloak-db:
    image: postgres:${POSTGRES_VERSION}
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_NAME}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KEYCLOAK_DB_USER} -d ${KEYCLOAK_DB_NAME} -h localhost -p 5432"]
      interval: 5s
      timeout: 2s
      retries: 15
    logging:
      driver: "json-file"
      options:
          max-size: "200m"
    networks:
      dockerbridge:
        ipv6_address: 2001:3200:3200::20

volumes:
  keycloak-db-data:


networks:
  dockerbridge:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 2001:3200:3200::/64
          gateway: 2001:3200:3200::1
```
