### ISSUE TITLE
Keycloak operator jgroups.dns.query error

### ISSUE THREAD

**Issue by ginokok1996** [keycloak/keycloak#27992]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

We are running keycloak in Openshift using the keycloak operator.
This has been running fine for a while, up until we removed to statefulset and re created it.
We now encounter the following errors without any changes in our config:

`{"timestamp":"2024-03-18T12:25:42.926485983Z","sequence":1033,"loggerClassName":"org.infinispan.commons.logging.Log_$logger","loggerName":"org.infinispan.commons.util.StringPropertyReplacer","level":"WARN","message":"ISPN000901: Property jgroups.dns.query could not be replaced as intended!","threadName":"keycloak-cache-init","threadId":17,"mdc":{},"ndc":"","hostName":"sso-1","processName":"QuarkusEntryPoint","processId":1}`

`{"timestamp":"2024-03-18T12:25:49.238572926Z","sequence":12382,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler","level":"ERROR","message":"ERROR: dns_query can not be null or empty","threadName":"main","threadId":1,"mdc":{},"ndc":"","hostName":"sso-1","processName":"QuarkusEntryPoint","processId":1}`

The pod ends up in a crashloopbackoff state.
Adding the jgroups.dns.query env variable by hand seems to work.

However in the CR i encountered the following args:
          args:
            - '-Djgroups.dns.query=sso-discovery.ns-bsbm-o-sso'
            - '--verbose'
            - start
            
These seem to trigger the warning that the property cant be replaced as intended.

### Version

24.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

The env variable jgroups.dns.query is set correctly without having to add it manually to the keycloak CR.

### Actual behavior

The env variable isn't being added which causes keycloak to be unable to start.

### How to Reproduce?

We can reproduce it by simply deploying the basic keycloak CR

**Comment by shawkins** [comment]
jgroups.dns.query is now set by the operator via the Pod container command, it should not be set via an environment variable - there was an issue on that because using an env variable produced a warning in the log #21830

Can you confirm that jgroups.dns.query is part of your command?

**Comment by ginokok1996** [comment]
The statefull set has the following arguments defined by default for the command:

 '-Djgroups.dns.query=sso-discovery.ns-bsbm-o-sso'
- '--verbose'
- start

These seem to trigger an error thst the variable couldnt be set (see log entry in ticket) and the pod wont be able to start.

As a temporary fix we added the env vara by hand to have a working keycloak.

**Comment by shawkins** [comment]
> These seem to trigger an error thst the variable couldnt be set (see log entry in ticket) and the pod wont be able to start.

There seems to be something different in your case as this generally works fine. Can you provide your full Keycloak CR?

**Comment by ginokok1996** [comment]
This is our Keycloak CRD that fails because it doesnt receive the env
``` yaml

apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: sso
  name: sso
spec:
  db:
    port: 9999
    schema: keycloak
    usernameSecret:
      key: username
      name: keycloak-db-secret
    vendor: postgres
    poolInitialSize: 1
    poolMinSize: 5
    poolMaxSize: 5
  transaction:
    xaEnabled: false
  hostname:
    strict: false
    strictBackchannel: false
  http:
    httpEnabled: true
  ingress:
    enabled: false
  additionalOptions:
    - name: metrics-enabled
      value: 'true'
  instances: 2
  imagePullSecrets:
    - name: harbor
  unsupported:
    podTemplate:
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app: sso
                  topologyKey: datacenter
                weight: 70
              - podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app: sso
                  topologyKey: kubernetes.io/hostname
                weight: 30
        initContainers:
          - image: >-
              container-registry.nspaas.ns.nl/bsbm/base/sso-init-container:20240130.1
            command:
              - sh
              - '-c'
              - cp /tmp/keycloak-metrics-spi-5.0.0.jar /mnt/providers
            volumeMounts:
              - name: providers
                mountPath: /mnt/providers
            name: provider-inject
          - image: 'container-registry.nspaas.ns.nl/bsbm/base/java-17:latest'
            name: keystore-provider
            command:
              - sh
              - '-c'
              - |-
                function processKeys() {
                  keystoreName=$1
                  prefix=$2
                  keystoreSrc="${KEYSTORE_SRC_DIR}${keystoreName}"
                  keystoreDest="${KEYSTORE_DEST_DIR}${keystoreName}"

                  echo "Current list of keys:"
                  keytool -list -keystore $keystoreSrc -storepass '' -rfc
                  # There is only one key in the pfx, so the first will suffice
                  current_alias=$(keytool -list -keystore $keystoreSrc -storepass '' -rfc | grep -Po '(?<=Alias name: ).*' -m 1)
                  echo "Found key $current_alias, renaming to $KEY_ALIAS"

                  keytool -importkeystore \
                    -srckeystore "$keystoreSrc" -srcstoretype PKCS12 -srcstorepass '' \
                    -destkeystore "$keystoreDest" -deststoretype PKCS12 -deststorepass:env "${prefix}_KEYSTORE_PASSWORD" \
                    -srcalias "$current_alias" -srckeypass '' \
                    -destalias "$KEY_ALIAS" -destkeypass:env "${prefix}_KEY_PASSWORD"

                  echo "Resulting keystore in $keystoreDest:"
                  keytool -list -keystore "$keystoreDest" -storepass:env "${prefix}_KEYSTORE_PASSWORD"
                }
                processKeys "adfsBam.pfx" KEYCLOAK
                processKeys "adfsBamBijs.pfx" KEYCLOAK
                processKeys "adfsBad.pfx" KEYCLOAK
                processKeys "adfsBadBijs.pfx" KEYCLOAK
            env:
              - name: KEY_ALIAS
                value: adfs-key
              - name: KEYSTORE_SRC_DIR
                value: /mnt/adfs-key/
              - name: KEYSTORE_DEST_DIR
                value: /mnt/keystores/
              - name: KEYCLOAK_KEYSTORE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: keycloak-adfs-keystore-secret
                    key: keycloakKeystorePassword
              - name: KEYCLOAK_KEY_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: keycloak-adfs-keystore-secret
                    key: keycloakKeyPassword
            volumeMounts:
              - name: keystore
                mountPath: /mnt/keystores
              - name: adfs-key
                mountPath: /mnt/adfs-key
                readOnly: true
        containers:
          - env:
              - name: QUARKUS_HTTP_LIMITS_MAX_FORM_ATTRIBUTE_SIZE
                value: '131072'
              - name: KC_HOSTNAME_ADMIN_URL
                value: 'https://${KC_HOSTNAME}'
              - name: HTTPS_PROXY
                value: 'http://10.176.100.1:8080'
              - name: NO_PROXY
                value: '127.0.0.1,localhost,*.svc.cluster.local'
              - name: KC_DB_URL_PROPERTIES
                valueFrom:
                  secretKeyRef:
                    name: keycloak-db-properties
                    key: dbProperties
              - name: KC_LOG_CONSOLE_OUTPUT
                value: json
              - name: URI_METRICS_ENABLED
                value: 'true'
              - name: KEYCLOAK_ADMIN
                valueFrom:
                  secretKeyRef:
                    name: sso-admin
                    key: username
                    optional: false
              - name: KEYCLOAK_ADMIN_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: sso-admin
                    key: password
                    optional: false
            command:
              - sh
              - '-c'
              - /opt/keycloak/bin/kc.sh build && /opt/keycloak/bin/kc.sh start
            volumeMounts:
              - name: providers
                mountPath: /opt/keycloak/providers
              - name: keystore
                mountPath: /mnt/keystores
                readOnly: true
              - name: certs
                mountPath: /mnt/certs
        volumes:
          - name: providers
            emptyDir: {}
          - name: keystore
            emptyDir: {}
          - name: certs
            secret:
              secretName: keycloak-db-properties
          - name: adfs-key
            secret:
              secretName: keycloak-adfs-keystore-secret
              items:
                - key: adfsBamKeystore
                  path: adfsBam.pfx
                - key: adfsBamBijsKeystore
                  path: adfsBamBijs.pfx
                - key: adfsBadKeystore
                  path: adfsBad.pfx
                - key: adfsBadBijsKeystore
                  path: adfsBadBijs.pfx

```
