### ISSUE TITLE
Port forwarding to Keycloak admin UI behind a proxy fails on v24.0.1 - ( v23.0.7 works ) -  now gives cookie errors

### ISSUE THREAD

**Issue by stecullum** [keycloak/keycloak#28049]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

“Cookie errors” after upgrading to keycloak 24.0.1 from keycloak 23.0.7 when connecting to admin URI with port forwarding

Running 24.0.1 locally in docker with keycloak behind a proxy works as expected
Running 24.0.1 on an EC2 in docker with keycloak behind a proxy and port forwarding gives a cookie error ..

### Version

24.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

Port forwarding to connect to keycloak should work the same as it does on 23.0.7

With 23.0.7 -- portforwarding to keycloak works 
`aws ssm start-session --target $ec2_instance_id --document-name AWS-StartPortForwardingSession --parameters '{"portNumber":["10000"],"localPortNumber":["10000"]}'`

With 24.01 -- portforwarding to keycloak fails with a cookie issue

### Actual behavior

v24.0.1 
Shows this when attempting to hit the admin UI when port forwarding

![image](https://github.com/keycloak/keycloak/assets/110533794/973fc2f6-0f49-4e2e-9f2c-27636ed0eb93)

### How to Reproduce?

Steps to repo 

* run `docker-compose up` on server
* add `mykeycloak` to `/etc/hosts  127.0.0.1`
* browse to http://mykeycloak:10000/
-- everything works as i expected
* use SSM or SSH to port forward to 10000 on another server
-- with 24.0.1 ; a login prompt is shown, I enter creds and an on screen "cookie not found..please make sure cookies are enabled in your browser" message is shown
-- with 23.0.7 ; the home page is shown ; i click admin console ; enter creds and am logged into the admin site

My Setup
----
Docker Compose File
```
services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7 # ( works )
      #    image: quay.io/keycloak/keycloak:24.0.1
    command: start -Djgroups.dns.query=keycloak
    env_file:
    - path: ./keycloak.env      
      required: true
    - path: ./secrets.env       
      required: false
    deploy:
      replicas: 1 # overridden in dev but not on server
      endpoint_mode: dnsrr
    logging:
      options:
        tag: "{{.Name}}"
    volumes:
       - ./infinispan/cache-ispn-jdbc-ping.xml:/opt/keycloak/conf/cache-ispn-jdbc-ping.xml
      
  envoy:
    image: envoyproxy/envoy:v1.28-latest
    ports:
      - "10000:10000"
      - "10001:10001"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    logging:
      options:
        tag: "{{.Name}}"
```

Envoy proxy sitting in front of keycloak
```
listeners:
    - address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
          - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                use_remote_address: false # https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-forwarded-proto
                xff_num_trusted_hops: 0  # https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers#x-forwarded-proto
                append_x_forwarded_port: true
                access_log:
                - name: envoy.access_loggers.stdout
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
                http_filters:
                - name: envoy.filters.http.router
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router

                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: keycloak

  clusters:
    - name: keycloak
      connect_timeout: 0.25s
      type: STRICT_DNS
      lb_policy: round_robin
 ```

Keycloak env file..
```
KC_DB=postgres
KC_DB_URL_HOST=postgres
KC_DB_URL_DATABASE=keycloak
KC_DB_SCHEMA=kc
KC_CACHE_CONFIG_FILE=cache-ispn-jdbc-ping.xml

KC_DB_USERNAME=keycloak
KC_DB_PASSWORD=passw0rd

KC_PROXY=edge # apparantly this is deprecated but without it i had issues
KC_PROXY_HEADERS=forwarded # |xforwarded # apparantly these supserceded [edge]
KC_HOSTNAME=mykeycloak
KC_HOSTNAME_PORT='10000'

KC_HOSTNAME_STRICT=false # Disables dynamically resolving the hostname from request headers
KC_HOSTNAME_STRICT_HTTPS=false # Required for running only in http mode
KC_HTTP_ENABLED=true # Enables the HTTP listener

KEYCLOAK_ADMIN=admin
KEYCLOAK_ADMIN_PASSWORD=admin

KC_METRICS_ENABLED=true # exposes a /metrics endpoint
KC_HEALTH_ENABLED=true
KC_LOG_LEVEL=INFO # WARN,org.infinispan:WARN,org.jgroups:WARN
```

./infinispan/cache-ispn-jdbc-ping.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:14.0 http://www.infinispan.org/schemas/infinispan-config-14.0.xsd"
        xmlns="urn:infinispan:config:14.0">
    <jgroups>
        <stack name="postgres-jdbc-ping-tcp" extends="tcp">                 
            <JDBC_PING connection_driver="org.postgresql.Driver"
                       connection_username="${env.KC_DB_USERNAME}" connection_password="${env.KC_DB_PASSWORD}"
                       connection_url="jdbc:postgresql://${env.KC_DB_URL_HOST}:${env.KC_DB_URL_PORT:5432}/${env.KC_DB_URL_DATABASE}${env.KC_DB_URL_PROPERTIES:}"
                       initialize_sql="CREATE SCHEMA IF NOT EXISTS ${env.KC_DB_SCHEMA:public}; CREATE TABLE IF NOT EXISTS ${env.KC_DB_SCHEMA:public}.JGROUPSPING (own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, bind_addr varchar(200) NOT NULL, updated timestamp default current_timestamp, ping_data BYTEA, constraint PK_JGROUPSPING PRIMARY KEY (own_addr, cluster_name));"
                       insert_single_sql="INSERT INTO ${env.KC_DB_SCHEMA:public}.JGROUPSPING (own_addr, cluster_name, bind_addr, updated, ping_data) values (?, ?, '${env.HOSTNAME:127.0.0.1}', NOW(), ?);"
                       delete_single_sql="DELETE FROM ${env.KC_DB_SCHEMA:public}.JGROUPSPING WHERE own_addr=? AND cluster_name=?;"
                       select_all_pingdata_sql="SELECT ping_data, own_addr, cluster_name FROM ${env.KC_DB_SCHEMA:public}.JGROUPSPING WHERE cluster_name=?"
                       clear_sql="DELETE FROM ${env.KC_DB_SCHEMA:public}.JGROUPSPING WHERE cluster_name=?"
                       info_writer_sleep_time="500"
                       remove_all_data_on_view_change="true"
                       stack.combine="REPLACE"
                       stack.position="MPING" />
        </stack>
    </jgroups>

    <cache-container name="keycloak">
        <transport lock-timeout="60000" stack="postgres-jdbc-ping-tcp"/>
        <local-cache name="realms" simple-cache="true">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <local-cache name="users" simple-cache="true">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <distributed-cache name="sessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="authenticationSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="offlineSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="clientSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="offlineClientSessions" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <distributed-cache name="loginFailures" owners="2">
            <expiration lifespan="-1"/>
        </distributed-cache>
        <local-cache name="authorization" simple-cache="true">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <replicated-cache name="work">
            <expiration lifespan="-1"/>
        </replicated-cache>
        <local-cache name="keys" simple-cache="true">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="3600000"/>
            <memory max-count="1000"/>
        </local-cache>
        <distributed-cache name="actionTokens" owners="2">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="-1" lifespan="-1" interval="300000"/>
            <memory max-count="-1"/>
        </distributed-cache>
    </cache-container>
</infinispan>
```

### Anything else?

The only keycloak warning I can find 
```
keycloak-1  | 2024-03-18 18:29:35,733 WARN  [org.keycloak.events] (executor-thread-6) type="LOGIN_ERROR", realmId="af404fdf-2a16-4a4a-af9c-XXX", clientId="null", userId="null", ipAddress="172.25.0.2", error="cookie_not_found"
```
