### ISSUE TITLE
ConditionalUserConfiguredAuthenticator matches non-configurable authenticators

### ISSUE THREAD

**Issue by aph3rson** [keycloak/keycloak#28488]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

**TL;DR:** ConditionalUserConfiguredAuthenticator needs to check if the evaluated executions are authenticators which can be configured by the user, as "non-configurable" authenticators (e.g. `allow-access-authenticator`) may exist in the flow.

-----

The ConditionalUserConfiguredAuthenticator is designed to evaluate to true if either:
- for all `REQUIRED` authenticators in the same flow as the condition, the current user has all said authenticators configured - if none exist,
- for any `ALTERNATIVE` authenticators in the same flow as the condition, the current user has one o said authenticators configured.

There are some filters to filter out executions in the flow which shouldn't be evaluated, such as this/other conditions, or things that are not authenticators. The logic for those filters is here:

https://github.com/keycloak/keycloak/blob/811c70d1361c60dfd52abc7932a16715cd00a952/services/src/main/java/org/keycloak/authentication/authenticators/conditional/ConditionalUserConfiguredAuthenticator.java#L27-L29

However, this filter fails to check if the authenticator is "configurable" for a given user. In the basic Keycloak deployment, only a handful of these authenticators exist (such as WebAuthN, and OTP). If there were another authenticator (primarily the `allow-access`/`deny-access` authenticator) alongside the condition, the condition incorrectly tries to see if the current user has this authenticator configured for their account.

An example of how this works: in this subflow, the condition is intended to match the two "configurable" authenticators, both of which are alternate.

![image](https://github.com/keycloak/keycloak/assets/838916/3a40480d-1fe6-4c76-ac29-a5e4da94baf8)

However, the condition evaluates to false, as seen in log output:

```txt
Apr 06 04:03:56 my.host kc.sh[5824]: 2024-04-06 04:03:56,904 TRACE [org.keycloak.authentication.DefaultAuthenticationFlow] (executor-thread-1) Set execution status: Execution: conditional-user-configured, status: EVALUATED_FALSE
Apr 06 04:03:56 my.host kc.sh[5824]: 2024-04-06 04:03:56,904 TRACE [org.keycloak.authentication.DefaultAuthenticationFlow] (executor-thread-1) Conditional subflow 'MFA (STEPUP_MFA_MANDATORY) flow' is disabled
```

If the aforementioned authenticator is disabled, as per below, the condition properly evaluates the "configurable" authenticators, and the user is prompted for their MFA method.

![image](https://github.com/keycloak/keycloak/assets/838916/f3ec440a-2c32-43b1-8b03-98eb26c3595a)

### Version

23.0.7

### Regression

- [ ] The issue is a regression

### Expected behavior

The ConditionalUserConfiguredAuthenticator should have a filter that only looks at authenticators that can be configured for a user, rather than all authenticators in the subflow.

### Actual behavior

Authenticators which cannot ever be configured for a user (e.g. `allow-access-authenticator`) match the execution selection algorithm, and incorrectly cause the condition to evaluate to `false`.

### How to Reproduce?

1. Create a subflow as indicated in the first picture.
2. Attempt to authenticate as a user with an MFA method configured.
3. Observe that the deny-access authenticator is reached.
4. Disable the allow-access authenticator, and retry.
5. Observe that the flow succeeds.

### Anything else?

For reference, the full authentication flow (style of Ansible's `community.general.keycloak_authentication`):

<details>
  <summary>Full authentication flow</summary>

```yaml
authenticationExecutions:
  - displayName: StepUp Forced MFA Authentication
    # TODO: Fix after https://github.com/keycloak/keycloak/issues/28341
    # requirement: CONDITIONAL
    requirement: DISABLED
    # description: If required, reauthenticate the user (with MFA).
  - displayName: Conditional - Level of Authentication
    providerId: conditional-level-of-authentication
    flowAlias: StepUp Forced MFA Authentication
    requirement: REQUIRED
    authenticationConfig:
      alias: STEPUP_MFA_ALWAYS
      config:
        loa-condition-level: 40
        loa-max-age: 1
  - displayName: Username Password Form
    providerId: auth-username-password-form
    flowAlias: StepUp Forced MFA Authentication
    requirement: REQUIRED
  - displayName: MFA (STEPUP_MFA_ALWAYS)
    flowAlias: StepUp Forced MFA Authentication
    requirement: CONDITIONAL
    # description: Allow user to choose from MFA sources.
  - displayName: Condition - user configured
    providerId: conditional-user-configured
    flowAlias: MFA (STEPUP_MFA_ALWAYS)
    requirement: REQUIRED
  - displayName: OTP Form
    providerId: auth-otp-form
    flowAlias: MFA (STEPUP_MFA_ALWAYS)
    requirement: ALTERNATIVE
  - displayName: WebAuthn Authenticator
    providerId: webauthn-authenticator
    flowAlias: MFA (STEPUP_MFA_ALWAYS)
    requirement: ALTERNATIVE
  - displayName: Allow access
    providerId: allow-access-authenticator
    flowAlias: MFA (STEPUP_MFA_ALWAYS)
    requirement: REQUIRED
  - displayName: Deny access
    providerId: deny-access-authenticator
    flowAlias: StepUp Forced MFA Authentication
    requirement: REQUIRED
    authenticationConfig:
      alias: STEPUP_MFA_ALWAYS_MISSING
      config:
        denyErrorMessage: >-
          Login denied. This application requires multi-factor
          authentication, which is not currently configured for your
          user account.
          (STEPUP_MFA_ALWAYS_MISSING)
  - displayName: StepUp Mandatory MFA Authentication
    requirement: CONDITIONAL
    # description: Authenticate with MFA, or a previously-MFA'd session.
  - displayName: Conditional - Level of Authentication
    providerId: conditional-level-of-authentication
    flowAlias: StepUp Mandatory MFA Authentication
    requirement: REQUIRED
    authenticationConfig:
      alias: STEPUP_MFA_MANDATORY
      config:
        loa-condition-level: 30
        loa-max-age: "{{ session_timeout }}"
  - displayName: Cookie
    providerId: auth-cookie
    flowAlias: StepUp Mandatory MFA Authentication
    requirement: ALTERNATIVE
  - displayName: Perform authentication (STEPUP_MFA_MANDATORY)
    flowAlias: StepUp Mandatory MFA Authentication
    requirement: ALTERNATIVE
    # description: Reauthenticate the user.
  - displayName: Username Password Form
    providerId: auth-username-password-form
    flowAlias: Perform authentication (STEPUP_MFA_MANDATORY)
    requirement: REQUIRED
  - displayName: MFA (STEPUP_MFA_MANDATORY)
    flowAlias: Perform authentication (STEPUP_MFA_MANDATORY)
    requirement: CONDITIONAL
    # description: Allow user to choose from MFA sources.
  - displayName: Condition - user configured
    providerId: conditional-user-configured
    flowAlias: MFA (STEPUP_MFA_MANDATORY)
    requirement: REQUIRED
  - displayName: OTP Form
    providerId: auth-otp-form
    flowAlias: MFA (STEPUP_MFA_MANDATORY)
    requirement: ALTERNATIVE
  - displayName: WebAuthn Authenticator
    providerId: webauthn-authenticator
    flowAlias: MFA (STEPUP_MFA_MANDATORY)
    requirement: ALTERNATIVE
  - displayName: Allow access
    providerId: allow-access-authenticator
    flowAlias: MFA (STEPUP_MFA_MANDATORY)
    requirement: REQUIRED
  - displayName: Deny access
    providerId: deny-access-authenticator
    flowAlias: Perform authentication (STEPUP_MFA_MANDATORY)
    requirement: REQUIRED
    authenticationConfig:
      alias: STEPUP_MFA_MANDATORY_MISSING
      config:
        denyErrorMessage: >-
          Login denied. This application requires multi-factor
          authentication, which is not currently configured for your
          user account.
          (STEPUP_MFA_MANDATORY_MISSING)
  - displayName: StepUp 1FA Authentication
    requirement: CONDITIONAL
    # description: Authenticate with username / password (no MFA needed).
  - displayName: Condition - Level of authentication
    providerId: conditional-level-of-authentication
    flowAlias: StepUp 1FA Authentication
    requirement: REQUIRED
    authenticationConfig:
      alias: STEPUP_1FA
      config:
        loa-condition-level: 10
        loa-max-age: "{{ session_timeout }}"
  - displayName: Cookie
    providerId: auth-cookie
    flowAlias: StepUp 1FA Authentication
    requirement: ALTERNATIVE
  - displayName: Perform authentication (STEPUP_1FA)
    flowAlias: StepUp 1FA Authentication
    requirement: ALTERNATIVE
    # description: Reauthenticate the user.
  - displayName: Username Password Form
    providerId: auth-username-password-form
    flowAlias: Perform authentication (STEPUP_1FA)
    requirement: REQUIRED
  - displayName: Optional required MFA
    flowAlias: Perform authentication (STEPUP_1FA)
    requirement: CONDITIONAL
    # description: Perform MFA if required for the user.
  - displayName: Condition - user role
    providerId: conditional-user-role
    flowAlias: Optional required MFA
    requirement: REQUIRED
    authenticationConfig:
      alias: MFA required for this user
      config:
        condUserRole: offline_access
  - displayName: MFA (STEPUP_1FA)
    flowAlias: Optional required MFA
    requirement: CONDITIONAL
    # description: Perform MFA if required for the user.
  - displayName: Condition - user configured
    providerId: conditional-user-configured
    flowAlias: MFA (STEPUP_1FA)
    requirement: REQUIRED
  - displayName: WebAuthn Authenticator
    providerId: webauthn-authenticator
    flowAlias: MFA (STEPUP_1FA)
    requirement: ALTERNATIVE
  - displayName: OTP Form
    providerId: auth-otp-form
    flowAlias: MFA (STEPUP_1FA)
    requirement: ALTERNATIVE
```
</details>

Idea is that the desired LoA (or ACR) will influence if MFA is required for the authentication, and if the user has to authenticate every time.
