### ISSUE TITLE
ERROR:  relation "public.migration_model" does not exist at character 25

### ISSUE THREAD

**Issue by outsinre** [keycloak/keycloak#29045]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

storage

### Describe the bug

After getting up keycloak container and postgres, see following error messages:

```
db             | 2024-04-24T07:06:46.195868633Z 2024-04-24 07:06:46.195 UTC [83] ERROR:  relation "public.migration_model" does not exist at character 25
db             | 2024-04-24T07:06:46.195901424Z 2024-04-24 07:06:46.195 UTC [83] STATEMENT:  SELECT ID, VERSION FROM public.MIGRATION_MODEL ORDER BY UPDATE_TIME DESC
db             | 2024-04-24T07:06:46.755066174Z 2024-04-24 07:06:46.754 UTC [83] ERROR:  relation "public.databasechangelog" does not exist at character 22
db             | 2024-04-24T07:06:46.755100966Z 2024-04-24 07:06:46.754 UTC [83] STATEMENT:  SELECT COUNT(*) FROM public.databasechangelog
db             | 2024-04-24T07:06:46.868267633Z 2024-04-24 07:06:46.868 UTC [84] ERROR:  relation "public.databasechangeloglock" does not exist at character 22
db             | 2024-04-24T07:06:46.868294091Z 2024-04-24 07:06:46.868 UTC [84] STATEMENT:  SELECT COUNT(*) FROM public.databasechangeloglock
db             | 2024-04-24T07:06:46.889815383Z 2024-04-24 07:06:46.889 UTC [83] ERROR:  relation "public.databasechangelog" does not exist at character 22
db             | 2024-04-24T07:06:46.889842758Z 2024-04-24 07:06:46.889 UTC [83] STATEMENT:  SELECT COUNT(*) FROM public.databasechangelog
```

### Version

quay.io/keycloak/keycloak:24.0.3

### Regression

- [x] The issue is a regression

### Expected behavior

Should not have such DB error messages.

### Actual behavior

See those error messages.

### How to Reproduce?

My Docker Compose YAML.

```
version: '3.5'
name: keycloak

services:
  db:
    image: postgres:14
    container_name: db
    environment:
      POSTGRES_PASSWORD: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak_idp
    volumes:
    - pg_data:/var/lib/postgresql/data
    ports:
    - "5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak", "-d", "keycloak_idp"]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: on-failure
  idp:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak.test
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: keycloak
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_SCHEMA: public
      KC_DB_URL: jdbc:postgresql://db/keycloak_idp
      KC_HOSTNAME: keycloak.test
      KC_HOSTNAME_STRICT: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME_DEBUG: true
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_LOG_LEVEL: INFO
      KC_METRICS_ENABLED: true
      QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY: true
    volumes:
    - ./ObjectStore/:/ObjectStore/          # https://github.com/keycloak/keycloak/issues/15255
    command: [ "start-dev", "--import-realm" ]
    ports:
    - "4080:4080"
    - "4443:4443"
    depends_on:
      db:
        condition: service_healthy
        restart: true

volumes:
  pg_data:
networks:
  default:
    name: test
    external: false
```
