### ISSUE TITLE
Can't enable file logging in a docker container and "org.keycloak.events"are only logged in sdout

### ISSUE THREAD

**Issue by ngthwi** [keycloak/keycloak#29120]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

In a docker container, the environment variable `KC_LOG: file` does not enable file logging (as described [in the documentation](https://www.keycloak.org/server/logging#_file_logging)). 
And even if `KC_LOG_LEVEL: DEBUG`, `org.keycloak.events`  are only logged in the container sdout.

### Version

19.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

 In a docker container, setting 'KC_LOG: file' should enable file logging to '/opt/jboss/keycloak/standalone/data/keycloak.log' and should log `org.keycloak.events`as well.

### Actual behavior

`org.keycloak.events` logs are only logged in the container sdout.

### How to Reproduce?

```
version: "3.9"
services:
  db:
    image: postgres:16
    container_name: Keycloak-DB
    hostname: keycloak-db
    mem_limit: 128m
    cpu_shares: 128
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "keycloak", "-U", "keycloakuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /volume1/docker/keycloak/db:/var/lib/postgresql/data:rw
    environment:
      TZ: Europe/London
      PGTZ: Europe/London
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloakuser
      POSTGRES_PASSWORD: my_kc_db_passwd
    restart: on-failure:5
    
  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      container_name: Keycloak
      restart: on-failure:5
      healthcheck:
       test: curl -f http://localhost:8080/ || exit 1
      environment:
        TZ: Europe/London
        DB_VENDOR: POSTGRES
        DB_ADDR: db
        DB_DATABASE: keycloak
        DB_USER: keycloakuser
        DB_SCHEMA: public
        DB_PASSWORD: my_kc_db_passwd
        KEYCLOAK_USER: my_kc_user
        KEYCLOAK_PASSWORD: my_kc_passwd
        PROXY_ADDRESS_FORWARDING: true
        KC_LOG: file
        KC_LOG_LEVEL: DEBUG
      ports:
        - 8080:8080
      volumes:
        - /docker/keycloak/data:/opt/jboss/keycloak/standalone/data      
        - /docker/keycloak/log:/opt/jboss/keycloak/standalone/log
      depends_on:
        - db
```
