### ISSUE TITLE
Support pod affinity settings in the Keycloak Operator

### ISSUE THREAD

**Issue by ahus1** [keycloak/keycloak#29258]
### Description

Kubernetes allows to specify affinity settings for Pods. 

This would allow: 
* avoiding to run multiple Keycloak instances on one node, avoiding data loss on a node failure (
* additional resilience strategies related to a Kubernetes topology (like avoid all Keycloak instances to be on servers on a specific rack, or a specific availability zone) 
* specifying Keycloak to run on ARM based nodes (similar to https://www.scaleway.com/en/docs/containers/kubernetes/how-to/deploy-x86-arm-images/)

### Motivation

* Better resilience against failures
* Cost-saving when using ARM

**Comment by ryanemerson** [comment]
FYI the Infinispan CR allows configurable affinity strategies, but also applies the following default to prefer that pods are scheduled to different nodes if possible:

```yaml
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app: infinispan-pod
              clusterName: <cluster_name>
              infinispan_cr: <cluster_name>
          topologyKey: "kubernetes.io/hostname"
```

https://infinispan.org/docs/infinispan-operator/main/operator.html#anti-affinity-strategies_availability

**Comment by shawkins** [comment]
@ahus1 @ryanemerson @vmuzikar to what extent are we looking to establish high availability of keycloak with embedded infinispan - or would we recommend using external infinispan?

Another consideration is that for managed kafka we didn't just want node anti-affinity but we also wanted a topology spread constraint across zones - which becomes trickier if we ever need to add stable storage into the mix. 

So what are we looking for the operator to assume / default to, and what do we want to document for users to do as part of the unsupported template?

**Comment by vmuzikar** [comment]
> to what extent are we looking to establish high availability of keycloak with embedded infinispan - or would we recommend using external infinispan?

I believe that the scenarios are covered by the HA guide.

> So what are we looking for the operator to assume / default to, and what do we want to document for users to do as part of the unsupported template?

I would say no defaults/assumptions, at least in the first iteration. Also -1 for documenting/suggesting to users the use of unsupported pod template.

**Comment by ryanemerson** [comment]
> @ahus1 @ryanemerson @vmuzikar to what extent are we looking to establish high availability of keycloak with embedded infinispan - or would we recommend using external infinispan?

We're not trying to achieve HA with embedded Infinispan, however I would argue that ensuring that session replicas are hosted on different k8s nodes is not High-Availability but just Availability :slightly_smiling_face:

Maybe I'm missing some considerations, but having a default anti-affinity strategy that ensures that Keycloak pods are distributed to disparate nodes seems like an easy usability (no additional config required) and resiliency (risk of session loss minimised) win for users that requires no additional knowledge on their part. Advanced users who require pods to be co-located on nodes etc can then apply more advanced configurations.


> Another consideration is that for managed kafka we didn't just want node anti-affinity but we also wanted a topology spread constraint across zones - which becomes trickier if we ever need to add stable storage into the mix.

A bit of a side-note, but this is something Infinispan also needs to add for external Infinispan deployments: https://github.com/infinispan/infinispan-operator/issues/1844

**Comment by shawkins** [comment]
> I believe that the scenarios are covered by the HA guide.

Maybe I'm missing something but it appears that external infinispan is mentioned only for multi-site, not single site HA. Single site HA is still possible if you can spread across availability zones - you don't need multiple clusters. 

Is there something implicit I don't know about the topology - for example if dealing with a single site then you always want infinispan embedded rather than externalized for performance? 

On a related note, it would probably also be good to have some topic on scale up / down considerations, I know that we didn't really expand on that when modifying keycloak to be a scalable resource.

> Maybe I'm missing some considerations, but having a default anti-affinity strategy that ensures that Keycloak pods are distributed to disparate nodes seems like an easy usability (no additional config required) and resiliency (risk of session loss minimised) win for users that requires no additional knowledge on their part

I agree - would this been done just for the operator, or would we like it to appear even in our Deployment yaml just in case a user wants to increase the replica count there. The only considerations would be: 
- I would still expect that users (and our integration tests) would want to run on a single node. We may need some flag to indicate to use preferred anti-affinity rather than required. We don't want the operator to infer what it should be because in clusters with node scaling the demand of an additional keycloak may be what is needed to create a new node.
- How it plays with the user supplying other affinities - via a yet to be determined first-class option, or via the unsupported template (if it's like the existing logic, the unsupported would trump most everything else).

> A bit of a side-note, but this is something Infinispan also needs to add for external Infinispan deployments:

That's good to know because it does mean we're not getting additional HA out-of-the-box currently just by using external infinispan.

**Comment by ryanemerson** [comment]
> Maybe I'm missing something but it appears that external infinispan is mentioned only for multi-site, not single site HA. Single site HA is still possible if you can spread across availability zones - you don't need multiple clusters.

It is possible, but from an Infinispan perspective we don't recommend using a "stretched" cluster whereby Infinispan nodes are spread across Availability-Zones as it causes the following issues:

- Reduced performance, due to increased latency between nodes
- Expensive state-transfer on rebalance caused by scale up/down or split-brain
- Lack of tooling (especially in Embedded) to handle split-brain, as this is provided by our xsite functionality

Furthermore, in order for such a setup to provide the expected availability it's necessary for [Server Hinting](https://infinispan.org/docs/stable/titles/configuring/configuring.html#server-hinting_clustered-caches) to be configured which Keycloak does not provide for it's Embedded instances.

> Is there something implicit I don't know about the topology - for example if dealing with a single site then you always want infinispan embedded rather than externalized for performance?
> 
> On a related note, it would probably also be good to have some topic on scale up / down considerations, I know that we didn't really expand on that when modifying keycloak to be a scalable resource.

I would say Embedded is chosen for simplicity reasons with single-site as it means one less component for users to configure. The main reason to use an external Infinispan with a single-site is that it decouples the session state from Keycloak, which allows for much greater flexibility when scaling up/down the Keycloak pods as you don't have to worry about Infinispan performing expensive rebalance operations.


> I agree - would this been done just for the operator, or would we like it to appear even in our Deployment yaml just in case a user wants to increase the replica count there. The only considerations would be:

I would strongly recommend against deploying Keycloak as a Deployment IF you're using an Embedded Infinispan instance, see [this previous discussion](https://github.com/keycloak/keycloak/discussions/11763#discussioncomment-2949975) for more details.

**Comment by shawkins** [comment]
> Furthermore, in order for such a setup to provide the expected availability it's necessary for [Server Hinting](https://infinispan.org/docs/stable/titles/configuring/configuring.html#server-hinting_clustered-caches) to be configured which Keycloak does not provide for it's Embedded instances.

Does that mean we should consider explicitly preventing the spread across AZs when running embedded infinispan?

> The main reason to use an external Infinispan with a single-site is that it decouples the session state from Keycloak, which allows for much greater flexibility when scaling up/down the Keycloak pods as you don't have to worry about Infinispan performing expensive rebalance operations.

Yes, I'd like to call that out in a guide.

> I would strongly recommend against deploying Keycloak as a Deployment IF you're using an Embedded Infinispan instance, see https://github.com/keycloak/keycloak/discussions/11763#discussioncomment-2949975 for more details.

Yes, we account for that in the operator. It didn't register when I looked at https://www.keycloak.org/getting-started/getting-started-kube - so we need a note on there about not using more than a single replica.

If there are no objections, I'll open some follow-up issues for the above.

**Comment by ryanemerson** [comment]
> Does that mean we should consider explicitly preventing the spread across AZs when running embedded infinispan?

Hmm yes, I think that would be for the best \cc @pruivo

**Comment by ahus1** [comment]
With a stretched setup, we would fear the latencies between AZs. We don't have a good strategy yet: We want to distribute things across AZs to make it fail safe, but keep things with an AZ to avoid the latencies. I think that will be a longer discussion that we would eventually need to settle and come up with a good design for.

**Comment by pruivo** [comment]
Infinispan is mostly I/O bound (network) and the main problem with stretched clusters is latency. I don't recommend stretched clusters but I'm aware of Infinispan users that are ok with the response times involved. Server hinting is a must with stretched clusters.
At the end of the day, it always ends up with the question: how much time can you afford to wait?

With the persistence session feature, the clustered caches can be removed or converted to local caches, minimizing the latency cost.

**Comment by vmuzikar** [comment]
Just to summarize the discussion if I understand correctly. The Operator could try setting some default pod affinity to ensure Keycloak with embedded Infinispan is deployed within the same AZ. Correct?

**Comment by shawkins** [comment]
In the shortest form what we're discussing here could look like the operator automatically adding something like:

```
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: "keycloak-name"
              topologyKey: "kubernetes.io/hostname"
          podAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/instance: "keycloak-name"
              topologyKey: "topology.kubernetes.io/zone"
```

Additional concerns:
- we'll want a more specific label for the keycloak pods - we already have the potential for an overlap between import job pods and keycloak pods
- how do allow for further customization - preferred vs required, weights? 
- should the affinity not be added if the cache is external - we have the limitation currently that we can't appropriately detect this if it's configured via a custom image
- Or should we just simply offer a first class section for affinity and let the user manage all of this on their own?

**Comment by shawkins** [comment]
After a discussion with @vmuzikar the direction we'd like to persue is to add a first class option to configure affinity via the Keycloak CR and document concerns like the above in the upcoming scaling / availability guide. This issue can be left open if desired to see if we want to take that a step further an offer even higher level / default support via the Keycloak CR / operator.

**Comment by ahus1** [comment]
My 2 cents: the `preferredDuringSchedulingIgnoredDuringExecution` + `topologyKey: "kubernetes.io/hostname"` is IMHO  a good general-purpose default setting for all users, with some users who want to eventually be more strict.

**Comment by abelmatos** [comment]
is not the case of using topologySpreadConstraints instead of affinity?
https://kubernetes.io/docs/concepts/scheduling-eviction/topology-spread-constraints/
```
         topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              app: keycloak
              app.kubernetes.io/instance: keycloak
              app.kubernetes.io/managed-by: keycloak-operator
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
        - labelSelector:
            matchLabels:
              app: keycloak
              app.kubernetes.io/instance: keycloak
              app.kubernetes.io/managed-by: keycloak-operator
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
```
