### ISSUE TITLE
Getting error for external infinispan cache in keycloak 24.0.3 

### ISSUE THREAD

**Issue by selimppc** [keycloak/keycloak#29274]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

I have followed the document : https://www.keycloak.org/high-availability/connect-keycloak-to-external-infinispan
and issue : https://github.com/keycloak/keycloak/issues/20031

I have created my cache-ispn.xml:

```
<?xml version="1.0" encoding="UTF-8"?>
<infinispan
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="urn:infinispan:config:14.0 http://www.infinispan.org/schemas/infinispan-config-14.0.xsd"
    xmlns="urn:infinispan:config:14.0">

    <cache-container name="keycloak">
        <transport cluster="infinispan" lock-timeout="60000"/>
    <!--    <transport cluster="infinispan" lock-timeout="60000"/>-->
        <local-cache name="realms">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <local-cache name="users">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <local-cache name="authorization">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <memory max-count="10000"/>
        </local-cache>
        <local-cache name="keys">
            <encoding>
                <key media-type="application/x-java-object"/>
                <value media-type="application/x-java-object"/>
            </encoding>
            <expiration max-idle="3600000"/>
            <memory max-count="1000"/>
        </local-cache>

        <distributed-cache name="sessions" owners="2" statistics="true">
            <expiration lifespan="-1"/>
            <persistence passivation="false">
                <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                              cache="sessions"
                              raw-values="true"
                              shared="true"
                              segmented="false">
                    <remote-server host="${env.KC_REMOTE_STORE_HOST}"
                                   port="${env.KC_REMOTE_STORE_PORT}"/>
                    <connection-pool max-active="16"
                                     exhausted-action="CREATE_NEW"/>
                    <security>
                        <authentication server-name="infinispan">
                            <digest username="${env.KC_REMOTE_STORE_USERNAME}"
                                    password="${env.KC_REMOTE_STORE_PASSWORD}"
                                    realm="default"/>
                        </authentication>
                    </security>
                </remote-store>
            </persistence>
        </distributed-cache>
        <distributed-cache name="actionTokens" owners="2" statistics="true">
            <expiration lifespan="-1"/>
            <persistence passivation="false">
                <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                          cache="actionTokens"
                          purge="false"
                          preload="false"
                          segmented="false"
                          shared="true"
                          raw-values="true"
                          marshaller="org.keycloak.cluster.infinispan.KeycloakHotRodMarshallerFactory"
                >
                    <remote-server host="${env.KC_REMOTE_STORE_HOST}"
                                   port="${env.KC_REMOTE_STORE_PORT}"/>
                    <connection-pool max-active="16"
                                     exhausted-action="CREATE_NEW"/>
                    <security>
                        <authentication server-name="infinispan">
                            <digest username="${env.KC_REMOTE_STORE_USERNAME}"
                                    password="${env.KC_REMOTE_STORE_PASSWORD}"
                                    realm="default"/>
                        </authentication>
                    </security>
                </remote-store>
            </persistence>
        </distributed-cache>

        <replicated-cache name="work" statistics="true">
            <expiration lifespan="-1"/>
            <persistence passivation="false">
                <remote-store xmlns="urn:infinispan:config:store:remote:14.0"
                              cache="work"
                              raw-values="true"
                              shared="true"
                              segmented="false">
                    <remote-server host="${env.KC_REMOTE_STORE_HOST}"
                                   port="${env.KC_REMOTE_STORE_PORT}"/>
                    <connection-pool max-active="16"
                                     exhausted-action="CREATE_NEW"/>
                    <security>
                        <authentication server-name="infinispan">
                            <digest username="${env.KC_REMOTE_STORE_USERNAME}"
                                    password="${env.KC_REMOTE_STORE_PASSWORD}"
                                    realm="default"/>
                        </authentication>
                    </security>
                </remote-store>
            </persistence>
        </replicated-cache>
    </cache-container>
</infinispan>
```

and My Dockerfile:

```
ARG KEYCLOAK_VERSION=24.0.3
....
FROM quay.io/keycloak/keycloak:${KEYCLOAK_VERSION} as keycloak-builder

WORKDIR /opt/keycloak
....

# Cache Infinispan
COPY ./mvn/extensions/cache/cache-ispn.xml /opt/keycloak/conf/cache-ispn.xml

RUN /opt/keycloak/bin/kc.sh build --cache=ispn --cache-stack=tcp --cache-config-file=cache-ispn.xml --verbose
.....
```

I am getting error:

```
keycloak-1  | 2024-05-03 15:19:06,390 WARN  [org.infinispan.HOTROD] (Thread-0) ISPN004005: Error received from the server: org.infinispan.server.hotrod.CacheNotFoundException: Cache with name 'actionTokens' not found amongst the configured caches
keycloak-1  | 2024-05-03 15:19:06,406 ERROR [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000660: Cache actionTokens start failed, stopping any running components: org.infinispan.commons.CacheConfigurationException: ISPN000659: Component ComponentWrapper{name=org.infinispan.persistence.manager.PersistenceManager, instance=org.infinispan.persistence.manager.PersistenceManagerImpl@56223a59, status=FAILED} failed to start
keycloak-1  |   at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:584)
keycloak-1  |   at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:807)
keycloak-1  |   at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:634)
keycloak-1  |   at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:598)

keycloak-1  | Caused by: java.lang.NullPointerException: Cannot invoke "org.infinispan.client.hotrod.impl.InternalRemoteCache.ping()" because "this.remoteCache" is null
keycloak-1  |   at org.infinispan.persistence.remote.RemoteStore.lambda$start$0(RemoteStore.java:136)
keycloak-1  |   at org.infinispan.util.concurrent.BlockingManagerImpl.lambda$supplyBlockingOperation$3(BlockingManagerImpl.java:155)
keycloak-1  |   at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
keycloak-1  |   ... 5 more
keycloak-1  | 
...
keycloak-1  | 2024-05-03 15:19:07,578 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start server in (production) mode
keycloak-1  | 2024-05-03 15:19:07,578 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to start caches
keycloak-1  | 2024-05-03 15:19:07,579 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: org.infinispan.manager.EmbeddedCacheManagerStartupException: ISPN000659: Component ComponentWrapper{name=org.infinispan.persistence.manager.PersistenceManager, instance=org.infinispan.persistence.manager.PersistenceManagerImpl@56223a59, status=FAILED} failed to start
keycloak-1  | 2024-05-03 15:19:07,579 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: ISPN000659: Component ComponentWrapper{name=org.infinispan.persistence.manager.PersistenceManager, instance=org.infinispan.persistence.manager.PersistenceManagerImpl@56223a59, status=FAILED} failed to start
keycloak-1  | 2024-05-03 15:19:07,579 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: ISPN000659: Component ComponentWrapper{name=org.infinispan.persistence.manager.PersistenceManager, instance=org.infinispan.persistence.manager.PersistenceManagerImpl@56223a59, status=FAILED} failed to start
keycloak-1  | 2024-05-03 15:19:07,579 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: java.lang.NullPointerException: Cannot invoke "org.infinispan.client.hotrod.impl.InternalRemoteCache.ping()" because "this.remoteCache" is null
keycloak-1  | 2024-05-03 15:19:07,579 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Cannot invoke "org.infinispan.client.hotrod.impl.InternalRemoteCache.ping()" because "this.remoteCache" is null
keycloak-1  | 2024-05-03 15:19:07,579 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) For more details run the same command passing the '--verbose' option. Also you can use '--help' to see the details about the usage of the particular command.
keycloak-1 exited with code 1

....

```

I have deployed Infinispan in a separate machine say: `http://ip_address:11222` and I exposed all ports in inbound rules. All ports are open. 

I am confused about the connection between Infinispan and keycloak through `cach-ispn.xml`. 

I have set up Infinispan in Kubernetes - and I got the same error. That's why trying with a separate machine to connect keycloak and Infinispan.

### Version

24.0.3

### Regression

- [ ] The issue is a regression

### Expected behavior

According to the doc - It should work for multiple pods with the cache. 
The Infinispan cache would allow us to get distributed cache for multiple keycloak pods and scale. a 

### Actual behavior

The cache-ispn.xml gets errors all the time. without using `--cache-config-file=cache-ispn.xml` my application runs except for sessions. 

### How to Reproduce?

Step 1: using 24.0.3 image , need to add above cache-ispn.xml in /opt/keycloak/conf/cache-ispn.xml

Step 2: build like this:

```
RUN /opt/keycloak/bin/kc.sh build --cache=ispn --cache-stack=tcp --cache-config-file=cache-ispn.xml --verbose
```

Step 3: Run the application 

You will get the error. 

Note I deployed Infinispan version `14.0.27.Final` in my machine `http://ip_address:11222/console/`

**Comment by ahus1** [comment]
@selimppc - there are several entries for "distributed-cache" missing in your configuration. 

See https://github.com/keycloak/keycloak/blob/24.0.3/quarkus/runtime/src/main/resources/cache-ispn.xml for the original file. 

Please try again with an XML file which contains all caches.

**Comment by selimppc** [comment]
@ahus1 Thank you for the configuration file.

Now I am trying to understand and Looking for the configuration of the following questions:
1. how can I connect the external cache using an IP address ( say I set up my Infinispan in Ec2)?
2. How do I connect Infinispan when my Infinispan cluster is in Kubernetes?


I appreciate your help.

**Comment by ahus1** [comment]
When you set up Infinispan, there will be an IP address and port to connect with it using the Hot Rod protocol. When using an ec2 setup, I assume you'll have a loadbalancer of some kind (either a reverse proxy a DNS) to provide a single DNS entry or IP address where client connect to. 

There is also a Keycloak guide how to deploy Infinispan to Kubernetes with the Infinispan Operator, see https://www.keycloak.org/high-availability/deploy-infinispan-kubernetes-crossdc

Note that with Keycloak 24.0.4 (released today) we've simplified the configuration to connect Keycloak to an external Infinispan for X-Site setups. There is no need to change the XML any more. See https://www.keycloak.org/high-availability/connect-keycloak-to-external-infinispan for the udpated docs.

**Comment by selimppc** [comment]
@ahus1 pardon me - I am confused now

keycloak version is `24.0.4` 

say I have deployed `infinispan` separately in another location and I configured yaml as below:

```
apiVersion: v1
kind: Secret
metadata:
  name: remote-store-secret
  namespace: default
type: Opaque
data:
  username: xxxxxxx= 
  password: xxxxxxx= 

---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: keycloak
  name: keycloak
  namespace: default
spec:
  additionalOptions:
    - name: cache-remote-host 
      value: "18.142.142.220"
    - name: cache-remote-port 
      value: "11222"
    - name: cache-remote-username 
      secret:
        name: remote-store-secret
        key: username
    - name: cache-remote-password 
      secret:
        name: remote-store-secret
        key: password
    - name: spi-connections-infinispan-quarkus-site-name 
      value: keycloak
```

and my keycloak.yaml is:
```
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: default
  labels:
    app: keycloak
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: keycloak
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  namespace: default
  labels:
    app: keycloak
spec:
  serviceName: "keycloak"
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: 267026814870.dkr.ecr.ap-southeast-1.amazonaws.com/keycloak:dev-9e80751d
        command: ["/opt/keycloak/bin/kc.sh"]
        args: [
            "start",
            "--proxy-headers=forwarded",
            "--optimized",
            "--db-pool-initial-size=10",
          ]
        envFrom:
         - secretRef:
              name: dev-saas-keycloak-secrets
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health/ready  # Updated path for readiness probe
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /health  # Updated path for liveness probe
            port: http
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5

```

the keycloak still getting error or creating embedded ispn cache: logs:

```
2024-05-08 13:07:59,950 WARN  [org.keycloak.quarkus.runtime.cli.Picocli] (main) The following used options or option values are DEPRECATED and will be removed in a future release:
	- proxy: Use proxy-headers.
Consult the Release Notes for details.
2024-05-08 13:08:07,720 INFO  [org.infinispan.CONTAINER] (keycloak-cache-init) ISPN000556: Starting user marshaller 'org.infinispan.jboss.marshalling.core.JBossUserMarshaller'
2024-05-08 13:08:08,368 INFO  [org.keycloak.quarkus.runtime.hostname.DefaultHostnameProvider] (main) Hostname settings: Base URL: <unset>, Hostname: accounts.development.bongo-solutions.com, Strict HTTPS: true, Path: <request>, Strict BackChannel: false, Admin URL: https://accounts.development.bongo-solutions.com, Admin: accounts.development.bongo-solutions.com, Port: -1, Proxied: true
2024-05-08 13:08:09,010 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
2024-05-08 13:08:10,341 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000078: Starting JGroups channel `ISPN`
2024-05-08 13:08:10,357 INFO  [org.jgroups.JChannel] (keycloak-cache-init) local_addr: ae937555-068c-4887-83f7-0760dedd05fd, name: keycloak-0-36673
2024-05-08 13:08:10,412 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1MB, but the OS only allocated 212.99KB
2024-05-08 13:08:10,412 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 20MB, but the OS only allocated 212.99KB
2024-05-08 13:08:10,413 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the send buffer of socket MulticastSocket was set to 1MB, but the OS only allocated 212.99KB
2024-05-08 13:08:10,413 WARN  [org.jgroups.protocols.UDP] (keycloak-cache-init) JGRP000015: the receive buffer of socket MulticastSocket was set to 25MB, but the OS only allocated 212.99KB
2024-05-08 13:08:10,621 INFO  [org.jgroups.protocols.FD_SOCK2] (keycloak-cache-init) server listening on *.19438
2024-05-08 13:08:12,639 INFO  [org.jgroups.protocols.pbcast.GMS] (keycloak-cache-init) keycloak-0-36673: no members discovered after 2006 ms: creating cluster as coordinator
2024-05-08 13:08:12,712 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000094: Received new cluster view for channel ISPN: [keycloak-0-36673|0] (1) [keycloak-0-36673]
2024-05-08 13:08:12,855 INFO  [org.infinispan.CLUSTER] (keycloak-cache-init) ISPN000079: Channel `ISPN` local address is `keycloak-0-36673`, physical addresses are `[192.194.8.60:34974]`
2024-05-08 13:08:12,939 WARN  [org.infinispan.CONFIG] (keycloak-cache-init) ISPN000569: Unable to persist Infinispan internal caches as no global state enabled
2024-05-08 13:08:29,539 INFO  [org.keycloak.connections.infinispan.DefaultInfinispanConnectionProviderFactory] (main) Node name: keycloak-0-36673, Site name: null
2024-05-08 13:08:29,549 INFO  [org.keycloak.broker.provider.AbstractIdentityProviderMapper] (main) Registering class org.keycloak.broker.provider.mappersync.ConfigSyncEventListener
2024-05-08 13:08:34,213 INFO  [io.quarkus] (main) Keycloak 24.0.4 on JVM (powered by Quarkus 3.8.4) started in 36.653s. Listening on: http://0.0.0.0:8080
2024-05-08 13:08:34,215 INFO  [io.quarkus] (main) Profile prod activated.
2024-05-08 13:08:34,217 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-postgresql, keycloak, logging-gelf, micrometer, narayana-jta, reactive-routes, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, smallrye-health, vertx]
```
