### ISSUE TITLE
Attempting to launch Keycloak under a certian URL route with Nginx results in "Timeout when waiting for 3rd party check iframe message"

### ISSUE THREAD

**Issue by michaelnicol** [keycloak/keycloak#29843]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I am trying to make it so that when the user goes to https://mywebsite.com/keycloak/, it will load the admin console. Any future requests to Keycloak must go through the /keycloak/ route.

The issue is that this will throw a ```Timeout when waiting for 3rd party check iframe message```, and Nginx and Keycloak do not have any indicators in the error logs as to why this happens.

(My website is not mywebsite.com, this is just a placeholder)

### Version

24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

When the user goes to mywebsite.com/keycloak/, it will redirect to the admin console and allow me to edit user information. 

When I check my docker-container logs for both Nginx and Keycloak, it just says that the admin console was status 200 with no errors. No other logs indicate why the iframe refuses to load.

### Actual behavior

The admin UI loads indefinitely, and the console throws the error "Timeout when waiting for 3rd party check iframe message".
at https://www.mywebsite.com/keycloak/admin/master/console/.

This happens in both ```start``` and ```start-dev``` mode.

### How to Reproduce?

My Keycloak and Nginx use the following ```docker-compose```.

```
version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/mywebsite/website-frontend/dist:/var/www/mywebsite/website-frontend/dist:ro
    command: ["nginx-debug", '-g', 'daemon off;']
    depends_on:
      - keycloak
    networks:
      - keycloak-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: custom-keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_PROXY=edge
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HOSTNAME_URL=https://www.mywebsite.com
      - KC_HOSTNAME_PATH=/keycloak
      - KC_HOSTNAME_ADMIN_URL=https://www.mywebsite.com/keycloak/
      - KC_FRONTEND_URL=https://www.mywebsite.com/keycloak/
      - KC_HTTP_RELATIVE_PATH=/keycloak
      - KC_HTTP_ENABLED=true
    volumes:
      - keycloak_data:/opt/keycloak/data
    command: start
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge

volumes:
  keycloak_data:
  ```
  And my Nginx that the compose references:
  
  ```
  server {
    server_name mywebsite.com www.mywebsite.com;

    proxy_set_header X-Forwarded-For $proxy_protocol_addr; 
    proxy_set_header X-Forwarded-Proto $scheme; 
    proxy_set_header Host $host; 

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
    }

    location /keycloak/ {
        proxy_pass http://keycloak:8080/keycloak/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        root /var/www/mywebsite/cba-frontend/dist;
        try_files $uri $uri/ /index.html;
    }

    listen 443 ssl; 
    ssl_certificate /etc/letsencrypt/live/mywebsite.com/fullchain.pem; 
    ssl_certificate_key /etc/letsencrypt/live/mywebsite.com/privkey.pem; 
    include /etc/letsencrypt/options-ssl-nginx.conf; 
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; 
}

server {
    if ($host = www.mywebsite.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    if ($host = mywebsite.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name mywebsite.com www.mywebsite.com;
    return 404; # managed by Certbot
}
```
