### ISSUE TITLE
Importing realm at start fails

### ISSUE THREAD

**Issue by aco-mreble** [keycloak/keycloak#30122]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

import-export

### Describe the bug

After upgrading from 21 to 24 I cant import the realm at startup with `--import-realm` anymore.

### Version

24.0.5

### Regression

- [X] The issue is a regression

### Expected behavior

When there is no realm it should import it and then automatically start

### Actual behavior

 I got this error:

> keycloak-1  | Option: 'start-dev --help' is not expected to contain whitespace, please remove any unnecessary quoting/escaping
> keycloak-1  | Did you mean: kc.sh start-dev or kc.sh start or kc.sh import?
> keycloak-1  | Try 'kc.sh --help' for more information on the available options.

### How to Reproduce?

docker-compose.yml:

```yml
keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command:
      - start-dev --import-realm
    ports:
      - "8080:8080"
    volumes:
      - ./config/keycloak:/opt/keycloak/data/import
    environment:
      # ....
```

### Anything else?

The documentation says that it should still work that way https://www.keycloak.org/server/importExport
