### ISSUE TITLE
Identity Provider Login ignores domain when trying to forward

### ISSUE THREAD

**Issue by Rainson12** [keycloak/keycloak#30169]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

When configuring an IdP like Entra Id / Azure AD authentication or any other provider it seems that the login page does not forward to the authorize endpoint.
OIDC Settings in Keycloak:
![image](https://github.com/keycloak/keycloak/assets/13119203/3ec26cf7-a3f8-4d9d-9aa6-ca264dc660ef)

This is how the login page then looks like:
![image](https://github.com/keycloak/keycloak/assets/13119203/0529282f-269d-46c0-aa4f-9be293bcc7f9)

However when I click on "Microsoft" it doesnt take me to the login.microsoftonline.com website but instead will try to reach it using the currents domain website
![image](https://github.com/keycloak/keycloak/assets/13119203/e7d14336-d2e9-4ac2-a3f6-6b5be4599e54)

The incorrect redirect URL is returned by the initial request:
![image](https://github.com/keycloak/keycloak/assets/13119203/8e2c9b4b-8e5e-4fdd-b505-2f3c9330aeb7)
somehow the domain just gets "replaced" with the current host.

### Version

24.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

I would correctly be forwarded to 
https://login.microsoftonline.com/54027e2f******/oauth2/v2.0/authorize?scope.....

### Actual behavior

I am just forwarded to the same domain just with /54027e2f******/oauth2/v2.0/authorize?scope.....
so if keycloak is hosted at "auth.DOMAIN.com" it would take me to auth.DOMAIN.com/54027e2f******/oauth2/v2.0/authorize?scope.....

### How to Reproduce?

Its a brand new installation, hosted via docker. This is the config:

```
services:
  keycloak:
      image: quay.io/keycloak/keycloak:24.0.5
      restart: always
      deploy:
        resources:
           limits:
              memory: 4096M
      environment:
       - KC_DB=postgres
       - KC_DB_URL=jdbc:postgresql://db03:5432/keycloak
       - KC_DB_USERNAME=keycloak
       - KC_DB_PASSWORD=PASSWORD
       - KEYCLOAK_ADMIN=admin
       - KEYCLOAK_ADMIN_PASSWORD=PASSWORD
       - KC_PROXY_HEADERS=forwarded
       - KC_HOSTNAME=auth.DOMAIN.com
       - KC_HTTPS_CERTIFICATE_FILE=/etc/x509/https/tls.crt
       - KC_HTTPS_CERTIFICATE_KEY_FILE=/etc/x509/https/tls.key
      volumes:
        - "/etc/ssl/indivumed/certificates/_.indivumed.com.crt:/etc/x509/https/tls.crt"
        - "/etc/ssl/indivumed/certificates/_.indivumed.com.key:/etc/x509/https/tls.key"
      ports:
        - 8010:8443
      command:
        - start
        - --verbose
```
