### ISSUE TITLE
Newly created roles cant be selected to assign to a user

### ISSUE THREAD

**Issue by Robbert-Brand** [keycloak/keycloak#30697]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

user-profile

### Describe the bug

Since the update to the latest keycloak container, being keycloak container 25.0.1-0, we can no longer assign Realm Roles that we created to users. Only pre-existing roles can be assigned.

### Version

keycloak container 25.0.1-0

### Regression

- [X] The issue is a regression

### Expected behavior

I would expect, that after creating a new Real Role (named test), I could go to Users or Groups -> Role mapping -> Assign role, and select my newly created role. However, only pre-existing *(built-in) roles are visible.

### Actual behavior

The newly created role does not appear in the menu.

### How to Reproduce?

We use the following compose file to spin up KeyCloak.

```
services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_LOG_LEVEL=INFO
      - KC_PROXY_HEADERS=xforwarded
      # - KC_HTTP_ENABLED=true
    ports:
      - 8080:8080
    restart: always
    volumes:
      - keycloak-state:/opt/keycloak/data/
    command: start-dev
    logging:
      driver: "json-file"
      options: 
          max-size: ${LOG_MAX_SIZE}
          max-file: ${LOG_MAX_FILE}
```

Create a new Realm, in which to create the new User and Role.
