### ISSUE TITLE
Issue in Migrating from 22.0.3 to 24.0.4

### ISSUE THREAD

**Issue by karthiknagraj** [keycloak/keycloak#31152]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I was using keycloak:22.0.3 as a microservice deployed on kubernetes cluster. I upgraded from 22.0.3 to 24.0.4, After the upgrade, I am not able to access the Keycloak UI. 
I had provided below config in 22.0.3 and it was working fine without any issue. Is there any additional configuration that I need to do for 24.0.4?

```
        args:
        - start 
        - --proxy 
        - edge
        - -Djboss.bind.address.private=127.0.0.1
        - -Djboss.bind.address=0.0.0.0
        env:
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: admin
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KC_TRANSACTION_XA_ENABLED
          value: "false"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "false"
        - name: KC_HOSTNAME_PORT
          value: "8088"
        - name: KC_HEALTH_ENABLED
          value: "true"
        - name: KC_METRICS_ENABLED
          value: "true"
```

### Version

24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

I expect to access the keycloak UI, Without any issue.

### Actual behavior

I am not able to access the keycloak UI

### How to Reproduce?

1. Create a keycloak deployment/statefulset resource with image of keycloak/keycloak:24.0.4 and deploy it in a kubernetes cluster.
2. Create a service and with the service, we should be able to access keycloak UI
