### ISSUE TITLE
IdP redirect URL shows hostname_admin

### ISSUE THREAD

**Issue by kochen** [keycloak/keycloak#31244]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

We are using a dedicated `hostname-admin` URL.
When creating a new IdP (i,e SSO with clients' AD), we have to share the redirect URL. The URL contains the admin url and not the frontend url.

### Version

25.0.1

### Regression

- [X] The issue is a regression

### Expected behavior

Frontend/Backend URL should be used to expose URLs and not the Administration URL.

Keycloak `v25.0.0` works as expected!

### Actual behavior

The URL contains the admin url and not the frontend url.

#### Running keycloak `25.0.1`
```yaml
services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    command: ["start-dev"]
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_HOSTNAME: http://localhost:8081
      KC_HOSTNAME_ADMIN: http://localhost:8082
    ports:
      - 8081:8080
      - 8082:8080
```
- browse to `http://localhost:8082` <- the admin console URL
- Go to `Identity providers` (bottom left main menu)
- create a new Identity Provider - doesn't matter which type (all have the same issue)
- Observe the Redirect URL: 
![image](https://github.com/user-attachments/assets/53181b47-7bc7-45b8-a8eb-49abbc00f1b8)
(shows the **admin** hostname)

#### Running keycloak `25.0.0`
```yaml
services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    command: ["start-dev"]
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_HOSTNAME: http://localhost:8081
      KC_HOSTNAME_ADMIN: http://localhost:8082
    ports:
      - 8081:8080
      - 8082:8080
```
- browse to `http://localhost:8082` <- the admin console URL
- Go to `Identity providers` (bottom left main menu)
- create a new Identity Provider - doesn't matter which type (all have the same issue)
- Observe the Redirect URL: 
![image](https://github.com/user-attachments/assets/b41761ef-41a0-44f8-87fe-6b83d1240c83)
(shows the **frontend** hostname)
