### ISSUE TITLE
Keycloak on azure mysql flexible server "Certificates do not conform to algorithm constraints" errors.

### ISSUE THREAD

**Issue by varun-thantry** [keycloak/keycloak#31274]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dependencies

### Describe the bug

in azure mysql flexible server , if the server parameter - "require_secure_transport" is set to OFF and if i use useSSL=false in KC_DB_URL then keycloak will connect to the database and work fine.
But if i set the "require_secure_transport" is set to ON , which is the default behaviour and gthen useSSL=true in KC_DB_URL then i get the following error :

`2023-03-10T13:54:44.250741391Z 2023-03-10 13:54:44,192 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Failed to obtain JDBC connection
2023-03-10T13:54:44.253996869Z 2023-03-10 13:54:44,192 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: SSL error: Certificates do not conform to algorithm constraints
2023-03-10T13:54:44.254005969Z 2023-03-10 13:54:44,192 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Certificates do not conform to algorithm constraints
2023-03-10T13:54:44.254020670Z 2023-03-10 13:54:44,193 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Certificates do not conform to algorithm constraints
2023-03-10T13:54:44.254027270Z 2023-03-10 13:54:44,194 ERROR [org.keycloak.quarkus.runtime.cli.ExecutionExceptionHandler] (main) ERROR: Algorithm constraints check failed on signature algorithm: SHA1withRSA`

please provide me a method on how to achieve this . 

Thank you in advance.

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak should successfully establish a secure connection to Azure MySQL Flexible Server when SSL is enabled on both ends.

### Actual behavior

Keycloak fails to connect, citing SSL certificate algorithm constraints. This occurs even with `useSSL=true` configured in the jdbc url.

### How to Reproduce?

1. Deploy Keycloak using the configuration provided.
2. Configure Azure MySQL Flexible Server with `require_secure_transport=ON`.
3. Start Keycloak and observe the SSL certificate verification errors.

### Anything else?

the below is my deployment file for keycloak:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:25.0.1
          command: ["start"]  
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY
              value: "edge"
            - name: KC_DB
              value: "mysql" 
            - name: KC_DB_URL
              value: "<jdbc url of azure mysql flexible server>"
            - name: KC_DB_URL_HOST
              value: "mysql"
            - name: KC_DB_URL_PORT
              value: "3306"
            - name: KC_DB_URL_DATABASE
              value: "keycloak"
            - name: KC_DB_USERNAME
              value: "root"
            - name: KC_DB_PASSWORD
              value: "password"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
              
   ```
   when i referred the internet for a solution i found solution and workaround for postgresql server but i didnt find any for the azure mysql flexible server .
but still i gave a try for the following method :
https://github.com/keycloak/keycloak/issues/17606#issuecomment-1472289443
but this does not work azure mysql flexible server.
