### ISSUE TITLE
Seeing `Client cannot marshall the server's key media type` with external Infinispan after 25 upgrade 

### ISSUE THREAD

**Issue by xgp** [keycloak/keycloak#31420]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

Instances of `Client cannot marshall the server's key media type ('application/x-java-object'). This could cause poor performance.` in the logs. No other functionality issues.

### Version

25.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

No log warning.

### Actual behavior

Above log messages.

### How to Reproduce?

Create external infinispan `15.0.4` with the operator and configure caches for keycloak as:
```yaml
  distributedCache: 
    owners: "2"
    mode: "SYNC"
    remoteTimeout: "17500"
    statistics: "true"
    encoding: 
      key: 
        mediaType: "application/x-jboss-marshalling"
      value: 
        mediaType: "application/x-jboss-marshalling"
    locking: 
      concurrencyLevel: "1000"
      acquireTimeout: "5000"
      striping: "false"
    expiration: 
      lifespan: "900000000000000000"
    stateTransfer: 
      timeout: "60000"
```

On the keycloak side, don't change the cache config xml file. Just set the `KC_CACHE_REMOTE_*` vars.

Create sessions as normal (e.g. log into the admin or account console).

### Anything else?

This didn't happen with `24`, but we use the cache config xml file to specify the remote cache options.
