### ISSUE TITLE
keycloak Public Client secret are updated frequently

### ISSUE THREAD

**Issue by CJsPod** [keycloak/keycloak#31444]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

token-exchange

### Describe the bug

We upgrade to 25.0.1 and since upgrade we see keycloak Public Client secret are constantly updated. We are using legacy realm operator to create this. The only difference we see in previous client and after update is "Front channel logout" is true now which was disabled earlier. The secret update might be happening after each logout action but we are still validating it.

Here is sample representation of public client 
```
Name:         dummy-realm-frontend-client
Namespace:    security
Labels:       app=dummy-realm-frontend-client
Annotations:  <none>
API Version:  legacy.k8s.keycloak.org/v1alpha1
Kind:         KeycloakClient
Metadata:
  Finalizers:
    client.cleanup
  Generation:        9
  Resource Version:  2530948865
  UID:               8936b68e-5fd1-43c9-83fe-b55a970a86c8
Spec:
  Client:
    Client Authenticator Type:  client-secret
    Client Id:                  dummy-realm-frontend-client
    Default Client Scopes:
      email
      profile
      roles
    Direct Access Grants Enabled:  true
    Id:                            cf662df7-9027-4c60-84fc-8c09e900fd7e
    Implicit Flow Enabled:         true
    Name:                          dummy-realm-frontend-client
    Optional Client Scopes:
      address
      microprofile-jwt
      offline_access
      phone
      web-origins
    Protocol:  openid-connect
    Protocol Mappers:
      Config:
        access.token.claim:    true
        claim.name:            groups
        id.token.claim:        false
        jsonType.label:        String
        Multivalued:           true
        user.attribute:        user_groups
        userinfo.token.claim:  true
      Consent Required:        false
      Id:                      16761d4f-3903-3c7d-ac76-e0ea1a842f36
      Name:                    dummy-realm-frontend-client-user-groups-mapper
      Protocol:                openid-connect
      Protocol Mapper:         oidc-usermodel-attribute-mapper
    Public Client:             true
    Redirect Uris:
      http://localhost/*
    Standard Flow Enabled:  true
    Web Origins:
      http://localhost
  Realm Selector:
    Match Labels:
      App:  dummy-realm
  Scope Mappings:
Status:
  Message:  
  Phase:    reconciling
  Ready:    true
  Secondary Resources:
    Secret:
      keycloak-client-secret-dummy-realm-frontend-client

```

Any suggestions would be appreciated. 

### Version

25.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Secret should not be updated very frequently

### Actual behavior

client Secret is updated frequently

### How to Reproduce?

See details above

**Comment by rmartinc** [comment]
Hi @CJsPod!

When you say the secret you mean the `secret` that authenticates the client, right? AFAIK the secret is not stored for public clients (they are public and they don't have any secret or other method to authenticate). The `secret` is used for confidential clients and not for public ones. For example, using the console, if you select the client as public (client authentication to off), the credentials tab disappear, because that client is not authenticated.

 Nevertheless I'm moving the issue to the cloud team because I think this is more related to the operator. Just move back if you think is something related to the core team.

**Comment by steadyk** [comment]
We are facing this on the Kubernetes secret which the (old) Keycloak Operator creates for the Keycloak client.

The `CLIENT_SECRET` itself, as you mentioned, should be empty since this is a frontend client with implicit flow enabled.

But since Keycloak 25 we are facing the strange behavior that the Kubernetes secret will be updated and a `CLIENT_SECRET` will be added.

E.g. we have this Kubernetes secret:

```yaml
apiVersion: v1
data:
  CLIENT_ID: xxx
  CLIENT_SECRET: ""
kind: Secret
metadata:
  name: test-realm-frontend-client
```

After some time (we actually do not know the reason), the Kubernetes secret will be updated to:

```yaml
apiVersion: v1
data:
  CLIENT_ID: xxx
  CLIENT_SECRET: yyy
kind: Secret
metadata:
  name: test-realm-frontend-client
```

This stays then for a couple of seconds and will be set back to the version without `CLIENT_SECRET`.

For us this looks like that Keycloak itself seams to change this, but we don't know.

**Comment by shawkins** [comment]
> Nevertheless I'm moving the issue to the cloud team because I think this is more related to the operator. Just move back if you think is something related to the core team.

@rmartinc the old operator is no longer supported by the community.

I'm not sure how the old operator and Keycloak 25 are being used together here. It is probably safe to close, or just mark as priority-low and leave it as a community issue in case others want to assist. cc @vmuzikar 

> For us this looks like that Keycloak itself seams to change this, but we don't know.

The Keycloak server, legacy or new, does not directly manipulate kubernetes resources.

**Comment by steadyk** [comment]
Thanks. Yes we are using the old operator (aka [realm-operator](https://github.com/keycloak/keycloak-realm-operator)), because the new operator currently does not support CustomResources for realms, users and clients.

We currently don't know, whether and when those CRDs will be supported by the new operator. Is there any better alternative, which could be used to manage realms, clients and users programmatically without the UI and direct API calls?
Maybe the [keycloak-config-cli](https://github.com/adorsys/keycloak-config-cli).

**Comment by steadyk** [comment]
We probably found our root cause:

We use an own realm-controller which itself uses
* the realm-operator (the old Keycloak operator) for most cases
* and some direct API calls

One of these direct API calls where done for adding post logout uris to the Keycloak client.
The periodically updates of these post logout uris seemed to cause our issue with the toggling client secrets on our public frontend client.

Surprisingly we saw then client secrets on the Keycloak client, even though the `publicClient` field on the client was `true`.
The secret was only visible if we fetch the secret via the API `<keycloak-url>/auth/admin/realms/<realm>/clients/<client-id>/client-secret`.
The `secret` field on the whole client representation with `<keycloak-url>/auth/admin/realms/<realm>/clients/<client-id>` was not present though.

We actually do not know why this happens.

We now directly set the post logout uris via the KeycloakClient CR which seems to avoid the issue.

**Comment by rmartinc** [comment]
@steadyk If you want us to continue with this we need to have clear how to reproduce this. For what I understand you have something that periodically change the valid post redirect URIs using the REST API and that was somehow regenerating the secrets, right?

Can you please check if you can simulate that using plain curl? That way you can send us proper reproducing steps. If not is very complicated that we can do something here.

**Comment by steadyk** [comment]
## Perform the following steps to reproduce the issue:

**1. Create realm via Keycloak UI or alternatively via realm-operator**

**Example for realm-operator:**

```yaml
apiVersion: legacy.k8s.keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: test-realm
  labels:
    app: test-realm
spec:
  instanceSelector:
    matchLabels:
      app: keycloak
  realm:
    displayName: test-realm
    enabled: true
    id: test-realm
    realm: test-realm
```

**2. Create client via Keycloak UI or alternatively via realm-operator**

**Example for realm-operator:**

```yaml
apiVersion: legacy.k8s.keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: test-client
spec:
  client:
    clientAuthenticatorType: client-secret
    clientId: test-client
    defaultClientScopes:
    - email
    - profile
    - roles
    directAccessGrantsEnabled: true
    implicitFlowEnabled: true
    name: test-client
    optionalClientScopes:
    - address
    - microprofile-jwt
    - offline_access
    - phone
    - web-origins
    protocol: openid-connect
    publicClient: true
    redirectUris:
    - https://localhost/*
    standardFlowEnabled: true
    webOrigins:
    - https://localhost
  realmSelector:
    matchLabels:
      app: test-realm
```

**3. Watch Keycloak client secret**

Feel free to use this script for that and replace the Keycloak endpoint, the namespace and the password if needed:

```bash
#!/bin/bash

keycloak="<keycloak-url>"
realm="test-realm"
clientId="test-client"
namespace="<namespace>"

password="$(kubectl -n master-security get secret credential-keycloak -o=jsonpath='{.data.ADMIN_PASSWORD}' | base64 -d)"

while :;do
	bearer=$(curl -s -X POST $keycloak/auth/realms/master/protocol/openid-connect/token \
		-H "content-type: application/x-www-form-urlencoded" \
		-d "username=admin" \
		--data-urlencode "password=$password" \
		-d "grant_type=password" \
		-d "client_id=admin-cli" | jq -r .access_token)

	if [ ! $id ];then
		id=$(curl -s -X GET $keycloak/auth/admin/realms/$realm/clients?clientId=$clientId \
			-H "content-type: application/json" \
			-H "authorization: bearer ${bearer}" | jq -r .[0].id)
	fi

	keycloakSecret="$(curl -s -X GET $keycloak/auth/admin/realms/$realm/clients/$id/client-secret \
		-H "content-type: application/json" \
		-H "authorization: bearer ${bearer}" | jq -r .value)"

	echo "$(date +%T): Secret: $keycloakSecret"

	sleep 5
done
```

**4. Add post logout redirect uris directly via API**

Feel free to use this script for that and replace the Keycloak endpoint, the namespace and the password if needed:

```bash
#!/bin/bash

keycloak="<keycloak-url>"
realm="test-realm"
clientId="test-client"
namespace="<namespace>"

password="$(kubectl -n $namespace get secret credential-keycloak -o=jsonpath='{.data.ADMIN_PASSWORD}' | base64 -d)"

while :;do
	bearer=$(curl -s -X POST $keycloak/auth/realms/master/protocol/openid-connect/token \
		-H "content-type: application/x-www-form-urlencoded" \
		-d "username=admin" \
		--data-urlencode "password=$password" \
		-d "grant_type=password" \
		-d "client_id=admin-cli" | jq -r .access_token)

	id=$(curl -s -X GET $keycloak/auth/admin/realms/$realm/clients?clientId=$clientId \
		-H "content-type: application/json" \
		-H "authorization: bearer ${bearer}" | jq -r .[0].id)

	echo "$(date +%T): Adding post.logout.redirect.uris"

	curl -s -X PUT $keycloak/auth/admin/realms/$realm/clients/$id \
		-H "content-type: application/json" \
		-H "authorization: bearer ${bearer}" \
		--data-raw '{"attributes":{"post.logout.redirect.uris":"https://localhost/*"}}'

	sleep 10
done
```

**Our observations**
* after creating the client, no secret is present since it is a public client (expected)
* after adding the post logout redirect uris we immediately see a client secret on Keycloak (not expected)
* if the realm-operator is used, the operator will remove the secret periodically on reconciliation
* manually removing the post logout redirect uris does not remove the client secret

**Expected behavior**
Keycloak does not create a client secret on a public client if  post logout redirect uris are added.
