### ISSUE TITLE
On the clients page,The "Home URL" of account-console and account is wrong, missing path /realms/xxx/account

### ISSUE THREAD

**Issue by potterhe** [keycloak/keycloak#31521]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Operation Path: admin console -> Clients -> Client list -> Home URL，shown as: http://localhost:8080 not http://localhost:8080/realms/xxx/account, miss "/realms/xxx/account"

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

account-console's Home URL is "http://localhost:8080/realms/xxx/account"

### Actual behavior

account-console's Home URL is "http://localhost:8080", miss "/realms/xxx/account"

### How to Reproduce?

```
version: '2'

services:
  mysql:
    image: mysql:8.1.0
    ports:
      - '13306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=keycloak
    volumes:
      - './mysql_data:/var/lib/mysql'
  keycloak:
    image: keycloak/keycloak:25.0.2
    command: ["start", "--features", "organization"]
    ports:
      - '8080:8080'
      - '9000:9000'
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_USERNAME=root
      - KC_DB_PASSWORD=example
      - KC_DB_URL=jdbc:mysql://mysql/keycloak
      - KC_METRICS_ENABLED=true
      - KC_HEALTH_ENABLED=true
    depends_on:
      - mysql
```

### Anything else?

na

**Comment by ssilvert** [comment]
This is working fine for me:

<img width="926" alt="ClientList" src="https://github.com/user-attachments/assets/7a2561ed-7cd5-45f8-89d0-fef5c0979482">

**Comment by iliuta** [comment]
I have the same problem, after migrating from 25.0.1 to 25.0.2, but also from 24 to 25.0.2.

**Comment by Loic-des-Rochettes** [comment]
Same here with 25.0.2 and h2 out of the box :

![image](https://github.com/user-attachments/assets/4fd37f03-7f6b-4dc9-a5ec-acc23f9eed5e)

```yaml
services:
  keycloak:
    image: "quay.io/keycloak/keycloak:25.0.2"
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ********
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME_STRICT: "false"
      DEBUG: "true"
      DEBUG_PORT: '*:8787'
    entrypoint: /bin/bash
    command: -c "/opt/keycloak/bin/kc.sh start"
    ports:
      - 8080:8080
      - "127.0.0.1:8787:8787"
    expose:
      - 8787
    volumes:
      - ./data/:/opt/keycloak/data/ # h2 database data dir
```
