### ISSUE TITLE
Discovery doesn't work with instances > 1 in IPv6 Kubernetes environment

### ISSUE THREAD

**Issue by zalejus** [keycloak/keycloak#32081]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

I deployed keycloak server using operator. When **instance** parameter is set as **1** everything works perfectly, but when I try to set more replicas by changing **instance: 2** I'm facing message in UI: "Network response was not OK."
I presume that problem might be because of wrongly discovered cluster but I don't have the faintest idea why it happen.
I'm not sure if it's bug. Below I attached my config. From my point of view it looks fine. I won't to use HA, I'd like to have simply 2-3 replicas. And after documentation I assume it is possible without configuring HA. Discovering seems working and addresses are correct. But they are not attached to the cluster.

```
$ bin/kc.sh show-config
Current Mode: production
Current Configuration:
	kc.cache =  ispn (ENV)
	kc.cache-stack =  kubernetes (ENV)
	kc.cache.stack =  kubernetes (ENV)
	kc.config.built =  true (SysPropConfigSource)
	kc.db =  postgres (ENV)
	kc.db-password =  ******* (ENV)
	kc.db-url-database =  keycloakdb (ENV)
	kc.db-url-host =  keycloakdb-primary (ENV)
	kc.db-username =  keycloakdb (ENV)
	kc.db.password =  ******** (ENV)
	kc.db.url.database =  keycloakdb (ENV)
	kc.db.url.host =  keycloakdb-primary (ENV)
	kc.db.username =  keycloakdb (ENV)
	kc.health-enabled =  true (ENV)
	kc.health.enabled =  true (ENV)
	kc.hostname-strict =  false (ENV)
	kc.hostname.strict =  false (ENV)
	kc.http-enabled =  true (ENV)
	kc.http-port =  8080 (ENV)
	kc.http.enabled =  true (ENV)
	kc.http.port =  8080 (ENV)
	kc.https-port =  8443 (ENV)
	kc.https.port =  8443 (ENV)
	kc.log-console-output =  default (classpath keycloak.conf)
	kc.log-level =  debug (ENV)
	kc.log.level =  debug (ENV)
	kc.proxy-headers =  xforwarded (ENV)
	kc.proxy.headers =  xforwarded (ENV)
	kc.run.in.container =  true (ENV)
	kc.spi-connections-infinispan-quarkus-stack =  kubernetes (ENV)
	kc.spi-hostname-v2-hostname-strict =  false (ENV)
	kc.spi.truststore.file.file =  /opt/ipa/cacert (ENV)
	kc.spi.truststore.file.hostname.verification.policy =  ANY (ENV)
	kc.spi.truststore.file.password =  ******** (ENV)
	kc.spi.truststore.file.type =  jks (ENV)
	kc.truststore-paths =  /var/run/secrets/kubernetes.io/serviceaccount/ca.crt (ENV)
	kc.truststore.paths =  /var/run/secrets/kubernetes.io/serviceaccount/ca.crt (ENV)
	kc.version =  25.0.2 (SysPropConfigSource)
```

A part of log session when cluster is discovered
```
2024-08-13 07:33:34,571 DEBUG [org.jgroups.protocols.dns.DNS_PING] (jgroups-6,keycloak-deployment-0-9226) keycloak-deployment-0-9226: entries collected from DNS (in 0 ms): [2a05:d014:d10:4524:2b01:0:0:f:0, 2a05:d014:d10:4528:6e29:0:0:13:0]
2024-08-13 07:33:34,571 DEBUG [org.jgroups.protocols.dns.DNS_PING] (jgroups-6,keycloak-deployment-0-9226) keycloak-deployment-0-9226: sending discovery requests to hosts [2a05:d014:d10:4524:2b01:0:0:f:0, 2a05:d014:d10:4528:6e29:0:0:13:0] on ports [7800 .. 7800]
2024-08-13 07:33:35,238 DEBUG [org.jgroups.protocols.dns.DNS_PING] (jgroups-6,keycloak-deployment-0-9226) keycloak-deployment-0-9226: entries collected from DNS (in 0 ms): [2a05:d014:d10:4524:2b01:0:0:f:0, 2a05:d014:d10:4528:6e29:0:0:13:0]
2024-08-13 07:33:35,238 DEBUG [org.jgroups.protocols.dns.DNS_PING] (jgroups-6,keycloak-deployment-0-9226) keycloak-deployment-0-9226: sending discovery requests to hosts [2a05:d014:d10:4524:2b01:0:0:f:0, 2a05:d014:d10:4528:6e29:0:0:13:0] on ports [7800 .. 7800]
2024-08-13 07:33:35,904 INFO  [org.jgroups.protocols.pbcast.GMS] (ForkJoinPool.commonPool-worker-1) keycloak-deployment-0-9226: no members discovered after 2002 ms: creating cluster as coordinator
```

### Version

25.0.2

### Regression

- [ ] The issue is a regression

### Expected behavior

It should work with 2 or more replicas

### Actual behavior

Keycloak doesn't work with 2 or more replicas

### How to Reproduce?

My keycloak definition
```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak-deployment
  namespace: keycloak
spec:
  instances: 2
  db:
    vendor: postgres
    host: keycloakdb-primary
    database: keycloakdb
    usernameSecret:
      name: keycloakdb-pguser-keycloakdb
      key: user
    passwordSecret:
      name: keycloakdb-pguser-keycloakdb
      key: password
  http:
    httpEnabled: true
    httpPort: 8080
  hostname:
    strict: false
  ingress:
    enabled: false
  additionalOptions:
    - name: log-level
      value: debug
    - name: proxy-headers
      value: xforwarded
    - name: spi-truststore-file-file
      value: "/opt/ipa/cacert"
    - name: spi-truststore-file-password
      value: "mypass"
    - name: spi-truststore-file-hostname-verification-policy
      value: ANY
    - name: spi-truststore-file-type
      value: jks
  unsupported:
    podTemplate:
      metadata:
        labels:
          name: keycloak-deployment
      spec:
        containers:
          - volumeMounts:
              - name: ipa-cacert
                mountPath: /opt/ipa
              - name: keytab
                mountPath: /opt/keytab
        volumes:
          - name: ipa-cacert
            secret:
              secretName: ipa-root-cacert
              items:
              - key: cacert
                path: cacert
          - name: keytab
            secret:
              secretName: keycloak-keytab
              items:
              - key: keytab
                path: keycloak.keytab
```
