### ISSUE TITLE
Clarify the behaviour of multiple Operator versions installed in the same cluster

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#32152]
### Description

* Document that all Operator versions use a single CRD API version. The CRD revisions between Operator versions don't introduce any breaking changes so they are backward compatible.
* OLM seems to keep the latest CRD revision regardless of in which order the Operator versions were installed. (This needs double checking.) Make sure to document this. Add a note for non-OLM installs that they should mimic this behaviour (installing latest CRD revision).
* Document that using a field introduced in a newer Operator version with and older Operator version is not supported and will lead to Operator failing on an unrecognized field.

**Comment by vmuzikar** [comment]
CC @keycloak/cloud-native

**Comment by shawkins** [comment]
> OLM seems to keep the latest CRD revision regardless of in which order the Operator versions were installed. (This needs double checking.) Make sure to document this. Add a note for non-OLM installs that they should mimic this behaviour (installing latest CRD revision).

It does not - the last one wins. The crd does keep the association with both versions:

```
  labels:
    olm.managed: 'true'
    operators.coreos.com/keycloak-operator.kc-new: ''
    operators.coreos.com/keycloak-operator.kc-old: ''
  annotations:
    operatorframework.io/installed-alongside-2ef0080d4f8fa2cc: kc-new/keycloak-operator.v25.0.6
    operatorframework.io/installed-alongside-7e5dde701a45cf8e: kc-old/keycloak-operator.v20.0.0
```

However this will only be possible if all of the existing resources are not yet using fields from the new CRD. It seems that OLM has functioned this way for some time: https://groups.google.com/g/operator-framework/c/aFr_hwxB43I - the reasoning then, and probably now, is that you should avoid this scenario if the CRDs change at all.
