### ISSUE TITLE
Endpoint configurations shows hostname_admin

### ISSUE THREAD

**Issue by kochen** [keycloak/keycloak#32205]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

We are using a dedicated hostname-admin URL.
The URL in the realm's endpoint configuration contains the admin url and not the frontend url.

This affects both:
- OpenID Endpoint Configuration 
- SAML 2.0 Identity Provider Metadata 

### Version

25.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

Frontend/Backend URL should be used to expose URLs and not the Administration URL.

### Actual behavior

The URL contains the admin url and not the frontend url.

#### Running keycloak `25.0.2`
```yaml
services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    command: ["start-dev"]
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_HOSTNAME: http://localhost:8081
      KC_HOSTNAME_ADMIN: http://localhost:8082
    ports:
      - 8081:8080
      - 8082:8080
```
- browse to `http://localhost:8082` <- the admin console URL
- Go to `Realm settings` (bottom left main menu)
- Observe the Endpoint URL (bottom of the page):
(shows the **admin** hostname)

### Anything else?

Related (regression?): https://github.com/keycloak/keycloak/issues/31244
