### ISSUE TITLE
Client Home URLs showing base domain only

### ISSUE THREAD

**Issue by kochen** [keycloak/keycloak#32336]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

Home URLs shown in the various clients, do not contain relative paths, but only the base hostname.

### Version

25.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

Home URLs should be full with relevant paths

### Actual behavior

Home URLs shown in the various clients, do not contain relative paths, but only the base hostname.

Tested to be broken in `25.0.2`, `25.0.3`, `25.0.4`

### How to Reproduce?

Running Keycloak `25.0.2`:
```
---
services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.2
    command: ["start-dev"]
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - 8081:8080
```

browse to http://localhost:8081 <- the admin console URL
Go to Clients (left main menu)
Observe the Home URLs (left column):
![image](https://github.com/user-attachments/assets/27204bc6-c85a-4899-a120-4b091dae5455)

### Anything else?

related: #32205 

Works as expected in `25.0.0`, `25.0.1`
