### ISSUE TITLE
KeycloakRealmImport not working with Istio service mesh

### ISSUE THREAD

**Issue by joshuacuellar1** [keycloak/keycloak#32368]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

I am installing Keycloak with the Operator in a namespace that has Istio sidecar injection enabled.
When I create a KeycloakRealmImport, the pod gets stuck in a NotReady state.

### Version

25.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

The realm should be imported into the Keycloak server.

### Actual behavior

The pod is stuck in a NotReady state.

```
$ kubectl get pods -A
NAMESPACE      NAME                                    READY   STATUS     RESTARTS        AGE
istio-system   istio-ingressgateway-75fcb94949-9pmw5   1/1     Running    0               3m48s
istio-system   istiod-5f7944b777-t7wc4                 1/1     Running    0               3m55s
keycloak       example-count0-kc-lvbqt                 1/2     NotReady   0               2m7s
keycloak       example-kc-0                            2/2     Running    0               2m47s
keycloak       keycloak-operator-54bcb5c9f7-bdhjs      2/2     Running    0               3m6s
kube-system    coredns-7db6d8ff4d-f9j5t                1/1     Running    0               3m55s
kube-system    etcd-minikube                           1/1     Running    0               4m9s
kube-system    kube-apiserver-minikube                 1/1     Running    0               4m9s
kube-system    kube-controller-manager-minikube        1/1     Running    0               4m10s
kube-system    kube-proxy-vfcgm                        1/1     Running    0               3m55s
kube-system    kube-scheduler-minikube                 1/1     Running    0               4m9s
kube-system    storage-provisioner                     1/1     Running    1 (3m24s ago)   4m8s
postgresql     postgresql-db-0                         2/2     Running    0               3m6s
```

### How to Reproduce?

```
#!/bin/bash


# Delete old minikube clusters
minikube delete --all

# Start minikube
minikube start --cpus=2 --memory 2g

# Download and install Istio
curl -L https://istio.io/downloadIstio | sh -
./istio-1.23.0/bin/istioctl install -y

# Create Keycloak namespace and enable Istio injection
kubectl create namespace keycloak
kubectl label namespace keycloak istio-injection=enabled

# Install Keycloak CRDs
kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/25.0.4/kubernetes/keycloaks.k8s.keycloak.org-v1.yml -n keycloak
kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/25.0.4/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml -n keycloak
kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/25.0.4/kubernetes/kubernetes.yml -n keycloak

# Install PostgreSQL
kubectl create namespace postgresql
kubectl label namespace postgresql istio-injection=enabled
kubectl apply -f - << EOF
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql-db
  namespace: postgresql
spec:
  serviceName: postgresql-db-service
  selector:
    matchLabels:
      app: postgresql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      containers:
        - name: postgresql-db
          image: postgres:16
          volumeMounts:
            - mountPath: /data
              name: cache-volume
          env:
            - name: POSTGRES_USER
              value: keycloak
            - name: POSTGRES_PASSWORD
              value: keycloak
            - name: PGDATA
              value: /data/pgdata
            - name: POSTGRES_DB
              value: keycloak
      volumes:
        - name: cache-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: postgresql
spec:
  selector:
    app: postgresql-db
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
EOF

# Create PostgreSQL secret for Keycloak
kubectl create secret generic keycloak-db-secret -n keycloak \
  --from-literal=username=keycloak \
  --from-literal=password=keycloak

# Create Keycloak instance
kubectl apply -f - << EOF
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
  namespace: keycloak
  labels:
    app: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    host: postgres-db.postgresql.svc
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
  http:
    httpEnabled: true
  hostname:
    strict: false
  proxy:
    headers: xforwarded
  ingress:
      enabled: false
EOF

# Deploy sample realm
kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak/main/operator/src/test/resources/example-realm.yaml -n keycloak

```
