### ISSUE TITLE
We cannot use dynamic hostname with ingress and keycloak 

### ISSUE THREAD

**Issue by luisfagottani** [keycloak/keycloak#32360]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

We tried to configure our keycloak with ingress, but when we set the hostname to a dynamic path with ‘*’, the front-end resources don't load.

We've tried several different configurations but this crashes the admin console.

We have tried to use hostname-debug but only returns failed. 
![360658048-936fa9b5-5227-4239-9234-63ccf7278288](https://github.com/user-attachments/assets/c01ab9df-4fde-45c7-b8e3-59c611d52612)

Ingress config
![image](https://github.com/user-attachments/assets/96f6c2ef-bc49-43cf-bcf8-ce1b6e332a06)

### Version

24.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

We can access admin console with another path `/admin` as example.

### Actual behavior

We can't load the resources when we try to access the console via a browser and, consequently, we can't authenticate the applications.

![360659106-828eebfc-cd09-43eb-afc6-d81d9e4bf729](https://github.com/user-attachments/assets/df27dc34-8379-49da-aaaa-d97f9baf8c70)

### How to Reproduce?

![image](https://github.com/user-attachments/assets/ecc16688-d79b-4d67-95dd-417098f883e8)

**Comment by brunopadz** [comment]
Hi, checking in the issue since @luisfagottani is a co-worker of mine.
I've just opened an [issue](https://github.com/bitnami/charts/issues/29091) on bitnami helm charts repo to report the same issue. 

We're using AWS LB Controller to control our ingresses, the configuration we're using on the ingresses are:

```yaml
extraEnvVars:
  - name: KC_HOSTNAME_URL
    value: "https://keycloak.external.dns"
  - name: KC_ADMIN_HOSTNAME_URL
    value: "https://adminkc.internal.dns"

adminIngress:
  enabled: true
  ingressClassName: "alb-internal"
  hostname: "adminkc.internal.dns"
  pathType: ImplementationSpecific
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/backend-protocol: "HTTP"
    alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-FS-1-2-Res-2019-08"
    alb.ingress.kubernetes.io/healthcheck-protocol: "HTTP"
    alb.ingress.kubernetes.io/healthcheck-path: "/"
ingress:
  enabled: true
  ingressClassName: "alb-external"
  hostname: "keycloak.external.dns"
  path: "/*"
  pathType: ImplementationSpecific
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: auth
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/backend-protocol: "HTTP"
    alb.ingress.kubernetes.io/ssl-policy: "ELBSecurityPolicy-FS-1-2-Res-2019-08"
    alb.ingress.kubernetes.io/healthcheck-protocol: "HTTP"
    alb.ingress.kubernetes.io/healthcheck-path: "/"
    alb.ingress.kubernetes.io/load-balancer-attributes: routing.http.preserve_host_header.enabled=true,routing.http.xff_header_processing.mode=preserve
    alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=false,stickiness.lb_cookie.duration_seconds=300
    alb.ingress.kubernetes.io/wafv2-acl-arn: "arn:aws:wafv2:us-east-1:xxx:regional/webacl/xxx/xxx"
```

Basically, when I try to access the admin panel through an internal URL, Keycloak returns a 404 error. When I configure the ingress to allow all traffic to an external ingress, it works correctly.

Let us know if you need any additional info or clarify something else.
