### ISSUE TITLE
Keycloak loses updates in distributed Infinispan using 2 Keycloak instances

### ISSUE THREAD

**Issue by kermakovich** [keycloak/keycloak#32613]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

I'm running 2 Keycloak instances 25.0.4 and 1 node Infinispan 15.0.7.Final.

Around 30% of registration attempts are failed. The reason is page expired. With debug log I see the following:
```
2024-08-23 08:45:59,374 DEBUG [org.keycloak.authentication.AuthenticationProcessor] (executor-thread-54) authenticationAction
2024-08-23 08:45:59,374 DEBUG [org.keycloak.authentication.AuthenticationProcessor] (executor-thread-54) Current execution does not equal executed execution.  Might be a page refresh
2024-08-23 08:45:59,374 DEBUG [org.keycloak.services.util.AuthenticationFlowURLHelper] (executor-thread-54) Redirecting to 'page expired' now. Will use last step URL: https://host/realms/realm-1/login-actions/authenticate?execution=22242793-471b-4463-9854-15dc9ec40055&client_id=client-0&tab_id=0E_VrpkefAg
```
 I checked it with Keycloak Benchmark test.
Here is report:
![image](https://github.com/user-attachments/assets/50405453-19c5-4639-a65d-f454c40e6a99)

I also can reproduce it manually going through ngnix. I noticed that steps must be following:
1. Go to login page (handle Keycloak-1)
2. Press register button (handle Keycloak-2)
3. Enter information.
4. press register button (handle Keycloak-1)

During 4 step I saw that Kecyloak-1 received authenticationSession not current (that Keycloak-2 put), but previous from Keycloak-1(step 1). And executions are not equal, which is logical

Configuration for infinispan:
```xml
<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:15.0 https://infinispan.org/schemas/infinispan-config-15.0.xsd
                        urn:infinispan:server:15.0 https://infinispan.org/schemas/infinispan-server-15.0.xsd"
        xmlns="urn:infinispan:config:15.0"
        xmlns:server="urn:infinispan:server:15.0">

    <cache-container name="remoteKeycloak" statistics="true">
        <transport cluster="${infinispan.cluster.name:ISPN}"
                   stack="${infinispan.cluster.stack:udp}" node-name="${infinispan.node.name:mainNode}"
                   site="sit1" />

        <security>
            <authorization />
        </security>

        <serialization marshaller="org.infinispan.jboss.marshalling.commons.GenericJBossMarshaller">
            <allow-list>
                <class>org.*</class>
                <regex>.*</regex>
            </allow-list>
        </serialization>

        <replicated-cache name="work">
            <encoding media-type="application/x-jboss-marshalling" />
        </replicated-cache>


        <distributed-cache name="sessions">
            <encoding media-type="application/x-jboss-marshalling" />
        </distributed-cache>

        <distributed-cache name="authenticationSessions">
            <encoding media-type="application/x-jboss-marshalling" />
        </distributed-cache>

        <distributed-cache name="clientSessions">
            <encoding media-type="application/x-jboss-marshalling" />
        </distributed-cache>

        <distributed-cache name="offlineSessions">
            <encoding media-type="application/x-jboss-marshalling" />
        </distributed-cache>

        <distributed-cache name="offlineClientSessions">
            <encoding media-type="application/x-jboss-marshalling" />
        </distributed-cache>

        <distributed-cache name="actionTokens">
            <encoding media-type="application/x-jboss-marshalling" />
        </distributed-cache>

        <distributed-cache name="loginFailures">
            <encoding media-type="application/x-jboss-marshalling" />
        </distributed-cache>
    </cache-container>

    <server xmlns="urn:infinispan:server:15.0">
        <interfaces>
            <interface name="public">
                <inet-address value="${infinispan.bind.address:127.0.0.1}" />
            </interface>
        </interfaces>

        <socket-bindings default-interface="public"
                         port-offset="${infinispan.socket.binding.port-offset:0}">
            <socket-binding name="default"
                            port="${infinispan.bind.port:11222}" />
            <socket-binding name="memcached"
                            port="11221" />
        </socket-bindings>

        <security>
            <credential-stores>
                <credential-store name="credentials" path="credentials.pfx">
                    <clear-text-credential clear-text="secret" />
                </credential-store>
            </credential-stores>
            <security-realms>
                <security-realm name="default">
                    <properties-realm groups-attribute="Roles">
                        <user-properties path="users.properties" />
                        <group-properties path="groups.properties" />
                    </properties-realm>
                </security-realm>
            </security-realms>
        </security>

        <endpoints socket-binding="default" security-realm="default">
            <endpoint>
                <hotrod-connector name="hotrod">
                    <authentication >
<!--                        <sasl mechanisms="SCRAM_SHA_512"-->
<!--                              server-name="infinispan" />-->
                    </authentication>
                </hotrod-connector>
                <rest-connector name="rest" >
                    <authentication mechanisms="BASIC">
                    </authentication>
                </rest-connector>
            </endpoint>
        </endpoints>
    </server>
</infinispan> 
```

Keycloak config:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<infinispan
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="urn:infinispan:config:15.0 http://www.infinispan.org/schemas/infinispan-config-15.0.xsd"
        xmlns="urn:infinispan:config:15.0">
    <jgroups>
        <stack name="ping-tcp" extends="tcp">
            <TCP bind_port="7800"/>
            <TCPPING
                    initial_hosts="infinispan[7800],keycloak[7800]"
                    port_range="0"
                    stack.combine="REPLACE"
                    stack.position="MPING"
            />
        </stack>
    </jgroups>
    <cache-container name="keycloak">
        <transport cluster="${infinispan.cluster.name:ISPN}" lock-timeout="60000" stack="ping-tcp" />
        <local-cache name="realms">
            <encoding>
                <key media-type="application/x-java-object" />
                <value media-type="application/x-java-object" />
            </encoding>
            <memory max-count="10000" />
        </local-cache>
        <local-cache name="users">
            <encoding>
                <key media-type="application/x-java-object" />
                <value media-type="application/x-java-object" />
            </encoding>
            <memory max-count="10000" />
        </local-cache>
        <local-cache name="authorization">
            <encoding>
                <key media-type="application/x-java-object" />
                <value media-type="application/x-java-object" />
            </encoding>
            <memory max-count="10000" />
        </local-cache>
        <local-cache name="keys">
            <encoding>
                <key media-type="application/x-java-object" />
                <value media-type="application/x-java-object" />
            </encoding>
            <expiration max-idle="3600000" />
            <memory max-count="1000" />
        </local-cache>
        <distributed-cache name="sessions" owners="1">
            <persistence passivation="false">
            </persistence>
        </distributed-cache>
        <distributed-cache name="authenticationSessions" owners="1">
            <persistence passivation="false">
            </persistence>
        </distributed-cache>
        <distributed-cache name="offlineSessions" owners="1">
            <persistence passivation="false">
            </persistence>
        </distributed-cache>
        <distributed-cache name="clientSessions" owners="1">
            <persistence passivation="false">
            </persistence>
        </distributed-cache>
        <distributed-cache name="offlineClientSessions" owners="1">
            <persistence passivation="false">
            </persistence>
        </distributed-cache>
        <distributed-cache name="loginFailures" owners="1">
            <persistence passivation="false">
            </persistence>
        </distributed-cache>
        <distributed-cache name="actionTokens" owners="1">
            <expiration max-idle="-1" interval="300000" />
            <persistence passivation="false">
            </persistence>
        </distributed-cache>
        <replicated-cache name="work">
            <persistence passivation="false">
            </persistence>
        </replicated-cache>
    </cache-container>
</infinispan>
```

dockerfile infinispan:
```
FROM quay.io/infinispan/server:15.0

USER root

ENV KEYCLOAK_VERSION=25.0.4

RUN cd /opt/infinispan/server/lib && \
 	curl -O https://repo1.maven.org/maven2/org/keycloak/keycloak-model-infinispan/${KEYCLOAK_VERSION}/keycloak-model-infinispan-${KEYCLOAK_VERSION}.jar && \
 	curl -O https://repo1.maven.org/maven2/org/keycloak/keycloak-server-spi/${KEYCLOAK_VERSION}/keycloak-server-spi-${KEYCLOAK_VERSION}.jar && \
 	curl -O https://repo1.maven.org/maven2/org/keycloak/keycloak-server-spi-private/${KEYCLOAK_VERSION}/keycloak-server-spi-private-${KEYCLOAK_VERSION}.jar && \
 	curl -O https://repo1.maven.org/maven2/org/keycloak/keycloak-core/${KEYCLOAK_VERSION}/keycloak-core-${KEYCLOAK_VERSION}.jar && \
 	cd -

COPY postgresql-42.7.2.jar /opt/infinispan/server/lib/

RUN getent group 185 || groupadd -g 185 infinispan && \
    id -u 185 || useradd -r -u 185 -g 185 -s /sbin/nologin infinispan

RUN mkdir -p /opt/infinispan/server/data && chmod -R g+w /opt/infinispan/server/data

USER 185:185

EXPOSE 11221 11222 11223 2157 46655 57600 7800 7900

ENTRYPOINT ["./bin/launch.sh"]
```
.env:
```
KC_HTTP_ENABLED=true
KC_PROXY=edge
#ENV KC_HOSTNAME=
KC_HOSTNAME_STRICT=false

#admin credentials
KEYCLOAK_ADMIN_PASSWORD=admin
KEYCLOAK_ADMIN=admin

KC_CACHE=ispn
KC_CACHE_REMOTE_HOST=infinispan
KC_CACHE_REMOTE_PASSWORD=admin
KC_CACHE_REMOTE_PORT=11222
KC_CACHE_REMOTE_USERNAME=admin
KC_CACHE_REMOTE_TLS_ENABLED=false
KC_DB_POOL_MAX_SIZE=45
```

docker-compose
```yaml
services:
  web_1:
    privileged: true # podman related
    user: root #podman related
    image: quay.io/keycloak/keycloak:25.0.4
    command: start-dev --cache-config-file=cache-ispn-remote.xml --proxy-headers forwarded --spi-connections-infinispan-quarkus-site-name="sit1" --log-level="INFO,org.keycloak.authentication:debug,org.infinispan.cache.impl:trace,org.infinispan:debug,org.keycloak.models:trace,org.keycloak.models.cache:debug,org.keycloak.cluster.infinispan:trace,org.keycloak.services.scheduled:info" # I used start-dev as I don't want to deal with TLS
    ports: # to be able to access admin console from my host
      - "8080:8080"
    volumes:
      - ./cache-ispn-remote.xml:/opt/keycloak/conf/cache-ispn-remote.xml
    env_file:
      - ./.env
#    deploy:
#      replicas: 2
    links:
      - postgres:postgres
      - infinispan:infinispan
    networks:
      - keycloak
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - web_1
      - web_2
    networks:
      - keycloak
  web_2:
    privileged: true # podman related
    user: root #podman related
    image: quay.io/keycloak/keycloak:25.0.4
    command: start-dev --cache-config-file=cache-ispn-remote.xml --proxy-headers forwarded --spi-connections-infinispan-quarkus-site-name="sit1" --log-level="INFO,org.keycloak.authentication:debug,org.infinispan:debug,org.infinispan.cache.impl:trace,org.keycloak.models:trace,org.keycloak.models.cache:debug,org.keycloak.cluster.infinispan:trace,org.keycloak.services.scheduled:info" # I used start-dev as I don't want to deal with TLS
    ports: # to be able to access admin console from my host
      - "8081:8080"
    volumes:
      - ./cache-ispn-remote.xml:/opt/keycloak/conf/cache-ispn-remote.xml
    env_file:
      - ./.env
    links:
      - postgres:postgres
      - infinispan:infinispan
    networks:
      - keycloak

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak
      POSTGRES_PASSWORD: keycloak-password
    ports:
      - "5678:5432"
    networks:
      - keycloak

  infinispan:
    privileged: true # podman related
    user: root # podman related
    image: infinispan:15.0
    build:
      context: .
      dockerfile: Dockerfile.infinispan
    volumes:
      - ./infinispan.xml:/opt/infinispan/server/conf/infinispan.xml
    command:
      - --cluster-name=ISPN -Dlog4j2.debug=true -Dorg.infinispan.SERVER=DEBUG
    ports:
      - 9122:11222 # changed port
    environment:
      USER: admin
      PASS: admin
    links:
      - postgres:postgres
    networks:
      - keycloak
networks:
  keycloak:
```

ngnix config
```
upstream backend {
#  hash $cookie_AUTH_SESSION_ID consistent;
    server web_1:8080;
    server web_2:8080;
}

server {
    listen 80;

    resolver 127.0.0.11 valid=5s;
    
    include /etc/nginx/mime.types;
    default_type  text/html;

    location / {
        proxy_pass http://backend/;
        proxy_set_header    Host               $host;
        proxy_set_header    X-Real-IP          $remote_addr;
        proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Host   $host;
        proxy_set_header    X-Forwarded-Server $host;
        proxy_set_header    X-Forwarded-Port   $server_port;
        proxy_set_header    X-Forwarded-Proto  $scheme;
     }
}
```

### Version

25.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

All registrations must be successful.

### Actual behavior

Around 30% registrations are failed.

### How to Reproduce?

Run docker-compose.yml

Reproduce it manually going through ngnix (not each time, only if requests goes as described below). Steps:
1. Go to login page (handle Keycloak-1)
2. Press register button (handle Keycloak-2)
3. Enter information.
4. press register button (handle Keycloak-1)

### Anything else?

maybe I missed smth in configuration..
