### ISSUE TITLE
Database index creation isn’t skipped on large data sets in Keycloak 24

### ISSUE THREAD

**Issue by dbubenheim** [keycloak/keycloak#32860]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

docs

### Describe the bug

Hi everyone, 

we’re working on the migration from Keycloak 23.0.7 to 24.0.5, and we have a question about a specific change that is mentioned in the migration guide. 

The migration guide says: 

> This change adds new indexes on the tables USER_ATTRIBUTE and FED_USER_ATTRIBUTE. If those tables contain more than 300000 entries, Keycloak will skip the index creation by default during the automatic schema migration and instead log the SQL statement on the console during migration to be applied manually after Keycloak’s startup. See the [Upgrading Guide](https://www.keycloak.org/docs/25.0.5/upgrading/) for details on how to configure a different limit. 

source: https://www.keycloak.org/docs/latest/upgrading/#user-attribute-value-length-extension 

In our use case the `fed_user_attribute` table contains way more than 300000 entries. But it doesn’t skip the index creation. 
 
We’ve noticed that Keycloak uses the ` QuarkusLiquibaseConnectionProvider`  instead of the `DefaultLiquibaseConnectionProvider` which actually contains and configures the `indexCreationThreshold` with a default value of `300000`.  Moreover we’ve seen that the `QuarkusLiquibaseConnectionProvider` lives in a legacy package and we’re not sure if that class should be used at all. 

We’ve started a default Keycloak image with 24.0.5 and noticed that the index got created every time, no matter how many entries exist in the db table. That’s because the parameter mentioned above is not being initialized properly. 

What is the desired behavior regarding the Liquibase initialization process? 
Which provider implementation should be used? 
And how does that fit to the documentation? 
Do we miss anything? 

### Version

24.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

The index creation should be skipped and an sql statement should be printed to the console.

### Actual behavior

the indexes are created automatically no matter how many entries are in the database table

<img width="1419" alt="startup-screen" src="https://github.com/user-attachments/assets/4a835943-f44b-4b88-a423-b561dfcd2bf0">

### How to Reproduce?

- run the `docker-compose.yml` file with keycloak version 23.0.7
- import data to the `fed_user_attribute` table and make sure to persist the data to a volume
- run the `docker-compose.yml` file with keycloak version 24.0.5

```yaml
services:

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - local

  keycloak:
    # image: quay.io/keycloak/keycloak:23.0.7
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: keycloak
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start", "--db", "postgres"]
    environment:
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
      KC_DB_URL_HOST: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
    ports:
      - "8080:8080"
    networks:
      - local
    depends_on:
      - postgres

networks:
  local:
    name: local
    driver: bridge
```
