### ISSUE TITLE
ERROR when run in docker

### ISSUE THREAD

**Issue by rosenante-aimee** [keycloak/keycloak#33038]
### Description

Hi!
I have trouble when open like that 
![image](https://github.com/user-attachments/assets/3652bb8d-364d-4e68-8d28-b5e7be974a0f)

After that, I check the container log, it has this error. Have you any ideal to fix this case

```
keycloakdb      | 2024-09-18 04:03:22.418 UTC [67] ERROR:  relation "migration_model" does not exist at character 25
keycloakdb      | 2024-09-18 04:03:22.418 UTC [67] STATEMENT:  SELECT ID, VERSION FROM MIGRATION_MODEL ORDER BY UPDATE_TIME DESC
keycloakdb      | 2024-09-18 04:03:23.159 UTC [67] ERROR:  relation "public.databasechangelog" does not exist at character 22
keycloakdb      | 2024-09-18 04:03:23.159 UTC [67] STATEMENT:  SELECT COUNT(*) FROM public.databasechangelog
keycloakdb      | 2024-09-18 04:03:23.428 UTC [68] ERROR:  relation "public.databasechangeloglock" does not exist at character 22
keycloakdb      | 2024-09-18 04:03:23.428 UTC [68] STATEMENT:  SELECT COUNT(*) FROM public.databasechangeloglock
keycloakdb      | 2024-09-18 04:03:23.464 UTC [67] ERROR:  relation "public.databasechangelog" does not exist at character 22
keycloakdb      | 2024-09-18 04:03:23.464 UTC [67] STATEMENT:  SELECT COUNT(*) FROM public.databasechangelog

```

**Comment by rosenante-aimee** [comment]
this is my docker compose

```
version: '3.8'

services:
  keycloak_web:
    image: quay.io/keycloak/keycloak:25.0.5
    container_name: keycloak_web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: "keycloak"
      KC_DB_PASSWORD: ""
      KC_HOSTNAME: ,..
      KC_LOG_LEVEL: info
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: ""
      KC_HTTP_ENABLED: "true"  
      KC_HTTPS_ENABLED: "false"  
    command: ["start"]
    depends_on:
      - keycloakdb
    ports:
      - 8443:8080 

  keycloakdb:
    image: postgres:15
    container_name: keycloakdb
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ""
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
```
