### ISSUE TITLE
Cookie_not_found error in IdP SAML

### ISSUE THREAD

**Issue by mohsin-wsd** [keycloak/keycloak#34295]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

saml

### Describe the bug

In Keycloak 26.0.1
I setup auth0.com as identity provider and set allowable callback and logout URLs, enabled SAML 2.0 with role mapping then download the metadata and import into keycloak as SAML Identity Provider. 

I found Cookie_not_found error, even all applications (my application, keycloak, auth0) are running over https.

Same setup is working fine in 25.0.3. And OIDC (26.0.1) working fine with auth0.com

### Version

26.0.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Successfully login using auth0.com act as a Identity Provider using SAML

### Actual behavior

Got Exception: Cookie_not_found

### How to Reproduce?

Docker Compose
````
services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    networks:
      - local-keycloak

  keycloak:
    # see all the defaults in https://hub.docker.com/r/bitnami/keycloak
    depends_on:
      - postgres
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      KC_FEATURES: organization
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: HelloWorld
      KEYCLOAK_DATABASE_USER: keycloak
      KEYCLOAK_DATABASE_PASSWORD: keycloak
      KEYCLOAK_DATABASE_NAME: keycloak
    image: bitnami/keycloak:26
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - local-keycloak

networks:
  local-keycloak:
````

1. Add Identity Provider (SAML 2.0)
2. Import Metadata that is generated from auth0.com
