### ISSUE TITLE
redirect loop when accessing account management console

### ISSUE THREAD

**Issue by Degoya-Studio** [keycloak/keycloak#34292]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

account/ui

### Describe the bug

I'm trying to run KeyCloak on Digital Ocean App Platform and everything works so far, except for the account console. When I try to open it for a none master realm, it ends up in an infinite redirect loop. I've tried a lot of things out but to not avail.

**Digital Ocean App Spec**

```
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
domains:
  - domain: auth.domain.dzg.de
    type: PRIMARY
    zone: dzg.de
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: dzg-auth-keycloak
      match:
        path:
          prefix: /
name: dzg-domain-keycloak-server
region: fra
services:
  - dockerfile_path: Dockerfile
    envs:
      - key: KC_DB_URL
        scope: RUN_AND_BUILD_TIME
        value: jdbc:postgresql://dzg-domain-db-cluster-postgresql-do-user-17085909-0.i.db.ondigitalocean.com:25060/keycloak
      - key: KC_DB_USERNAME
        scope: RUN_AND_BUILD_TIME
        value: doadmin
      - key: KC_DB_PASSWORD
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:KgX0LcruXm/Gu7DVca62/55uXMklwToK:c+XSu0GiEhA33zWHZ8gKYfSqtPHAiPfILdI9fisAbfX6zdQ9nQsFOw==]
      - key: KEYCLOAK_ADMIN
        scope: RUN_AND_BUILD_TIME
        value: admin
      - key: KEYCLOAK_ADMIN_PASSWORD
        scope: RUN_AND_BUILD_TIME
        value: password
      - key: KC_HOSTNAME
        scope: RUN_AND_BUILD_TIME
        value: auth.domain.dzg.de
      - key: KC_SPI_EVENTS_LISTENER_EVENT_LISTENER_API_URL
        scope: RUN_AND_BUILD_TIME
        value: https://api.domain.dzg.de/api/v1
      - key: KC_SPI_EVENTS_LISTENER_EVENT_LISTENER_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: EV[1:v7DRsuEk9O2sQ3L8Yrcd6ymDR9J9uQ0D:RQ7lgyPa3+FjtzECLIcXZWF51/trTOxxmT6AVCTFnBfVDO0=]
      - key: KC_PROXY
        scope: RUN_AND_BUILD_TIME
        value: edge
      - key: KC_PROXY_ADDRESS_FORWARDING
        scope: RUN_AND_BUILD_TIME
        value: "true"
      - key: KC_PROXY_HEADERS
        scope: RUN_AND_BUILD_TIME
        value: xforwarded
      - key: KC_HOSTNAME_STRICT
        scope: RUN_AND_BUILD_TIME
        value: "false"
      - key: KC_HTTP_ENABLED
        scope: RUN_AND_BUILD_TIME
        value: "false"
      - key: KC_HOSTNAME_STRICT_HTTPS
        scope: RUN_AND_BUILD_TIME
        value: "false"
      - key: KC_SPI_COOKIE_DEFAULT_SECURE
        scope: RUN_AND_BUILD_TIME
        value: "false"
      - key: KC_SPI_COOKIE_DEFAULT_SAME_SITE
        scope: RUN_AND_BUILD_TIME
        value: "false"
      - key: KC_HTTP_RELATIVE_PATH
        scope: RUN_AND_BUILD_TIME
        value: /
      - key: KC_HOSTNAME_DEBUG
        scope: RUN_AND_BUILD_TIME
        value: "true"
      - key: KC_HOSTNAME_BACKCHANNEL_DYNAMIC
        scope: RUN_AND_BUILD_TIME
        value: "false"
    github:
      branch: main
      deploy_on_push: true
      repo: Degoya-Studio/dzg-auth-keycloak
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    name: dzg-auth-keycloak
    source_dir: /
```

**Keycloak Export files**

[account.json](https://github.com/user-attachments/files/17505355/account.json)
[realm-export.json](https://github.com/user-attachments/files/17505447/realm-export.json)

**Screenshots**

<img width="1785" alt="Bildschirmfoto 2024-10-24 um 11 54 27" src="https://github.com/user-attachments/assets/ddbfe55d-78e8-436d-b8fc-0f96eaee7970">
<img width="1761" alt="Bildschirmfoto 2024-10-24 um 11 54 47" src="https://github.com/user-attachments/assets/34c85e69-39f3-4ec4-821d-09680d1e6ad2">
<img width="645" alt="Bildschirmfoto 2024-10-24 um 12 02 49" src="https://github.com/user-attachments/assets/9bd506d4-e693-43f9-9b12-93ac9abb6d15">

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Access the Account Management Console.

### Actual behavior

redirect loop when accessing the Account Management Console for a non master realm

### How to Reproduce?

Run Keycloak on Digital Ocean App Platform and open https://<url>/realms/<none-master>/account

### Anything else?

_dzg is not the actual name of the domain. It's just a realm name_

https://github.com/keycloak/keycloak/issues/33109
