### ISSUE TITLE
Memory leak with v26.0.2 ?

### ISSUE THREAD

**Issue by mloiseleur** [keycloak/keycloak#34397]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

core

### Describe the bug

Memory usage on keycloak is usually quite stable, we configured it with:

```yaml
            - name: JAVA_OPTS_APPEND
              value: -server -Xms196m -Xmx256m
[...]
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 640Mi
```

We upgraded our keycloak instance on our kubernetes cluster to v26.0.2 last friday. No other change, just update image from `quay.io/keycloak/keycloak:26.0.1` to `quay.io/keycloak/keycloak:26.0.2`.

Since then, memory usage increase with a regular pace, without stopping:

![image](https://github.com/user-attachments/assets/87224e46-2612-442d-b676-ed92d48adfe4)

### Version

26.0.2

### Regression

- [X] The issue is a regression

### Expected behavior

Memory usage should be stable.

### Actual behavior

Memory usage increase without stop

### How to Reproduce?

Just replace image tag with latest version

### Anything else?

No info in the logs about any error.

**Comment by mabartos** [comment]
@ahus1 @mhajas Hi guys! In the KC benchmark, you have some continuous Keycloak monitoring related to memory and other metrics per day, right? 

Did you encounter any difference since 26.0.2 was released?

**Comment by ahus1** [comment]
We run tests on nightly, but not with such small memory usage, so we wouldn't notice a change there. 

I would recommend to look into the JVM metrics to see the what kind of memory area increased. See https://www.keycloak.org/keycloak-benchmark/kubernetes-guide/latest/running/metrics/jvm_metrics for the usual metrics jvm_memory_committed_bytes and jvm_memory_used_bytes 

 It would be good to know the Keycloak feature and options that are enabled in this environment.

**Comment by mabartos** [comment]
@ahus1 Thanks.

@mloiseleur Could you please provide more information about your deployment to know more about potential issues?

**Comment by mloiseleur** [comment]
@mabartos 

<details>

<summary>Here is the complete statefulset</summary>

```yaml
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
  serviceName: keycloak
  template:
    metadata:
      labels:
        app: keycloak
        app.kubernetes.io/name: keycloak
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: auth-registries
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.0.5
          args:
            - start
            - --cache=local
            - --health-enabled=true
            - --hostname=XXXX
            - --hostname-backchannel-dynamic=false
            - --http-enabled=true
            - --metrics-enabled=true
            - --proxy-headers=xforwarded
          env:
            - name: JAVA_OPTS_APPEND
              value: -server -Xms196m -Xmx256m
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: admin_password
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9000
              name: mgmt
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 640Mi
          volumeMounts:
            - mountPath: /opt/keycloak/data
              name: keycloak-data
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - NET_RAW
          livenessProbe:
            httpGet:
              port: mgmt
              path: /health/live
            initialDelaySeconds: 150
          readinessProbe:
            httpGet:
              port: mgmt
              path: /health/ready
            initialDelaySeconds: 150
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
  volumeClaimTemplates:
    - metadata:
        name: keycloak-data
      spec:
        resources:
          requests:
            storage: 1Gi
        accessModes:
          - ReadWriteOnce
        storageClassName: "XXXX"
  updateStrategy:
    type: RollingUpdate
```

</details>


With latest v26.0.5 version and metrics enabled, here are the graphs on committed bytes:

![image](https://github.com/user-attachments/assets/fa1d559f-3c3b-40fe-aa78-8b29a4268384)

and memory used:

![image](https://github.com/user-attachments/assets/f420cb5c-1186-446e-a64c-52ec9ac6f506)

On committed bytes, it increase slowly but surely: from 34,0 MB to 35,5 MB.
Same for jvm memory on "non-heap" profiled nmethods:
![image](https://github.com/user-attachments/assets/80e29100-efab-4637-8a80-88d15dbffcc4)

and non heap non profiled nmethods:
![image](https://github.com/user-attachments/assets/d56ee1a6-a81d-4f4d-9a21-70b5e7939cf0)

Is this enough information ? Please tell me if you need anything else.
