### ISSUE TITLE
persistent user session has performance issues with organization feature having more then 300 organizations for given realm

### ISSUE THREAD

**Issue by sandip-oa** [keycloak/keycloak#34437]
### Description

We are evaluating organization feature. Our use-case involves creating 10000 or more organization within given realm and have users associated with these organizations. There is possibility those users could be part of multiple organizations.

We expected certain RPS during access token and refresh token generation. We have written performance test scripts which simulates this scenario. While running performance tests we observed that with 300 organization and 5000 users per first 100 organization and 1000 users for next 200 organization the performance drops after reaching 300+ PRS.

### Motivation

Handling multi-tenancy using organization feature instead of creating separate realm for each of end-customer. As we know Keycloak has performance issues after reaching certain number of realms within single instance.

### Details

Below are the details of our infrastructure and test scenario.

### Infrastructure
* Database - Aurora PostgreSQL db.r6g.xlarge
* Compute - EKS (4 pods - each 4vCPU and 8GB RAM)

### Test scenario
* Each second introduce new user and get access token
* For next 4-5 minutes each second generate new access token using refresh token
* Repeat the process for 15 min and increase the RPS to 500 over the time
 
### Test Configuration
* Tool - Artillery (distributed test on  ECS)
* Duration - 15 min
* ECS Task - 8vCPU and 16GB RAM

### Test Script
```
config:
  target: "<local-env-url>"
  plugins:
    metrics-by-endpoint: 
      useOnlyRequestNames: true
    apdex: 
      threshold: 1000
  environments:
    dev:
      target: "<dev-env-url>"
      phases:
        - duration: 300
          arrivalRate: 10
          rampTo: 300
          name: "ramp-to-300"
        - duration: 300
          arrivalRate: 300
          rampTo: 500
          name: "ramp-to-500"
        - duration: 300
          arrivalRate: 500
          name: "steady-load"
  http:  
    extendedMetrics: true
    timeout: 20
    pool: 20000
  processor: "../scripts/hooks.js" # custom processor for generating users and maintaining state

before:
  flow:
    - log: 'Connecting to redis client...'
    - function: connectToRedisClient
    - function: setCtxVariables
    - function: setUserData

after:
  flow:
    - log: 'Disconnecting from redis client...'
    - function: disconnectFromRedisClient
    - function: logUserData

scenarios:
  - name: "auth-user-scenario"
    flow:
      - function: "selectUserAndIncreaseCounter"
      - post:
          name: get-access-token
          url: "/realms/{{ $env.REALM_NAME }}/protocol/openid-connect/token"
          headers:
            'content-type': 'application/x-www-form-urlencoded'
          form:
            grant_type: 'password'
            response_type: 'token'
            client_id: '<clien-id>'
            username: '{{ currentAuthUser.username }}'
            password: '{{ currentAuthUser.password }}'
            scope: 'openid profile email {{ currentAuthUser.scope }}'
          capture:
            - json: "$.access_token"
              as: "accessToken"
            - json: "$.refresh_token"
              as: "refreshToken"
            - json: "$.id_token"
              as: "idToken"
            - json: "$.expires_in"
              as: "expiresIn"
          afterResponse:
              - inspectResponseAndLogError
              - setTokenActive
          ifTrue: 'hasExpired'
      - think: 1
      - post:
          name: get-access-token-using-refresh-token
          url: /realms/{{ $env.REALM_NAME }}/protocol/openid-connect/token
          headers:
            'content-type': 'application/x-www-form-urlencoded'
          form:
            grant_type: 'refresh_token'
            client_id: '<client-id>'
            refresh_token: '{{ refreshToken }}'
          capture:
            - json: "$.refresh_token"
              as: "newRefreshToken"
          afterResponse:
            - inspectResponseAndLogError
            - setRefreshToken
          ifTrue: 'not hasExpired'
```
### Observation
* After reaching 300+ RPS performance drops significantly with high CPU utilization on DB side. Lot of `COMMIT` happening to `offline_user_session` table it seems.
* If we disable `persistent-user-sessions` we are able to achieve the expected RPS and even increase the number of organizations upto 5000.
