### ISSUE TITLE
Renaming realm in UI broken

### ISSUE THREAD

**Issue by yo-l1982** [keycloak/keycloak#34540]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

In a freshly install using keycloak operator(26.0.4) in kubernetes, it is not possible to rename the "master" realm through the Admin UI.
PUT request to the endpoint gets response:
 `errorMessage	"Can't rename master realm"`

If I create a new realm and try to rename the new one the same UI behaviour will happen.
Now the put request states:
`error	"HTTP 403 Forbidden"`

### Version

26.0.4

### Regression

- [ ] The issue is a regression

### Expected behavior

Realm would rename and no error should appear in the UI or an error message showing the real error from PUT request "errorMessage	"Can't rename master realm""

### Actual behavior

An error screen stating "Realm not found" and realm is not renamed.
Browser URL changes to point to renamed realm url.
Realm drop down stops working
![Screenshot_20241031_110728](https://github.com/user-attachments/assets/16f65a71-070c-4ff4-b8ef-e77b3b571fe7)

### How to Reproduce?

Using a fresh local postgresdb.
Keycloak manifest used in setup.
```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  proxy:
    headers: "forwarded"
  hostname:
    hostname: "http://localhost:8081"
  resources:
    requests:
      cpu: "0.5"
      memory: "1250M"
    limits:
      cpu: "6"
      memory: "2250M"
  db:
    vendor: "postgres"
    host: "my-postgresql.postgres.svc.cluster.local"
    port: 5432
    database: "postgres"
    poolMinSize: 2
    poolInitialSize: 2
    poolMaxSize: 2
    usernameSecret:
      name: "my-postgresql"
      key: "postgres-username"
    passwordSecret:
      name: "my-postgresql"
      key: "postgres-password"
  startOptimized: false 
  features:
    enabled:
      - "token-exchange"
      - "admin-fine-grained-authz"
  transaction:
    xaEnabled: false 
  additionalOptions:
    - name: http-max-queued-requests
      value: "1000"
    - name: metrics-enabled 
      value: "true"
    - name: http-pool-max-threads 
      value: "66"
    - name: spi-connections-infinispan-quarkus-site-name
      value: "keycloak"
    - name: hostname-debug
      value: "true"
    - name: http-relative-path
      value: "/"
    - name: http-management-relative-path
      value: "/"


  instances: 1
  ingress:
    enabled: false
  http:
    httpEnabled: true
```
master realm:
- Login with the generated temp-admin
- Navigate to "Realm Settings"
- Change "Realm Name"
- Save

Freshly created realm:
- Create new realm
- Navigate to "Realm Settings"
- Change "Realm Name"
- Save

### Anything else?

It is possible to edit the url in the browser to reference the old realm name and UI will start working again.
