### ISSUE TITLE
Web Application hit too many redirects issue after upgrade from keycloak-23.0.7 to keycloak-25.0.5

### ISSUE THREAD

**Issue by weim3ng** [keycloak/keycloak#34727]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

1. Upgrade from keycloak 23.0.7 to 25.0.5

2. Environment - azure aks with Kubernetes version v 1.28.5

3. Run - Login with Angular Web Application which is using keycloak-angular package with keycloak.js v 25.0.6

4. Web Application hit too many redirect issue
![377838864-e671e387-dc8d-44f7-898c-fac7ff0b65f2](https://github.com/user-attachments/assets/980e960f-57d8-4aab-b62a-3f70ca1ebff6)
5. Found that is related to duplicate Cookies AUTH_SESSION_ID
![377839569-08873d33-c4d9-423f-b675-d1282663e9a6](https://github.com/user-attachments/assets/a3345f22-2b96-4620-9b6c-09078c5375a9)
6. how do I get rid of the duplicate cookies in client browser without the need of users to manually clear their browser cookies?

### Version

25.0.5

### Regression

- [X] The issue is a regression

### Expected behavior

Able to login successfully as in keycloak 23.0.7 version

### Actual behavior

Angular Web Application hit too many redirect issue.
![377838864-e671e387-dc8d-44f7-898c-fac7ff0b65f2](https://github.com/user-attachments/assets/cdb3fff0-15cb-4c5e-b1ff-24dadc368382)

### How to Reproduce?

1. Upgrade from keycloak 23.0.7 to 25.0.5

2. Environment - azure aks with Kubernetes version v 1.28.5

3. Run - Login with Angular Web Application which is using keycloak-angular package with keycloak.js v 25.0.6

4. Web Application hit too many redirect issue
![377838864-e671e387-dc8d-44f7-898c-fac7ff0b65f2](https://github.com/user-attachments/assets/980e960f-57d8-4aab-b62a-3f70ca1ebff6)
5. Found that is related to duplicate Cookies AUTH_SESSION_ID
![377839569-08873d33-c4d9-423f-b675-d1282663e9a6](https://github.com/user-attachments/assets/a3345f22-2b96-4620-9b6c-09078c5375a9)
6. how do I get rid of the duplicate cookies in client browser without the need of users to manually clear their browser cookies?

### Anything else?

yaml file
``` yaml
image:
  debug: true

auth:
  adminUser: ${KEYCLOAK_ADMIN_USER}
  adminPassword: ${KEYCLOAK_ADMIN_PASSWORD}

postgresql:
  enabled: false

externalDatabase:
  host: ${DB_HOST}
  port: 1433
  database: ${DB_NAME}
  user: ${DB_USER}
  password: ${DB_PASSWORD}

cache:
  enabled: true

production: true

proxy: edge

extraStartupArgs: "--spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true --spi-sticky-session-encoder-infinispan-should-attach-route=true"

extraEnvVars:
  - name: KEYCLOAK_LOG_LEVEL
    value: DEBUG
  - name: QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY
    value: "true"
  - name: QUARKUS_TRANSACTION_MANAGER_OBJECT_STORE_DIRECTORY
    value: "/opt/bitnami/keycloak/objectstore"
  - name: PROXY_ADDRESS_FORWARDING
    value: "true"
  - name: KC_DB
    value: "mssql"
  - name: KC_DB_URL
    value: "jdbc:sqlserver://${DB_HOST}:1433;databaseName=${DB_NAME};encrypt=true;trustServerCertificate=false;loginTimeout=30;sendStringParametersAsUnicode=false;"
  - name: KC_TRANSACTION_XA_ENABLED
    value: "false"

replicaCount: 2

resources:
  requests:
    cpu: 384m
    memory: 1536Mi
  limits:
    cpu: 500m
    memory: 2048Mi

livenessProbe:
  enabled: true
  initialDelaySeconds: 300
  periodSeconds: 1
  timeoutSeconds: 5
  failureThreshold: 3
  successThreshold: 1

readinessProbe:
  enabled: true
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
  successThreshold: 1

startupProbe:
  enabled: false
  initialDelaySeconds: 30
  periodSeconds: 5
  timeoutSeconds: 1
  failureThreshold: 60
  successThreshold: 1

nodeSelector:
  application: "yes"

extraVolumeMounts:
  - mountPath: /opt/bitnami/keycloak/themes/dms
    name: theme
  - mountPath: /opt/bitnami/keycloak/objectstore
    name: objectstore

extraVolumes:
  - name: theme
  - name: objectstore

service:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800

ingress:
  annotations:
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "*"
    nginx.ingress.kubernetes.io/cors-allow-origin: "https://*.xxx.xxxxxxxx.com, http://localhost:4200" 
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/proxy-buffer-size: 12k
    # this section was used in keycloak 23.0.7 but have to remove in 25.0.5
    # nginx.ingress.kubernetes.io/affinity: "cookie"
    # nginx.ingress.kubernetes.io/session-cookie-name: "AUTH_SESSION_ID" 
    # nginx.ingress.kubernetes.io/session-cookie-max-age: "86400"
    # nginx.ingress.kubernetes.io/session-cookie-expires: "86400"
    # nginx.ingress.kubernetes.io/affinity-mode: "balanced"
  hostname: ${KEYCLOAK_INGRESS_HOST}
  ingressClassName: nginx-internal
  tls: true

pdb:
  create: true
  minAvailable: 1

logging:
  output: default
  level: INFO
```
