### ISSUE TITLE
Can't log in to clients on 26.0.5

### ISSUE THREAD

**Issue by oculos** [keycloak/keycloak#34800]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

I suddenly can't login to my clients after updating to 26.0.5

I am not sure what happened. I enter my username and password, but I don't get presented with the two-factor.

All I get in the logs is this: 

Non-secure context detected; cookies are not secured, and will not be available in cross-origin POST requests

### Version

26.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

To log in properly

### Actual behavior

I don't get logged in. I end up with a timeout and gateway error

### How to Reproduce?

Upgrade to 26.0.5

**Comment by shawkins** [comment]
> Non-secure context detected; cookies are not secured, and will not be available in cross-origin POST requests

Are you running an edge / tls terminiation proxy? If so there is now a check for a secure context that will require you to have enabled proxy-headers and are setting at least a header that would convey the scheme.

**Comment by oculos** [comment]
Thanks. Actually my problem was DNS.

But I still keep getting this errors. I do have proxy edge termination, and I have the headers configured:

On my nginx:

``` 
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
``` 

And on my ingress: 

``` 
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "X-Forwarded-For $http_x_forwarded_for";
        proxy_set_header X-Forwarded-Proto: https;
``` 


My Dockerfile has this:

``` 
ENV KC_PROXY_HEADERS=xforwarded
ENV KC_PROXY_TRUSTED_ADDRESSES=10.20.30.10,10.234.0.0/8,127.0.0.0/8
#ENV KC_PROXY=edge
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
``` 

My deployment yml:

``` 
 additionalOptions:
    - name: proxy-headers
      value: xforwarded
    - name: proxy-trusted-addresses
      value: "10.20.30.15,10.234.0.0/16"
#    - name: proxy
#      value: edge
#   - name: hostname-debug
 #     value: "true"
 ``` 


Should I do something differently?
