### ISSUE TITLE
Theme doesn't display 

### ISSUE THREAD

**Issue by ronycohen** [keycloak/keycloak#34978]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

After installing the keycloak (docker) solution and apply themes to the Realm.
![image](https://github.com/user-attachments/assets/1bfa5a87-471e-4ecd-8d65-f22b4c71457a)

The login UI page is not displaying any style : 

http://keycloak.local:8080/realms/GRC/protocol/openid-connect/auth?client_id=grc&redirect_uri=http%3A%2F%2Flocalhost%3A5173%2Flogin&state=31c6beba-b3c1-4c92-8935-47fa1ae539df&response_mode=fragment&response_type=code&scope=openid&nonce=23795dbe-1f92-43ae-82d6-5a94cbf2894f&code_challenge=JoHQc13fJMO3K3rmcqyC_qT_zz-oQlOkOZiKn5YNE8k&code_challenge_method=S256

![image](https://github.com/user-attachments/assets/7c7fdb3f-190c-402b-999e-39a7f8abfd41)

Here is the Docker Compose : 
```
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://192.168.1.12:5432/keycloak  
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME=keycloak.local
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=keycloak.local
      # - KC_HTTP_RELATIVE_PATH=/
      - KC_FRONTEND_URL=http://keycloak.local:8080/
      - KC_LOG_LEVEL=debug
      - KC_HOSTNAME_STRICT_HTTPS=false
    ports:
      - "8080:8080"
    volumes:
      - ./themes:/opt/keycloak/themes
    restart: always
    command: start-dev
    #command: start
    
```

### Version

26.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

I would expect the Base or one of the custom theme I applied to the Client created.

### Actual behavior

Currently I don't have any Style applied to the Login/ui page.

### How to Reproduce?

I just installed the latest version through docker compose, created a Realm a client and a user. I did connect a Web-App to keycloak and got a login page without style.

### Anything else?

I tried to apply several custom theme : 
 
```
   volumes:
      - ./themes:/opt/keycloak/themes
```   
But even with them selected it's not working.
