### ISSUE TITLE
[Operator] Network Policy Rules

### ISSUE THREAD

**Issue by pruivo** [keycloak/keycloak#35598]
### Description

Follow up on https://github.com/keycloak/keycloak/issues/34659

When Kubernetes network policies are enabled in the Keycloak Operator, the user must be able to configure the rules for the incoming traffic. 

The simplest proposal is below, where 3 new attributes are added to the Keycloak CR: `http`, `https` and `management`. 

```
networkPolicy:
    enabled: true
    http: -> array of `NetworkPolicyPeer`
    https: -> array of `NetworkPolicyPeer`
    management: -> array of `NetworkPolicyPeer`
```

### Details

* The reason to have `http` and `https` attributes is that Keycloak allows both ports 8443 (HTTPS) and 8080 (HTTP) enabled. 
* The `NetworkPolicyPeer` is a Kubernetes Resource ([Reference here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.31/#networkpolicypeer-v1-networking-k8s-io)).
