### ISSUE TITLE
Some Prometheus Metrics Missing in Kubernetes Deployment

### ISSUE THREAD

**Issue by kmcchesney21** [keycloak/keycloak#35952]
### Description

I am trying to deploy the [Keycloak Grafana Dashboard](https://grafana.com/grafana/dashboards/10441-keycloak-metrics-dashboard/) and noticed that I am not getting all of the prometheus metrics necessary to get the dashboard working. I am getting the java related metrics but not any of the keycloak ones (e.g. keycloak_logins). I also noticed in the keycloak UI the `jboss-logging` Event Listener is enabled and there is no option to add the `metrics-listener` Event Listener. I will also note that I have set the `metrics-enabled=true` in my keycloak deployment yaml and confirmed the `KC_METRICS_ENABLED` env variable is true in the deployment.

I know there are ways to rebuild the image to enable this functionality but I was hoping to continue using the provider image if possible (currently on quay.io/keycloak/keycloak:26.0.7). Are there any plans to add the keycloak related metrics to the provider image or will that require me to build the image myself?

### Motivation

Provides ability for keycloak instances deployed to kubernetes to leverage open source grafana dashboards for monitoring.

### Details

I am deploying into my kubernetes cluster by installing the keycloak operator and CRDs from:
https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.0.7/kubernetes/kubernetes.yml                                
https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.0.7/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml  
https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/26.0.7/kubernetes/keycloaks.k8s.keycloak.org-v1.yml    

Here is a snippet of one of my keycloak pod definitions to confirm config settings:
```
apiVersion: v1                           
kind: Pod                          
spec:
  containers:
  - args:
    - -Djgroups.dns.query=keycloak-discovery.keycloak
    - --verbose
    - start
    env:
    - name: JAVA_OPTS
      value: -Dcom.redhat.fips=false -Djgroups.dns.query=keycloak-discovery.keycloak.svc.cluster.local.
    - name: QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY
      value: "true"
    - name: KC_HOSTNAME
      value: keycloak-testkube.trunk.fade
    - name: KC_HTTP_PORT                                                  
      value: "8080"
    - name: KC_HTTPS_PORT
      value: "8443"
    - name: KC_HTTPS_CERTIFICATE_FILE
      value: /mnt/certificates/tls.crt
    - name: KC_HTTPS_CERTIFICATE_KEY_FILE
      value: /mnt/certificates/tls.key
    - name: KC_DB
      value: postgres
    - name: KC_DB_USERNAME
      valueFrom:
        secretKeyRef:
          key: username
          name: keycloak-db-secret
    - name: KC_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: keycloak-db-secret
    - name: KC_DB_URL_HOST
      value: keycloak-testkube-trunk.trunk.fade
    - name: KC_BOOTSTRAP_ADMIN_USERNAME
      valueFrom:
        secretKeyRef:
          key: username
          name: keycloak-initial-admin
    - name: KC_BOOTSTRAP_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          key: password
          name: keycloak-initial-admin
    - name: KC_HEALTH_ENABLED
      value: "true"
    - name: KC_CACHE
      value: ispn
    - name: KC_CACHE_STACK
      value: kubernetes
    - name: KC_METRICS_ENABLED
      value: "true"
    - name: KC_TRUSTSTORE_PATHS
      value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    - name: KC_TRACING_SERVICE_NAME
      value: keycloak
    - name: KC_TRACING_RESOURCE_ATTRIBUTES
      value: k8s.namespace.name=keycloak
    image: quay.io/keycloak/keycloak:26.0.7
    ports:
    - containerPort: 8443
      name: https
      protocol: TCP
    - containerPort: 8080
      name: http
      protocol: TCP
    - containerPort: 9000
      name: management
      protocol: TCP
```
