### ISSUE TITLE
Keycloak new Management Interface port breaks in GCE Ingress + Operator

### ISSUE THREAD

**Issue by mike-pt** [keycloak/keycloak#36257]
### Before reporting an issue

- [X] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

I'm not sure if this is a bug as it seems intended but ended up breaking compatibility with GKE setups (probably the later).

While upgrading to v25 (tried 26 too) with the operator ingress is now failing the health checks, I noticed the was a change in the port.

I can see the service now exposing both port 8080 and 9000 and so the operator does create the service with new port.

I am using a custom ingress because with the "ingress" enabled in the operator I bump into other issues in GKE, it seems mostly tailored for openshift, also with GCE ingress we get free managed certificates.

The issue is GCE insists in creating a default healthcheck

```
checkIntervalSec: 15
creationTimestamp: '2025-01-06T15:37:21.226-08:00'
description: Default kubernetes L7 Loadbalancing health check for NEG.
healthyThreshold: 1
id: 'xxxxxx'
kind: compute#healthCheck
logConfig:
  enable: true
name: k8s1-2afddd51-keycloak-alpha-cde-keycloak-service-8080-c8c14c0c
selfLink: https://www.googleapis.com/compute/v1/projects/alpha/global/healthChecks/k8s1-xxxxx-keycloak-alpha-keycloak-service-8080-xxxxx
tcpHealthCheck:
  portSpecification: USE_SERVING_PORT
  proxyHeader: NONE
timeoutSec: 15
type: TCP
unhealthyThreshold: 2
```

I tried to add custom probes:
```
      containers:
         -
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9000
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000
              scheme: HTTP
          startupProbe:
            httpGet:
              path: /health/started
              port: 9000
              scheme: HTTP
            initialDelaySeconds: 60   # Increase to allow Keycloak startup
            periodSeconds: 10         # Reduce probe frequency
            timeoutSeconds: 5         # Allow slow responses
            failureThreshold: 30      # Wait up to 5 minutes before failing
```

Unfortunately this seems to be ignored by GCE ingress (though I see the probs listed in the pods) 

From the docs google either uses BackendConfig or Readiness probe.

https://cloud.google.com/kubernetes-engine/docs/troubleshooting/ingress-health-checks

This was working fine before and though I understand the security issue with other endpoints I'm not to worried about health endpoints.... I don't see much wrong with those being public tbh and they are useful for external health-checks/ping from monitor tools. Is there a way to still have those endpoints in port 8080? Or is this all or nothing? Or is there some other way to set the readinessProbe? I seems google only cares for it if its on the same port.

### Version

25 and 26

### Regression

- [X] The issue is a regression

### Expected behavior

Operator Deploy would work fine with GCE ingress after upgrade

### Actual behavior

After upgrade ingress is not healthy and the service is not exposed.

### How to Reproduce?

GCP and custom ingress resource (disable ingress in operator)

Sample ingress yaml
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: -keycloak-ingress
  namespace: keycloak
  annotations:
    kubernetes.io/ingress.global-static-ip-name: kc-gw-lb
    networking.gke.io/managed-certificates: "${CERT_NAME}"
    networking.gke.io/v1beta1.FrontendConfig: keycloak-ingress
    kubernetes.io/ingress.className: "gce"
spec:
  rules:
  - host: ${HOSTNAME}
    http:
      paths:
      # - path: /auth
      - pathType: ImplementationSpecific
        backend:
          service:
            name: ${ENV_SUBSYS}-keycloak-service
            port:
              number: 8080
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: CERT_NAME
  namespace: keycloak
spec:
  domains:
    - $HOSTNAME
```
