### ISSUE TITLE
feat(metrics): add label `application` to metrics generated by `keycloak`

### ISSUE THREAD

**Issue by davinkevin** [keycloak/keycloak#36280]
### Description

Hello 👋 

As a user of Keycloak in multiple environements (with quarkus, spring boot, armeria, ktor…), they all have in common the usage of `micrometer`, which makes monitoring and grafana dashboard easy to create. 

However, in the stack, `keycloak` is the only one without `application` label in metrics, and this makes harder to rely on already existing dashboards, including those from [the community](https://grafana.com/grafana/dashboards/4701-jvm-micrometer/). 

Would it be possible to add an hardcoded label `application: keycloak` or maybe something we can configure… as soon as a label is available, it will do the job. 

### Motivation

Simplify operation and dashboard creation for `Keycloak`, using those already available for `micrometer`.

If required or accepted, I could provide a PR for this, with proper guidance to do that "the way the project wants it". 

### Details

Provided in the description. 

Technically, this can be a simple line introduction, with `registry.config().commonTags("application", "keycloak")` in the code.

**Comment by mabartos** [comment]
@mhajas @ahus1 Could you please check it?

**Comment by ahus1** [comment]
With scraping tools like Prometheus, adding common labels to the application is IMHO less common, as it offers "relabeling", and adding context information to scraped metrics automatically.

For example, with Kubernetes, you would automatically get the namespace added as a label. If you have a non-Kubernetes setup, you can add those information to the scraping configuration of Prometheus. 

To configure the scraping in Kubernetes, the `PodMonitor` CR offers three places: The `podTargetLabels`, which would copy over labels from the Pod 1:1, relabeling with a constant replacement, and relabeling with a dynamic mapping of one or more source labels.  

If you can show examples how tools other than Prometheus fail to offer such functionality, we might consider this one for a PR / help wanted. 

```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: keycloak-metrics
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: keycloak
  # Use pod target labels "as is" without any renaming
  # podTargetLabels:
  #   - app
  podMetricsEndpoints:
    - port: management
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
      relabelings:
        - targetLabel: application
          # Alternative: hard-coded value
          # replacement: "keycloak"
          sourceLabels:
          - __meta_kubernetes_pod_label_app
          regex: (.+)
          replacement: ${1}
```

**Comment by davinkevin** [comment]
I already do that, but it requires a dedicated `[Pod|Service]Monitor` for `keycloak`.
When the `application: …` label is part of the system already, it allows to use the same `[Pod|Service]Monitor` for a group of heterogeneous pods. 

```
apiVersion: monitoring.coreos.com/v1
kind: …Monitor
metadata:
  name: my-product-or-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: my-product-or-service
  namespaceSelector:
    any: false
    matchNames: []
  endpoints:
    - …
```

Because they all provides the same `endpoint` and same set of labels, especially for JVM, it allows application to be scraped the same way. 

From an organization point of view, it becomes less an *Operator* responsibility (`[Pod|Service]Monitor`) and more a *Developer*'s one, where they have to set an `application` label in the app to simplify operation.

As already mentioned, the idea is to simplify operations at scale, between applications and frameworks. 

Thank you 😇
