### ISSUE TITLE
Receiving an error when logout using infinispan 15

### ISSUE THREAD

**Issue by changrett4** [keycloak/keycloak#36853]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Describe the bug

I'm using keycloak 26.1.0 with infinispan 15.0.11.Final as an external cache and when i'm doing a logout of Keycloak, this returns : 

2025-01-27 14:45:32,288 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-5) Uncaught server error: java.util.concurrent.CompletionException: org.infinispan.client.hotrod.exceptions.HotRodClientException:Request for messageId=149 returned server error (status=0x85): org.infinispan.commons.marshall.MarshallingException: Unknown type id : 65606

This id is the same of  ClientSessionKey "object" in Protoschema send by keycloak to infinispan instance.  Below are my docker settings for keycloak and infinispan

docker-compose keycloak:
```yaml
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    ports:
      - 5432:5432
    networks:
      - keycloak-net
  keycloak:
    depends_on:
      - postgres
    build:
      context: .
    restart: unless-stopped
    ports:
      - 0.0.0.0:8080:8080
      - 0.0.0.0:9000:9000
    networks:
      - keycloak-net
    environment:
      KC_DB: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_CACHE: ispn
      KC_CACHE_REMOTE_TLS_ENABLED: false
      KC_CACHE_REMOTE_HOST: 192.168.56.101
      KC_CACHE_REMOTE_PORT: 11222
      KC_CACHE_REMOTE_USERNAME: infinispan
      KC_CACHE_REMOTE_PASSWORD: infinispan
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123

networks:
  keycloak-net:
    driver: bridge
```
-----------------------------------------------------------------
Dockerfile keycloak:
```Dockerfile
FROM quay.io/keycloak/keycloak:26.1.0 as builder
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_DB=postgres
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_FEATURES=multi-site,clusterless
ENV KC_FEATURES_DISABLED=persistent-user-sessions
WORKDIR /opt/keycloak
# for demonstration purposes only, please make sure to use proper certificates in production instead
#RUN keytool -genkeypair -storepass password -storetype PKCS12 -keyalg RSA -keysize 2048 -dname "CN=server" -alias server -ext "SAN:c=DNS:localhost,IP:127.0.0.1" -keystore conf/server.keystore
RUN /opt/keycloak/bin/kc.sh build --http-relative-path=/auth

FROM quay.io/keycloak/keycloak:26.1.0
COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENV KC_FEATURES=multi-site,clusterless
ENV KC_FEATURES_DISABLED=persistent-user-sessions
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_CLUSTER_ENABLED=true
ENV KC_CLUSTER_SITE=DC1
ENV KC_SPI_CONNECTIONS_INFINISPAN_QUARKUS_SITE_NAME=site1

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD [ "start-dev","--http-relative-path=/auth"]
```
-----------------------------------------------------------------
docker-compose ispn:
```yaml
services:
  infinispan:
    image: infinispan/server:15.0.5.Final
    container_name: infinispan
    network_mode: "host"
    environment:
      - USER=infinispan
      - PASS=infinispan
      - CLUSTER_NAME=infinispan-cluster
      - ENABLE_STATISTICS=true
      - BIND_ADDRESS=192.168.56.101
      - JGROUPS_DISCOVERY_PROTOCOL=TCPPING
      - JGROUPS_DISCOVERY_PROPERTIES=initial_hosts=192.168.56.101[7800];port_range=0
```
   -----------------------------------------------------------------

192.168.56.101 is the IP of an internal VM 

### Version

26.1.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak must store operations correctly and error-free in external ispn caches

### Actual behavior

2025-01-27 14:45:32,288 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-5) Uncaught server error: java.util.concurrent.CompletionException: org.infinispan.client.hotrod.exceptions.HotRodClientException:Request for messageId=149 returned server error (status=0x85): org.infinispan.commons.marshall.MarshallingException: Unknown type id : 65606

### How to Reproduce?

How to reproduce error: 
- Use an external ispn cache with version 15.0.11.Final with the above settings
-  Log in to keycloak using admin credentials
-  Log out of keycloak
