### ISSUE TITLE
Invoking dynamic client registration with lightweight access token results in a 404

### ISSUE THREAD

**Issue by stianst** [keycloak/keycloak#36926]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

oidc

### Describe the bug

Using the bootstrap admin client to obtain an access token (lightweight token by default) to dynamically register a client fails with:

```
Request failed: status=403, error=insufficient_scope, description='Forbidden', url=http://localhost:8080/realms/master/clients-registrations/openid-connect
```

Disabling `Always use lightweight access token` without any additional changes works, so this seems to be just down to the fact the dynamic client registration is not "introspecting" lightweight access tokens.

### Version

nightly

### Regression

- [ ] The issue is a regression

### Expected behavior

Dynamic client registration supports lightweight access tokens

### Actual behavior

Dynamic client registration results in 403 with lightweight access tokens

### How to Reproduce?

Start Keycloak with `bin/kc.sh start-dev --bootstrap-admin-client-id=test --bootstrap-admin-client-secret=test`

Use the following config for kct:

```
---
default-context: "bootstrap"
store-tokens: false
truststore: {}
issuers:
  test:
    url: "http://localhost:8080/realms/master"
    client-registration-context: "bootstrap"
    contexts:
      bootstrap:
        flow: "client"
        client:
          secret: "test"
          client-id: "test"
```

Then try to create a client:

```
kct config context create --context=myclient --client=myclient --client-secret=secret --flow=client  --create-client --iss test -X
```

With `kct token -d` you can see the token is a lightweight token, and `kct introspect` will show you that the introspected token has access to create clients.
