### ISSUE TITLE
Keycloak 26 modifies redirect URI hostname when running behind IIS proxy

### ISSUE THREAD

**Issue by imsaha** [keycloak/keycloak#37102]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### **Description**
When using Keycloak 26 behind an IIS proxy, the `redirect_uri` is being modified from `http://localhost:5267/scalar/v1` to `https://domain.com/scalar/v1` after successful authentication. This happens even though the proxy headers and Keycloak configuration seem correct.

  - KC_HOSTNAME=${KEYCLOAK_HOSTNAME}
  - KC_HOSTNAME_URL=https://${KEYCLOAK_HOSTNAME}
  - KC_PROXY_HEADERS=forwarded

### Version

26

### Regression

- [ ] The issue is a regression

### Expected behavior

Expected to redirect to the provided redirect_uri.

redirect_uri = `http://localhost:5267/scalar/v1` without modifying the base address

### Actual behavior

Redirects to `https://domain.com/scalar/v1` rewriting the base address `http://localhost:5267`

### **Steps to Reproduce**
1. Docker compose.

```yml
services :
  keycloak :
    image : quay.io/keycloak/keycloak:26.0.5
    container_name : kc26
    environment :
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres/${POSTGRES_DB}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      
      - KC_HOSTNAME=${KEYCLOAK_HOSTNAME}
      - KC_HOSTNAME_URL=https://${KEYCLOAK_HOSTNAME}
      - KC_HTTP_ENABLED=true

      - KC_HOSTNAME_STRICT=true
      - KC_HOSTNAME_STRICT_HTTPS=false

      - KC_PROXY_HEADERS=forwarded

      - KC_HTTPS_CERTIFICATE_FILE=/keycloak/certificates/__smartmeservices.ae.pem
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/keycloak/certificates/__smartmeservices.ae_key.pem

    ports :
      - "80:8080"
      - "443:8443"
    volumes :
      - ./certificates:/keycloak/certificates
      - ./themes:/opt/keycloak/themes
    command : start 
    restart : always
    depends_on :
      - postgres
      - rabbitmq
    networks :
      - kc26net

  postgres :
    image : postgres:latest
    container_name : postgres
    restart : always
    environment :
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports :
      - 5432:5432
    volumes :
      - ./db_data:/var/lib/postgresql/data
    networks :
      - kc26net

networks :
  kc26net :
    driver : bridge

```

2. IIS config:
```xml

<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <system.webServer>
        <rewrite>
            <rules>
                <!-- Reverse Proxy to Keycloak Server -->
                <rule name="Keycloak Reverse Proxy" enabled="true" stopProcessing="true">
                    <match url="(.*)" />
                    <action type="Rewrite" url="https://192.168.1.25/{R:0}" appendQueryString="true" logRewrittenUrl="false" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>
```

3. Map the IIS website to a domain.com
