### ISSUE TITLE
Enabling metrics in operator

### ISSUE THREAD

**Issue by yaroslavkasatikov** [keycloak/keycloak#37175]
### Description

Hello team,

Could you please tell me if it is possible to enabled metrics with help of new keycloak operator?
I seems I need to run keycloak with args `--metrics-enabled=true` but I don't know how to do it.
Also I didn't find anything in docs.

Thanks!

**Comment by yaroslavkasatikov** [comment]
Found the solution:

```
spec:
  additionalOptions:
  - name: metrics-enabled
    value: "true"
```
