### ISSUE TITLE
java.net.SocketTimeoutException & java.net.SocketException error leads to 502 Bad Gateway error

### ISSUE THREAD

**Issue by SatheeshSP** [keycloak/keycloak#37211]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

We have multiple Keycloak pods deployed in an Azure Kubernetes cluster, which are routed through an Azure Application Gateway with an active WAF policy. The WAF policy settings are as follows:

Maximum request body inspection limit: 128 KB
Maximum request body size: 128 KB
Maximum file upload size: 100 MB
JavaScript Challenge expiration: 30 minutes (preview)

In some scenarios, our application UI encounters a 502 Bad Gateway error when attempting to connect to Keycloak via the following API call:

> API call: https://{keycloak_domain_name}/realms/{realm_name}/broker/{client_identity_provider_name}/endpoint?code=1.AQ4AcvQs_hUWUEOuOSFEHQL78fNsUKePXrlJr-mdRMVogKVpAQAOAA.AgABBAIAAABVrSpeuWamRam2jAF1XRQEAwDs_wUA9P8QqpefKuea2RhkblP4d37gxlmFSHW0UJDY4ogBvY43TKJ6xLXL905lEqyNORNIVY-D-ShQqb9vbyKYLaD2Va4fev-gz2zbANjZ2VeQlcp2jhKSHM-bvnwkfs1ueSQCKbs8p1P6xm3SCY6Vt2VNv_ZI13vzJCSEma1oehxe2ofzvrN2zKTiw6I5Eax4IV9x5MPBBJPxyY9UVzKUOPnrmvytcdTQsWfDv96lhzO38MlDELQei6ji_zezs2ic6-pPnW6BE0MJr7IIGMP9mmDn1SlYglqF34jpUoISqxDkpqk2T_JFGIvJZMmJU8L-rbEN0UrPB6lcKrh9HKzhWD_o3EdU7eAbInsxf05wuQdMcxkVM3ig15Ul8nr-XbauV3Bm1Kjiqr9bNrNt2jEGNUWa1W_WA1PBHPHaksdIjyhH9WyreNDZTjkBYhrHHm1AnCpueY2DpTLrhuftCm4OibBNS8GBqkXAVlSmV0anG1TBPAvHeteOwXl7HVix8_AVSPl8zj1lOr48ogppTbD-mC-46LCLiBpIw9X--OGGnilWtG31Sp_XSTJQI0hauMNKcan8ZBubb5dXfM-8-ZxFui0MDMIn0IZMIRuBf4GeC8OCG91WmnuehpX0TKjR19Lfke79N0Ug0uzGltlZaGQGe8s9zmXaiatOl9MesaXs8wR-126KinrKM9VpK7uRQ5RUrwcCkoRY7GlqM3EE3cNHrNoqZJgaOm41KGMvPEDVjPw4lJJChQ4wbR5V6hnllDnT1XvFGcxmlR3bfNDyVzq4Hx0MyA&state=Q5cpSPbnZlAtoZZIJzRbuKUMiFLvBh8-vYTplI675Tw.-cRtAqLoTWo.1FzBwx2NQ_WvG9NE2aHnHA.eyJydSI6Imh0dHBzOi8vc2FpYS5saXZlaGF1bC5pby9hcGkvYXV0aC9jYWxsYmFjay9rZXljbG9hayIsInJ0IjoiY29kZSJ9&session_state=001fc4e9-2626-1adf-30bf-5059e6fabf7d#

![Image](https://github.com/user-attachments/assets/278e0d9f-ce49-47cf-bfc2-0298d7f8a7c7)

When reviewing the logs in Datadog, the error "Failed to make identity provider OAuth callback" is observed. The following event attributes are associated with this error:

![Image](https://github.com/user-attachments/assets/a069acca-6d47-4e4d-b266-11faca04d7c2)
![Image](https://github.com/user-attachments/assets/a74b84f7-9580-4b17-912c-c4c440a95950)

Here is the Kubernetes resource template that I have used:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-name-keycloak-env
  labels:
    helm.sh/chart: keycloak-26.0.0-keycloak26.1_2
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
data:
  JAVA_OPTS_APPEND: '-Djgroups.dns.query=keycloak-headless-service'
  KC_CACHE_STACK: kubernetes
  KC_DB: postgres
  KC_DB_PASSWORD: ***
  KC_DB_URL: {DB_URL}
  KC_DB_USERNAME: {DB_USERNAME}
  KC_HEALTH_ENABLED: 'true'
  KC_HOSTNAME: {KEYCLOAK_DOMAIN_NAME}
  KC_HTTP_ENABLED: 'true'
  KC_HTTPS_CERTIFICATE_FILE: /etc/ssl/tls.crt
  KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/ssl/tls.key
  KC_LOG_CONSOLE_OUTPUT: json
  KC_LOG_LEVEL: INFO
  KC_METRICS_ENABLED: 'true'
  KC_PROXY: edge
  KC_PROXY_HEADERS: xforwarded
  KC_TRANSACTION_XA_ENABLED: 'false'
  KEYCLOAK_ADMIN: {KEYCLOAK_ADMIN_NAME}
  KEYCLOAK_ADMIN_PASSWORD: ***
  PROXY_ADDRESS_FORWARDING: 'true'
---
# Source: keycloak/templates/headless-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-keycloak-headless-service
  labels:
    helm.sh/chart: keycloak-26.0.0-keycloak26.1_2
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: release-name
---
# Source: keycloak/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-keycloak
  labels:
    helm.sh/chart: keycloak-26.0.0-keycloak26.1_2
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443
  selector:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: release-name
---
# Source: keycloak/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-keycloak
  labels:
    helm.sh/chart: keycloak-26.0.0-keycloak26.1_2
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
    tags.datadoghq.com/env: default
    tags.datadoghq.com/service: keycloak
    tags.datadoghq.com/version: "26.0.0-keycloak26.1-2"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      annotations:
        ad.datadoghq.com/keycloak.logs: '[{"source":"csharp"}]'
        admission.datadoghq.com/dotnet-lib.version: v2.50.0-musl
      labels:
        helm.sh/chart: keycloak-26.0.0-keycloak26.1_2
        app.kubernetes.io/name: keycloak
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "1.16.0"
        app.kubernetes.io/managed-by: Helm
        tags.datadoghq.com/env: default
        tags.datadoghq.com/service: keycloak
        tags.datadoghq.com/version: "26.0.0-keycloak26.1-2"
    spec:
      imagePullSecrets:
        - name: acrcsecret
      serviceAccountName: default
      securityContext: {}
      containers:
        - name: keycloak
          securityContext:
            runAsGroup: 1000
            runAsNonRoot: true
            runAsUser: 1000
          image: "keycloak:26.0.0-keycloak26.1-2"
          imagePullPolicy: IfNotPresent
          args:
            - start
          env:
          - name: DD_ENV
            value: "default"
          - name: DD_SERVICE
            value: "release-name-keycloak"
          - name: DD_VERSION
            value: "26.0.0-keycloak26.1-2"
          - name: DD_LOGS_INJECTION
            value: "true"
          - name: DD_PROFILING_ENABLED
            value: "true"
          - name: DD_RUNTIME_METRICS_ENABLED
            value: "true"
          - name: DD_TRACE_OTEL_ENABLED
            value: "true"
          - name: DD_PROFILING_MIN_CORES_THRESHOLD
            value: '0.5'
          - name: DD_PROFILING_ALLOCATION_ENABLED
            value: 'true'  
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8443
              name: https
              protocol: TCP
          envFrom:
            - configMapRef:
                name: keycloak-env
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 1000m
              memory: 1Gi       
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 120
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /realms/master
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 120
            successThreshold: 1
            timeoutSeconds: 10
          volumeMounts:
            - mountPath: /etc/ssl
              name: tls-secret
              readOnly: true
      volumes:
        - name: tls-secret
          secret:
            defaultMode: 420
            secretName: tls-secret
```

### Version

26.0.0

### Regression

- [ ] The issue is a regression

### Expected behavior

I believe the error may be caused by read timeouts or connection resets from the identity provider integrated with Keycloak, specifically Microsoft AD and Okta. Are there any parameters that can be adjusted to mitigate this issue?

### Actual behavior

No 502 errors should be reported for the specified call.

GET /realms/{realm_name}/broker/{client_identity_provider_name}/endpoint

### How to Reproduce?

Please help us to resolve this issue
