### ISSUE TITLE
Add full Keycloak CR HPA example to docs

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#37306]
### Description

From #37223 it would be clearer to show a full HorizontalPodAutoscaler snippet [in the docs](https://www.keycloak.org/getting-started/getting-started-scaling-and-tuning).

**Comment by OS-emanuelbrici** [comment]
Here is an example I've used when testing

```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: keycloak-hpa
  namespace: keycloak-cluster
spec:
  scaleTargetRef:
    apiVersion: k8s.keycloak.org/v2alpha1
    kind: Keycloak
    name: keycloak
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
```
