### ISSUE TITLE
Change in unsupported spec did not update dependent resource

### ISSUE THREAD

**Issue by shawkins** [keycloak/keycloak#37322]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

After updating the unsupported spec args, the dependent resource was left unchanged.

### Version

26.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Changes to the unsupported spec should cause a full reconciliation.

### Actual behavior

If the pod resource was already created, the changes to the args were ignored.

### How to Reproduce?

Create a keycloak like:

```
  unsupported:
    podTemplate:
      spec:
        containers:
          - args:
              - start-dev2
```

Then change it to:

```
  unsupported:
    podTemplate:
      spec:
        containers:
          - args:
              - start-dev
```
