### ISSUE TITLE
HOSTNAME_ADMIN Not Being Applied to All Requests

### ISSUE THREAD

**Issue by kevingarman** [keycloak/keycloak#37892]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

Hi,

When I try to load the admin ui, it hangs and eventually fails.  Looking at the traffic, I see one request is using the KC_HOSTNAME rather than the KC_HOSTNAME_ADMIN.  The specific request is for step1.html.

![Image](https://github.com/user-attachments/assets/0eff50d2-3906-4ab9-aef9-386f6afd91fd)

### Version

26.1

### Regression

- [ ] The issue is a regression

### Expected behavior

Admin ui should fully load at KC_HOSTNAME_ADMIN url.

### Actual behavior

Admin ui doesn't load...

![Image](https://github.com/user-attachments/assets/0eff50d2-3906-4ab9-aef9-386f6afd91fd)

### How to Reproduce?

I am using the 26.1 docker image with the following docker compose....

```
services:
  keycloak-test:
    container_name: "keycloak-test"
    image: quay.io/keycloak/keycloak:26.1
    environment:
      KC_DB: dev-file
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: http://keycloak:8080
      KC_HOSTNAME_ADMIN: http://keycloakadmin:8080
      KC_LOG_LEVEL: info
      KC_HTTP_ENABLED: "true"
      KC_FEATURES_DISABLED: persistent-user-sessions
    command: start
    ports:
      - "0.0.0.0:8080:8080"
```

Opening http://keycloakadmin:8080 in my browser fails to load the admin ui fully.
