### ISSUE TITLE
Keycloak w/ Infinispan Operator cluster

### ISSUE THREAD

**Issue by Gearscry** [keycloak/keycloak#37924]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

Hello,

I'm facing to an issue when I try to make work together an single node Keycloak v26.1.3 and an external Infinispan cluster v15.0.3.Final thanks to Infinispan Operator v2.4.11.

I built my infinispan cluster with Helm, and create a custom cache configuration to align the initial configuration of keycloak cache : https://www.keycloak.org/server/caching#_configuring_caches

**Current Setup**

- Single site Keycloak
- cache-embedded-remote-store feature enable
- custom `cache-ispn.xml` file with specific transport conf : 
`<transport lock-timeout="60000" cluster="infinispan-cluster" stack="kubernetes" site="site1"/>`
- Keycloak deployed in Kubernetes (1 node)
- Infinispan deployed in Kubernetes (3 nodes)
- Confirmed that cluster nodes are configured properly and talking to each other (logs confirmation)

Keycloak configuration : 
```
- name: KC_CACHE_STACK
  value: kubernetes
- name: KC_CACHE
  value: ispn
- name: KC_CACHE_REMOTE_HOST
  value: infinispan-cluster.default.svc.cluster.local
- name: KC_CACHE_REMOTE_PORT
  value: "11222"
- name: KC_CACHE_REMOTE_USERNAME
  value: admin
- name: KC_CACHE_REMOTE_PASSWORD
  value: admin
- name: KC_CACHE_REMOTE_TLS_ENABLED
  value: "false"
- name: JAVA_OPTS_APPEND
  value: "-Djgroups.dns.query=infinispan-cluster-ping.default.svc.cluster.local"
```

Note : For KC_CACHE_STACK it's not mandatory because I already specify it in the transport conf in the xml config file.

### Version

26.1.3

### Regression

- [ ] The issue is a regression

### Expected behavior

Keycloak should start properly and working with external Infinispan cluster.

### Actual behavior

Keycloak starts and connects to the Infinispan servers. The cluster is well built and Keycloak start to put data in `work` cache. Then this error show off : 
```
2025-03-07 13:23:12,652 WARN  [org.infinispan.HOTROD] (HotRod-client-async-pool-8-38) ISPN004005: Error received from the server: org.infinispan.remoting.RemoteException: ISPN000217: Received exception from keycloak-7f95c6bcd5-84f59-53363(site-id=site1), see cause for remote stack trace
java.lang.IllegalArgumentException: Unknown type id : 11
2025-03-07 13:23:12,653 WARN  [org.keycloak.cluster.infinispan.InfinispanClusterProviderFactory] (main) Failed to write key 'cluster-start-time' and value '1741350167' in iteration '0' . Retrying: org.infinispan.client.hotrod.exceptions.HotRodClientException:Request for messageId=178 returned server error (status=0x85): org.infinispan.remoting.RemoteException: ISPN000217: Received exception from keycloak-7f95c6bcd5-84f59-53363(site-id=site1), see cause for remote stack trace
java.lang.IllegalArgumentException: Unknown type id : 11
```

What does id 11 refer to ? 
Could it be an issue about marshalling ? 
In both (Keycloak and Infinispan) they are using the `org.infinispan.commons.marshall.ImmutableProtoStreamMarshaller` 

### How to Reproduce?

For my test, I'm working with a fresh Keycloak in version 26.1.3 and a fresh Infinispan server in version 15.0.3 built with Infinispan Operator v2.4.11.

I have download and installed Infinispan Operator thanks to the OperatorHub : https://operatorhub.io/operator/infinispan
The mainly part of the Infinispan configuration is the default conf thanks to the Operator. Then I used Helm to build Infinispan CR : 

`infinispan-cluster.yaml`

```
apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: infinispan-cluster
  namespace: default
spec:
  replicas: {{ .Values.infinispan.replicas }}
  version: {{ .Values.infinispan.version }}
  security:
    endpointAuthentication: true
    endpointSecretName: infinispan-secret
  service:
    type: DataGrid
  configMapName: cluster-config
```

An configmap for custom cache definition : 

`infinispan-configmap.yaml`

```
apiVersion: v1
kind: ConfigMap
metadata:
   name: cluster-config
data:
   infinispan-config.xml: >
     <infinispan>
        <cache-container name="keycloak">
            <replicated-cache name="work" statistics="true">
                <encoding media-type="application/x-protostream" />
            </replicated-cache>

            <distributed-cache name="sessions" statistics="true">
                <encoding media-type="application/x-protostream" />
            </distributed-cache>

            <distributed-cache name="authenticationSessions" statistics="true">
                <encoding media-type="application/x-protostream" />
            </distributed-cache>

            <distributed-cache name="clientSessions" statistics="true">
                <encoding media-type="application/x-protostream" />
            </distributed-cache>

            <distributed-cache name="offlineSessions" statistics="true">
                <encoding media-type="application/x-protostream" />
            </distributed-cache>

            <distributed-cache name="offlineClientSessions" statistics="true">
                <encoding media-type="application/x-protostream" />
            </distributed-cache>

            <distributed-cache name="actionTokens" statistics="true">
                <encoding media-type="application/x-protostream" />
            </distributed-cache>

            <distributed-cache name="loginFailures" statistics="true">
                <encoding media-type="application/x-protostream" />
            </distributed-cache>
        </cache-container>
      </infinispan>
```

An secret for user credentials (this one will create an admin:admin access)  : 
```
apiVersion: v1
kind: Secret
metadata:
  name: infinispan-secret
type: Opaque
data:
  identities.yaml: |
    Y3JlZGVudGlhbHM6Ci0gdXNlcm5hbWU6IGFkbWluCiAgcGFzc3dvcmQ6IGFkbWluCg==
```

For Keycloak it's also an Helm configuration : 

`keycloak-deployment.yaml`

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "keycloak.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- range .Values.container.args }}
            - {{ . }}
            {{- end }}
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: {{ include "keycloak.fullname" . }}
                  key: {{ .Values.secret.key.admin.user }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "keycloak.fullname" . }}
                  key: {{ .Values.secret.key.admin.pwd }}
            - name: KC_DB_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "keycloak.fullname" . }}
                  key: {{ .Values.secret.key.db.url }}
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "keycloak.fullname" . }}
                  key: {{ .Values.secret.key.db.usr }}
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "keycloak.fullname" . }}
                  key: {{ .Values.secret.key.db.pwd }}
            - name: KC_DB
              value: {{ .Values.env.db }}
            - name: KC_DB_SCHEMA
              value: {{ .Values.env.dbSchema }}
            - name: KC_HOSTNAME
              value: {{ .Values.env.hostname}}
            - name: KC_HOSTNAME_ADMIN
              value: {{ .Values.env.hostnameAdmin}}
            - name: KC_HOSTNAME_BACKCHANNEL_DYNAMIC
              value: {{ .Values.env.hostnameStrictBackChannel | quote }}
            - name: KC_HEALTH_ENABLED
              value: {{ .Values.env.healthEnabled | quote }}
            - name: KC_HTTP_ENABLED
              value: {{ .Values.env.httpEnabled | quote }}
            - name: KC_CACHE_STACK
              value: kubernetes
            - name: KC_CACHE
              value: ispn
            - name: KC_CACHE_REMOTE_HOST
              value: infinispan-cluster.default.svc.cluster.local
            - name: KC_CACHE_REMOTE_PORT
              value: "11222"
            - name: KC_CACHE_REMOTE_USERNAME
              value: admin
            - name: KC_CACHE_REMOTE_PASSWORD
              value: admin
            - name: KC_CACHE_REMOTE_TLS_ENABLED
              value: "false"
            - name: JAVA_OPTS_APPEND
              value: "-Djgroups.dns.query=infinispan-cluster-ping.default.svc.cluster.local"
            - name: TZ
              value: {{ .Values.env.timezone | quote }}
          ports:
          - containerPort: {{ .Values.service.ports.http }}
            name: http
          - containerPort: {{ .Values.service.ports.management }}
            name: management
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
```

### Anything else?

The cluster in Keycloak and Infinispan is `infinispan-cluster` and the stack is obviously kubernetes. For Infinispan the stack name is `image-tcp` but it extends the kubernetes stack. Here is the JGroups configuration in Infinispan (I point out that is the default JGroups from Operator) : 
```
<jgroups>
    <stack name="image-tcp" extends="kubernetes">
        <!-- overwrite diagnostics-->
        <TCP diag.enabled="${jgroups.diag.enabled:false}" stack.combine="COMBINE" />
        <!-- overwrite DNS query (only required attribute) -->
        <dns.DNS_PING dns_query="${jgroups.dns.query:infinispan-cluster-ping.default.svc.cluster.local}" stack.combine="COMBINE" />
    </stack>
</jgroups>
```
Here is the full conf from Infinispan Operator if you want to take a look : 

[infinispan-cluster-configuration.log](https://github.com/user-attachments/files/19128620/infinispan-cluster-configuration.log)

In infinispan logs, I have clearly log that show an issue when Keycloak try to put data in `work` cache : 
```
12:19:33,060 ERROR (jgroups-11,infinispan-cluster-2-59442) [org.infinispan.interceptors.impl.InvocationContextInterceptor] ISPN000136: Error executing command PutKeyValueCommand on Cache 'work', writing keys [WrappedByteArray[\J12\c\l\u\s\t\e\r\-\s\t\a\r\t\-\t\i\m\e (20 bytes)]] org.infinispan.remoting.RemoteException: ISPN000217: Received exception from keycloak-7f95c6bcd5-84f59-38863(site-id=site1), see cause for remote stack trace
....
Caused by: java.lang.IllegalArgumentException: Unknown type id : 11
```
A funny things (not really) is that if my Infinispan cluster have X nodes, the data in `work` cache will be replicated in X-1 nodes : 

![Image](https://github.com/user-attachments/assets/cf67b8a9-6377-40df-95fd-36d66e9e355e)

![Image](https://github.com/user-attachments/assets/c50945f6-07d1-482e-adc4-9855cc154e07)

And if you have only 1 node in the Infinispan cluster, then the data will not be in the cache. 

Here's the full log for Keycloak startup and Infinispan node where the data is not replicated : 

[infinispan-cluster-2.log](https://github.com/user-attachments/files/19128547/infinispan-cluster-2.log)
[keycloak-singleNode.log](https://github.com/user-attachments/files/19128546/keycloak-singleNode.log)
