### ISSUE TITLE
431 Request Header Fields Too Large – Keycloak Token Size Issue

### ISSUE THREAD

**Issue by alexnuttinck** [keycloak/keycloak#38102]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

dist/quarkus

### Describe the bug

When running a terraform plan for our staging tenant keycloak.cloud.imio-test.be, we encounter the following error:

**Terraform Error**:

Planning failed. Terraform encountered an error while generating this plan.

```
╷
│ Error: error initializing keycloak provider
│ 
│   with provider["registry.terraform.io/keycloak/keycloak"],
│   on provider.tf line 24, in provider "keycloak":
│   24: provider "keycloak" {
│ 
│ failed to perform initial login to Keycloak: error sending GET request to
│ /admin/serverinfo: 431 Request Header Fields Too Large.
╵
ERRO[0012] terraform invocation failed in /home/anuttinck/workspace/gitlab/infra/keycloak/keycloak.tf/staging/keycloak.cloud.imio-test.be 
ERRO[0012] 1 error occurred:
	* [/home/anuttinck/workspace/gitlab/infra/keycloak/keycloak.tf/staging/keycloak.cloud.imio-test.be] exit status 1
```

The root cause appears to be that the access token for the Terraform client (created in the realm master) has grown too large, as it includes permissions for all realms (approximately 140 currently). This exceeds the HTTP header size limit.

**Keycloak Logs**

After setting the log level to "trace" in Keycloak, we observed the following error:

```
staging-kc-2 keycloak 2025-02-26 10:56:52,653 DEBUG [io.quarkus.micrometer.runtime.binder.vertx.VertxHttpServerMetrics] (vert.x-eventloop-thread-4) responseEnd io.vertx.core.http.impl.Http1xServerResponse@127797da, HttpRequestMetric [initialPath=/admin/serverinfo, currentRoutePath=null, templatePath=null, request=io.vertx.core.http.impl.Http1xServerRequest@5a3486e7]
staging-kc-2 keycloak 2025-02-26 10:56:52,653 TRACE [io.vertx.core.http.impl.HttpServerImpl] (vert.x-eventloop-thread-4) Connection failure: io.netty.handler.codec.http.TooLongHttpHeaderException: HTTP header is larger than 65535 bytes.
...
```

This log confirms that the error originates from Keycloak, specifically from the Quarkus Java framework. The issue is not caused by our NGINX reverse proxy.

**Troubleshooting Attempts**

* Adjusted configuration variables in the Keycloak Docker image and Keycloak Operator, following Quarkus documentation:
    https://quarkus.io/guides/all-config#quarkus-vertx-http_section_quarkus-http-limits
    → No effect; the error persists.
* Tried setting QUARKUS_HTTP_HTTP2=false
    → No effect.

**Next Steps / What We Haven't Tried Yet**

Using a configuration file instead of environment variables for Quarkus settings.

**Related GitHub Issues**

* Quarkus Issue #33692
* Keycloak Issue #13933

**Additional informations**

* We use the last version of Keycloak and of the Kubernetes Operator.

Would appreciate any guidance or potential fixes for this issue!

### Version

26.1.0

### Regression

- [ ] The issue is a regression

### Expected behavior

**Expected Outcome**

Keycloak should properly handle large access tokens or provide a way to mitigate this issue.

### Actual behavior

431 Request Header Fields Too Large error on /admin/serverinfo with the method grant_type=client_credentials and when there is too many realms.

### How to Reproduce?

- Create many realms. (more than 100?)
- Create a new client using the openid-connect protocol. This client is created in the master realm.
- Update the client you just created:
* Set Access Type to confidential.
* Set Standard Flow Enabled to OFF.
* Set Direct Access Grants Enabled to OFF
* Set Service Accounts Enabled to ON.
- Grant required roles for managing Keycloak via the Service Account Roles tab in the client you created.

Get the bearer token:
```
curl --location 'https://XXX/realms/master/protocol/openid-connect/token' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'client_id=XXX' \
--data-urlencode 'client_secret=XXX' \
--data-urlencode 'grant_type=client_credentials'
```

Get request on /serverinfo:
```
curl --location 'https://XXX/admin/serverinfo' \
--header 'Authorization: ••••••'
```

**Comment by alexnuttinck** [comment]
As a workaround, I go through a dedicated user with the admin role (inherited from the default "admin-cli" client), rather than through the created oidc client that inherits all roles from all realms.

**Comment by sschu** [comment]
@alexnuttinck Did you check out lightweight access tokens?

**Comment by alexnuttinck** [comment]
Thanks, @sschu! I wasn’t aware of that feature. It definitely seems like a solution to the root cause.

**Comment by jonkoops** [comment]
This is fixed by using lightweight access tokens, closing.

**Comment by alexnuttinck** [comment]
@shawkins yes, lightweight access tokens did the job. 
Maybe, the documentation about the keycloak terraform provider could improved, https://registry.terraform.io/providers/keycloak/keycloak/latest/docs#client-credentials-grant-setup-recommended , to mention this.
However, I was not able to modify the quarkus env variables with the keycloak operator, as described in the issue description. It  Or, I mean, putting env variables had no effect.

**Comment by shawkins** [comment]
> Or, I mean, putting env variables had no effect.

@alexnuttinck Just to make sure, can you provide explicitly what you tried? What might be happening is that Quarkus env properties won't be used if there is an existing value for them in a higher level config source - #38236 would address this.

**Comment by alexnuttinck** [comment]
Sure, Here is the keycloak tenant resource definition I tried, by using the podTemplate spec. 

I followed the [official documentation](https://www.keycloak.org/operator/advanced-configuration).

```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: staging-kc
spec:
  instances: 3
  image: harbor.imio.be/common/keycloak:77baa39f
  imagePullSecrets:
    - name: harbor-secret
  db:
    usernameSecret:
      name: keycloak-secret
      key: db_username
    passwordSecret:
      name: keycloak-secret
      key: db_password
    port: 5432
    database: common_keycloak
    host: 10.7.121.7
    vendor: postgres
  hostname:
    hostname: https://keycloak.cloud.imio-test.be
    admin: https://admin.keycloak.cloud.imio-test.be
  ingress:
    enabled: false
  http:
    httpEnabled: true
    tlsSecret: keycloak-secret-tls
  additionalOptions:
    - name: metrics-enabled 
      value: 'true'
    - name: log-level
      value: 'trace'
  features:
    enabled:
      - preview
  resources:
    requests:
      cpu: 500m
      memory: 1700Mi
    limits:
      memory: 2000Mi
  unsupported:
    podTemplate:
      spec:
        containers:
          - name: keycloak
            env:
              # https://quarkus.io/guides/all-config#quarkus-vertx-http_section_quarkus-http-limits
              - name: QUARKUS_HTTP_HTTP2
                value: "false"
              - name: QUARKUS_HTTP_LIMITS_MAX_HEADER_SIZE
                value: 200K
```

I also tried to pass these environment variables in our custom Dockerfile:

```
FROM quay.io/keycloak/keycloak:26.1.0 AS builder

# Enable health and metrics support
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=true
ENV KC_FEATURES=preview
# Configure a database vendor
ENV KC_DB=postgres
# Configure quarkus specific options
ENV QUARKUS_HTTP_LIMITS_MAX_HEADER_SIZE=200K
ENV QUARKUS_HTTP_HTTP2=false

# Add the provider JAR file to the providers directory
ADD --chown=keycloak:keycloak --chmod=644 https://github.com/aerogear/keycloak-metrics-spi/releases/download/7.0.0/keycloak-metrics-spi-7.0.0.jar /opt/keycloak/providers/keycloak-metrics-spi.jar
ADD --chown=keycloak:keycloak --chmod=644 imio-keycloak-themes* /opt/keycloak/providers/imio-keycloak-themes.jar
ADD --chown=keycloak:keycloak --chmod=644 keycloak-home-idp-discovery* /opt/keycloak/providers/keycloak-home-idp-discovery.jar

# Context: RUN the build command
RUN /opt/keycloak/bin/kc.sh build

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]

FROM quay.io/keycloak/keycloak:26.1.0

COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
```
