### ISSUE TITLE
Unable to activate user-event-metrics with optimized container image using the operator

### ISSUE THREAD

**Issue by oyviaase** [keycloak/keycloak#38249]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

operator

### Describe the bug

Keycloak fails to start the contianer when I try to activate user-event-metrics in an pre built image, where the feature already is enabled. 

### Version

26.1.3 also tested with latest wich is 26.1.4

### Regression

- [ ] The issue is a regression

### Expected behavior

The expected outcome is that keycloak should run and I should be able to collect the user-event-metrics

### Actual behavior

Keycloak crashes with the following error message
```
The following build time options have values that differ from what is persisted - the new values will NOT be used until another build is run: kc.spi-events-listener-micrometer-user-event-metrics-enabled
```

### How to Reproduce?

The container image used for testing is built using the following Containerfile
```
from quay.io/keycloak/keycloak:latest as builder
# enable health and metrics support
env kc_health_enabled=true
env kc_metrics_enabled=true
env kc_tracing_enabled=true
env kc_event_metrics_user_enabled=true

# configure a database vendor
env kc_db=postgres

workdir /opt/keycloak
run /opt/keycloak/bin/kc.sh build --features="user-event-metrics"

from quay.io/keycloak/keycloak:latest
copy --from=builder /opt/keycloak/ /opt/keycloak/

# change these values to point to a running postgres instance
entrypoint ["/opt/keycloak/bin/kc.sh"]
```

The operator configuration that's used:
```yaml
apiVersion: v1
items:
- apiVersion: k8s.keycloak.org/v2alpha1
  kind: Keycloak
  metadata:
    name: keycloak
  spec:
    additionalOptions:
    - name: cache-stack
      value: kubernetes
    - name: metrics-enabled
      value: "true"
    - name: event-metrics-user-enabled
      value: "true"
    - name: event-metrics-user-tags
      value: realm,idp,clientId
    image: local-registry/keycloak:latest
    imagePullSecrets:
    - name: keycloak-image-pull-secret
    ingress:
      annotations:
        haproxy.router.openshift.io/balance: roundrobin
        haproxy.router.openshift.io/disable_cookies: "true"
      className: openshift-default
    instances: 1
    startOptimized: true
```
The configuration is missing the database and ingress configuration.
