### ISSUE TITLE
A realm created on v24 migrated to v26 have improperly configured organization when enabled.

### ISSUE THREAD

**Issue by jbzellerEudo** [keycloak/keycloak#38258]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

organizations

### Describe the bug

When I try to enable organization on a realm created from in a v24.0.5 version of keycloak, the v26.1.4 version of keycloak will not add the organization scope nor will it alter the browser login flow.

When I look at the client scope list, organization is not there. And the browser flow hasn't been altered to add organization into the mix.

I am using a postgresql database if that matters.

### Version

26.1.4 from 24.0.5

### Regression

- [ ] The issue is a regression

### Expected behavior

The organization switch enable all the bells and whistles.

![Image](https://github.com/user-attachments/assets/70dd7d65-94f3-4aa9-88d2-4c3fc1eff43c)

![Image](https://github.com/user-attachments/assets/de0461c8-8f59-47d6-9c6a-df2ea4b0377b)

### Actual behavior

The organization does not have the client scopes nor does it has the altered browser flow.

![Image](https://github.com/user-attachments/assets/e692c38e-a5a0-4982-a936-016a1dd648e8)

![Image](https://github.com/user-attachments/assets/a5ca670b-9306-4fec-84fe-7e1b0e0bb2e0)

### How to Reproduce?

I used a docker compose script to quickly reproduce the problem.

1. run this script with `docker compose up`
```yaml
services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data_migrate:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    environment:
      KC_LOG_LEVEL: info
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD : mycoolpassword
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/postgres
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    ports:
      - 8080:8080
    command: start-dev
    depends_on:
      - postgres
```
2. Connect to keycloak with http://localhost:8080 and create a realm then stop the cluster.
3. Edit the yaml to change the line :
`    image: quay.io/keycloak/keycloak:24.0`
to
`    image: quay.io/keycloak/keycloak:latest`
4. run docker compose pull to pull the latest version.
5. run docker compose up
6. connect to keycloak again, go to the previously created realm. Then enable organization on said realm.
