### ISSUE TITLE
Memory leak when updating LDAP federated user (join groups / update attributes)

### ISSUE THREAD

**Issue by EnvyIT** [keycloak/keycloak#38477]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ldap

### Environment Details

Keycloak Version: 26.1.4
Admin-Client-API (Java) : { module = "org.keycloak:keycloak-admin-client", version = "26.0.4" }
Docker Version: 28.0.4, build b8034c0
Operating System: Ubuntu 24.04.2 LTS

### Problem Description

Our custom application syncs LDAP federated users to our system and we enrich them via Keycloak Admin Client with groups and user attributes. (~200 Users)

The sync runs every hour. We experience now an increase of memory consumption in our Keycloak docker container which is not  released during GC.

### Version

26.1.4

### Regression

- [ ] The issue is a regression

### Expected behavior

No memory leak

### Actual behavior

The Keycloak Docker container experiences consistent memory growth, even when limited to 4GB, without releasing memory when the container is stopped.

Initially:
![Image](https://github.com/user-attachments/assets/94e87b86-7d16-411b-aa6d-ad16c4853d00)

After 3 Sync runs - memory drastically increased in Keycloak container:
![Image](https://github.com/user-attachments/assets/651aab62-c1d0-4297-be28-811eca1fae47)

**Log output** 

Running our container with GC Logs we saw that o**ld regions constantly grow**

```
[942.361s][info   ][gc,start    ] GC(61) Pause Young (Prepare Mixed) (G1 Evacuation Pause)
[942.361s][info   ][gc,task     ] GC(61) Using 23 workers of 23 for evacuation
[942.537s][info   ][gc,phases   ] GC(61)   Pre Evacuate Collection Set: 1.3ms
[942.537s][info   ][gc,phases   ] GC(61)   Merge Heap Roots: 0.4ms
[942.537s][info   ][gc,phases   ] GC(61)   Evacuate Collection Set: 166.5ms
[942.537s][info   ][gc,phases   ] GC(61)   Post Evacuate Collection Set: 7.1ms
[942.537s][info   ][gc,phases   ] GC(61)   Other: 0.1ms
[942.537s][info   ][gc,heap     ] GC(61) Eden regions: 549->0(495)
[942.537s][info   ][gc,heap     ] GC(61) Survivor regions: 40->74(74)
[942.537s][info   ][gc,heap     ] GC(61) Old regions: 1293->1302
[942.537s][info   ][gc,heap     ] GC(61) Humongous regions: 0->0
[942.537s][info   ][gc,metaspace] GC(61) Metaspace: 137458K(138880K)->137458K(138880K) NonClass: 121087K(121664K)->121087K(121664K) Class: 16370K(17216K)->16370K(17216K)
[942.537s][info   ][gc          ] GC(61) Pause Young (Prepare Mixed) (G1 Evacuation Pause) 3763M->2751M(4096M) 175.478ms
[942.537s][info   ][gc,cpu      ] GC(61) User=0.33s Sys=2.70s Real=0.17s
```

### Reproduction Steps

1. Start Keycloak Docker container in version 26.1.4
2. Configure LDAP federation
4. Automatically update multiple users every hour with (groups and user defined attributes)
3. Observe memory usage over time
4. Stop the container
5. Check system memory allocation

### Docker Compose / Run Configuration

```
services:

  keycloak-db:
    image: postgres:17.4-alpine
    container_name: ${KEYCLOAK_DB_CONTAINER_NAME}
    volumes:
      - keycloak_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_DATABASE_NAME}
      POSTGRES_USER: ${KEYCLOAK_DATABASE_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
    ports:
      - ${KEYCLOAK_EXPOSED_PORT}:5432
    restart: always

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - "keycloak"
      args:
        KEYCLOAK_VERSION: 26.1.4
    container_name: "keycloak"
    ports:
      - "8180:8080"
      - "8181:9000"
    mem_limit: 4G
    mem_reservation: 2G
    environment:
      JAVA_TOOL_OPTIONS: |
        -Xms2g -Xmx4g
        -XX:+UseG1GC
        -XX:MaxGCPauseMillis=200
        -XX:ParallelGCThreads=8
        -XX:+UseGCOverheadLimit
        -XX:MetaspaceSize=256m
        -XX:MaxMetaspaceSize=512m
        -Xlog:gc*:file=/opt/keycloak/gc.log
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://${KEYCLOAK_DB_CONTAINER_NAME}/${KEYCLOAK_DATABASE_NAME}
      KC_DB_USERNAME: ${KEYCLOAK_DATABASE_USER}
      KC_DB_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
    command:
      - start-dev
      - --import-realm
      - --hostname-strict=false
      - --http-enabled=true
      - --spi-theme-static-max-age=-1
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
    depends_on:
      - keycloak-db
      - mailpit
    restart: always

  mailpit:
    image: axllent/mailpit:v1.23.0@sha256:dd3d5b10e82aab5da337f8f1a9d7ae5d65dca5b00c43f75682fa8e8e71c1fb82
    container_name: "mailpit"
    restart: always
    ports:
      - ${SMTP_PORT}:1025
      - ${MAILPIT_PORT}:8025

volumes:
  keycloak_data:
    driver: local
```

### 
LDAP Configuration:

![Image](https://github.com/user-attachments/assets/03eb3706-f13b-4c53-9b21-b8b2f0f05218)

![Image](https://github.com/user-attachments/assets/c082ab33-cc08-4b9f-a483-6c70af5d78ad)

![Image](https://github.com/user-attachments/assets/2a48fa07-1331-4e86-adae-d91855487cf1)

![Image](https://github.com/user-attachments/assets/d40a5b06-0b18-41e4-8ab7-f8427a9e203a)
