### ISSUE TITLE
Ansible: Invalid provider type or no such provider

### ISSUE THREAD

**Issue by mandalorian9** [keycloak/keycloak#38895]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

authentication

### Describe the bug

Using an ansible module we are not able to add a KeyProvider, receiving a following error:
```
TASK [keycloak_config_prod : Add RSA Key Provider with RS512 algorithm to Keycloak Realm] ************************************************************************************************
fatal: [keycloak_prod_us]: FAILED! => changed=false 
  msg: 'Could not create component in realm auth: HTTP Error 400: Bad Request: {"error":"Invalid provider type or no such provider"}'
```

Ansible task:
```
- name: Add RSA Key Provider with RS512 algorithm to Keycloak Realm
  community.general.keycloak_component:
    auth_client_id: admin-cli
    auth_keycloak_url: "{{ apps.keycloak.auth_keycloak_url_local }}"
    auth_realm: master
    auth_username: "{{ kc_admin_user }}"
    auth_password: "{{ kc_admin_password }}"
    name: "rsa-2048-key-rs512-algo-provider"
    state: present
    parent_id: "{{ apps.keycloak.realms.auth.name }}"
    provider_id: "rsa-rs512-provider"
    provider_type: "org.keycloak.keys.KeyProvider"
```

When I use rest api to obtain current realm providers, I can see:
```
{
    "id": "d04d5502-dcdb-4429-9859-aae398460c5f",
    "name": "rsa-enc-generated",
    "providerId": "rsa-enc-generated",
    "providerType": "org.keycloak.keys.KeyProvider",
    "parentId": "auth",
    "config": {
      "priority": [
        "100"
      ],
      "algorithm": [
        "RSA-OAEP"
      ]
    }
  }
```

So the provider type `org.keycloak.keys.KeyProvider` but the API says otherwise.
I tried also to create the provider using `uri` module, but no luck, get the same error.

### Version

26.1.3

### Regression

- [ ] The issue is a regression

### Expected behavior

IssueType provider is accepted and record is created.

### Actual behavior

```
HTTP Error 400: Bad Request: {"error":"Invalid provider type or no such provider"}'
```

### How to Reproduce?

As above in the description
