### ISSUE TITLE
Keycloak 26.2.0 UI Performance Degradation

### ISSUE THREAD

**Issue by VonNao** [keycloak/keycloak#39023]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

admin/ui

### Describe the bug

We have Deployt keycloak via the Keycloak Operator on our Cluster. After updateing from Keycloak 26.1.2 to 26.2.0 Keycloak seems to be kinda slow. UI Operations aswell aus Authentication seem to be a slower.

For our Setup:

We got around 150 LDAP federations against our Active directory. 
We deployed it on k8s via the operator and got cnpg as postgres-cluster. Metrics show that none of the systems is anywhere near utilization. 

### Version

26.2.0

### Regression

- [ ] The issue is a regression

### Expected behavior

Responsiveness as of patch 26.1.x 

### Actual behavior

Degredation is responsivness in regards of ui oprations.

### How to Reproduce?

Install keycloak 26.2.0 manage groups etc. via Webinterface

**Comment by ahus1** [comment]
Could you try to enable tracing as described in https://www.keycloak.org/observability/tracing and provide a trace? If you are using Jaeger, you could either provide a screenshot, or export the trace as a JSON. 

As an alternative, you could provide a thread dump of a Keycloak node under load, still that is usually less helpful.

**Comment by VonNao** [comment]
Sorry for the late response. I could narrow the "problem" down. The Slugish ui only is noticable in our keycloak operator deployments. Single node dev instances work as fast as ever. 

The infrastructure around the k8s operator deployment did not change from 26.1 to 26.2 is it possible that session affinity could be a thing? 

Our Ingress Controller ist Nginx-Ingress with the following annotations.
```
nginx.ingress.kubernetes.io/backend-protocol: "https"
cert-manager.io/cluster-issuer: "letsencrypt-production"
cert-manager.io/private-key-rotation-policy: Always
cert-manager.io/private-key-algorithm: "ECDSA"
cert-manager.io/private-key-size: "384"
```

**Comment by ahus1** [comment]
@VonNao - As we describe in our docs, Jaeger could be run as a Pod on Kubernetes like any other, similar on how you deploy Keycloak today. While in a production environment you would want all applications to send their traces to Jaeger, it might be enough for a test environment for just Keycloak to send its logs to this test instance of Jaeger.

**Comment by ssilvert** [comment]
@VonNao @ahus1 Can this one be closed or moved to a different team?  Or do we think there is a UI bug?

**Comment by ssilvert** [comment]
Closing due to lack of recent interest.  We can reopen if needed.

**Comment by VonNao** [comment]
@ssilvert Sorry for the late response. Jaeger is up and running. Following are some screenshots from the traces. Tested with normal ser actions form perspective of a administrator. Some Events just need a really long Time 4s+ to finish. As in another issue mentioned when scaling down to one instance the performance is like 26.1 and earlier. 

![Image](https://github.com/user-attachments/assets/e8b8dddd-a8dc-4da1-8ec2-24f0b81460c7)

![Image](https://github.com/user-attachments/assets/b94fb59f-474b-4e38-bc1d-2b5ee1d84cd8)

![Image](https://github.com/user-attachments/assets/cbf361ff-be8e-4ec5-85ad-652ebfe8cb8e)

This last Screenshot is from a login test from a user 

![Image](https://github.com/user-attachments/assets/6d13fff5-6a70-4693-b3d8-1a5eec9d310c)

Since with one instance there is no problem i would guess that it has something to do with the infinispan cluster?

If you need more information hook me up.

**Comment by ahus1** [comment]
@VonNao - thank you for the screenshots. The long black bar is each time on `InfinispanChangeLogBasedTransaction.commit`. That's something we need to investigate. 

As you say you are using the Operator, please share your Keycloak CR. I especially wonder what resource limits you might have set for Keycloak. Thanks!

BTW: The screenshots are readable, but quite small. Can you please click in upper right corner to archive a trace? This should give you a JSON download. It would be great it you could that it with us. Thanks!

**Comment by ahus1** [comment]
@srekkas - can you please share your configuration (Keycloak CR if you are using the Operator), especially the CPU requests limits you are using?

**Comment by srekkas** [comment]
> [@srekkas](https://github.com/srekkas) - can you please share your configuration (Keycloak CR if you are using the Operator), especially the CPU requests limits you are using?

yes, this is our CR, we are using operator.

```
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: <name>-prod
  namespace: <name>
  labels:
    app: <name>-prod
    app.kubernetes.io/instance: <name>
spec:
  imagePullSecrets:
    - name: <name>-regcred
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi
  startOptimized: true
  http:
    httpEnabled: false
    httpsPort: 8443
    tlsSecret: <name>-prod-cert
  hostname:
    hostname: <hostname>
  unsupported:
    podTemplate:
      spec:
        containers:
          - env:
              - name: KC_LOG_LEVEL
                value: INFO
  ingress:
    enabled: false
  additionalOptions:
    - name: http-max-queued-requests
      value: '1000'
    - name: http-pool-max-threads
      value: '66'
  image: '<reg>:5050/<name>/<name>-containers/<name>:26.2.3'
  db:
    passwordSecret:
      key: password
      name: <name>-prod-pg-app
    poolInitialSize: 30
    poolMaxSize: 30
    poolMinSize: 30
    url: 'jdbc:postgresql://<name>-prod-pg-rw:5432/<name>-prod-db'
    usernameSecret:
      key: username
      name: <name>-prod-pg-app
    vendor: postgres
  instances: 3
```

**Comment by ahus1** [comment]
I am still investigating this. For the time being, my best guess is to change the CPU limit to 2000m or 3000m. 

I suppose we are running into a virtual thread problem. With a limit of 2 or 3 vCPUs, Java will for a thread pool of 3, while it would otherwise only start a thread pool of 1 which might be the cause of the problems. 

Again, I'm still investigating this.

**Comment by wkloucek** [comment]
We see the same issue during load tests.

We have a CPU request of 14 cores and no CPU limit set.

When we decrease the Keycloak replicas from 3 to only 1, we see consistently fast Infinispan transaction commit times.

**Comment by VonNao** [comment]
> > Since with one instance there is no problem i would guess that it has something to do with the infinispan cluster?
> 
> Are you running Keycloak with an external Infinispan cluster?

We use the profided infinispan from the keycloak image itself. I will profide the traces from asap

**Comment by wkloucek** [comment]
Our Keycloak 26.2.2 setup with builtin Infinispan looks like this:

<details>

```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
...
spec:
  additionalOptions:
  - name: http-max-queued-requests
    value: "10000"
  - name: http-pool-max-threads
    value: "56"
  - name: log
    value: console
  - name: log-level
    value: error
  - name: log-console-output
    value: json
  - name: log-console-include-trace
    value: "true"
  - name: metrics-enabled
    value: "true"
  - name: http-metrics-histograms-enabled
    value: "true"
  - name: event-metrics-user-enabled
    value: "true"
  - name: tracing-enabled
    value: "true"
  - name: tracing-protocol
    value: grpc
  - name: tracing-endpoint
    value: http://grafana-agent-rules.grafana-agent-rules.svc:4317
  - name: tracing-jdbc-enabled
    value: "true"
  - name: tracing-sampler-ratio
    value: "1.0"
  - name: tracing-sampler-type
    value: parentbased_traceidratio
  - name: spi-connections-http-client-default-socket-timeout-millis
    value: "10000"
  - name: spi-connections-http-client-default-connection-pool-size
    value: "10000"
  - name: spi-connections-http-client-default-max-pooled-per-route
    value: "10000"
  - name: cache-embedded-authorization-max-count
    value: "10000000"
  - name: cache-embedded-client-sessions-max-count
    value: "10000000"
  - name: cache-embedded-users-max-count
    value: "10000000"
  - name: cache-embedded-sessions-max-count
    value: "10000000"
  - name: cache-embedded-offline-client-sessions-max-count
    value: "10000000"
  - name: cache-embedded-offline-sessions-max-count
    value: "10000000"
  - name: cache-embedded-realms-max-count
    value: "10000"
  - name: cache-embedded-crl-max-count
    value: "10000"
  - name: cache-embedded-keys-max-count
    value: "10000"
  db:
    database: keycloak
    host: pgkeycloak
    passwordSecret:
      key: password
      name: keycloak.pgkeycloak.credentials.postgresql.acid.zalan.do
    poolInitialSize: 100
    poolMaxSize: 100
    poolMinSize: 100
    usernameSecret:
      key: username
      name: keycloak.pgkeycloak.credentials.postgresql.acid.zalan.do
  features:
    disabled:
    - impersonation
    - persistent-user-sessions
  hostname:
    admin: xxx
    backchannelDynamic: false
    hostname: xxx
    strict: true
  http:
    httpEnabled: false
    tlsSecret: xxx-tls
  image: docker-proxy.xxx/xxx/keycloak:26.2.2
  ingress:
    annotations:
     ...
    enabled: true
  instances: 3
  proxy:
    headers: xforwarded
  resources:
    limits:
      memory: 24Gi
    requests:
      cpu: "14"
      memory: 24Gi
  scheduling:
    priorityClassName: high-priority
    topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/component: server
          app.kubernetes.io/instance: keycloak
          app.kubernetes.io/managed-by: keycloak-operator
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
  unsupported:
    podTemplate:
      metadata:
        labels:
          velero.io/exclude-from-backup: "true"
      spec:
        containers:
        - env:
          - name: JAVA_OPTS_APPEND
            value: -Xms2g -Xmx20g -Dcom.sun.jndi.ldap.connect.pool.initsize=100 -Dcom.sun.jndi.ldap.connect.pool.maxsize=10000
              -Dcom.sun.jndi.ldap.connect.pool.timeout=10000 -Dcom.sun.jndi.ldap.connect.pool.protocol="plain
              ssl"
          imagePullPolicy: IfNotPresent
  update:
    strategy: Auto
```
</details>

This is a trace taken during loadtests:

<details>

![Image](https://github.com/user-attachments/assets/8695267f-6d1d-4622-89d9-e8f7b47491a2)

```json
{
    "batches": [
        {
            "resource": {
                "attributes": [
                    {
                        "key": "host.name",
                        "value": {
                            "stringValue": "keycloak-1"
                        }
                    },
                    {
                        "key": "service.version",
                        "value": {
                            "stringValue": "26.2.2"
                        }
                    },
                    {
                        "key": "telemetry.sdk.language",
                        "value": {
                            "stringValue": "java"
                        }
                    },
                    {
                        "key": "telemetry.sdk.name",
                        "value": {
                            "stringValue": "opentelemetry"
                        }
                    },
                    {
                        "key": "telemetry.sdk.version",
                        "value": {
                            "stringValue": "1.44.1"
                        }
                    },
                    {
                        "key": "webengine.name",
                        "value": {
                            "stringValue": "Quarkus"
                        }
                    },
                    {
                        "key": "webengine.version",
                        "value": {
                            "stringValue": "3.20.0"
                        }
                    },
                    {
                        "key": "service.name",
                        "value": {
                            "stringValue": "keycloak"
                        }
                    },
                    {
                        "key": "k8s.namespace.name",
                        "value": {
                            "stringValue": "central-idm"
                        }
                    }
                ],
                "droppedAttributesCount": 0
            },
            "instrumentationLibrarySpans": [
                {
                    "spans": [
                        {
                            "traceId": "141ab4ce42247c32ef11309f5a543f37",
                            "spanId": "9018df20c4679396",
                            "parentSpanId": "0000000000000000",
                            "traceState": "",
                            "name": "GET /realms/{realm}/broker/{provider_alias}/login",
                            "kind": "SPAN_KIND_SERVER",
                            "startTimeUnixNano": 1746594278313009000,
                            "endTimeUnixNano": 1746594289859036200,
                            "attributes": [
                                {
                                    "key": "kc.realmName",
                                    "value": {
                                        "stringValue": "xxx"
                                    }
                                },
                                {
                                    "key": "code.function",
                                    "value": {
                                        "stringValue": "performLogin"
                                    }
                                },
                                {
                                    "key": "user_agent.original",
                                    "value": {
                                        "stringValue": "k6/1.0.0-rc1 (https://k6.io/)"
                                    }
                                },
                                {
                                    "key": "http.response.status_code",
                                    "value": {
                                        "intValue": 303
                                    }
                                },
                                {
                                    "key": "url.scheme",
                                    "value": {
                                        "stringValue": "https"
                                    }
                                },
                                {
                                    "key": "kc.authenticationTabId",
                                    "value": {
                                        "stringValue": "_dBgbSmmPhA"
                                    }
                                },
                                {
                                    "key": "http.request.method",
                                    "value": {
                                        "stringValue": "GET"
                                    }
                                },
                                {
                                    "key": "http.route",
                                    "value": {
                                        "stringValue": "/realms/{realm}/broker/{provider_alias}/login"
                                    }
                                },
                                {
                                    "key": "server.address",
                                    "value": {
                                        "stringValue": "auth.xxx"
                                    }
                                },
                                {
                                    "key": "client.address",
                                    "value": {
                                        "stringValue": "xxx"
                                    }
                                },
                                {
                                    "key": "url.query",
                                    "value": {
                                        "stringValue": "session_code=IhICpkTLMBAw7B6xlX7zPdteDbo0ceZKdbpdu8ctkzU&client_id=xxx-web&tab_id=_dBgbSmmPhA&client_data=eyJydSI6Imh0dHBzOi8vOTEwMDEuZHJpdmUuY2xvdWRzcGVpY2hlci1iYXllcm4uZGUvb2lkYy1jYWxsYmFjay5odG1sIiwicnQiOiJjb2RlIiwic3QiOiI4MDEyYzQzZS03ZmU4LTRlODUtYTEyYi1iNGE1MDdlNDcwNWEifQ"
                                    }
                                },
                                {
                                    "key": "kc.clientId",
                                    "value": {
                                        "stringValue": "xxx-web"
                                    }
                                },
                                {
                                    "key": "url.path",
                                    "value": {
                                        "stringValue": "/realms/xxx/broker/upstream-idp/login"
                                    }
                                },
                                {
                                    "key": "code.namespace",
                                    "value": {
                                        "stringValue": "org.keycloak.services.resources.IdentityBrokerService"
                                    }
                                },
                                {
                                    "key": "http.response.body.size",
                                    "value": {
                                        "intValue": 0
                                    }
                                },
                                {
                                    "key": "kc.authenticationSessionId",
                                    "value": {
                                        "stringValue": "4ca7579f-06ec-42ca-b6f9-c02393aad1c8"
                                    }
                                },
                                {
                                    "key": "cluster",
                                    "value": {
                                        "stringValue": "xxx"
                                    }
                                },
                                {
                                    "key": "datacenter",
                                    "value": {
                                        "stringValue": "xxx"
                                    }
                                }
                            ],
                            "droppedAttributesCount": 0,
                            "droppedEventsCount": 0,
                            "droppedLinksCount": 0,
                            "status": {
                                "code": 0,
                                "message": ""
                            }
                        }
                    ],
                    "instrumentationLibrary": {
                        "name": "io.quarkus.opentelemetry",
                        "version": ""
                    }
                }
            ]
        },
        {
            "resource": {
                "attributes": [
                    {
                        "key": "host.name",
                        "value": {
                            "stringValue": "keycloak-1"
                        }
                    },
                    {
                        "key": "service.version",
                        "value": {
                            "stringValue": "26.2.2"
                        }
                    },
                    {
                        "key": "telemetry.sdk.language",
                        "value": {
                            "stringValue": "java"
                        }
                    },
                    {
                        "key": "telemetry.sdk.name",
                        "value": {
                            "stringValue": "opentelemetry"
                        }
                    },
                    {
                        "key": "telemetry.sdk.version",
                        "value": {
                            "stringValue": "1.44.1"
                        }
                    },
                    {
                        "key": "webengine.name",
                        "value": {
                            "stringValue": "Quarkus"
                        }
                    },
                    {
                        "key": "webengine.version",
                        "value": {
                            "stringValue": "3.20.0"
                        }
                    },
                    {
                        "key": "service.name",
                        "value": {
                            "stringValue": "keycloak"
                        }
                    },
                    {
                        "key": "k8s.namespace.name",
                        "value": {
                            "stringValue": "central-idm"
                        }
                    }
                ],
                "droppedAttributesCount": 0
            },
            "instrumentationLibrarySpans": [
                {
                    "spans": [
                        {
                            "traceId": "141ab4ce42247c32ef11309f5a543f37",
                            "spanId": "26f7265c4ccab892",
                            "parentSpanId": "9018df20c4679396",
                            "traceState": "",
                            "name": "RealmsResource.getBrokerService",
                            "kind": "SPAN_KIND_INTERNAL",
                            "startTimeUnixNano": 1746594278521833500,
                            "endTimeUnixNano": 1746594278521969000,
                            "attributes": [
                                {
                                    "key": "code.function",
                                    "value": {
                                        "stringValue": "getBrokerService"
                                    }
                                },
                                {
                                    "key": "code.namespace",
                                    "value": {
                                        "stringValue": "org.keycloak.services.resources.RealmsResource"
                                    }
                                },
                                {
                                    "key": "cluster",
                                    "value": {
                                        "stringValue": "xxx"
                                    }
                                },
                                {
                                    "key": "datacenter",
                                    "value": {
                                        "stringValue": "xxx"
                                    }
                                }
                            ],
                            "droppedAttributesCount": 0,
                            "droppedEventsCount": 0,
                            "droppedLinksCount": 0,
                            "status": {
                                "code": 0,
                                "message": ""
                            }
                        },
                        {
                            "traceId": "141ab4ce42247c32ef11309f5a543f37",
                            "spanId": "608985773e507e70",
                            "parentSpanId": "9018df20c4679396",
                            "traceState": "",
                            "name": "IdentityBrokerService.performLogin",
                            "kind": "SPAN_KIND_INTERNAL",
                            "startTimeUnixNano": 1746594278522017800,
                            "endTimeUnixNano": 1746594278530256000,
                            "attributes": [
                                {
                                    "key": "code.function",
                                    "value": {
                                        "stringValue": "performLogin"
                                    }
                                },
                                {
                                    "key": "code.namespace",
                                    "value": {
                                        "stringValue": "org.keycloak.services.resources.IdentityBrokerService"
                                    }
                                },
                                {
                                    "key": "cluster",
                                    "value": {
                                        "stringValue": "xxx"
                                    }
                                },
                                {
                                    "key": "datacenter",
                                    "value": {
                                        "stringValue": "xxx"
                                    }
                                }
                            ],
                            "droppedAttributesCount": 0,
                            "droppedEventsCount": 0,
                            "droppedLinksCount": 0,
                            "status": {
                                "code": 0,
                                "message": ""
                            }
                        },
                        {
                            "traceId": "141ab4ce42247c32ef11309f5a543f37",
                            "spanId": "48dde614532a8e41",
                            "parentSpanId": "9018df20c4679396",
                            "traceState": "",
                            "name": "RealmCacheSession$1.commit",
                            "kind": "SPAN_KIND_INTERNAL",
                            "startTimeUnixNano": 1746594278530320600,
                            "endTimeUnixNano": 1746594278530329600,
                            "attributes": [
                                {
                                    "key": "cluster",
                                    "value": {
                                        "stringValue": "xxx"
                                    }
                                },
                                {
                                    "key": "datacenter",
                                    "value": {
                                        "stringValue": "xxx"
                                    }
                                }
                            ],
                            "droppedAttributesCount": 0,
                            "droppedEventsCount": 0,
                            "droppedLinksCount": 0,
                            "status": {
                                "code": 0,
                                "message": ""
                            }
                        },
                        {
                            "traceId": "141ab4ce42247c32ef11309f5a543f37",
                            "spanId": "bd1fb36f55480019",
                            "parentSpanId": "9018df20c4679396",
                            "traceState": "",
                            "name": "JtaTransactionWrapper.commit",
                            "kind": "SPAN_KIND_INTERNAL",
                            "startTimeUnixNano": 1746594278530339000,
                            "endTimeUnixNano": 1746594278530398500,
                            "attributes": [
                                {
                                    "key": "cluster",
                                    "value": {
                                        "stringValue": "xxx"
                                    }
                                },
                                {
                                    "key": "datacenter",
                                    "value": {
                                        "stringValue": "xxx"
                                    }
                                }
                            ],
                            "droppedAttributesCount": 0,
                            "droppedEventsCount": 0,
                            "droppedLinksCount": 0,
                            "status": {
                                "code": 0,
                                "message": ""
                            }
                        },
                        {
                            "traceId": "141ab4ce42247c32ef11309f5a543f37",
                            "spanId": "7e9a47f744e0ff23",
                            "parentSpanId": "9018df20c4679396",
                            "traceState": "",
                            "name": "RollbackDrivenTransaction.commit",
                            "kind": "SPAN_KIND_INTERNAL",
                            "startTimeUnixNano": 1746594278530408200,
                            "endTimeUnixNano": 1746594278530413600,
                            "attributes": [
                                {
                                    "key": "cluster",
                                    "value": {
                                        "stringValue": "xxx"
                                    }
                                },
                                {
                                    "key": "datacenter",
                                    "value": {
                                        "stringValue": "xxx"
                                    }
                                }
                            ],
                            "droppedAttributesCount": 0,
                            "droppedEventsCount": 0,
                            "droppedLinksCount": 0,
                            "status": {
                                "code": 0,
                                "message": ""
                            }
                        },
                        {
                            "traceId": "141ab4ce42247c32ef11309f5a543f37",
                            "spanId": "e4dc3e9acc91b1f8",
                            "parentSpanId": "9018df20c4679396",
                            "traceState": "",
                            "name": "RollbackDrivenTransaction.commit",
                            "kind": "SPAN_KIND_INTERNAL",
                            "startTimeUnixNano": 1746594278530418700,
                            "endTimeUnixNano": 1746594278530424600,
                            "attributes": [
                                {
                                    "key": "cluster",
                                    "value": {
                                        "stringValue": "xxx"
                                    }
                                },
                                {
                                    "key": "datacenter",
                                    "value": {
                                        "stringValue": "xxx"
                                    }
                                }
                            ],
                            "droppedAttributesCount": 0,
                            "droppedEventsCount": 0,
                            "droppedLinksCount": 0,
                            "status": {
                                "code": 0,
                                "message": ""
                            }
                        },
                        {
                            "traceId": "141ab4ce42247c32ef11309f5a543f37",
                            "spanId": "7e6f27bc0939a771",
                            "parentSpanId": "9018df20c4679396",
                            "traceState": "",
                            "name": "RealmCacheSession$2.commit",
                            "kind": "SPAN_KIND_INTERNAL",
                            "startTimeUnixNano": 1746594278530430000,
                            "endTimeUnixNano": 1746594278530441700,
                            "attributes": [
                                {
                                    "key": "cluster",
                                    "value": {
                                        "stringValue": "xxx"
                                    }
                                },
                                {
                                    "key": "datacenter",
                                    "value": {
                                        "stringValue": "xxx"
                                    }
                                }
                            ],
                            "droppedAttributesCount": 0,
                            "droppedEventsCount": 0,
                            "droppedLinksCount": 0,
                            "status": {
                                "code": 0,
                                "message": ""
                            }
                        },
                        {
                            "traceId": "141ab4ce42247c32ef11309f5a543f37",
                            "spanId": "d847e20b2d8a8424",
                            "parentSpanId": "9018df20c4679396",
                            "traceState": "",
                            "name": "EventListenerTransaction.commit",
                            "kind": "SPAN_KIND_INTERNAL",
                            "startTimeUnixNano": 1746594278530446300,
                            "endTimeUnixNano": 1746594278530451200,
                            "attributes": [
                                {
                                    "key": "cluster",
                                    "value": {
                                        "stringValue": "xxx"
                                    }
                                },
                                {
                                    "key": "datacenter",
                                    "value": {
                                        "stringValue": "xxx"
                                    }
                                }
                            ],
                            "droppedAttributesCount": 0,
                            "droppedEventsCount": 0,
                            "droppedLinksCount": 0,
                            "status": {
                                "code": 0,
                                "message": ""
                            }
                        },
                        {
                            "traceId": "141ab4ce42247c32ef11309f5a543f37",
                            "spanId": "6987b4adc5e5da0c",
                            "parentSpanId": "9018df20c4679396",
                            "traceState": "",
                            "name": "EventListenerTransaction.commit",
                            "kind": "SPAN_KIND_INTERNAL",
                            "startTimeUnixNano": 1746594278530459000,
                            "endTimeUnixNano": 1746594278530465300,
                            "attributes": [
                                {
                                    "key": "cluster",
                                    "value": {
                                        "stringValue": "xxx"
                                    }
                                },
                                {
                                    "key": "datacenter",
                                    "value": {
                                        "stringValue": "xxx"
                                    }
                                }
                            ],
                            "droppedAttributesCount": 0,
                            "droppedEventsCount": 0,
                            "droppedLinksCount": 0,
                            "status": {
                                "code": 0,
                                "message": ""
                            }
                        },
                        {
                            "traceId": "141ab4ce42247c32ef11309f5a543f37",
                            "spanId": "566b755cae4c3573",
                            "parentSpanId": "9018df20c4679396",
                            "traceState": "",
                            "name": "InfinispanChangelogBasedTransaction.commit",
                            "kind": "SPAN_KIND_INTERNAL",
                            "startTimeUnixNano": 1746594278530491600,
                            "endTimeUnixNano": 1746594289854996000,
                            "attributes": [
                                {
                                    "key": "cluster",
                                    "value": {
                                        "stringValue": "xxx"
                                    }
                                },
                                {
                                    "key": "datacenter",
                                    "value": {
                                        "stringValue": "xxx"
                                    }
                                }
                            ],
                            "droppedAttributesCount": 0,
                            "droppedEventsCount": 0,
                            "droppedLinksCount": 0,
                            "status": {
                                "code": 0,
                                "message": ""
                            }
                        },
                        {
                            "traceId": "141ab4ce42247c32ef11309f5a543f37",
                            "spanId": "c4c4a70e36a3a765",
                            "parentSpanId": "9018df20c4679396",
                            "traceState": "",
                            "name": "SessionEventsSenderTransaction.commit",
                            "kind": "SPAN_KIND_INTERNAL",
                            "startTimeUnixNano": 1746594289855004700,
                            "endTimeUnixNano": 1746594289855008800,
                            "attributes": [
                                {
                                    "key": "cluster",
                                    "value": {
                                        "stringValue": "xxx"
                                    }
                                },
                                {
                                    "key": "datacenter",
                                    "value": {
                                        "stringValue": "xxx"
                                    }
                                }
                            ],
                            "droppedAttributesCount": 0,
                            "droppedEventsCount": 0,
                            "droppedLinksCount": 0,
                            "status": {
                                "code": 0,
                                "message": ""
                            }
                        }
                    ],
                    "instrumentationLibrary": {
                        "name": "org.keycloak.quarkus.runtime.integration.resteasy.KeycloakTracingCustomizer$StartHandler",
                        "version": "26.2.2"
                    }
                }
            ]
        }
    ]
}
```

</details>
