### ISSUE TITLE
Issue with SSL and `CertificatereloadManager` in Keycloak 26.2 when using Istio

### ISSUE THREAD

**Issue by muscionig** [keycloak/keycloak#39065]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

infinispan

### Describe the bug

I have updated `keycloak` to `26.2.0` and I am experiencing multiple log messages when `infinispan` is enabled in `Kubernetes`. 

These are the logs that repeat:

```
2025-04-17 15:18:08,907 WARN  [org.jgroups.protocols.TCP] (TcpServer.Acceptor[7800]-1,keycloak-5b99d748f8-ktjmj-55080) JGRP000006: 10.244.0.6:7800: failed accepting connection from peer SSLSocket[hostname=10.244.0.5, port=53525, Session(1744903073273|SSL_NULL_WITH_NULL_NULL)]: java.net.SocketException: Socket is closed
2025-04-17 15:18:12,262 INFO  [org.keycloak.infinispan.module.certificates.CertificateReloadManager] (TQ-Bundler-5,keycloak-5b99d748f8-ktjmj-55080) On certificate exception
2025-04-17 15:18:12,263 INFO  [org.keycloak.infinispan.module.certificates.CertificateReloadManager] () Reloading JGroups Certificate
2025-04-17 15:18:37,960 WARN  [org.jgroups.protocols.TCP] (TcpServer.Acceptor[7800]-1,keycloak-5b99d748f8-ktjmj-55080) JGRP000006: 10.244.0.6:7800: failed accepting connection from peer SSLSocket[hostname=10.244.0.5, port=51201, Session(1744903088908|SSL_NULL_WITH_NULL_NULL)]: java.net.SocketException: Socket is closed
2025-04-17 15:18:52,701 INFO  [org.keycloak.infinispan.module.certificates.CertificateReloadManager] (TQ-Bundler-5,keycloak-5b99d748f8-ktjmj-55080) On certificate exception
2025-04-17 15:18:52,702 INFO  [org.keycloak.infinispan.module.certificates.CertificateReloadManager] () Reloading JGroups Certificate
```

### Version

26.2.0

### Regression

- [x] The issue is a regression

### Expected behavior

While running `26.1.4` with the same exact configuration, `infinispan` initializes and works fine. I believe these `info` and SSL `warn` messages should not occur. I saw this: https://github.com/keycloak/keycloak/issues/37941, if this could be related in any way I'd be happy to open a quick fix to switch this to `debug`, however, the SSL `warn` does look like maybe the issue could be somewhere else. 

### Actual behavior

In `26.2.0` `infinispan` goes up, but there are warnings and info messages regarding expired certificates.

### How to Reproduce?

You can use the following:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak-temp
  labels:
    app: keycloak
spec:
  replicas: 2
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.2.0
          args: ["start"]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_HOSTNAME
              value: "localhost"
            - name: JAVA_OPTS_APPEND
              value: '-Djgroups.dns.query="keycloak-temp-headless.keycloak-temp.svc.cluster.local"'
            - name: 'KC_CACHE'
              value: 'ispn'
            - name: 'KC_CACHE_STACK'
              value: 'kubernetes'
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
  name: keycloak-temp-headless
  namespace: keycloak-temp
spec:
  selector:
    app: keycloak
  clusterIP: None
  type: ClusterIP
```

The same works without issues when setting `26.1.4`. The issue is reproducible for:
1. update in place from `26.1.4`
2. new deployment with `26.2.0`

### Anything else?

I checked the upgrading notes (https://www.keycloak.org/docs/latest/upgrading/index.html) and found this:

> If you are using a custom transport stack, this default behavior can be disabled by setting the option cache-embedded-mtls-enabled to false.

Let me know if this is relevant. 

If this is just a matter of switching `info` to `debug` I'll be happy to contribute.

**Comment by mposolda** [comment]
I am moving to SRE team for triage as this issue is related to infinispan and infrastructure.

**Comment by ahus1** [comment]
When scaling up Keycloak to two nodes, you need to store all data in an external shared database. 

With the example given above, you store it in a local H2 development database on each node, and one node will therefore not see the changes of the other node. 

Due to that, you will see a lot of problems. And there is also a warning "WARNING: Usage of the default value for the db option in the production profile is deprecated. Please explicitly set the db instead." at startup. 

One of the follow-up problems you see in your logs that starting with Keycloak 26.0 each instance will create a certificate to encrypt the cluster communication. As they don't share a database, they create distinct certificates, and therefore can't talk to each other. 

So TL;DR: 
* When trying out Keycloak with the internal database, use only a single instance
* If you want to use more than one instance, use an external database

I assume this resolves your issue. If this is the case, please close this issue.

**Comment by muscionig** [comment]
@ahus1 

Thank you for the detailed explanation. The reason I didn’t test with a database initially was that I assumed the issue would behave the same in both scenarios. In my actual setup, I’m using a `postgres` database, and `keycloak` is running within an `istio` service mesh.

Interestingly, I reproduced the same setup with and without `istio` (see attached [keycloak-base.txt](https://github.com/user-attachments/files/19915181/keycloak-base.txt)), and the issue does not occur. MTLS is enabled, but the Infinispan and failure ports are excluded from the mesh. I even attempted an in-place upgrade from `26.1.4` to `26.2.0`, but the problem still didn’t manifest.

I’ve attached the logs from the actual setup I’m debugging here: [logs-keycloak.log](https://github.com/user-attachments/files/19915367/logs-keycloak.log). Let me know if you notice anything unusual. That said, this seems to be a user-level issue rather than a bug, so feel free to close this. Hopefully, I’ll be able to figure out what’s going on.

**Comment by ahus1** [comment]
Thank you for providing the additional information about the Kubernetes resources. 

I found that with the setup you shared, Infinispan discovery doesn't work as expected as it is missing `publishNotReadyAddresses: true` from the headless service. Due to that, two nodes starting up in parallel won't see each other as they are both not ready yet. See [keycloak-base.txt](https://github.com/user-attachments/files/19955712/keycloak-base.txt) for an updated version. 

Once I changed that, the startup was smooth, and I didn't see the error messages.

Note that errors in a rolling update from 26.1.x to 26.2.x are expected as the old version doesn't know about the TLS encryption, while the new one does. Also, we don't support rolling updates between minor versions. We are currently looking into a full support for rolling updates in patch releases. Follow #38881 for the progress on this. 

We also don't recommend to use a Deployment for Keycloak, but a StatefulSet instead. With a StatefulSet Kubernetes will restart the Pods one by one, and this ensures that no session data for example for authentication sessions is lost during a rolling restart. 

All of our best practices are incorporated in to the Keycloak Operator, so maybe you want to give it a try. There are also several community Helm charts that include those configurations, although we don't maintain them. 

If you still see the error messages in a pure 26.2.x setup, please check that no other service is trying to connect itself to the Infinispan Port 7800. Any connection to that port with an invalid TLS certificate or no certificate would lead to a check if the certificate should be reloaded from the database.

**Comment by necipakca** [comment]
We are using istio and **mTLS enabled cluster wide**.
We are using operator for rolling-out KC.

When we upgrade the 26.2, we started to get the error : 

`{"timestamp":"2025-04-29T13:48:53.739480203Z","sequence":12440,"loggerClassName":"org.slf4j.impl.Slf4jLogger","loggerName":"org.jgroups.protocols.TCP","level":"WARN","message":"JGRP000006: 10.233.91.7:7800: failed accepting connection from peer SSLSocket[hostname=10.233.106.107, port=37810, Session(1745934497192|SSL_NULL_WITH_NULL_NULL)]: java.net.SocketException: Socket is closed","threadName":"TcpServer.Acceptor[7800]-1,central-keycloak-0-22692","threadId":104,"mdc":{},"ndc":"","hostName":"central-keycloak-0","processName":"/usr/lib/jvm/java-21-openjdk-21.0.7.0.6-1.el9.x86_64/bin/java","processId":1}`


and we have exclude the port 7800 from mTLS like : 

```
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: infinispan-allow-nomtls
spec:
  selector:
    matchLabels:
      app: keycloak
  portLevelMtls:
    "7800":
      mode: PERMISSIVE
```

and It works without any issue now.
