### ISSUE TITLE
Keep redirecting to /admin endpoint

### ISSUE THREAD

**Issue by rpartapsing** [keycloak/keycloak#39489]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

login/ui

### Describe the bug

I have installed keycloak helm chart [24.6.3](https://hub.docker.com/layers/bitnamicharts/keycloak/24.6.3/images/sha256-2079cfe0107eef4c1e07e5dd866c7ce4cf343dee242556c41c538c36754e7892)
using keycloak v26.2.2 after an upgrade from keycloak 24.0.5

with helm values
```
replicaCount: 3
resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 1Gi
postgresql:
  enabled: false
externalDatabase:
  existingSecret: {{ .Values.keycloakName }}-postgres-app
  existingSecretHostKey: host
  existingSecretPortKey: port
  existingSecretUserKey: username
  existingSecretDatabaseKey: dbname
  existingSecretPasswordKey: password
proxyHeaders: xforwarded
httpRelativePath: "/auth/"
auth:
  adminUser: admin
  existingSecret: {{ .Values.keycloakName }}
production: true
ingress:
  tls: true
  enabled: true
  ingressClassName: traefik
  pathType: Prefix
  hostname: "{{ .Values.subdomain }}.{{ .Values.platform.dnsDomain }}"
  path: "/"
  servicePort: http
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-https-redirect-permanent@kubernetescrd
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    endpoints:
      - path: '/auth/metrics'
    labels:
      prometheus-selector-target: system-prometheus
extraEnvVars:
  - name: KC_FEATURES
    value: "scripts"
```

So even with
proxyHeaders: xforwarded
httpRelativePath: "/auth/"

I keep getting redirected to the /admin endpoint. I tried entering
<MYHOSTNAME>
<MYHOSTNAME>/
<MYHOSTNAME>/auth
<MYHOSTNAME>/auth/

With my keycloak v24.0.5 all works fine. However there I have
```
proxy: edge
```

Anyone have an idea?

### Version

keycloak:26.2.2-debian-12-r0

### Regression

- [ ] The issue is a regression

### Expected behavior

Redirect to /auth endpoint when setting http-relative-path
https://github.com/bitnami/charts/blob/main/bitnami/keycloak/values.yaml#L236C1-L236C17

### Actual behavior

redirected to /admin endpoint

### How to Reproduce?

I have installed keycloak helm chart [24.6.3](https://hub.docker.com/layers/bitnamicharts/keycloak/24.6.3/images/sha256-2079cfe0107eef4c1e07e5dd866c7ce4cf343dee242556c41c538c36754e7892)
using keycloak v26.2.2 after an upgrade from keycloak 24.0.5

with helm values
```
replicaCount: 3
resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 1Gi
postgresql:
  enabled: false
externalDatabase:
  existingSecret: {{ .Values.keycloakName }}-postgres-app
  existingSecretHostKey: host
  existingSecretPortKey: port
  existingSecretUserKey: username
  existingSecretDatabaseKey: dbname
  existingSecretPasswordKey: password
proxyHeaders: xforwarded
httpRelativePath: "/auth/"
auth:
  adminUser: admin
  existingSecret: {{ .Values.keycloakName }}
production: true
ingress:
  tls: true
  enabled: true
  ingressClassName: traefik
  pathType: Prefix
  hostname: "{{ .Values.subdomain }}.{{ .Values.platform.dnsDomain }}"
  path: "/"
  servicePort: http
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-https-redirect-permanent@kubernetescrd
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    endpoints:
      - path: '/auth/metrics'
    labels:
      prometheus-selector-target: system-prometheus
extraEnvVars:
  - name: KC_FEATURES
    value: "scripts"
```

So even with
proxyHeaders: xforwarded
httpRelativePath: "/auth/"

I keep getting redirected to the /admin endpoint. I tried entering
<MYHOSTNAME>
<MYHOSTNAME>/
<MYHOSTNAME>/auth
<MYHOSTNAME>/auth/

With my keycloak v24.0.5 all works fine. However there I have
```
proxy: edge
```

Anyone have an idea?
