### ISSUE TITLE
Admin console not loading

### ISSUE THREAD

**Issue by cmonty14** [keycloak/keycloak#39703]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Describe the bug

I configured K8s with Istio Gateway ingress controller.
For deployment of keycloak I'm using bitnami helm chart.

Istio gateway is configured with SSL Termination.
And here's the virtual service manifest:
```
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: keycloak
  namespace: keycloak
spec:
  hosts:
    - "keycloak.sle-stage.devsys.net"  # Match the host in your Gateway
  gateways:
    - istio-system/sle-stage-gateway  # Reference your Gateway
  http:
    - match:
        - uri:
            prefix: "/"  # For keycloak.sle-stage.devsys.net, match all paths and port 80
      route:
        - destination:
            host: keycloak
            port:
              number: 80
```

### Version

26.2.4

### Regression

- [ ] The issue is a regression

### Expected behavior

Admin console with login

### Actual behavior

![Image](https://github.com/user-attachments/assets/048c9cdd-587a-4c3e-8774-d58d47065989)

### How to Reproduce?

Enter (pretty) URL in any browser.
