### ISSUE TITLE
Analyse the impact of the `podTemplate` field removal

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#40184]
### Description

* Analyze the impact of the breaking change on the Keycloak CR and the Operator upgrade process.
* Identify and prioritize common use cases that currently require the `podTemplate` field.
  * For the critical ones, create GH Issues for adding support for them as first class citizens in the Keycloak CR.

**Comment by ahus1** [comment]
One thing I would miss are JVM Options. I would use them for example for: 

* Adding explicit memory settings - I know we auto-assign the memory based on the Pod's memory limits, but IMHO this is not a one-thing-fits-all for very small and very large heaps.
* Enabling remote debugging
* [Cryostat](https://cryostat.io/) 
* Debug options `-Djdk.tracePinnedThreads=full`

**Comment by KyriosGN0** [comment]
Hey, i currently use the pod template spec to push some env var that are not related to keycloak (rather quarkus), it would be nice if the option to mount env var would be kept 
also the option to mount volumes would be nice

**Comment by stiaga** [comment]
I use that feature for additional environment variable, secret, configmaps and sidecar, so please add these fetatures to the operator before the removal.

**Comment by emouty** [comment]
We do use the podTemplate feature to apply a label ( `podTemplate.metadata.labels` ) on the pod so that our google cloud sql proxy operator can inject the cloud sql proxy sidecar on the pod.
We also use the service account field ( `podTemplate.spec.serviceAccountName` ) for the proxy to authenticate

**Comment by discostur** [comment]
We use `podTemplate` for init containers to download our custom theme for login pages, for example: 

```bash
  unsupported:
    podTemplate:
      spec:
        initContainers:
          - name: realm-ext-provider
            image: curlimages/curl
            imagePullPolicy: IfNotPresent
            command:
              - sh
            args:
              - -c
              - |
                # always download the latest theme jar file from the GitHub releases
                mkdir -p /shared/providers
                ASSET_ID=$(curl -s -H "Authorization: token ${GITHUB_PAT}" "https://api.github.com/repos/XXX/releases/latest" | grep -B 5 '"name": "keycloak-theme-for-kc-all-other-versions.jar"' | grep '"id":' | head -1 | sed 's/.*"id": *\([0-9]*\).*/\1/')
                curl -L -f -S -H "Authorization: token ${GITHUB_PAT}" -H "Accept: application/octet-stream" -o /shared/providers/keycloak-theme.jar "https://api.github.com/repos/XXX/releases/assets/${ASSET_ID}"
            env:
              - name: GITHUB_PAT
                valueFrom:
                  secretKeyRef:
                    name: keycloak-credentials
                    key: github_pat
            volumeMounts:
              - name: shared-data
                mountPath: /shared
        containers:
          - name: keycloak
            volumeMounts:
              - name: shared-data
                mountPath: /opt/keycloak/providers
                subPath: providers
        volumes:
          - name: shared-data
            emptyDir: {}

```

**Comment by davesteinberg** [comment]
I use `podTemplate` to make Keycloak use `verify-full` SSL mode for PostgreSQL, which verifies the server certificate using a trusted root certificate, protecting against man-in-the-middle attacks. I put that root certificate in a ConfigMap and mount it into the Keycloak container:

```
  unsupported:
    podTemplate:
      spec:
        containers:
        - env:
          - name: KC_DB_URL_PROPERTIES
            value: ?sslmode=verify-full&sslrootcert=/mnt/postgresql/root.crt
          volumeMounts:
          - mountPath: /mnt/postgresql
            name: postgresql-config
        volumes:
        - configMap:
            name: keycloak-db-root.crt
          name: postgresql-config
```

I would love to see first-class support for this in the operator so I could move away from the unsupported `podTemplate`.

**Comment by cfahrni** [comment]
> I use `podTemplate` to make Keycloak use `verify-full` SSL mode for PostgreSQL, which verifies the server certificate using a trusted root certificate, protecting against man-in-the-middle attacks. I put that root certificate in a ConfigMap and mount it into the Keycloak container:
> 
> ```
>   unsupported:
>     podTemplate:
>       spec:
>         containers:
>         - env:
>           - name: KC_DB_URL_PROPERTIES
>             value: ?sslmode=verify-full&sslrootcert=/mnt/postgresql/root.crt
>           volumeMounts:
>           - mountPath: /mnt/postgresql
>             name: postgresql-config
>         volumes:
>         - configMap:
>             name: keycloak-db-root.crt
>           name: postgresql-config
> ```
> 
> I would love to see first-class support for this in the operator so I could move away from the unsupported `podTemplate`.

There should be no need to use the `podTemplate` section in your case.
We use Keycloak in combination with CNPG and this is how we enable the `verify-full` SSL mode. 
```
spec:
  db:
    vendor: postgres
    host: postgresql-rw
    database: app
    usernameSecret:
      name: postgresql-app
      key: username
    passwordSecret:
      name: postgresql-app
      key: password
  truststores:
    postgresql-ca:
      secret:
        name: postgresql-ca
  additionalOptions:
    - name: db-url-properties
      value: "?sslmode=verify-full&sslrootcert=/opt/keycloak/conf/truststores/secret-postgresql-ca/ca.crt"
```
