### ISSUE TITLE
[Keycloak CI] - Windows: local maven repository error

### ISSUE THREAD

**Issue by miquelsi** [keycloak/keycloak#40339]
### Before reporting an issue

- [x] I have read and understood the above terms for submitting issues, and I understand that my issue may be closed without action if I do not follow them.

### Area

ci

### Describe the bug

```
Run ./.github/scripts/download-node-tooling.sh 22.14.0 10.4.1
  ./.github/scripts/download-node-tooling.sh 22.14.0 10.4.1
  shell: C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail {0}
  env:
    MAVEN_ARGS: -B -nsu -Daether.connector.http.connectionMaxTtl=25
    SUREFIRE_RERUN_FAILING_COUNT: 2
    SUREFIRE_RETRY: -Dsurefire.rerunFailingTestsCount=2
    MAVEN_OPTS: -Xmx1536m
    JAVA_HOME: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\21.0.7-6.0\x64
    JAVA_HOME_21_X64: C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\21.0.7-6.0\x64
Downloading node-v22.14.0-linux-x64.tar.gz...
mkdir: cannot create directory '/c/Users/runneradmin/.m2/repository': File exists
```

https://github.com/keycloak/keycloak/actions/runs/15524058469/job/43701209512

### Version

latest

### Regression

- [ ] The issue is a regression

### Expected behavior

-

### Actual behavior

-

### How to Reproduce?

-
