### ISSUE TITLE
Update Keycloak on Kubernetes Getting Started guide

### ISSUE THREAD

**Issue by amirensit** [keycloak/keycloak#8859]
### Describe the bug

The ingress ressource file for [this ](https://www.keycloak.org/getting-started/getting-started-kube)guide is not up to date.

Instead of this: 
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: keycloak
spec:
  tls:
    - hosts:
      - KEYCLOAK_HOST
  rules:
  - host: KEYCLOAK_HOST
    http:
      paths:
      - backend:
          serviceName: keycloak
          servicePort: 8080

```
It should be like this: 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
spec:
  tls:
    - hosts:
      - KEYCLOAK_HOST
  rules:
  - host: KEYCLOAK_HOST
    http:
      paths:
      - path: /
        pathType: Prefix 
        backend:
          service:
            name: "keycloak"
            port: 
              number: 8080


```

### Version

The same as for the guide

### How to Reproduce?

Follow this guide of keycloak on kubernetes
https://www.keycloak.org/getting-started/getting-started-kube
