### ISSUE TITLE
LDAPS Bind test fails with SSLHandshakeException while LDAP connection test works

### ISSUE THREAD

**Issue by Kagee** [keycloak/keycloak#9313]
### Describe the bug

We are using the jboss/keycloak-docker. We are trying to connection to a LDAP (LDAP+TLS, port 636, not STARTTLS) AD verified by a sertificate signed by a itnernal CA. We import the CA certificates using the `X509_CA_BUNDLE`-argument, and this appears to work as both `keycloak_tls_truststore_password` and `keycloak_tls_truststore_file` is written to `/opt/jboss/keycloak/bin/.jbossclirc`

When testing a `ldaps://ad.example.com` URL in the setup for User Federation the `Test connection` test works, while `Test authentication` fails with a TLS/PKI error:
```
16:34:13,688 ERROR [org.keycloak.services] (default task-13) KC-SERVICES0055: Error when authenticating to LDAP: simple bind failed: ad.example.com:636: javax.naming.CommunicationException: simple bind failed: ha
voc.cert.no:636 [Root exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested
 target]
...
```

### Version

15.1.1 (jboss/keycloak:15.1.1)

### Expected behavior

Either
* The authentication test to not fail on a TLS error since the connection test works
or
* The connection fail to fail with the same TLS error as the authentication test

### Actual behavior

The authentication test fails with a TLS error that was not expected since the connection test worked.

### How to Reproduce?

Use a non-public CA for a LDAPS endpoint, import the CA certificate, and setup and test the connection in keycloack.

**Comment by kevinlul** [comment]
I've been able to reproduce a similar error, but not on WildFly Docker images from version 15, 16, or 17, regardless of whether TLS is enabled for Keycloak. I only got it to happen on the new Quarkus images, and I think that is because the keystore isn't being built in the entrypoint from `X509_CA_BUNDLE` like the [legacy distribution](https://github.com/keycloak/keycloak-containers/blob/main/server/tools/x509.sh#L60-L68).

**Comment by AlexeiKlimenko** [comment]
What are the further steps, how to resolve it?

**Comment by ykuksenko** [comment]
The following seems to work for me.

Remove the following environment variables:
```
KC_HTTPS_TRUST_STORE_FILE
KC_HTTPS_TRUST_STORE_PASSWORD
KC_SPI_TRUSTSTORE_FILE_FILE
KC_SPI_TRUSTSTORE_FILE_PASSWORD
```
Add these build steps with a PEM CA chain as the last stage of your container build
```
USER root
COPY ca.crt /etc/pki/ca-trust/source/anchors/ca.crt
RUN /usr/bin/update-ca-trust
USER keycloak
```
Use `KC_HTTPS_CERTIFICATE_FILE`, `KC_HTTPS_CERTIFICATE_KEY_FILE` variables for configuring inbound TLS connections.

With this process the following steps work as expected for me:
- Testing the LDAPS connection
- Testing authentication
- Syncing users


This is on quarkus/keycloak 18.

**Comment by ahus1** [comment]
@mposolda - **TL;DR: could we eliminate `ldapsOnly` as an option and keep only `always` and `never`?**

I understand that there are two ways to connect to LDAP securely: LDAP with STARTTLS (then the URL starts with `ldap://...`) and LDAP with TLS (then the URL starts with `ldaps://...`).

When triaging this issue, I found that the option `ldapsOnly` is broken, as it is never used in the code, and thereby never activates the truststore.

I wonder if the LDAP Truststore configuration could be simplified to `Never` and `Always`, as I don't see the case for configuring this conditionally for STARTLS: If a user wants to the truststore for either LDAPS with TLS, they choose either yes or no. The same if they have chosen LDAP with STARTTLS.

**Comment by rubendevgo** [comment]
Hi @ahus1, did you manage to find a simpler way to solve this problem using dockerfile for quarkus?

**Comment by ahus1** [comment]
@rubendevgo - depending on your setup, you might want to use the truststore as described here https://www.keycloak.org/server/keycloak-truststore and then configure LDAP to use the truststore "always".

**Comment by rubendevgo** [comment]
@ahus1  I'm using the following setup for my dockerfile: 
`FROM quay.io/keycloak/keycloak:latest as builder

WORKDIR /opt/keycloak/

COPY rootca.cer /opt/keycloak/ldap.cer
USER root

RUN keytool -import -trustcacerts -alias ldapcert -file /opt/keycloak/ldap.cer -trustcacerts -keystore /usr/lib/jvm/java-17-openjdk-17.0.7.0.7-1.el9_1.x86_64/lib/security/cacerts -storepass changeit -noprompt

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/ /opt/keycloak/


ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]`
And this is my dockercompose file:
` keycloak:
    container_name: keycloak
    build:
      context: .
      dockerfile: Dockerfile.keycloak

    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: root
      KC_DB_USERNAME: postgres
      KC_DB_SCHEMA: public
      KC_PROXY: passthrough
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KC_HOSTNAME_STRICT_BACKCHANNEL: 'false'
      KC_HTTP_ENABLED: 'true'
      PROXY_ADDRESS_FORWARDING: 'true'
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      KC_METRICS_ENABLED: 'true'
      KC_HTTP_PORT: 8890
      KC_SPI_TRUSTSTORE_FILE_FILE: /usr/lib/jvm/java-17-openjdk-17.0.7.0.7-1.el9_1.x86_64/lib/security/cacerts
      KC_SPI_TRUSTSTORE_FILE_PASSWORD: changeit
      KC_HTTPS_PROTOCOLS: TLSv1.2
      KC_HTTPS_CIPHER_SUITES: ECDHE-RSA-AES256-SHA384
     
    ports:
       - "8890:8890"
    depends_on:
      - postgres`
  Does this envs  KC_SPI_TRUSTSTORE_FILE_FILE and  KC_SPI_TRUSTSTORE_FILE_PASSWORD work the same that this "bin/kc.[sh|bat] start --spi-truststore-file-file=myTrustStore.jks --spi-truststore-file-password=password --spi-truststore-file-hostname-verification-policy=ANY"?

**Comment by rubendevgo** [comment]
@ahus1 I'm using the following setup for my dockerfile:
```dockerfile
FROM quay.io/keycloak/keycloak:latest as builder

WORKDIR /opt/keycloak/

COPY rootca.cer /opt/keycloak/ldap.cer
USER root

RUN keytool -import -trustcacerts -alias ldapcert -file /opt/keycloak/ldap.cer -trustcacerts -keystore /usr/lib/jvm/java-17-openjdk-17.0.7.0.7-1.el9_1.x86_64/lib/security/cacerts -storepass changeit -noprompt

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:latest
COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start"]
``` 


And this is my dockercompose file:
```
keycloak:
  container_name: keycloak
  build:
    context: .
    dockerfile: Dockerfile.keycloak
  restart: always
  environment:
    KC_DB: postgres
    KC_DB_URL_HOST: postgres
    KC_DB_URL_DATABASE: keycloak
    KC_DB_PASSWORD: root
    KC_DB_USERNAME: postgres
    KC_DB_SCHEMA: public
    KC_PROXY: passthrough
    KEYCLOAK_ADMIN_PASSWORD: admin
    KEYCLOAK_ADMIN: xxxxxxxx
    KC_HOSTNAME_STRICT_BACKCHANNEL: 'false'
    KC_HTTP_ENABLED: 'true'
    PROXY_ADDRESS_FORWARDING: 'true'
    KC_HOSTNAME_STRICT: 'false'
    KC_HOSTNAME_STRICT_HTTPS: 'false'
    KC_METRICS_ENABLED: 'true'
    KC_HTTP_PORT: 8890
    KC_SPI_TRUSTSTORE_FILE_FILE: /usr/lib/jvm/java-17-openjdk-17.0.7.0.7-1.el9_1.x86_64/lib/security/cacerts
    KC_SPI_TRUSTSTORE_FILE_PASSWORD: changeit
    KC_HTTPS_PROTOCOLS: TLSv1.2
    KC_HTTPS_CIPHER_SUITES: ECDHE-RSA-AES256-SHA384
  
  ports:
     - "8890:8890"
  depends_on:
    - postgres
``` 

Does this envs KC_SPI_TRUSTSTORE_FILE_FILE and KC_SPI_TRUSTSTORE_FILE_PASSWORD work the same that this "bin/kc.[sh|bat] start --spi-truststore-file-file=myTrustStore.jks --spi-truststore-file-password=password --spi-truststore-file-hostname-verification-policy=ANY"?

**Comment by hmlnarik** [comment]
As agreed with @stianst directly, we will remove the ldapsOnly option.

**Comment by remyd1** [comment]
Hi @yashjain027 ,

If that can help, after digging seriously into this issue and solutions given here and elsewhere ([1](https://github.com/keycloak/keycloak/issues/11360), [2](https://github.com/keycloak/keycloak/issues/21935), [3](https://stackoverflow.com/questions/68122316/keycloak-federation-configuration-keystore-trustore-error-when-initializing-the), [4](https://stackoverflow.com/questions/52674979/keycloak-ssl-setup-using-docker-image), that may not be related to that current issue), I have been able to have a working LDAPS connection between keycloak and our AD.

I had 2 main problems : permissions on the `/opt/jboss/keycloak/standalone/configuration/keystore`directory which was mounted from the host, and the content of the truststore itself.
Indeed, after checking logs with `KEYCLOAK_DEBUG: debug` I saw that truststore is generated at boot in that directory from java cacerts.

So, I changed the following given solution from @ykuksenko to:

```
FROM jboss/keycloak
USER root
COPY ca.crt /etc/pki/ca-trust/source/anchors/ca.crt
RUN /usr/bin/update-ca-trust
USER jboss
```

and used that image instead of the official jboss image; I also changed the cert directory permissions on the host to `777` (...).

Every other solutions did not work for me. I disabled STARTTLS and enabled "Always" option to use the truststore SPI.

**Comment by hmlnarik** [comment]
> Every other solutions did not work for me. I disabled STARTTLS and enabled "Always" option to use the truststore SPI.

@remyd1 The `STARTTLS` behaviour was broken in 22.0.0 which is fixed in the current nightly build and will be part of Keycloak 22.0.4, and this could have caused the issues you encountered. Apologies for the inconvenience. The MSAD connection now works as long as you use `ldap://` (not `ldaps`) protocol with `StartTLS`, and also via `ldaps://` without StartTLS which you apparently use now.

> They didn't even included in patch notes, ges it was only a bug after all:)

@yashjain027 This was announced [in the release notes](https://www.keycloak.org/docs/latest/release_notes/index.html#ldaps-only-truststore-option-removed) since this is significant user-facing change. Is there any other place you would like to see it in?

**Comment by pberswe** [comment]
I am having these issues as well and cannot get ldaps working for keyckloak -> MSAD

Although this may be a solution 
```
/FROM jboss/keycloak
USER root
COPY ca.crt /etc/pki/ca-trust/source/anchors/ca.crt
RUN /usr/bin/update-ca-trust
USER jboss
```
there must be an option to manipulate the release prod image from quay to do this as well when you just want to deploy the image as released, building your own image can´t be the only option?

in general adding cert and ca cert could be much more simplified and documented.

**Comment by ahus1** [comment]
@pberswe - to in certificates, consider mounting a secret into the container. If you are using the Keycloak Operator, the only way you can do this today is using the `unsupported` part of the CR and provide those as part of the `podTemplate`. 

There are already issues for this, and you might want to upvote them: #12722, #23742, #9784

**Comment by pberswe** [comment]
@ahus1  thank you for your reply, we use a helm chart to deploy the quay image to k3s edge clusters
```
   spec:
      containers:
      - args: {{- toYaml .Values.keycloak.keycloak.args | nindent 8 }}
        env:
...
        - name: KC_PROXY
          value: {{ quote .Values.keycloak.keycloak.env.kcProxy }}
        - name: KC_HEALTH_ENABLED
          value: {{ quote .Values.keycloak.keycloak.env.kcHealthEnabled }}
        - name: KC_METRICS_ENABLED
          value: {{ quote .Values.keycloak.keycloak.env.kcMetricsEnabled }}
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: {{ quote .Values.keycloak.keycloak.env.kcHostnameStrictHttps }}
        - name: KC_HTTP_ENABLED
          value: {{ quote .Values.keycloak.keycloak.env.kcHttpEnabled }}
        - name: KC_LOG_LEVEL
          value: {{ quote .Values.keycloak.keycloak.env.kcLogLevel }}
        - name: KC_DB
          value: {{ quote .Values.keycloak.keycloak.env.kcDb }}
        - name: KC_DB_URL_HOST
          value: {{ quote .Values.keycloak.keycloak.env.kcDbUrlHost }}
        - name: KC_DB_URL_DATABASE
          value: {{ quote .Values.keycloak.keycloak.env.kcDbUrlDatabase }}
        - name: KC_HOSTNAME
          value: {{ quote .Values.keycloak.keycloak.env.kcHostname }}
        # - name: KC_FILE
        #   value: {{ quote .Values.keycloak.keycloak.env.kcImportFile }}
...
        volumeMounts:
        - name: {{ .Values.keycloak.volumename }} #The name(key) value must match pod volumes name(key) value 
          mountPath: {{ .Values.keycloak.mountpath}}
        - name: {{ .Values.keycloak.tlsvolumename }} #The name(key) value must match pod volumes name(key) value 
          mountPath: {{ .Values.keycloak.tlsmountpath}}
        image: {{ .Values.keycloak.keycloak.image.repository }}:{{ .Values.keycloak.keycloak.image.tag | default .Chart.AppVersion }}
...
# values.yaml
    image:
      repository: quay.io/keycloak/keycloak
      tag: 22.0.4
```
This way we can use gitops to manage deployments but don´t have to build and maintain a docker image. We don´t have dependable internet so this keeps our payload minimal and the clusters can keep trying to sync the deployments based on availability. The challenge is that i cannot get keycloak to trust our root CA :/ i mount a keystore using a configmap atm and start kc using
```
    - start --spi-truststore-file-file=/opt/keycloak/data/import/mountpoint/keycloaktrust.jks --spi-truststore-file-password=Password --spi-truststore-file-hostname-verification-policy=ANY

```
i can see the certs being loaded in the debug log but no luck connecting over LDAPS
