### ISSUE TITLE
Custom themes as extensions not loaded/available

### ISSUE THREAD

**Issue by MBauerDC** [keycloak/keycloak#9347]
### Describe the bug

When packaging and deploying a custom theme as a `jar` as described in the [Server Development Guide](https://www.keycloak.org/docs/latest/server_development/#deploying-themes), the extension gets deployed, but the theme never gets loaded / never becomes available for selection. 

This is reproducible locally with a minimal example described below.

### Version

v16.1.0 & v16.0.0 & v.15.1.1

### Expected behavior

The theme is available for selection in the admin console.

### Actual behavior

The theme never shows up for selection, despite being deployed correctly.

### How to Reproduce?

1. Create a directory for testing, and in this directory create another directory named `theme-test` for developing a minimal example (we will call this minimal example theme simply `minimal`). In the `theme-test` subdirectory, create the following subdirectories:

* META-INF/
* themes/minimal/login/

2. In the `META-INF/` subdirectory, create a file called `keycloak-themes.json` with the following content: 
```
{
    "themes": [{
        "name": "minimal",
        "types": ["login"]
    }]
}
```

3. In the `themes/minimal/login/` subdirectory, create a file called `theme.properties` with the following content:
```
parent=base
import=common/keycloak
```
4. in the root directory for our testing, create a file named `docker-compose.yaml` with the following content:

```
version: "3.2"
volumes:
  postgres_data:
      driver: local
services:
  postgres:
      image: postgres
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  keycloak:
      image: quay.io/keycloak/keycloak:16.1.0
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: admin
      ports:
        - 8080:8080
      depends_on:
        - postgres
      volumes:
        - type: bind
          source: ./theme-test/themes/minimal
          target: /opt/jboss/keycloak/themes/minimal

```
5. Bring up the application via `docker-compose up -d`, access the admin console and observe that a theme named `minimal` is selectable in the realm-settings under `Themes`.

6. Execute `docker-compose down`.

7. In the `theme-test` directory, execute `jar cfM minimal.jar ./*` to package the theme as a jar (alternative methods e.g. without the `M` option or via `mvn package` with an appropriate `pom.xml` produce the same end-result).

8. Execute `jar tvf ./minimal.jar` to verify the contents - the output should look similar to the following:
```
     0 Mon Dec 27 17:07:44 CET 2021 META-INF/
    82 Mon Dec 27 17:07:44 CET 2021 META-INF/keycloak-themes.json
     0 Mon Dec 27 17:05:24 CET 2021 themes/
     0 Mon Dec 27 17:05:26 CET 2021 themes/minimal/
     0 Mon Dec 27 17:06:20 CET 2021 themes/minimal/login/
    35 Mon Dec 27 17:06:20 CET 2021 themes/minimal/login/theme.properties
```

9. Modify the the `docker-compose.yaml` file's `volumes` section to contain the following:
```
    - type: bind
      source: ./theme-test/minimal.jar
      target: /opt/jboss/keycloak/standalone/deployments/minimal.jar
```      
10. Execute `docker-compose up -d`, then check the logs to confirm that the jar has been deployed successfully. Eventually, the log should contain an entry similar to:

```
keycloak_1  | 17:15:40,282 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 33) WFLYSRV0010: Deployed "minimal.jar" (runtime-name : "minimal.jar")
```

11. Visit and enter the admin console to observe that no custom theme named `minimal` is selectable as a login theme in the realm settings (or on the client-level)

    

### Anything else?

This is currently preventing deployment to production for a project I am working on for a customer (deployed via operator, thus only `jar`-deployment possible).

I have created an enhancement-request for logging of theme-extension [here](https://github.com/keycloak/keycloak/issues/9338), as well as a stackoverflow question [here](https://stackoverflow.com/questions/70421293/deploying-custom-keycloak-theme-with-operator-v15-1-1-v16-0-0)

Locally, I have also modified (and bind-mounted) the `standalone.xml` file to disable theme-caching as specified in the documentation.

Furthermore, I have tried themes in various more or less minimal configurations with different packaging methods (jar with or without the `M` option as well as via `mvn package` in the same way as [keycloakify](https://github.com/InseeFrLab/keycloakify/blob/913a6c3ec39ed145cae9c0b0de5a7cce2a120d51/src/bin/build-keycloak-theme/generateJavaStackFiles.ts) does it), on versions 15.1.1, 16.0.0 both locally and online via keycloak-operator - as well 16.1.0 (only locally). 

In the operator-managed deployment, I have also tried creating a configmap with the jar as its contents and mounting this configmap (as described [here](https://stackoverflow.com/questions/65922655/how-to-use-custom-themes-on-keycloak-operator-deployment-on-kubernetes), except without the `subPath`, which is not supported).
