### ISSUE TITLE
Alway doesn't have the header "Access-Control-Allow-Origin"

### ISSUE THREAD

**Issue by lenguyenkhoi21** [keycloak/keycloak#9416]
### Describe the bug

I use Spring Boot 2.6.2 with KeyCloak, using Keycloak adapter Spring Security. 

Config im application.yaml

```
keycloak:
  realm: zuzul
  auth-server-url: http://localhost:8080/auth/
  ssl-required: none
  resource: zuzul-product-private
  credentials:
    secret: E5bbXHj5RINdG3JTz7ud0PfnJxrECGm0
  use-resource-role-mappings: true
  bearer-only: true
  cors: true
  cors-max-age: 0
  cors-allowed-methods: POST, PUT, DELETE, GET, OPTIONS
  cors-allowed-headers: X-Requested-With, Content-Type, Authorization, Origin, Accept, Access-Control-Request-Method, Access-Control-Request-Headers

```

I setup keycloaklike this 
![image](https://user-images.githubusercontent.com/25551366/148488064-de8eefcd-02b2-49c6-8d6c-0f203a6412b5.png)
but when I dummy test in js client, it still get something wrong here:
![image](https://user-images.githubusercontent.com/25551366/148488218-ce99ef98-76f6-452a-bc23-0af87895d3d1.png)

my code in js client:
```
const jwt = 'eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJFT2doUXFRLWdLU0V4WnRTM3RwTXk3TjdNSjJ0Q2hpUUk1TXBVT1hqdTdvIn0.eyJleHAiOjE2NDE1MjY2MTMsImlhdCI6MTY0MTUyNjMxMywianRpIjoiNjhmMmM2ZDAtNDczMS00MGVjLThhNTYtNmY1ZGI3ZmQyMzFkIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2F1dGgvcmVhbG1zL3p1enVsIiwiYXVkIjpbInJlYWxtLW1hbmFnZW1lbnQiLCJ6dXp1bC1wcm9kdWN0LXByaXZhdGUiLCJicm9rZXIiLCJhY2NvdW50Il0sInN1YiI6Ijc0YjkyNDBmLTM2ODgtNDQzNS1hOGEyLWFjYmQ3ZmM4ZDU5NSIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFkbWluLWNsaSIsInNlc3Npb25fc3RhdGUiOiJlNWNhZmFlZC05MGE3LTRlZWYtODMxMy00NWY3ZDA3ZWExNjgiLCJhY3IiOiIxIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtenV6dWwiLCJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsicmVhbG0tbWFuYWdlbWVudCI6eyJyb2xlcyI6WyJ2aWV3LWlkZW50aXR5LXByb3ZpZGVycyIsInZpZXctcmVhbG0iLCJtYW5hZ2UtaWRlbnRpdHktcHJvdmlkZXJzIiwiaW1wZXJzb25hdGlvbiIsInJlYWxtLWFkbWluIiwiY3JlYXRlLWNsaWVudCIsIm1hbmFnZS11c2VycyIsInF1ZXJ5LXJlYWxtcyIsInZpZXctYXV0aG9yaXphdGlvbiIsInF1ZXJ5LWNsaWVudHMiLCJxdWVyeS11c2VycyIsIm1hbmFnZS1ldmVudHMiLCJtYW5hZ2UtcmVhbG0iLCJ2aWV3LWV2ZW50cyIsInZpZXctdXNlcnMiLCJ2aWV3LWNsaWVudHMiLCJtYW5hZ2UtYXV0aG9yaXphdGlvbiIsIm1hbmFnZS1jbGllbnRzIiwicXVlcnktZ3JvdXBzIl19LCJ6dXp1bC1wcm9kdWN0LXByaXZhdGUiOnsicm9sZXMiOlsiVEVTVF9ST0xFIl19LCJicm9rZXIiOnsicm9sZXMiOlsicmVhZC10b2tlbiJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsInZpZXctYXBwbGljYXRpb25zIiwidmlldy1jb25zZW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJtYW5hZ2UtY29uc2VudCIsImRlbGV0ZS1hY2NvdW50Iiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJwcm9maWxlIGVtYWlsIiwic2lkIjoiZTVjYWZhZWQtOTBhNy00ZWVmLTgzMTMtNDVmN2QwN2VhMTY4IiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhZG1pbi1zeXN0ZW0ifQ.NZRWSp4xs4JW2EusX_sraS6bz0KD0d3cd9-DuMhPMgHk4XbQbRnve0OTsH9_6mhq0uWqRhgIwOI_levMGYs4yQ9319cy5TRarz6zW-wFFebaGzcKT2d-34n_vGcIekttkCP7gnedTtQCG5Mlxhc-HIadReYiEQwSY0qUVyBbZMKwVfSdwuNKxmN0GymV4QJ9N7vto95M7q6IL2F_oQbwhIUyvXJ22Uie31sg-y96MSy_YDWXKwfeWViZTF1_ju-Jz-SCMeuOm8GVu9v6imQ_hdcAeqsbhe8DsKauj3hhyS9fm7kQgdWsU1Bty4aAVCn7irsuhhBzp51lQMJJFzbiGg'
            fetch('http://localhost:7940/zuzul-product-private/v1/service_info', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${jwt}`
                },
                mode: 'cors',
                body: JSON.stringify({
                    name: '4',
                    description: '4',
                    version: '34'
                }),
                redirect: 'follow'
            })
                .then(response => response.json())
                .then(data => console.log(data));
```

### Version

15.1 

### Expected behavior

Have header "Access-Control-Allow-Origin" and no cors bug

### Actual behavior

Doesn't have
