### ISSUE TITLE
Memory leak in keycloak

### ISSUE THREAD

**Issue by BiatBang** [keycloak/keycloak#9647]
### Describe the bug

We have 2 applications under 2 clients and one app A is sending heartbeats to the other B. A is using client secret as credentials.

In `application.yaml`
```
keycloak:
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}
```

For AuthzClient:
```
HttpClient httpClient = new HttpClientBuilder().disableTrustManager().build();
Configuration configuration = new Configuration(
            kcProperties.getAuthServerUrl(),
            kcProperties.getRealm(),
            kcProperties.getResource(),
            kcProperties.getCredentials(),
            httpClient
    );
AuthzClient.create(configuration);
```

For getting access token:
```
AccessTokenResponse accessTokenResponse = authzClient.obtainAccessToken();
```

For sending heartbeat:
```
HttpRequest request = HttpRequest.newBuilder(initHeartbeatUri())
        .header(CONTENT_TYPE, APPLICATION_JSON)
        .header(ACCEPT, APPLICATION_JSON)
        .header(AUTHORIZATION, "Bearer " + accessToken)
        .POST(HttpRequest.BodyPublishers.ofString(objectMapper.writeValueAsString(status)))
        .build();
HttpResponse<String> response = httpClient.send(request, BodyHandlers.ofString());
```

In keycloak client settings:
```
Access Token Lifespan: 30min
Client Session Max: 20min
Client Session Idle: 5min
```

After a period of time, memory usage of keycloak goes up continuously. When we dump the jvm heap, we found 2 kinds of objects keep increasing: 
Previous:
```
num     #instances         #bytes  class name (module)
5:        164364        6574560  org.infinispan.container.entries.MortalCacheEntry
9:        164352        2629632  org.keycloak.models.sessions.infinispan.entities.ActionTokenValueEntity
```
After 1 hr:
```
4:        264762       10590480  org.infinispan.container.entries.MortalCacheEntry
8:        264750        4236000  org.keycloak.models.sessions.infinispan.entities.ActionTokenValueEntity
```

Is there any configs I'm not doing correctly? Or is there any memory leak in keycloak? Look forward to any idea. Thanks a lot.

### Version

16.0.1

### Expected behavior

Memory does not increase continuously and gets released periodically.

### Actual behavior

Memory usage increases continuously.

**Comment by hmlnarik** [comment]
Could you share a bit more of the code?
What flow do you use?

**Comment by BiatBang** [comment]
We are using standard flow.

For keycloak config in `application.yml`:
```
keycloak:
  realm: test-realm
  cors: true
  cors-max-age: 1000
  cors-allowed-methods: "POST, PUT, DELETE, GET, PATCH"
  cors-exposed-headers: "Access-Control-Allow-Origin"
  resource: test-resource
  auth-server-url: ${KEYCLOAK_SCHEMA}://${KEYCLOAK_IP}:${KEYCLOAK_PORT}/auth/
  ssl-required: external
  confidential-port: 10043
  connection-pool-size: 20
  public-client: false
  disable-trust-manager: true
  allow-any-hostname: true
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET}
  principal-attribute: preferred_username
  bearer-only: true
```

For authzClient:
```
public AuthzClient authzClient(KeycloakSpringBootProperties kcProperties) throws Exception {
    HttpClient httpClient = new HttpClientBuilder().disableTrustManager().build();

    Configuration configuration = Configuration(
            kcProperties.getAuthServerUrl(),
            kcProperties.getRealm(),
            kcProperties.getResource(),
            kcProperties.getCredentials(),
            httpClient
    );
    configuration.setDisableTrustManager(true);
    configuration.setAllowAnyHostname(true);

    return AuthzClient.create(configuration);
}
```

For refreshing access token periodically:
```
Timer timer = new Timer();
timer.scheduleAtFixedRate(new TimerTask() {
  @Override
  public void run() {
    AccessTokenResponse accessTokenResponse = authzClient.obtainAccessToken();
    this.accessToken = accessTokenResponse.getToken();
  }
}, refreshSec * 900, refreshSec * 900);
timer.scheduleAtFixedRate(new TimerTask() {
  @Override
  public void run() {
    AccessTokenResponse accessTokenResponse = authzClient.obtainAccessToken();
    this.accessToken = accessTokenResponse.getToken();
  }
}, sessionMaxAge * 950, sessionMaxAge * 950);
```

For sending heartbeat with accessToken:
```
HttpRequest request = HttpRequest.newBuilder(heartbeatUri)
        .header(CONTENT_TYPE, APPLICATION_JSON)
        .header(ACCEPT, APPLICATION_JSON)
        .header(AUTHORIZATION, "Bearer " + this.accessToken)
        .POST()
        .build();
HttpResponse<String> response = httpClient.send(request, BodyHandlers.ofString());
```

Please let me know if you need anything else.
