### ISSUE TITLE
Add truststore options to Keycloak CR

### ISSUE THREAD

**Issue by vmuzikar** [keycloak/keycloak#9784]
* Add support to the Keycloak CRD for mounting Secrets with a custom truststore.
* Needs to be PEM (probably needs to be converted to Java Keystore either by the operator or the image).
* Configure Keycloak to use it.
* We should consider unifying the Keycloak truststore SPI and Quarkus truststore
* Possibly requires changes at the server side too

Mapped options:
* https-trust-store-file
* https-trust-store-password
* https-trust-store-type (hardcoded to PEM for now)
* spi-truststore-file-file
* spi-truststore-file-password

CR structure:
```yaml
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: example-kc
spec:
  http:
    truststoreFileSecret:
      name: my-secret-with-trustore
      key: my-key
    truststorePasswordSecret:
      name: my-secret-with-trustore
      key: my-key
...
```

Related tasks:
* #9780
* #14396

Follow-up tasks:
* #10117

**Comment by shawkins** [comment]
Replaced by #24798 - there may need to be a fresh issue to cover configuring infinispan's key / truststore.

**Comment by ozbillwang** [comment]
So any reason this request is not planned?

in RHBK (redhat build of keycloak), it does support truststore (https://access.redhat.com/solutions/7051525) 

```
additionalOptions:
  - name: spi-truststore-file-file
    secret:
      name: truststore-example-secret
      key: path
  - name: spi-truststore-file-password
    secret:
      name: truststore-example-secret
      key: password
unsupported:
  podTemplate:
    spec:
      containers:
        - volumeMounts:
            - name: truststore
              mountPath: /opt/truststore                                                                                                                                                                         
      volumes:
        - name: truststore
          secret: 
            secretName: truststore-file-secret
```

the problem here is, RHBK , Redhat Build of Keycloak, (**apiVersion: k8s.keycloak.org/v2alpha1**) has limited CRD support: The current RHBK operator only ships **Keycloak** and **KeycloakRealmImport** CRDs under k8s.keycloak.org/v2alpha1. Crucial CRDs like **KeycloakRealm, KeycloakClient, and KeycloakUser are missing.** The setting , include ldap, clients, realm, etc, are not persistant, so keycloak CRD will reset the settings , these setting, done via keycloakrealmImport are gone. It is very annoying. 

<img width="807" height="404" alt="Image" src="https://github.com/user-attachments/assets/07348da7-ac2d-4fd4-a2e5-51b9a56cb5c8" />

So we have to back to RHSSO (**apiVersion: keycloak.org/v1alpha1**) , but unlucky, truststore doesn't suport yet

### Update

Finally, made it works with rhsso operator

```
apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: rhsso-keycloak
  labels:
    app: sso
  namespace: aap
spec:
  externalAccess:
    enabled: true
  instances: 1
  # Add environment variables for truststore
  keycloakDeploymentSpec:
    experimental:
      volumes:
        items:
          - mountPath: /etc/x509/ca
            name: ca-bundle-pem
            secrets:
              - ca-bundle-pem
      env:
        - name: X509_CA_BUNDLE
          value: "/etc/x509/ca/ca-bundle.pem"
```

Note: Make sure there is no any comments in the .pem file. the scirpt in offical redhat keycloak image, `/opt/eap/bin/launch/openshift-x509.sh` is not good enough. It can't handle the .pem file  with command `csplit` properly.
